### ISSUE TITLE
C_CPP: File Management/Handling

### ISSUE THREAD

**Issue by sneha2001sinha** [girlscript/winter-of-contributing#1004]
<hr>

## Description 📜
`Add description here`

I want to contribute on the following using video:
- File Management/Handling in C
<hr>

`Add type of contrib here`

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by Suvraneel** [comment]
Duplicate #914

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by sneha2001sinha** [comment]
> This issue [has been assigned](https://github.com/girlscript/winter-of-contributing/issues/1004#issuecomment-922498035) to @sneha2001sinha! It will become unassigned if it isn't closed within 12 days. A maintainer can also add the **pinned** label to prevent it from being unassigned.

/assign
