### ISSUE TITLE
Flutter : Widgets Documentation

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#1007]
<hr>

## Description 📜

One is supposed to add documentation on-
1. What are Widgets?
2. Types & examples of widgets and their description.
<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter)

<hr>

**Comment by supriya-045** [comment]
Please refer to this[ colab ](https://colab.research.google.com/drive/1uYnw83zjqLsbLuJHjOiQ6ga3eUSUm9je?usp=sharing)and review my documentation work on assigned issue ,  should I raise a PR?

**Comment by PranavMasekar** [comment]
@ViAsmit i want to contribute in this issue and i also written /assign but its not assigning the issue to me so pls check it once

**Comment by ViAsmit** [comment]
@supriya-045 please make a PR , and then ask your mentor to review it...if there is any fault he will let you know.

**Comment by ViAsmit** [comment]
@PranavMasekar if someone is already assigned, you can't be assigned that issue.. Also....we will add new issues by today..
