### ISSUE TITLE
Frontend With Framework - React Devtools 

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#1013]
<hr>

## Description 📜

Contributors are required to include a procedure to Install Reat-DevTools, which should cover questions like:-
What is React-DevTools?
Why it is needed?
How to install it?
How to open React-DevTools in the browser? (you can make GIF, which shows how to open this)
etc....

And also mention that we will learn, how to use it further in the upcoming topics.

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (React, Angular, Vue)

<hr>

**Comment by CSAURABH** [comment]
@anandhu720 can I work on this issue (Documentation)

**Comment by paras-saxena11** [comment]
i want to contribute plz assign me work

**Comment by Safwan310** [comment]
The bot is not working huh :(

**Comment by Durva15** [comment]
@anandhu720 I want to work on this issue

**Comment by aryan-mehta05** [comment]
@anandhu720 can I work on this, please?

**Comment by aryan-mehta05** [comment]
\assign

**Comment by anandhu720** [comment]
already assigned bro
