### ISSUE TITLE
Flutter: Stateful Widget

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#1017]
<hr>

## Description 📜

One is supposed to add documentation on-
1. What are stateful Widgets?
2. Use of Stateful Widgets.
3. Syntax of Stateful Widget.
4. Description of Keywords in the syntax with example.
<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter)

<hr>

**Comment by arcAman07** [comment]
Can I also take this issue?

**Comment by Harshit9557** [comment]
Can i take this issue?
