### ISSUE TITLE
C/CPP Install C++ on different OS

### ISSUE THREAD

**Issue by ayushmaan02** [girlscript/winter-of-contributing#1024]
<hr>

## Description 📜
- I will be providing documentation on downloading and setting up C/C++ for different OS.
- Installation of C/C++ for Windows and Mac 
- VS code download and set up for C/C++. 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by VandanaKumari18** [comment]
/assign

i will provide a detailed information about the different platform where we can code in C++/C .
i will make a step by step explaination of VS code installation.
i will provide several links for installation helps.
images will also be attached with the details. 
installation on mac os will also be explained.

**Comment by Kanishk0412** [comment]
I have already Create an issue sorry.

**Comment by ayushmaan02** [comment]
> I have already Create an issue sorry.

Regarding the same topic?

**Comment by Saviour1001** [comment]
Closing this issue as the PR got merged ! You can open new issues !
