### ISSUE TITLE
Data Science with Python : Data Analysis using Scikit Learn

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1027]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Data Analysis using Scikit Learn. Tutorial to Data Analysis using Scikit Learn and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualization

Mentors Assigned : [Kareem Negm](https://github.com/Kareem-negm) / [Ishika Kesarwani](https://github.com/ishikkkkaaaa)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by preestine** [comment]
Hello!
I would like to work on this issue in the form of documentation. I would begin with a brief introduction and and eventually progress by performing analysis using the scikit-learn library on the dataset which I obtained from Kaggle.
Name: Preeti Chaudhari
Batch: 8
Sr.No.: 268

**Comment by prathimacode-hub** [comment]
@preestine, this issue is assigned to you for documentation.

**Comment by Kareem-negm** [comment]
Hello, the mentor here for any help

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Data Science with Python 
Batch-19  
Serial No-787 
Issue Number-1027
Contribution Approaches-use of scikit learn to do data analysis, scikit learn in big data analysis

**Comment by Kareem-negm** [comment]
hello @preestine , please if you made any PR mention this issue

**Comment by preestine** [comment]
@Kareem-negm Hello Sir,I am facing a lot of difficulties to make the PR. I have followed all the tutorials,but I am still clueless about how to make the PR. I have made the project of my issue in Google Colab and I have the dataset. If possible, please help me out.

**Comment by Kareem-negm** [comment]
Don't worry it's easy, just finish your task on google colab  and download your notebook 
after that follow this article or video to make your first [contribution ](https://www.dataschool.io/how-to-contribute-on-github/)
or you can see this [video](https://www.youtube.com/watch?v=Aj4Bo8-yTT0)
if you have any questions please let me know
```
if == you still can't make your PR:
    redownload git 
else:
    tell me 
```

**Comment by preestine** [comment]
@Kareem-negm Thanks a lot for your kind words and support. I might need some time to make the PR,because I am following your instructions and tutorials. I am slow learner,I take time to learn new things. :(
Your guidance and consideration is appreciated.

**Comment by preestine** [comment]
@Kareem-negm Hello sir,Kindly review my PR.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
