### ISSUE TITLE
Front End: CSS Libraries

### ISSUE THREAD

**Issue by GenMech** [girlscript/winter-of-contributing#1030]
<hr>

## I have a good hold on CSS and want to contribute 📜

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [x] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by GenMech** [comment]
@praveenscience

**Comment by paras-saxena11** [comment]
hey i want to contribute ?
what to do please assign

**Comment by rishabh2030** [comment]
please assign me this issue i will work on it and Definitely make it amazing

**Comment by GenMech** [comment]
@code-reaper08 I have created this issue but github bot not assigning me can you pls assign it to me
