### ISSUE TITLE
Data Science with Python : Principal Component Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1034]
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Principal Component Analysis. Tutorial to Principal Component Analysis and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Nithin](https://github.com/Nithin-Reddy-02) / [Arya Patel](https://www.github.com/AryaPatel1111)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Vishaka830** [comment]
### Vishaka Saxena
**Serial No**: 901
**Batch:** 3
**Issue Number**:1034
**Type:** Documentation
**Approach:** 

- Definition, 
- Objectives, 
- Uses
-  and its methods
Please assign this issue to me @prathimacode-hub 
###

**Comment by prathimacode-hub** [comment]
Sorry @Vishaka830, I had created a thread for all the contirbutors in discord who haven't been assigned to any issue to come up with their very own issue as it's their first contribution. So you can put up a message in a thread created with your name, issue topic and your github profile. So that I could consider and create an issue accordingly. @Vishaka830

**Comment by aswinikalyan30** [comment]
Aswini Kalyan

Serial No: 406
Batch: 11
Issue Number:1034
Type: Documentation
Github Profile: @aswinikalyan30
Approach:

-Definition,
-Objectives, 
-Use cases and implementation

**Comment by prathimacode-hub** [comment]
Issue assigned to @aswinikalyan30 for documentation

**Comment by prathimacode-hub** [comment]
@Vishaka830, there are more issues arriving. This is done according to thread provided in discord.

**Comment by prathimacode-hub** [comment]
@Vishaka830, do you like to work on this issue?

**Comment by Vishaka830** [comment]
@prathimacode-hub yes ma'am.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Vishaka830 for documentation.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation of the issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do video on this issue.
my approach: a detailed explanation.

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for video contribution
