### ISSUE TITLE
Android-Java: 9.0 How to work with audio and video files in Android Studio.

### ISSUE THREAD

**Issue by Arjun2905** [girlscript/winter-of-contributing#105]
Description : 
1. How to store audio and video files in your android project inside Android Studio.
2. How you can play your audio and video files within your application.

**Comment by Arjun2905** [comment]
@Rohit-2602 Can I start work on this issue ?
I have created this issue.
This is also important to know .

**Comment by sitamadex11** [comment]
@Arjun2905 Bro it little bit advanced topic. We should first cover all basics of android. You can cover it some days later.

**Comment by Arjun2905** [comment]
@VikasPandey121 please share on thoughts on it.

**Comment by VikasPandey121** [comment]
Yes sure, Here we are trying to build a repo that can be helpful from beginners to the advanced level Android-Developers. I am referring it with Module 9 of [Road-Map](https://docs.google.com/document/d/137rcHXwjCMY8rSD06IwtJzAEMS1g4_G8VJEggRwhjGQ/edit?usp=sharing).

Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 9.0 for instance `9.0 Android Multimedia`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `9.0.1`, `9.0.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by VikasPandey121** [comment]
@Arjun2905 I have assigned this issue to you, You can start your contribution with it.

**Comment by Arjun2905** [comment]
@Rohit-2602 Please go through my PR.  https://github.com/girlscript/winter-of-contributing/pull/2434
