### ISSUE TITLE
C_CPP: SETS IN C++ STL

### ISSUE THREAD

**Issue by yogeshkumar-1234** [girlscript/winter-of-contributing#1050]
<hr>

## Description 📜
    
    This documentation will explain all about sets,unordered_sets and multisets in STL

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by sumitmukharjeeeeee** [comment]
Assign Me

**Comment by yogeshkumar-1234** [comment]
Please assign this issue to me

**Comment by angle361** [comment]
Please assign this issue to me.

**Comment by kalyanirb12** [comment]
I would like to contribute by documentation pls assign it to me.

**Comment by Suvraneel** [comment]
@angle361 @KhushiBhambri @afridihannan @kalyanirb12 
doc has been assigned to the author... choose among : audio & video

**Comment by Saviour1001** [comment]
Closing this issue as #1738 got merged !
