### ISSUE TITLE
Introduction to OOPs

### ISSUE THREAD

**Issue by girija0707** [girlscript/winter-of-contributing#1051]
<hr>

## Description 📜

Explaining polymorphism in c++  via documentation format
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by sumitmukharjeeeeee** [comment]
Assing me

**Comment by shreya024** [comment]
assign

**Comment by girija0707** [comment]
please assign me this issue I would love to work on it under documentation part 
/assign

**Comment by SouravKr2001** [comment]
I am interested plz assign it to me
