### ISSUE TITLE
DSA_in_C

### ISSUE THREAD

**Issue by pilipi-puu-puu** [girlscript/winter-of-contributing#1054]
<hr>

## Description 📜
There will be multiple problems on DSA using C, explaining via documentation.

<hr>

## Domain of Contribution 📊

- [x] C
- [x] Competitive Programming
- [x] DSA

<hr>

**Comment by harshsri28** [comment]
Don't create issues by your own ,as these issues not going to count.

**Comment by pilipi-puu-puu** [comment]
Ok, thank you for informing.

**Comment by pilipi-puu-puu** [comment]
@Saviour1001 please assign this issue to me.

**Comment by Saviour1001** [comment]
This is a fairly vast topic. Write a specific data structure or algorithm you are aiming to implement in C. I am closing this issue for now. You can open a new one. Choose a specific topic and assign. The bots are up to help you !!
