### ISSUE TITLE
CSS Animations in Documentation

### ISSUE THREAD

**Issue by priyanka001tech** [girlscript/winter-of-contributing#1056]
<hr>

## Description 📜

Different kind of animations in css
Different technique to do animations of different kind using Examples

<hr>

## Domain of Contribution 📊

- [X] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by sumitmukharjeeeeee** [comment]
Assign Me

**Comment by aritrabanerjee11** [comment]
sdf

**Comment by Tharunya07** [comment]
Hey! I want to work on this. Can you assign the issue to me?
