### ISSUE TITLE
Frontend: The CSS Box Model

### ISSUE THREAD

**Issue by reeyah** [girlscript/winter-of-contributing#1057]
<hr>

## Description 📜

Explain the CSS Box model.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by gsk-007** [comment]
I am interested in workin on this issue. Batch 6 frontend.

**Comment by asppanda12** [comment]
I am interested in workin on this issue. Batch 6 frontend.

**Comment by cenacrharsh** [comment]
/assign
I will work on documentation
Batch-5 Frontend with HTML and CSS
