### ISSUE TITLE
Python 1.8 knowing concept of loop in python 

### ISSUE THREAD

**Issue by subhoshreep** [girlscript/winter-of-contributing#106]
i wish to contribute on this topic
subhoshree pattnaik
batch 1

**Comment by KeerthanaPravallika** [comment]
I want to contribute to this issue 
Keerthana Pravallika Samudrala 
Batch 4

**Comment by priyanshuc4423** [comment]
please assign me
Priyanshu
Batch  4

**Comment by harmankaler2000** [comment]
Hey! I would like to contribute to this issue
Harmandeep Kaur Kaler
Python batch - 4

**Comment by deepeshaburse** [comment]
Hey! I would like to contribute to this issue. 
Deepesha Burse
DS with Python, Batch 4

**Comment by Yugal41735** [comment]
I wan to know since it does not have GWOC tag so would it not get counted for GWOC'21 contribution?
