### ISSUE TITLE
Android-Java : 3.2 Spinners in Java

### ISSUE THREAD

**Issue by g-animesh02** [girlscript/winter-of-contributing#1060]
1. Introduction to spinners.
2. XML and Java files(Example Project) for spinners
3. Material Design for spinners

**Comment by g-animesh02** [comment]
Mentor/Supervisor can you please assign me this issue.
Name - Animesh Gupta
batch - 8

**Comment by Rohit-2602** [comment]
yes, you can start working on this @g-animesh02
