### ISSUE TITLE
DS-R: 2.3.DOC Introduction - Using Rstudio

### ISSUE THREAD

**Issue by micepram** [girlscript/winter-of-contributing#1064]
<hr>

## Description 📜

In this issue, you need to work on the documentation efforts in the "Introduction" section under the "Using Rstudio" subsection. Please ensure that you document in detail.

<hr>

## Domain of Contribution 📊

- [x] Datascience with R

<hr>

## Instructions ✔

* Kindly make a README going over the subtopic.
* Changes should be made under **Datascience_With_R** branch only and push your PR to the same.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

<hr>

**Comment by ravireddy07** [comment]
I would like to work on this

**Comment by micepram** [comment]
Sure @ravireddy07! All the best!

**Comment by micepram** [comment]
Hi @ravireddy07 what's the progress on the issue?

**Comment by ravireddy07** [comment]
Hey @micepram, 
i'm working on it. I'll make an update soon.

**Comment by ravireddy07** [comment]
@micepram raised the PR, Please review it.
