### ISSUE TITLE
Data Science with Python : Image to Pencil Sketch Image using Python

### ISSUE THREAD

**Issue by tjanhvi** [girlscript/winter-of-contributing#1067]
<hr>

## Description 📜

Basically, Firstly read the image in RBG format and then convert it to a grayscale image. This will turn an image into a classic black and white photo. Then the next thing to do is invert the grayscale image also called negative image, this will be our inverted grayscale image. Inversion can be used to enhance details. Then we can finally create the pencil sketch by mixing the grayscale image with the inverted blurry image

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by aaryan078** [comment]
can you please assign me this issue

**Comment by snehasharma76** [comment]
I will like to work on this issue. Please assign me this.

**Comment by harichandana1406** [comment]
Can you please assign me this issue? if no one is working on this.

**Comment by m0hit-kumar** [comment]
I want to contribute to this issue :
Name-Mohit Kumar
Domain-Data Science with Python
Batch-4
Issue Number- 1067
Contribution Approaches-
Import Libraries and image
Convert to Grey Image.
apply different methods to Invert Image 
blurring effects
inverted blur image

**Comment by tjanhvi** [comment]
As i already told to assign me 
Please assign me asi already started on working on it

**Comment by NiharikaDinesh** [comment]
Please assign me to this issue

**Comment by Tanya205** [comment]
Hi, I would like to contribute to this issue.
Tanya Malhotra
ML Batch - 6
Sr No. - 889
https://github.com/Tanya205
Documentation

**Comment by tjanhvi** [comment]
Please assign me this issue

**Comment by divya-ganesh** [comment]
I would like to contribute to this issue
Divya Ganesh
DSWP batch-2
Documentation

**Comment by Nay907** [comment]
Hey! I am Nayanika Mishra
Batch- 9
I would like to contribute to this issue.

**Comment by AkritiAgarwal09** [comment]
Hi I would like to contribute to this issue
Please assign me this issue

Akriti Agarwal
DSWP batch -15
Serial No : 505

**Comment by prathimacode-hub** [comment]
This issue is not as it's not informed and no proper details. @tjanhvi
