### ISSUE TITLE
VS Code vs Turbo C 

### ISSUE THREAD

**Issue by VandanaKumari18** [girlscript/winter-of-contributing#1068]
<hr>

## Advantage and Disadvatage of Turbo C and VS Code And which one will more preferable.what will be choosen between Turbo C and VS code and why ? everything about features.
📜

- [x] C/CPP

<hr>

**Comment by VandanaKumari18** [comment]
i would like to work on this issue created by me . each and everything that a person should know before starting with C/CPP will be explained in this . for freshers as well as intermediates. freshers must have a knowledge of this thing to get started with the domain.

**Comment by Aryamanz29** [comment]
@VandanaKumari18  Don't add the wrong labels
Thanks

**Comment by VandanaKumari18** [comment]
> @VandanaKumari18 Don't add the wrong labels
> Thanks

okay sir . 
should i start working on this issue ? or you will assign this to me first then i should start ?
