### ISSUE TITLE
Android-Java 3.3: EventListener in Android

### ISSUE THREAD

**Issue by SB2318** [girlscript/winter-of-contributing#1071]
<hr>

## Description 📜
* A small description of the EventListener interface
* Basic event listener and their properties, how can we use them
* EventListener corresponding to a particular View
I hope this issue is helpful for a beginner, who want to  work on their project

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Java)
- [x] Open Source

<hr>

**Comment by SB2318** [comment]
I want to work  on this issue

**Comment by SB2318** [comment]
> I want to work on this issue, Please assign it to me, whenever it is available

**Comment by sumitmukharjeeeeee** [comment]
\assign documentation

**Comment by Rohit-2602** [comment]
@SB2318 you can start working on it. and change the issue title to 
"Android-Java 3.3: EventListener in Android"

**Comment by SouravKr2001** [comment]
I want to work on this issue, Please assign it to me(documentation)
