### ISSUE TITLE
Python: What is Automation?

### ISSUE THREAD

**Issue by PhantomANaz** [girlscript/winter-of-contributing#1087]
<hr>

## Description 📜

Automation is the most fun topic of Python. Like, take, for example, you've to check your Facebook messages, or checking the speed of your CPU regularly, or in my case, checking the email every two hours which for me is quite boring. But if I write a particular code and ask it to implement in every two hours, then EUREKA!!! That's what automation is, to make a process to operate automatically.

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

**Comment by Praannjaal** [comment]
Name : Pranjal Mittal
I would like to be assigned this issue

**Comment by Ash-KODES** [comment]
batch 5 python

**Comment by Pmair20** [comment]
I would like to work on this issue (documentation part along with code sample)
Name: Pritish Mair
Python Batch 1

**Comment by adityabisoi** [comment]
@Randrita Is the mentor for this issue. Please reach out to her in case of queries.

**Comment by roopali-1** [comment]
@adityabisoi i would like to work on this issue as audio contribution .. can you please assign this to me as audio ...
