### ISSUE TITLE
DSA 1.1.1 Arrays Introduction( STL, implementation etc)

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#109]
## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by adityaraj079** [comment]
Hey I would like to work on this issue.

**Comment by Sneha-0308** [comment]
Hey, I would like to work on this!

**Comment by Vedika-Agrawal** [comment]
@pjdurden sir, Please assign this issue to me, I would like to work on this issue under GWOC.

**Comment by mansisingh2803** [comment]
Hey I would like to work on this . Please assign me this issue

**Comment by ananyaagrawal23** [comment]
Hey! I would like to work on this. Please assign this issue to me.

**Comment by Subhradeep10** [comment]
@Akshat-2002-coder Go for it. Assigned to you

**Comment by Akshat-2002-coder** [comment]
> @Akshat-2002-coder Go for it. Assigned to you

thanks for assigning this to me .
can u plz guide me how to proceed further as I am a beginner to open source

**Comment by Subhradeep10** [comment]
@Akshat-2002-coder Well contruibuting is easy I will say that later or you can talk about that in Discord also, First say do you have prerequisite knowledge on Array (Arrays Introduction( STL, implementation etc)?

- If No, First read about the Arrays from GFG or W3Schools and gain proper knowledge in it.

- If Yes, Go and prepare a Documentation on Readme (.md) extension.Basic Introduction about the topic , Some code example and line by line explaination of the code. Don't do blindly copy paste otherwise we have to gave you plagiarism and the issue will be solved by someone else. 

And if you face any issue. You can ask my directly in the discord

All the best🚀

**Comment by Akshat-2002-coder** [comment]
yes I have prerequisite knowledge on array.
thx for guiding me

**Comment by jaissumi1402** [comment]
@pjdurden sir, Please assign this issue to me, I would like to work on this issue

**Comment by cookieg13** [comment]
I would really love to contribute on this issue! I have all the pre requisite knowledge for Arrays. Can you please assign me this work?

**Comment by Akshat-2002-coder** [comment]
I have already  started preparing documentation on it🙂.

**Comment by cookieg13** [comment]
> I have already started preparing documentation on it🙂.

Oh alright, I didnt read the previous comments, all the best!

**Comment by KislaySingh10** [comment]
Hey, I would like to work on this issue.

**Comment by kalyanirb12** [comment]
I would like to work on this

**Comment by JRManasa** [comment]
I would love to work on this

**Comment by uditkatyal** [comment]
I would like to contribute on STL(arrays).

**Comment by Shruti-Subu** [comment]
can i contribute in this?

**Comment by EktaAgrawal** [comment]
Hello sir, I have a keen interest in this and wanted to contribute. kindly assign me

**Comment by russapal** [comment]
Hello Sir, I would like to work in this issue. Please kindly assign it to me.
