### ISSUE TITLE
OpenSource : 6.5 Android in Open Source

### ISSUE THREAD

**Issue by Harshil-Jani** [girlscript/winter-of-contributing#1092]
<hr>

## Description 📜

Android is on nearly 3 billion devices. So, This Issue will contains points regarding Impact of Android in Open Source.
Points planned to cover : 
- Breif about Android history and Linux Kernal
- About AOSP (Android Open Source Project)
- License and Legalization on Android Souce code.
- Role of Google for Android
- How you can contribute?

<hr>

## Domain of Contribution 📊

- [x] Open Source

### NOTE 👇
Please put your doc `inside section-6` if not present create new folder `section-6`

<hr>

## Mode of contribution
- [x] Documentation
- [ ] Audio
- [ ] Video

**Comment by Aryamanz29** [comment]
@pspiagicw  Assigned , Happy Learning 🎉🎉

**Comment by pspiagicw** [comment]
PR issued!
