### ISSUE TITLE
MERN_React: 3.1 Class and Functional Components and their lifecycles

### ISSUE THREAD

**Issue by v-rohan** [girlscript/winter-of-contributing#1093]
# Instructions 
## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## What are components?

-  What are class components, and their properties?
-  What are functional components, and their advantages over class based components?
-  Introduction to hooks and basic data fetching using the axios/fetch APIs using the ```useEffect``` hook in functional components and ```componentDidMount``` function in class based components.

Please refrain from plagiarising.

# Task 

- [ ] Documentation

**Comment by GyaniRoman23** [comment]
Hey @v-rohan!! I would like to work with the Documentation part of this issue.

**Comment by SrijanShovit** [comment]
Hello @v-rohan I would like to work on Documentation part of this issue.

**Comment by AdityaPandey03** [comment]
Hello @v-rohan, I would like to work on the documentation part of this issue

**Comment by AdityaPandey03** [comment]
\assign

**Comment by v-rohan** [comment]
@SrijanShovit @AdityaPandey03 @AdityaPandey03 

If assigned to all three can you collaborate and make the respective video presentation together as well?

**Comment by AdityaPandey03** [comment]
> @SrijanShovit @AdityaPandey03 @AdityaPandey03
> 
> If assigned to all three can you collaborate and make the respective video presentation together as well?

 I am not so comfortable in carrying out the video presentation...would like to take up the documentation part

**Comment by SrijanShovit** [comment]
> @SrijanShovit @AdityaPandey03 @AdityaPandey03
> 
> If assigned to all three can you collaborate and make the respective video presentation together as well?



> @SrijanShovit @AdityaPandey03 @AdityaPandey03
> 
> If assigned to all three can you collaborate and make the respective video presentation together as well?

Sorry ,but same case with me. I can do the documentation part but not comfortable with video presentation.

**Comment by GyaniRoman23** [comment]
@v-rohan I did the first comment and if the first come first serve rule is being followed here, I request you to please take me into consideration with the documentation part of the issue.

**Comment by v-rohan** [comment]
> @v-rohan I did the first comment and if the first come first serve rule is being followed here, I request you to please take me into consideration with the documentation part of the issue.

Fine I'm assigning this issue to you, @GyaniRoman23

**Comment by manjeetdhayal** [comment]
hey @GyaniRoman23 I have assigned it to you, you can work on documentation part.

**Comment by GyaniRoman23** [comment]
Thank You @manjeetdhayal :)

**Comment by GyaniRoman23** [comment]
Hey @v-rohan Just wanted to know that should I include how a Hook is created or not as you have mentioned to provide only an introduction to them ?
