### ISSUE TITLE
Python: Web scraping

### ISSUE THREAD

**Issue by nakshatra-garg** [girlscript/winter-of-contributing#1096]
<hr>
@adityabisoi @prathimacode-hub 

## Description 📜

Web scraping is the process of using bots to extract content and data from a website.

To extract data using web scraping with python, the following steps are done:
- Find the URL that you want to scrape
- Inspecting the Page
- Find the data you want to extract
- Write the code
- Run the code and extract the data
- Store the data in the required format 

<hr>

## Domain of Contribution 📊

- [x] Python

<hr>

**Comment by cybot-des** [comment]
I would like to work on this issue (documentation part along with code sample) 
Name: Pooja Deshpande
Python Batch 1

**Comment by dhruti29** [comment]
I would like to work on this issue (documentation part)
Name: Dhruti Gandhi
Python Batch 1

**Comment by Pmair20** [comment]
I would like to work on this issue (documentation part along with code sample)
Name: Pritish Mair
Python Batch 1

**Comment by adityabisoi** [comment]
@Randrita Is the mentor for this issue. Please reach out to her in case of queries.
