### ISSUE TITLE
2.1. What is Learning? Why Machine Learning works?

### ISSUE THREAD

**Issue by nakshatra-garg** [girlscript/winter-of-contributing#1097]
<hr>
@abhisheks008 

## Description 📜

Explain What is Learning? 
Why Machine Learning works?

<hr>

## Domain of Contribution 📊
- [x] Machine Learning
<hr>

**Comment by snehasharma76** [comment]
I will like to work on this. Please assign me this issue.

**Comment by imcoza** [comment]
I would like to work on this issue. Kindly assign me this issue.
