### ISSUE TITLE
Break/Continue keywords in C/CPP

### ISSUE THREAD

**Issue by KartikChinda** [girlscript/winter-of-contributing#1098]
<hr>

## Description 📜

Creating documentation and code for explaining the use of the break and the continue keyword in C. 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by shreya024** [comment]
Can i Do this?

**Comment by Aman-Deshpande** [comment]
Can I work on this issue.
Aman Deshpande
Batch 11

**Comment by JayashreeSadarhalli** [comment]
\assign document

**Comment by Zuber8040** [comment]
\assign Document

**Comment by KartikChinda** [comment]
@Suvraneel sir please assign this issue to me since the self assign bot isn't working. Thanks!

**Comment by am-dusky** [comment]
@KartikChinda  You can check issue number 960. It is on break and continue in C/CPP and had been already assigned to me

**Comment by KartikChinda** [comment]
@am-dusky my bad, I did search the issue up before creating this and for some reason it didn't show your issue. I'll close this up!
