### ISSUE TITLE
Open Source : 6. 4 Information about WINE and Proton

### ISSUE THREAD

**Issue by pspiagicw** [girlscript/winter-of-contributing#1102]
<hr>

## Description 📜

WINE  and Proton are technologies developed to run Windows Software in Linux.

Topics to cover
 - Wine and Proton history and development
 - Current Status and ProtonDB
 - Limitations
 - Use in industry (Steam , Steam Deck , Google Stadia)
 - How can you contribute

<hr>

### NOTE 👇
Please put your doc `inside section-6` if not present create new folder `section-6`

- [x] Open Source

<hr>
Thanks to @Aryamanz29 for this oppurtunity to open a issue.

**Comment by Aryamanz29** [comment]
@itsbittoosharma  Assigned, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
Any updates ??

**Comment by itsbittoosharma** [comment]
Will be doing a pr by tonight

**Comment by Aryamanz29** [comment]
Cool @itsbittoosharma

**Comment by itsbittoosharma** [comment]
Please checkout my PR #2122
