### ISSUE TITLE
OpenSource : 6.3 Information about Vi/Vim and Emacs.

### ISSUE THREAD

**Issue by pspiagicw** [girlscript/winter-of-contributing#1103]
<hr>

## Description 📜
Vim and Emacs are the most hackable and customizable text editors out there.Both developed in the 1980's they are compared to each other and have resulted in a Editor War over the years.

Points to include
- Their birth
- Their style of editing documents and ways to customize
- Features included in respective editors.
- Current status

<hr>

### NOTE 👇
Please put your doc `inside section-6` if not present create new folder `section-6`

## Domain of Contribution 📊

- [x] Open Source

<hr>
Thanks to @Aryamanz29 for giving me this oppurtunity of creating this issue.

**Comment by divyanshuss** [comment]
would like to contribute @Aryamanz29

**Comment by Aryamanz29** [comment]
@divyanshuss  Sur, Happy Learning 🎉🎉

**Comment by divyanshuss** [comment]
@Aryamanz29 Thank you.
