### ISSUE TITLE
Open Source : 6.16 `Language Server Protocol`

### ISSUE THREAD

**Issue by pspiagicw** [girlscript/winter-of-contributing#1104]
<hr>

## Description 📜

Language Server Protocol is a new technology used by many Open Source Editors and developed in collabration with Microsoft.
It enables autocompletion, goto-definition and other intelligent code functions to be offloaded to a dedicated server for the language currently being written.
Topics to Cover
- Origin of LSP
- How does it work
- LSP Servers for different languages
- Current status in multiple editors

<hr>

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.16_Language_Server_Protocol.md`

## Domain of Contribution 📊

- [x] Open Source

<hr>
Thanks to @Aryamanz29 for giving me this oppurtunity to open this issue.

**Comment by Binita-tech** [comment]
\assign Document

**Comment by Aryamanz29** [comment]
@Binita-tech  Sure , Happy docs 🎉

**Comment by Aryamanz29** [comment]
Any updates ?? @Binita-tech

**Comment by Binita-tech** [comment]
I had term 2 exam, I have started working on it now.

**Comment by Aryamanz29** [comment]
@Binita-tech  Any updates ?

**Comment by Binita-tech** [comment]
I have made document, I am learning git command. Soon , I will make pull request.

**Comment by Aryamanz29** [comment]
@Binita-tech  Any updates??

**Comment by ELLIPSIS009** [comment]
@Aryamanz29 can i work on this ?

**Comment by Aryamanz29** [comment]
@Abhay3008  Any updates?

**Comment by Abhay3008** [comment]
I'll be making PR by tomorrow
