### ISSUE TITLE
Open Source : 6.1 Open Source in Space!

### ISSUE THREAD

**Issue by pspiagicw** [girlscript/winter-of-contributing#1108]
<hr>

## Description 📜

Open Source has reached even Space . With the recent Ingenuity quadcopter flying in Mars , totally powered by Linux software wise. It is time we explore use of Open Source in Space Exploration

Topics that can be covered
- Advantages
- Open Source Tools for Space and Aerospace research.
- Open Source used in SpaceX and NASA
- Open Source on Mars( The newest Mars Rover and Ingenuity Quadcopter)
- 

### NOTE 👇
Please put your doc `inside section-6` if not present create new folder `section-6`

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

Thanks for @Aryamanz29  for giving me this oppurtunity to create a issue.

**Comment by imcoza** [comment]
I want to work on this issue .I would like to prepare the documentation on this. Kindly assign me this
IMAMA SHEHZAD from python batch 5

**Comment by pspiagicw** [comment]
I think you have to use the /assign command to get assigned

**Comment by imcoza** [comment]
> I think you have to use the /assign command to get assigned
Is I am assigned for this issue . If yes, then from when I need to work on this and the last date to submit.

**Comment by imcoza** [comment]
> /assign

thanks for telling me

**Comment by Aryamanz29** [comment]
> > /assign
> 
> thanks for telling me

@imcoza  Assigned , Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@imcoza  Any updates on this ??

**Comment by imcoza** [comment]
I have done the PR

> @imcoza Any updates on this ??

I have made the documentation but did not able to make a PR perfectly
