### ISSUE TITLE
ML 1.8: A\B Testing (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1109]
Welcome to 'ML' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge that one needs to know about A/B Testing.

To get assigned to this issue, add your Batch Numbers mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

**Points to Note :**

* The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

* "Issue Title" and "PR Title should be the same. Include issue number along with it.

* Changes should be made inside the Machine Learning/Machine_Learning/Statistics_for_Machine_Learning Branch.

* Follow Contributing Guidelines & Code of Conduct before start Contributing.

* This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

To be Mentioned while taking the issue :

* Full name
* Batch Number
* GitHub Profile Link
* Which type of Contribution you want to make :
       -  Audio

All the best. Enjoy your open source journey ahead.

**Comment by Aaksha-sharma** [comment]
@Isha307 this is where I can contribute right?

**Comment by Isha307** [comment]
Yeah

**Comment by imcoza** [comment]
I want to contribute to this issue. I want to make documentation on this.
 Imama Shehzad ML batch 2.
https://github.com/imcoza

**Comment by Isha307** [comment]
@imcoza First of all this issue is already assigned and second is that you can see this issue is audio type.

**Comment by imcoza** [comment]
> @imcoza First of all this issue is already assigned and second is that you can see this issue is audio type.

Sorry, I want to work on the documentation part no experience with the audio type.

**Comment by Isha307** [comment]
@imcoza This is the time, You can learn and explore new things.

**Comment by Aaksha-sharma** [comment]
@Isha307  I have done the audio on this part where should I send it to you?
