### ISSUE TITLE
DSA 1.2.1 Asymptotic Analysis (Analysis of Algorithms)

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#111]

**Comment by AJgthb2002** [comment]
Please assign this issue to me. I'd like to create a tutorial on this topic

**Comment by mandeep168** [comment]
Can I work on this?
Mandeep Kaur
dsa-batch-5

**Comment by Subhradeep10** [comment]
@AJgthb2002 Go for it. Assigned to you

**Comment by sakkshm26** [comment]
Hey, can I work on this issue?

**Comment by Yatheshta** [comment]
Can I work on this ?

**Comment by Subhradeep10** [comment]
@AJgthb2002 Any updates?

**Comment by AJgthb2002** [comment]
@Subhradeep10 Thank you. I am working on it

**Comment by kalyanirb12** [comment]
i would like to contribute

**Comment by Akshita-Sharma-25** [comment]
please assign this issue to me, I would like to contribute towards this issue.
I'm from batch 4

**Comment by uditkatyal** [comment]
pls, assign this issue to me.
I have made awesome notes regarding the analysis of algorithms.
I will convert it in documentation
They are given in such an easy way that a simple read will make it crystal clear.
pls assign
dsa-batch-3

**Comment by EktaAgrawal** [comment]
Hello sir, I have a keen interest in this and wanted to contribute. I have also stared working on it  kindly assign me

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal
I am Python Batch-6
I would like to contribute via documentation in this issue 
Pls assign me
