### ISSUE TITLE
ML 1.8: A\B Testing (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1115]
Welcome to 'ML' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge that one needs to know about A/B Testing.

To get assigned to this issue, add your Batch Numbers mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

**Points to Note :**

* The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

* "Issue Title" and "PR Title should be the same. Include issue number along with it.

* Changes should be made inside the Machine Learning/Machine_Learning/Statistics_for_Machine_Learning Branch.

* Follow Contributing Guidelines & Code of Conduct before start Contributing.

* This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

To be Mentioned while taking the issue :

* Full name
* Batch Number
* GitHub Profile Link
* Which type of Contribution you want to make :
  [] Video

All the best. Enjoy your open source journey ahead

<hr>

**Comment by deepthi1107** [comment]
name: Deepthi M
Batch : 2
github link: https://github.com/deepthi1107
type: document

**Comment by Isha307** [comment]
@deepthi1107 Check the issue, it is for video not for the documentation.

**Comment by abhisheks008** [comment]
@deepthi1107 Issue assigned.

**Comment by abhisheks008** [comment]
@deepthi1107 Complete your previous issue first and then only you'll be eligible to take up another issue.

**Comment by karma659** [comment]
Name-Akash Karmakar
Batch- 5
github link-https://github.com/karma659
type - documentation

**Comment by abhisheks008** [comment]
@karma659 It's clearly written as Video content, check the guidelines first. And do not use self assign without taking permissions of the supervisors.

**Comment by karma659** [comment]
Name-Akash Karmakar
Batch- 5
github link-https://github.com/karma659
type - video

**Comment by abhisheks008** [comment]
Issue Assigned @karma659. Complete this issue within this Friday.

**Comment by abhisheks008** [comment]
What is the update @karma659 ? It's been 3 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by karma659** [comment]
Yes I am  doing the PR

**Comment by abhisheks008** [comment]
@karma659 What's the update on this issue?
