### ISSUE TITLE
Websites for Android Development using Java

### ISSUE THREAD

**Issue by RahulRam29** [girlscript/winter-of-contributing#1118]
<hr>

Documentation

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Java)

<hr>

**Comment by RahulRam29** [comment]
Assign Websites for Android Development using Java to me @RahulRam29

**Comment by Binita-tech** [comment]
\assign Audio & Video

**Comment by Binita-tech** [comment]
\assign Document

**Comment by VikasPandey121** [comment]
> Documentation
> 
> ## Domain of Contribution 📊
> * [x]  Android Dev (Java)

Please add more description to this issue regarding what could be done in this context.
