### ISSUE TITLE
Data Science with Python : Decision Tree Algorithm

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1126]
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Decision Tree Algorithm. Tutorial to Decision Tree Algorithm and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Shivang Dubey](https://github.com/shivangdubey) / [Kareem Negm](https://github.com/Kareem-negm)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by dev123singh** [comment]
Thank you for adding the issue of Decision tree Algorithm
Approach:
Getting a dataset appropriate for the ML model.
Data quality check, i. e : Removal of outliers, Data processing
Data Visualization, graphic implementation
Training of dataset
ML model building
Getting an accuracy score.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with a serial number:172. I would like to do documentation on this issue.
my approach: a detailed explanation and a data set to explain the code.

**Comment by prathimacode-hub** [comment]
Issue is assigned to @dev123singh for documentation.

@deepthi1107, if you haven't been assigned to any issue, put up your message in discord thread

**Comment by deepthi1107** [comment]
ok @prathimacode-hub

**Comment by m0hit-kumar** [comment]
I want to contribute to this issue :
Name-Mohit Kumar
Domain-Data Science with Python
Batch-4
Issue Number- 1126
Contribution Approaches- 
what is a decision tree,
how to make a Decision Tree approach.
how to tune for better results.

**Comment by Kareem-negm** [comment]
Hello, the mentor here for any help

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172. I would like to do video on this issue.
My approach: A detail explanation with an example and code.

**Comment by Praannjaal** [comment]
Hello , I'm Pranjal Mittal
Batch : 19
Type: Documentation
Approach: Explaining decision tree , how to make it with a brief of why it is needed and giving suitable examples for it.

**Comment by shripaddhopate** [comment]
I would be glad to work on this issue.
Name : Shripad Dhopate
Batch : 21
Type : Documentation , Video
Serial No: 930

**Comment by prathimacode-hub** [comment]
If you're interested for video, let me know. Documentation is already been assigned. @shripaddhopate

**Comment by prathimacode-hub** [comment]
Issue is assigned to @deepthi1107 for video contribution
