### ISSUE TITLE
C/CPP - Looping Control Structure

### ISSUE THREAD

**Issue by Shubhrajyoti24** [girlscript/winter-of-contributing#1128]
<hr>

## Description 📜

Documentation for loops and their functioning in C

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by Suvraneel** [comment]
@Shubhrajyoti24  doc has already been assigned
Lemme know if you want to contribute audio/video

**Comment by sakshi168** [comment]
/assign 
want to contribute in video format
