### ISSUE TITLE
Open Source : 6. Open Source in Gaming

### ISSUE THREAD

**Issue by pspiagicw** [girlscript/winter-of-contributing#1129]
<hr>

## Description 📜

Gaming is a little behind in Open Source especially for modern AAA titles. Open Source technology is being used to make the games , but the game itself maybe closed source

Topics to cover:
- Advantages and Limitations
- Open Source Game Engines ( Unity , Godot , Love2D)
- Current Open Source Games ( 0AD , Xonotic , SuperTuxCart , FreeDOOM , OpenRCS2 )
- How to contribute

### NOTE 👇
Please put your doc `inside section-6` if not present create new folder `section-6`

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>
Thanks to @Aryamanz29 for the opportunity for opening this issue

**Comment by pspiagicw** [comment]
PR raised

**Comment by Aryamanz29** [comment]
@pspiagicw Awesome work 🎉🎉
