### ISSUE TITLE
DSA: Sorting Algorithms

### ISSUE THREAD

**Issue by themonikanayak** [girlscript/winter-of-contributing#113]
Detailed Explanation of Sorting Algorithms in C++.

**Comment by Asmit2952** [comment]
Hey, I would like to contribute to this issue.

**Comment by themonikanayak** [comment]
> Hey, I would like to work on this issue.

Yes, sure go ahead!

**Comment by Asmit2952** [comment]
Can you assign it to me, so that other contributors will also know

**Comment by siddhi-244** [comment]
Hey can I work on it?

**Comment by Asmit2952** [comment]
> > Hey, I would like to work on this issue.
> 
> Yes, sure go ahead!

Can you please provide the folder structure

**Comment by shivasaiutkar** [comment]
i would like to contribute on this 
dsa batch 5
shivasai utkar

**Comment by mandeep168** [comment]
I would like to work on this.
Mandeep Kaur
dsa-batch-5

**Comment by mansisingh2803** [comment]
Hey I would like to work on this . Please assign it to me

**Comment by Vedika-Agrawal** [comment]
@themonikanayak, Please assign this issue to me, I would like to work on this issue under GWOC.

**Comment by mansisingh2803** [comment]
Please assign this issue to me, I would like to work on this issue under
GWOC.

—

**Comment by preeti-14-7** [comment]
I would like to contribute to this topic as I have a clear concept of all sorting algorithms.
dsa batch 3
Preeti Kumari Yadav

**Comment by vishvarana** [comment]
I would like to work on this if given a chance.
Please assign this to me. @themonikanayak

**Comment by nik09877** [comment]
I would like to work on this issue.
Nikhil Kumar Mishra
DSA Batch-3

**Comment by ajaykathwate** [comment]
Heyy
I would like to work on it
can you assign it to me?

**Comment by jaissumi1402** [comment]
Please assign this issue to me, I would like to work on this issue under GWOC

**Comment by cookieg13** [comment]
Hi sir! I would really love to work on this issue and I also have in depth knowledge about sorting algorithms. I am Debarati Ghatak from DSA Batch 3. Please assign it to me.

**Comment by Aaryan376** [comment]
Hey! I would like to work on this issue

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal
I would like to contribute/work on this issue
I am from DSA Batch 2

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal
I would like to contribute/work on this issue
I am from DSA Batch 2

**Comment by likitarai1** [comment]
I would like to work on this issue.
Likita Rai
DSA batch 2

**Comment by Pawanupadhyay10** [comment]
Pls assign this issue to me.

**Comment by kalyanirb12** [comment]
i would like to contribute

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by themonikanayak** [comment]
> Detailed Explanation of Sorting Algorithms in C++.

/assign
