### ISSUE TITLE
FrontEnd: Colors in CSS

### ISSUE THREAD

**Issue by ArpitaGupta4086** [girlscript/winter-of-contributing#1131]
<hr>

## Description 📜  

I would describe the different ways or methods in which one can specify the colors in CSS.I would also document how we can add text color, background color etc. using CSS.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by lohith1392** [comment]
\assign document

**Comment by lohith1392** [comment]
\assign

**Comment by ishika-1205** [comment]
\assign

**Comment by subhradwip01** [comment]
I would like to work on the issue with documentation. Batch 18 Frontend Subhradwip Kulavi

**Comment by ArpitaGupta4086** [comment]
@Ayan-thecodeking can you please assign this to me

**Comment by jaigora24** [comment]
\assign Document

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking can you please assign this to me

go ahead @ArpitaGupta4086
