### ISSUE TITLE
Data Science with Python : LightGBM Algorithm

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1137]
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with LightGBM Algorithm. Tutorial to LightGBM Algorithm and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Peehu Saxena](https://github.com/PeehuSaxena) / [Arya Patel](https://www.github.com/AryaPatel1111)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Vidit-Ostwal** [comment]
Name : Vidit

**Comment by prathimacode-hub** [comment]
@Vidit-Ostwal, i'm not rejecting you but as mentioned this issue was created on contributors request. To make things a bit easier, I had created a thread in discord where in you can come up with an issue you would like to work on voluntarily until new issues are created, i had also created a thread of PR notice board in discord, wherein you can give all the details asked for reviewing process so that we know PR is created in the pool of things.

**Comment by Vidit-Ostwal** [comment]
I didn't knew it was created on contributor request,

**Comment by prathimacode-hub** [comment]
> I didn't knew it was created on contributor request,

That's Ok, just letting you know of things how it's flowing. @Vidit-Ostwal

**Comment by m0hit-kumar** [comment]
I want to contribute to this issue :
Name-Mohit Kumar
Domain-Data Science with Python
Batch-4
Issue Number-1137
Contribution Approaches- 
What is Light GBM
Advantages of Light GBM
Important parameters of Light GBM
Light GBM vs XGBOOST
Tuning parameters of Light GBM for better performance

**Comment by prathimacode-hub** [comment]
@Vidit-Ostwal Do you like to work on this issue for documentation?

@m0hit-kumar, are you up for audio or video for this issue?

**Comment by m0hit-kumar** [comment]
@Vidit-Ostwal for documentation

**Comment by Vidit-Ostwal** [comment]
Yup, i will take that for documentation

**Comment by prathimacode-hub** [comment]
Yes, since @Vidit-Ostwal expressed his interest first for documentation

What about you?  @m0hit-kumar

**Comment by m0hit-kumar** [comment]
@prathimacode-hub documentation

**Comment by prathimacode-hub** [comment]
But @Vidit-Ostwal expressed his interest first for documentation. Anyways you both decide up and come with an answer so that i could assign accordingly. @m0hit-kumar

**Comment by m0hit-kumar** [comment]
i really want to work on this @paramsiddharth

**Comment by Vidit-Ostwal** [comment]
@m0hit-kumar u already have a better profile of GitHub than me, 
Let me work on this on, u can take some other issue,
@prathimacode-hub kindly assign it to me on FCFB (First come First Basis).

**Comment by m0hit-kumar** [comment]
@Vidit-Ostwal  no this is my first

**Comment by prathimacode-hub** [comment]
@m0hit-kumar, other than this algorithm there is any other algorithm you are interested to work on

**Comment by m0hit-kumar** [comment]
@prathimacode-hub what other we have??

**Comment by prathimacode-hub** [comment]
> @m0hit-kumar, other than this algorithm there is any other algorithm you are interested to work on. Since it's your first PR. I have create a thread on discord for all first timers to come up with their own issue to get it assigned. If there is any other algorithm you want to work on, you can put a message there with details. 

As said according to rule, it should be allotted on FCFS basis, since you both aren't deciding up anything. I had to assign this to @Vidit-Ostwal for documentation.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub what other we have??

CatBoost Algorithm? @m0hit-kumar

**Comment by prathimacode-hub** [comment]
Issue assigned to @Vidit-Ostwal for documentation

**Comment by m0hit-kumar** [comment]
@prathimacode-hub so assigned me that. i would love to work on it

**Comment by m0hit-kumar** [comment]
@prathimacode-hub Mam, if possible can you create a new issue about CatBoost  I would like to contribute.

ds-with-python-batch4
Name: Mohit Kumar

Topic: CatBoost  Algorithm

Preference: Documentation

Github profile: https://github.com/m0hit-kumar

Approaches-  What is CatBoost
Advantages of CatBoost library
CatBoost in comparison to other boosting algorithms,
Handling Categorical features
Solving various ML challenges using CatBoost
using an appropriate dataset
Thank you

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Mam, if possible can you create a new issue about CatBoost I would like to contribute.
> 
> ds-with-python-batch4
> Name: Mohit Kumar
> 
> Topic: CatBoost Algorithm
> 
> Preference: Documentation
> 
> Github profile: https://github.com/m0hit-kumar
> 
> Approaches- What is CatBoost
> Advantages of CatBoost library
> CatBoost in comparison to other boosting algorithms,
> Handling Categorical features
> Solving various ML challenges using CatBoost
> using an appropriate dataset
> Thank you

Ok great, I had created a issue, comment it using the same details to get it assigned. @m0hit-kumar

**Comment by m0hit-kumar** [comment]
@paramsiddharth mam done pls assigned it to me now

**Comment by prathimacode-hub** [comment]
> @paramsiddharth mam done pls assigned it to me now

This is my github username : prathimacode-hub. @m0hit-kumar

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
