### ISSUE TITLE
Basic Data Types in Python

### ISSUE THREAD

**Issue by Kanishk0412** [girlscript/winter-of-contributing#1139]
<hr>

## Description 📜

In the documentation form, I'll go over all of the data types used in Python and how to assign them.

<hr>

## Domain of Contribution 📊

- [x ] Python

<hr>

**Comment by BhaswatiRoy** [comment]
> ## Description 📜
> In the documentation form, I'll go over all of the data types used in Python and how to assign them.
> 
> ## Domain of Contribution 📊
> * [x ] Python

/assign

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Python 
Batch-3  
Issue Number-
Contribution Approach-explain all the datatypes with examples and code samples of each and why we dont need to mention datatype over variable declaration

**Comment by Aaksha-sharma** [comment]
I want to contribute through Audio in this issue

**Comment by simran2104** [comment]
I want to contribute to this issue :
Python Batch-1
Contribution Approach- Explain Each data Type with sample code and how to use them, their memory sizes, which to use and when.

**Comment by adityabisoi** [comment]
The topic has already been covered.
