### ISSUE TITLE
DSA: TREE TRAVERSALS

### ISSUE THREAD

**Issue by themonikanayak** [girlscript/winter-of-contributing#114]
Explain in detail various tree traversals. Write both approach and code for the same.

**Comment by Kavindra-Mohan-Dwivedi** [comment]
sir i would like to work on this issue

**Comment by srikars-1** [comment]
I would like to work on this issue

**Comment by srikars-1** [comment]
I would like to work on this issue

**Comment by thepranaygupta** [comment]
Hey! I would like to contribute to this issue, I have a [personal repo](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/04.%20Tree) for the same.
Pranay Gupta
DSA batch-4

**Comment by ShivM03** [comment]
Hello! I would like to contribute to this issue

**Comment by rajveer43** [comment]
i would like to work on this issue 
Rajveer Rathod
DSA batch 2

**Comment by mandeep168** [comment]
I would like to work on this. 
Mandeep Kaur 
DSA batch 5

**Comment by shivasaiutkar** [comment]
i would like to contribute on this
shivasai utkar
dsa batch 5

**Comment by harshithapasupuleti** [comment]
I would like to work on this issue
Pasupuleti Harshitha
DSA batch  5

**Comment by codermanisha** [comment]
I would like to contribute on this issue.
MANISHA KUMARI

**Comment by Vedika-Agrawal** [comment]
Please assign this issue to me, I would like to work on this issue under GWOC.

**Comment by jaissumi1402** [comment]
Can you please assign me this work?

**Comment by cookieg13** [comment]
I would really love to contribute on this issue! Can you please assign me this work?

**Comment by rkadam61001** [comment]
i would like to contribute (DSA batch-1)

**Comment by usgn94** [comment]
I would like to work on this issue (DSA Batch - 4)

**Comment by divya1467** [comment]
I would really like to contribute on this issue!
(DSA Batch-5)

**Comment by Sacheta** [comment]
Hey there, would like to work on this issue. (DSA Batch 3)

**Comment by ketanraj15** [comment]
I would really like to contribute on this issue!
(DSA Batch-5)

**Comment by pravahanj** [comment]
Sir, 
I would like to contribute in it (DSA Batch 5)

**Comment by Shruti-Subu** [comment]
can i try this?

**Comment by neenad99** [comment]
would like to contribute in it  (DSA batch 1)

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by khareyash05** [comment]
@Kavindra-Mohan-Dwivedi Would you like to work on this?
