### ISSUE TITLE
Improve the Readme file of Main Java Branch

### ISSUE THREAD

**Issue by garvitraj** [girlscript/winter-of-contributing#1143]
<hr>

## Description 📜

You are required to improve the readme file of the main Java Branch and Quick navigation and make it more attractive and provide adequate knowledge with that.

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

**Comment by sumitaccess007** [comment]
\assign

**Comment by sumitaccess007** [comment]
\assign Video
