### ISSUE TITLE
C_CPP : Linear and Binary Search Documentation

### ISSUE THREAD

**Issue by areenoverclouds** [girlscript/winter-of-contributing#1145]
<hr>

## Description 📜

I'll provide documentation for linear and binary searches in an array.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by areenoverclouds** [comment]
> /assign

Hello, are you a mentor? Aren't we supposed to open our own issues for ourselves? :)

**Comment by SouravKr2001** [comment]
I am interested to contribute documentation part plz assign it to me

**Comment by beecoder-pro** [comment]
Can you assign this to me?

**Comment by Pawanupadhyay10** [comment]
I'm doing

**Comment by Suvraneel** [comment]
@areenoverclouds  Like stated before, authors will be given preference
So, go ahead... And try to make a PR quick since its always been 11 days... (Let me know if you need more time)

**Comment by Pawanupadhyay10** [comment]
I am doing it

**Comment by Saviour1001** [comment]
Closing this as the PR got merged !
