### ISSUE TITLE
Frontend_Web_Development_HTML_CSS_JS: AJAX

### ISSUE THREAD

**Issue by aniketpathak028** [girlscript/winter-of-contributing#1150]
# AJAX
---
AJAX in javascript

# Directory
---
```
Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/9.AJAX
```

# Description 📜
---
creating a tutorial on AJAX in Javascript for Front_End_Web_Development_HTML_CSS_JS branch and discussing the following:
- What is AJAX?
- How does AJAX Work?
- AJAX - The XMLHttpRequest Object
- Fetch API

# Domain of Contribution 📊
---

- [x] Frontend Dev (HTML, CSS, JS)

# Format
---
- [x] Documentation

**Comment by aniketpathak028** [comment]
@praveenscience I have created this issue but am unable to get assigned using the bot, please assign me this issue.
Thanks

**Comment by jaigora24** [comment]
\assign Document

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : Frontend_Web_Development_HTML_CSS_JS: AJAX
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-1150
Contribution Approaches-Full form of AJAX, Asynchronous javascript, What is XML, What is JSON, What is a Promise, How does AJAX work
Type-Audio
