### ISSUE TITLE
Competitive Programming : Backtracking

### ISSUE THREAD

**Issue by hariketsheth** [girlscript/winter-of-contributing#1152]
<hr>

## Description 📜

Would like to add the documentation and coding problems related to the concept of Backtracking. 
Can you please assign me for this issue?
Thanks 

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming
- [x] DSA
- [x] Open Source

<hr>

**Comment by palakshivlani-11** [comment]
assign
