### ISSUE TITLE
Frontend_Web_Development_HTML_CSS_JS: The DOM

### ISSUE THREAD

**Issue by sushovanb02** [girlscript/winter-of-contributing#1155]
# The DOM
DOM in JavaScript
<hr>

# Directory
```Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/7.The DOM```
## Description 📜

Creating a tutorial on DOM in Javascript for Front_End_Web_Development_HTML_CSS_JS branch and discussing the following:
- What is the DOM?
- The DOM tree structure
- Accessing the DOM
- DOM Methods
- What is Document Object?

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

# Format
- [x] Documentation

**Comment by sushovanb02** [comment]
@praveenscience sir, I have created this issue. Please assign me this as the bot is not working.

**Comment by sushovanb02** [comment]
and also kindly attach the Frontend label

**Comment by amankumar11** [comment]
I can write some example code for this part using HTML,CSS and JS.

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : Frontend_Web_Development_HTML_CSS_JS: The DOM
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-1155
Contribution Approaches-What is DOM, full form of DOM, How does the DOM work
Type-Audio

**Comment by amankumar11** [comment]
@sushovanb02 i am still working on the 5 examples of The DOM under this issue.
I have completed 3 examples with full-fledged running Js, only 2 more examples are left and i will push the changes by Friday forsure.
I will request you to open this issue so that i can make a PR accordingly.

**Comment by code-reaper08** [comment]
> @sushovanb02 i am still working on the 5 examples of The DOM under this issue.
> I have completed 3 examples with full-fledged running Js, only 2 more examples are left and i will push the changes by Friday forsure.
> I will request you to open this issue so that i can make a PR accordingly.

You can create a new issue, with a **PR** @amankumar11
