### ISSUE TITLE
Java 3.1: Primitive Data Types - Integers

### ISSUE THREAD

**Issue by sumitaccess007** [girlscript/winter-of-contributing#1156]
<hr>

## Description 📜
Primitive Data Types - Integers

<hr>

## Domain of Contribution 📊

- [x] Java

<hr>

**Comment by sumitaccess007** [comment]
\assign Video

**Comment by sumitaccess007** [comment]
\assign

**Comment by AbhishekBhatt072003** [comment]
\assign documentation

**Comment by souvikrajsingh** [comment]
\assign Documentation

**Comment by Rohit570git-hub** [comment]
\assign document

**Comment by AkMo3** [comment]
Issue creation by contributor not allowed. This will be closed.
