### ISSUE TITLE
DSA : Arrays : Sort an array of 012

### ISSUE THREAD

**Issue by siddhi-244** [girlscript/winter-of-contributing#1167]
<hr>

## Description 📜

Sort an array of 012
<hr>

## Domain of Contribution 📊

- [x] DSA
<hr>

**Comment by siddhi-244** [comment]
Siddhi Bhanushali 
DSA BATCH 1
DOCUMENTATION

**Comment by palakshivlani-11** [comment]
\assign documentation

**Comment by Aryan-Mohanty** [comment]
can i work on this issue?
