### ISSUE TITLE
Android-Java: 2.2 How onclicklistener works and handled in the Android studio.

### ISSUE THREAD

**Issue by Pradumnasaraf** [girlscript/winter-of-contributing#117]
1) How click is been handled in android.
2) What is OnClickListner and how to use it.
3) Also add a small project to showcase how OnClickListner works.

**Comment by Pradumnasaraf** [comment]
Sir, @VikasPandey121 can I work on this issue?

**Comment by shekhars08** [comment]
Can you assign this task to me @VikasPandey121

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 2.2 for instance `2.2 Android UI Widgets`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.2.1`, `2.2.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by VikasPandey121** [comment]
> Sir, @VikasPandey121 can I work on this issue?

@Pradumnasaraf  Yes sure, I have assigned this issue to you. 
@shekhars08 Please look into other issues which are still not been assigned to others.

**Comment by Pradumnasaraf** [comment]
Thank You for assigning it to me.

**Comment by SouravKr2001** [comment]
I am interested (docum..)
