### ISSUE TITLE
1.1.4.2 Arrays: Order Statistics

### ISSUE THREAD

**Issue by vikhyatsingh123** [girlscript/winter-of-contributing#1171]
> ## Description
>Explain how to find median of 2 sorted arrays.
> 
> ## Task
Contribution can be in the forms of

> * [x]  Editorial/Documentation
> * [ ]  Audio
> * [ ]  Video
> 
> ## Note
> * While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
> * Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
> * In case you see that the issue has already been assigned, try to request for a different task within the same issue.
> * Changes should be made inside the `DSA/directory` & `DSA` branch.
> * Name of the file should be same as the issue.
> * This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Madhuranaik21** [comment]
\assign documentation

**Comment by palakshivlani-11** [comment]
\assign documentation

**Comment by vikhyatsingh123** [comment]
@ritikaxx on which part are you working?

**Comment by ritikaxx** [comment]
@vikhyatsingh123  
I am working on the documentation which will include the complexity analysis and code.

**Comment by vikhyatsingh123** [comment]
@palakshivlani-11 @Madhuranaik21 documentation part is already assigned. So you can ask for other part.
