### ISSUE TITLE
React - Deploying a React App to GitHub Pages

### ISSUE THREAD

**Issue by cenacrharsh** [girlscript/winter-of-contributing#1173]
<hr>

## Description 📜

How to deploy a React app created using create-react-app on GitHub Pages.

<hr>

## Domain of Contribution 📊

- [ ] Frontend Dev (React, Angular, Vue)
<hr>

**Comment by cenacrharsh** [comment]
I have opened this issue, I would like to work on this using documentation.
Please assign this to me, and add the labels.

**Comment by AdityaPandey03** [comment]
Hello @cenacrharsh,  I would like to work on the documentation part of this issue

**Comment by cenacrharsh** [comment]
> Hello @cenacrharsh,  I would like to work on the documentation part of this issue
> 

Actually I am a contributor as well, I opened this issue to work on it, and currently waiting for it to get assigned to me 

You can talk with mentors and work on audio or video part, since I will be working on the documentation part.

**Comment by AdityaPandey03** [comment]
> > Hello @cenacrharsh,  I would like to work on the documentation part of this issue
> 
> Actually I am a contributor as well, I opened this issue to work on it, and currently waiting for it to get assigned to me
> 
> You can talk with mentors and work on audio or video part, since I will be working on the documentation part.

oh okay harsh

**Comment by anandhu720** [comment]
guys plese dont open issues by your self,it will create unnecessary chaos.
