### ISSUE TITLE
Frontend Dev (HTML, CSS, JS): HTML Lists

### ISSUE THREAD

**Issue by Neha7703** [girlscript/winter-of-contributing#1175]
<hr>

## Description 📜

I would like to make a documentation on HTML Lists, covering all the information related to lists such as types of lists, list tags, etc. and will provide code snippets. 
 

<hr>

## Domain of Contribution 📊

- [ ] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by KartikChinda** [comment]
Hey @Neha7703 , this issue has already been created and assigned to me. A good practice would be to search the issue before contributing. Cheers!

**Comment by Neha7703** [comment]
> Hey @Neha7703 , this issue has already been created and assigned to me. A good practice would be to search the issue before contributing. Cheers!

Kindly check the general channel for Frontend Dev. It is already mentioned there by @code-reaper08 sir that multiple persons can work on a single topic as there are many students and the topics are less. Almost all the issues have already been created and assigned.
