### ISSUE TITLE
Competitive Programming : Stacks, Queues and Arrays

### ISSUE THREAD

**Issue by hariketsheth** [girlscript/winter-of-contributing#1183]
<hr>

## Description 📜

Would like to add the codes for Implementation and Concepts (Stacks, Queues and Arrays - Data Structures) 
Can you please assign me for this issue?
Thanks 

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming
- [x] DSA
- [x] Open Source

<hr>

**Comment by RitabrataDas343** [comment]
@Mentors/Supervisors, can I get the issue?
