### ISSUE TITLE
Android-Java: 2.6 Radio Buttons In Android Studio 

### ISSUE THREAD

**Issue by Pradumnasaraf** [girlscript/winter-of-contributing#1187]
<hr>

## Description 📜

* What are Radio Buttons.
* How to use Radio Buttons.
* How they are different from Check Box

<hr>

## Domain of Contribution 📊
- [x] Android Dev (Flutter, Java, Kotlin)
<hr>

**Comment by Pradumnasaraf** [comment]
@Rohit-2602 @VikasPandey121

**Comment by Rohit-2602** [comment]
yes, you can start working on it

**Comment by Pradumnasaraf** [comment]
> yes, you can start working on it
> 

Thank you

**Comment by Pradumnasaraf** [comment]
> /assign

It's already assigned @Animesh312, please try finding unassigned issues or open a new issue by consulting your mentor
Have a great day 😀
