### ISSUE TITLE
Android Java: 2.3 Toast In Android Studio

### ISSUE THREAD

**Issue by Pradumnasaraf** [girlscript/winter-of-contributing#119]
1) What is Toast.
2) How we can implement them and their working
3) Also add a Small project to show how Toast works.

**Comment by Pradumnasaraf** [comment]
Sir, @VikasPandey121 can I work on this issue?

**Comment by priyanshu688** [comment]
@VikasPandey121 Sir Can I work on this??

**Comment by priyanshu688** [comment]
Can I work on this issue @VikasPandey121

**Comment by Rohit-2602** [comment]
@Pradumnasaraf yes you can work on this.

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` command before pushing commit it to the remote repository.
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by SouravKr2001** [comment]
I am from Android Development with Java Batch-6
I want to contribute/work in this issue via documentation

**Comment by cmonitishofficial** [comment]
**Can I work on this issue? @VikasPandey121**

**Comment by VikasPandey121** [comment]
> **Can I work on this issue? @VikasPandey121**

Please look up for the vacant issues as it is already assigned to another contributor.
