### ISSUE TITLE
OpenSource : 3.3 Introduction to open source software and examples to few open source softwares

### ISSUE THREAD

**Issue by siddhi-244** [girlscript/winter-of-contributing#120]
Please assign this to me.

**Comment by Akshat-2002-coder** [comment]
sir can u plz assign this to me?
I want to work on it.

**Comment by paras-saxena11** [comment]
I want to contribute in this ?
Please assign me

**Comment by siddhi-244** [comment]
Can I start working on it ?

**Comment by Aryamanz29** [comment]
@siddhi-244  Assigning this to you, Happy Documenting 🎉

**Comment by Aryamanz29** [comment]
> I want to contribute in this ?
> Please assign me

You don't need to wait for issues, Any suggestions, Improvements or topics, That you wanted to add to the domain, You can create issues for that if it lies under the `open_source` domain, I'll assign that to you straight away, Now comes to roadmap thing, That will share in 2-3 days with all contributors of my domain, So you guys don't need to worry about that thing. I hope it clears everything. Happy Contributing :slight_smile: `Note: Make sure you used proper naming convention & issue not same as previous ones`

**Comment by siddhi-244** [comment]
Please check my pr!

**Comment by siddhi-244** [comment]
> > I want to contribute in this ?
> > Please assign me
> 
> @paras-saxena11
> You don't need to wait for issues, Any suggestions, Improvements or topics, That you wanted to add to the domain, You can create issues for that if it lies under the `open_source` domain, I'll assign that to you straight away, I hope it clears everything. Happy Contributing 🙂 `Note: Make sure you used proper naming convention & issue not same as previous ones`

Thank you so much.

**Comment by Aryamanz29** [comment]
> Please check my pr!

Done, Merged 🎉🎉🎉, Closing this issue now

**Comment by siddhi-244** [comment]
> > Please check my pr!
> 
> Done, Merged 🎉🎉🎉, Closing this issue now

Thank you
