### ISSUE TITLE
Android Java: 2.4 Layouts in Android development

### ISSUE THREAD

**Issue by Priyanshirathore** [girlscript/winter-of-contributing#121]
@VikasPandey121  can I work on this issue?

**Comment by priyanshu688** [comment]
Can I work on this issue @VikasPandey121

**Comment by saloni33** [comment]
Can I work on this issue @VikasPandey121

**Comment by anmol20112000** [comment]
Plzz assign this work to me....i want to do this @VikasPandey121

**Comment by Rohit-2602** [comment]
@Priyanshirathore add proper description and can start working on it.

**Comment by Priyanshirathore** [comment]
okay, sir will do.

**Comment by VikasPandey121** [comment]
Please add a description as well in this issue. I am assigning this issue to you @Priyanshirathore .

keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 2.4 for instance `2.4 Layouts in Android development`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.4.1`, `2.4.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by Priyanshirathore** [comment]
Okay sir, I will work on this. Thank you.

**Comment by Priyanshirathore** [comment]
**Description of the issue:**
1. What is a layout in android?
2. Attributes of layout in android.
3. Types of layouts in android.

**Comment by SouravKr2001** [comment]
I am from Android Development with Java Batch-6
I want to contribute/work in this issue via documentation

**Comment by Priyanshirathore** [comment]
@Rohit-2602 sir, I gave a brief description of the Linear Layout, Table Layout, Relative Layout, and Constraint layout with sample code and UI output screenshots in my documentation till now.
1.1 Overview of Layouts
1.1.1 Linear layout
1.1.2 Relative layout
1.1.3 Constraint layout
1.1.4 Table layout
Should I give a brief about any other type of layout as a sub-topic?

**Comment by Rohit-2602** [comment]
@Priyanshirathore also add some layout code with their images side by side

**Comment by ShivaniAgarwal2001** [comment]
Mentor @Rohit-2602 and @VikasPandey121, the contributor haven't contributed fully, since I can see **some of the layout** such as Scroll view, Grid layout, Frame layout and list view are missing. 
**Can I please contribute further. I want to work in it.**

**Comment by Priyanshirathore** [comment]
> Mentor @Rohit-2602 and @VikasPandey121, the contributor haven't contributed fully, since I can see **some of the layout** such as Scroll view, Grid layout, Frame layout and list view are missing.
> **Can I please contribute further. I want to work in it.**

I am working on frame and absolute layout 
Grid layout is completed 
List view scroll view web view these should be covered in the a new issue describing views and viewGroups.

**Comment by Priyanshirathore** [comment]
> @Priyanshirathore also add their layout code with their images side by side

Done sir

**Comment by ShivaniAgarwal2001** [comment]
> > Mentor @Rohit-2602 and @VikasPandey121, the contributor haven't contributed fully, since I can see **some of the layout** such as Scroll view, Grid layout, Frame layout and list view are missing.
> > **Can I please contribute further. I want to work in it.**
> 
> I am working on frame and absolute layout
> Grid layout is completed
> List view scroll view web view these should be covered in the a new issue describing views and viewGroups.

Every layout is a ViewGroups(groups of many views or widgets). Hence, we cannot make new issue for the same.

**Comment by Priyanshirathore** [comment]
> > > Mentor @Rohit-2602 and @VikasPandey121, the contributor haven't contributed fully, since I can see **some of the layout** such as Scroll view, Grid layout, Frame layout and list view are missing.
> > > **Can I please contribute further. I want to work in it.**
> > 
> > 
> > I am working on frame and absolute layout
> > Grid layout is completed
> > List view scroll view web view these should be covered in the a new issue describing views and viewGroups.
> 
> Every layout is a ViewGroups(groups of many views or widgets). Hence, we cannot make new issue for the same.

Alright then I will make 3 more subheadings. But I guess if an issue is already assigned, it can't be re-assigned to you.

**Comment by Priyanshirathore** [comment]
@Rohit-2602 sir is it okay to have 10 files under the main file. Because then I have to make a PR of 11 files.
