### ISSUE TITLE
Frontend Dev (HTML, CSS, JS): CSS Positionings

### ISSUE THREAD

**Issue by braveheartdata** [girlscript/winter-of-contributing#1214]
<hr>

## Description 📜
I would like to make documentation on CSS Static, Relative, and Absolute Positioning.
I would provide theory related to it along with some examples

<hr>

## Domain of Contribution 📊

Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by Knighthawk-Leo** [comment]
> ## Description 📜
> I would like to make documentation on CSS Static, Relative, and Absolute Positioning.
> I would provide theory related to it along with some examples
> 
> ## Domain of Contribution 📊
> Frontend Dev (HTML, CSS, JS)

Add images of GIF would be also a great Idea also add that

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : Frontend Dev (HTML, CSS, JS): CSS Positionings
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-1214
Contribution Approaches-CSS position properties, various categories of positioning
Type-Audio
