### ISSUE TITLE
Android Java: 8.0 Notifications

### ISSUE THREAD

**Issue by saloni33** [girlscript/winter-of-contributing#122]
What would I include?
1. What is a notification and its types.
2. How to create notifications with working code.

**Comment by saloni33** [comment]
@VikasPandey121  can I work on this issue?

**Comment by priyanshu688** [comment]
Can I work on this issue?

**Comment by Rohit-2602** [comment]
@saloni33 yes you can work on this.

**Comment by saloni33** [comment]
Okay sir, I will do it.

**Comment by VikasPandey121** [comment]
> @VikasPandey121 can I work on this issue?

Yes sure, I am assigning this issue to you @saloni33 
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 8.0 for instance `8.0 Notifications`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `8.0.1`, `8.0.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by saloni33** [comment]
Thank you sir, I will keep these things in my mind.

**Comment by Rohit-2602** [comment]
@saloni33  can you please give a progress update about the issue and if you are facing any problem feel free to ask.

**Comment by saloni33** [comment]
@Rohit-2602 sir my main topic is notifications in android and I have completed the following subtopics in it-
1. Appearances on a device
2. Create a Notification 
3. Using Notification Channels 
4. How to Create a Notification 
and only a few things are left in it.
