### ISSUE TITLE
CSS Flexbox

### ISSUE THREAD

**Issue by subhradwip01** [girlscript/winter-of-contributing#1227]
<hr>

## Description 📜

I want to make documentation on CSS Flexbox like what is flexbox, basic properties of flexbox, and some examples of code.

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [x] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by sayakongit** [comment]
Hey, please this to me. I am in batch 13 of Web dev. I want to contribute to this topic.

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : CSS Flexbox
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-1227
Type-Audio
Contribution Approaches-What is flexbox, How does flexbox work, Advantages of flexbox, Commonly used flexbox properties
