### ISSUE TITLE
Android-Java: 2.4 Overview of JVM, DVM, ART, JIT, AOT

### ISSUE THREAD

**Issue by sitamadex11** [girlscript/winter-of-contributing#123]
## Description :
* What is Virtual Machine?
* Give some overview of JVM, DVM, ART, JIT, AOT
* JVM vs DVM
* Why Android OS used DVM instead of JVM?
* Why Android depreciated DVM and started to use ART?
* DVM vs ART
* Why Android Reintroducing JIT with ART
* JIT vs AOT

## References :
> https://medium.com/programming-lite/android-core-jvm-dvm-art-jit-aot-855039a9a8fa
> https://www.geeksforgeeks.org/difference-between-jvm-and-dvm/
> https://medium.com/android-news/closer-look-at-android-runtime-dvm-vs-art-1dc5240c3924

* Changes should be made in **Android_Development/Java/** directory under **Android_Development_With_Java** branch.
* You have to push your PR to the **Android_Development_With_Java** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by shekhars08** [comment]
Can I work on this issue @VikasPandey121

**Comment by LegendSumeet** [comment]
i can do these can You assign me to these @sitamadex11

**Comment by PVenkatArvind** [comment]
Greetings mentors, I am interested to work on the issue. Kindly assign me

**Comment by sitamadex11** [comment]
@shekhars08 you can start work on this issue

**Comment by Rohit-2602** [comment]
@shekhars08  can you please give a progress update about the issue and if you are facing any problem feel free to ask.

**Comment by LegendSumeet** [comment]
@Rohit-2602 assign me

**Comment by Utkarsh-Arora-007** [comment]
@VikasPandey121 Kindly assign this issue to me.....I would be very thankful to you
