### ISSUE TITLE
Deep Learning Algorithm - Recurrent Neural Networks

### ISSUE THREAD

**Issue by Manas1820** [girlscript/winter-of-contributing#1230]
<hr>

## Description 📜

Work on documentation including a basic overview of Recurrent Neural Networks with their types and  a basic diagram of how it works and a basic code example

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python
<hr>

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do documentation on this issue.
My approach: A documentation with related code and explanation

**Comment by Manas1820** [comment]
Actually, I have already applied to work on this issue and just waiting to get assigned.

**Comment by Tanya205** [comment]
Hi, I would like to contribute to this issue.
Tanya Malhotra
ML Batch - 6
Sr No. - 889
https://github.com/Tanya205
Documentation
