### ISSUE TITLE
HTML Lists

### ISSUE THREAD

**Issue by rohitroy2305** [girlscript/winter-of-contributing#1231]
<hr>

## Description 📜

I would like to work on the documentation of HTML lists

<hr>

## Front-end Development with HTML,CSS,JS and Bootstrap 📊

- [x ] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by rohitroy2305** [comment]
/ assign documentation

**Comment by sayakongit** [comment]
> / assign documentation

Hey, can I contribute to your issue ?

**Comment by AkhilaAthinarapu1003** [comment]
Can I contribute documentation to this issue?

**Comment by RitabrataDas343** [comment]
This issue has already been created before.
Please check #1010.

**Comment by Elisha-s** [comment]
resolved

**Comment by Elisha-s** [comment]
@sifa123  I guess there was some issue with the linking because I cannot see the linked pull request here. I'm really confused. Can you please guide me through it?
