### ISSUE TITLE
Python Basics

### ISSUE THREAD

**Issue by AkhilaAthinarapu1003** [girlscript/winter-of-contributing#1232]
<hr>

## Description 📜
Hello everyone!!! I would like to provide a documentation on python basics .. 

<hr>

## Domain of Contribution
- [ ] Open Source
- [ ] Python

<hr>

**Comment by dbmohit** [comment]
Can i work on this

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Python 
Batch-3  
Issue Number-1232
Approaches-hello world,variables, datatype, conversion from one datatype to other,examples of each, arithmetic operation, string operations

**Comment by adityabisoi** [comment]
This has been covered already.
