### ISSUE TITLE
Null & Void Pointers in C

### ISSUE THREAD

**Issue by kashyap1905** [girlscript/winter-of-contributing#1238]
<hr>

## Description 📜

This will describe Null Pointers & Void Pointers and also the difference between Null Pointers & Void Pointers.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by kashyap1905** [comment]
\assign

**Comment by Alankrita9** [comment]
/assign 
I will explain null and void pointers through examples and various functions
