### ISSUE TITLE
Android-Java : 1.9 Updating IDE and Essential SDK Tools

### ISSUE THREAD

**Issue by Arjun2905** [girlscript/winter-of-contributing#124]
Description :
1. How to update Android Studio step by step.
2. Updating SDK and other important tools.

**Comment by Arjun2905** [comment]
@VikasPandey121 should I work on this issue ?
I created this issue. 
As a beginner you need to know it exactly.

**Comment by Rohit-2602** [comment]
@Arjun2905 yes you can work on this

**Comment by Arjun2905** [comment]
Ok assign this to me @Rohit-2602 .

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 1.9 for instance `1.9 Updating IDE and Essential SDK Tools`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `1.9.1`, `1.9.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by Arjun2905** [comment]
@Rohit-2602  please go through my pull request 
https://github.com/girlscript/winter-of-contributing/pull/1246
