### ISSUE TITLE
File Handling in C - Functions used for File I/O

### ISSUE THREAD

**Issue by kashyap1905** [girlscript/winter-of-contributing#1247]
<hr>

## Description 📜

This will explain different function that can be used for reading and writing while working with the files in C.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by Diksha-11** [comment]
Please assign this issue to me.
I will contribute through Document, code.
Batch 2 C/Cpp

**Comment by Suvraneel** [comment]
duplicate #913

you can take audio if you want
