### ISSUE TITLE
ML 1.9 : Hypothesis Testing (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1258]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Hypothesis Testing**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

**Comment by ashish-reddy-20-08** [comment]
Hey, I am M. Ashish Reddy, I would like to work on this issue. @Isha307 
Batch Number: 2
GitHub Profile Link: https://github.com/ashish-reddy-20-08
contribution you want to make :  Documentation

**Comment by Isha307** [comment]
@ashish-reddy-20-08 You can work on this issue 👍

**Comment by ashish-reddy-20-08** [comment]
thank you, @Isha307

**Comment by ashish-reddy-20-08** [comment]
Hello @Isha307.
I have completed the work and created a PR.
You can check my PR in this link  :https://github.com/girlscript/winter-of-contributing/pull/1861
