### ISSUE TITLE
Android Java: 2.1 Use of Material Designs in UI

### ISSUE THREAD

**Issue by anisha-01-phoenix** [girlscript/winter-of-contributing#126]
In this, I will be describing on how we can use material designs to enhance our App UI and make it user-friendly.
The various material designs include:
 * FloatingActionButton
 * SnackBar
 * Bottom Sheets
 * Navigation Drawer
 * Bottom Navigation

We will also be describing on how to make simple XML Views like Edit Text and Button more user professional to view with the help of material designs.

**Comment by anisha-01-phoenix** [comment]
@VikasPandey121 can I work on this issue?

**Comment by Debasmita-01** [comment]
> @VikasPandey121 can I work on this issue?

Go ahead !

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 2.2 for instance `2.2 Android UI Widgets`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.2.1`, `2.2.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by anisha-01-phoenix** [comment]
> Please keep these steps in mind while creating a pull request:
> 
> * use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
> * Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 2.2 for instance `2.2 Android UI Widgets`
>   Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.2.1`, `2.2.2` etc
> * Create a new branch and push your PR on `Android_Development_With_Java` branch.
> * Pull request should contain only one commit
>   Note: If you have multiple commits then `squash` your commit.

ok Sir

**Comment by BishwasKumar** [comment]
good job vikas

**Comment by SouravKr2001** [comment]
I am from Android Development with Java Batch-6
I want to contribute/work in this issue via documentation

**Comment by Rohit-2602** [comment]
@anisha-01-phoenix  can you please give a progress update about the issue and if you are facing any problem feel free to ask.

**Comment by anisha-01-phoenix** [comment]
> @anisha-01-phoenix  can you please give a progress update about the issue and if you are facing any problem feel free to ask.

Yes Sir, I have completed the documentation on Floating Action Bar and Snack Bar along with an introduction on Material Designs and how they are better than normal XML views such as edit text or button. I have written about the usage of floating action button and Snack bar along with the codes on how to implement them.  I was thinking of making a simple project based on the usage of all the material designs, and will include that code in my documentation. Presently I am working on Bottom Sheets.
