### ISSUE TITLE
ML 1.9 : Hypothesis Testing (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1261]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Hypothesis Testing**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by Arjun2905** [comment]
Arjun Wankhede
ML batch 3
https://github.com/Arjun2905
Type of Contribution : Audio

**Comment by m0hit-kumar** [comment]
is there is something for documentation

**Comment by Isha307** [comment]
@Arjun2905 Great, You can work on it 👍

**Comment by Isha307** [comment]
@m0hit-kumar Check out other issues or wait for it.

**Comment by m0hit-kumar** [comment]
@Isha307 do you have any issue unassigned pls assigned me that

**Comment by Isha307** [comment]
@m0hit-kumar Checkout this https://github.com/girlscript/winter-of-contributing/labels/Up-For-Grabs

**Comment by m0hit-kumar** [comment]
@Isha307 they are for video and audio only and the rest are already assigned which lie under my domain

**Comment by m0hit-kumar** [comment]
@Isha307 i already checked it out, the only left one is for audio and video  not for documentation in my domain.

**Comment by Arjun2905** [comment]
@Isha307  Please go through my pull request https://github.com/girlscript/winter-of-contributing/pull/1905
