### ISSUE TITLE
ML 1.10: P-Value (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1262]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **P-Value**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

**Comment by Isha307** [comment]
@imcoza Read the above comment properly and ask in the the format.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

**Comment by Isha307** [comment]
@hrugved06  Great, you can work on it.

**Comment by Isha307** [comment]
Update?

**Comment by hrugved06** [comment]
> Update?

I'm on it

**Comment by Isha307** [comment]
okay, How many more days you need?

**Comment by hrugved06** [comment]
> okay, How many more days you need?

I'll finish it by tommorrow

**Comment by Isha307** [comment]
great

**Comment by tanvideshmukh29** [comment]
Can I work on this ?
Name: Tanvi Deshmukh
Batch: 5
Documentation

**Comment by hrugved06** [comment]
> Can I work on this ?
> Name: Tanvi Deshmukh
> Batch: 5
> Documentation

Please find a different issue.. I'm almost done with it :-)
