### ISSUE TITLE
ML 1.10: P-Value (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1263]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **P-Value**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Machine Learning
Batch-6
Issue Number- 1263                                                                                                                                                     Contribution Approaches-about p value, relation in graph, importance

**Comment by BhaswatiRoy** [comment]
> The assigned contributor has more than 3 open issues, kindly reassign manually (@Supervisors/Mentors)

The issues are not in ML domain they are in other domains so kindly please add me again in this issue

**Comment by abhisheks008** [comment]
@BhaswatiRoy that's why we request you guys not to use self assign, it'll not help you out everytime. Nevertheless the issue is assigned to you. try to complete this issue within this friday. Happy contribution.

Type of contribution : **Audio**

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy that's why we request you guys not to use self assign, it'll not help you out everytime. Nevertheless the issue is assigned to you. try to complete this issue within this friday. Happy contribution.
> 
> Type of contribution : **Audio**

Yah sorry .........also thanks will finish asap
