### ISSUE TITLE
ML 1.10: P-Value (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1264]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **P-Value**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by Isha307** [comment]
@imcoza You can work on 1 issue at a time and please check the format.

**Comment by imcoza** [comment]
> @imcoza You can work on 1 issue at a time and please check the format.

okay no problem

**Comment by NeerajHazarika** [comment]
Please assign me this issue @Isha307 
Name : Neeraj Pratap Hazarika
Batch number : ML - 5 ( ID : 783 )
GitHub Profile link : https://github.com/NeerajHazarika
Approach : Video
I have made a pull request on the previous issue, I was working on, It hasn't yet been reviewed. Rather than waiting for tht, I would like to work on a new issue.

**Comment by abhisheks008** [comment]
What is the update @NeerajHazarika ? It's been 4 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by NeerajHazarika** [comment]
@abhisheks008 yes I will make the PR by today. I was stuck with my previous issue which just got merged yesterday. When I took this issue, my previous issue was under review I thought it will merged but my supervisor asked for more changes.

**Comment by abhisheks008** [comment]
Do it ASAP @NeerajHazarika
