### ISSUE TITLE
pointers and 1D arrays in c

### ISSUE THREAD

**Issue by Suravihere** [girlscript/winter-of-contributing#1273]
<hr>

## Description 📜

I want to contribute in this issue.

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [x ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by akarshan2602** [comment]
Uh well im new to open source so i don't know anything, Can anyone help me with the procedure to start and submition? Will be really grateful...

**Comment by akarshan2602** [comment]
@Suravihere hey, sorry for the delay, but i went to the cpp branch, and saw that someone has already uploaded the solution 3 days ago, so was this a mistake?? of assigning it to me or i still have to work on it??

Regards,
Akarshan

**Comment by Suvraneel** [comment]
@akarshan2602  @Suravihere  Please pick another topic...

**Comment by akarshan2602** [comment]
Ah okok
