### ISSUE TITLE
C++ STL : Vectors

### ISSUE THREAD

**Issue by Op-panda** [girlscript/winter-of-contributing#1278]
<hr>

## Description 📜

C++ STL (Standard Template Library) is very important part of C++ .vector is subdomain of C++ STL.
I will be working upon video on Vectors in C++.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by Yukti-20** [comment]
I can write a well-formatted and structured documentation on the topic. May I do this?
Batch - 4
Documentation

**Comment by Yukti-20** [comment]
I can write well-formatted and structured documentation on the topic. May I do this?
Batch - 4
Documentation

**Comment by Op-panda** [comment]
> I can write well-formatted and structured documentation on the topic. May I do this?
> Batch - 4
> Documentation

please make your own issues
