### ISSUE TITLE
Explanation of public static void main (String[] args)

### ISSUE THREAD

**Issue by SB2318** [girlscript/winter-of-contributing#1280]
<hr>

## Description 📜
Now, As a Java programmer, we should know this. And this question is also asked in the interview.
Here I will explain each word and its importance.
<hr>

## Domain of Contribution 📊

- [x] Open Source
<hr>

**Comment by SB2318** [comment]
Can i work on this issue?

**Comment by SB2318** [comment]
Can I work on this issue?

**Comment by SB2318** [comment]
> /assign Document

Sorry maam, I cannot get your word.

**Comment by AkMo3** [comment]
Technically it is part of `Java` domain, so it cannot be created as all issues of Java are to be created by the Supervisors.
