### ISSUE TITLE
Data type in c

### ISSUE THREAD

**Issue by vishnu95075** [girlscript/winter-of-contributing#1290]
<hr>

## Description 📜

<hr>

## Domain of Contribution 📊

- [ ] Backend Dev (Java, .NET, Python)
- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by priyankapiba** [comment]
Hello! Please tell me how to contribute this?

**Comment by avishj** [comment]
Please open issues properly.
