### ISSUE TITLE
Data type in C

### ISSUE THREAD

**Issue by vishnu95075** [girlscript/winter-of-contributing#1295]
<hr>

## Description 📜

Data type in C

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>
/assign

**Comment by priyankapiba** [comment]
Hey @vishnu95075 I would like to work with this issue.

**Comment by vishnu95075** [comment]
Ofcouse @priyankapiba  you do .

**Comment by priyankapiba** [comment]
> Ofcouse @priyankapiba you do .

Please assign me this issue.

**Comment by vishnu95075** [comment]
@priyankapiba  you assigne issue for me . i am also assign you good issue for you.
