### ISSUE TITLE
MERN_React: 2.5 Using .map() in JSX

### ISSUE THREAD

**Issue by manjeetdhayal** [girlscript/winter-of-contributing#1298]
<hr>

## Description 📜

# Instructions 

## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## How to use .map() in JSX expressions 

# Task 

- [ ] Documentation

<hr>

## Domain of Contribution 📊

- [ ] MERN

<hr>

**Comment by GyaniRoman23** [comment]
Hey @manjeetdhayal I would like to work with this issue. Kindly consider assigning me this issue.

**Comment by manjeetdhayal** [comment]
@sap-phire I have assigned it to you. Go for it.

**Comment by sap-phire** [comment]
> @sap-phire I have assigned it to you. Go for it.

Thank you.

**Comment by likitarai1** [comment]
@manjeetdhayal I would like to work on documentation part.

**Comment by likitarai1** [comment]
@manjeetdhayal plz review my PR #7915
