### ISSUE TITLE
HTML Links and Links colors

### ISSUE THREAD

**Issue by Op-panda** [girlscript/winter-of-contributing#1302]
<hr>

## Description 📜

I will work on this topic in video format and submit through google drive link. 

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by Knighthawk-Leo** [comment]
> frontend (HTML, CSS, JS)
> Batch - 7
> video format
> please /assign

Ohk Assigned Start You can start the work

**Comment by chakitg** [comment]
Hey creator, I would like to work on this issue. Can you please assign me this?
Name: Chakit Gupta
Batch: Frontend with HTML, CSS, Js Batch-4
Type: Documentation

**Comment by Op-panda** [comment]
no I have already done work on this , just need a finishing touch after
that i make my PR. please make your own issues
