### ISSUE TITLE
C_CPP :- STL LISTS IN DOCUMENT FORM

### ISSUE THREAD

**Issue by Pranshu321** [girlscript/winter-of-contributing#1307]
<hr>

## Description 📜
I would like to work on this issue i submit the Lists of stl topic in document form . i will describe every point in great detail without leaving any point and with code snippets and also its functions used or described in STL. 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by Saviour1001** [comment]
Closing as the PR got merged!
