### ISSUE TITLE
Control Statements in JAVA (documentaion)

### ISSUE THREAD

**Issue by ketkikaushik** [girlscript/winter-of-contributing#1309]
<hr>

## Description 📜

I want to make a documentation on Control Statements in JAVA. It will contain detailed explanation of all types of control statements with example.

<hr>

## Domain of Contribution 📊

- [x ] Java

<hr>

**Comment by MeghaGD** [comment]
\assign

**Comment by AkMo3** [comment]
Issue creation by contributors are not allowed. Please do not make me repeat every time.
