### ISSUE TITLE
Python | List and Tuples 

### ISSUE THREAD

**Issue by bhumitbedse** [girlscript/winter-of-contributing#1310]
<hr>

## Description 📜

Here I explain the brief idea of what is List and Tuple in Python and how to use it 
<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [x] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by bhumitbedse** [comment]
I will do this @prathimacode-hub

**Comment by NarayanAdithya** [comment]
Can someone Assign this to me if possible?

**Comment by shrey-ya** [comment]
@adityabisoi is this a valid issue?
