### ISSUE TITLE
Data Science With Python : Explaining Linear Regression (Documentation)

### ISSUE THREAD

**Issue by ayushijindal** [girlscript/winter-of-contributing#1319]
<hr>

## Description 📜

Taking optimal dataset to explain linear regression in documentation format
Visualizing both actual and predicted value
format: Documentation
serial no. : 253

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

**Comment by ayushijindal** [comment]
Approach: using the optimal dataset to explain linear regression
Id: 253

**Comment by shreyarai05** [comment]
Approach: Brief explanation using dataset to explain linear regression
id:155
format: Documentation

**Comment by ayushijindal** [comment]
Approach: using the optimal dataset to explain linear regression
Id: 253
format: Documentation
