### ISSUE TITLE
Flutter: What is Flutter?

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#132]
A README file to understand what is Flutter.

The reference you may take:

Flutter Docs: https://flutter.dev/
https://github.com/dwyl/learn-flutter

https://github.com/Asabeneh/30-Days-Of-JavaScript/blob/master/04_Day_Conditionals/04_day_conditionals.md
(This is JS repository, ours should also look like this only)

**Comment by naveeramesh** [comment]
Can I work on this issue.I'm a contributor on GWoC'21

**Comment by SurabhiMishra** [comment]
Can I be assigned this issue?

**Comment by ViAsmit** [comment]
@SurabhiMishra Assigned you another topic

**Comment by jaissumi1402** [comment]
can I work on this?

**Comment by ishukhr** [comment]
I'm a contributor in GWOC'21 can I work on this issue?

**Comment by eshan1925** [comment]
May I work on this issue as I have already wriiten blog on this topic..
