### ISSUE TITLE
MERN_React: 3.2 Using event listeners in components 

### ISSUE THREAD

**Issue by manjeetdhayal** [girlscript/winter-of-contributing#1325]
# Instructions 

## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/MERN/Contributing.md) to get started

## Event listeners
> Write a brief summary on event listeners.
> Explain with the help of working examples

# Task 

- [ ] Documentation

## Domain of contribution 
- [X] MERN

**Comment by GyaniRoman23** [comment]
Hey @manjeetdhayal I would like to work with this issue.

**Comment by manjeetdhayal** [comment]
Hey @GyaniRoman23 I have assigned it to you. Rock it!
