### ISSUE TITLE
MERN_React: 3.2 using event listeners in components Video

### ISSUE THREAD

**Issue by manjeetdhayal** [girlscript/winter-of-contributing#1331]
# Instructions 

- Video must be in mp4 format and drive link to be uploaded

## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/MERN/Contributing.md) to get started

## Event listeners_Video
> Show a brief summary on event listeners.
> Explain with the help of working examples

# Task 

- [ ] Video

## Domain of contribution 
-  [X] MERN

**Comment by likitarai1** [comment]
@manjeetdhayal Plz review my PR.
