### ISSUE TITLE
C/CPP: Concept of OOPS

### ISSUE THREAD

**Issue by ketkikaushik** [girlscript/winter-of-contributing#1333]
<hr>

## Description 📜

This documentation will contain detailed explanation (with examples) of Concept of OOPS in C/CPP that includes: 

- Object
- Class
- Inheritance
- Polymorphism 
- Abstraction
- Encapsulation.

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

**Comment by sarav18302** [comment]
@ketkikaushik can I contribute to this issue

**Comment by Kamya123** [comment]
/assign
Please assign this issue to me. I want to create Documentation on this. I am currently learning deeply about the concept of OOPS and  I am sure that I will do it in a perfect manner.
