### ISSUE TITLE
Flutter: Why to use Flutter?

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#134]
A README file to understand.
1. Why to use flutter.
2.  Why to use it over traditional android and ios development,
3. How it reduces code 
4. Which language it uses

The reference you may take:

Flutter Docs: https://flutter.dev/
https://github.com/dwyl/learn-flutter

https://github.com/Asabeneh/30-Days-Of-JavaScript/blob/master/04_Day_Conditionals/04_day_conditionals.md
(This is JS repository, ours should also look like this only)

**Comment by msramesh2k1** [comment]
Can I work on this,I'm contributor in GWoC'21

**Comment by SurabhiMishra** [comment]
Can I please work on this.

**Comment by SurabhiMishra** [comment]
Can I please work on this.

**Comment by ViAsmit** [comment]
@msramesh2k1 can you take issue #136

**Comment by msramesh2k1** [comment]
> @msramesh2k1 can you take issue #136 ?

Sure

**Comment by yatharthrajput** [comment]
Can u pls assign me any work,I really want to contribute in this

**Comment by Simran1604** [comment]
I'd like to contribute to this issue.

**Comment by msbuddhu** [comment]
Hey @ViAsmit,
Shabi Kaushal this side. I am good at Cross-platform development using Dart and Flutter. I can implement them in practice lucidly as well as document them. May you assign me this task?

Shabi Kaushal (Android Development with Flutter Batch 10)
issue #448
