### ISSUE TITLE
C_CPP: Single Inheritance Documentation

### ISSUE THREAD

**Issue by Siddhartha-Dhar** [girlscript/winter-of-contributing#1341]
<hr>

## Description 📜

Documentation of Single Inheritance in C++
<hr>

## Domain of Contribution 📊

- [x] C/CPP
<hr>

**Comment by Suvraneel** [comment]
@Siddhartha-Dhar Go ahead

**Comment by SouravKr2001** [comment]
I am interested in contributing  documentation  for this issue

**Comment by iam-sakshi** [comment]
Hello ! I am interested in contributing documentation for this issue

**Comment by purohitmansi** [comment]
Please do assign this to me.
