### ISSUE TITLE
The workflow

### ISSUE THREAD

**Issue by himanshu007-creator** [girlscript/winter-of-contributing#1348]
<hr>

## Description 📜

To get started with any contribution in any project other than yours'  there is a certain order of things. There is a certain way of communicating with the maintainers. So it would be good to have a Workflow section in the readme within an opensource folder, to help beginners know how everything works out.

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

**Comment by Suvraneel** [comment]
Delete non-domains as directed in template

**Comment by Suvraneel** [comment]
@himanshu007-creator Kindly remake properly

**Comment by sakkshm26** [comment]
Hey, can I work on this issue?

**Comment by sakkshm26** [comment]
Shall I add the workflow section in the readme?

**Comment by Aryamanz29** [comment]
We don't need this issue now
Thanks
