### ISSUE TITLE
ML 1.3:   Central Limit Theorem 

### ISSUE THREAD

**Issue by kokila-Manogar** [girlscript/winter-of-contributing#1353]
<hr>

## Description 📜
This documentation will contain a detailed explanation (with examples) of the Central Limit Theorem. 
and also an audio/Video  about the real-life examples of these concepts for better understanding. 

- What is the Central Limit Theorem (CLT)?
- Significance of the Central Limit Theorem
- Statistical Significance
- Practical Applications
- Assumptions Behind the Central Limit Theorem
- Implementing the Central Limit Theorem in Python

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

**Comment by abhisheks008** [comment]
Do not create spam issues, without consulting with the supervisors! @kokila-Manogar
