### ISSUE TITLE
Competitive Coding: (Backtracking) Word Search

### ISSUE THREAD

**Issue by sr-sweta** [girlscript/winter-of-contributing#1357]
## Description 📜

Make Leetcode folder inside Competitive coding and add few codes of CP. Below is a backtracking problem
- Word Search

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming
- [x] DSA

**Comment by Anuj2403** [comment]
Name - Anuj Rouniyar
Batch - CP batch 1
I want to work on this issue, please assign
/assign
