### ISSUE TITLE
Flutter: Introduction to Dart

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#136]
A README file to understand dart programming language.

It should cover all the basics and some advanced topics of DART, and maybe sections can be divided into several contributors.

Those who want to contribute can comment the topics they would like to cover.

Topics to cover:
1. Dart Variables
2. Dart Data Types
3. Dart Functions
4. Dart Arrow Function
5. Dart Lists
6. Dart Conditionals
7. Dart classes and objects
8. Dart Class constructors
9. Any other topics that you may find useful

References: 
https://github.com/Asabeneh/30-Days-Of-JavaScript/blob/master/04_Day_Conditionals/04_day_conditionals.md
(This is JS repository, ours should also look like this only)

Dart: https://dart.dev/

**Comment by msramesh2k1** [comment]
Can I work on this.

**Comment by ViAsmit** [comment]
@msramesh2k1  Please tell me which topics you will be covering?
So that others can also take some topics in it

**Comment by msramesh2k1** [comment]
> @msramesh2k1 Please tell me which topics you will be covering?
> So that others can also take some topics in it

I can work on first 5 topics. @ViAsmit

**Comment by ViAsmit** [comment]
Ohk cool. Please see the JS Repository, I mentioned in the reference for folder structure and how to design README file.

**Comment by adityaraj079** [comment]
@ViAsmit you can assign me the rest topics.

**Comment by jaissumi1402** [comment]
@ViAsmit can you please assign me any work. I want to contribute

**Comment by ViAsmit** [comment]
@jaissumi1402 Sorry for the inconvenience. Wait for some time, we are having a meet with mentors soon. Once done, the work will be divided equally among yourself, and anyone won't have to rush for contribution.

till then - you can work on the remaining topics of issue #137

**Comment by jaissumi1402** [comment]
@ViAsmit okay sure I will wait. I want to contribute in documentation form.

**Comment by yatharthrajput** [comment]
@ViAsmit can you please assign me any work on flutter. I want to contribute

**Comment by yatharthrajput** [comment]
I am intrested,
I can work on Dart list

**Comment by Simran1604** [comment]
I'd like to contribute to dart class constructors.

**Comment by ViAsmit** [comment]
@msramesh2k1 have you done with this issue?

**Comment by ViAsmit** [comment]
@adityaraj079  I think you have two tasks assigned. can you tell me in which you are working so that I can assign other one to someone else

**Comment by msramesh2k1** [comment]
> @msramesh2k1 have you completed this issue?

Yeah I had made Pull request and requested my mentor to validate my pull request

**Comment by ViAsmit** [comment]
@msramesh2k1  you wrongly mentioned the issue, which was the video part, in the pull request. I corrected that

**Comment by msramesh2k1** [comment]
> @msramesh2k1  you wrongly mentioned the issue number, which was the video part, in the pull request. I corrected that

Oops sry and thanks

**Comment by adityaraj079** [comment]
> @adityaraj079 I think you have two tasks assigned. can you tell me in which you are working so that I can assign other one to someone else

Nopes this is the only task that i have been assigned till now.

**Comment by adityaraj079** [comment]
Also @ViAsmit You plz merge the PR made by @msramesh2k1 so that i can make my changes on that file

**Comment by ViAsmit** [comment]
@adityaraj079 wait for some time. let mentor validate that PR. then  you can fo the changes

**Comment by DarthSalad** [comment]
@ViAsmit 
I would like to work on the Dart: Classes and Objects part
Can you assign the issue to me?

**Comment by arcAman07** [comment]
I would like to contribute to this issue, so can I take some topics

**Comment by adityaraj079** [comment]
Hey @ViAsmit this issue's PR is now merged 
I request you to please close this issue so that we can work on other issues.
