### ISSUE TITLE
Android-Kotlin : 07.1 LinearLayout in Kotlin

### ISSUE THREAD

**Issue by Narotam-singh** [girlscript/winter-of-contributing#1362]
<hr>

## Description 📜

I wanted to work on LinearLayout in Kotlin by making documentation.
Kindly assign this to me @rahulsain 

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Kotlin)

<hr>

**Comment by sitamadex11** [comment]
@rahulsain please add the **Android-Dev-Kotlin** label here.
