### ISSUE TITLE
JAVA 3.4: Single Dimensional Array (Implementation) 

### ISSUE THREAD

**Issue by pavankapoor31** [girlscript/winter-of-contributing#1370]
<hr>

## Add Implementation of Single Dimension Array in Java📜

<hr>
## Domain of Contribution 📊

- [x] Java_Domain

<hr>

**Comment by AkMo3** [comment]
Are we not clear when we say that issue creation is not allowed. Why are you guys constantly creating your own issues. This is being closed permanently.
