### ISSUE TITLE
Number Theory in Competitive Programming

### ISSUE THREAD

**Issue by Perpetual-Incantation** [girlscript/winter-of-contributing#1384]
<hr>

## Description 📜

Find all factors of a natural number . 
Write the code and describe the algorithm used?

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

**Comment by Safwan310** [comment]
Wait... What is this??? Why is every domain tagged?

**Comment by Suvraneel** [comment]
@Perpetual-Incantation  @Safwan310 

Delete all other domains from your comment.. like mentioned in PR template directives
Kindly follow the issue template from next time ... & preach this to your fellow contributors

**Comment by Suvraneel** [comment]
@Perpetual-Incantation  Perfect ... Preach this to your peers too :)

**Comment by Perpetual-Incantation** [comment]
Hey, I have edited this before. You can check it out also.

**Comment by sarav18302** [comment]
\assign Can I work on this issue because I have been working on Number theory for Competitive programming

**Comment by Perpetual-Incantation** [comment]
@Suvraneel Please review my code.

**Comment by Perpetual-Incantation** [comment]
@Rishabh510 Please review my code.
