### ISSUE TITLE
DS-R: 1.1.DOC History - History of R Language

### ISSUE THREAD

**Issue by micepram** [girlscript/winter-of-contributing#139]
<hr>

## Description 📜

In this issue, you need to work on the documentation efforts in the "History" section under the "History of R language" subsection. Please ensure that you document in detail.

> https://bookdown.org/rdpeng/rprogdatascience/history-and-overview-of-r.html
> https://www.stat.auckland.ac.nz/~ihaka/downloads/Massey.pdf

<hr>

## Domain of Contribution 📊

- [x] Datascience with R

<hr>

## Instructions ✔

* Kindly make a README going over the subtopic.
* Changes should be made under **Datascience_With_R** branch only and push your PR to the same.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

<hr>

**Comment by TechnoPhasePRO** [comment]
@micepram hey, I would like to work on this issue. Please assign me this.

**Comment by TechnoPhasePRO** [comment]
please add gwoc label.

**Comment by micepram** [comment]
Sure, all the best!

**Comment by TechnoPhasePRO** [comment]
@micepram there is no such ds-r/ directory under data science with R. should I create this directory?

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M . I would like to do documentation on this issue.

**Comment by micepram** [comment]
Yes @TechnoPhasePRO create it. Also @deepthi1107 you can work together @TechnoPhasePRO together on this.

**Comment by deepthi1107** [comment]
sure, thanks for the opportunity.

**Comment by micepram** [comment]
Hey @deepthi1107, we are going to be limiting issues to one person only due to logistics. Each Top (1.1, 1.2, etc.) will have 3 issues for 1 for Documentation, 1 for Audio, 1 for Video and hence will only have one person assigned. I'll be removing you from this assignment and request you to choose another issue. There will be plenty coming in soon. Thank you :)

**Comment by micepram** [comment]
@TechnoPhasePRO what's the update?

**Comment by TechnoPhasePRO** [comment]
@micepram sorry but I'm having some problems with the head branch in git as its detached. Due to which my commits are not authorized under correct credential . That's why its taking long to resolve it.

**Comment by TechnoPhasePRO** [comment]
@micepram please delete my other commits and merge my PR as it is not possible to squash all commits from my end.

**Comment by TechnoPhasePRO** [comment]
@micepram please merge my PR and also plz squash other commits i have made.

**Comment by micepram** [comment]
Merged, closing.
