### ISSUE TITLE
Frontend : Introduction to HTML

### ISSUE THREAD

**Issue by VidhiDixit2000** [girlscript/winter-of-contributing#1396]
<hr>

## Description 📜

I want to add Documentation on this topic.
Assign this issue to me.

<hr>

## Domain of Contribution 📊

- [X]  Frontend Dev HTML/CSS/JS

<hr>

**Comment by CSAURABH** [comment]
@VidhiDixit2000 I already created this issue

**Comment by VidhiDixit2000** [comment]
Ok
