### ISSUE TITLE
CSS cheatsheet

### ISSUE THREAD

**Issue by abhi-2024** [girlscript/winter-of-contributing#1404]
## DESCRIPTION

CSS cheatsheet which will guide you through your day to day work.

## Domain

- Frontend Dev HTML/CSS/JS

## Type of Contribution

Audio, Video, Documentation

## Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Kamya123** [comment]
/assign
Please assign me this work. I know CSS3 very well and implemented almost all properties. So, I think I will do it very nicely.
