### ISSUE TITLE
Implementation of AVL tree in C++

### ISSUE THREAD

**Issue by sandeepkumar00110** [girlscript/winter-of-contributing#1419]
<hr>

## Description 📜

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by sandeepkumar00110** [comment]
i want to work on this

**Comment by Pawanupadhyay10** [comment]
hey pls assign this issue to me

**Comment by sandeepkumar00110** [comment]
@Suvraneel please review

**Comment by Suvraneel** [comment]
@sandeepkumar00110  Link this issue no. to your PR properly..
