### ISSUE TITLE
DS-R: 1.X Video

### ISSUE THREAD

**Issue by micepram** [girlscript/winter-of-contributing#142]
## Description :
This issue for making a video covering all the topics under DS-R 1.X mentioned below. 
* History of R language
* History of Data Science
* Roots of Data Science with R

## References :
> https://bookdown.org/rdpeng/rprogdatascience/history-and-overview-of-r.html
> https://www.stat.auckland.ac.nz/~ihaka/downloads/Massey.pdf
> https://datasciencedegree.wisconsin.edu/blog/history-of-data-science/
> https://bookdown.org/rdpeng/rprogdatascience/
> https://blog.paperspace.com/intro-to-datascience/

* Kindly make the video and attach the link in a text/markdown file going over the 1.X topics.
* Changes should be made in **DS-R/** directory under **Datascience_With_R** branch.
* You have to push your PR to the **Datascience_With_R** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by kunal-kumar-chaudhary** [comment]
hey! I would like to work on this!

**Comment by micepram** [comment]
Great, I'll assign you!

**Comment by kunal-kumar-chaudhary** [comment]
> Great, I'll assign you!

I've few questions:-

1. what should be the length of the video?
2. should my face be visible in the corner of the video?
3. is there any sort of deadline?

will be great if you can clarify these doubts!

**Comment by micepram** [comment]
1) Just be clear and concise while covering the entire topic, whatever length it maybe.
2) That's up to you, but make sure it doesn't cover more than 15% of the width/height.
3) Deadline is till 31st November, 2021 but try to finish before that.

**Comment by micepram** [comment]
Hey @kunal-kumar-chaudhary this issue will be closed and replaced with 3 separate ones for 1.1, 1.2, 1.3. Kindly assign yourself to one of those and keep working :)
