### ISSUE TITLE
GoLang: 8.2.DOC Concurrency - Goroutines

### ISSUE THREAD

**Issue by amino19** [girlscript/winter-of-contributing#1427]
<hr>

## Description 📜
**Goroutines**
Basic-Intermediate-Advanced information about `Goroutines` in Golang, also needs to create some examples.
This must be inside `Concurrency` folder. 

**References:**
- [Geeks for Geeks](https://www.geeksforgeeks.org/goroutines-concurrency-in-golang)
- [A Tour of Go](https://tour.golang.org/concurrency/1)
- [gobot](https://golangbot.com/goroutines/)

<hr>

## Domain of Contribution 📊

- [x] Golang

<hr>

## Instructions ✔

* Kindly make a README going over the subtopic.
* Changes should be made under the **Golang** branch only and push your PR to the same.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by LegendSumeet** [comment]
@avishj assign me

**Comment by amino19** [comment]
@LegendSumeet: Yep sure to pick this up, you just need to write:
```
/assign
```
& it'll gonna auto the process. :slightly_smiling_face:

**Comment by avishj** [comment]
Merged.
