### ISSUE TITLE
Android-Java: 2.8 Overview of Android Architecture

### ISSUE THREAD

**Issue by sitamadex11** [girlscript/winter-of-contributing#143]
## Description :
**Give an overview of the main components of the android architecture are following**:-
* Applications
* Application Framework
* Android Runtime
* Platform Libraries
* Linux Kernel

## References :
> https://www.tutorialspoint.com/android/android_architecture.htm
> https://www.geeksforgeeks.org/android-architecture/

* Changes should be made in **Android_Development/Java/** directory under **Android_Development_With_Java** branch.
* You have to push your PR to the **Android_Development_With_Java** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by Priyanshirathore** [comment]
Can I work on it @VikasPandey121 sir?

**Comment by sitamadex11** [comment]
@Priyanshirathore ya sure, you can go for it.

**Comment by Priyanshirathore** [comment]
okay, sir, do I have to push one single word file containing all the subheadings, or should I have different files for different subheadings?

**Comment by LegendSumeet** [comment]
can you assign this work to me? @Priyanshirathore

**Comment by Priyanshirathore** [comment]
> can you assign this work to me? @VikasPandey121 sir

Actually, I already started working on it. You can work on my other issue, Layouts in Android if you want.

**Comment by LegendSumeet** [comment]
> > can you assign this work to me? @VikasPandey121 sir
> 
> Actually, I already started working on it. You can work on my other issue, Layouts in Android if you want.

but you are not assign to it?

**Comment by Priyanshirathore** [comment]
I am assigned to both of the issues.

**Comment by Priyanshirathore** [comment]
@sitamadex11 sir please look into the PR, I gave the access. 
https://github.com/girlscript/winter-of-contributing/pull/193
