### ISSUE TITLE
Cybersecurity: 1.9.6 CIA triad.

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#144]
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with **Diagrams**.
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on **first come first serve**
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by I-Infinatoo** [comment]
Can I do this ?

**Comment by Anant1711** [comment]
> Can I do this ?

Sure!
I'm assigning this task to you!

**Comment by Sejalm12** [comment]
Cn i do this task in Documentation?

**Comment by Anant1711** [comment]
> Cn i do this task in Documentation?

The documentation has already taken!
You can submit in Video format If you want!
