### ISSUE TITLE
Android-Java: 2.9 Overview of Android-Application Components

### ISSUE THREAD

**Issue by sitamadex11** [girlscript/winter-of-contributing#146]
## Description :
**Give an overview of the main components of the Android-Application**:-
* Activities
* Services
* Broadcast Receiver
* Content Providers

## References :
> https://www.tutorialspoint.com/android/android_application_components.htm
> https://www.geeksforgeeks.org/components-android-application/
> https://developer.android.com/guide/components/fundamentals?authuser=2

* Changes should be made in **Android_Development/Java/** directory under **Android_Development_With_Java** branch.
* You have to push your PR to the **Android_Development_With_Java** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by Yugal41735** [comment]
I can work on this.

**Comment by sitamadex11** [comment]
@Yugal41735 ya, you can go for this.

**Comment by LegendSumeet** [comment]
csn you assign me to these?

**Comment by SouravKr2001** [comment]
Ya i am interested in contributing via documentation plz assign it to me

**Comment by Yugal41735** [comment]
@sitamadex11 I had made a pull request. Please review it. 
link of the pr => https://github.com/girlscript/winter-of-contributing/pull/1287
