### ISSUE TITLE
Cybersecurity: 2.9.3 Firewall

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#1479]
<hr>

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [x] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by I-Infinatoo** [comment]
Can I do the Documentation part ?

**Comment by medhatiwari** [comment]
Please assign this to me @Anant1711

**Comment by Anant1711** [comment]
> Can I do the Documentation part ?

Go with `Documentation`

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.Please consider me for this..
Riya Pandey
Batch-2

**Comment by Anant1711** [comment]
> I would like to contribute to this via documentation.Please consider me for this..
> Riya Pandey
> Batch-2

Sorry @riyapandey730 Documentation is already done!
you can contribute in `Video`
And cybersecurity has only 1 batch I guess!
