### ISSUE TITLE
Cybersecurity: 1.9.7 Types of Hackers.

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#148]
### Discuss 8 Types of Hackers:

 - White Hat Hackers.
 - Black Hat Hackers.
 - Gray Hat Hackers.
 - Script Kiddies.
 - Green Hat Hackers.
 - Blue Hat Hackers.
 - Red Hat Hackers.
 - State/Nation Sponsored Hackers.
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with Diagrams
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by ankitjha2711** [comment]
Sir, i want to do this work

**Comment by 0shivamh** [comment]
I would like to work on this

**Comment by Anant1711** [comment]
> Sir, i want to do this work

How you will contribute? In documentation or in Video format?

**Comment by anjanaaaaaaaa** [comment]
can i take this in documentation

**Comment by ankitjha2711** [comment]
> > Sir, I want to do this work
> 
> How you will contribute? In documentation or Video
Video sir, but if u want it in documentation, that will be also fine for me.

**Comment by Manmeet2607** [comment]
sir please assign me this issue i would contribute in both image and documentation form

**Comment by Anant1711** [comment]
> > > Sir, I want to do this work
> > 
> > 
> > How you will contribute? In documentation or Video
> > Video sir, but if u want it in documentation, that will be also fine for me.

Okay! I'm assigning this task to you for video submission!

**Comment by Anant1711** [comment]
> sir please assign me this issue i would contribute in both image and documentation form

@Manmeet2607 
For documentation already Anjana comment! Even after that, I have to ask another person also, So no chance for this issue until and unless they all are unable to submit their work on time!
Hope you understand!

**Comment by Anant1711** [comment]
@anjanaaaaaaaa You want to submit in documentation form, but before your comment, @0shivamh also commented!

so @0shivamh would you like to work with documentation?
or I'll pass it to @anjanaaaaaaaa?

**Comment by anjanaaaaaaaa** [comment]
> @anjanaaaaaaaa You want to submit in documentation form, but before your comment, @0shivamh also commented!
> 
> so @0shivamh would you like to work with documentation?
> or I'll pass it to @anjanaaaaaaaa?

I'll take some other issue

**Comment by 0shivamh** [comment]
@Anant1711 , Yes I would like to work on doc.

**Comment by Anant1711** [comment]
> @Anant1711 , Yes I would like to work on doc.

Okay!
I'm assigning this task to you for `Documentation`

**Comment by Sejalm12** [comment]
I would like to take this task for Documentation.

**Comment by Anant1711** [comment]
> I would like to take this task for Documentation.

Sorry @Sejalm12 , Documentation is already done!

**Comment by Anant1711** [comment]
Documentation is completed!

@ankitjha2711 Any update for video submission?

**Comment by ankitjha2711** [comment]
> Documentation is completed!
> 
> @ankitjha2711 Any update for video submission?

Today, I will try to complete that, sir

**Comment by Anant1711** [comment]
> > Documentation is completed!
> > @ankitjha2711 Any update for video submission?
> 
> Today, I will try to complete that, sir

Yes, PLEASE

**Comment by ankitjha2711** [comment]
sir i am done with video but i don't know how to submit the link.

**Comment by Anant1711** [comment]
> sir i am done with video but i don't know how to submit the link.

Upload your Video on google drive and then make a .md file in the week_1 folder and then drop your video link in this format!
`[![Your_video_title](Your_video_thumbnail_photo_link)](Your_vide_link "Your_video_title")`

**Comment by ankitjha2711** [comment]
![image](https://user-images.githubusercontent.com/76564889/133951368-09c52aec-34e9-4b3a-ad24-87249a38595b.png)

**Comment by ankitjha2711** [comment]
Sir it is showing me like this

**Comment by Anant1711** [comment]
Yeah! You had to add cybersecurity: before your title name.
But okay this time, I reviewed your PR!
Kindly check the comment!
