### ISSUE TITLE
C/CPP: Concept of OOPS

### ISSUE THREAD

**Issue by ketkikaushik** [girlscript/winter-of-contributing#1480]
<hr>

## Description 📜

This documentation will contain detailed explanation (with examples) of Concept of OOPS in C/CPP that includes:

Object
Class
Inheritance
Polymorphism
Abstraction
Encapsulation.

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

**Comment by Suvraneel** [comment]
Its already been said...
Take 1 small topic & make an elaborate documentation
