### ISSUE TITLE
Cybersecurity: 2.9.4 LAN

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#1481]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by medhatiwari** [comment]
Please assign the `Documentation` part to me @Anant1711

**Comment by Anant1711** [comment]
> Please assign the `Documentation` part to me @Anant1711

Okay, Go with the `Documentation` part!

**Comment by iamKushGupta** [comment]
Is documentation assigned just now or video ?

**Comment by iamKushGupta** [comment]
If not, then Can I be assigned Documentation ?

**Comment by Anant1711** [comment]
> If not, then Can I be assigned Documentation ? (Not video)

No, the `Documentation` part is taken!

**Comment by medhatiwari** [comment]
@Anant1711 Should I also explain different topologies?

**Comment by Anant1711** [comment]
> @Anant1711 Should I also explain different topologies?

NO, you have to explain LAN with respect to cybersecurity, (BUS, RING topologies are not useful in this).
You have to explain What is LAN what area it will be covered, its advantages (for security purposes), its disadvantages/limitations for Security purposes!

**Comment by medhatiwari** [comment]
> > @Anant1711 Should I also explain different topologies?
> 
> NO, you have to explain LAN with respect to cybersecurity, (BUS, RING topologies are not useful in this).
> You have to explain What is LAN what area it will be covered, its advantages (for security purposes), its disadvantages/limitations for Security purposes!

Got it!
Thank-you

**Comment by HumblePlebeian** [comment]
Hi, 
I would like to work on the video form of contribution for this issue.
Could you please assign it to me?

Thanks!

**Comment by Anant1711** [comment]
> Hi,
> I would like to work on the video form of contribution for this issue.
> Could you please assign it to me?
> 
> Thanks!

That's Great!😊
Go with it!
