### ISSUE TITLE
Open Source : 4.2 Explain Everything related to `GSOC`

### ISSUE THREAD

**Issue by HassanRahim26** [girlscript/winter-of-contributing#1497]
<hr>

## Description 📜

In this issue I'm going to explain everything related to Google Summer of Code(GSOC).  

<hr>

## Domain of Contribution 📊

- [x] Open Source

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

**Comment by HassanRahim26** [comment]
> Hello @HassanRahim26,
> Thank you for opening an issue. :octocat:
> Note - Self-assigns by the original author will be prioritised by mentors manually
> To get assigned to this particular issue please use /assign
> Check this [guide](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) before contributing.

/assign

**Comment by mayankkuthar** [comment]
It has already been merged and closed Issue #263 and  PR #311
