### ISSUE TITLE
Frontend with framework-React:Intro To Redux 

### ISSUE THREAD

**Issue by Ananyagupta43** [girlscript/winter-of-contributing#1498]
<hr>

## Description 📜

- What is Redux ?
- How Should we use it?
- Why should we use Redux ?
- When should we avoid using Redux ?

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev React/Angular/Vue

<hr>

**Comment by Ananyagupta43** [comment]
@mukeshmjn Sir I created this issue.Please check it and please remove the Frontend Dev HTML/CSS/JS tag.

**Comment by mukeshmjn** [comment]
Removed the tag @Ananyagupta43 . @anandhu720 will check it

**Comment by Ananyagupta43** [comment]
ok sir .

**Comment by anandhu720** [comment]
Please dont create this issue right now.We are planning issues as per roadmap.
