### ISSUE TITLE
Android-Kotlin : 02.5 Functions in Kotlin

### ISSUE THREAD

**Issue by anantcodes** [girlscript/winter-of-contributing#1499]
<hr>

## Description :scroll:

* Give a description of functions in Kotlin.
*  Required Documentation or Video or Audio.

<hr>

## Domain of Contribution :bar_chart:

- [x] Android Dev (Kotlin)

<hr>

<hr>

## References :
https://kotlinlang.org/docs/functions.html
https://www.geeksforgeeks.org/kotlin-functions/

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in Android_Development_With_Kotlin/ directory under Android_Development_With_Kotlin branch.
* You have to push your PR to the Android_Development_With_Kotlin branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.
>Supervisor @rahulsain

## Happy Contributing. Best of Luck.:sparkling_heart:

**Comment by mrkc2303** [comment]
I want to work on this issue in the video section.
Kanishk Chhabra here! (Batch-1, Android-Development-Kotlin)

**Comment by eshan1925** [comment]
@anantcodes I have created a PR you can merge if everything is good to go.
ThankYou

**Comment by eshan1925** [comment]
@anantcodes This is the correct PR. Please merge if there is no issue.

**Comment by mrkc2303** [comment]
Was out of station, trying to complete it ASAP now.

**Comment by ayush-sleeping** [comment]
hey @rahulsain , assign me this for  " Audio  " section . <br>
I would to like to fixed the  "  Audio  " part of this issue .......

**Comment by rahulsain** [comment]
> Was out of station, trying to complete it ASAP now.

Any updates?

**Comment by mrkc2303** [comment]
Hey @rahulsain,
I had to undergo a surgery a few days ago. 
I have recorded the video, will upload it by today!
Thanks for your Understanding
