### ISSUE TITLE
Cybersecurity: 1.9.8 Introduction to IT Act 2000.

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#150]
## Description
The Information Technology Act, 2000 serves as the de facto framework for digital governance in India.
## Note:
- If interested, mention in which format you want to contribute either in `Documentation` or in `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with **Diagrams**
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security` branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by prithwishpramanik** [comment]
sir, i want to do this work the documentation part

**Comment by anjanaaaaaaaa** [comment]
I can do it in video format

**Comment by Anant1711** [comment]
> sir, i want to do this work the documentation part

Okay!
I'm assigning this task to you for `Documentation`!

**Comment by Anant1711** [comment]
> I can do it in video format

okay!
Assigned for `Video` submission!

**Comment by Anant1711** [comment]
Great work Guyz!
