### ISSUE TITLE
Cybersecurity: 1.9.9 Limitations of Indian IT Act, 2000

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#151]
## Description
The Information Technology Act, 2000 serves as the de facto framework for digital governance in India. It has its limitation also.
## Note:
 - If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with Diagrams
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by kar-cloud** [comment]
i want to contribute on this in documentation form

**Comment by Anant1711** [comment]
> i want to contribute on this in documentation form

Okay!
Assigned for `Documentation`!
