### ISSUE TITLE
JS browser object model(BOM)

### ISSUE THREAD

**Issue by Surbhi-sinha** [girlscript/winter-of-contributing#1513]
<hr>

## Description 📜

In this particular section, I would be making a document-based contribution to javascript browser object modeling and its basic functionality.

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [x ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by Surbhi-sinha** [comment]
In this particular section, I would be making a document-based contribution to javascript browser object modeling and its basic functionality. Please assign it to me.
/assign

**Comment by Suvraneel** [comment]
@Surbhi-sinha remove non-domains 7 reopen
