### ISSUE TITLE
Flutter: Exercises for Intro_To_Dart

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#152]
Edit the exercise.md file present inside Flutter/Intrduction_To_Dart, to add questions related to dart programming, along with thier solution.

Reference: https://github.com/Asabeneh/30-Days-Of-JavaScript/blob/master/04_Day_Conditionals/04_day_conditionals.md#exercises-level-1

Anyone can do contribution, I am not assigning to anyone but comment before working on which topic you will be adding the question. (Max 3 questions per topic), so that other contributors should not add question related to that topic.

**Comment by Niranjan5601** [comment]
Interested.
I'll add probs based on conditionals

**Comment by jaissumi1402** [comment]
Interested
I'll add problems on parameters

**Comment by rithish26** [comment]
Intrested 
I'll add problems on operators

**Comment by naveeramesh** [comment]
I would like to work on functions.

**Comment by msramesh2k1** [comment]
I wish to add excercise on classes and objects.

**Comment by PranavMasekar** [comment]
I wish to add excercise on maps and list data types.

**Comment by ViAsmit** [comment]
Don't take more than one issue at a time..

**Comment by Safwan310** [comment]
Interested, I would like to work on Array Utility Methods like forEach(), map() etc...

**Comment by naveeramesh** [comment]
> Don't take more than one issue at a time..

I have completed the first issue assigned for me, can I do now the exercise for functions?

**Comment by ViAsmit** [comment]
@naveeramesh contact you mentor first so that he can validate your contribution.. once done then only do further contribution

**Comment by Safwan310** [comment]
> @naveeramesh contact you mentor first so that he can validate your contribution.. once done then only do further contribution

**Comment by Safwan310** [comment]
@ViAsmit can you assign the work I commented for?

**Comment by Simran1604** [comment]
I'd like to contribute for inheritance concept in Dart.

**Comment by naveeramesh** [comment]
@ViAsmit can I contribute now to the exercise based on functions?

**Comment by msbuddhu** [comment]
Interested,
I'll add problems on Strings. Please assign me this task.

Shabi Kaushal (batch 10)

**Comment by ViAsmit** [comment]
Now no more topics on this issue... This much will be ok..

**Comment by PranavMasekar** [comment]
@thisisamank

**Comment by thisisamank** [comment]
Hi @PranavMasekar Thanks for tagging. Your PR just got merged and it looks good to me too.

**Comment by msbuddhu** [comment]
Hey, I have created a PR for the issue I was assigned. [https://github.com/girlscript/winter-of-contributing/pull/535](https://github.com/girlscript/winter-of-contributing/pull/535). Please have a look @thisisamank

**Comment by ViAsmit** [comment]
@msbuddhu  I have edited your PR.. how to add the issue number in PR. Have a look on that. so that you wont get confused again

**Comment by msbuddhu** [comment]
Ok. I have seen. Thanks

**Comment by Niranjan5601** [comment]
Ill add probs for loop statements and format the document to look clean and uniform.

**Comment by msbuddhu** [comment]
@ViAsmit Why I have been unassigned?

**Comment by ViAsmit** [comment]
@msbuddhu actually I was removing who have completed thier contribution...so that I can take a record who are still left...

**Comment by msbuddhu** [comment]
> @msbuddhu actually I was removing who have completed thier contribution...so that I can take a record who are still left... 

Ok. No problem then.

**Comment by msbuddhu** [comment]
I have mentioned @thisisamank in the comments above. Now what to do @ViAsmit ?

**Comment by ViAsmit** [comment]
@msbuddhu I think you already mention aman... He will review it...

**Comment by msbuddhu** [comment]
> @msbuddhu He will review it soon..you can take rest now...

Ok :)
