### ISSUE TITLE
Data Science with Python : IRIS Dataset Classification using Different Approaches

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1525]
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with IRIS Dataset Classification. Tutorial to IRIS Dataset Classification and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Gauri Bharadwaj / Jivitesh Jain

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by srini047** [comment]
I would like to work on this issue.
Name: Sriniketh J
Batch No: 17
Serial No: 613
Type: Documentation

**Comment by srini047** [comment]
!assign

**Comment by prathimacode-hub** [comment]
Issue assigned to @srini047 for documentation. Also let me know of your approach you would follow.

**Comment by srini047** [comment]
Approach: Perform Data Analysis, Data Visualizations, Data Preprocessing, and Model Building using different Algorithms like DecisionTree, KNN, LogisticRegression. Also, visualize DecisionTree pictorially.

**Comment by ayushijindal** [comment]
Kindly assign me this issue
Format: Video 
Approach: Detail explanation of Iris dataset using different approaches in video format
Serial no: 253
@prathimacode-hub

**Comment by deepthi1107** [comment]
Hello mam @prathimacode-hub, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
