### ISSUE TITLE
Data Science with Python : K means Clustering Algorithm

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1527]
Welcome to 'DSWP' Team, good to see you here.

This issue will helps readers in acquiring all the knowledge to learn about getting involved with K means Clustering Algorithm. Tutorial to K means Clustering Algorithm and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Arya Patel / Nithin

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ayushi424** [comment]
Name: Ayushi Shrivastava
Batch: 19
Sno: 811
Approach to be followed:
Getting a  example dataset to implement this ML model.
- Data Preprocessing
- Data Visualization
- Data Training 
- Data modelling
- Performance check by accuracy score.

**Comment by ayushi424** [comment]
**/assign**

**Comment by prathimacode-hub** [comment]
Issue assigned to @ayushi424 for documentation

**Comment by ShubhamPatel01** [comment]
@prathimacode-hub 
I would like to work on this issue, which is issue no. 1527
Name: Shubham Patel
Serial No. 104.
Type: Video
Approach:

- Introduction to K-Means Clustering

- Working of K-Means Clustering algorithm and implementing it.

- Application of K-Means Clustering algorithm

**Comment by prathimacode-hub** [comment]
Issue assigned to @ShubhamPatel01 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation of the issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
