### ISSUE TITLE
Flutter: NULL Safety 

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#153]
README file to understand NULL Safety feature of DART(Only Basic)

Reference:
https://dart.dev/

**Comment by rithish26** [comment]
Intrested to contribute

**Comment by 2002Bishwajeet** [comment]
Can you assign this issue to me?

**Comment by ViAsmit** [comment]
Anyone if you have already taken one contribution please don't comment on any other issue
