### ISSUE TITLE
Update roadmap for Frontend web development

### ISSUE THREAD

**Issue by emily876** [girlscript/winter-of-contributing#1537]
<hr>

## Description 📜

The readme file for frontend web dev in HTML, CSS, and js is not complete. So I want to include topics for
- JavaScript, HTML, and CSS Project
- Deploying Your App
<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

**Comment by AkMo3** [comment]
@emily876 On which content are you willing to work?

**Comment by AkMo3** [comment]
My bad, mistakes have been corrected!. Go on with your work 👍
