### ISSUE TITLE
Flutter: Info about Flutter

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#154]
README File to get information related to how flutter started. how flutter evolved, how  flutter works, who owns flutter, timeline, etc

**Comment by rithish26** [comment]
interested to contribute.

**Comment by Niranjan5601** [comment]
Can you assign this work to me .

**Comment by AdityaChaudhary18** [comment]
Interested

**Comment by ViAsmit** [comment]
Sorry for inconvenience to others... You can contribute on exercise issue ...  We will be having a more uniform way to divide the work soon.. wait for some time

**Comment by ViAsmit** [comment]
@rithish26 am closing this issue...as it contain onlu irrelevant information.

**Comment by ViAsmit** [comment]
@rithish26  I am closing this issue as it contains irrelevant information please do not work on it
