### ISSUE TITLE
DSA: Spiral Print of 2D Array

### ISSUE THREAD

**Issue by themonikanayak** [girlscript/winter-of-contributing#1547]
<hr>

## Description 📜

Write documentation regarding the approach as well as code for a spiral print of a 2d array.
<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming

- [x] DSA

- [x] Interview Prep

<hr>

**Comment by arsheelsheikh** [comment]
@themonikanayak I have made PR can you merge it ASAP!

**Comment by nimisha-yadav** [comment]
> 
> 
> @themonikanayak I have made PR can you merge it ASAP!

She herself is a contributor and not a maintainer. You should check before making PRs. I advise you to create a fresh issue on 2D array. @arsheelsheikh

**Comment by nimisha-yadav** [comment]
@themonikanayak Create one PR pertaining to one issue and one topic. Do not make several PRs based on single issue.

**Comment by arsheelsheikh** [comment]
@nimisha-yadav I thought only Mentors or Supervisors are entertained to make new issues.
anyways now I have already made a new PR what about that !!

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav I thought only Mentors or Supervisors are allowed to make new issues.
> anyways now I have already made a new PR what about that !!

You should read the guidelines mentioned in the readme and contributing.md files before getting started. Nevertheless no worries, just create a new issue mentioning the topic and the problem statement, and link your PR to that issue number. Once done, tag me. I'll review. @arsheelsheikh

**Comment by arsheelsheikh** [comment]
Ok done, tagged you there
