### ISSUE TITLE
ML 1.11: Skewness (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1555]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Skewness**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by karma659** [comment]
Name - Akash Karmakar
Batch - 5
profile -https://github.com/karma659
type - Documentation

**Comment by Isha307** [comment]
@karma659 This issue is about audio, you have to contribute through audio only.

**Comment by abhisheks008** [comment]
What is the update @karma659 ? It's been 3 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by karma659** [comment]
yes  doing   the PR
