### ISSUE TITLE
ML 1.12: Confusion Matrix (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1557]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Confusion Matrix**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

**Comment by vanshhhhh** [comment]
Vansh Sharma, Batch 3, [Github profile](https://github.com/vanshhhhh)

**Comment by BasuDevTyagi10** [comment]
I would like to work on this issue.
Name: Basudev Tyagi
Batch: ML Batch-6
Type: Documentation

**Comment by Praannjaal** [comment]
/assign 
Name: Pranjal Mittal
Batch: 6
Type: Documentation

**Comment by Isha307** [comment]
@BasuDevTyagi10 @Praannjaal This issue is already assigned :)

**Comment by abhisheks008** [comment]
What is the update @vanshhhhh ? It's been 4 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!
