### ISSUE TITLE
ML 1.12: Confusion Matrix (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1558]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Confusion Matrix**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Machine Learning
Batch-6
Issue Number-1558                                                                                                                                                     
Contribution Approaches-about confusion matrix, how it helps in determining accuracy, about TP TN FP FN
/assign

**Comment by abhisheks008** [comment]
@BhaswatiRoy one issue at a time!

**Comment by nakshatra-garg** [comment]
Batch - 1
I want to contribute to the documentation part of this issue.
Approach:
I'll Explain the confusion matrix by taking an appropriate classification example.

**Comment by nakshatra-garg** [comment]
Batch - 1
I want to contribute to the documentation part of this issue. @abhisheks008 
Approach:
I'll Explain the confusion matrix by taking an appropriate classification example.

**Comment by tavneetgill** [comment]
I want to contribute this issue.
Full name-Tavneet Kaur Gill
Batch Number-2
GitHub Profile Link-https://github.com/tavneetgill
Contribution Type-Audio
Issue number-1558
Contribution approaches-basic definition, detailed explanation with examples and sample codes, formulas, where is is used
/assign

**Comment by Isha307** [comment]
@Nay907 you can work on this issue.

**Comment by Nay907** [comment]
Thank you @Isha307

**Comment by abhisheks008** [comment]
What is the update @Nay907 ? It's been 3 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by Nay907** [comment]
Sorry for the delay!! I will be doing it soon!
