### ISSUE TITLE
ML 1.12: Confusion Matrix (V) 

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1560]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Confusion Matrix**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by samridhikapoor** [comment]
I would like to contribute for this issue. I request you to assign me the same.
Thanks 

Name: Samridhi Kapoor
Batch No.: 3
Github Profile link: https://github.com/samridhikapoor
Type of contribution I want to make: Video (as specified)

**Comment by Rishita11** [comment]
I would like to contribute to this issue. Please assign me.

Name: Rishita Srivastava
Batch No: 1
Github profile link: https://github.com/Rishita11 
Type of contribution: Documentation

**Comment by monalsingh10** [comment]
/assign
documentation

**Comment by monalsingh10** [comment]
I would like to contribute in this issue. Please assign me for this position:-
Name :Monal Singh
Batch Number: 5
Github profile link: https://github.com/monalsingh10
contribution Type:Documentation

**Comment by abhisheks008** [comment]
@samridhikapoor please make the PR ASAP.

**Comment by samridhikapoor** [comment]
> @samridhikapoor please make the PR ASAP.

This is regarding my progress on the PR. 
I am presently working on my PR. As I have been assigned the video contribution, so I am making a PPT on this topic. I will surely complete the PPT by today evening and then upload the video ASAP

Thanks

**Comment by abhisheks008** [comment]
Good, do it by this evening. @samridhikapoor
