### ISSUE TITLE
GoLang: 9.3.DOC OOP - Polymorphism

### ISSUE THREAD

**Issue by amino19** [girlscript/winter-of-contributing#1573]
<hr>

## Description 📜
**Polymorphism**
Basic-Intermediate-Advanced information about `Polymorphism` in Golang, also needs to create some examples.
This must be inside the `Object-Oriented Programming` folder. 

**References:**
- [Geeks for Geeks](https://www.geeksforgeeks.org/polymorphism-in-golang/)
- [Go By Example](https://golangdocs.com/polymorphism-in-golang)
- [golangbot](https://golangbot.com/polymorphism/)

<hr>

## Domain of Contribution 📊

- [x] Golang

<hr>

## Instructions ✔

* Kindly make a README going over the subtopic.
* Changes should be made under the **Golang** branch only and push your PR to the same.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by eshan1925** [comment]
Hey, @amino19 Please review the code. I have created the PR.
THANK YOU
