### ISSUE TITLE
GoLang: 10.0.DOC Defer and Error Handling

### ISSUE THREAD

**Issue by amino19** [girlscript/winter-of-contributing#1579]
<hr>

## Description 📜
**Defer and Error Handling**
with some description about:

- [Defer](https://www.geeksforgeeks.org/defer-keyword-in-golang/)
- [Error & Exception Handling](https://golangdocs.com/errors-exception-handling-in-golang)
- [Custom Errors](https://www.digitalocean.com/community/tutorials/creating-custom-errors-in-go)
- [Panic](https://www.geeksforgeeks.org/panic-in-golang/) and [Recover](https://www.geeksforgeeks.org/recover-in-golang/)

<hr>

## Domain of Contribution 📊

- [x] Golang

<hr>

## Instructions ✔

* Kindly make a `README.md` for this issue, inside the folder as per topic.
* Changes should be made under the **Golang** branch only and push your PR to the same.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.

**Comment by eshan1925** [comment]
May i work on the issue @amino19

**Comment by amino19** [comment]
> May i work on the issue @amino19

@eshan1925: Sure, go ahead! :rocket:

**Comment by eshan1925** [comment]
@amino19 I have generated the PR. Please merge it if there are no issues.
THANKYOU😁
