### ISSUE TITLE
Flutter: Installation & Setup Android Studio - Video

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#158]
A video depicting installation and setup of Android Studio and Flutter on the local machine.

One should cover:
-Download and setup of Flutter
-Download and setup of Android Studio Code
-Change in environment variables, if needed
-Run the default source code of Flutter Project(button click) to check if the setup works flawlessly.

**Comment by Janak2401** [comment]
I am interested.
