### ISSUE TITLE
Flutter: Setup Flutter & VS Code - Video

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#159]
A video depicting installation and setup of Visual Studio Code and Flutter on the local machine.

One should cover:
-Download and setup of Flutter
-Download and setup of Visual Studio Code
-Change in environment variables, if needed
-Run the default source code of Flutter Project(button click) to check if the setup works flawlessly.

**Comment by rohangilbile123** [comment]
I'm interested to solve this issue

**Comment by bakisama** [comment]
Hi,
I would like to work on this

**Comment by Tiwarisonal19** [comment]
Hey, I too would like to contribute on this too!

**Comment by ViAsmit** [comment]
@bakisama have you completed the issue?

**Comment by bakisama** [comment]
Hi @ViAsmit, 
I do not believe in submitting sub-par work and I want to help anyone I can. I needed sometime setting up the virtual machines so I can help Linux and MacOS users too. I will probably be done by tomorrow night. I hope you understand :)

**Comment by ViAsmit** [comment]
@bakisama sure

**Comment by bakisama** [comment]
@pratishthaa Do I need to cover the installation on Android Studio too? It was done in another issue but is needed to emulate the android device to run the default source code

**Comment by ViAsmit** [comment]
@bakisama what you can do is refer to that link which contains installation in your video... Rather than repeating the same thing

**Comment by ViAsmit** [comment]
@bakisama  any updates?

**Comment by bakisama** [comment]
@ViAsmit https://youtu.be/Fi9lnrZu0mE Raising a Pull Request right now

**Comment by ViAsmit** [comment]
@bakisama have you raised the pull request. I cant see it. also mention this issue in your PR.
like this: Fixes #<issueNo>

**Comment by bakisama** [comment]
@ViAsmit oh okay
