### ISSUE TITLE
Topic:Search Engine Code

### ISSUE THREAD

**Issue by freq31** [girlscript/winter-of-contributing#1597]
<hr>

## Description 📜
Write the code for word search engine using tries

<hr>

## Domain of Contribution 📊
Competitve Programming

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [x] C/CPP
- [x] Competitive Programming
- [ ] Cyber Security
- [x] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by freq31** [comment]
Title:Search Engine code,Topic:Tries, Contribution:Documentation ,Language:C++

**Comment by avishj** [comment]
You can only have one domain, remove the rest from the initial issue.
