### ISSUE TITLE
Introduction to SQL and Databases and RDBMS

### ISSUE THREAD

**Issue by Ash515** [girlscript/winter-of-contributing#1634]
<hr>

## Description 📜

Write an Introduction of  SQL and Databases and RDBMS

<hr>

## Domain of Contribution 📊

- [ ] Database

<hr>

**Comment by Divyanshigarg** [comment]
[SQL-Intro.docx](https://github.com/girlscript/winter-of-contributing/files/7205055/SQL-Intro.docx)

**Comment by Divyanshigarg** [comment]
Sir can u check once and review my work. I don't know where and how to add. If I added at wrong place than please guide me.

**Comment by Ash515** [comment]
Sure

**Comment by sakshi168** [comment]
/assign 
want to contribution in documentation form

**Comment by Ash515** [comment]
Sure

**Comment by hariketsheth** [comment]
/assign 

@Ash515 - I would like to contribute documentations for this
Thank you !

**Comment by Ash515** [comment]
Sure

**Comment by sakshi168** [comment]
@Ash515 Please review my PR
