### ISSUE TITLE
Python | Basic Data-Structure (List)

### ISSUE THREAD

**Issue by bhumitbedse** [girlscript/winter-of-contributing#1659]
<hr>

## Description 📜

In this Document, I Explain what is the List in Python 
Issue number : #1659 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [x] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by prathimacode-hub** [comment]
Add the issue number here? @bhumitbedse

**Comment by bhumitbedse** [comment]
Where in title ?

**Comment by bhumitbedse** [comment]
Updated @prathimacode-hub

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal
I would like to work on the documentation part
Pls assign me this issue
i am from Python Batch-6
and DSA batch-2

**Comment by bhumitbedse** [comment]
@adityabisoi kindly add one mentor in this issue because this is issue created by my own so no mentor is tagged

**Comment by BasuDevTyagi10** [comment]
/assign
Name: Basudev Tyagi
Batch: Python Batch-3
Type: Documentation

**Comment by adityabisoi** [comment]
Please check for existing issues first. This topic has already been covered.
