### ISSUE TITLE
HTML_Form

### ISSUE THREAD

**Issue by pilipi-puu-puu** [girlscript/winter-of-contributing#1663]
<hr>

## Description 📜
This documentation will contain a form using HTML.📄
More specifically there will be :
- input
- label
- select
- textarea
- button>
- fieldset
- datalist
- output
- option

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

**Comment by pilipi-puu-puu** [comment]
@Saviour1001 Can you please check this?

**Comment by pilipi-puu-puu** [comment]
@Saviour1001 I'm so sorry, actually I forgot.

**Comment by akratikushwah** [comment]
Hey! I want to work on this issue.

**Comment by akratikushwah** [comment]
> /assign
> 

So, Is this issue assigned to me??
