### ISSUE TITLE
Polymorphism in Cpp (oops)

### ISSUE THREAD

**Issue by aman34503** [girlscript/winter-of-contributing#1670]
<hr>

## Description 📜
In this, we will get a brief idea about the oops concept of polymorphism in cpp.

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] Competitive Programming

<hr>

**Comment by Pranshu321** [comment]
This topic is already assigned to me 3-4 days ago how this issue assigned to you.

**Comment by akratikushwah** [comment]
> This topic is already assigned to me 3-4 days ago how this issue assigned to you.
> 

I have no idea

**Comment by TammanaNiharika** [comment]
I am also assigned to this issue. How can it assign to others?
Can I work on it or not? someone please clarify me!

**Comment by Suvraneel** [comment]
@Pranshu321  's issue will be considered
