### ISSUE TITLE
Dev C++ IDE: Installation, Features And C++ Development  Documentation

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#168]
Tutorial Explains the Installation, Working and Features of Dev C++ IDE which is one of the Most Commonly used IDEs for Developing C++ Applications

**Comment by aman12207** [comment]
can u please five more details about it..

**Comment by aman12207** [comment]
can u please share details more details about this issue..

**Comment by aman12207** [comment]
can u please share more details about this issue..

**Comment by anmol20112000** [comment]
I wan to work on this @LegendSumeet  plzz assign this work to me

**Comment by Rijudas149** [comment]
I want to work on this issue...

**Comment by LegendSumeet** [comment]
> can u please share more details about this issue..

The stepwise installation for dev-C++
Debugging In C++ IDE
Compile/Build & Execute Project
Development Using Dev-C++ IDE

**Comment by Rijudas149** [comment]
@LegendSumeet sir I want to work on this issue... Plz add me...

**Comment by LegendSumeet** [comment]
Hello Supervisor/ Mentor, Can I start working on this issue I just created? 😅

**Comment by Pawanupadhyay10** [comment]
Pls  assign this issue to me.

**Comment by LegendSumeet** [comment]
@Aryamanz29 plz assign me to these issue I had created it ?

**Comment by Aryamanz29** [comment]
@LegendSumeet I'm supervisor of Open source domain

**Comment by VanshikaSable** [comment]
@LegendSumeet  should i start working on this ? because the issue is created bye you and you want to work on it i guess?

**Comment by VanshikaSable** [comment]
@LegendSumeet  sir i have made a pull request on this issue please review it.

**Comment by VanshikaSable** [comment]
Please have a review on my PR.
