### ISSUE TITLE
Flutter: Animations

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#1691]
<hr>

## Description 📜

Add a README File, which explains animations in a flutter,

Reference:
https://flutter.dev/docs
For the structure of folders and files, view previous commits by other contributors

<hr>

## Domain of Contribution 📊

- [x] Android Dev (Flutter, Java, Kotlin)
<hr>

**Comment by RK1905101** [comment]
can i contribute in this for documentation?

**Comment by akshat-crypto** [comment]
hey @ViAsmit, I also want to contribute to this project
can you please share with me at what time new issues will be updated so that i can contribute in them

**Comment by ViAsmit** [comment]
@RK1905101 any updates?

**Comment by RK1905101** [comment]
yes.
I'm currently working on it and so by tomorrow, you'll get PR for this issue.
