### ISSUE TITLE
Cybersecurity: 1.9.9.1 Linux File System

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#170]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with **Diagrams**
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on **first come first serve**
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by medhatiwari** [comment]
I would like to contribute to it in the form of `Documentation`

**Comment by Anant1711** [comment]
> I would like to contribute to it in the form of `Documentation`

Go with it!

**Comment by b33pl0g1c** [comment]
Hi @Anant1711, Can I contribute to this too?

**Comment by Anant1711** [comment]
> Hi @Anant1711, Can I contribute to this too?

Can you submit in `Video` format?
Because `documentation` already taken?

**Comment by medhatiwari** [comment]
@Anant1711 Please review the PR
