### ISSUE TITLE
Cybersecurity 1.9.9.2 Linux File System Directories

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#171]
### Explain what is Linux File System directories. 
_(Documentation is also good, but try to make a video on this topic and explain every command and directory!)_

 
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by NIRBHAYKAUSHIK11** [comment]
I would like to contribute in documentation form.

**Comment by Anant1711** [comment]
> I would like to contribute in documentation form.

Okay!
Go with Documentation.

**Comment by Anant1711** [comment]
@NIRBHAYKAUSHIK11 When you are going to submit your work?
Today is 5th day from assigning date!

**Comment by NIRBHAYKAUSHIK11** [comment]
@Anant1711 due to some highly unavoidable reasons I was unable to submit my work. I have completed the task. Can you please guide me how to submit it?

**Comment by Anant1711** [comment]
> @Anant1711 due to some highly unavoidable reasons I was unable to submit my work. I have completed the task. Can you please guide me how to submit it?

First fork the repo and then select `cyber_security` from branch dropdown and `cyber_security` directory, then go to respective week folder and add your work in a `.md` file! then commit, please add `cybersecurity` before your PR title!

**Comment by Anant1711** [comment]
@NIRBHAYKAUSHIK11 
Update your status, you took 7 days!

**Comment by NIRBHAYKAUSHIK11** [comment]
How to update the status?

**Comment by Anant1711** [comment]
> How to update the status?

When you are going to submit your work?

**Comment by Anant1711** [comment]
> I have submitted the work today itself.

Okay!

**Comment by NIRBHAYKAUSHIK11** [comment]
I was unable to add images in .md file.

**Comment by Anant1711** [comment]
> I was unable to add images in .md file.

How you are trying to add?

**Comment by NIRBHAYKAUSHIK11** [comment]
I am trying to paste image from clipboard.

**Comment by Anant1711** [comment]
> m clipboard.

Check this!
https://stackoverflow.com/questions/14494747/how-to-add-images-to-readme-md-on-github

**Note**:- your images path will be `/images/<image_name>`

**Comment by Anant1711** [comment]
@NIRBHAYKAUSHIK11 Any update?
You took 10 days for this task!

**Comment by NIRBHAYKAUSHIK11** [comment]
I have submitted my work.I submitted it on 22nd september.

**Comment by Anant1711** [comment]
can you share the Link of your PR?

**Comment by NIRBHAYKAUSHIK11** [comment]
https://github.com/NIRBHAYKAUSHIK11/winter-of-contributing/blob/db357d2d7b43e51eeda8551ded994b17da3d3e63/Cyber_Security/Week_1/Explain%20what%20is%20Linux%20File%20System%20directories%20(1).md

**Comment by NIRBHAYKAUSHIK11** [comment]
This is the permalink of the file.

**Comment by Anant1711** [comment]
Man what you did??
Do you know How to make PRs? Where to make a contribution? I didn't get any PR!
You have to select  Cyber_security branch.
<img width="395" alt="Capture" src="https://user-images.githubusercontent.com/63709820/134817951-1d2dac5d-6ab6-4a52-ab6d-dfe6666c4ba2.PNG">

**Comment by Anant1711** [comment]
@NIRBHAYKAUSHIK11 
Please submit in the correct way, please!

**Comment by iamKushGupta** [comment]
Can the documentation part for this issue be assigned to me ??
I perhaps guess that it's not yet done...

**Comment by Anant1711** [comment]
> Can the documentation part for this issue be assigned to me ?? I perhaps guess that it's not yet done...

Assigned!
