### ISSUE TITLE
C/CPP : Implementation of queue using stack

### ISSUE THREAD

**Issue by Pragati1122** [girlscript/winter-of-contributing#1710]
<hr>

## Description 📜

I will explain enqueue and dequeue function using stack. ###Documentation

<hr>

## Domain of Contribution 📊

- [ x ] C/CPP

<hr>

**Comment by akratikushwah** [comment]
Hey! I want to work on this issue.

**Comment by Saviour1001** [comment]
Closing as the PR got merged !
