### ISSUE TITLE
[Frontend_Web_Development_HTML_CSS_JS] Topic: Code Structure

### ISSUE THREAD

**Issue by sushovanb02** [girlscript/winter-of-contributing#1711]
# Code Structure
The code structure of JavaScript
# Directory
```Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/3.Code_Structure```
## Description 📜
- Functionality and Readability
- Whitespace
- Semicolons
- Indentation
- Identifiers

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

# Format
- [x] Documentation

**Comment by Knighthawk-Leo** [comment]
So the PR is approved now I am closing this Issue.
