### ISSUE TITLE
Heap Data Structure Using Priority_queue in C++

### ISSUE THREAD

**Issue by KhushiBhambri** [girlscript/winter-of-contributing#1716]
<hr>

## Description 📜

In this  documentation, we will discuss about the **Heap data structure.**
1.) Theory
2.)  properties of Heap
3.) Heap using STL - priority_queue
4.) Applications of Heap

<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [ ] Competitive Programming
- [x] DSA

<hr>

**Comment by Kashika02** [comment]
Please assign it to me.
Kashika Parmar 
Dsa batch 1

**Comment by Kashika02** [comment]
Thankyou Shruti Verma !!

**Comment by KhushiBhambri** [comment]
> Please assign it to me.
> Kashika Parmar
> Dsa batch

**Comment by KhushiBhambri** [comment]
Hey  @Kashika02 @AkritiAgarwal09 @ShrutiVerma28   -> The issue has been assigned for documentation to the author of the issue, you can contribute to the audio or video files for the same.
Thankyou !

**Comment by nimisha-yadav** [comment]
@KhushiBhambri, DSA domain is following a roadmap for contribution and heap is not there in the week agenda so if you edit this issue, kindly do not check-mark DSA.

**Comment by KhushiBhambri** [comment]
> @KhushiBhambri, DSA domain is following a roadmap for contribution and heap is not there in the week agenda so if you edit this issue, kindly do not check-mark DSA.

Ok sure! will take care next time :)

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged !
