### ISSUE TITLE
DSA (Recursion)

### ISSUE THREAD

**Issue by Rajan2531** [girlscript/winter-of-contributing#1749]
<hr>

## Description 📜

How recursion works.
Different types of recursions.
Few examples to show the flow of recursion.
<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [ ] Competitive Programming
- [x] DSA

- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript

<hr>

**Comment by pranjalambesh** [comment]
I want to work with this

**Comment by saketsagarsingh** [comment]
i want to work on this issue, may i?
Saket Sagar
Batch-2
Documentation
