### ISSUE TITLE
Competitive Programming: Adding Binary Search Related Problems

### ISSUE THREAD

**Issue by ayushijindal** [girlscript/winter-of-contributing#175]
I would like to add question-related to binary search in the form of documentation and work on this issue

**Comment by Chirag-creator17** [comment]
i want to work on this issue.

**Comment by ayushijindal** [comment]
But I would like to work on this issue and waiting for the permission to work on it

**Comment by chetan-2002** [comment]
Can the contributors contribute to the domains they have been selected for?

**Comment by ayushijindal** [comment]
Can we work as a team??

**Comment by RIYANSHGARG** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by ayushijindal** [comment]
I am the contributor only not a mentor/ supervisor. I have raised this issue to work on it but if you want to participate either you create your own issue or work as a team together

**Comment by Chirag-creator17** [comment]
I think you should wait for team to raise issue according to roadmap .

**Comment by Vedika-Agrawal** [comment]
Please assign this issue to me, I would like to work on this issue under GWOC.

**Comment by sanskarn17** [comment]
Hey, can I work on this issue?

**Comment by pratyaksh1610** [comment]
Hey , I would like to contribute to this issue, can you assign this to me .

**Comment by anjalikumawat2002** [comment]
I want to contribute in this issue.
Type - Documantation
Anjali Kumawat
Batch - 3
