### ISSUE TITLE
C/CPP: Sort functions in C++ SLT

### ISSUE THREAD

**Issue by pranjalambesh** [girlscript/winter-of-contributing#1758]
<hr>

## Description 📜
 The documentation will explain about the sorting functions in C++ in detail

<hr>

## Domain of Contribution 📊

- [ ] C/CPP

<hr>

**Comment by pranjalambesh** [comment]
I made this issue can you please assign it to me 
/assign

**Comment by akratikushwah** [comment]
Hey! I want to work on this issue.

**Comment by Saviour1001** [comment]
Closing as the PR got merged
