### ISSUE TITLE
DSA 1.2.4.1 NP-Complete Problem - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1780]
## Description
What do you understand by NP-Completeness? Discuss in detail, what are NP, P, NP-complete and NP-Hard problems?

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Shruti-Subu** [comment]
Can u assign me this?
Name : Shruti Subu
Batch : DSA BATCH 1

**Comment by nimisha-yadav** [comment]
> Can u assign me this?
> Name : Shruti Subu
> Batch : DSA BATCH 1

Assigning this issue to you @Shruti-Subu, all the best!

**Comment by Shruti-Subu** [comment]
Hello @nimisha-yadav  thank you for assigning me this . I have also been assigned to DSA#1789 . So just wanted to clarify am i allowed to work on 2 task together?

**Comment by nimisha-yadav** [comment]
> Hello @nimisha-yadav thank you for assigning me this . I have also been assigned to DSA#1789 . So just wanted to clarify am i allowed to work on 2 task together?

Yeah, ofcourse

**Comment by nimisha-yadav** [comment]
> 
> 
> Hello @nimisha-yadav thank you for assigning me this . I have also been assigned to DSA#1789 . So just wanted to clarify am i allowed to work on 2 task together?

any updates? @Shruti-Subu

**Comment by Shruti-Subu** [comment]
Sorry for the late reply .. will be making a pr by tomorrow.

**Comment by Shruti-Subu** [comment]
@nimisha-yadav
