### ISSUE TITLE
DSA 1.2.4.1 NP-Complete Problem - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1781]
## Description
What do you understand by NP-Completeness? Discuss in detail, what is NP, P, NP-complete and NP-Hard problems?

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by arsheelsheikh** [comment]
Name- Arsheel Sheikh
Batch- 4
Kindly assign me this issue!

**Comment by Harsh-Chaudhary7** [comment]
Harsh Chaudhary
DSA Batch-1
Kindly assign the issue to me.

**Comment by Ayushi2811** [comment]
thanku for assigning it to me .Will do my best!

**Comment by GenMech** [comment]
Gitesh Pareek
Batch-1

**Comment by nimisha-yadav** [comment]
> /assign

@Ayushi2811 once you submit your previous tasks, I'll assign you more. Also, always follow the guidelines mentioned in the note.

**Comment by dhruti29** [comment]
I would like to work on this issue..
Batch - 2
Dhruti Gandhi
