### ISSUE TITLE
DSA 1.2.5.1 Approximation Algorithms - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1783]
## Description
What are approximation algorithms? State their types and properties in detail.

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by arsheelsheikh** [comment]
I have completed previous issues sorry for the inconvenience

**Comment by arsheelsheikh** [comment]
Name- Arsheel Sheikh
DSA Batch- 4

**Comment by Aryan-Mohanty** [comment]
can i work on this issue ?
Aryan Mohanty
DSA batch -6

**Comment by nimisha-yadav** [comment]
> Name- Arsheel Sheikh
> DSA Batch- 4

Assigning this issue to you @arsheelsheikh, all the best

**Comment by dhruti29** [comment]
I would like work on this issue.
Batch - 2
Dhruti Gandhi

**Comment by nimisha-yadav** [comment]
> 
> 
> > Name- Arsheel Sheikh
> > DSA Batch- 4
> 
> Assigning this issue to you @arsheelsheikh, all the best

@arsheelsheikh, any updates?

**Comment by arsheelsheikh** [comment]
> > > Name- Arsheel Sheikh
> > > DSA Batch- 4
> > 
> > 
> > Assigning this issue to you @arsheelsheikh, all the best
> 
> @arsheelsheikh, any updates?

@nimisha-yadav working on it will finish it by tomorrow ASAP

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav working on it will finish it by tomorrow ASAP

PR updates? @arsheelsheikh
