### ISSUE TITLE
DSA 1.2.5.1 Approximation Algorithms - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1784]
## Description
What are approximation algorithms? State their types and properties in detail.

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by NIKITAjadhav4124** [comment]
@nimisha-yadav Name: Nikita Jadhav
Batch No: DSA Batch-6

**Comment by nimisha-yadav** [comment]
@jaigora24 It's been many days, please try to submit this PR within 2 days now.
