### ISSUE TITLE
DSA 1.2.5.1 Approximation Algorithms - Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1785]
## Description
What are approximation algorithms? State their types and properties in detail.

## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Apoorv-17** [comment]
I would like to work on this issue.
Name: Apoorv Yadav
Batch: 07
Type: Video

**Comment by nimisha-yadav** [comment]
Great @Apoorv-17, it's good to see someone working on an old topic, there're few more [such issues](https://github.com/girlscript/winter-of-contributing/issues?page=1&q=is%3Aopen+label%3AUp-For-Grabs+DSA), feel free to take them up too.

**Comment by Apoorv-17** [comment]
Sure, will gladly take the old issues.
