### ISSUE TITLE
DSA 1.2.5.2 Approximation Algorithms Example Problems - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1787]
## Description
Briefly explain the examples of approximation algorithms.
Vertex cover problem, Travelling salesman problem, Set covering problem.

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by arsheelsheikh** [comment]
I have completed previous issues sorry for inconvenience

**Comment by Aryan-Mohanty** [comment]
can i work on this issue ?

**Comment by nimisha-yadav** [comment]
> can i work on this issue ?
> Aryan Mohanty
> Batch -6

Assigning this issue to you @Aryan-Mohanty, all the best!

**Comment by dhruti29** [comment]
can I work on this issue?
Dhruti Gandhi
Batch -2

**Comment by kalyanirb12** [comment]
can I work on this 
kalyani rajebhosale
mode:-documentation
batch:-1

**Comment by nimisha-yadav** [comment]
> 
> 
> can I work on this
> kalyani rajebhosale
> mode:-documentation
> batch:-1

Assigning this issue to you @kalyanirb12, all the best.

**Comment by kalyanirb12** [comment]
@nimisha-yadav thanku

**Comment by nikki-priyaHIT** [comment]
mai i work on this issue?
Nikki Priya
Batch-2

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by nimisha-yadav** [comment]
> 
> 
> can I work on this kalyani rajebhosale mode:-documentation batch:-1

any updates? @kalyanirb12

**Comment by kalyanirb12** [comment]
@nimisha-yadav  currently working on it I will update you within 2 days.

**Comment by kalyanirb12** [comment]
@nimisha-yadav can you Please guide me on what to do after creating documentation on this topic?

**Comment by nimisha-yadav** [comment]
> 
> 
> can I work on this issue? Dhruti Gandhi Batch -2

Assigning this issue to you @dhruti29
