### ISSUE TITLE
DSA 1.2.5.2 Approximation Algorithms Example Problems - Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1788]
## Description
Briefly explain the examples of approximation algorithms.
Vertex cover problem, Travelling salesman problem, Set covering problem.

## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Harsh-Chaudhary7** [comment]
I want to work on this Kindly assign to me.
Harsh Chaudhary
DSA Batch-1

**Comment by Ayushi2811** [comment]
I dont have 3 opened issues.I only have one issue assigned previously so plz dont change and re assign it to me.U can chk my profile it has only one opened issue

**Comment by nimisha-yadav** [comment]
> I want to work on this Kindly assign to me.
> Harsh Chaudhary
> DSA Batch-1

Assigning this issue to you @Harsh-Chaudhary7, all the best!

**Comment by Harsh-Chaudhary7** [comment]
Sorry won't be able to do this please assign it to somebody else @nimisha-yadav

**Comment by ShraddhaMeshram27** [comment]
Can I get this issue ?
but i'm not DSA Batch

**Comment by nimisha-yadav** [comment]
> Can I get this issue ? but i'm not DSA Batch

Go ahead!

**Comment by nimisha-yadav** [comment]
> Can I get this issue ? but i'm not DSA Batch

Go ahead @ShraddhaMeshram27

**Comment by ShraddhaMeshram27** [comment]
Sorry Ma'am, I am working on 2 issues on my domain now hence cannot take up this issue.
Thank you for your concern 🙏.
