### ISSUE TITLE
DSA 1.2.5.2 Approximation Algorithms Example Problems - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#1789]
## Description
Briefly explain the examples of approximation algorithms.
Vertex cover problem, Travelling salesman problem, Set covering problem.

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Shruti-Subu** [comment]
Can u assign me this?
Name :  Shruti Subu
Batch : DSA BATCH 1

**Comment by Shruti-Subu** [comment]
@soumyaagr427 we can't use the assign command for this issue.
Its mentioned in the above description.

**Comment by nimisha-yadav** [comment]
> Can u assign me this?
> Name : Shruti Subu
> Batch : DSA BATCH 1

Assigning this issue to you @Shruti-Subu, all the best!

**Comment by Shruti-Subu** [comment]
@nimisha-yadav  Thank you for assigning me this.
