### ISSUE TITLE
 C++17 - The Complete Guide Documentation

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#179]
C++17 - The Complete Guide 
Giving guidance on how to use the new language and library features of C++17

**Comment by sumit-6** [comment]
Can I work on this issue?
I would like to contribute via writing content on this issue

**Comment by Rijudas149** [comment]
Sir can I work on this issue??

**Comment by LegendSumeet** [comment]
Hello Supervisor/ Mentor, Can I start working on this issue I just created? 😅

**Comment by Rijudas149** [comment]
Can't understand what you're saying sir
