### ISSUE TITLE
html_list

### ISSUE THREAD

**Issue by prernakumari031** [girlscript/winter-of-contributing#1791]
### Description

Describe the different types of lists and their uses

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sifa123** [comment]
Hello everyone, @prernakumari031 @arsheelsheikh @kumarschitransh, as @anmolx001  already mentioned this issue in a PR. You guys can work on that PR as a team. Look at the PR and see what other things you can add.

**Comment by arsheelsheikh** [comment]
I was doing PR now but seem like someone has already made it for HTML List even tho he has not assigned the task 
@sifa123 can you let me know what needs to be done here !!

**Comment by sifa123** [comment]
Guys this topic is already merged. I should inform all of you that earlier, my apologies. That is why I will close this issue. If anyone wants to work on video or audio, they can create a new issue.

**Comment by sifa123** [comment]
> I was doing PR now but seem like someone has already made it for HTML List even tho he has not assigned the task
> @sifa123 can you let me know what needs to be done here !!

Hey @arsheelsheikh , you can go through the merged file about html list and check if any topic is missing or if you can add more content, then create an issue about what topics you want to add.
