### ISSUE TITLE
Resources For Competitive Programming Documentation

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#180]
Giving guidance on how to use the new Best Resources For Competitive Programming

**Comment by chetan-2002** [comment]
Competitive programming is not my selected domain . Can I still contribute to this domain?

**Comment by Chirag-creator17** [comment]
I would like to work on this issue .
chirag , cp batch 2

**Comment by LegendSumeet** [comment]
Hello Supervisor/ Mentor, Can I start working on this issue I just created? 😅

**Comment by sakkshm26** [comment]
Hey, can I work on this issue?
