### ISSUE TITLE
[Create New Issue]: Macros in C

### ISSUE THREAD

**Issue by KartikChinda** [girlscript/winter-of-contributing#1812]
### Description

I would like to add documentation for the various Macros in C. 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by KartikChinda** [comment]
@Suvraneel sir please assign me this issue. I would love to work on this!

**Comment by Saviour1001** [comment]
Closing this issue as it got fixed in #2575
