### ISSUE TITLE
Data Science with Python : Hierarchical Clustering

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1830]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Hierarchical Clustering. Tutorial to Hierarchical Clustering and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Shivang Dubey / Dhruv Bajaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ashish-reddy-20-08** [comment]
hello, I am M. Ashish Reddy. I would like to do documentation on this issue.
Batch number: 5
serial number:174.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do a video on this issue.
My approach: A clear explanation of the issue and code explanation.

**Comment by prathimacode-hub** [comment]
Issue is assigned to @ashish-reddy-20-08 for documentation and @deepthi1107 for video contribution

**Comment by BhoomiVarshney** [comment]
Hello 
I am Bhoomi Varshney
Serial No.: 641
Batch:17
I would like to work on documentation.
My approach would: Why use hierarchical clustering and how to implement it.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Thank you for the opportunity mam.

**Comment by ashish-reddy-20-08** [comment]
Name: M. Ashish Reddy
Type: Documentation
Batch number: 5
Serial number: 174
PR link: https://github.com/girlscript/winter-of-contributing/pull/2147

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you please assign me audio for this mam.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for audio contribution @ashish-reddy-20-08
