### ISSUE TITLE
Bit Manipulation

### ISSUE THREAD

**Issue by uditkatyal** [girlscript/winter-of-contributing#1835]
### Description

Description
what is bit manipulation 
types of bit operators 
uses and functioning.

### Domain

Competitive Programming

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
@uditkatyal  
Observe the changes to your comment & do the same from next time...
Anyway, Go ahead with this :octocat:

**Comment by uditkatyal** [comment]
cool I have added  C_CPP domain can you review my PR!
