### ISSUE TITLE
MERN_MongoDB: 1.1 What is MongoDB? 

### ISSUE THREAD

**Issue by aryan-mehta05** [girlscript/winter-of-contributing#1840]
### Description
Introduction to MongoDB in the MERN stack.

### Domain
MERN

### Project Directory
`Branch MERN>MERN/Topic/Backend/MongoDB/ `

### Type of Contribution
Documentation

### Code of Conduct
- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by pankaj-Makhijani** [comment]
Hello, is this issue open for video part?

**Comment by saloni-15** [comment]
> Hello, is this issue open for video part?

hey, you can create a new issue, for the video part with the title `MERN_MongoDB: 1.1 What is MongoDB?_Video`
and self-assign it.

**Comment by saloni-15** [comment]
> Hello, is this issue open for video part?

here it is if you want to work on
https://github.com/girlscript/winter-of-contributing/issues/2252

**Comment by pankaj-Makhijani** [comment]
@saloni-15 Thank you for creating this issue. Will start working on it.

**Comment by aryan-mehta05** [comment]
The updates to 1.1_What_is_MongoDB? are made and PR has been merged without any problems.
