### ISSUE TITLE
Flutter: documentation on Appbar Widget

### ISSUE THREAD

**Issue by jaissumi1402** [girlscript/winter-of-contributing#1845]
### Description

I will be adding a documentation on appbar widget with example and images

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ViAsmit** [comment]
@jaissumi1402 you can continue working on this topic. but make sure your content is not plagiarised and give proper references.
