### ISSUE TITLE
Android-Java: Orientation of Android activity.

### ISSUE THREAD

**Issue by pragatikesarwani38** [girlscript/winter-of-contributing#185]
In this issue you have to describe briefly about the various types of orientation an activity can have.

**Comment by LegendSumeet** [comment]
can i work on it ? i can make a good documentation on it ?

**Comment by Rohit-2602** [comment]
@pragatikesarwani38  yes you can work on it

**Comment by LegendSumeet** [comment]
assign me to?

**Comment by pragatikesarwani38** [comment]
Thank you @Rohit-2602

**Comment by pragatikesarwani38** [comment]
I have created a pull request, please check that out sir. @Rohit-2602

**Comment by Rohit-2602** [comment]
In the future, add a link to the pull request to message also

**Comment by pragatikesarwani38** [comment]
Okay
