### ISSUE TITLE
Data Science with Python : Tokenization & Lemmatization

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1856]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Tokenization & Lemmatization from scratch. Tutorial to Tokenization & Lemmatization and how it's applied using code snippets

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : Nithin / Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Robinrai2612** [comment]
@prathimacode-hub I would like to work on the issue and I will explain the theoretical concepts and coding regarding it.

Type: Documentation
Sr.No: 146

**Comment by prathimacode-hub** [comment]
Issue assigned to @Robinrai2612 for documentation

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy. I would like to do VIDEO on this issue.
Batch number: 5
serial number:174.

**Comment by prathimacode-hub** [comment]
Issue is assigned to @ashish-reddy-20-08 for video contribution

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam can you please review my PR.
PR link: https://github.com/girlscript/winter-of-contributing/pull/2521
Batch number: 5
serial number:174
Name: M. Ashish Reddy

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-5. I would like to do video on this issue.
My approach: A detailed explanation of the theory.

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
