### ISSUE TITLE
[Create New Issue]: React props vs state

### ISSUE THREAD

**Issue by SakshiMishra1** [girlscript/winter-of-contributing#1867]
### Description

Description

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by SakshiMishra1** [comment]
@anandhu720 sorry, I wasn't aware of that sir. No complaints from my side after this

**Comment by anandhu720** [comment]
please ask your doubts in discord and be active there
