### ISSUE TITLE
Opensource : 3.1 Github best practices  

### ISSUE THREAD

**Issue by NamanManjkhola** [girlscript/winter-of-contributing#187]
### Description 

Documentation on

- Best practices to follow on GitHub. 
- Things to remember/avoid while contributing.
- Enhancing your GitHub profile.

**Comment by NamanManjkhola** [comment]
@Aryamanz29  Can I work on this issue I created?

**Comment by LegendSumeet** [comment]
can you assign this work to me?

**Comment by Aryamanz29** [comment]
Sure 💯, Make sure to follow `contributing_guidelines` , Happy Documenting 🙌

**Comment by Aryamanz29** [comment]
> can you assign this work to me? 

@LegendSumeet  Can you create new issue on topic : customising GitHub profile  👈

**Comment by NamanManjkhola** [comment]
ofcourse ,Thanks!

**Comment by riyapandey730** [comment]
can i work on this?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Can I work on this issue I created?

Any updates????

**Comment by NamanManjkhola** [comment]
Will raise a pr today itself

**Comment by NamanManjkhola** [comment]
@Aryamanz29  Please tell the branch and directory I need to raise PR on.
