### ISSUE TITLE
Java Streams

### ISSUE THREAD

**Issue by Satyam175** [girlscript/winter-of-contributing#1871]
### Description

<h1>Java Basic Concepts</h1>

<ul>

<li>Streams</li>

</ul>

<p>
Documents should have proper code explaination with comment lines. For Audio and Video Contributions Audio should be clear .
</p>

### Domain

Backend Dev (Java)

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by MauryaD** [comment]
/assign

Please assign this issue to me as I want add more into this topic.

**Comment by pooja002** [comment]
Hi @Satyam175 , can you please review my pull request and provide suggestions if  any .

**Comment by Satyam175** [comment]
> Hi @Satyam175 , can you please review my pull request and provide suggestions if any .

Can you please share your link

**Comment by pooja002** [comment]
> > Hi @Satyam175 , can you please review my pull request and provide suggestions if any .
> 
> Can you please share your link

https://github.com/pooja002/winter-of-contributing/blob/Backend_Development_With_Java/Backend_Development_With_Java/Basic_Concepts/new%20file.md

Please find the attached link.

**Comment by pooja002** [comment]
Hi @Satyam175 , kindly review my pull request.
[https://github.com/girlscript/winter-of-contributing/pull/3776](url)
