### ISSUE TITLE
Exception Handling in Java

### ISSUE THREAD

**Issue by Satyam175** [girlscript/winter-of-contributing#1874]
### Description

<h1>Java Basic Concepts</h1>

<ul>

<li>Exception Handling</li>
</ul>

<p>
Documents should have proper code explaination with comment lines. For Audio and Video Contributions Audio should be clear .
</p>

### Domain

Backend Dev (Java)

### Type of Contribution

Audio, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sanghisha145** [comment]
@Satyam175 I already started working on Documentation. Please help as you have assigned same to @varunborar

**Comment by varunborar** [comment]
> @Satyam175 I already started working on Documentation. Please help as you have assigned same to @varunborar

You can continue with the work i have un-assigned myself.

**Comment by Satyam175** [comment]
> /assign

Hii are you working on the issue?
