### ISSUE TITLE
Frontend With Framework : Class Components in React

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#1876]
### Description

Need to add Details of Class Components in React,How It works,Why we use Class Components,dis advantages of class components and any thing relevant regarding class components in react

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by GyaniRoman23** [comment]
Hey @anandhu720 I would like to work with this issue.
