### ISSUE TITLE
Frontend With Framework : Functional Components in React

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#1878]
### Description

This need to be include all about Functional Components in React,Why we use Functional Components,Advantages and DisAdvantages and anything relevant to this topic

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by GyaniRoman23** [comment]
@anandhu720  I would like to work on this issue. I have a good understanding of class and functional components, so please do consider me.

**Comment by anandhu720** [comment]
@GyaniRoman23 bro only work on a single issue at a time.Because we have many contributers.Most of them are not getting work.

**Comment by GyaniRoman23** [comment]
> @GyaniRoman23 bro only work on a single issue at a time.Because we have many contributers.Most of them are not getting work.

Sure:)

**Comment by Anshii12** [comment]
Sir, I would like to work on this issue.
Kindly assign it to me.

**Comment by anandhu720** [comment]
@Anshii12 sure

**Comment by cenacrharsh** [comment]
I don't have any issues assigned to me, why was I unassigned @anandhu720?

**Comment by anandhu720** [comment]
@cenacrharsh Only one can work on one issue bro.
