### ISSUE TITLE
Frontend With Framework : Comparing Functional and Class Components

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#1880]
### Description

Need to add a Comparision of Functional and Class Components.Different methods in them to do a specific task.Synatx,which one is better.

Table form will be better.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by CSAURABH** [comment]
Can I work on this issue

**Comment by anandhu720** [comment]
@CSAURABH bro you are already working on one issue.Please work on one issue at a time.Because it will reduce the chance of other to get work

**Comment by nooobcoder** [comment]
@anandhu720 PR raised at [https://github.com/girlscript/winter-of-contributing/pull/2107](https://github.com/girlscript/winter-of-contributing/pull/2107) for Issue **#1880**
Please review, and merge if there are no conflicts.

Thank You 🙏

**Comment by nooobcoder** [comment]
@anandhu720 please close this issue as PR has been merged #2107
