### ISSUE TITLE
JS: JSON  Tutorial

### ISSUE THREAD

**Issue by rwiteshbera** [girlscript/winter-of-contributing#1882]
### I will discuss what is JSON and how to use it?
```
Topics/8.JSON
```

### Domain

JavaScript

### Type of Contribution

- [x] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by paramsiddharth** [comment]
@rwiteshbera I hope you'll be either contributing in a different format or extending the existing contribution! Please note that I am updating the directory path.

**Comment by Surbhi-sinha** [comment]
can I also work on this adding more functionality ?? @paramsiddharth.

**Comment by yellowberard** [comment]
@paramsiddharth I have some issue pulling the repository and I have also mentioned same in discord.so please assign this issue to me.
