### ISSUE TITLE
Opensource : 3.2 customising GitHub profile

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#189]
Hello Supervisor/ Mentor, Can I start working on this issue I just created? 😅

**Comment by Aryamanz29** [comment]
@LegendSumeet Sure , Happy documenting

**Comment by lohith1392** [comment]
can I also do this or only one can only do it??

**Comment by Aryamanz29** [comment]
> can I also do this or only one can only do it??

Create a new issue which you want to work under `open_source_domain` @lohith1392

**Comment by lohith1392** [comment]
Ok thank you

**Comment by lohith1392** [comment]
@Aryamanz29 Is there any list of issues to select or our own???

**Comment by Aryamanz29** [comment]
Its must be inside `opensource domain`
