### ISSUE TITLE
DSA 1.1.3.8 Arrays: Range Queries (for searching an element)

### ISSUE THREAD

**Issue by jaissumi1402** [girlscript/winter-of-contributing#1908]
### Description

Given an array of size N and Q queries in the form of L R X. For each query give the output Yes or No if X present in between the indices L and R. 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by jaissumi1402** [comment]
@nimisha-yadav ma'am can i work on this issue

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav ma'am can I work on this issue?

Yes, now it's okay, go ahead

**Comment by Divya-2001** [comment]
Is the issue still on?

**Comment by nimisha-yadav** [comment]
> 
> 
> Is the issue still on?

For audio and video format, yes. @Divya-2001
