### ISSUE TITLE
Competitive Programming : Creating a Binary search tree

### ISSUE THREAD

**Issue by maddler-hub** [girlscript/winter-of-contributing#1913]
### Description

DescriptionLabels: GWOC21, Competitive Programming, Documentation

Format: Documentation

Language:C++

Topic:CompetitiveProgramming/BinarySearchTrees

Description: Program for creating a binary search tree using a recursive function.

### Domain

Competitive Programming

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Nishita5421** [comment]
Hey ! Can I work on the documentation part of this issue?
