### ISSUE TITLE
OpenSouce  : 3.4 List of open source events .

### ISSUE THREAD

**Issue by siddhi-244** [girlscript/winter-of-contributing#192]
**List of open source events**
**Link to their websites**
**How to participate in it**
Please assign this to me !

**Comment by Aryamanz29** [comment]
@siddhi-244  You need to explain every open-source programs in detail with images, flowcharts and also mention their repo links

**Comment by Aryamanz29** [comment]
> Please assign this to me !

Note: Issue will be more descriptive, follow other issues of mine while creating

**Comment by siddhi-244** [comment]
> @siddhi-244 You need to explain every open-source programs in detail with images, flowcharts and also mention their repo links

Ok sure

**Comment by Aryamanz29** [comment]
> > @siddhi-244 You need to explain every open-source programs in detail with images, flowcharts and also mention their repo links
> 
> Ok sure

Now it's good

**Comment by RIYANSHGARG** [comment]
please assign this issue to I want to work on it

**Comment by siddhi-244** [comment]
Please check my pr!
