### ISSUE TITLE
Shell Sort Algorithm

### ISSUE THREAD

**Issue by sanskarn17** [girlscript/winter-of-contributing#1923]
### Description

Explanation and code.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by abhishekd358** [comment]
Is the issue still open ? If yes .
Please /assign to me
