### ISSUE TITLE
CPP: File Handling 

### ISSUE THREAD

**Issue by sheril04** [girlscript/winter-of-contributing#1929]
### Description

File Handling and I/O Management using CPP

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this issue as the PR got merged
