### ISSUE TITLE
Front End with Framework:  Mapping data to components in React

### ISSUE THREAD

**Issue by NikhilSharma03** [girlscript/winter-of-contributing#1937]
### Description

- How to map data into Components using ReactJS?
- Add examples (Must)

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by anandhu720** [comment]
@AdityaPandey03 You can work only in single issue at a time.We have repeated this several time.Then also you guys are auto assigning many tasks from bot.Please obey the rules.We have a lot of contributers by doing like this you guys are taking their opportunities.Please dont this again.

**Comment by Ajinkyap331** [comment]
@anandhu720  I have just completed my Python Contribution. Now I would to glad to work on this issue

**Comment by Navneetkumarjpr** [comment]
i want this task

**Comment by heet-kumar** [comment]
@AdityaPandey03 are you working on these issue so stop your work because we are changing this issue. Will you able to work on the different issue if we assign you . Because this same issue is already created by other before this issue created.

**Comment by Ajinkyap331** [comment]
@heet-kumar I am working on this issue.

**Comment by heet-kumar** [comment]
but it is already created by other .

**Comment by heet-kumar** [comment]
before this issue created

**Comment by Ajinkyap331** [comment]
But that issue is #1949 and this is 1937. So this the one which is created first

**Comment by heet-kumar** [comment]
@Ajinkyap331 ok then continue..........

**Comment by Ajinkyap331** [comment]
Thank you so much @heet-kumar

**Comment by heet-kumar** [comment]
> Thank you so much @heet-kumar

No problem @Ajinkyap331
