### ISSUE TITLE
Data Science with Python : Movie Recommendation Systems

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#1939]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about Movie Recommendation Systems. Tutorial to Movie Recommendation Systems and how it's applied using code snippets.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Dhruv Bajaj / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Tanya205** [comment]
Hi, I would like to contribute to this issue.
Tanya Malhotra
Data Science with Python, Batch - 12
Sr No. - 429
https://github.com/Tanya205
Documentation

**Comment by CodeSavitar** [comment]
I would like to contribute to this issue.
Adhith Sankar (DS with Python Batch 18)
Documentation

**Comment by divya-chhoriya** [comment]
/assign
I'll provide all the necessary details about this topic and a sample code to demonstrate the working
Divya Chhoriya
Type : Documentation
Serial no: 444 (DS- Python batch 12)

**Comment by Prateek-8168** [comment]
I want to work with this issue.

**Comment by prathimacode-hub** [comment]
@CodeSavitar @Tanya205 @Prateek-8168, you can choose either audio or video.

**Comment by ashish-reddy-20-08** [comment]
hello @prathimacode-hub , Can you please assign me this issue for video contribution mam. 
approach: i will explain the code and about the recommendation system.
M. Ashish Reddy
Batch - 5

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you please assign me audio for this mam.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for audio contribution
