### ISSUE TITLE
Frontend with Framework: using the React Developer Tools

### ISSUE THREAD

**Issue by nirvikagarwal** [girlscript/winter-of-contributing#1943]
### Description

Contributors need to include the following.
- How does React Dev Tool help in the development.
- Examples showing its usage.

Installation is not required as it was already covered in week 1

__Note:__
- Plagiarism is strictly prohibited.
- Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
- Files need to be added into the **Week2** folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AdityaPandey03** [comment]
I want to work on the documentation part of this issue

**Comment by ARUNBALACHOCKALINGAM** [comment]
can I work on this issue

**Comment by anandhu720** [comment]
@AdityaPandey03 any updates

**Comment by AdityaPandey03** [comment]
Hey @anandhu720! With the hactoberfest around I actually didn't realize that this issue has been assigned to me. I am so sorry for this..can you please provide me one more day..I will surely make a PR till tomorrow. I am so sorry for this !!

**Comment by anandhu720** [comment]
@AdityaPandey03 fine.

**Comment by AdityaPandey03** [comment]
hey @anandhu720... made a pr just now..please do have a look and I'm sorry for the delay!

**Comment by anandhu720** [comment]
fine bro

**Comment by AdityaPandey03** [comment]
@anandhu720 can you please merge the pr?

**Comment by AdityaPandey03** [comment]
You have mentioned that this pr shows a lot of changes which is not usual . I didn't get it, what do I need to do exactly ? @anandhu720

**Comment by anandhu720** [comment]
@AdityaPandey03 you created or not bro

**Comment by AdityaPandey03** [comment]
hey i have some doubt...while comparing my frontend with framework branch and master branch of girlscript repo there are 75 files changed...
And when i am creating a pull request to frontend with framework branch there are more than 700 changes

**Comment by AdityaPandey03** [comment]
sorry for the delay once again...was the first contribution so turned out to be a bit messy
