### ISSUE TITLE
[C/CPP]: Input Output operators in C++using cin and cout

### ISSUE THREAD

**Issue by Sunainacode** [girlscript/winter-of-contributing#1947]
### Description

This will focus on the operators used to take input and provide output in C++ programs and the header files used in the process.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Pooj123-A** [comment]
**/assign**
