### ISSUE TITLE
Frontend with Framework: Mapping data to components in React

### ISSUE THREAD

**Issue by nirvikagarwal** [girlscript/winter-of-contributing#1949]
### Description

**Description:**

This needs to include how to map data to React Components.
How we should separate the Data with the logic of our Component to avoid code repetition.
Any other point relevant to this topic is welcomed.

**Note:**
Plagiarism is strictly prohibited.
- Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
- Files need to be added into the Week2 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by GyaniRoman23** [comment]
@nirvikagarwal I would like to work with this issue.

**Comment by anandhu720** [comment]
@SMD-1 do you start working on this issue

**Comment by GyaniRoman23** [comment]
Hey @anandhu720 @nirvikagarwal if this issue is reassigned, do consider me for it.

**Comment by SMD-1** [comment]
> @SMD-1 do you start working on this issue

I got fever, so i am not feeling well that's why i have not started working on this issue. If you want you can reassign this issue to someone else i don't want to waste your time i'll work on some other issue next time.

**Comment by anandhu720** [comment]
@SMD-1 okey bro,actually this issue is already created by mistakily mentor created this issue.So we are closing this issue.
