### ISSUE TITLE
Cybersecurity: 3.6 Resident virus

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#1956]
### Description

Discuss Resident viruses.

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by 0shivamh** [comment]
I would like to work on this one issue

**Comment by Anant1711** [comment]
> I would like to work on this one issue

Okay!
I'm assigning it to you!

**Comment by PrachiDoshi2170** [comment]
Hello @Anant1711 if the documentation of this issue has not been assigned to anyone. I would like to work on it

**Comment by 0shivamh** [comment]
> Hello @Anant1711 if the documentation of this issue has not been assigned to anyone. I would like to work on it

hey, I'm doing documentation
