### ISSUE TITLE
Cybersecurity: 3.9 File injecting virus

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#1959]
### Description

Discuss more about File injecting virus.

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
@Harsh-Chaudhary7 You didn't submit your previous work!
Please submit that first!

**Comment by medhatiwari** [comment]
@Anant1711 can you assign me this?

**Comment by Anant1711** [comment]
> @Anant1711 can you assign me this?
> `Documentation`

Assigned!
