### ISSUE TITLE
Cybersecurity: 3.9.1 Boot sector virus

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#1960]
### Description

Discuss more about the Boot sector virus.

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
@prithwishpramanik When do you submit your work?
You took 7 days!

**Comment by prithwishpramanik** [comment]
> @prithwishpramanik When do you submit your work? You took 7 days!

Today only...I was busy with some college stuff.

**Comment by Anant1711** [comment]
> > @prithwishpramanik When do you submit your work? You took 7 days!
> 
> Today only...I was busy with some college stuff.

Please submit it by Today itself!

**Comment by SwarnaliBhunia** [comment]
@Anant1711 sir pls assign me this vedio
