### ISSUE TITLE
ML 1.15 : Types of Distribution (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#1966]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Types of Distribution**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by abhisheks008** [comment]
@HastiSutaria Make sure you have to contribute in this issue via **Video** contribution.

**Comment by HastiSutaria** [comment]
@abhisheks008 Okay

**Comment by abhisheks008** [comment]
Please create the PR ASAP @HastiSutaria

**Comment by abhisheks008** [comment]
What's the update @HastiSutaria

**Comment by HastiSutaria** [comment]
@abhisheks008 Will create PR by tomorrow.

**Comment by abhisheks008** [comment]
Yeah that's what is the motto of the issue, add major things which will be beneficial for the users @HastiSutaria

**Comment by HastiSutaria** [comment]
Okay! Is audio and face compulsory in video ?

**Comment by Isha307** [comment]
@HastiSutaria face is not compulsory.
Any Update?

**Comment by abhisheks008** [comment]
@HastiSutaria What happened?

**Comment by HastiSutaria** [comment]
@abhisheks008 I had to give my PC for repairing! So I won't be able to shoot the video.

**Comment by sanjana-iyengar** [comment]
/assign
I would like to contribute.

Full name: Sanjana Alaham
Batch Number: 6
GitHub Profile Link: https://github.com/sanjana-iyengar
Contribution: Video

**Comment by Isha307** [comment]
@sanjana-iyengar Update?

**Comment by abhisheks008** [comment]
@sanjana-iyengar you have assigned the by your own choice still after 7 days you have not come up with the PR. Please provide us the update.
