### ISSUE TITLE
FrontEnd Web : 0. Basics of Internet

### ISSUE THREAD

**Issue by Harshil-Jani** [girlscript/winter-of-contributing#197]
Documentation on Basics of Internet ! 
- How does the Internet Work?
- What is HTTP?
- How does Browser Rendering Works?
- DNS & Working of DNS?
- Domain Name Basics.
- Hosting & Name Servers.

From Front End Web Developement Branch.

**Comment by Harshil-Jani** [comment]
Can I take up this Issue?

**Comment by salonisingh77** [comment]
Please assign

**Comment by Asmit2952** [comment]
I want to work on this!

**Comment by ug2510** [comment]
Want to work on this!!

**Comment by salonisingh77** [comment]
Yes

**Comment by Rijudas149** [comment]
Sir I want to work on this issue

**Comment by LavleenAgrawal** [comment]
I want to make audio content on this, May I ?
Lavleen Agrawal (Batch 18 - Frontend)

**Comment by Harshil-Jani** [comment]
Due to inactivity from supervisors. I am closing this issue.
