### ISSUE TITLE
[Create New Issue]: HTML Classes and Ids

### ISSUE THREAD

**Issue by RakshitGupta621** [girlscript/winter-of-contributing#1983]
### Description

Contribution in documentation of **HTML classes and Ids** 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by jaigora24** [comment]
I opened my PR. Please review it https://github.com/girlscript/winter-of-contributing/pull/2802
