### ISSUE TITLE
[Create New Issue]: Searching and Sorting Algorithms in Arrays

### ISSUE THREAD

**Issue by RakshitGupta621** [girlscript/winter-of-contributing#1985]
### Description

I want to contribute in the documentation of **Searching and Sorting algorithms of Arrays**

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Pooj123-A** [comment]
**/assign**
