### ISSUE TITLE
OpenSource :  1. History of free and open-source software (1980 & 1990’s)

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#20]
### Description :
- **Explain the History of free and open-source software (1980 & 1990’s)**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by Adi7171** [comment]
I would like to be assigned this issue

**Comment by Aryamanz29** [comment]
> I would like to be assigned this issue

Sure @Adi7171 
Happy Documenting 🙌😉

**Comment by Adi7171** [comment]
so how do I contribute do I do it through github readme for documentation

**Comment by Aryamanz29** [comment]
> so how do I contribute do I do it through github readme for documentation

Hey, You can contribute through `documentation, audio & video`. See: https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md
For documentation, It should be `markdown` format
Create new directory `History of free and open-source software`
Inside made your contribution

**Comment by Adi7171** [comment]
so I am supposed to write it on google collab and not on readme?

**Comment by Aryamanz29** [comment]
> so I am supposed to write it on google collab and not on readme?

@Adi7171  You can use `markdown` as well

**Comment by Aryamanz29** [comment]
PR merge #160, Closing this now
