### ISSUE TITLE
[Create New Issue]: Array in c

### ISSUE THREAD

**Issue by jyotibajaj729** [girlscript/winter-of-contributing#2001]
### Description

An Array is a collection of data items stored at contiguous memory locations and elements can be randomly accessed using indices of array.
**Why do we need Array?**
Array are needed when we need to store large number of elements for that we can't use normal variables as it would take lot of time and memory and it becomes difficult to manage with normal variables.
**Array Declaration-**
There are different methods to declare an array.Let us check those methods for an integer array.
1).int a[n] where n is the number of elements of that array.
2).int a[4]={1,2,3,4} 
3).int a[4]={ } or int a[4]={0} 
Here,by default all the elements of array will be 0.
4).int a[4]={1}
so, array elements will be 1,0,0,0 only first elements will be assigned the given values others will be 0.
5).int a[4]={[0...1]=2}
Here,the indices 0 to 1 will be assigned value 2 and rest will be 0.
**Advantages of Array-**
1.Use of less line of code as it creates a single array of multiple elements.
2.Easy access to all the elements.
3.Traversal through the array becomes easy using a single loop.
4.Sorting becomes easy as it can be accomplished by writing less line of code.
**Disadvantages of an Array-**
1.Allows a fixed number of elements to be entered which is decided at the time of declaration. Unlike a linked list, an array in C is not dynamic.
2.Insertion and deletion of elements can be costly since the elements are needed to be managed in accordance with the new memory allocation.
**How to access Array Elements-**
Array elements can be accessed using indices which are in integer form.It starts from 0 to size of array -1.
If our given index is out of bound then some garbage value will be printed in that case.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Prateek-8168** [comment]
I want to work with this issue.

**Comment by jyotibajaj729** [comment]
> I want to work with this issue.

But i have been assigned this now.can u plzz take some other issue.
