### ISSUE TITLE
Install a database engine and SQL Syntax 🛢

### ISSUE THREAD

**Issue by Ash515** [girlscript/winter-of-contributing#2012]
### Description

Learn how to install the Database tools and the SQL syntax.  

### Domain

Database

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by mmeghana2405** [comment]
Hello, I would like to work on this issue by making a video.
Batch: 1

**Comment by Ash515** [comment]
> Hello, I would like to work on this issue by making a video.
> Batch: 1

Okay @mmeghana2405

**Comment by Ash515** [comment]
@UditJain77  already documenation doing by Mr. @hariharas-wq and video by @mmeghana2405   so you can choose any other medium

**Comment by UditJain77** [comment]
But the format is to write in this way "/assign Content Type", I wrote in exactly that format
