### ISSUE TITLE
JS: Operators in JavaScript

### ISSUE THREAD

**Issue by Himanshu664** [girlscript/winter-of-contributing#202]
# Operators in JavaScript

### Directory

```
Topics/5.Syntax/2.Operators
```

### Description

* Talk about the various operators in JavaScript.
* Arithmetic, Assignment, Increment and Decrement, Comparison, Logical, Bitwise.
* Explain operators types through examples.

### Hints

* Check out the [W3C tutorial](https://www.w3schools.com/js/js_operators.asp)

## Formats
- [x] Document
- [ ] Video
- [ ] Audio

**Comment by Himanshu664** [comment]
Hello Mentor, Can I work on this issue.

**Comment by Himanshu664** [comment]
@paramsiddharth please label this issue I want to work on it.

**Comment by rwiteshbera** [comment]
I also want to contribute on this issue. @paramsiddharth Can you please assigned me this issue?

**Comment by siddhi-244** [comment]
Can I try this?

**Comment by hshrivastav** [comment]
I can also want to work it on.Can you please assigned me this issue?

**Comment by paramsiddharth** [comment]
Issue updated. You may proceed with the contribution.

**Comment by pradeepks10** [comment]
i can also want to work it on. Can you please assigned me this issue?

**Comment by Himanshu664** [comment]
@paramsiddharth sir why my PR is not merged yet
