### ISSUE TITLE
Benefits of Open Source Contribution

### ISSUE THREAD

**Issue by aaheli8** [girlscript/winter-of-contributing#203]
**Description**
- To discuss the benefits of open source contribution
- Can learn more about open source projects

**Comment by aaheli8** [comment]
Mentor, can I be assigned to work on this issue

**Comment by chakitg** [comment]
I want to contribute to this... please assign this issue to me.
Language: English
OpenSouce Batch-1: Chakit Gupta | Contributor

**Comment by LegendSumeet** [comment]
I want to contribute to this... please assign this issue to me. @Aryamanz29
