### ISSUE TITLE
FRONTEND WITH FRAMEWORK: VueJS-2.1 => Data and Methods

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [girlscript/winter-of-contributing#2063]
Contributors are required to explain about Data and Methods in Vue.js, which should cover questions like:-
What is Data in Vue.js?
What is Methods in Vue.js?
Why it is needed?
How do they work?
How to use it? (Explain with basic code)
etc....

**Note:**
Plagiarism is strictly prohibited.

Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Files need to be added into the Week2 folder only.

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by CSAURABH** [comment]
@SourabhSaraswat-191939  can I work on this issue?

**Comment by anandhu720** [comment]
@CSAURABH we have repeated many times,you can work only in one issue at a time.Please don't do this again

**Comment by Prateek-8168** [comment]
I want to work with this issue.

**Comment by madildev** [comment]
I would like to work on this issue

**Comment by SourabhSaraswat-191939** [comment]
Hey @Prateek-8168, any updates?
It's being too long, we are not getting any updates from your side.
If you are facing any problems while working on this issue. Let us know. We will help you out.

**Comment by SourabhSaraswat-191939** [comment]
> I would like to work on this issue

@madildev, This is the already assigned issue. We will be going to raise new issues soon. You can work on that.
Or you can also work on issues on which the assigned person is not active, if we found any then we will assign that to you and then you can start working on that. I will ping you If I found any.

**Comment by madildev** [comment]
No its not like that.. Just stuck in a bit of mess.. I am working with it..
Will get it done with it really soon..

**Comment by madildev** [comment]
> > I would like to work on this issue
> 
> @madildev, This is the already assigned issue. We will be going to raise new issues soon. You can work on that.
> Or you can also work on issues on which the assigned person is not active, if we found any then we will assign that to you and then you can start working on that. I will ping you If I found any.

No, issue just let me know when the issue related to Vue becomes available.. Thanks..

**Comment by RIYANSHGARG** [comment]
@SourabhSaraswat-191939 hey if no one is working on it please assign it to me.

**Comment by Prateek-8168** [comment]
I am stuck after made the documentation.

**Comment by SourabhSaraswat-191939** [comment]
@Prateek-8168, this PR is opened from last 18 days. Please update us if you are facing any issues.

**Comment by anandhu720** [comment]
@Prateek-8168 If you will not respond in one day we will re-assign this task.

**Comment by SourabhSaraswat-191939** [comment]
@CSAURABH, are there any updates related to this issue?
If you are facing any kind of issue while solving this, then let me know I will help you out.
