### ISSUE TITLE
Android-Java: Drawable Resource Overview.

### ISSUE THREAD

**Issue by ShivaniAgarwal2001** [girlscript/winter-of-contributing#2077]
### Description

1. Inflate/paste an image resource (bitmap Image or file) in your project.
2. Create an XML resource file that defines the drawable properties.
  2.1. Create Custom Resource files.
          2.1.1. shape.
      2.1.2. selector.
      2.1.3. layer-list.
  2.2. Create Image Assets.
  2.3. Create Vector Assets.

### Domain

Android Dev (Java), Open Source

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- #1092 
- #1883

**Comment by ShivaniAgarwal2001** [comment]
Please Mentor @VikasPandey121 allow me to contribute in it.

**Comment by Koustubh-lapate** [comment]
Please Mentor @VikasPandey121 assign me the issue to contribute in it.
