### ISSUE TITLE
Introduction to HTML

### ISSUE THREAD

**Issue by RIYANSHGARG** [girlscript/winter-of-contributing#208]
I will cover 
1. What is HTML
2. Sample HTML structure
3. HTML element

**Comment by RIYANSHGARG** [comment]
Can I write content on this topic ?

**Comment by LavleenAgrawal** [comment]
I want to make video content on this, May I ?
- Lavleen Agrawal (Batch 1 - Python)

**Comment by CSAURABH** [comment]
@RIYANSHGARG I have already created this issue.

**Comment by Bhavika2210** [comment]
I would like to write about history of HTML

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.
Fronted Batch 9

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by aniket7515** [comment]
I would like to work on this issue. I  have experience in web and I will create a full detailed and structured documentation .
