### ISSUE TITLE
4 Sum

### ISSUE THREAD

**Issue by vk-2501** [girlscript/winter-of-contributing#2089]
### Description

Given an array nums of n integers, return an array of all the unique quadruplets [nums[a], nums[b], nums[c], nums[d]] such that:

0 <= a, b, c, d < n
a, b, c, and d are distinct.
nums[a] + nums[b] + nums[c] + nums[d] == target

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vk-2501** [comment]
> \assign

**Comment by vk-2501** [comment]
how to do that?

**Comment by Koustav-1250** [comment]
I think we cannot assign self -assign issue to someone else.

**Comment by vk-2501** [comment]
I didnt got you. We can create issues but we cannot work on our issues?

**Comment by Koustav-1250** [comment]
Yes you can work on your issue. Definitely.

**Comment by vk-2501** [comment]
ok and who will accept out pull request?

**Comment by Koustav-1250** [comment]
I have sent you email . Can you ask there. It's not good to ask there I
guess in github.

**Comment by Koustav-1250** [comment]
I have sent you email.

**Comment by Koustav-1250** [comment]
Basically you have to merge pull request to link your issue.
