### ISSUE TITLE
Front End -1 -> CSS: Introduction to CSS

### ISSUE THREAD

**Issue by Asmit2952** [girlscript/winter-of-contributing#209]
I have seen the roadmap given and I would like to contribute about Introduction to CSS.

Topics to be covered :

* Introduction to css
* Selectors and pseudo selector
* Classes and Id’s
* CSS general rule
* Colors in css

Mentors, please assign me this issue. I have good working knowledge of CSS

**Comment by Asmit2952** [comment]
I have opened this issue by seeing the roadmap and I want to contribute for the same.

**Comment by LavleenAgrawal** [comment]
I want to make video content on this, May I ?
- Lavleen Agrawal (Batch 18 - Frontend)

**Comment by Rijudas149** [comment]
May I work on this issue??? I want to work on this

**Comment by Asmit2952** [comment]
> I want to make video content on this, May I ?
> - Lavleen Agrawal (Batch 18 - Frontend)

We can both work on this, I'll do the documentation part, if it's fine with u?

**Comment by LavleenAgrawal** [comment]
> > I want to make video content on this, May I ?
> > 
> > * Lavleen Agrawal (Batch 18 - Frontend)
> 
> We can both work on this, I'll do the documentation part, if it's fine with u?

No Asmit mentors and supervisors will assign us that... once assigned we can start..!

**Comment by Asmit2952** [comment]
> > > I want to make video content on this, May I ?
> > > 
> > > * Lavleen Agrawal (Batch 18 - Frontend)
> > 
> > We can both work on this, I'll do the documentation part, if it's fine with u?
> 
> No Asmit mentors and supervisors will assign us that... once assigned we can start..!

Cool✌🏻

**Comment by siddhi-244** [comment]
Plzz assign this to me

**Comment by Asmit2952** [comment]
@praveenscience please assign this issue to me

**Comment by trip0le** [comment]
Hi @praveenscience Sir, This is Titas Nath(batch 6, frontend with HTML, css). May I contribute on this topic?

**Comment by jaigora24** [comment]
Can I go for it?

**Comment by LavleenAgrawal** [comment]
Hey @Asmit2952....Why did you closed it.....?? You are a contributor and its not allowed to.....Praveen sir was asking about it...please reply to this text...

**Comment by Asmit2952** [comment]
> Hey @Asmit2952....Why did you closed it.....?? You are a contributor and its not allowed to.....Praveen sir was asking about it...please reply to this text...

I guess I saw another issue and PR was also merged.
