### ISSUE TITLE
K means algorithm 

### ISSUE THREAD

**Issue by shreyarai05** [girlscript/winter-of-contributing#2098]
### Description

There will be brief theory along with code examples for defining k means algorithm  and how we can use this to solve real life problems.

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment]
This issue is already done. If you want audio / video you can comment on the respective issue. So this issue has to be closed. 
@shreyarai05
