### ISSUE TITLE
OpenSource :  1.1 Rise Of Open Source Programming Languages

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#21]
### Description :
- **Explain the " Rise Of Open Source Programming Languages "**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by Chirag-creator17** [comment]
I would like to work on this issue.

**Comment by Aryamanz29** [comment]
> I would like to work on this issue.

Sure @Chirag-creator17, Assigning this to you ☀
Happy Documenting 🙌

**Comment by Chirag-creator17** [comment]
What should be the length of readme file ?

**Comment by Aryamanz29** [comment]
> What should be the length of readme file ?
> 

I'm not sure about specific length of the file , but it should cover all mention topics in it .

**Comment by Chirag-creator17** [comment]
how to raise a pr by google colab?

**Comment by Aryamanz29** [comment]
> how to raise a pr by google colab?
> 

If you're not comfortable with google colab then try to submit your work in markdown file

**Comment by Aryamanz29** [comment]
PR merged , Closing this issue now
