### ISSUE TITLE
Inheritance in java (Java Core-OOPs concepts)

### ISSUE THREAD

**Issue by saniya44** [girlscript/winter-of-contributing#2101]
### Description

**What is inheritance in java?**

### Domain

Backend Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saniya44** [comment]
> /assign

> Will you also contribute?

**Comment by akarshlahariya11** [comment]
Yes, I'll also contibute and I think that atleast 2-3 people can work on a same issue.

**Comment by saniya44** [comment]
> Yes, I'll also contibute. 
> I think that atleast 2-3 people can work on a same issue.

> Okay 👍 I am doing in the form of documentation, can you do audio or video. Cause only one person can contribute to single format, so you contribute audio or video. Let me know so that I will add label to it👍

**Comment by akarshlahariya11** [comment]
> > Yes, I'll also contibute.
> > I think that atleast 2-3 people can work on a same issue.
> 
> > Okay 👍 I am doing in the form of documentation, can you do audio or video. Cause only one person can contribute to single format, so you contribute audio or video. Let me know so that I will add label to it👍

Actually, I did already  submitted it in the doc format.
