### ISSUE TITLE
[JS: Video for difference between const, var and let]: 

### ISSUE THREAD

**Issue by 2devyank** [girlscript/winter-of-contributing#2106]
### Description

Topics/5.Syntax/Variable_Initialization

### Domain

JavaScript

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by 2devyank** [comment]
@paramsiddharth please assign this issue to me as there wasn't any issue on this topic based on video contribution

**Comment by paramsiddharth** [comment]
@2devyank Actually, you could have reused #395 for the video-based contribution too. Each topic is represented by an independent issue, no matter what format the contribution is, which I mentioned in the contribution guide update last week. I'll close this issue. @2devyank and @Ayushi2811 , please go and comment on #395 to be assigned.
