### ISSUE TITLE
[Create New Issue]: HTML Lists

### ISSUE THREAD

**Issue by shubh045** [girlscript/winter-of-contributing#2112]
### Description

 About Lists in HTML 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Rutumbhara** [comment]
@shubh045 I wanted to contribute to this issue if it is not assigned to anyone else.

**Comment by shubh045** [comment]
@Rutumbhara if you want to contribute to this topic in other format than document then maybe you can do, as somebody else's work for this topic in document format has already been merged, and maybe that is why they are not merging my pull request

**Comment by Rutumbhara** [comment]
Ok
