### ISSUE TITLE
Front End JavaScript: Code structure 

### ISSUE THREAD

**Issue by Asmit2952** [girlscript/winter-of-contributing#212]
I have seen the roadmap given and I would like to contribute about JavaScript.

Topics to be covered: 

* Code Structure

I have a good working knowledge of JavaScript and different libraries.

**Comment by Asmit2952** [comment]
Mentors, I have opened this issue as I want to contribute to it. Please assign me this issue. I have a good working knowledge of JS.

**Comment by Rijudas149** [comment]
I want to work on this issue

**Comment by Asmit2952** [comment]
@praveenscience @ghulamyazdani please assign this issue to me.

**Comment by Asmit2952** [comment]
@praveenscience I checked the roadmap and I want to work on this. Can I start documenting it?
