### ISSUE TITLE
[JS] Issue: Regular Expressions  

### ISSUE THREAD

**Issue by subhendudash02** [girlscript/winter-of-contributing#2142]
### Description

Introducing the topic of Regular Expressions and their significance in JavaScript.

<b>Mode: </b> Documentation

## Directory
`JavaScript/Topics/13.Regular_Expressions`

### Domain

JavaScript

### Type of Contribution

- [ ] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by subhendudash02** [comment]
@paramsiddharth @Creatoon @dakshsethi @s4-2 Kindly review this issue.
Thank you!

**Comment by akratikushwah** [comment]
I would not be able to work on this issue please unassign it to me.

**Comment by shreya-gb** [comment]
@subhendudash02 I'll work on this, please?

**Comment by rits8027** [comment]
Ok

**Comment by subhendudash02** [comment]
> @subhendudash02 I'll work on this, please?

Ask @paramsiddharth
