### ISSUE TITLE
friend functions & friend classes in c++

### ISSUE THREAD

**Issue by Akriti-Choudhary** [girlscript/winter-of-contributing#2166]
### Description

documentation on friend functions and friend classes in c++ 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vasu-1** [comment]
### Hey @aman12207 you cannot assign this issue to yourself because this issue is created by @Akriti-Choudhary .
### kindly unassign @aman12207 
### @Akriti-Choudhary please assign it to yourself 

@aman12207 you can make another issue or pick up another one , but it should not be already exist or any duplicates or already assigned. !

**Comment by vasu-1** [comment]
@Akriti-Choudhary  don't worry we will do it by our end.
you can continue your work !

**Comment by aman12207** [comment]
Please tell me the command to unassign this issue.

**Comment by Akriti-Choudhary** [comment]
@vasu-1 Thankyou.

**Comment by vasu-1** [comment]
Hey @aman12207  
You can unassigned from here .. please do ASAP.
![IMG_20210923_194458](https://user-images.githubusercontent.com/76911582/134524010-6d55f3e4-3221-47c6-b71a-8aa909ae0e13.jpg)

After unassigned @Akriti-Choudhary  please assign it to yourself..👍👍

**Comment by aman12207** [comment]
@vasu-1 I unassigned this project. Sorry for inconvenience.

**Comment by vasu-1** [comment]
It is all okk @aman12207 . Go Ahead !

@Akriti-Choudhary  Please assign this to yourself !

**Comment by Akriti-Choudhary** [comment]
@vasu-1 What do you suggest ? How can I self-assign this project?

**Comment by vasu-1** [comment]
hey ! i think you have 3 open issues ..
if you have done pr for those issues then you  can simply close those issues.. 
and you can again try here/assign

**Comment by Akriti-Choudhary** [comment]
@vasu-1 The PRs are not merged . Will, there be a problem if I will close those issues without them getting merged?

**Comment by vasu-1** [comment]
Please be patient !
your one of the pr will be merge shortly !
after that you can close that respective issue and pr as well !!

**Comment by Akriti-Choudhary** [comment]
okay, Thankyou.

**Comment by vasu-1** [comment]
now you can close that respective issue and try here !
