### ISSUE TITLE
OpenSource : Explain Setting up Docker Environment and create a Project.

### ISSUE THREAD

**Issue by Harshil-Jani** [girlscript/winter-of-contributing#2167]
### Description

- How to configure our projects with ```Docker```.
- Use ```docker``` with your project and document the whole process in steps.

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Harshil-Jani** [comment]
@Aryamanz29 On the continuation of #632 I would like to  document this !

**Comment by aaditya2801** [comment]
please /assign, I want to add my docker learnings 👍.

**Comment by Harshil-Jani** [comment]
@Aryamanz29  Can you please check on this? Any updates.

**Comment by Aryamanz29** [comment]
@Harshil-Jani  Assigning this to you , Happy learning 🎉🎉

**Comment by Harshil-Jani** [comment]
> @Harshil-Jani Assigning this to you , Happy learning

Hey Thanks for Assigning ! Can You please guide me regarding topic number ? You are giving any unique topic number of shall I name it as 5.4_Docker ?
