### ISSUE TITLE
Competitive_Programming: Stack In C++

### ISSUE THREAD

**Issue by ravireddy07** [girlscript/winter-of-contributing#218]
I would like to write a doc on Stack Data Structure in C++.
Competitive_Programming
* Introduction
* Syntax and Implementation
* Operations
* Use cases
* Complexity Differences

Please assign this to me. Thanks

**Comment by siddhi-244** [comment]
Can I try it?

**Comment by supriya-045** [comment]
sir, i would like to work on it.Please assign it to me.

**Comment by Vidit-Ostwal** [comment]
I don't know how the things works in GWoC, whether contributor themselves can make the issue and can contribute directly to it, or the issue needs to  be first created by mentor/supervisor, then contributor can contribute,

PS: @siddhi-244 & @supriya-045 , @ravireddy07 itself is a contributor, 'Read the last line' he is asking to assign it to him.

**Comment by ravireddy07** [comment]
@Vidit-Ostwal  Yes. Contributor's can create issues. But, can't work on it until it gets assigned by mentors.

**Comment by janvist** [comment]
i would like to work on this. please assign this to me.

**Comment by Ayushi2811** [comment]
I would like to contribute on this issue by presentaing a well flow structured  documentation and take it from a beginer to an expertise level explanation.Do assign it to me.
Ayushi Chauhan
Batch-1

**Comment by anjalikumawat2002** [comment]
I want to try on this issue.
Anjali Kumawat
Batch - 3
