### ISSUE TITLE
Objects and arrays in javascript 

### ISSUE THREAD

**Issue by siddhi-244** [girlscript/winter-of-contributing#219]
Please assign this to me.

**Comment by Rijudas149** [comment]
which language???

**Comment by Kavindra-Mohan-Dwivedi** [comment]
I would love to work on this issue . Please assign this to me

**Comment by VedRatan** [comment]
I would like to try my hands in this issue

**Comment by samridhikapoor** [comment]
I would like to contribute on this issue via documentation or video
I would request you to assign this issue to me.
Thanks and regards

**Comment by amankumar11** [comment]
I would like to contribute to the documentation part. Can you pls assign this issue to me?
