### ISSUE TITLE
Introduction to C

### ISSUE THREAD

**Issue by ikavyajain** [girlscript/winter-of-contributing#2190]
### Description

I have prepared a presentation on:
INTRODUCTION TO C
[x] Some facts and features about C Programming Language
[x] Advantages & Disadvantages
[x] Syntax and Semantics
[x] Errors 
[x] C Data Types
[x] Variable declaration in C
[x] Special use of sizeof() operator

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as PR got merged !
