### ISSUE TITLE
ML 1.14 : ANOVA (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2198]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **ANOVA**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [x] Documentation

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by TishaJhabak1014** [comment]
Full name : Tisha Jhabak
Batch Number : 6
GitHub Profile Link : https://github.com/TishaJhabak1014
Which type of Contribution you want to make : Documentation
@Isha307 plz do assign me this.

/assign

**Comment by amitrakshar01** [comment]
I would like to be assigned
Name: Amitrakshar Sanyal
Batch: 5
GitHub: github.com/amitrakshar01

**Comment by amitrakshar01** [comment]
Name: Amitrakshar Sanyal
Batch 5
https://github.com/amitrakshar01

I would like to be assigned.

**Comment by abhisheks008** [comment]
Please make the PR @TishaJhabak1014

**Comment by TishaJhabak1014** [comment]
@Isha307 @abhisheks008 Raised a PR. Thank you.
