### ISSUE TITLE
OpenSource :  1.2 What Is a Distributed Version Control System (DVCS)?

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#22]
### Description :

- **What Is a Distributed Version Control System (DVCS)?**
- **The Evolution of Version Control Systems.**
- **Limitations of the DVCS Model.**
- **Why Companies Switch to Distributed Version Control System (DVCS) instead of CVCS?**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by Dhruv-194** [comment]
Can I work on this issue?

**Comment by Aryamanz29** [comment]
@Dhruv-194  Sure, I'll assign this to you !!
Happy Documenting 🙌

**Comment by Akshat-2002-coder** [comment]
sir can I work on this issue?

**Comment by Aryamanz29** [comment]
> sir can I work on this issue?

@Akshat-2002-coder  Hey thanks for asking , Actually this issue is already been assigned to contributor so can you look other plenty of open issues,  thanks✌️

**Comment by Aryamanz29** [comment]
@Dhruv-194  Any updates on this ?

**Comment by siddhi-244** [comment]
> > sir can I work on this issue?
> 
> @Akshat-2002-coder Hey thanks for asking , Actually this issue is already been assigned to contributor so can you look other plenty of open issues, thanks

There are no issues open.

**Comment by Aryamanz29** [comment]
> > > sir can I work on this issue?
> > 
> > 
> > @Akshat-2002-coder Hey thanks for asking , Actually this issue is already been assigned to contributor so can you look other plenty of open issues, thanks
> 
> There are no issues open.

Hey @siddhi-244  👋, You can create a new issue that you want to work under `open_source_domain`

**Comment by siddhi-244** [comment]
> > > > sir can I work on this issue?
> > > 
> > > 
> > > @Akshat-2002-coder Hey thanks for asking , Actually this issue is already been assigned to contributor so can you look other plenty of open issues, thanks
> > 
> > 
> > There are no issues open.
> 
> Hey @siddhi-244 👋, You can create a new issue that you want to work under `open_source_domain`

Where is the road map?? And I have opened a new issue there is no reply for that.

**Comment by Dhruv-194** [comment]
> @Dhruv-194 Any updates on this ?

I will complete this issue by today itself. Thank you for reminding :)

**Comment by Aryamanz29** [comment]
@Dhruv-194  Updates??

**Comment by Dhruv-194** [comment]
Hey @Aryamanz29 I was working on this issue. And I am having two problems with it. 
1. I cannot a find a lot of detailed information for the evolution of DVCS. So can we add any other topic in place of it. 
2. The second one is for companies switching to CVCS. Are you sure that companies are switching to CVCS? Because wherever I go, I read that most of the companies have started to use DVCS instead of CVCS. So is there a mistake in the heading?

**Comment by Aryamanz29** [comment]
> Hey @Aryamanz29 I was working on this issue. And I am having two problems with it.
> 
> 1. I cannot a find a lot of detailed information for the evolution of DVCS. So can we add any other topic in place of it.
> 2. The second one is for companies switching to CVCS. Are you sure that companies are switching to CVCS? Because wherever I go, I read that most of the companies have started to use DVCS instead of CVCS. So is there a mistake in the heading?

1. We need to add content about DVCS, So we can't change that right now
2. Yes there is a typo it should be DVCS

**Comment by Aryamanz29** [comment]
@Dhruv-194  I have changed issue description, Please look into this
Here is ref for you : https://www.slideshare.net/caniszczyk/evolution-of-version-control-in-open-source

**Comment by Aryamanz29** [comment]
@Dhruv-194  Try to complete this issue today
Thanks

**Comment by Dhruv-194** [comment]
Okay Thank you @Aryamanz29
