### ISSUE TITLE
Front_End: Conventions & Best Practices

### ISSUE THREAD

**Issue by ravireddy07** [girlscript/winter-of-contributing#220]
I would like to write a Doc on _**Conventions & Best Practices**_ while writing HTML code/scripts.

* I would be mentioning best and bad practices.
* an explanation with appropriate examples.

Please Assign this to me. Thanks
@2024-SANDHYA

**Comment by Rijudas149** [comment]
I can work on this issue.. plz assign me

**Comment by kumaradityaraj** [comment]
I would also like to contribute to this topic.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> I would like to write a Doc on _**Conventions & Best Practices**_ while writing HTML code/scripts.
> 
>     * I would be mentioning best and bad practices.
> 
>     * an explanation with appropriate examples.
> 
> 
> Please Assign this to me. Thanks
> @2024-SANDHYA

Sure assigned @ravireddy07

**Comment by ravireddy07** [comment]
Hey @2024-SANDHYA , Added the Doc. 
Review it once and let me know, if anything required to change.

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : Front_End: Conventions & Best Practices
Name-Arya Gupta 
Domain-Frontend with HTML CSS
Batch-16 
Serial No-3172
Issue Number-220
Contribution Approaches-
Usage of best practices and proper convention increases code readability (proper document structure, mentioning the doctype, closing tags, avoiding the usage of inline CSS, using an alt attribute for images and the usage of proper semantic tags)

**Comment by Kalyani02072003** [comment]
can i be assigned in this?
batch - 18 frontend
discord - STRAWHAT_LUFFY#8651

**Comment by Alankrita9** [comment]
I would like to write a Doc on Conventions & Best Practices while writing HTML code/scripts.

I would be mentioning best and bad practices.
an explanation with appropriate examples.
Please Assign this to me. Thanks
@2024-SANDHYA

**Comment by ravireddy07** [comment]
Merged([#550](https://github.com/girlscript/winter-of-contributing/pull/510)) and closing this Issue.
