### ISSUE TITLE
ML 1.14 : ANOVA (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2200]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **ANOVA**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [x] Audio

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Arjun2905** [comment]
Arjun Wankhede
ML Batch 3
Type of contribution : Audio
https://github.com/Arjun2905

**Comment by Arjun2905** [comment]
@Isha307  assign this to me

**Comment by Isha307** [comment]
@Arjun2905 You can work on it.

**Comment by abhisheks008** [comment]
What's the update @Arjun2905 ?

**Comment by Arjun2905** [comment]
@abhisheks008 I'll be starting to work on it. I have one issue going on in other domain. Till monday night I will create a pull request for this.

**Comment by abhisheks008** [comment]
Okay! @Arjun2905

**Comment by abhisheks008** [comment]
@Arjun2905 update on this issue.

**Comment by Arjun2905** [comment]
@Isha307 Please go through my pull request https://github.com/girlscript/winter-of-contributing/pull/3684
sorry for the delay.
