### ISSUE TITLE
ML 1.14 : ANOVA (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2203]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **ANOVA**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [x] Video

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aaryan078** [comment]
/assign
I would like to work on this issue
Name: Aaryan
Type: Documentation
I will complete this in 12 days

**Comment by Isha307** [comment]
@aaryan078 Remember that this issue is for video not for documentation.

**Comment by aaryan078** [comment]
@Isha307  sorry  i can't do it in video format

**Comment by riyasai22** [comment]
if this issue is still open I would like to contribute to this issue. @abhisheks008
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22
Contribution type: Video

**Comment by riyasai22** [comment]
I've submitted my PR @abhisheks008 
Kindly review it.
