### ISSUE TITLE
ML 1.13 : Confidence Interval (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2207]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Confidence Interval**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [x] Audio

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by abhisheks008** [comment]
@TishaJhabak1014 1 issue at a time and do not use self assign tag, mention us we'll assign you tasks.

**Comment by 101Priyanshi** [comment]
Full name : Priyanshi Saxena
Batch Number : 5
GitHub Profile Link : https://github.com/101Priyanshi
type of Contribution :  Audio

**Comment by abhisheks008** [comment]
Issue assigned @101Priyanshi. Complete it by Monday (27.09.2021)

**Comment by 101Priyanshi** [comment]
Do I need to attach the audio here itself?

**Comment by abhisheks008** [comment]
You have create a md file with proper naming, and then insert the link there in proper syntax provided in the Demo folder. You can check out others contributions to have an idea of it. @101Priyanshi

**Comment by 101Priyanshi** [comment]
I have completed the task and created a pull request as well
