### ISSUE TITLE
[Programming Fundamentals : JavaScript ]: 

### ISSUE THREAD

**Issue by Nandani-koli** [girlscript/winter-of-contributing#2208]
### Description

**Frontend With HTML/CSS/JS**
In Programming Fundamentals folder
Add detail about JavaScript:- 
 Control structures

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Riya-Bisht** [comment]
@Nandani-koli hey, can I work on this issue? I dont have any idea how to assign myself to any issue so, can you please tell me how to do that? I tried writing this --> /assign but do I have to wait ?

**Comment by Nandani-koli** [comment]
@Riya-Bisht This one is already assigned to me, so you cannot assign the issue which is already assign to someone else. you have to create your own issue on the topic which is not already taken by someone else and then use this /assign command for self assign.

**Comment by Riya-Bisht** [comment]
> @Riya-Bisht This one is already assigned to me, so you cannot assign the issue which is already assign to someone else. you have to create your own issue on the topic which is not already taken by someone else and then use this /assign command for self assign.

Ok @Nandani-koli thank you :)

**Comment by code-reaper08** [comment]
Closing this with respect to #7099 
If anybody have plans to contribute in form of audio or video, you can tag me here, I'll reopen the issue.
