### ISSUE TITLE
Insertion in Binary Search Tree

### ISSUE THREAD

**Issue by VARUN-K-BANSAL** [girlscript/winter-of-contributing#2213]
### Description

In this documentation I will add logic and code for inserting a new node or data in a Binary Search Tree.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this issue as the PR got merged ! You can open new issues !!
