### ISSUE TITLE
DSA 1.2.3.1 Algorithms : Space Complexity

### ISSUE THREAD

**Issue by lvi131** [girlscript/winter-of-contributing#2233]
### Description

Analysis of space complexity of algorithms.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by goelesha** [comment]
@lvi131 
Pls, refrain from getting the issue assigned yourself. 
You can go ahead with this issue. But change the name according to the guidelines.

**Comment by lvi131** [comment]
@goelesha 
Sorry for self assigning.
Can you please help me with the name, I am not sure about the numbering in it - 
DSA 1.2.??? Algorithms: Space Complexity

**Comment by goelesha** [comment]
Can you pls elaborate what exactly you will be adding in space complexity ?

**Comment by goelesha** [comment]
> @goelesha
> Sorry for self assigning.
> Can you please help me with the name, I am not sure about the numbering in it -
> DSA 1.2.??? Algorithms: Space Complexity

Can you pls elaborate what exactly you will be adding in space complexity ?

**Comment by lvi131** [comment]
@goelesha 
Definition, 1 or 2 simple examples how to calculate, one example of recursive algo, and auxiliary space vs space complexity

**Comment by goelesha** [comment]
Okay. You can go ahead with the issue. I will rename it myself

**Comment by lvi131** [comment]
Okay Thanks.
