### ISSUE TITLE
Application of Cpp

### ISSUE THREAD

**Issue by RaghavvGupta** [girlscript/winter-of-contributing#2243]
### Description

I would like to work on the topic of real world applications of Cpp.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as PR #4600 got merged
