### ISSUE TITLE
Front End : Introduction to HTML

### ISSUE THREAD

**Issue by I-ArchanaDash** [girlscript/winter-of-contributing#225]
I would like to work on this issue in the form of Audio. 
Please assign it to me.
Regards.

**Comment by siddhi-244** [comment]
I want to work on it in form of documentation

**Comment by tavneetgill** [comment]
I would like to work on this issue using documentation and audio. Can I go for it?

**Comment by Rijudas149** [comment]
I want to work on this issue

**Comment by chetan-2002** [comment]
I want to work on the documentation part if anyone wants to collaborate with me in writing the documentation, You are always welcome. Cheers :)

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.
Fronted Batch 9

**Comment by uditkatyal** [comment]
I would like to work on this issue.
I have well defined written notes which I will convert to proper documentation

**Comment by EktaAgrawal** [comment]
Hello sir , I am quite proficient and interested in html. Kindly assign me!

**Comment by beecoder-pro** [comment]
I would like to provide step by step instructions with code snippets for this issue.

**Comment by Aryan283** [comment]
I would like to work on this issue
