### ISSUE TITLE
MERN_MongoDB: 1.1 What is MongoDB?(V)

### ISSUE THREAD

**Issue by saloni-15** [girlscript/winter-of-contributing#2252]
## What is MongoDB?
Provide the .md file containing the drive link for MP4 video explaining "**Introduction to MongoDB in MERN stack**".

## Project directory
`Branch MERN>MERN/Topic/Backend/MongoDB/`

## File Name
`1.1_What_is_MongoDB?(V).md`

### Domain

MERN

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saloni-15** [comment]
hey @pankaj-Makhijani , what's the status of this issue?

**Comment by pankaj-Makhijani** [comment]
@saloni-15 Working on it, but somework is still pending so will be creating pull request tomorrow.

**Comment by pankaj-Makhijani** [comment]
Hey @saloni-15 I made a PR, kindly review it and let me know if any changes are needed to be done.
