### ISSUE TITLE
Front-end -->CSS : Colors in CSS

### ISSUE THREAD

**Issue by Yashesvinee** [girlscript/winter-of-contributing#226]
I would like to contribute to this in the form of a documentation
Yashesvinee V (Batch 4)

**Comment by Rijudas149** [comment]
I want to work on this issue.. plz assign me

**Comment by Asmit2952** [comment]
I had already opened an issue

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.
Fronted Batch 9
