### ISSUE TITLE
Principal Component Analysis with python

### ISSUE THREAD

**Issue by shreyarai05** [girlscript/winter-of-contributing#2262]
### Description

It will describe how this algoritham can be used to solve real issues .Need to include theory along with code files for demonstration.

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do documentation on this issue.
my approach: A detailed explanation with code

**Comment by shreyarai05** [comment]
This issue has been assigned to me i guess

**Comment by prathimacode-hub** [comment]
@shreyarai05 you had created this issue by own, but there is already an issue running and assigned to someone else. Don't create issues without notifying to avoid duplication. Else your efforts would be wasted.

**Comment by shreyarai05** [comment]
Where should I notify about issue created?
