### ISSUE TITLE
 Frontend Dev (HTML, CSS, JS) : HTML TABLE

### ISSUE THREAD

**Issue by Baba-Yaga-1** [girlscript/winter-of-contributing#227]
I would like to contribute about HTML table along with its example code and screenshots of the output in the form of documentation.

**Comment by aman12207** [comment]
I would like to work on this issue

**Comment by ramii17** [comment]
I am interested on the topic HTML TABLES , i ll contribute the documentation with the example codes and output screenshots. It would be great if u assign this to me . Thanks

Regards,
RAMYA KM || CONTRIBUTOR

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.
Fronted Batch 9

**Comment by khush2706** [comment]
I am interested to contribute to this via documentation. Please consider me for this..
Khushboo Chaturvedi
Batch-18

**Comment by joshi-anita** [comment]
I am interested to contribute to this i have previously worked on this and i have  a good knowledge of working on html table..
please consider me for this 
Anita joshi 
batch 17

**Comment by shailja-mishra** [comment]
Hi @praveenscience sir . I would like to contribute to the HTML tables via documentation . I will make sure that People get a clear insight of tables along with examples . kindly assign this to me
Batch - 14 (Frontend with html,css,js &bootstrap)
