### ISSUE TITLE
OpenSource : 3.8 Process to submit a patch to linux kernel 

### ISSUE THREAD

**Issue by ashish-patwal** [girlscript/winter-of-contributing#2271]
#### Linux is arguably the largest opensource project in the whole world . This project is the backbone of many other technologies and industries . Many linux enthusiasts dream of contributing to the linux kernel but don't know how to get started with submitting patches . Write a detailed document , regarding the process of submitting patches to the linux kernel.
<br>

*Key points to include*
 * Using checkpatch.pl to verify your changes
 * How to generate a patch with git format-patch
 * Emailing the patch to the maintainers
 
*Resource to give you a headstart - [Linux Kernel Patch](https://www.youtube.com/watch?v=LLBrBBImJt4)*

### NOTE 👇
Please put your doc `inside section-6` if not present create new folder `section-6`

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by amitrakshar01** [comment]
I want to contribute Open Source Batch 4

**Comment by ashish-patwal** [comment]
@amitrakshar01 Please use the /assign command to assign yourself to this issue !! Happy contributing .

**Comment by ashish-patwal** [comment]
@amitrakshar01 , Please do take a look at the resource i have provided in the issue template . It will give you a great headstart . Then you can do your research accordingly to make the documentation .
