### ISSUE TITLE
Demo video !

### ISSUE THREAD

**Issue by Saviour1001** [girlscript/winter-of-contributing#2283]
### Description

Adding this and this 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
@Suvraneel hey I WAS WORKING ON THIS !!

**Comment by Suvraneel** [comment]
@Saviour1001  Lmao
