### ISSUE TITLE
Front end : CSS Box Model

### ISSUE THREAD

**Issue by Baba-Yaga-1** [girlscript/winter-of-contributing#229]
I would like to contribute about CSS box model along with its example and screenshots of the output in the form of documentation.
@praveenscience  kindly assign this to me. I am a GWOC contributor.

**Comment by Rijudas149** [comment]
I want to work on this issue

**Comment by LavleenAgrawal** [comment]
@praveenscience I want to make video content on this, May I ?

Lavleen Agrawal (Batch 18 - Frontend)
