### ISSUE TITLE
Update Datatype Readme

### ISSUE THREAD

**Issue by priyankapiba** [girlscript/winter-of-contributing#2294]
### Description

#Data types
##What are data types(Definition)?
###What are various data types in Python? Explain with examples. 

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyankapiba** [comment]
@adityabisoi  please assign me this issue.

**Comment by adityabisoi** [comment]
> @adityabisoi please assign me this issue.
> I would like to work on it.

You can star working on it

**Comment by adityabisoi** [comment]
@hritikksingh Is the mentor of this issue. Please reach out to him for your queries.
