### ISSUE TITLE
OpenSource : 1.3 Recent OS Projects (Ex : Android, Chromium OS, etc)

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#23]
### Description :

-  **Explain Recent OS Projects (ex : Android, Chromium OS, etc)**
-  **Idea behind why organization started ?**
-  **Tech they're currently using for maintaining those projects**
-  **Their Future plans**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

#### Reference :  
https://www.androidauthority.com/what-is-chrome-os-1137371/
https://www.chromium.org/chromium-os
https://opensource.google/projects/android

## Happy Contributing 🙌

**Comment by RAMESSESII2** [comment]
I already have an interest in Linux (Fedora OS user) and I would love to contribute to this because that gives me an opportunity to learn about other open-source OSs. 
So, hey, @Aryamanz29  assign it to me.

**Comment by Aryamanz29** [comment]
> I already have an interest in Linux (Fedora OS user) and I would love to contribute to this because that gives me an opportunity to learn about other open-source OSs. 
> So, hey, @Aryamanz29  assign it to me.

Glad to see your enthusiasm @RAMESSESII2 🙂 , Go ahead ✌️

**Comment by RAMESSESII2** [comment]
> Glad to see your enthusiasm @RAMESSESII2  , Go ahead

Thank you

**Comment by Aryamanz29** [comment]
@RAMESSESII2  Any updates on this ?

**Comment by RAMESSESII2** [comment]
> @RAMESSESII2 Any updates on this ?

Yeah, I'm working on it, expect a PR very soon.
