### ISSUE TITLE
DSA : Longest Arithmetic Subarray

### ISSUE THREAD

**Issue by priyanka001tech** [girlscript/winter-of-contributing#2305]
### Description

A has an array of N non-negative integers. A wants to calculate maximum length of contiguous arithmetic subarray.

Arithmetic Subarray is an array that contains at least two integers and the difference between consecutive integers are equal. For example  [9,10] , [3,3,3] and [9,7,5,3] arithmetic arrays.

Input: No. of test cases T
          integer no N
          array A[]
 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by dhruti29** [comment]
I would like to work on this issue. 
BATCH - 2 DSA
Dhruti Gandhi
