### ISSUE TITLE
Front End : HTML forms

### ISSUE THREAD

**Issue by I-ArchanaDash** [girlscript/winter-of-contributing#231]
I would like to work on this issue and add documentation to it in a detailed manner.
Please assign it to me.
Regards.

**Comment by siddhi-244** [comment]
> I would like to work on this issue and add documentation to it in a detailed manner.
> Please assign it to me.
> Regards.

I have already opened it.

**Comment by samridhikapoor** [comment]
I would like to contribute on this issue via documentation or video

**Comment by Rijudas149** [comment]
I want to work on this issue

**Comment by hshrivastav** [comment]
I would like to work on this issue and add documentation to it in a detailed manner can add ss of code examples too.
Please assign it to me.
Regards

**Comment by pradeepks10** [comment]
I want  to work on this issue and add documentation to it in a detailed manner.
please assign it to me.

**Comment by SushantPatial** [comment]
I want to work on this issue.

**Comment by vkaash-sharma** [comment]
I want to work on this I have full pledged knowledge about it u can go through my portfolio and check my contact me form where I use my skills of HTML FORMS.
https://vkaash-sharma.github.io/vikas-portfolio/

**Comment by shailja-mishra** [comment]
i would like to work on this issue via documentation . I'm pretty good at html forms . I request @praveenscience to assign this issue to me
Name - Shailja Mishra
Batch - 14 (frontend with html , css ,js and bootstrap)

**Comment by I-ArchanaDash** [comment]
Since Many people have opened the same issue, I have closed mine.
