### ISSUE TITLE
CSS general rule

### ISSUE THREAD

**Issue by brassgolem-25** [girlscript/winter-of-contributing#2313]
### Description

I'll be adding documentation about rule's one should follow for css.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by chakitg** [comment]
Hey creator, I would like to work on this issue, is it possible now? Can you please assign me this?
Name: Chakit Gupta
Batch: Frontend With Html-Css-js Batch-4
Type: Documentation

**Comment by brassgolem-25** [comment]
@chakitg no not possible.

**Comment by brassgolem-25** [comment]
The pr for this issue has been merged so closing the issue...
