### ISSUE TITLE
JS: Events in JavaScript 

### ISSUE THREAD

**Issue by sushovanb02** [girlscript/winter-of-contributing#2319]
# Description

- What is an Event ?
- Mouse events
- Keyboard events
- onclick Event Type
- onsubmit Event Type

# Directory
```Topics/15.Events```

### Domain

JavaScript

### Type of Contribution

Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sushovanb02** [comment]
@paramsiddharth assign me please

**Comment by sushovanb02** [comment]
@paramsiddharth assign me please

**Comment by Creatoon** [comment]
@paramsiddharth I think naming a topic events is very general, as events occurs in normal life but handling events is programming, so i think topic name should be Event_Handler.

**Comment by paramsiddharth** [comment]
> @paramsiddharth I think naming a topic events is very general, as events occurs in normal life but handling events is programming, so i think topic name should be Event_Handler.

@sushovanb02 I am closing this issue since this is for front-end event handling and we already have an issue and PR for the same (see #761). If you want to make this issue about events in the back-end/command-line (Node.js), you may edit and reopen the issue (which I'm planning to do, soon).
