### ISSUE TITLE
Frontend with HTML, CSS : What is Flex Box and Flex Properties

### ISSUE THREAD

**Issue by YASHMAROO** [girlscript/winter-of-contributing#232]
<hr>

## Description 📜
Documentation on the topic - FlexBox and Flex Properties

<hr>

## Domain of Contribution 📊
- [x] Frontend Dev HTML/CSS/JS
<hr>

**Comment by Rijudas149** [comment]
I want to work on this issue

**Comment by h2o-Noob** [comment]
I would like to work on this issue by providing documentation. I have a good knowledge of css flexbox and worked alot with them in past projects

**Comment by samridhikapoor** [comment]
I would like to contribute on this issue via documentation or video
I would request you to assign this issue to me.
Thanks and regards

**Comment by cookieg13** [comment]
Hi sir! I would love to contribute on this topic, can you please assign it to me? Debarati Ghatak, Frontend Batch 5

**Comment by uditkatyal** [comment]
I would love to contribute to this issue.
flex and its properties always become a menace for a student studying it the first time.
I will try to explain in a way that would make understanding flex very easy and fun.

**Comment by vkaash-sharma** [comment]
I would like to contribute to this issue.
I know how flex works I am familiar with all the properties of flex I work on document areas in such a way that beginners can understand easily lastly I make my own portfolio there I use flex a lot.

https://vkaash-sharma.github.io/vikas-portfolio/
