### ISSUE TITLE
C/CPP : Infix, Prefix and Postfix ( Application of Stack )

### ISSUE THREAD

**Issue by PranaySanjule** [girlscript/winter-of-contributing#2327]
## Description 📜

I will create a folder Stack ( in the CPP Domain ) and inside that folder, I will add documentation to explain Application of Stack - Evaluation of Arithmetic Expressions ( Introduction to Infix, Prefix, and Postfix Expressions with code ).
<hr>

## Domain of Contribution 📊

- [x] C/CPP
- [x] DSA

<hr>

**Comment by Saviour1001** [comment]
Closing as the PR got merged !
