### ISSUE TITLE
OpenSource : 3.7 The Pros and Cons of Open Source Software Development

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#234]
includes 
Sense of value
Community recognition
Personal benefits
What Is Great About Developing Open Source Software?
What Is Open Source?

can @Aryamanz29 you assign me to these?

**Comment by Aryamanz29** [comment]
> includes 
> Sense of value
> Community recognition
> Personal benefits
> What Is Great About Developing Open Source Software?
> What Is Open Source?
> 
> 
> can @Aryamanz29 you assign me to these?

Hey @LegendSumeet  , You've already been assigned 2 issues first try to create PR for that then We'll think of working on this.
Thanks

**Comment by Kavindra-Mohan-Dwivedi** [comment]
I would love to work on this issue

**Comment by Aryamanz29** [comment]
> I would love to work on this issue

@Kavindra-Mohan-Dwivedi  Assigning this to you , Happy Documenting 🙌

**Comment by Dracarys0511** [comment]
Please allow me to work on this issue
