### ISSUE TITLE
Frontend Dev (HTML, CSS, JS) : HTML Classes and IDs

### ISSUE THREAD

**Issue by Baba-Yaga-1** [girlscript/winter-of-contributing#235]
I would like to contribute about HTML classes and ids along with its example and screenshots of the output in the form of documentation.
Kindly assign this to me. I am a GWOC contributor.

**Comment by Rijudas149** [comment]
I want to work on this issue

**Comment by LavleenAgrawal** [comment]
I want to make audio content on this, May I ?
Lavleen Agrawal (Batch 18 - Frontend)

**Comment by samridhikapoor** [comment]
I would like to contribute on this issue via documentation or video
I would request you to assign this issue to me.
Thanks and regards

**Comment by Korak-Sengupta** [comment]
I would be extremely glad to work on this issue, through audio and documentation, pleasee assign this to me

**Comment by Pranshu321** [comment]
i would be extremely glad if i get a chance to work on this issue and  i do this in the form of documentation form

**Comment by vatsss** [comment]
I would like to work on this issue via documentation, can you assign it to me?

**Comment by Ayushi2811** [comment]
I would like to work on this issue and make a well structured documentation out of it.Do assign it to me
Ayushi Chauhan
Frontened batch-1

**Comment by SudhansuuRanjan** [comment]
I would like to prepare an interactive documentation . Please assign it to me!!

**Comment by vkaash-sharma** [comment]
I can contribute to this issue I can make interactive documentation on this topic so please assign it to me!

**Comment by FirdausJawed** [comment]
I want to contribute with documentation. Please assign it to me !!
