### ISSUE TITLE
A Complete Guide to Flexbox documentation

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#236]
Documentation Include 👍 :
Background
Basics and terminology
Flexbox properties
Prefixing Flexbox
Examples
Flexbox tricks
Browser support
Bugs
Related properties

can you @praveenscience assign me to these?

**Comment by LavleenAgrawal** [comment]
I want to make audio content on this, May I ?
Lavleen Agrawal (Batch 18 - Frontend)

**Comment by samridhikapoor** [comment]
I would like to contribute on this issue via documentation or video
I would request you to assign this issue to me.
Thanks and regards

**Comment by SushantPatial** [comment]
I would like to contribute to this issue as well

**Comment by joshi-kaushal** [comment]
I would love to contribute to this! I have my personal notes that I can use..
