### ISSUE TITLE
CPP: Ambiguity in Function Overloading 

### ISSUE THREAD

**Issue by ShikhaSwati60** [girlscript/winter-of-contributing#2362]
### Description

I will provide the detailed documentation on ambiguity in function overloading in c++.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged
