### ISSUE TITLE
Lists in C++ STL

### ISSUE THREAD

**Issue by emily876** [girlscript/winter-of-contributing#2370]
### Description

I will give a brief description of lists in STL and its working in c++ .

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vasu-1** [comment]
@emily876 you have created duplicate issue of #1307

kindly delete this issue and also delete the respective pr ! #2455 
Please create another but make sure it should not be duplicate one..

Thanks !

**Comment by emily876** [comment]
@vasu-1  Sorry, I checked it before, but it didn't show up that's why I worked on it. I'll take care of it next time.

**Comment by vasu-1** [comment]
Not an issue !
please delete this issue !
