### ISSUE TITLE
Constructor and Destructor in cpp

### ISSUE THREAD

**Issue by SHUKLA-KUSHAGRA** [girlscript/winter-of-contributing#2371]
### Description

In this we will be discussing in brief about constructors and destructors in cpp.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
Duplicate of #858
