### ISSUE TITLE
Introduction to Operating system in C/CPP domain

### ISSUE THREAD

**Issue by am-dusky** [girlscript/winter-of-contributing#2386]
### Description

I will make a documentation on introduction of Operating System , its need .I will also explain some concepts like multitasking and multiprogramming.

Name-Megha Singh
Batch-1
 @Suvraneel Kindly assign me

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
@am-dusky  Go ahead
