### ISSUE TITLE
HTML : Search Engine Optimisation Basics

### ISSUE THREAD

**Issue by VenkateswarNayak** [girlscript/winter-of-contributing#2396]
<hr>

## Description 📜

I want to work on making a complete documentation on the topic Search Engine Optimisation Basics.
Please /assign this to me.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by VenkateswarNayak** [comment]
@moulikagrawal  @sifa123  Please add the frontend labels to this issue.

**Comment by Yashesvinee** [comment]
Hi I already took up an issue on this topic and it was merged about 3days ago

**Comment by sifa123** [comment]
@VenkateswarNayak you can work on video/ audio...documentation part is already added

**Comment by VenkateswarNayak** [comment]
okay Mam
