### ISSUE TITLE
MERN_MongoDB: 2.1 MongoDB installation and configuration - Windows

### ISSUE THREAD

**Issue by saloni-15** [girlscript/winter-of-contributing#2398]
### Description

Description

## Installing MongoDB on Windows
- **Explain all the steps for installing and configuring MongoDB on Windows.**

## Project Directory
`Branch MERN>MERN/Topic/Backend/MongoDB/`

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by GyaniRoman23** [comment]
Hey @saloni-15 I would like to work with this issue.
