### ISSUE TITLE
OpenSource : 1.4 Why Open Source?

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#24]
### Description :

-  **Why you should open source your projects ?**
-  **Benefits of contributing to an open source softwares**
-  **Good practices while contributing to an open-source software**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by shubhdholakiya** [comment]
Can I work on this? Kindly assign this to me.

**Comment by Aryamanz29** [comment]
> Can I work on this? Kindly assign this to me.

Yea, Sure @shubhdholakiya , Assigning this to you ✅
Happy documenting 🙌

**Comment by shubhdholakiya** [comment]
Can please tell me like I have to make a readme file and write all the answers to the given questions in the above description?

**Comment by Aryamanz29** [comment]
> Can you please tell me like I have to make a readme file and write all the answers to the given questions in the above description?

Hey, You can contribute through `documentation, audio & video`. See: https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md
For documentation, It should be `markdown` format

**Comment by shubhdholakiya** [comment]
> > Can you please tell me like I have to make a readme file and write all the answers to the given questions in the above description?
> 
> Hey, You can contribute through `documentation, audio & video`. See: https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md
> For documentation, It should be `markdown` format

Okay Thank you very much.

**Comment by s4marth** [comment]
@Aryamanz29  May I also work on this issue?

**Comment by shubhdholakiya** [comment]
I will be making a PR by tonight!

**Comment by Aryamanz29** [comment]
@shubhdholakiya  Any updates on this ?

**Comment by paras-saxena11** [comment]
May i contribute in this?

**Comment by Aryamanz29** [comment]
> May i contribute in this?

@paras-saxena11  Can you open a new issue for which you would like to contribute to the `open-source domain `? by following the above issue convention.

**Comment by shubhdholakiya** [comment]
> @shubhdholakiya Any updates on this ?

Yes, will be posting PR by tonight.

**Comment by shubhdholakiya** [comment]
@Aryamanz29 Hey brother, while making PR do I need to add any other document, or do I just need to add the documentation I made?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Hey brother, while making PR do I need to add any other document, or do I just need to add the documentation I made?

Only doc
