### ISSUE TITLE
Data Science with Python : Dealing with Categorical Columns

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#2403]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about working on Dealing with Categorical Columns. Tutorial to Dealing with Categorical Columns and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Peehu Saxena / Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do documentation on this issue.

**Comment by deepthi1107** [comment]
Approach: A detailed explanation.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy. I would like to do a VIDEO on this issue.
Batch number: 5
serial number:174.

**Comment by prathimacode-hub** [comment]
This is created on the request of a contributor. If it's not claimed by evening, it'll will be assigned on queue. There are many more issues coming up. @ashish-reddy-20-08 @deepthi1107

**Comment by deepthi1107** [comment]
ok sure.

**Comment by ashish-reddy-20-08** [comment]
Ok mam, Looking for new issues.
Thank you @prathimacode-hub

**Comment by prathimacode-hub** [comment]
New issues are created. Check on to them. @ashish-reddy-20-08 @deepthi1107

**Comment by ayushi424** [comment]
Name: Ayushi Shrivastava
S No: 811
Approach to be followed:  
-  Documentation 
 - Categorical columns might hamper the efficiency of a ML model so to deal with it we can convert categorical columns into numerical and enhance the efficiency of a ML model using a example dataset with proper code and explanation.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ayushi424 for documentation

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Mam can i work on the video part for this

**Comment by prathimacode-hub** [comment]
Yes, issue assigned to @ashish-reddy-20-08 for documentation

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you evaluate the PR mam 
Link of PR: https://github.com/girlscript/winter-of-contributing/pull/2906
Name: M. Ashish Reddy
Batch - 5

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you evaluate the PR mam
Link of PR: #2906
Name: M. Ashish Reddy
Batch - 5

**Comment by tavneetgill** [comment]
@prathimacode-hub I would like to work on this issue
Name: Tavneet Kaur Gill
Serial No. 323
Type: Audio
Approach: Explanation how it works, what it means, how to incorporate in different topics of data science

**Comment by SaloniThete** [comment]
Name: Saloni Thete
Sr.No: 821
Type: Documentation
Approach: Solutions and their detailed explanation to dealing with categorical columns along with resources and examples.
@prathimacode-hub Kindly assign :)

**Comment by prathimacode-hub** [comment]
Issue assigned to @tavneetgill for audio contribution

@SaloniThete, for documentation, audio and video it's already assigned. You can try for some other issue.

**Comment by SaloniThete** [comment]
Sure,Thanks :)
