### ISSUE TITLE
Data Science with Python : Getting Started with Theano

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#2409]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Getting Started with Theano. Tutorial to Theano and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Deep Learning

Mentors Assigned : Aarya Patel / Nithin

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sera001** [comment]
I would like to contribute to this issue.
Name: Jeffy Johnson
Serial number: 713
Type: Documentation
Approach: What is Theano?, Implementation, sample code, advantages

**Comment by prathimacode-hub** [comment]
Have you addressed your earlier PR, if not do so before starting into this. Anyways I have assigned this issue to @Sera001 for documentation

**Comment by tavneetgill** [comment]
I would like to contribute to this issue.
Name: Tavneet Kaur Gill
Serial number: 323
Type: Audio
Approach: Definition of Theano ,Implementation, sample code, usage

**Comment by prathimacode-hub** [comment]
Issue assigned to @tavneetgill for audio contribution

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution
