### ISSUE TITLE
Android-Architecture

### ISSUE THREAD

**Issue by thejayeshsoni** [girlscript/winter-of-contributing#241]
### Platform Architecture 
Android is an open source, Linux-based software stack created for a wide array of devices and form factors.

### The main components of android architecture are following:-

- System Apps
- Java API framework
- Native C/C++ libraries
- Android Runtime
- Hardware abstraction layer (HAL)
- Linux Kernel

### Resources:-
[https://developer.android.com/guide/platform](url)
[https://www.geeksforgeeks.org/android-architecture/](url)

Can I work on this issue sir @salil-naik @paramsiddharth

**Comment by paramsiddharth** [comment]
@thejayeshsoni Looks great to me! Please request assignment from an Android/Mobile domain supervisor.
