### ISSUE TITLE
CSS Loaders

### ISSUE THREAD

**Issue by S07K** [girlscript/winter-of-contributing#2419]
### Description

How To Create different types of Loaders using CSS.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Bhuvnesh875** [comment]
hello, i would like to work for this issue!
