### ISSUE TITLE
Programming Paradigms

### ISSUE THREAD

**Issue by deepali2002-max** [girlscript/winter-of-contributing#2424]
### Description

I have added documentation of programming paradigms

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as PR  #2429 got merged
