### ISSUE TITLE
Frontend with HTML, CSS: Responsive Design and Media Queries

### ISSUE THREAD

**Issue by YASHMAROO** [girlscript/winter-of-contributing#243]
I would like to work on the above topic's documentation @praveenscience. 
In my previous projects, I had worked extensively with the media queries and making websites responsive in any view.  So I have good knowledge on the above-said topic and would like to share this knowledge with everyone.

**Comment by LavleenAgrawal** [comment]
I want to make audio content on this, May I ?
Lavleen Agrawal (Batch 18 - Frontend)

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.
Fronted Batch 9

**Comment by cookieg13** [comment]
Hi sir! I would love to contribute on this topic, can you please assign it to me? 

- Debarati Ghatak,
-  Frontend Batch 5

**Comment by jaigora24** [comment]
Can I go for it?

**Comment by Baalamurgan** [comment]
I am interested working on this topic. Let me know the update!

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by joshi-anita** [comment]
i am interested for working on this 
Anita Joshi
Batch-17
