### ISSUE TITLE
[Create New Issue]: CPP : KMP Algorithm for Pattern Searching

### ISSUE THREAD

**Issue by akashshukla7458** [girlscript/winter-of-contributing#2435]
### Description

KMP Algorithm for Pattern Searching .
Given a text txt[0..n-1] and a pattern pat[0..m-1], write a function search(char pat[], char txt[]) that prints all occurrences of pat[] in txt[]. You may assume that n > m.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this issue as #5367 got merged
