### ISSUE TITLE
[Create New Issue]: Hoisting

### ISSUE THREAD

**Issue by Moeen-Ul-Islam** [girlscript/winter-of-contributing#2449]
### Description

Documentation

### Domain

JavaScript

### Type of Contribution

Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Moeen-Ul-Islam** [comment]
Should I close the issue with attaching file here itself or make a PR ?

**Comment by paramsiddharth** [comment]
> @paramsiddharth Should I close the issue with attaching file here itself or make a PR ?

@Moeen-Ul-Islam Please look at #161. An issue already exists for hoisting.
