### ISSUE TITLE
[Create New Issue]: Find the next greater element

### ISSUE THREAD

**Issue by AnkitaGupta454** [girlscript/winter-of-contributing#2454]
### Description

Description  find next greater element in an array

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ujju20** [comment]
Please assign it to me.
