### ISSUE TITLE
[DSA]:  Range queries in arrays

### ISSUE THREAD

**Issue by meghna750** [girlscript/winter-of-contributing#2456]
### Description

Range queries in arrays:
1. MO's algorithm
2. range LCM queries
3. Array range queries over t=range queries

I will use proper documentation and the best examples so that a newbie can understand these concepts.
Very excited to work on these topics, please assign them to me.

### Domain

DSA

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanka001tech** [comment]
I would like to contribute

**Comment by priyanka001tech** [comment]
BATCH NO 1
DSA

**Comment by nimisha-yadav** [comment]
This topic has already been covered so closing this issue.
