### ISSUE TITLE
[C/C++]: Decision making 

### ISSUE THREAD

**Issue by meghna750** [girlscript/winter-of-contributing#2467]
### Description

I will add all details of if, else and else if statements in a very easy way that even a newbie can understand it easily!
I will use the documentation for this purpose.

### Domain

C/CPP

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by LegendSumeet** [comment]
assign me @meghna750

**Comment by vasu-1** [comment]
@rishitajain01  @meghna750 @LegendSumeet 

- one person can only work on one issue
- issue should not be duplicates ( if you want to work on the same topic you have to change your type of contribution but again this should also not be any duplicate )
i hopw it will make sense to all of you !!!

**Comment by rishitajain01** [comment]
@vasu-1 Can I modify my documentation content?

**Comment by LegendSumeet** [comment]
video assign me

**Comment by vasu-1** [comment]
> video assign me

Hey @Subhampreet 
Please make another Issue.. of this topic and opt for video format.....
And assign it to yourself 
For assigning to yourself you will have to type ` /assign `
