### ISSUE TITLE
SQLData types and SQL Operators 🛠🛢

### ISSUE THREAD

**Issue by Ash515** [girlscript/winter-of-contributing#2468]
### Description

Data types and operators are the backbone for every programming languages, start to learn the concept in SQL programming  and contribute here.

### If it is in document mode of contribution, you have to write in **.md file**  i.e Readme file. 

Happy Contributing !!

### Domain

Database

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by LegendSumeet** [comment]
assign me

**Comment by hariketsheth** [comment]
/assign 
@Ash515 - Would like to contribute to this, if possible. Thank you !
