### ISSUE TITLE
Deletion in Binary Search Tree

### ISSUE THREAD

**Issue by VARUN-K-BANSAL** [girlscript/winter-of-contributing#2474]
### Description

Generating this issue to add documentation of deletion of a particular element in Binary Search Tree.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged
