### ISSUE TITLE
Open Source : npm in opensource

### ISSUE THREAD

**Issue by ashish-patwal** [girlscript/winter-of-contributing#2479]
#### The npm Registry is a repository of open-source software packages hosted by npm for the Node. js developer community. Using npm's hosted service is free for open source software, and private package hosting is available for teams and individual developers.
<br>

*Points to Note*
* Describe and explain npm and npm packages 
* Their role in promoting opensource , shareable software for everyone . 
* Setting up npm in various operating system and linux distributions  .
* Basic commands used in npm .
* npm vs npx 

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by eshan1925** [comment]
@ashish-patwal where to store the .MD file while creating PR. Please mention it.

**Comment by ashish-patwal** [comment]
> @ashish-patwal where to store the .MD file while creating PR. Please mention it.

Put it in the /Open_Source/Section-6 directory . If Section-6 directory doesn't exist , please do make one yourself . Give an appropriate title to the md file eg (npm_in_opensource.md) and then make a pr with it .

**Comment by ashish-patwal** [comment]
@eshan1925 Thank you for your contribution . I have already given green light to your PR . It just needs a final review from the supervisor , who will then merge the branch into the respective repository folder .
