### ISSUE TITLE
Python: 3.2 Operators: arithmetic & assignment operators

### ISSUE THREAD

**Issue by vanshhhhh** [girlscript/winter-of-contributing#249]
@adityabisoi I would like to work on the documentation of the specified topic. I will work on all the sub-topics given in the Python roadmap (i.e. Arithmetic operators, Assignment operators, Comparison operators, Logical operators, Identity operators, Membership operators, Bitwise operators).
Please assign me this issue. Thanks.

Vansh Sharma (Python Batch 3)

**Comment by ragavan14** [comment]
@adityabisoi I would like to work on the documentation of the specified topic. I have good experience in python and its functionalities
Please assign me this issue. Thanks.

B.Ragavan (Python Batch 6)

**Comment by yashh18** [comment]
@adityabisoi I'd like to work on the documentation or code of the project. I am a 5 star coder in Python @HackerRank
Thanks !!
Yash Kataria(Python batch-3)

**Comment by nayakaj** [comment]
i would lovw to do plz assign

**Comment by Malvikakaushal2001** [comment]
I want to contribute in this issue
I am from Python batch-3

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me. 
@adityabisoi 
python batch 4

**Comment by adityabisoi** [comment]
> i would like to work on this via audio or video. please assign this to me.
> @adityabisoi
> python batch 4

One issue at a time, please. If you make a PR, you'll be assigned new issues, then.

**Comment by adityabisoi** [comment]
**Only arithmetic & assignment operators are to be covered.**
This issue is open for AUDIO and VIDEO contributions.

**Comment by darkhorse-2000** [comment]
I can contribute in this issue by documentation or video
Python Batch - 4

**Comment by Cyber-Prajwal** [comment]
I want to contribute in form of a video tutorial, please assign me the video part @adityabisoi
Prajwal Bang
python batch 1

**Comment by adityabisoi** [comment]
@darkhorse-2000 Video, This issue is open for AUDIO

**Comment by shecoderfinally** [comment]
@adityabisoi Please assign this to me for audio contribution

**Comment by subhoshreep** [comment]
@adityabisoi please assign me this issue I can contribute in audio form
subhoshree Pattnaik
batch 1 python

**Comment by anjalikumawat2002** [comment]
@adityabisoi I want to contribute this in audio form.
Anjali Kumawat
Batch - 6  Python

**Comment by vandana3869** [comment]
I would like contribute to this issue in the video form. Please assign me

**Comment by priyanshinaredi** [comment]
@adityabisoi I Priyanshi Naredi would like to contribute to operators for documentation purposes it would be great if you assign e this thank you.

**Comment by rohit-goyal** [comment]
Hello 
My name is Rohit goyal 
i am from Python Batch-6
i want to contribute/work in this issue via documentation

**Comment by anjalikumawat2002** [comment]
@adityabisoi I want to contribute this in audio form.
Anjali Kumawat
Batch - 6 Python

**Comment by SouravKr2001** [comment]
I am from Python Batch-1
I want to contribute/work in this issue via documentation

**Comment by mohansaitejatalari** [comment]
I would be thankful and request you to allow me to  resolve this issue by documentation.

**Comment by adityabisoi** [comment]
> I would be thankful and request you to allow me to resolve this issue by documentation.

You'll have to comment early on from next time.

**Comment by vanshhhhh** [comment]
@adityabisoi please go through my PR.

**Comment by adityabisoi** [comment]
@prathimacode-hub Is the mentor of this issue. Please reach out to her incase of any queries.

**Comment by prathimacode-hub** [comment]
@darkhorse-2000 @vanshhhhh @anjalikumawat2002 , I am a mentor for this issue. If any queries, feel free to ask. If you had made a PR, Add up your PR links here.
