### ISSUE TITLE
search an elemennt in an array

### ISSUE THREAD

**Issue by string-SAm** [girlscript/winter-of-contributing#2495]
### Description

using dsa solving problem search an element in an array.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by thepallavi02** [comment]
I would like to work on this issue. kindly assign it to me !/assign video.
