### ISSUE TITLE
Cybersecurity: 3.9.2 Malware 

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#2499]
### Description

##Description:
Explain What are Malwares, and preventions.

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by iamKushGupta** [comment]
Can I be assigned the documentation for this issue ??

**Comment by iamKushGupta** [comment]
I noticed that you weren't online but this issue was available, 
so I took the step of commenting first on it, 
and made the above pull request. (Since, I was done with my previous Issues)

Hopefully, there won't be any problem... 
@Anant1711
