### ISSUE TITLE
OpenSource : 2. Getting Started With Open Source

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#25]
### Description :

-  **Getting Started With Open Source**
     -  **Build a good Tech-Related background**
         - Software products are built with different kinds of tech stacks and
also by following different architectural patterns. Therefore it is
better to study **_architectural patterns, design patterns, and
well-known technologies_** before you begin anything.

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by priyanshuc4423** [comment]
please assign me

**Comment by Aryamanz29** [comment]
> please assign me

Assigning this to you @priyanshuc4423 
Happy Documenting 🙌

**Comment by Aryamanz29** [comment]
PR merged #164 , Closing this issue
