### ISSUE TITLE
Frontend : CSS : Content manipulation - margin,padding,align

### ISSUE THREAD

**Issue by TuhinBanerjee31** [girlscript/winter-of-contributing#250]
I would like to work on this issue in the form of documentation under Gwoc-21 .

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.
frontend batch 9

**Comment by trip0le** [comment]
@praveenscience I would like to contribute on this topic by means of audio and video.

**Comment by ishitam-29** [comment]
I'm familiar with this. Can You assign me this? Ishita mittal (batch-1 frontend with HTML,CSS)

**Comment by Mayank242002** [comment]
I have a great knowledge of box model.Can you assign this issue to me?

**Comment by vkaash-sharma** [comment]
I have great knowledge of margins padding I can write on this topic in a detailed manner. u can check my previous project where how I use margins paddings.

https://vkaash-sharma.github.io/vikas-portfolio/

**Comment by rishitajain01** [comment]
\assign documentation & video

**Comment by vaibhavkumar5** [comment]
#2633

**Comment by vaibhavkumar5** [comment]
Refer PR #2633
