### ISSUE TITLE
Cybersecurity: 3.9.4 Cloud Jacking

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#2502]
### Description

##Description
Explain What is Cloud jacking.

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by iamKushGupta** [comment]
I am done with the previous issue [Cybersecurity 3.9.2 Malware #2499](with Plagarism check), 
Can I be assigned this issue for the documentation part ?

**Comment by Anant1711** [comment]
> I am done with the previous issue [Cybersecurity 3.9.2 Malware #2499](with Plagarism check),
> Can I be assigned this issue for the documentation part ?

Okay!
