### ISSUE TITLE
Cybersecurity 3.9.5 MAN-IN-THE-MIDDLE attack

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#2503]
### Description

##Description

Explain in detail what is MAN-IN-THE-MIDDLE attack, How it can be done, How we can prevent ourselves!

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by medhatiwari** [comment]
I would like to contribute to this. Please assign this to me @Anant1711 
`Documentation`

**Comment by medhatiwari** [comment]
\ assign

**Comment by prithwishpramanik** [comment]
/ assign video

**Comment by Anant1711** [comment]
> / assign video

assigned!
