### ISSUE TITLE
Front-end : CSS Button Styling

### ISSUE THREAD

**Issue by KhafiaAyyub** [girlscript/winter-of-contributing#252]

**Comment by GopinathBalaji** [comment]
I have adequate knowledge of CSS styling. Can I please have this issue.

**Comment by gsk-007** [comment]
I am interested in working on the documentation.

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.

**Comment by cookieg13** [comment]
Hi ! I would love to contribute on this topic, can you please assign it to me? Debarati Ghatak, Frontend Batch 5

**Comment by uditkatyal** [comment]
I would like to work on this issue! 
I am quite good knowledge of designing elements.

**Comment by trip0le** [comment]
Hi @praveenscience  Sir, This is Titas Nath(batch 6, frontend with HTML, css). May I contribute on this topic?

**Comment by EktaAgrawal** [comment]
Hello sir @praveenscience ,  I am quite proficient and interested in CSS button styling. Kindly assign me!

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.Please consider me for this..
Riya Pandey
Batch-2

**Comment by Rishika-Gaur** [comment]
I am interested in contributing to this topic too.

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : CSS Button Styling
Name-Arya Gupta 
Domain-Frontend with HTML CSS
Batch-16 
Serial No-3172
Issue Number-252
Contribution Approaches-What is CSS button styling, About the button tag (using border, margin,padding,color,background-color,box shadow,using the transition property to change styling)

**Comment by anushka-mishra-code** [comment]
I would be glad to work on this issue.
Name : Anushka Mishra
Batch : 1
Serial No.: 175
Type : Documentation
Approach:

Brief Introduction to HTML ,CSS, JavaScript
explaination of CSS in detail
major focus on styling buttons in CSS with examples

**Comment by suvangi2205** [comment]
I have adequate knowledge in styling buttons with CSS.Can I contribute to the documentation part?
Batch 1

**Comment by preestine** [comment]
Hello!
My name is Preeti Chaudhari (Sr.No.2157,Batch:11).
I would be glad to work on the documentation part for this issue.

**Comment by mansisingh2803** [comment]
I would like to contribute to this issue
Mansi Singh
Batch-7
Type : video

**Comment by Akshay-kumar01** [comment]
I would like to work on this issue : CSS button styling.

Akshay Kumar Singh
Batch : 18
Type : Documentation and code example, explaining full concept.

**Comment by rishabh2030** [comment]
please assign me this issue i will work on it and Definitely make it amazing

**Comment by baibhav0305** [comment]
pls assign this issue to me
/assign

**Comment by Meet-011** [comment]
Please assign me this topic, I would like to work on this issue.

Name : Meet

Type : Documentation

Approach
1. Will brief about HTML ,CSS, JavaScript
2. Explanation of CSS in detail
3. Styling buttons in CSS with various examples
