### ISSUE TITLE
[Open Source]: Deployment projects in Github Pages

### ISSUE THREAD

**Issue by anupamishra333** [girlscript/winter-of-contributing#2523]
### Description

Description

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
Already covered #315 @anupamishra333
