### ISSUE TITLE
Android-Kotlin: 00.2 Readme Update W.R.T Roadmap

### ISSUE THREAD

**Issue by rahulsain** [girlscript/winter-of-contributing#254]
Update the [readme](https://github.com/girlscript/winter-of-contributing/blob/Android_Development_With_Kotlin/Android_Development_with_Kotlin/README.md) of Android Dev with Kotlin with the content given in the roadmap (already given in the #general channel) with clean documentation.

**Comment by Lakshit-Chiranjiv** [comment]
I would like to work on this after you share the roadmap

**Comment by rahulsain** [comment]
@Lakshit-Chiranjiv You can proceed with this task.

**Comment by Lakshit-Chiranjiv** [comment]
> @Lakshit-Chiranjiv You can proceed with this task.

Got this!!
