### ISSUE TITLE
exit() and _Exit() Functions in C++ [Documentation]

### ISSUE THREAD

**Issue by ritika728** [girlscript/winter-of-contributing#2548]
### Description

I will explain about exit() and _Exit() Functions along with proper examples in documentation form.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as PR got merged.
