### ISSUE TITLE
Python: File Handling  & Exception Handlling 

### ISSUE THREAD

**Issue by TechnoPhasePRO** [girlscript/winter-of-contributing#256]
**PYTHON**
FILE HANDLING & EXCEPTION HANDLING IN PYTHON

### FILE HANDLING IN PYTHON 

- Opening & Closing Files.
- Working of different Modes

### EXCEPTION HANDLING

- WHAT ARE EXCEPTIONS & ITS TYPES
- USE OF EXCEPTION HANDLING
- WORKING OF TRY..EXCEPT CLAUSES
- RAISING EXCEPTIONS 

### format

- [ ] DOCUMENTATION

**Comment by TechnoPhasePRO** [comment]
@adityabisoi I would love to work on this issuue. please assign lables to this issue.

**Comment by lohith1392** [comment]
I am intrested in working over the documentation 
Peddi sai lohith
Python batch 4

**Comment by shaurya24sri** [comment]
I am interested in working with this issue.
@shaurya24sri
Python-batch 5

**Comment by Malvikakaushal2001** [comment]
I want to contribute in this issue
I am from Python batch-3

**Comment by CodeSavitar** [comment]
I would like to contribute to this issue. (Python Batch 3)

**Comment by adityabisoi** [comment]
This topic is handled much later in the roadmap. We're in our first week now. I'll create this issue later.
