### ISSUE TITLE
OpenSource : 3.8 Finding Issues on Github

### ISSUE THREAD

**Issue by Harshil-Jani** [girlscript/winter-of-contributing#257]
Documentation on 
- Understanding the Github Search Bar
- Creating and Finding Issues
- Adding Labels

**Comment by Harshil-Jani** [comment]
Batch-1
Open Source Contributor
Can I try with this one for documenting?

**Comment by Aryamanz29** [comment]
Nice issue , We need that @Harshil-Jani Thanks for creating 🙌 . Assigning this to you . Happy Documenting 🎉

**Comment by nayakaj** [comment]
i wanna do it plz assign

**Comment by Aryamanz29** [comment]
> You've already assigned one issue , please complete that first
