### ISSUE TITLE
Menu Driven Code to implement stack 

### ISSUE THREAD

**Issue by itsgourav62** [girlscript/winter-of-contributing#2570]
### Description

A menu driven program in C to perform the following operations using stack:
Create(); Push(); Pop(); Traverse()

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this issue as the PR got merged !! Open new issues !
