### ISSUE TITLE
Python: basic data types

### ISSUE THREAD

**Issue by lohith1392** [girlscript/winter-of-contributing#258]
Contains all data types used in python like 
Str
Int 
Float

**Comment by VidhiBhatt01** [comment]
I would like to do this

**Comment by lohith1392** [comment]
@adityabisoi can I work on this documentation
Peddi sai lohith
Batch 4 python

**Comment by lohith1392** [comment]
@VidhiBhatt01 actually I did this topic for me

**Comment by shaurya24sri** [comment]
I am Shaurya
python batch 5
I would like to work on the issue

**Comment by samruddhikadam** [comment]
@adityabisoi can i work on this
python batch 4
audio or video format

**Comment by yashh18** [comment]
I can contribute to it
I am pretty well versed about all the data types used in python!
Yash Kataria (Python Batch-3)

**Comment by adityabisoi** [comment]
This issue has already been created.
