### ISSUE TITLE
C_CPP: Overloaded Constructor

### ISSUE THREAD

**Issue by 124015001** [girlscript/winter-of-contributing#2582]
### Description

documentation

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR is merged
