### ISSUE TITLE
C_CPP: Fenwick tree in C++ 

### ISSUE THREAD

**Issue by adityaraj079** [girlscript/winter-of-contributing#2595]
### Description

Description
Fenwick tree in C++

Where is this topic in the roadmap:
Roadmap -> C++ -> Data Structures -> User Defined -> Fenwick Tree

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by gunjan-g** [comment]
@adityaraj079 you can proceed with this

**Comment by adityaraj079** [comment]
@gunjan-g you can check the pr created

**Comment by adityaraj079** [comment]
@gunjan-g can you check the pr

**Comment by gunjan-g** [comment]
> @gunjan-g can you check the pr

I have reviewed it already
