### ISSUE TITLE
Android-Java: 3.5 Android Explicit Intent Example

### ISSUE THREAD

**Issue by Pradumnasaraf** [girlscript/winter-of-contributing#2599]
### Description

1) Implicit vs explicit intent
1) What are Explicit Intent 
2) eg by Calling one activity from another activity

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Pradumnasaraf** [comment]
@Rohit-2602 @VikasPandey121 Please check .

**Comment by VikasPandey121** [comment]
> @Rohit-2602 @VikasPandey121 Please check.

If you created a PR on this issue then please tag the issue number on your PR like #2599 so that I can look into it,
