### ISSUE TITLE
OpenSource : 2.1 Practice Git and Github fundamentals

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#26]
### Description :

-  **Explain `Git and Github fundamentals` & their` contribution workflow`.**
-  **About `Github actions`**
-   - When there is collaborative work on a codebase well-managed
source code management is highly recommended. Most of the
open-source projects are using Git as the **SCM (Source Code
Management)** tool and they use Github as the hosting service for
Git repositories. Therefore Git experience and being familiar with
Github is required skills to work with open source projects. 

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by developer-metalhead** [comment]
Can I be assigned this issue?

**Comment by Aryamanz29** [comment]
> Can I be assigned this issue?

Sure @developer-metalhead 😀
Happy Documenting 🙌

**Comment by developer-metalhead** [comment]
Thank You @Aryamanz29

**Comment by ajaykathwate** [comment]
Heyy
I would like to contribute to this issue 
can you assign it to me?

**Comment by Aryamanz29** [comment]
@ajaykathwate  This issue was already been assigned to @developer-metalhead  and he already has made PR, We'll create more issues in a couple of days.
Thanks
