### ISSUE TITLE
[Java 6.2]: Switch Blocks Code Fix 

### ISSUE THREAD

**Issue by ganaaduvva** [girlscript/winter-of-contributing#2608]
### Description

In the documentation of **Switch blocks**, I felt it need some _example modification_ and _syntax highlighting_ 

### Domain

Java_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AkMo3** [comment]
Documentation PR merged.  Other 2 domains are available to take.
