### ISSUE TITLE
Unordered multimap

### ISSUE THREAD

**Issue by sujal2048** [girlscript/winter-of-contributing#2610]
### Description

Unordered multimaps are associative containers that store elements formed by the combination of a key value and a mapped value, much like unordered map , but allowing different elements to have equivalent keys and hence it is main advantage of using it.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vasu-1** [comment]
> /assign

Only One person can work on the issue !!! @Anandkx007
