### ISSUE TITLE
MERN_NodeJs 3.1 JSON

### ISSUE THREAD

**Issue by EkjotKaur** [girlscript/winter-of-contributing#2614]
# Instructions
## Project directory
`Branch MERN>Web_Development/MERN/Topic/Backend/Node/`

FileName: 3.1_JSON.md

## JSON 
Give brief introduction of JSON and how it is used

## Task

- [ ]  Audio
- [ ]  Documentation
- [ ]  Video

### Send a PR in the following branch only and make documentation in form of markdown file with (.md) extension and in the respective folder

**Comment by aishapervin** [comment]
@EkjotKaur ,i will be working with the documentation part.

**Comment by EkjotKaur** [comment]
> @EkjotKaur ,i will be working with the documentation part.

Go head.

**Comment by aishapervin** [comment]
Kindly close the issue now that it is merged,because i have to assign myself in other isssues too.Since the issue is already open,i am not able to assign myself others.Thankyou
