### ISSUE TITLE
MERN_NodeJs 4.2 Example of using a module

### ISSUE THREAD

**Issue by EkjotKaur** [girlscript/winter-of-contributing#2619]
# Instructions

## Project directory
`Branch MERN>Web_Development/MERN/Topic/Backend/Node/`

FileName: 4.2_Example of using modules.md

## Example of using a module?
Import a module and show its working ( you can show it's function in console) 

# Task

- [ ]  Audio
- [ ]  Documentation
- [ ]  Video

## Send a PR in the following branch only and make documentation in form of markdown file with (.md) extension and in the respective folder

**Comment by WajihaFatim** [comment]
@EkjotKaur please check

**Comment by WajihaFatim** [comment]
@EkjotKaur I have corrected can you now merge it

**Comment by WajihaFatim** [comment]
@EkjotKaur close the issue please

**Comment by WajihaFatim** [comment]
@EkjotKaur please close the issues so that I can assign myself new one
