### ISSUE TITLE
Front-end: List of HTML code Editors

### ISSUE THREAD

**Issue by rajmadhu0406** [girlscript/winter-of-contributing#262]
I would like to make a list of top HTML editors.

**Comment by LavleenAgrawal** [comment]
I want to make audio content on this, May I ?
Lavleen Agrawal (Batch 18 - Frontend)

**Comment by vatsss** [comment]
I would like to work on this issue via documentation, please consider me for this.

**Comment by khush2706** [comment]
I would like to contribute to this via documentation. I would make a list of top HTML editors along with their features. Please consider me for this..
Khushboo Chaturvedi
Batch-18

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation. I would make a list of top HTML editors along with their features. Please consider me for this..
Riya Pandey
Batch-2
