### ISSUE TITLE
MERN_NodeJs 5.2 How to use asynchronous APIs?

### ISSUE THREAD

**Issue by EkjotKaur** [girlscript/winter-of-contributing#2621]
# Instructions

## Project directory
`Branch MERN>Web_Development/MERN/Topic/Backend/Node/`

FileName: 4.1_How to use asynchronous APIs.md

## How to use asynchronous APIs??
Explain How to use asynchronous APIs?

# Task

- [ ]  Audio
- [ ]  Documentation
- [ ]  Video

## Send a PR in the following branch only and make documentation in form of markdown file with (.md) extension and in the respective folder

**Comment by aishapervin** [comment]
@EkjotKaur, i will just be working with the documentation part

**Comment by EkjotKaur** [comment]
> @EkjotKaur, i will just be working with the documentation part

Go head.
