### ISSUE TITLE
Java 13.3: Importing Packages

### ISSUE THREAD

**Issue by garvitraj** [girlscript/winter-of-contributing#2624]
### Description
 Add audio, documentation, and video regarding the **Importing Packages**.

 ### Location of File to be added
 The files should be added inside the `Importing Packages` folder which is inside the `Packages` folder present in the `Java` main folder. The documentation file can be in the `.md`/`.py`/`.ipynb` format. Audio should be in `.mp3` format and to be submitted through a Google drive link. Video can be in any format and should be submitted through a Google Drive link.
 **Note:**

 * You are required to comment with `\assign CONTENT_TYPE`, so that other content types can be created at the same time.
 * Failing to comment in the above manner will lead to the removal of assignment from the issue even if the bot assigns.
 * You are required to do a PR within 7 days otherwise you will be unassigned and others will be assigned.
 * Issues will be assigned on a first come first serve basis.

### Domain

Java_Domain

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by amitx007** [comment]
Sorry i have unsigned my self, i have commented by mistakely because of a confusion @garvitraj

**Comment by Harsh-Chaudhary7** [comment]
I have only one issue open and that to waiting to be merged.

**Comment by pragmatic-philosopher09** [comment]
\assign documentation

**Comment by RahulSoni0** [comment]
I was Assigned with 2 issues of same branch so both the issue got pushed with the same request . Kindly check the PR by your side . Thank you @garvitraj

**Comment by ganaaduvva** [comment]
@AkMo3 if the documentation issue is not resolved can I go with the issue

**Comment by AkMo3** [comment]
@ganaaduvva You have been assigned documentation

**Comment by ganaaduvva** [comment]
Thanks for your confirmation @AkMo3 !!

**Comment by ganaaduvva** [comment]
@AkMo3 can I go with the audio if not done yet!

**Comment by ganaaduvva** [comment]
@garvitraj  I have made the audio file can you review my PR

**Comment by ganaaduvva** [comment]
@AkMo3 can you please review my PR of audio it is my 1st audio contribution and happy to listen for any advice
