### ISSUE TITLE
[JAVA]: Final vs Finally vs Finalize in JAVA

### ISSUE THREAD

**Issue by sunidhii09** [girlscript/winter-of-contributing#2625]
### Description

A comparison between the Final, Finally and Finalize keywords.

### Domain

Java_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sunidhii09** [comment]
\assign documentation

**Comment by sunidhii09** [comment]
> /assign documentation

Hey! Can you please not take this issue, I have worked on this and created it for myself.

**Comment by amitx007** [comment]
okay sorry @sunidhii09

**Comment by sunidhii09** [comment]
Thanks! @amitx007
