### ISSUE TITLE
OpenSouce : 3.6 Overview of Google summer of code

### ISSUE THREAD

**Issue by priyanshuc4423** [girlscript/winter-of-contributing#263]

**Comment by priyanshuc4423** [comment]
@Aryamanz29  can I contribute to this

**Comment by Sakshi-1101** [comment]
Sir , can I contribute to this ?

**Comment by Aryamanz29** [comment]
> Sir , can I contribute to this ?

Can you create new issue for explaining everything about `MLH fellowship` @Sakshi-1101

**Comment by Aryamanz29** [comment]
I'll assign that to you

**Comment by Sakshi-1101** [comment]
Yes sir!

**Comment by mayankkuthar** [comment]
What is this 3.6 ??

**Comment by Aryamanz29** [comment]
> What is this 3.6 ??

Section 3 of the roadmap, You just ignore
