### ISSUE TITLE
Android-Java: 1.12 Dalvik-Virtual-Machine

### ISSUE THREAD

**Issue by Jonty512** [girlscript/winter-of-contributing#2630]
### Description

Android-Java: 1.12 Dalvik-Virtual-Machine

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Jonty512** [comment]
This was closed only because the issue was not assigned to me yea?

**Comment by VikasPandey121** [comment]
> This was closed only because the issue was not assigned to me yea?

We have already merged a PR on this issue.
