### ISSUE TITLE
C_CPP : The Spiral Matrix

### ISSUE THREAD

**Issue by shivam-iitk** [girlscript/winter-of-contributing#2632]
### Description

CODE for storing elements of any array in spiral matrix form and returning elements of any matrix in spiral order.

### Domain

C/CPP

### Type of Contribution

- [x] Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by monalsingh10** [comment]
/assign
Name: Monal Singh
Github profile link: https://github.com/monalsingh10
Which type of contribution you want to make:Documentation

**Comment by shivam-iitk** [comment]
Can you people work on some other issues @monalsingh10 @Anandkx007 . I am already assigned to this one.

**Comment by monalsingh10** [comment]
There is a two position documentation and video .@shivam-iitk  have'nt specified which part you are doing.

**Comment by shivam-iitk** [comment]
> There is a two position documentation and video .@shivam-iitk have'nt specified which part you are doing.

I will do both. Don't worry you may suggest changes when I am done with the issue.

**Comment by shivam-iitk** [comment]
I am already assigned to it so only my contribution will be counted anyways.

**Comment by monalsingh10** [comment]
Alright !! U have'nt mentioned specifically so I thought one might be not filled yet with the position.
U may carry on!!
