### ISSUE TITLE
bubble sort & insertion sort with complexities

### ISSUE THREAD

**Issue by VandanaKumari18** [girlscript/winter-of-contributing#2641]
### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by palsahabmalviyan** [comment]
Mam Please assign me this issue . I want work on document part.
