### ISSUE TITLE
Frontend: HTML LISTS

### ISSUE THREAD

**Issue by Pranshu321** [girlscript/winter-of-contributing#265]
I would Like to work on this via documentation form i will full explain every point with example and its different styles also.
like defining ordered and unordered list properly.

**Comment by samruddhikadam** [comment]
i would like to work on this via audio or video. please assign this to me.

**Comment by vatsss** [comment]
I would like to work on this issue via documentation, please assign this to me.

**Comment by cookieg13** [comment]
@praveenscience Hi sir! I would love to contribute on this topic, can you please assign it to me? Debarati Ghatak, Frontend Batch 5

**Comment by Mitali-13** [comment]
hi , i would like to work on this issue, please assign this to me.

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by khush2706** [comment]
I would like to contribute to this via documentation. I would make a well-structured document explaining every point in detail. Can you please assign it to me...
Khushboo Chaturvedi
Batch-18

**Comment by akj1608** [comment]
I would like to contribute to Can you please assign it to this topic and create Well formatted documentation. Can you please assign it to me?? 
Abhishek kumar  jha 
frontend batch 14

**Comment by Sreemoyee26** [comment]
@Pranshu321 hello sir, I would like to work in this issue can u please assign me this?
Frontend Batch 4

**Comment by charitha-byte** [comment]
i would like to work on this issue

**Comment by Pranshu321** [comment]
\assign
