### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular (2.2)-> What are Template Statements

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#2664]
### Description

- What are template statements?
- Syntax?
- When and How to use?
- Reference:- https://angular.io/guide/template-statements
(It's a week-2 issue )

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week2" directory
3. Tasks would be assigned on First Come First Serve Basis.

### Domain

Frontend Dev React/Angular/Vue

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anshii12** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by mukeshmjn** [comment]
@Anshii12 done! Go for it

**Comment by mukeshmjn** [comment]
@Anshii12 any updates?

**Comment by Anshii12** [comment]
Yes sir. I've completed half of the readme file. I'll be adding the PR by tomorrow.

**Comment by mukeshmjn** [comment]
ok @Anshii12
