### ISSUE TITLE
Quick notes/ Cheat Sheet -> Python

### ISSUE THREAD

**Issue by syedareehaquasar** [girlscript/winter-of-contributing#2667]
### Description

A crisp and concise revision sheet to refer to while preparing for the Interview!
-> DS Implementation
-> Inbuilt functions
-> Important concepts

### Domain

Interview Prep

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saketsagarsingh** [comment]
i want to work on this issue.
Saket Sagar
Batch-2
Documentation

**Comment by syedareehaquasar** [comment]
Right now vipula is assigned to this issue. You can work on a different issues or create a new one for a suitable contribution! @saketsagarsingh

**Comment by saketsagarsingh** [comment]
@syedareehaquasar if no one have update any issue I want to be assigned for this issue kindly assign this issue to me manually
Saket Sagar
Batch-2
Documentation

**Comment by vipula2001** [comment]
Hey @saketsagarsingh @syeedareehaquasar I am working on this

**Comment by syedareehaquasar** [comment]
@vipula2001 you can choose another medium (video or audio or contribute to @saketsagarsingh contribution... It was more than a month and pr should be created within 14 days of assigning the issue that is why I re-assigned. Hope you can understand.

**Comment by vipula2001** [comment]
Okayy

**Comment by saketsagarsingh** [comment]
@syedareehaquasar thank you for assigning I'll make a PR within 3-4 days

**Comment by Kanishk0412** [comment]
@syedareehaquasar Can I take this issue?

**Comment by syedareehaquasar** [comment]
Go ahead @Kanishk0412

**Comment by Kanishk0412** [comment]
I have opened a PR as well Please look into it https://github.com/girlscript/winter-of-contributing/pull/8556

**Comment by Kanishk0412** [comment]
Close this issue now !!
