### ISSUE TITLE
Quick notes/ Cheat Sheet -> C++

### ISSUE THREAD

**Issue by syedareehaquasar** [girlscript/winter-of-contributing#2668]
### Description

A crisp and concise revision sheet to refer to while preparing for the Interview!
-> DS Implementation
-> Inbuilt functions
-> Important concepts

### Domain

Interview Prep

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by syedareehaquasar** [comment]
@vishnu kindly close one of the 3 issues assigned to you or unassign to get this one assigned as others can work on this in the meanwhile!

**Comment by Kanishk0412** [comment]
Please assign this issue to me @syedareehaquasar.

**Comment by syedareehaquasar** [comment]
Please go ahead Kanishk!

**Comment by Kanishk0412** [comment]
Okay thanks

**Comment by Kanishk0412** [comment]
Close this issue now !!
