### ISSUE TITLE
Front-end: colors in CSS

### ISSUE THREAD

**Issue by Ravinayak07** [girlscript/winter-of-contributing#267]
- I would like to work on this issue and add  detailed documentation of <br>
 <strong><a href="#"> CSS Colors :- RGB, HEX, HSL</a> </strong>

- Please assign it to me.
- FRONTEND WITH HTML, CSS Batch-17(GWOC Contributor)

- Name : Ravi Shankar Nayak . 

- can you @praveenscience assign me this role?

**Comment by LavleenAgrawal** [comment]
I want to make audio content on this, May I ?
Lavleen Agrawal (Batch 18 - Frontend)

**Comment by kumaradityaraj** [comment]
### colors in CSS

- CSS Background Color
- CSS Text Color
- CSS Border Color
- CSS Color Values
- RGB, HEX, HSL

Please assign me this one .

**Comment by trip0le** [comment]
@praveenscience May I contribute on this topic?

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by vkaash-sharma** [comment]
I love to contribute to this issue I can give u well structure documentation..u can check my last project which have done last how i use css color on it.please assign this project to me..

https://vkaash-sharma.github.io/vikas-portfolio/

**Comment by suvangi2205** [comment]
Can I work on this issue?

**Comment by anushka-mishra-code** [comment]
I would be glad to work on this issue.
Name : Anushka Mishra
Batch : 1
Serial No.: 175
Type : Documentation
Approach:

Brief Introduction to HTML ,CSS, JavaScript
explaination of CSS in detail
major focus on colors in CSS
