### ISSUE TITLE
What is HTTP? 

### ISSUE THREAD

**Issue by Ayushi11-hue** [girlscript/winter-of-contributing#2674]
### Description

Hyper Text Transfer Protocol

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by dikshatakyar** [comment]
@code-reaper08 please assign this issue to me. I will be doing contribution via VIDEO. thanks.

**Comment by code-reaper08** [comment]
> @code-reaper08 please assign this issue to me. I will be doing contribution via VIDEO. thanks.

Done 🚀

**Comment by Ayushi11-hue** [comment]
@dikshatakyar /assign

**Comment by dikshatakyar** [comment]
@Ayushi11-hue  why did you close this issue ?

**Comment by dikshatakyar** [comment]
@Ayushi11-hue reopen this issue please, I am left to contribute in this topic via VIDEO.

**Comment by Ayushi11-hue** [comment]
Ok I have make a new issue for the same you can contribute there.. it's
same.. just find with the same name and assign it to yourself..

**Comment by dikshatakyar** [comment]
ok,but please don't close the new issue till i contribute there which is #3140  right ? @code-reaper08 , please look into this matter.

**Comment by Ayushi11-hue** [comment]
Yup I will not .. I have to that one because of some issue with the ID ..
just do this one it will be open.
Sorry for that!!!...
