### ISSUE TITLE
MERN_MongoDB: 4.1 Connecting application to local Database.

### ISSUE THREAD

**Issue by saloni-15** [girlscript/winter-of-contributing#2675]
## Connecting our application with a local database.
- Briefly explain all the steps for connecting nodejs application `app.js/server.js` to the local database using MongoDB.

## Project Directory
`Branch MERN>MERN/Topic/Backend/MongoDB/`

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sumitmukharjeeeeee** [comment]
Assign Me

**Comment by saloni-15** [comment]
use `/assign`
