### ISSUE TITLE
[Create New Issue]: Kadane's Algorithm

### ISSUE THREAD

**Issue by RakshitGupta621** [girlscript/winter-of-contributing#2688]
### Description

I want to contribute to the code of **Kadane's Algorithm**

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by msbuddhu** [comment]
\assign

**Comment by saketsagarsingh** [comment]
@RakshitGupta621 if no one is working on this issue I want it to be assigned to me
Saket Sagar
Batch-2
Documentation
please assign this to me if no one have updated anything yet

**Comment by RakshitGupta621** [comment]
> @RakshitGupta621 if no one is working on this issue I want it to be assigned to me
> Saket Sagar
> Batch-2
> Documentation
> please assign this to me if no one have updated anything yet

Someone has already written documentation for this. You can self assign to yourself.

Using /assign
