### ISSUE TITLE
Polymorphism in C++

### ISSUE THREAD

**Issue by sakshi168** [girlscript/winter-of-contributing#2694]
### Description

Describe Polymorphism and its types

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by achsahxavier** [comment]
@Suvraneel 
If this issue is open for audio contribution, please assign it to me.
Thank you.
