### ISSUE TITLE
MERN_Express: 1.0 Introduction to Express

### ISSUE THREAD

**Issue by hardikk2002** [girlscript/winter-of-contributing#2698]
### Minimum points to be covered.
- Introduction to Express
- Why do we need Express.js
- How it is useful to use in Nodejs

### Project Directory
```
Branch MERN>MERN/Topic/Backend/Express/
```
### Name of the File
```
1.0_Introduction_to_Express(D).md
```

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hardikk2002** [comment]
@SMD-1 Any updates?

**Comment by SMD-1** [comment]
I will submit it by tomorrow morning

**Comment by hardikk2002** [comment]
> I will submit it by tomorrow morning

Hey! that's awesome. Take your time.
Also, add one more point something like **prerequisites for getting started with express**.
