### ISSUE TITLE
OpenGL using C++

### ISSUE THREAD

**Issue by 1PRatgit** [girlscript/winter-of-contributing#2699]
### Description

Description: This document explains about OpenGL using C++.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as PR #3519 got merged
