### ISSUE TITLE
OpenSource : 2.2 Learn open source basics

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#27]
### Description :

- `Learn open source basics 👇`

    - Every work has the best practices and standards which were
initiated by experienced people and followed by many in order to
maintain the quality of work. It applies to open source as well. It is
better to go through things like **best practices for commit
messages, semantic versioning, open-source licenses, contribution
guidelines, and the code of conduct for open-source projects**.

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by nayakaj** [comment]
Can I be assigned this issue?

**Comment by nayakaj** [comment]
how to start @Aryamanz29

**Comment by Aryamanz29** [comment]
@nayakaj  Any updates on this?

**Comment by siddhi-244** [comment]
Can I try it

**Comment by nayakaj** [comment]
@Aryamanz29  i submit by today

**Comment by nayakaj** [comment]
@Aryamanz29
![WhatsApp Image 2021-09-17 at 20 24 06](https://user-images.githubusercontent.com/80377839/133803922-2e55b9b3-0c05-4403-8056-5d796841cd1f.jpeg)
plz look into this when im pushing it it is asking git password and username

**Comment by nayakaj** [comment]
@Aryamanz29  completed

**Comment by nayakaj** [comment]
@Aryamanz29 plz check

**Comment by Aryamanz29** [comment]
> @Aryamanz29 plz check

Complete requested changes

**Comment by mayankkuthar** [comment]
If No one is working on this issue, I would like to work on it, Please Assign it to me.

**Comment by Aryamanz29** [comment]
@mayankkuthar  Sure
