### ISSUE TITLE
C_CPP : C++14 vs C++17

### ISSUE THREAD

**Issue by areenoverclouds** [girlscript/winter-of-contributing#2711]
### Description

I would like to provide the documentation of a comparison between C++14 and C++17.

Domain of contribution: C/CPP
Format: Documentation
Language: C++

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by areenoverclouds** [comment]
Please assign me this issue.

**Comment by Saviour1001** [comment]
Closing as the PR got merged
