### ISSUE TITLE
Two Way Data Binding in React

### ISSUE THREAD

**Issue by trip0le** [girlscript/winter-of-contributing#2724]
### Description

Is two way data binding really applicable in React? Explain.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by trip0le** [comment]
@anandhu720 Sir, is it alright if I work on this issue ?

**Comment by anandhu720** [comment]
we have told you please dont create issue by yourself
