### ISSUE TITLE
Singly Linked list in C

### ISSUE THREAD

**Issue by Akriti-Choudhary** [girlscript/winter-of-contributing#2735]
### Description

Documentation on the singly linked list in C.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged.
