### ISSUE TITLE
Android-Kotlin: 00.1 Contributing Guideline

### ISSUE THREAD

**Issue by rahulsain** [girlscript/winter-of-contributing#275]
Make a CONTRIBUTING.md that has the same rules that are shared on the announcement section **Workflow.docx**

**Comment by atishay5203** [comment]
Sir, i will like to work on this.

**Comment by yuvraj-2503** [comment]
I would like to work on this issue.

**Comment by sitamadex11** [comment]
@yuvraj-2503 Any update regarding your work?

**Comment by yuvraj-2503** [comment]
I have already made the PR and its merged also.
