### ISSUE TITLE
[Transition and Transformation in CSS]: 

### ISSUE THREAD

**Issue by Aditi-247** [girlscript/winter-of-contributing#2756]
[Path name-](https://github.com/girlscript/winter-of-contributing/tree/Frontend_Web_Development_HTML_CSS_JS/Web_Development/FrontEnd)

**Transform property** in CSS is invoked when there is a change in the state of the HTML element. You can rotate, skew, move and scale elements. It occurs when the state of an element is modified, like when you hover the mouse over a button or perform a mouse-click.
**Translate property** changes the position left/right and up/down of the element on the page based on the given X (horizontal) and Y (vertical) axes parameters. 

I am a GWOC'21 contributor from **Batch 1 of Frontend with HTML, CSS, JS.**
Please assign this issue to me. I assure you that this issue's title will be the same as my PR's title as well as I will be Contributing under the Guidelines and Code of Conduct.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ganaaduvva** [comment]
@Aditi-247   To assigning the issue, you need to comment then the bot will automatically gives you with this task

**Comment by iamsunil25** [comment]
@praveenscience can you assign this issue to me?
