### ISSUE TITLE
ML 2.1 : What is Learning? Why Machine Learning works? (A)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#2775]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **What is Learning? Why Machine Learning works?**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Audio** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Machine Learning
Batch-6
Issue Number-2775
Type-Audio                                                                                                                                                      
Contribution Approaches-what is learning & ml, importance of data in ml, how machine learns from data,

**Comment by ron352** [comment]
Sarmistha Sarna
Batch :01
https://github.com/ron352
type : audio

@abhisheks008  can I work on this?

**Comment by geeythree** [comment]
@ron352 Definitely!
