### ISSUE TITLE
ML 2.1 : What is Learning? Why Machine Learning works? (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#2776]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **What is Learning? Why Machine Learning works?**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Video** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do video on this issue.

**Comment by ashish-reddy-20-08** [comment]
@geeythree @abhisheks008 , Can you kindly assign me this work.
M.Ashish Reddy
Batch-2

**Comment by abhisheks008** [comment]
@ashish-reddy-20-08 Issue assigned. Go ahead 🚀

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , thank you so much sir.

**Comment by ashish-reddy-20-08** [comment]
@geeythree @abhisheks008 @Isha307 , can you please evaluate my PR.
Link : https://github.com/girlscript/winter-of-contributing/pull/3083
M. Ashish Reddy
ML -> Batch -2
