### ISSUE TITLE
ML 2.9 : Decision Trees Algorithm (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2777]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Decision Trees Algorithm_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy, I would like to work on this issue. 
Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
contribution you want to make : Documentation

**Comment by ron352** [comment]
Sarmistha Sarna
Git :@ron352
Type :documentatio
/assign

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , Sir it was said not to use "/assign sir " please look into this

**Comment by TishaJhabak1014** [comment]
@abhisheks008 sir, who is gonna take this up? Look two of us have been assigned.

**Comment by TishaJhabak1014** [comment]
@abhisheks008 sir, let me know so that I can look up to different issues. But, plz giving this issue to me would love to work on it.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation
/assign

**Comment by geeythree** [comment]
The person to have commented first would get the issue. Therefore, it has been assigned to @khushali452. Please complete the work and make a PR within three days. 😄

**Comment by khushali452** [comment]
Gotcha ! @geeythree
