### ISSUE TITLE
Android-Java : 11.0 Android Sensor Tutorial

### ISSUE THREAD

**Issue by Srijan221** [girlscript/winter-of-contributing#278]
This issue will have - 
1. Overview of using mobile sensors in an app
2. Use of motion sensors like Accelerometer, Gravity, Gyroscope, Step Counter, etc
3. Use of position sensors like Proximity Sensor
4. Making and integrating a simple app with some onboarding sensors of mobile phones.

**Comment by Srijan221** [comment]
@Rohit-2602 I want to work in this, Can I?

**Comment by Srijan221** [comment]
@Rohit-2602 I want to work in this, Can I?

**Comment by Rohit-2602** [comment]
yes @Srijan221 you can work on this

**Comment by Rohit-2602** [comment]
@Srijan221  can you please give a progress update about the issue and if you are facing any problem feel free to ask.
