### ISSUE TITLE
ML 2.5: Linear Regression (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2780]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Linear Regression**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Video** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do documentation on this issue.

**Comment by Yugal41735** [comment]
Yugal Agarwal, Batch-2,  link => https://github.com/Yugal41735, documnetation

**Comment by Isha307** [comment]
@TishaJhabak1014 you are already working in 3 issues which is assigned to you.

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

**Comment by TishaJhabak1014** [comment]
@Isha307  mam there's a confusion, got assigned to a common issue, let mentor confirm who is gonna take up.

**Comment by purvanshgarg** [comment]
I think the first one gets it

**Comment by abhisheks008** [comment]
Follow the guidelines and then comment out here as per the guidelines, then only you'll be assigned to this issue. `/assign` tag is not gonna help you 👎

**Comment by ayushi424** [comment]
Name: Ayushi Shrivastava
Batch no.  
github: https://github.com/ayushi424

contribution for: Documentation

Approach: proper code along with explanation via project.
@abhisheks008 Kindly assign :)

**Comment by abhisheks008** [comment]
> Name: Ayushi Shrivastava
> Batch no. 1
> github: https://github.com/ayushi424
> 
> contribution for: Documentation
> 
> Approach: proper code along with explanation via project.
> @abhisheks008 Kindly assign :)

One issue at a time @ayushi424

**Comment by abhisheks008** [comment]
@TishaJhabak1014 Issue assigned, complete this issue by this wednesday.

**Comment by ahmedtarek26** [comment]
I want to take this issue.
Ahmed Tarek
ML-batch-1
https://github.com/ahmedtarek26
Video
