### ISSUE TITLE
ML 2.2 Contrast between Regression and Classification (A)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#2781]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Contrast between Regression and Classification**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Audio** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Machine Learning
Batch-6
Issue Number-                 
Type-Audio                                                                                                                                     
Contribution Approaches-types of data, approaches, algorithms used, data preprocessings

**Comment by ashish-reddy-20-08** [comment]
Hello @geeythree @abhisheks008 , 
can you assign me this issue
M.Ashish Reddy
batch-2

**Comment by abhisheks008** [comment]
Sorry @ashish-reddy-20-08 as @BhaswatiRoy has already commented in it, it'll be assigned to @BhaswatiRoy.

@BhaswatiRoy Issue assigned to you, go ahead and complete this by Wednesday 🎉

**Comment by BhaswatiRoy** [comment]
> Sorry @ashish-reddy-20-08 as @BhaswatiRoy has already commented in it, it'll be assigned to @BhaswatiRoy.
> 
> @BhaswatiRoy Issue assigned to you, go ahead and complete this by Wednesday 🎉

Sure thanks!
