### ISSUE TITLE
ML 2.5: Linear Regression (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2782]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Linear Regression**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Video** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy, I would like to work on this issue. 
Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
contribution you want to make : video

**Comment by abhisheks008** [comment]
@ashish-reddy-20-08 one issue at a time.

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , sir i have already started working on this and will submit by today evening sir.

**Comment by abhisheks008** [comment]
@ashish-reddy-20-08 Do it, but this will not count. This issue is not even assigned to you.

**Comment by ashish-reddy-20-08** [comment]
@Isha307 @abhisheks008 , I have completed my first issue which is assigned to me.

PR link of my first issue  : https://github.com/girlscript/winter-of-contributing/pull/2818

can you please assign me this issue now.

**Comment by ashish-reddy-20-08** [comment]
@Isha307 , KIndly assign this to me as i have done the first issue PR also.

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , Sir i have completed the first issue and made PR ALSO SIR 
CAN u please assign me sir

**Comment by abhisheks008** [comment]
Now you can work on it. Issue assigned @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@Isha307 @abhisheks008 , Kindly evaluate my PR.
PR link: https://github.com/girlscript/winter-of-contributing/pull/2863
Name: M. Ashish Reddy
Batch - 2
