### ISSUE TITLE
ML 2.2 : Contrast between Regression and Classification (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#2786]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Contrast between Regression and Classification**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Video** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by geeythree** [comment]
@tanvideshmukh29 This issue is only for video content

**Comment by Sumit3301** [comment]
/assign
name- Sumit Gaur
Batch-3
github-https://github.com/Sumit3301
contribution type- Video

**Comment by abhisheks008** [comment]
Issue assigned @Sumit3301. But do not use /assign tag in future, otherwise we'll unassign you.

**Comment by Sumit3301** [comment]
okay, sir ill keep that in mind from next time.

**Comment by Isha307** [comment]
@Sumit3301 Any Update?

**Comment by Sumit3301** [comment]
@Isha307  will be making a PR today.

**Comment by Sumit3301** [comment]
@Isha307 can I upload the video on youtube and make PR by adding file in .md file??

**Comment by geeythree** [comment]
@Sumit3301 GWOC team has mentioned that videos have to be uploaded on google drive only.
