### ISSUE TITLE
ML 2.10 : Support Vector Machines (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2789]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Support Vector Machines_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do documentation on this issue.

**Comment by abhisheks008** [comment]
Follow the guidelines and then comment out here as per the guidelines, then only you'll be assigned to this issue. `/assign` tag is not gonna help you 👎

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
[Profile link](https://github.com/priyall)
Contribution type: Documentation
/assign

**Comment by abhisheks008** [comment]
@priyall Issue assigned, complete this by this wednesday.

**Comment by monalsingh10** [comment]
Sir thought that is the way of assigning.Will you reassign please??
