### ISSUE TITLE
ML 2.10 : Support Vector Machines (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2792]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Support Vector Machines_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do video on this issue.

**Comment by geeythree** [comment]
@deepthi1107 you seem to have more than three issues open currently

**Comment by silicolicious** [comment]
Full Name: Mageshkrishna R 
Batch No.: ML Batch 4
Github Profile: https://github.com/silicolicious 
Discord Username: Mag#2191
Type of Contribution: Video

This would be my first issue in Machine Learning.
Assign it to me.

Thank you.

**Comment by geeythree** [comment]
@silicolicious The issue has been assigned to you. Please work on it and make a PR within 3 days. Happy contributing! 😄

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do video on this issue.

**Comment by samridhikapoor** [comment]
I would like to contribute for this issue. I request you to assign me the same.
Thanks

Name: Samridhi Kapoor
Batch No.: 3
Github Profile link: https://github.com/samridhikapoor
Type of contribution I want to make: Video (as specified)

**Comment by das-ankur** [comment]
I would like to contribute for this issue. I request you to assign me the same.
Thanks

Name : Ankur Das
Batch No. : 2
Github: https://github.com/das-ankur
Type of contribution : Document/Video

**Comment by Isha307** [comment]
@deepthi1107 you can now work on this.
