### ISSUE TITLE
ML 2.4 : Pandas Cheatsheet: Most Useful Functions and Methods (D)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#2793]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Pandas Cheatsheet: Most Useful Functions and Methods (D)**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Documentation** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

**Comment by TishaJhabak1014** [comment]
Name Tisha Jhabak
Batch 6
https://github.com/TishaJhabak1014
Interested

**Comment by geeythree** [comment]
@hrugved06 The issue has been assigned to you. Please complete it and make a PR within 3 days. Happy contributing! 😄

**Comment by hrugved06** [comment]
> @hrugved06 The issue has been assigned to you. Please complete it and make a PR within 3 days. Happy contributing! 😄

Sure

**Comment by abhisheks008** [comment]
@hrugved06 If you spam like these, then no issue will be assigned to you. Be careful buddy 👎

**Comment by hrugved06** [comment]
@abhisheks008 what happened?
I am working on the issue

**Comment by hrugved06** [comment]
> @hrugved06 If you spam like these, then no issue will be assigned to you. Be careful buddy 👎

Don't unassign issues which we have started working on

**Comment by Tirth-AI** [comment]
Tirth B Dalwadi
Batch 6
https://github.com/Tirth-AI
Documentation

**Comment by abhisheks008** [comment]
> > @hrugved06 If you spam like these, then no issue will be assigned to you. Be careful buddy 👎
> 
> Don't unassign issues which we have started working on

Stop spamming like those, the issue you have assigned just do that, if you not wanna do that, tell us we'll unassign you. If you can comment out in every issue using /assign, then we can also unassign issues at our own will. Stop making spams.

**Comment by abhisheks008** [comment]
@Tirth-AI issue assigned, complete it by this wednesday.

**Comment by Meet-011** [comment]
Name : Meet Panchal (Meet)
Batch : 8
https://github.com/Meet-011
Interested

**Comment by geeythree** [comment]
@Meet-011 This issue has already been assigned to another contributor

**Comment by ahmedtarek26** [comment]
I want to take this issue.
Ahmed Tarek
Batch :1
https://github.com/ahmedtarek26
interested
