### ISSUE TITLE
ML 2.6: Logistic Regression (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2795]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Logistic Regression**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Documentation** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by TishaJhabak1014** [comment]
https://github.com/TishaJhabak1014
Name Tisha Jhabak
Btach 6
Interested

**Comment by Isha307** [comment]
@TishaJhabak1014 @ron352 you both are already working in 3 issues, so complete that first.

**Comment by ron352** [comment]
@Isha307 no mam..I have been unassigned in previous issues though I commented first :/ currently I have got assigned in issue #2778

**Comment by priyall** [comment]
@Isha307 Can I be assigned to this issue..

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 @ron352 you both are already working in 3 issues, so complete that first.

@Isha307 No mam, Not assigned to any issues currently. Rest all are approved.

**Comment by tanvideshmukh29** [comment]
/assign
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation
plz assign it to me.

**Comment by abhisheks008** [comment]
@tanvideshmukh29 issue assigned, complete this by this wednesday.
