### ISSUE TITLE
ML 2.11 : Naive Bayes Algorithms (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2796]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Naive Bayes Algorithms_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy, I would like to work on this issue. 
Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
contribution you want to make : Documentation

**Comment by Yugal41735** [comment]
Yugal Agarwal, Batch-1, link => https://github.com/Yugal41735, documnetation

**Comment by geeythree** [comment]
@purvanshgarg I'm assigning this issue to @Yugal41735. Please complete the issue and make a PR  within 3 days! 😄

**Comment by tanvideshmukh29** [comment]
/assign
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by Yugal41735** [comment]
@abhisheks008  I tried to clone the repo, but after cloning the folder that created is empty and even tried to switch branch but still no luck it is showing some errors, so please look into it.

**Comment by CodingForTheBetter** [comment]
Full name -> Tanush Vijayakumar Savadi
Batch Number -> 4
GitHub Profile Link -> https://github.com/CodingForTheBetter
Which type of Contribution you want to make: Documentation

Please assign this to me if not assigned already. Thank you.
