### ISSUE TITLE
ML 2.11 : Naive Bayes Algorithms (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2798]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Naive Bayes Algorithms_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy, I would like to work on this issue. 
Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
contribution you want to make : video

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do video on this issue.

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , Sir how come you didn't assign me , and assigned deepthi ???

**Comment by ashish-reddy-20-08** [comment]
@Isha307 , Mam whats this mam , I have completed all my issues and made PR , and first commented here.

**Comment by ashish-reddy-20-08** [comment]
How did you give to someone else ignoring the first come first serve policy which is said by you. @Isha307 @abhisheks008

**Comment by Isha307** [comment]
But that time you were working on one issue, that's why.
@ashish-reddy-20-08 you can look into the other issues.

**Comment by ashish-reddy-20-08** [comment]
@Isha307 , This is totally unfair , I have created My PR at and tagged you before messaging over here , You can cross check it, 
from my side i have made the PR and after that , if its delayed from the team end how is that going to affect me. 
I have made PR, and then i have commented here. If evaluation was late that doesn't mean i have to wait till the evaluation is done , BEcause there might be only small issues after making PR.

So i believe i should get this work assigned.
