### ISSUE TITLE
Frontend Web Development Using React: JSX

### ISSUE THREAD

**Issue by Saurabh-crypto16** [girlscript/winter-of-contributing#280]
I have seen the roadmap given and I would like to contribute to the documentation of JSX  in Frontend Web Development using React.

Topics to be covered:
1. What is JSX?
2. Syntax of JSX.
3. Why use JSX.
4. Comparing JSX with JS and HTML
5. How to Embed Expressions in JSX
6. JSX as an Expression.
7. How to Specify Attributes with JSX.
8. How to Specify Children with JSX
9. How JSX Represents Objects.

Language: English
Frontend Web Development React Angular Vue Batch-2 (GWOC Contributor)

**Comment by Baalamurgan** [comment]
I am interested in this topic. Batch-6-frontend-framework
