### ISSUE TITLE
ML 2.13 : Implement Naive Bayes without using any standard ML library like scikit-learn or more. (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2803]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Implement Naive Bayes without using any standard ML library like scikit-learn or more_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
-  Dataset to be used : **IRIS DATASET**. (No other datasets will be entertained.)

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Coding in .ipynb file, show the implementation)
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

**Comment by abhisheks008** [comment]
@hrugved06 Complete this issue by this wednesday, if you not gonna work on it, then tell me I'll unassign you.

**Comment by hrugved06** [comment]
> @hrugved06 Complete this issue by this wednesday, if you not gonna work on it, then tell me I'll unassign you.

Sure

**Comment by abhisheks008** [comment]
Then complete this one, without further spamming.
