### ISSUE TITLE
ML 2.7: Contrast between Linear and Logistic Regression (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2804]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Contrast between Linear and Logistic Regression**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Audio** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AdityaNikhil** [comment]
**Full name** : Aditya Nikhil
**Batch Number**: 2
**GitHub Profile Link** : github.com/adityanikhil
**Which type of Contribution you want to make** :
video

**Comment by Aaksha-sharma** [comment]
I want to contribute through audio

**Comment by abhisheks008** [comment]
Great issue assigned to @Aaksha-sharma. Go ahead 🚀

**Comment by abhisheks008** [comment]
Any update? @Aaksha-sharma

**Comment by Aaksha-sharma** [comment]
yes I will make PR today my hard drive crashed I am sorry for delay.

**Comment by Aaksha-sharma** [comment]
@abhisheks008 I have made PR please look into it. Let me know in case of any changes.
Link - https://github.com/girlscript/winter-of-contributing/pull/3867

**Comment by Aaksha-sharma** [comment]
I have done the requested changes @abhisheks008 please see to it. 
link- https://github.com/girlscript/winter-of-contributing/pull/3867
