### ISSUE TITLE
ML 2.14 : Implement Support Vector Machine without using any standard ML library like scikit-learn or more. (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2806]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Implement Support Vector Machine without using any standard ML library like scikit-learn or more_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
-  Dataset to be used : **IRIS DATASET**. (No other datasets will be entertained.)

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Coding in .ipynb file, show the implementation)
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

I'd like to work on this

**Comment by hrugved06** [comment]
@Isha307 
I can work on the issue pls do assign
/assign

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by abhisheks008** [comment]
@tanvideshmukh29  If you spam like these, then no issue will be assigned to you. Be careful buddy 👎

**Comment by tanvideshmukh29** [comment]
Sry for it.
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation
/assign

**Comment by tanvideshmukh29** [comment]
Sry for it.
Full name :Tanvi Deshmukh
Batch Number:5
GitHub Profile Link:https://github.com/tanvideshmukh29
Which type of Contribution you want to make :
 Documentation

**Comment by abhisheks008** [comment]
@tanvideshmukh29 One issue at a time.

**Comment by Shreya18031997** [comment]
Full name : Shreya Kumari
Batch Number:5
GitHub Profile Link:https://github.com/ishreyakumari
Which type of Contribution you want to make :
Documentation

**Comment by abhisheks008** [comment]
@Shreya18031997 issue assigned, complete this by this wednesday.

**Comment by ishreyakumari** [comment]
Can I work on this issue?
Full name : Shreya Kumari
Batch Number: 5
GitHub Profile Link: https://github.com/ishreyakumari
Which type of Contribution you want to make :
Documentation
@abhisheks008 Sorry by mistake i commented using wrong github. This is my correct github. Can you please assign it on this github. Sorry for inconvenience caused. I will complete this till wednesday.

**Comment by ishreyakumari** [comment]
> @ishreyakumari issue assigned, complete this by this wednesday.

Sure. Thank you :)

**Comment by Isha307** [comment]
@ishreyakumari Any Update?

**Comment by ishreyakumari** [comment]
> @ishreyakumari Any Update?

@Isha307 Its almost completed. I will create pull request today. Sorry for delay.
