### ISSUE TITLE
ML 2.7: Contrast between Linear and Logistic Regression (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2808]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Contrast between Linear and Logistic Regression**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Documentation** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purvanshgarg** [comment]
Purvansh Garg
Batch no 2
Documentation

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

Can I work on this?

**Comment by purvanshgarg** [comment]
There is a lot of confusion, the bot is assigning the issue to more than one contributors

**Comment by purvanshgarg** [comment]
I think the collaborators will sort this out in some time

**Comment by Isha307** [comment]
@hrugved06 @purvanshgarg You both had been assigned one issue, so work on that first.

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by ayushi424** [comment]
Full name: Ayushi Shrivastava
Batch Number: 1
GitHub Profile Link: https://github.com/ayushi424
Which type of Contribution you want to make :
 Documentation
@Isha307 Please look :)

**Comment by abhisheks008** [comment]
@ayushi424 Issue assigned. Complete this by Wednesday.
