### ISSUE TITLE
ML 2.8: K-Nearest Neighbour Algorithm (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#2811]
### Description

Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **K-Nearest Neighbour**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", this issue is only for **Documentation** content.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

/assign

**Comment by TishaJhabak1014** [comment]
Name Tisha Jhabak
Batch 6
https://github.com/TishaJhabak1014
Interested

**Comment by Yugal41735** [comment]
Yugal Agarwal, Batch-1, link => https://github.com/Yugal41735, documnetation

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
Contribution type: Documentation
/assign

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation
/assign

**Comment by tanvideshmukh29** [comment]
Full name :Tanvi Deshmukh
Batch Number:5
GitHub Profile Link:https://github.com/tanvideshmukh29
Which type of Contribution you want to make :
Documentation

**Comment by abhisheks008** [comment]
@everyone One issue at a time. You guys have already assigned one issue, complete that first.

**Comment by monalsingh10** [comment]
Name:Monal Singh
Batch no.:5
Github profile link: https://github.com/monalsingh10
Which type of contribution you want to make: Documentation

**Comment by monalsingh10** [comment]
Mentors this my first contribution!!So please assign me this!

**Comment by abhisheks008** [comment]
@monalsingh10 Issue assigned, complete this issue by this Wednesday.

**Comment by monalsingh10** [comment]
@abhisheks008 sir can you please give me tomorrows due date .Due to network issue I am not able to send PR .Please its an request.
