### ISSUE TITLE
Graph in c++: Topological Sorting  

### ISSUE THREAD

**Issue by shreya024** [girlscript/winter-of-contributing#2813]
### Description

Documentation and code on Topological Sort in Graph.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR #4088 got merged
