### ISSUE TITLE
C_CPP : Virtual Functions, Friend Functions & Friend Classes (Documentation)

### ISSUE THREAD

**Issue by amankumar11** [girlscript/winter-of-contributing#2816]
### Description

 Virtual Functions, Friend Functions & Friend Classes in CPP (Documentation)

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR is merged
