### ISSUE TITLE
JS: Promises in JavaScript - Video

### ISSUE THREAD

**Issue by husain3012** [girlscript/winter-of-contributing#282]
## Directory
```
Topics/Promises
```
The index will be added manually after merging.

## Description
- Explain the concept of promises.
- Why do we need them?
- How to handle returned promises.
- What different types of promises can be returned?

**Comment by husain3012** [comment]
@paramsiddharth Kindly label this issue, and I would like to work on it.

**Comment by 2devyank** [comment]
@paramsiddharth sir I would like to try this issue

**Comment by Koustav-1250** [comment]
I would like to work on this issue. Can you this issue to me as well.

**Comment by 2devyank** [comment]
@paramsiddharth  sir I have made the pull request please check
