### ISSUE TITLE
 Object Oriented Programming - Encapsulation

### ISSUE THREAD

**Issue by jyotsana279** [girlscript/winter-of-contributing#2830]
### Description

The concepts of Object Oriented Programming will be discussed keeping Encapsulation as the main topic.

### Domain

Java_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by tamalbag117** [comment]
\assign Document

**Comment by lakshya7878** [comment]
\assign  Audio
