### ISSUE TITLE
Opensource: 2.5  Resources to find good First Issues for your first open-source contribution

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#2837]
### Description :

**You may write some resources or give references of 
websites and explaining best practices how to contribute to beginner issues in projects**

Maybe someone like is you also looking for that kind of solution, Do
you like to help someone?😉 You can explain about good first issues and how to find issues in big repositories so developers who've never contributed to open-source can get started quickly.

#Note
- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HassanRahim26** [comment]
Hey @Muskan-creator, I would like to work on this issue. Can you please assign me this?
Name: Hassan Rahim
Batch: Open-Source Batch-1
Type: Documentation

**Comment by Aryamanz29** [comment]
@HassanRahim26  Assigned, Happy docs 🎉🎉

**Comment by PrachiDoshi2170** [comment]
Hello @Muskan-creator and @Aryamanz29 Can i work on this issue for documentation?

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170  Sure. Assigning this to you

**Comment by VandanaKumari18** [comment]
/assign 
Can i work on this issue ??

**Comment by ishikajn8126** [comment]
@Aryamanz29 @Muskan-creator  since this issue has been inactive for quite some days. Can I work on it?

I'll add :
- resources where contributors can find links to good first issues 
- resources for best practices while contributing in open source
- some self-written content from my experience

Type: Documentation

**Comment by PrachiDoshi2170** [comment]
Ishika I am almost done documenting this stuff I will upload it today
