### ISSUE TITLE
[Create New Issue]: Casting Operators

### ISSUE THREAD

**Issue by Eswari-Priya** [girlscript/winter-of-contributing#2839]
### Description

I'd like to describe all the casting operators that are present in cpp.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as #2922 got merged !
