### ISSUE TITLE
OpenSource : 3.9 Overview of Red Hat Open Source Contest

### ISSUE THREAD

**Issue by ELLIPSIS009** [girlscript/winter-of-contributing#284]
@Aryamanz29 can i contribute to this

**Comment by Aryamanz29** [comment]
@ELLIPSIS009  Sure, I'll assign this to you, Happy Documenting 🎉🎉

**Comment by Aryamanz29** [comment]
Please note that @ELLIPSIS009  commit and File name should have the same name ie. `OpenSource : 3.9 Overview of Red Hat Open Source`

**Comment by ELLIPSIS009** [comment]
Okay, Got it

**Comment by saketsagarsingh** [comment]
Saket Sagar 118- May I have the honour of working on this issue?
