### ISSUE TITLE
OpenSource : 4. Participating in Open Source Communities

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#285]
its include:

  1. What does it mean for an organization to contribute?
  2 .How did contributions work?
  3 . How open-source projects are managed?

Please note that: @LegendSumeet
- File `name, commit message and PR title` should be the same
- Doc should be less `text-heavy` , try to explain things with `gif, images, graphs` etc

@Aryamanz29

**Comment by Aryamanz29** [comment]
Assigning this to you @LegendSumeet , Happy Documenting 🎉🎉

**Comment by Aryamanz29** [comment]
@LegendSumeet  Any updates ??

**Comment by LegendSumeet** [comment]
Yes just today evening it will be done and ready to merge @Aryamanz29
