### ISSUE TITLE
/assign

### ISSUE THREAD

**Issue by ayush572** [girlscript/winter-of-contributing#2866]
### Description

I would like to work with this issue.

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saloni-15** [comment]
hey @ayush572  you have done some mistake, please check this and close this issue

**Comment by v-rohan** [comment]
Hey @ayush572, Kindly close this issue. You've made a basic error. Kindly got to any pre-existing issue, and assign to yourself by commenting /assign on it.

**Comment by ayush572** [comment]
How do I close the issue?
Actually i thought that, until someone completes an issue, anyone can take any issue...

Also, umm... most of the issues have been taken, that's why..., I assigned it.

Plz lemme know the command to unassign an issue

**Comment by saloni-15** [comment]
@ayush572 go the end of this conversation, there you will get an option for `Close Issue`

![image](https://user-images.githubusercontent.com/75828760/134843308-14117a48-55f6-4945-8bcf-399d063fa886.png)

**Comment by ayush572** [comment]
okay, closed the issue...
