### ISSUE TITLE
Rearrange the order of content in front end with html, css branch.

### ISSUE THREAD

**Issue by RoshanMhatre** [girlscript/winter-of-contributing#2868]
### Description

Some HTML concepts are in between CSS and some basic web concepts are placed in between in other concepts.
Rearrange them would make it look clean and easy to  search

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RoshanMhatre** [comment]
Moderator assing this issue to me so I can rearrange everything in order.

**Comment by PrachiDoshi2170** [comment]
@RoshanMhatre can I be assigned this issue for the documentations?

**Comment by PrachiDoshi2170** [comment]
@RoshanMhatre can I be assigned this issue for the documentations?

**Comment by jay-498** [comment]
please assign this issue for the documentations i will arrange them neatly ! @RoshanMhatre

**Comment by RoshanMhatre** [comment]
@PrachiDoshi2170  and @jay-498, maybe you can add some other feature and fix some other thing.

**Comment by RoshanMhatre** [comment]
Please add the Hacktoberfest label to it if it's valid.
