### ISSUE TITLE
OpenSource : 4.1 Explain everything related to the `MLH fellowship`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#287]
### Description :

- **Explain everything related to the fellowship**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- Doc name should same as the `issue title  `

## Happy Contributing 🙌

**Comment by mayankkuthar** [comment]
Can I work on this?

**Comment by siddhi-244** [comment]
Can I work on this !

**Comment by Aryamanz29** [comment]
> Can I work on this?

Sure @mayankkuthar , Assigning this to you, Happy Documenting 🎉🎉

**Comment by Aryamanz29** [comment]
> Can I work on this !

Creating more issues wait 😂

**Comment by Aryamanz29** [comment]
@siddhi-244  Till then complete your assigned ones

**Comment by siddhi-244** [comment]
> @siddhi-244 Till then complete your assigned ones

1 is done.😅

**Comment by Soumili1818** [comment]
Can I have the honour of handling this PR, please?
