### ISSUE TITLE
OpenSource : 4.2 Explain everything related to the `Fossasia Codeheat`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#288]
### Description :

- **Explain everything related to the Fossasia Codeheat**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- Doc name should same as the `issue title  `

## Happy Contributing 🙌

**Comment by siddhi-244** [comment]
Can I  try?

**Comment by Purvibhoyar** [comment]
Hello supervisors and mentors 
I am from Open source batch 1
Please assign me this issue 
I will try this out.
Thank you

**Comment by Aryamanz29** [comment]
@Purvibhoyar  Assigning this to you, Happy Documenting 🎉🎉🎉

**Comment by Purvibhoyar** [comment]
Yes, Thank you 
Can we add documentation +audio /documentation +video format?
Or strictly either of  three.

**Comment by Aryamanz29** [comment]
> Yes, Thank you @Aryamanz29
> Can we add documentation +audio /documentation +video format?
> Or strictly either of three.

@Purvibhoyar  You can contribute to anyone format, Read [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by siddhi-244** [comment]
Can I try this ?

**Comment by Aryamanz29** [comment]
@Aryamanz29 Already Assigned to @Purvibhoyar , Please check before commenting

**Comment by Aryamanz29** [comment]
@Purvibhoyar  Any updates ? Please submit PR by today

**Comment by Purvibhoyar** [comment]
@Aryamanz29 Yes , Progress is on the way
I will be submitting by today or mostly by tomorrow for Sure.

**Comment by Purvibhoyar** [comment]
@Aryamanz29  Hey
I have made a PR to my submission 3-4 hours back.
Please check and let me know if it is covering everything or not

**Comment by Aryamanz29** [comment]
@Purvibhoyar  Please link PR to this issue, I can't find your PR

**Comment by Purvibhoyar** [comment]
@Aryamanz29 HAVE YOU GOT IT?

**Comment by Aryamanz29** [comment]
@Purvibhoyar  Linked your PR to this issue

**Comment by mayankkuthar** [comment]
@Aryamanz29 If anyone is not working on this issue, please assign it to me. I would love to work on this one.
