### ISSUE TITLE
Modular Arithmetic in C++

### ISSUE THREAD

**Issue by kaustubh0777** [girlscript/winter-of-contributing#2889]
### Description

<hr>

## Description 📜

I want to Create an Documentation explaining the concepts of Modular Arithmetic in C++ with some code examples too.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged !
