### ISSUE TITLE
FRONTEND WITH FRAMEWORK: REACT-1.1 WHAT IS JSX? 

### ISSUE THREAD

**Issue by riasenpai** [girlscript/winter-of-contributing#289]
Contributors are required to include what is JSX and why it is used, its relation with react as a framework. An example and its syntax should also be included.

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)
and [Code Of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by trip0le** [comment]
Hi @praveenscience Sir, This is Titas Nath(batch 6, frontend with HTML, css). May I contribute on this topic?

**Comment by trip0le** [comment]
Hi, This is Titas Nath(batch 6, frontend framework). May I contribute on this topic?

**Comment by anandhu720** [comment]
@trip0le I have assigned you a work already,after that i will assign you this work

**Comment by sahil9510** [comment]
Can I contribute on this?
Sahil Srivastava Batch-6 Frontend-Framework

**Comment by iamsuyashpatel07** [comment]
@anandhu720 hello mentor I'm from Batch-1 Frontend-Framework. **can I start working on this issue ?**

**Comment by nik09877** [comment]
Can I work on this issus?
I am from Batch-3 Frontend-Framework

**Comment by Saurabh-crypto16** [comment]
@anandhu720 I have a basic idea about JSX I want to contribute to this issue. I am from batch-2-frontend-framework

**Comment by the-pro** [comment]
@sahil9510 I have assigned you on this. @iamsuyashpatel07 @nik09877 @Saurabh-crypto16 It is a fist come first serve basis. Wait for other issues. Just keep checking "Frontend with frameworks" milestone

**Comment by iamsuyashpatel07** [comment]
okay @the-pro.

**Comment by ShobhanSrivastava** [comment]
Can i work on the video part of it?

**Comment by anandhu720** [comment]
@sahil9510  any updates of your work

**Comment by sahil9510** [comment]
@anandhu720 I have made a PR. Please review it

**Comment by anandhu720** [comment]
@sahil9510 ok

**Comment by anandhu720** [comment]
This issue is completed
