### ISSUE TITLE
OpenSource : 2.3 Start contributing some projects

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#29]
### Description :

Select some **interesting repositories** and start working on those.
The key thing is that before contributing a project it is always good to be familiar with it. In other words, use it before you help it. Therefore **download the releases** and try before you look at the `bug tracker.`  If you face some problems you can raise an issue in the bug tracker. Thereafter you may start submitting **some patches** for **particular tickets**.

`List of repositories:`
https://github.com/MunGell/awesome-for-beginners
Open-Source Programs/Contests you can participate in
There are many open-source coding programs that you can
participate in.
​
- Google Summer of Code (GSoC)
- HacktoberFest
- GirlScript Summer of Code
- Outreachy
- Rails Girl Summer of Code
- MLH Fellowship

`For more info check out:`
https://github.com/tapaswenipathak/Open-Source-Programs

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by Abhay3008** [comment]
Hey! I wanted to work on this issue !!

**Comment by Aryamanz29** [comment]
> Hey! I wanted to work on this issue !!
> 

Assigning this to you @Abhay3008 , Happy Documenting 🤩

**Comment by paras-saxena11** [comment]
I want to contribute in this please guide me.

**Comment by Aryamanz29** [comment]
@paras-saxena11  We really appreciate your comment but this issue has already been assigned to @Abhay3008.
Don't worry, We're creating a bunch more issues in the `OpenSource domain` for contributors in a couple of days. 😉

**Comment by siddhi-244** [comment]
Can I try it !
