### ISSUE TITLE
OpenSource : 4.3 Explain everything related to the `Season of KDE`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#290]
### Description :

- **Explain everything related to the `Season of KDE`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- Doc name should same as the `issue title  `

## Happy Contributing 🙌``

**Comment by KhafiaAyyub** [comment]
Can i work on this issue @Aryamanz29 ??

**Comment by KhafiaAyyub** [comment]
Can I contribute on this issue?

**Comment by Aryamanz29** [comment]
@KhafiaAyyub  Already assigned one issue to you, Complete that one first then I'll assign this to you 😉

**Comment by KhafiaAyyub** [comment]
Okay, thank you!!

**Comment by mayankkuthar** [comment]
@Aryamanz29  Can I work on this one? :)

**Comment by Harshkumar62367** [comment]
Can i work on this @Aryamanz29 ?

**Comment by Aryamanz29** [comment]
> Can i work on this @Aryamanz29 ?

Sure @Harshkumar62367 ; Assigning this to you
