### ISSUE TITLE
Cybersecurity: 1.9.9.3 Familiar to Linux Terminal

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#291]
## Note:
- This task is only for `Video` submission!
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by prithwishpramanik** [comment]
Sir I want to do this job

**Comment by Anant1711** [comment]
> Sir I want to do this job

@prithwishpramanik First submit your 1.9.8 task, only then I can assign you a second issue!

**Comment by prithwishpramanik** [comment]
Ok sir

**Comment by ShreyaTyagi0XD** [comment]
Can i work on this?

**Comment by Anant1711** [comment]
> Can i work on this?

Okay!
I'm assigning this task to you!

**Comment by Anant1711** [comment]
@ShreyaTyagi0XD When are you going to submit your Video?

**Comment by ShreyaTyagi0XD** [comment]
In a day or two
