### ISSUE TITLE
OpenSource : 4.4 Explain everything related to `Linux Foundation Mentorship Programs`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#292]
### Description :

- **Explain everything related to `Linux Foundation Mentorship Programs`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- Doc name should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Harshil-Jani** [comment]
Can I try with this?

**Comment by Aryamanz29** [comment]
> Can I try with this?

Sure @Harshil-Jani , Happy Documenting 🎉🎉
