### ISSUE TITLE
Python: Yield Keyword

### ISSUE THREAD

**Issue by nakshatra-garg** [girlscript/winter-of-contributing#2927]
### Description

Description:
What is the yield keyword?
Where yield keyword is used?
Advantages and Disadvantages.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nakshatra-garg** [comment]
/assign
@adityabisoi @prathimacode-hub

**Comment by adityabisoi** [comment]
@hritikksingh Is the mentor of this issue. Please reach out to him for your queries.

**Comment by hritikksingh** [comment]
@nakshatra-garg what's the status?

**Comment by nakshatra-garg** [comment]
> @nakshatra-garg what's the status?
> 

I'm still working on it.

**Comment by tanishpophale53** [comment]
@adityabisoi I want to work on documentation part of Yield Keyword. Please assign this issue to me.

**Comment by adityabisoi** [comment]
> @adityabisoi I want to work on documentation part of Yield Keyword. Please assign this issue to me.

Already been taken.
