### ISSUE TITLE
OpenSource : 4.5 Explain everything related to `Girlscript Summer of code`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#293]
### Description :

- **Explain everything related to `Girlscript Summer of code`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Ravinayak07** [comment]
can i work on this?

**Comment by Aryamanz29** [comment]
@Ravinayak07  Sure, Happy Documenting 🎉🎉

**Comment by Ravinayak07** [comment]
> @Ravinayak07 Sure, Happy Documenting 🎉🎉

Thank you

**Comment by Aryamanz29** [comment]
@Ravinayak07  Any updates ??  Submit PR by today

**Comment by Ravinayak07** [comment]
yeah working on the same. I will submit by today

**Comment by Ravinayak07** [comment]
> @Ravinayak07 Any updates ?? Submit PR by today

I have submitted the PR. please check

**Comment by Aryamanz29** [comment]
> > @Ravinayak07 Any updates ?? Submit PR by today
> 
> I have submitted the PR. please check

Create PR to `girlscript  : Opensource ` branch not `main` @Ravinayak07

**Comment by Ravinayak07** [comment]
> > > @Ravinayak07 Any updates ?? Submit PR by today
> > 
> > 
> > I have submitted the PR. please check
> 
> Create PR to `girlscript : Opensource ` branch not `main` @Ravinayak07

Done Sir

**Comment by nickel-28** [comment]
I would like to work on this issue. Please assign me this

**Comment by adityakrm2** [comment]
I would also like to work on this, thank you.

**Comment by Aryamanz29** [comment]
@adityakrm2  Assigning this to you, Happy learning 🎉🎉
