### ISSUE TITLE
Flutter : Basic Widgets used - Documentation

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#2939]
### Description

Add documentation on basic widgets used-
-Text
-Row, Column
-Stack
-Container

Each should be explained with examples to distinctively explain the use of each widget.

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Safwan310** [comment]
@pratishthaa I have created a pull request. Can you please verify it?
