### ISSUE TITLE
OpenSource : 4.6 Explain everything related to the `Google Season of Docs (GSoD)`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#294]
### Description :

- **Explain everything related to the `Google Season of Docs (GSoD)`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Ravinayak07** [comment]
can i work on this?

**Comment by yashikabhargava** [comment]
can I work on this issue?

**Comment by RaghavvGupta** [comment]
Can I work on this?

**Comment by Aryamanz29** [comment]
@yashikabhargava Sure, Happy Documenting🎉🎉

**Comment by yashikabhargava** [comment]
> @yashikabhargava Sure, Happy Documenting🎉🎉

Thank You!

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.Please consider me for this..
Riya Pandey
Batch-2

**Comment by Aryamanz29** [comment]
@yashikabhargava  Any updates ??

**Comment by yashikabhargava** [comment]
@Aryamanz29 Yes I'm Working on it. Just have a question how do I checkout new branch from opensource branch, I'm a beginner so a little confused.
