### ISSUE TITLE
FRONTEND WITH FRAMEWORK: REACT- 1.2 Introduction to Babel

### ISSUE THREAD

**Issue by riasenpai** [girlscript/winter-of-contributing#295]
Contributors are required to include 
* what is Babel
* about babel
* why babel 
*  its relation to React and anything relevant to the framework should be included. 

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) and [Code Of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Himanshi1805** [comment]
Can I contribute on this? 
Himanshi Gupta Batch-6 Frontend-Framework

**Comment by mukeshmjn** [comment]
Sure @Himanshi1805 go for it . Good luck!

**Comment by CSAURABH** [comment]
@mukeshmjn Can I work on this issue documentation.

**Comment by GyaniRoman23** [comment]
I would like to work on this issue. @mukeshmjn if this issue s reassigned, please do consider me for it.

**Comment by mukeshmjn** [comment]
> I would like to work on this issue. @mukeshmjn if this issue s reassigned, please do consider me for it.

Sure :)
