### ISSUE TITLE
ML 2.19 : Gradient Descent Algorithms (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2954]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Gradient Descent Algorithms_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
-  Dataset to be used : **IRIS DATASET**. (No other datasets will be entertained.)

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation 
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by guptapriya-83900** [comment]
Name: Priya Gupta
Batch: batch-1
Github Profile link: https://github.com/guptapriya-83900
Type of Contribution: Documentation , I will explain in detail bout Gradient Descent along with implementation and its uses.

**Comment by abhisheks008** [comment]
Issue assigned @guptapriya-83900. Go ahead 🚀

**Comment by guptapriya-83900** [comment]
Thankyou for assigning me this issue @abhisheks008 
I have a doubt, Can we use scikit library for this or we have to implement this without using scikit. 
And Is it Ok if we show implementation both with the help of Scikit library and without it?

**Comment by abhisheks008** [comment]
Show both, then compare them, it'll be a great one @guptapriya-83900

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by guptapriya-83900** [comment]
@abhisheks008 
I have created the pull request
