### ISSUE TITLE
ML 2.19 :Gradient Descent Algorithms (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#2955]
### 📌  Issues for Week 2
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Gradient Descent Algorithms_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Supervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
-  Dataset to be used : **IRIS DATASET**. (No other datasets will be entertained.)

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do video on this issue.

**Comment by AdityaNikhil** [comment]
**Full name** : Aditya Nikhil
**Batch Number** : 2
**GitHub Profile Link** : github.com/adityanikhil
**Which type of Contribution you want to make** :
Documentation (Coding in .ipynb file, show the implementation)

**Comment by Aaksha-sharma** [comment]
I want to contribute through audio

**Comment by das-ankur** [comment]
Hello, I would like to work on this issue.
Full Name: Ankur Das
Batch No: 2
GitHub : https://github.com/das-ankur
Documentation : Document / Video

**Comment by abhisheks008** [comment]
As we are assigning issues on FCFS basis, this issue is assigned to @AdityaNikhil. Go ahead! 🚀
