### ISSUE TITLE
DSA: Search in a sorted and rotated array

### ISSUE THREAD

**Issue by Aaryan376** [girlscript/winter-of-contributing#2960]
### Description

Implementation of Search in a sorted and rotated array problem by writing code.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sameer-19** [comment]
Sameer Aggrawal
Batch-3 DSA
Documentation
Please assign this problem to me. I would like to solve this problem.
