### ISSUE TITLE
Version Control System

### ISSUE THREAD

**Issue by newbiens** [girlscript/winter-of-contributing#2962]
### Description

In this document, version control and it's type will be discussed.

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
Already covered @newbiens See this https://github.com/girlscript/winter-of-contributing/tree/Opensource/Open_Source
