### ISSUE TITLE
Opensource : 6.3 Everything about `PIP` 

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2966]
<hr>

## Description 📜

Opensource :   6.3 Everything about `PIP` 

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.3_PIP.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by GyaniRoman23** [comment]
Hey @Aryamanz29  I want to contribute to this issue.

**Comment by Aryamanz29** [comment]
@GyaniRoman23  Sure, Happy learning 🎉🎉

**Comment by Aryamanz29** [comment]
@GyaniRoman23  Any updates on this?

**Comment by GyaniRoman23** [comment]
Yeah!! @Aryamanz29  I'll make a PR today itself, its almost finished.

**Comment by riyapandey730** [comment]
I want to contribute on this

**Comment by GyaniRoman23** [comment]
@riyapandey730 I have almost finished this issue, will make a PR asap

**Comment by riyapandey730** [comment]
okay

**Comment by mayankkuthar** [comment]
@Aryamanz29 I would like to work on this issue, Kindly assign me this.

**Comment by GyaniRoman23** [comment]
Hey @mayankkuthar I have finished this issue, just having some problems while making a PR. Will do it today!!

**Comment by mayankkuthar** [comment]
@GyaniRoman23 Hey kindly update your work or make a PR ASAP, and if You don't want to make a PR, Then kindly let me do it 😄 
@Aryamanz29 Please Assign me :octocat:
