### ISSUE TITLE
Opensource : 6.4  Everything about `vscode` 

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2967]
<hr>

## Description 📜

Opensource :   Opensource : 6.4 Everything about `vscode`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.4_vscode.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@AdityaStark7 Any updates on this?

**Comment by purohitmansi** [comment]
Please do assign this to me.
