### ISSUE TITLE
Frontend With Framework - What and Why React.js

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#297]
### **NEED TO CONTAIN**

*  What is React.js
*  Why React.js
*  Advantage of React.js
*  Dis Advantages of React.js

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ React inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by Ravinayak07** [comment]
can i work on this ?

**Comment by trip0le** [comment]
Can I be assigned the above task?

**Comment by anandhu720** [comment]
@Ravinayak07 you can only work at a single task at a time
do you want to do this or other one

**Comment by anandhu720** [comment]
@trip0le wait for some time,we are following first come first service,If he is doing another one we will assign this to you

**Comment by anandhu720** [comment]
@trip0le you can do it

**Comment by Adarshswain** [comment]
Can I work on this

**Comment by Ravinayak07** [comment]
> @Ravinayak07 you can only work at a single task at a time
> do you want to do this or other one

I want to work on this

**Comment by Ravinayak07** [comment]
> @Ravinayak07 you can only work at a single task at a time
> do you want to do this or other one

ok i will work on other one.

**Comment by trip0le** [comment]
> @trip0le you can do it
Thank you Sir

**Comment by ishitam-29** [comment]
Can I work on this sir?

**Comment by vilay1702** [comment]
I am interested to do it. Please consider me if it is reassigned.

**Comment by Shakthi011001** [comment]
I can work on this

**Comment by Jaya3112** [comment]
I wish to contribute in the form of documentation. Assign me this work.

**Comment by anandhu720** [comment]
@trip0le any updates

**Comment by Babithakumari** [comment]
I can work on this. Please consider me if it is reassigned

**Comment by kajaljha09** [comment]
I can work on this

**Comment by anandhu720** [comment]
@trip0le  any updates please inform us

**Comment by trip0le** [comment]
> @trip0le any updates please inform us

Sir, I am working on the above issue.
 Is there a deadline by which I have to complete my work?

**Comment by anandhu720** [comment]
@trip0le take your time.One week is max time.Please try to finish before it.Because things are planned according to week

**Comment by trip0le** [comment]
> @trip0le take your time.One week is max time.Please try to finish before it.Because things are planned according to week

Sure Sir

**Comment by trip0le** [comment]
@anandhu720 Sir, I was thinking of making a power point presentation with audio on the above issue. In that case,  if I push a readme file having the google drive link of the presentation in my forked repository and then send a pull request to the Frontend_Web_Development_React_Angular_Vue branch from the same, will it be acceptable?

**Comment by trip0le** [comment]
@anandhu720 Sir, I have finished working on the above issue. Would you please check if whether its alright?
