### ISSUE TITLE
Opensource : 6.8 Explain everything about `Deno`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2974]
<hr>

## Description 📜

Opensource : 6.8 Explain everything about `Deno`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.8_Deno.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by mayankkuthar** [comment]
Please Assign me I would like to work on this issue.

**Comment by Aryamanz29** [comment]
@eshan1925 Assigned,  Happy Learning 🎉🎉

**Comment by eshan1925** [comment]
@Aryamanz29 I have created the PR, please review and merge if it is having no issues.
THANK YOU
