### ISSUE TITLE
Opensource : 6.9 Explain everything about `Three.js`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2975]
<hr>

## Description 📜

Opensource : 6.9 Explain everything about `Three.js`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.9_ThreeJS.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by mayankkuthar** [comment]
Please Assign me I would like to work on this issue.

**Comment by Aryamanz29** [comment]
@mayankkuthar  Happy learning 🎉🎉

**Comment by mayankkuthar** [comment]
@Aryamanz29 Kindly Review Pull request #3196  So that I can Open a Pull request for this Issue in the opensource branch

**Comment by mayankkuthar** [comment]
@Aryamanz29 Thanks! 😄
