### ISSUE TITLE
Opensource : 6.10 Explain everything about `Material UI`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2978]
<hr>

## Description 📜

Opensource : 6.10 Explain everything about `Material UI`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.10_MaterialUI.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by newbiens** [comment]
I have done the required things, please merge the PR.
