### ISSUE TITLE
Opensource : 6.11 Explain everything about `Webpack`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2979]
<hr>

## Description 📜

Opensource : 6.11 Explain everything about `Webpack`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.11_Webpack.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.

**Comment by Aryamanz29** [comment]
@riyapandey730  Suree, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@riyapandey730  Any updates on this?
