### ISSUE TITLE
FRONTEND WITH FRAMEWORK: REACT-1.3 ES6 Features 

### ISSUE THREAD

**Issue by riasenpai** [girlscript/winter-of-contributing#298]
Contributors are required to include information about ES6 features, their syntax , an example, a comparison and anything relevant to the framework. 

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)
and [Code Of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Ravinayak07** [comment]
can i work on this?

**Comment by mukeshmjn** [comment]
Sure @Ravinayak07

**Comment by mukeshmjn** [comment]
@Ravinayak07 go for it

**Comment by Ravinayak07** [comment]
> @Ravinayak07 go for it!

thank you

**Comment by nik09877** [comment]
Can i work on this issue?
BAtch-3 Frontend Framework

**Comment by vatsal1704** [comment]
Can I work on this issue?
Batch-5 Frontend Framework

**Comment by heet-kumar** [comment]
@Ravinayak07 what is the update till know on these issue

**Comment by anandhu720** [comment]
@Ravinayak07  any updates

**Comment by Ravinayak07** [comment]
> @Ravinayak07 any updates

yeah working on it., will submit PR by tomorrow

**Comment by anandhu720** [comment]
@Ravinayak07 no problem bro,take your time,just asked to check if you are working or not

**Comment by ishangupta6412** [comment]
@riasenpai maam can i work on this?

**Comment by ishangupta6412** [comment]
Please assign this to me

**Comment by Ravinayak07** [comment]
> @Ravinayak07 no problem bro,take your time,just asked to check if you are working or not

when is the last date to submit the PR?

**Comment by anandhu720** [comment]
@Ravinayak07 one week is max time,please try to submit it before that

**Comment by Ravinayak07** [comment]
> @Ravinayak07 one week is max time,please try to submit it before that

Sure sir

**Comment by Ravinayak07** [comment]
> @Ravinayak07 one week is max time,please try to submit it before that

Sir I have submitted the PR. please Check
