### ISSUE TITLE
Opensource : 6.13 Explain everything about `React Native`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2981]
<hr>

## Description 📜

Opensource : 6.13 Explain everything about `React Native`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.13_React_Native.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HassanRahim26** [comment]
I would like to work on this issue, please assign me this issue.

**Comment by Aryamanz29** [comment]
@HassanRahim26  Assigned, Happy Learning 🙂

**Comment by Aryamanz29** [comment]
@HassanRahim26  Any updates on this?

**Comment by HassanRahim26** [comment]
It'll be completed today.
