### ISSUE TITLE
Opensource : 6.15 Explain everything about `Ember.js`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#2983]
<hr>

## Description 📜

Opensource : 6.15 Explain everything about `Ember.js`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.15_EmberJS.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@Harshkumar62367 Any updates on this?

**Comment by Harshkumar62367** [comment]
I will submit a pr tonight sir.
