### ISSUE TITLE
[Create New Issue]: Relational Algebra

### ISSUE THREAD

**Issue by NiharikaSngh** [girlscript/winter-of-contributing#2987]
### Description

State all the Fundamental Operations of Relational algebra like Select, Project, Union, Set difference, etc.

### Domain

Database

### Type of Contribution

Documentation

### Code of Conduct  

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by NiharikaSngh** [comment]
This issue has been opened by me and I'll assign it to myself. So visitors, kindly move over to the next issue!!

**Comment by ayushjain27** [comment]
I am not able to create pull request in this repository.  Not able to merge. Help me
