### ISSUE TITLE
OpenSource : 4.7 Explain everything related to `Outreachy Program`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#299]
### Description :

- **Explain everything related to `Outreachy Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title `

## Happy Contributing 🙌

**Comment by yashikabhargava** [comment]
can i work on this issue?

**Comment by Aryamanz29** [comment]
@yashikabhargava  Already assigned one issue to you, Complete that one, I'll assign this to you

**Comment by yashikabhargava** [comment]
@Aryamanz29 Okay, Thank you!

**Comment by KhafiaAyyub** [comment]
can I contribute on this issue??

**Comment by arpanaditya** [comment]
Can i work on this issue? @Aryamanz29

**Comment by Aryamanz29** [comment]
Creating more issues folks , Don't worry🙌

**Comment by saketsagarsingh** [comment]
May I have the honour of working on this issue?

**Comment by riyapandey730** [comment]
can i do this?

**Comment by nickel-28** [comment]
Please Assign it to me!!!
I want to contribute
