### ISSUE TITLE
JavaScript vs jQuery

### ISSUE THREAD

**Issue by KhafiaAyyub** [girlscript/winter-of-contributing#2990]
### Description

As jQuery is a JavaScript library. So, this issue  will cover about JS vs jQuery.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by daminimehra** [comment]
@paramsiddharth pls assign this issue to me. I would like to work on this issue.

**Comment by paramsiddharth** [comment]
> @paramsiddharth pls assign this issue to me. I would like to work on this issue.

@daminimehra I'm so sorry, the issue was automatically tagged JavaScript by the bot. It seems to be for FEWD instead.
