### ISSUE TITLE
C/C++ Libraries

### ISSUE THREAD

**Issue by NiharikaSngh** [girlscript/winter-of-contributing#2997]
### Description

Write the functions of various libraries in Cpp/c.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by NiharikaSngh** [comment]
@akarshan2602 This issue has been created by me. I am also a contributor like you. I'll assign this issue to myself later. So, back off !!

**Comment by akarshan2602** [comment]
Gurl u could have said that in a good way, i didn't see that it was
assigned, so i did that, use your brains

**Comment by NiharikaSngh** [comment]
Ohhkk......then un-assign yourself now .....so that I can assign this issue to me. And sorry if you were hurt 👍

**Comment by akarshan2602** [comment]
It's ok...i will unassign..sorry for the trouble, im struggling alot, im
new there lmao, sorry if i was rude
