### ISSUE TITLE
OpenSource : 4.9 Explain everything related to `Hyperledger Mentorship Program`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#301]
### Description :

- **Explain everything related to `Hyperledger Mentorship Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by RaghavvGupta** [comment]
Please assign it to me!

**Comment by Aryamanz29** [comment]
@RaghavvGupta  Sorry Issue already assigned to you, First, complete that one, Hope you understandand

**Comment by LegendSumeet** [comment]
Can you assign me to these issue?
 
I will do in video and Documentation manner....@Aryamanz29

**Comment by RaghavvGupta** [comment]
Sure, thanks for assigning!

**Comment by Aryamanz29** [comment]
> Can you assign me to these issue?
> 
> I will do in video and Documentation manner....@Aryamanz29

Ok, Assigning this to you @LegendSumeet 🎉🎉
