### ISSUE TITLE
OpenSource : 4.11 Explain everything related to `HacktoberFest`

### ISSUE THREAD

**Issue by Adi7171** [girlscript/winter-of-contributing#302]
### Description :

- **Explain everything related to `HacktoberFest`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Adi7171** [comment]
@Aryamanz29  I would like to be assigned to this issue

**Comment by Adarshswain** [comment]
can i go  for it

**Comment by jaigora24** [comment]
Can I go for it?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I would like to be assigned to this issue

Assigning this issue to you since you've created @Adi7171 , More issues coming folks, Don't worry🙌🙌

**Comment by jaigora24** [comment]
Can I go for it?
