### ISSUE TITLE
OpenSource : 4.10 Explain everything related to  `Free Software Foundation (FSF) Internship Program`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#303]
### Description :

- **Explain everything related to `Free Software Foundation (FSF) Internship Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by kunal-kumar-chaudhary** [comment]
i would like to work on this!

**Comment by Aryamanz29** [comment]
> i would like to work on this!

You've already assigned one issue, Try to complete that first

**Comment by Asmit2952** [comment]
I would like to work on this @Aryamanz29 . Please assign this to me.

**Comment by Aryamanz29** [comment]
> I would like to work on this @Aryamanz29 . Please assign this to me.

Sure @Asmit2952 , Assigning this to you, Happy Documenting🎉🎉

**Comment by Asmit2952** [comment]
> > I would like to work on this @Aryamanz29 . Please assign this to me.
> 
> Sure @Asmit2952 , Assigning this to you, Happy Documenting🎉🎉

Can I contribute in .MD file or do I need to contribute in .ipynb file?

**Comment by Aryamanz29** [comment]
> > > I would like to work on this @Aryamanz29 . Please assign this to me.
> > 
> > 
> > Sure @Asmit2952 , Assigning this to you, Happy Documentingtadatada
> 
> Can I contribute in .MD file or do I need to contribute in .ipynb file?

Contribute in `.md`

**Comment by Asmit2952** [comment]
I need a help, I created a PR, but my previous commits also came along with that PR, what should I do?

**Comment by Aryamanz29** [comment]
Delete that fork repo and fork it again , then use `git checkout Opensource` then create new branch for solving this Issue using `git checkout -b new_branch_name` then made changes and create PR
