### ISSUE TITLE
OpenSource : 4.14 Explain everything related to`Open Mainframe Project Mentorship Program`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#304]
### Description :

- **Explain everything related to `Open Mainframe Project Mentorship Program`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Asmit2952** [comment]
Can I work on this?

**Comment by Aryamanz29** [comment]
@Asmit2952  Already assigned one issue to you, Complete that one first then I'll assign this to you 😉

**Comment by siddhi-244** [comment]
Can I try?

**Comment by Aryamanz29** [comment]
> Can I try?

@siddhi-244 Ok, Go ahead 🎉🎉
