### ISSUE TITLE
POM.xml file configuration

### ISSUE THREAD

**Issue by Satyam175** [girlscript/winter-of-contributing#3044]
### Description

<h2>Create Documentation for configuration of POM.xml file </h2>

### Domain

Backend Dev (Java)

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Yash-Chandrani** [comment]
\assign document
