### ISSUE TITLE
The Preprocessors in C language

### ISSUE THREAD

**Issue by aparajitachaturvedi** [girlscript/winter-of-contributing#3049]
### Description

I would like to make a documentation on different preprocessors in C language along with suitable example.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Prateek-8168** [comment]
I want to work in this issue.

**Comment by Harsh652-cpu** [comment]
I want to work with this issue,please assign this issue with me
