### ISSUE TITLE
Guide For MLH Fellowship

### ISSUE THREAD

**Issue by Sakshi-1101** [girlscript/winter-of-contributing#305]

**Comment by Sakshi-1101** [comment]
Sir please assign me this issue ?

**Comment by Chirag-creator17** [comment]
this issue is already there.

**Comment by Aryamanz29** [comment]
> Sir please assign me this issue ?

Copy of #287 ,Closing this

**Comment by Aryamanz29** [comment]
> Sir please assign me this issue ?

#290 is open try to grab that
