### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular (2.3)-> What are Pipes?Explain Built-in and Custom Pipes.

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#3052]
### Description

- What are pipes?
- Why are they used?
- Built in pipes
- Custom pipes
- Explain with syntax/code.
- Reference:- https://angular.io/guide/pipes
(It's a week-2 issue )

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week2" directory
3. Tasks would be assigned on First Come First Serve Basis.

### Domain

Frontend Dev React/Angular/Vue

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by CSAURABH** [comment]
@mukeshmjn @anandhu720 can I work on this issue.

**Comment by mukeshmjn** [comment]
@CSAURABH sure.

**Comment by CSAURABH** [comment]
@mukeshmjn  I'll be adding the PR by tomorrow.
