### ISSUE TITLE
DSA

### ISSUE THREAD

**Issue by shubhamraj1601** [girlscript/winter-of-contributing#3067]
### Description

Writing Solution for the problems.

### Domain

Competitive Programming

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saketsagarsingh** [comment]
/assign
Saket Sagar Batch -2
