### ISSUE TITLE
OpenSource : 4.12 Explain everything related to`Open Summer of Code`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#307]
### Description :

- **Explain everything related to `Open Summer of Code`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Adarshswain** [comment]
I want Contribute

**Comment by siddhi-244** [comment]
Can I try

**Comment by Adarshswain** [comment]
can I contribute

**Comment by Aryamanz29** [comment]
@Adarshswain Assigning this to you, Happy Documenting 🎉🎉🎉

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.Please consider me for this..
Riya Pandey
Batch-2

**Comment by Aryamanz29** [comment]
@Adarshswain Removed assignment (Due to inactivity)

**Comment by Harshil-Jani** [comment]
Can I go with Documentation? 
Batch-1

**Comment by Aryamanz29** [comment]
@Harshil-Jani  Assigning this to you, Happy learning 🎉🎉

**Comment by Adarshswain** [comment]
Till which date I have to submit

**Comment by Aryamanz29** [comment]
> Till which date I have to submit

1-2 days max
