### ISSUE TITLE
DSA 2.1.1.1 Strings : Introduction to Strings

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3070]
### Description
Explain strings, string representation, and declaration.

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by diya-dhan** [comment]
Diya Dhandapani
Batch No 7
Documentation

**Comment by goelesha** [comment]
@Anushka-Gamad It has been mentioned to not use assign command in the issues created by the supervisors. You can still work on the audio part. Work on - #3105 

@diya-dhan Assigning the issue to you for documentation.
Make sure to submit a PR within 7 days.

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation
