### ISSUE TITLE
DSA 2.1.1.2 Strings : Implementation of Strings in C & C++

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3071]
### Description
Explain the implementation of strings in C and C++

## Task
- [ ] Audio
- [ ] Video
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by 1PRatgit** [comment]
Pranjali R
DSA batch 7
I want to work on this issue

**Comment by 1PRatgit** [comment]
Documentation

**Comment by goelesha** [comment]
@1PRatgit Assigning this issue to you for documentation.
Make sure to submit a PR within 7 days.
All the best !!

**Comment by dhruti29** [comment]
batch - 2
documentation
Dhruti Gandhi

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by 0199prabha** [comment]
/assign 
->documentation

**Comment by 0199prabha** [comment]
Prabha Kumari
Batch-1
Contribution type: Documentation

**Comment by tanvideshmukh29** [comment]
can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by goelesha** [comment]
The issue is already assigned.
