### ISSUE TITLE
DSA 2.1.1.3 Strings: Arithmetic Operations on Strings

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3072]
### Description
Explain arithmetic operations in strings.

## Task
- [ ] Audio
- [ ] Video
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sirilalithaadapa** [comment]
Siri Lalitha 
Batch-7
DSA
Documentation

**Comment by goelesha** [comment]
@sirilalithaadapa Assigning the issue to you for documentation. 
Make sure to submit a PR within 7 days

**Comment by dhruti29** [comment]
I would like to work on this issue (documentation).
batch - 2
Dhruti Gandhi

**Comment by goelesha** [comment]
The documentation part is already assigned. You can take up either video or audio or you can work on some other issue.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by saketsagarsingh** [comment]
@goelesha if no one is working on this issue I want to be assigned to this issue
Saket Sagar
Batch-2
Documentation

**Comment by goelesha** [comment]
@saketsagarsingh Submit a PR within 7 days
