### ISSUE TITLE
SQL expressions and SQL commands

### ISSUE THREAD

**Issue by Ash515** [girlscript/winter-of-contributing#3084]
### Description

Learn how to form expressions and commands in SQL  and upload the documentation or video, or audio into Database folder 

### Domain

Database

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by NIKITAjadhav4124** [comment]
I would like to work on this issue @Ash515
