### ISSUE TITLE
OpenSource : 2.4 Start your own open-source projects

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#31]
### Description :

You may write your own **libraries or frameworks** or e**ven simple
code snippets for your own** works or for your workplace tasks.
Maybe someone like is you also looking for that kind of solution, Do
you like to help someone?😉 Of course, you can share your work as an
open-source project just using the steps as per below

-  Bring project stuff to one location and `make a Git repository.`
-  Select a proper license `(MIT, Apache, etc)`
-  Push to a `Github repository`
-  Improve the `documentation` and  write a  `good README.`

### Note : 
You have to add your github profile & projects link in this :arrow_right:  [file](https://github.com/girlscript/winter-of-contributing/blob/Opensource/Open_Source/2.Getting_Started_With_Open_Source/2.4_Create_Your_Own_Open_Source_Project.md)  

#### Reference PR :- https://github.com/girlscript/winter-of-contributing/pull/1927

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by kunal-kumar-chaudhary** [comment]
I would like to work on this issue.

**Comment by kunal-kumar-chaudhary** [comment]
> > I would like to work on this issue.
> 
> Sure @kunal-kumar-chaudhary , Assigning this to you , Happy Documenting 🤩

i had made a python script file where i have all the helper functions that i use to plot the graphs, unzip the data, etc.. can i include that file here?

**Comment by Aryamanz29** [comment]
> > > I would like to work on this issue.
> > 
> > 
> > Sure @kunal-kumar-chaudhary , Assigning this to you , Happy Documenting star_struck
> 
> i had made a python script file where i have all the helper functions that i use to plot the graphs, unzip the data, etc.. can i include that file here?

Yes sure @kunal-kumar-chaudhary , that's what we want, Feel free to come with creative ideas 😀

**Comment by Aryamanz29** [comment]
@kunal-kumar-chaudhary  Any Updates?

**Comment by siddhi-244** [comment]
Can I try it !

**Comment by kunal-kumar-chaudhary** [comment]
> @kunal-kumar-chaudhary Any Updates?

i've had  made pull request, but now i see the file structure has been changed. can you tell in which section i have to include my files for making yet another different pull request?

**Comment by Aryamanz29** [comment]
> > @kunal-kumar-chaudhary Any Updates?
> 
> i've had made pull request, but now i see the file structure has been changed. can you tell in which section i have to include my files for making yet another different pull request?

@kunal-kumar-chaudhary  Put your doc under `section-2` and follow `file name convention`

**Comment by kunal-kumar-chaudhary** [comment]
> > > @kunal-kumar-chaudhary Any Updates?
> > 
> > 
> > i've had made pull request, but now i see the file structure has been changed. can you tell in which section i have to include my files for making yet another different pull request?
> 
> @kunal-kumar-chaudhary Put your doc under `section-2` and follow `file name convention`

I've created the pull request now with the proper hierarchical check.

**Comment by shashank725** [comment]
I would like to work on this issue.

**Comment by mayankkuthar** [comment]
@kunal-kumar-chaudhary Please Attach your pull request to the issue.

**Comment by Aryamanz29** [comment]
@shashank725  Go ahead , Happy Learning

**Comment by shashank725** [comment]
> @kunal-kumar-chaudhary Please Attach your pull request to the issue.

I have created a hotel management website can i can upload that here?

**Comment by palakshivlani-11** [comment]
I would like to work on this issue.

**Comment by nickel-28** [comment]
I would like to work on this issue. Please assign this to me @kunal-kumar-chaudhary

**Comment by Aryamanz29** [comment]
Guys for this issue we can have multiple contributors so I'm assigning everyone, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
Just put  your `doc` inside `section-2` and make sure you all have a `different doc name`

**Comment by mayankkuthar** [comment]
@Aryamanz29 It would be better if every contributor put their repo and project link in a single doc like in #401 or you can define a name convention of doc name for every contributor to follow. 
<b>Example:</b> ```2.4.1_<Contributor's Name>'s_Opensource_project.md```

**Comment by Aryamanz29** [comment]
> @Aryamanz29 It would be better if every contributor put their repo and project link in a single doc like in #401 or you can define a name convention of doc name for every contributor to follow.
> Example: `2.4.1_<Contributor's Name>'s_Opensource_project.md`

Sure I'll update this in issue description

**Comment by siddhi-244** [comment]
Can we add others open source projects as well ?

**Comment by mayankkuthar** [comment]
@siddhi-244 No, It's clearly mentioned in the topic of issue ```own open-source project```. Therefore, I think It's not like you can add other projects.

**Comment by palakshivlani-11** [comment]
can i add about various features of a particular framework?

**Comment by shashank725** [comment]
> > @kunal-kumar-chaudhary Please Attach your pull request to the issue.
> 
> I have created a hotel management website can i can upload that here?

@Aryamanz29 ?

**Comment by Aryamanz29** [comment]
> > @kunal-kumar-chaudhary Please Attach your pull request to the issue.
> 
> I have created a hotel management website can i can upload that here?

Yes you can add your project in doc @shashank725

**Comment by siddhi-244** [comment]
> > > @kunal-kumar-chaudhary Please Attach your pull request to the issue.
> > 
> > 
> > I have created a hotel management website can i can upload that here?
> 
> Yes you can add your project in doc @shashank725

I have a open source project of my own can I add ?

**Comment by Aryamanz29** [comment]
> > > > @kunal-kumar-chaudhary Please Attach your pull request to the issue.
> > > 
> > > 
> > > I have created a hotel management website can i can upload that here?
> > 
> > 
> > Yes you can add your project in doc @shashank725
> 
> I have a open source project of my own can I add ?

Sure go ahead @siddhi-244  🎉🎉 Follow this PR https://github.com/girlscript/winter-of-contributing/pull/1927

**Comment by Aryamanz29** [comment]
@siddhi-244  You have to add your github profile & projects link in this :arrow_right:  [file](https://github.com/girlscript/winter-of-contributing/blob/Opensource/Open_Source/2.Getting_Started_With_Open_Source/2.4_Create_Your_Own_Open_Source_Project.md)

**Comment by siddhi-244** [comment]
> @siddhi-244 You have to add your github profile & projects link in this ➡️ [file](https://github.com/girlscript/winter-of-contributing/blob/Opensource/Open_Source/2.Getting_Started_With_Open_Source/2.4_Create_Your_Own_Open_Source_Project.md)

Sure . Thank you.

**Comment by purohitmansi** [comment]
I would like to work on this issue. Please do assign this to me.

**Comment by shashank725** [comment]
@Aryamanz29 I have created a PR

**Comment by aaditya2801** [comment]
please /assign  me, I want to add one of my best open source project 👍

**Comment by Aryamanz29** [comment]
> please /assign me, I want to add one of my best open source project +1

Done, Go ahead 🚀

**Comment by aaditya2801** [comment]
@Aryamanz29 yeah I am working on it 👍

**Comment by Aryamanz29** [comment]
@KushalMehta39  Assigned

**Comment by KushalMehta39** [comment]
> @KushalMehta39 Assigned

Can I add My web dev project here @Aryamanz29

**Comment by amanraj-iit** [comment]
I would like to work on it

**Comment by Aryamanz29** [comment]
@amanraj-iit  Sure , Go ahead

**Comment by Aryamanz29** [comment]
Closing this issue now, Thanks everyone for contributing  🎉🎉
