### ISSUE TITLE
OpenSource : 4.13 Explain everything related to `FOSSEE Summer Fellowship`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#310]
### Description :

- **Explain everything related to `FOSSEE Summer Fellowship`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by siddhi-244** [comment]
Can I try?

**Comment by Aryamanz29** [comment]
@siddhi-244 Already assigned previous one

**Comment by siddhi-244** [comment]
> @siddhi-244 Already assigned previous one

Sure thank you. I already completed my previous 2 issues. I can work on these 2 now !

**Comment by Aryamanz29** [comment]
ok @siddhi-244  Assigning this to you 🎉🎉

**Comment by siddhi-244** [comment]
> ok @siddhi-244 Assigning this to you 🎉🎉

Thank you so much.

**Comment by siddhi-244** [comment]
Please check my pr @Aryamanz29
