### ISSUE TITLE
DSA 2.1.1.1 Strings : Introduction to Strings- Audio

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3105]
### Description
Explain strings, string representation, and declaration.

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by goelesha** [comment]
@Anushka-Gamad You can take up this issue.

**Comment by afreenabegum** [comment]
Hi mam @goelesha 
I want to contribute through AUDIO format, Please assign it to me.


Afreena begum
DSA Batch-1
