### ISSUE TITLE
Bit Manipulation : Bitwise operator

### ISSUE THREAD

**Issue by uditkatyal** [girlscript/winter-of-contributing#313]
Note :
Changes should be made inside the Open_Source/ directory & Opensource branch.
Issue only for GWOC'21 contributors.
For Contributor please don't create the same issue again, before creating any issue do visit OpenSource Milestone
Doc name should same as the issue title
Must-Follow : Contributing Guidelines & Code of Conduct before start Contributing.
Happy Contributing

**Comment by GopinathBalaji** [comment]
Can I try to work on this issue, please?

**Comment by Akshita-Sharma-25** [comment]
please assign this issue to me i have well defined notes with questions on this topic which can be turned into a document for contribution.
DSA batch-4 Akshita sharma

**Comment by pragatia-64U** [comment]
I can work on this issue. Can you assign this to me?

**Comment by ketanraj15** [comment]
I can work on the issue. Can you assign this to me?

**Comment by ajaykathwate** [comment]
I would love to work on this issue.(doc)
pls assign this issue to me
