### ISSUE TITLE
DSA :2.1 Comparison Between Between Different Sorting Algorithm

### ISSUE THREAD

**Issue by pallavidhere23** [girlscript/winter-of-contributing#3133]
### Description

This Documentation will Compare Different Sorting Algorithm on the basis of Time and Space Complexity.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saketsagarsingh** [comment]
Saket Sagar
Batch-2
Documentation
