### ISSUE TITLE
[Frontend with HTML/CSS/JS] How does the Internet work

### ISSUE THREAD

**Issue by PrachiDoshi2170** [girlscript/winter-of-contributing#3134]
###  Description

Mention the details about how does the internet work and what are the services provided by the internet in the area of web development

Please /assign me this task @moulikagrawal 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by PrachiDoshi2170** [comment]
Please /assign me this issue @moulikagrawal, if it is not yet create and guide me about where and under what title should I submit the PR

**Comment by moulikagrawal** [comment]
@PrachiDoshi2170 sorry this issue is already created and PR is generated

**Comment by PrachiDoshi2170** [comment]
Okay so should I close this issue or delete it? And can you guide me how to
find out that which topics are still left in the front-end roadmap?

**Comment by moulikagrawal** [comment]
Yes you can close the issue. To find already taken issues, you will have to search the issues tab for the topic
