### ISSUE TITLE
OpenSource : 5. Explain everything related to `github-pages`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#315]
### Description :

- **Explain everything related to `github-pages`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by HarshK07** [comment]
Can i get this one ? @Aryamanz29

**Comment by anurag-b72** [comment]
Can I work on this ! @Aryamanz29

**Comment by uditkatyal** [comment]
I have hosted my all websites on Github pages and am quite familiar with idea.
pls, assign this issue to me! @Aryamanz29

**Comment by Aryamanz29** [comment]
@HarshK07 , Assigning this to you, Happy Documenting 🎉🎉🎉

**Comment by riyapandey730** [comment]
can i work on this?

**Comment by Aryamanz29** [comment]
@riyapandey730  Assigning this to you, Happy docs 🎉🎉
Removed assignment from @HarshK07  (Due to inactivity)

**Comment by bhavesh-chaudhari** [comment]
@Aryamanz29 can i try this ? I have hosted many static websites with github pages and i am aware about common issues.

**Comment by Aryamanz29** [comment]
@bhavesh-chaudhari  Assigning this to you, Happy Learning 🎉🎉

**Comment by bhavesh-chaudhari** [comment]
> 
> 
> @bhavesh-chaudhari Assigning this to you, Happy Learning 🎉🎉

Thanks, I will try to finish this task by tommorow afternoon.

**Comment by bhavesh-chaudhari** [comment]
@Aryamanz29  this task has been completed. You can review the pull request now.
