### ISSUE TITLE
Pair : Data Structure

### ISSUE THREAD

**Issue by uditkatyal** [girlscript/winter-of-contributing#316]
Use of pairs, 
How to declare,
STL required for pair and its library functions

**Comment by Shruti-Subu** [comment]
can i try this?

**Comment by manishaag7** [comment]
Can I work on this? I use c++ so I am familiar with it.

**Comment by nik09877** [comment]
Can I work on this issue?
Nikhil Kumar Mishra
DSA Batch-3

**Comment by Ayushi2811** [comment]
would like to contribute on this topic and prepare a well structure documentation.Can u assign it to me?
Ayushi Chauhan
Batch-01

**Comment by pragatia-64U** [comment]
i can work on this issue. Can you assign it to me?

**Comment by vkaash-sharma** [comment]
i can work on this issue can you assign to me

**Comment by AkritiAgarwal09** [comment]
Hi I would like to contribute to this issue
Akriti Agarwal
CP batch -5
Serial No : 819

I can work with this issue
