### ISSUE TITLE
OpenSource : 5.1 Explain `Deploying to Netlify`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#317]
### Description :

- **Explain everything related to `Deploying to Netlify`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by uditkatyal** [comment]
pls assign this issue to me 
familiar with Netlify and its working.

**Comment by Aryamanz29** [comment]
@uditkatyal  Assigning this to you, Happy Documenting 🎉🎉

**Comment by uditkatyal** [comment]
Thank you sir!
