### ISSUE TITLE
DSA 2.2.17 KMP Algorithm

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#3170]
## Description
Give an introduction and explain the working of Knuth–Morris–Pratt algorithm.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by 101Priyanshi** [comment]
Name : Priyanshi Saxena 
Batch: 8

**Comment by Subhradeep10** [comment]
@101Priyanshi @ishivamgupta9 Not assigned to anyone of you, I had said already said don't do this
Now I have to speak with higher autority regarding this.

**Comment by cookieg13** [comment]
Hi! @Subhradeep10 I would love to work on this issue? can you please assign it to me?😊
Name: Debarati Ghatak
Batch: 3
Contribution type: Documentation

**Comment by Subhradeep10** [comment]
@cookieg13 Assigned to you

**Comment by cookieg13** [comment]
> @cookieg13 Assigned to you

Thank you!😁

**Comment by 101Priyanshi** [comment]
Hi @Subhradeep10, sorry for my previous mistake. I didn't know that we can't self assign. I would really like to contribute to this issue. Please give me a chance.
Name: Priyanshi Saxena
Batch: 8
Contribution type: Video

**Comment by Subhradeep10** [comment]
@101Priyanshi It's Okk, But don't do it from the next time . Assigned to @cookieg13 and @101Priyanshi

**Comment by pjdurden** [comment]
> Hi! @pjdurden I wanted to give an update, I am almost done with the documentation and I will be making the PR by today. I am really sorry for the delay.

no problem @cookieg13 , i have seen your pull request, i will merge it after it is reviewed by the mentor.

**Comment by cookieg13** [comment]
> no problem @cookieg13 , i have seen your pull request, i will merge it after it is reviewed by the mentor.
Thank you!! My PR has been reviewed by  mentor. 😊
