### ISSUE TITLE
DSA 2.2.20 Aho-Corasick Algorithm

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#3171]
## Description
Give an introduction and explain the working of Aho-Corasick algorithm.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by VanshikaSable** [comment]
Vanshika Sable batch-1- documentation

**Comment by aishapervin** [comment]
@pjdurden  assign me this issue

**Comment by 0xUvaish** [comment]
Assign this to me pls,
Name: Mohd Uvaish Siddiqui
Batch: 7
Task: Documentation

**Comment by Subhradeep10** [comment]
@aishapervin @0xUvaish Assigned to you

**Comment by aishapervin** [comment]
@Subhradeep10 i also had to do the documentation part,so plz clarify whether i am assigned the documentation part or not.Thankyou

**Comment by Subhradeep10** [comment]
@aishapervin You have to do only the documentation part

**Comment by mehabhalodiya** [comment]
@goelesha Pls assign this issue to @aishapervin @0xUvaish

**Comment by Subhradeep10** [comment]
@mehabhalodiya This issue is opened by Prajjwal Sir, not Esha Mam

**Comment by pranshukas** [comment]
@0xUvaish Are you sure because no one is currently assigned to this issue, that's why I requested for it. If possible please check with the mentors/supervisors.

**Comment by likitarai1** [comment]
@pjdurden I would like to work on this issue.
