### ISSUE TITLE
DSA 2.2.3 Monotonic functions

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#3172]
## Description
Give an introduction and explain the working of monotonic functions in the context of binary search and bisection method.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by eshan1925** [comment]
\assign

**Comment by eshan1925** [comment]
Please assign me this @pjdurden

**Comment by Subhradeep10** [comment]
@eshan1925 Not assigned to you, I have already said don't do this.
Now I have to talk with higher authourity to take strict action regarding this

**Comment by eshan1925** [comment]
> @eshan1925 Not assigned to you, I have already said don't do this.
> Now I have to talk with higher authourity to take strict action regarding this

Ok dont assign...wont ask again...

**Comment by eshan1925** [comment]
> > @eshan1925 Not assigned to you, I have already said don't do this.
> > Now I have to talk with higher authourity to take strict action regarding this
> 
> Ok dont assign...wont ask again...

Thankyou @Subhradeep10

**Comment by jaya6400** [comment]
Can I work on the document part @pjdurden @Subhradeep10 
Name - Jaya Dubey
Batch - 3

**Comment by Subhradeep10** [comment]
@jaya6400 Assigned to you, Go for it

**Comment by pjdurden** [comment]
@eshan1925 kindly dont abuse the assign bot. First submit pr for the open issues you have and then ask for new issues.

**Comment by eshan1925** [comment]
> @eshan1925 kindly dont abuse the assign bot. First submit pr for the open issues you have and then ask for new issues.

Already done....i was assigned to an issue whose PR was already merged...

**Comment by eshan1925** [comment]
By the way i dont want to get assigned to this issue for now😁
Thankyou
