### ISSUE TITLE
DSA 2.2.4 Bisection Method ( Binary search)

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#3173]
## Description
Give an introduction and explain the working of bisection method for root finding.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by VanshikaSable** [comment]
DSa batch 1-documentation

**Comment by debjitpal5040** [comment]
Debjit Pal, DSA Batch 1
Please assign me this issue. I want to do the documentation part.
