### ISSUE TITLE
Data Science with Python : Usage of get_dummies to create Dummy Variables with Pandas

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#3176]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Usage of get_dummies to create Dummy Variables with Pandas Tutorial to Usage of get_dummies to create Dummy Variables with Pandas and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Dhruv Bajaj / Kareem Negm

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ayushijindal** [comment]
/content/globalterrorismdb_0718dist.csv

**Comment by prathimacode-hub** [comment]
Bot says you have more than 3 open issues under you. Is it? @ayushijindal

**Comment by ayushijindal** [comment]
No

**Comment by prathimacode-hub** [comment]
It's still open as it's assigned to multiple contributors. So it can't be closed until all the persons assigned to that issue doesn't complete their PR. Issue assigned to @ayushijindal for documentation

**Comment by Shende-Ayush** [comment]
Approach : Using a dataset to explain the Usage of get_dummies to create Dummy Variables with Pandas
Format   :  Documentation
Serial No. : 695
Batch : 18
@prathimacode-hub my humble request for the allotment of  this issue

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-5. I would like to do audio on this issue.
Approach: A detail explanation with code

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
