### ISSUE TITLE
Data Science with Python : Data Cleaning

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#3177]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Data Cleaning. Tutorial to Data Cleaning and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Aishani Singh / Peehu Saxena

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do documentation on this issue.

**Comment by ayushi424** [comment]
Name: Ayushi Shrivastava
S No: 811
Approach to be followed:  
-  Documentation 
 - Proper code and explanation for a sample dataset with missing or null or inappropriate data values to clean and balance the dataset so that it can be used for data training & model creation.Also improve the performance of the project.

@prathimacode-hub Kindly assign :)

**Comment by prathimacode-hub** [comment]
You both are so active. This is done on contributors request. If not claimed, you both can choose. But priority goes to person who has asked for this issue. All issues created now are from requests. @ashish-reddy-20-08 @deepthi1107

**Comment by prathimacode-hub** [comment]
Issue assigned to @ayushi424 for documentation. You both can choose audio / video. @ashish-reddy-20-08 @deepthi1107

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , I will do video mam

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do audio on this issue.
my approach: a detail explanation .

**Comment by prathimacode-hub** [comment]
Ok. Issue assigned to @ashish-reddy-20-08 for video and @deepthi1107 for audio contribution.

**Comment by SaloniThete** [comment]
Name: Saloni Thete 
S.No: 821
Batch-19 
Type: Documentation
Approach: Provide Resources for data cleaning and steps to perform the process.
@prathimacode-hub Kindly assign :)
