### ISSUE TITLE
OpenSource : M.13_Deploying_to_heroku

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#318]
### Description :

- **Explain `Deploying projects to heroku`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by uditkatyal** [comment]
Hey pls, assign this issue.
deployed a couple of projects here.
thank you!

**Comment by manishaag7** [comment]
I would like to work on this issue!

**Comment by Aryamanz29** [comment]
> I would like to work on this issue!

@manishaag7 Sure , Happy Documenting 🎉

**Comment by Soumili1818** [comment]
May I have the honour of working on this issue, please?

**Comment by Aryamanz29** [comment]
@manishaag7  Any updates???

**Comment by Aryamanz29** [comment]
@Soumili1818  Assigning this to you, Happy docs 🎉🎉

**Comment by Aryamanz29** [comment]
@Soumili1818  Any updates ???

**Comment by Soumili1818** [comment]
> @Soumili1818 Any updates ???

Hello sir, since I already have 2 issues under me, kindly assign this one to the one in need, thanks a lot.

**Comment by Aryamanz29** [comment]
Sure @Soumili1818

**Comment by Shiitu** [comment]
I Would Like to work on this issue.

**Comment by Aryamanz29** [comment]
> I Would Like to work on this issue.

Sure , Assigning this to you

**Comment by mayankkuthar** [comment]
@Aryamanz29 If no one is working on this issue, I would like to contribute, Please Assign me the issue.

**Comment by Chirag-creator17** [comment]
yeah i also want to work on this issue i asked for it earlier also

**Comment by Aryamanz29** [comment]
> yeah i also want to work on this issue i asked for it earlier also

ok, Go ahead @Chirag-creator17

**Comment by Chirag-creator17** [comment]
ok thanks
