### ISSUE TITLE
OpenSource : 5.3 Compare `github-pages` vs `netlify`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#319]
### Description :

- **OpenSource : 5.3 Compare `github-pages` vs `netlify`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by anurag-b72** [comment]
Can I work on this ! @Aryamanz29

**Comment by Aryamanz29** [comment]
@anurag-b72 Assigning this to you, Happy doc 🎉🎉

**Comment by Soumili1818** [comment]
May I have the honour of working on this issue @Aryamanz29 ,please?

**Comment by Aryamanz29** [comment]
Removed assignment from @anurag-b72 (due to inactivity), Assigned to @Soumili1818, Happy docs 🎉🎉

**Comment by Aryamanz29** [comment]
@Soumili1818  Any updates on this ??

**Comment by Soumili1818** [comment]
> @Soumili1818 Any updates on this ??

Yes im working on rhe project, thank you for your concern.

**Comment by mayankkuthar** [comment]
@Aryamanz29  would like to work on this Issue Please Assign me.

**Comment by Aryamanz29** [comment]
@mayankkuthar  Assigning this to you , Since @Soumili1818  (Inactivity)
