### ISSUE TITLE
DSA 2.2.2 Linear Search & Binary Search

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#3193]
## Description
Give an introduction and explain the working of Linear Search & Binary Search, and compare them in terms of their complexities

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by divya1467** [comment]
I would like to work on this issue
Divya (DSA batch-5)

**Comment by divya1467** [comment]
I would like to work on the documentation 
Divya (DSA batch-5)

**Comment by palsahabmalviyan** [comment]
@Sarthak-Agg  sir, please review this pull request..
