### ISSUE TITLE
Visualization using Seaborn 

### ISSUE THREAD

**Issue by Shende-Ayush** [girlscript/winter-of-contributing#3197]
### Description

I will be creating documentation regarding Visualization Using Seaborn Functions it contains Functions such as Imlot , relplot , Scatterplot , catplot, heatmap , etc.

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment]
This issue is already done. Don't create issues and self assign yourself. @Shende-Ayush
