### ISSUE TITLE
DSA 2.2.2.1 Ternary search

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#3198]
## Description
Give an introduction and explain the working of Ternary search, both iterative and recursive methods

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by brassgolem-25** [comment]
@Sarthak-Agg Assign me this issue
Name - Tushar Tiwari
Batch - #6

**Comment by WajihaFatim** [comment]
@Sarthak-Agg where i have to create my file like my file name is 2.2.2.1 .I am unable to understand.Sir ,please tell me

**Comment by WajihaFatim** [comment]
@Sarthak-Agg sir ,please review ,I have done my part

**Comment by Sarthak-Agg** [comment]
good job @WajihaFatim

**Comment by WajihaFatim** [comment]
Thank you sir, can you close the issue so that I can work on more
