### ISSUE TITLE
OpenSource : 3. Blog what you do and be more social

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#32]
### Description :

Blogging is a very good approach to build an audience for your open source projects. `Introducing your projects` and writing `how-to-type blog posts` would be nice for **your future community.**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  

## Happy Contributing 🙌

**Comment by Ash-KODES** [comment]
ok,I would like to contribute for this issue.
opensource batch 3
thankyou

**Comment by Aryamanz29** [comment]
@Ash-KODES  Assigning this to you ✌️

**Comment by paras-saxena11** [comment]
Hey, I want to start contributing how to do start?

**Comment by Ash-KODES** [comment]
hey paras,glad to see that you want to contribute
follow these steps:-
1.search a issue that belong to your domain or tech stack
2.claim the issue
3.start contributing
:)

> Hey, I want to start contributing how to do start?

**Comment by Ash-KODES** [comment]
mentor,please review my changes @Aryamanz29
