### ISSUE TITLE
OpenSource : 5.4 Explain `Firebase Hosting`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#320]
### Description :

- **5.4 Explain `Firebase Hosting`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by arsheelsheikh** [comment]
Hi, Can I work on this issue?

**Comment by Aryamanz29** [comment]
@arsheelsheikh  Assigning this to you, Happy docs 🎉🎉

**Comment by Aryamanz29** [comment]
@arsheelsheikh  Any updates ????

**Comment by Aryamanz29** [comment]
Unassign @arsheelsheikh  Due to inactivity

**Comment by mayankkuthar** [comment]
@Aryamanz29 I would like to work on this, Please Assign me.

**Comment by Aryamanz29** [comment]
@mayankkuthar  Go ahead 🙌
