### ISSUE TITLE
2.2.5 Counting Sort & Radix Sort 

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#3204]
## Description
Give an introduction and explain the working of Counting Sort and its complexity, Radix sort and its usage and complexity and how it uses counting sort as a subroutine to sort, and its applications

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ShivaniPaliwal29** [comment]
/assign
Shivani Paliwal
dsa-batch-4

**Comment by Sarthak-Agg** [comment]
@ShivaniPaliwal29  have made your contribution to this issue?
