### ISSUE TITLE
2.2.5 Pigeonhole Sort

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#3211]
## Description
Give an introduction and explain the working of Pigeonhole Sort, its complexity and also explain how it is different from counting sort,

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by aishapervin** [comment]
@Sarthak-Agg plz assign me this issue

**Comment by aishapervin** [comment]
@Sarthak-Agg plz close this issue,now that it is merged.I am not able to take up new issues.Thankyou.
