### ISSUE TITLE
2.2.5 Bitonic Sort

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#3213]
## Description
Give an introduction and explain the working of Bitonic Sort, its use cases and its complexity 

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by brassgolem-25** [comment]
Name - Tushar Tiwari
Batch - 6

**Comment by 7sakshi7** [comment]
Name - Sakshi Agarwal
Batch - 10

**Comment by soma2000-lang** [comment]
/assign
Name-Somasree Majumder
batch -1

**Comment by Sarthak-Agg** [comment]
@soma2000-lang  have made your contribution?

**Comment by soma2000-lang** [comment]
I will be doing it by tonight
