### ISSUE TITLE
2.2.5 Binary Insertion Sort

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#3214]
## Description
Give an introduction and explain the working of Binary Insertion Sort, using both iterative and recursive approach, and its complexity

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Nay907** [comment]
Name- Nayanika Mishra
Batch- 9

**Comment by 7sakshi7** [comment]
Name : Sakshi Agarwal
Batch : 10

**Comment by Sarthak-Agg** [comment]
who is willing to make a contribution to this issue ?
@WajihaFatim  @Nay907  @7sakshi7

**Comment by Nay907** [comment]
I want to contribute to this issue @Sarthak-Agg

**Comment by 7sakshi7** [comment]
yes..I am
