### ISSUE TITLE
OpenSource : 5.5 Explain everything related to `Amazon S3`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#322]
### Description :

- **Explain everything related to `Amazon S3`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by geeythree** [comment]
I'd like to work on this. Can you please assign this issue to me?

**Comment by Aryamanz29** [comment]
> I'd like to work on this. Can you please assign this issue to me?

Sure @geeythree , Happy Documenting 🎉🎉

**Comment by harshi606** [comment]
I would love to work on this issue ! Can I also contribute here ?

**Comment by Aryamanz29** [comment]
@geeythree Any updates?????

**Comment by geeythree** [comment]
@Aryamanz29 Hi, I'm sorry for the delay. I'll make a PR by today evening.
