### ISSUE TITLE
C_CPP: POLICY BASED DATA STRUCTURES

### ISSUE THREAD

**Issue by yogeshkumar-1234** [girlscript/winter-of-contributing#3234]
### Description

This documentation will include policy based data structure along with it's functions.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged
