### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(2.4)->What is Property Binding?

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#3235]
### Description

**Description**
- What is property binding?
- How it works?
- Difference between property binding and interpolation.
- How to bind directive property?
- Brief about property binding among components.
- Explain with code snippets/syntax.
- Reference :- https://angular.io/guide/property-binding
(Week-2 Issue)

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week2" directory
3. Tasks would be assigned on First Come First Serve Basis.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RIYANSHGARG** [comment]
I would like to work on it. kindly assign it to me.

**Comment by RIYANSHGARG** [comment]
I have added the pull request, Kindly review it.
