### ISSUE TITLE
OpenSource : 5.6 Explain everything related to `gitlab-pages`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#324]
### Description :

- **Explain everything related to `gitlab-pages`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by uditkatyal** [comment]
pls assign this to me

**Comment by Ash-KODES** [comment]
I would like to contribute for this issue!
opensource batch batch 3
thankyou

**Comment by Aryamanz29** [comment]
@Ash-KODES Assigning this to you , Happy Documenting 🎉

**Comment by Aryamanz29** [comment]
@Ash-KODES  Any updates????

**Comment by Ash-KODES** [comment]
yes mentor,I am on it!

**Comment by Ash-KODES** [comment]
mentor,please review my code:)

**Comment by Ash-KODES** [comment]
sir,please assign me some new issue!
