### ISSUE TITLE
Quick Notes/ Cheat Sheet -> SQL

### ISSUE THREAD

**Issue by singhnikhiljsr** [girlscript/winter-of-contributing#3240]
### Description

A crisp and concise revision sheet to refer to while preparing for the Interview!
-> Inbuilt functions
-> Important concepts

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by syedareehaquasar** [comment]
Go ahead looks good!
