### ISSUE TITLE
Reference Variables in C++ - Documentation

### ISSUE THREAD

**Issue by kashyap1905** [girlscript/winter-of-contributing#3243]
### Description

Points to be discussed in documentation -

- What are Reference Variables
- Difference between Referance and Address of a Variable
- Declaration syntax and rules for a Reference Variable
- Reference Variables and Ampersand Operators
- Difference between Pointers and Reference Variables
- Usage of Reference Variables
- Examples and Code Snippets

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Clsoing as the PR got merged
