### ISSUE TITLE
[Frontend with HTML,CSS,JS]: HTML LIST

### ISSUE THREAD

**Issue by samipak458** [girlscript/winter-of-contributing#3245]
### Description

What is List ?
Types Of List
1)Ordered List
2)Unordered List

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : [Frontend with HTML,CSS,JS]: HTML LIST
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-3245
Contribution Approaches-what is a list, why do we need lists, types of lists-ordered,unordered
Type-Audio
