### ISSUE TITLE
DSA : Recursion using Tower of Hanoi

### ISSUE THREAD

**Issue by priyashajain** [girlscript/winter-of-contributing#3247]
### Description

I will submit the documentation on the topic Recursion using Tower of Hanoi, where I will explain the concept of recursion, and its step by step working through Tower of Hanoi problem.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sameer-19** [comment]
Sameer Aggrawal
Batch-3 DSA
Documentation
Please assign this problem to me. I would like to solve this problem.

**Comment by priyashajain** [comment]
Can I work on this issue?

**Comment by priyashajain** [comment]
Will it be considered as an open issue?

**Comment by priyashajain** [comment]
Priyasha Jain
DSA Batch-7
Documentation
Can I still work on this issue?

**Comment by priyashajain** [comment]
Name- Priyasha Jain
Batch - DSA-7
I would like to work on this issue in documentation format. Please assign this issue to me.
Thank you!

**Comment by nimisha-yadav** [comment]
> Name- Priyasha Jain Batch - DSA-7 I would like to work on this issue in documentation format. Please assign this issue to me. Thank you!

You can work on this issue and it is already assigned to you, all the best @priyashajain

**Comment by priyashajain** [comment]
Thank you!

**Comment by mrkc2303** [comment]
@nimisha-yadav Is this issue available for the Video section, I would like to work on it?

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav Is this issue available for the Video section, I would like to work on it?

Yeah, go ahead @mrkc2303
