### ISSUE TITLE
OpenSource : 5.7 Compare `github` vs `gitlab` vs `bit bucket`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#325]
### Description :

- **Compare `github` vs `gitlab` vs `bit bucket`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by mayankkuthar** [comment]
Can I work on this one?

**Comment by Aryamanz29** [comment]
@mayankkuthar Assigning this to you , Happy docs 🎉🎉
