### ISSUE TITLE
DSA 1.2.2.2 Algorithms: Lower and Upper bounds - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3256]
## Description
Discuss Asymptotic Notations. What are Lower and Upper bounds? Describe their usages.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by shahhilag** [comment]
Respected Sir,
I would like to work on this issue.
I am Hilag Shah from DSA batch 1

**Comment by nimisha-yadav** [comment]
> 
> 
> Name - Hilag Shah Batch - DSA batch 1 @nimisha-yadav Please assign this issue to me

Assigning this issue to you @shahhilag, all the best!

**Comment by shahhilag** [comment]
> > Name - Hilag Shah Batch - DSA batch 1 @nimisha-yadav Please assign this issue to me
> 
> Assigning this issue to you @shahhilag, all the best!

Thankyou very much mam.I have created a pull request mam.Your review will help me improve.

**Comment by shahhilag** [comment]
@nimisha-yadav mam I have created a new pull request.Thankyou for helping me out and sorry this is my first contribution thus wasted a lot of your time.

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav mam I have created a new pull request.Thankyou for helping me out and sorry this is my first contribution thus wasted a lot of your time.

It's completely okay, this is the purpose of this program. Well done for first contribution :D

**Comment by shahhilag** [comment]
> > @nimisha-yadav mam I have created a new pull request.Thankyou for helping me out and sorry this is my first contribution thus wasted a lot of your time.
> 
> It's completely okay, this is the purpose of this program. Well done for first contribution :D

Thankyou very much @nimisha-yadav mam.Your support and guidance truely will help me grow a lot.

**Comment by shahhilag** [comment]
Thankyou mam:)
