### ISSUE TITLE
DSA 1.2.2.4 Recurrence Relations: Recursion Tree Method - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3258]
## Description
How can you solve recurrences using Recursion Tree Method?

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by nimisha-yadav** [comment]
Send in your full name and DSA batch number. @purohitmansi

**Comment by purohitmansi** [comment]
> Send in your full name and DSA batch number. @purohitmansi



> Send in your full name and DSA batch number. @purohitmansi

Name: Mansi Rajpurohit
Batch: 4

**Comment by nimisha-yadav** [comment]
> Name: Mansi Rajpurohit Batch: 4

Assigning this issue to you, all the best!
