### ISSUE TITLE
DSA 2.1 Implementation of Strings in Java - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3261]
## Description
How are strings implemented in Java? Discuss string class, string length.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by afreenabegum** [comment]
Hi mam @nimisha-yadav .I want to work on this issue. Can you assign it to me?
Helpful if you assign to me!!
Thank you.

**Comment by nimisha-yadav** [comment]
> 
> 
> Hi mam @nimisha-yadav .I want to work on this issue. Can you assign it to me? Helpful if you assign to me!! Thank you.
> 
> Afreena begum Batch-1,DSA.

Assigning this to you, all the best!

**Comment by afreenabegum** [comment]
@nimisha-yadav thank you mam.
I'll give my best.

**Comment by afreenabegum** [comment]
> Yeah I understand but that is the way of contribution in audio format, one of the contributor [did it like this](https://drive.google.com/file/d/19A7UNgOB5N6QmYobgikBryUYrbZ2EkOb/view?usp=drivesdk). Either you may do it this way or you can create a ppt with your voice in the background of slides. That will also work. @afreenabegum 

Ok mam. I'll do it . 
Thank you.
