### ISSUE TITLE
DSA 1.1.3.5 Arrays: Suffix Array - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3263]
## Description
Explain the construction and applications of Suffix Array.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by nimisha-yadav** [comment]
> 
> 
> Please do assign this to me.

Okay, send in your full name and DSA batch number. @purohitmansi

**Comment by purohitmansi** [comment]
> > Please do assign this to me.
> 
> Okay, send in your full name and DSA batch number. @purohitmansi

Name: Mansi Rajpurohit
Batch: 4

**Comment by nimisha-yadav** [comment]
> Name: Mansi Rajpurohit Batch: 4

Assigning this issue to you, all the best!
