### ISSUE TITLE
DSA 2.1 Implementation of Strings in Python - Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3264]
## Description
How are strings implemented in Python? Discuss with examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav Mam. I would like to work on this issue. (video)
> 
> Harsh Kumar Batch -6, DSA

Assigning this issue to you @harsh827, all the best!

**Comment by harsh827** [comment]
@nimisha-yadav  .Before making a pull request, I wanted to confirm my doubt

1.  is location where file to be added  correct ? = 
 `winter-of-contributing/DSA/2.1 Strings/3. Implementation in Java, Python/`
