### ISSUE TITLE
DSA 2.1 Implementation of Strings in Python - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3266]
## Description
How are strings implemented in Python? Discuss with examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by rajmadhu0406** [comment]
Please assign this issue to me.
Raj Madhu
DSA Batch - 6

**Comment by nimisha-yadav** [comment]
> Please assign this issue to me. Raj Madhu DSA Batch - 6

Assigning this issue to you, all the best!

**Comment by nimisha-yadav** [comment]
> Please assign this issue to me. Raj Madhu DSA Batch - 6

@rajmadhu0406 any update?

**Comment by nimisha-yadav** [comment]
@rajmadhu0406 final call. Submit PR within 2 days else the issue will be closed.

**Comment by jaigora24** [comment]
@nimisha-yadav mam assign this to me
Name - Jai Gora
Batch - 7
