### ISSUE TITLE
2.1 Strings - Rabin-Karp Algorithm - Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3268]
## Description
Discuss the Rabin-Karp Algorithm. Mention about its implementation, complexity, examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by likitarai1** [comment]
@nimisha-yadav  Can I work on this issue? 
Likita Rai - DSA batch 2

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav Can I work on this issue? Likita Rai - DSA batch 2

Assigning this issue to you @likitarai1, all the best!

**Comment by likitarai1** [comment]
Will you add Hacktoberfest label to this?

**Comment by likitarai1** [comment]
@nimisha-yadav please review my PR #5225
