### ISSUE TITLE
2.1 Strings - Rabin-Karp Algorithm - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3269]
## Description
Discuss the Rabin-Karp Algorithm. Mention about its implementation, complexity, examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by divya1467** [comment]
Can you please assign this to me
Divya(DSA batch-5)

**Comment by dhruti29** [comment]
I would like to work on this issue.
Dhruti Gandhi
Batch - 2

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-7
Contribution type: documentation

**Comment by nishant-jhaa** [comment]
assign to me 
Name- Nishant Jha
batch-8

**Comment by 0xUvaish** [comment]
Assign to me pls
Name - Mohd Uvaish Siddiqui
Batch - 7

**Comment by nimisha-yadav** [comment]
> 
> 
> Can you please assign this to me Divya(DSA batch-5)

Assigning this issue to you @divya1467, all the best!

**Comment by divya1467** [comment]
> > Can you please assign this to me Divya(DSA batch-5)
> 
> Assigning this issue to you @divya1467, all the best!

Thanks!
