### ISSUE TITLE
2.1 Strings - Rabin-Karp Algorithm - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3270]
## Description
Discuss the Rabin-Karp Algorithm. Mention about its implementation, complexity, examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by cookieg13** [comment]
Hi! I would love to work on this issue? can you please assign it to me?
Name: Debarati Ghatak
Batch: 3
Contribution type: Documentation

**Comment by nimisha-yadav** [comment]
> Mandeep Kaur DSA batch 5

@mandeep168 Any update?

**Comment by mandeep168** [comment]
I am sorry, I will not be able to contribute.  Please unassign me.

**Comment by Elisha-s** [comment]
Can you please tell me the last date to make the final PRs?  @nimisha-yadav

**Comment by nimisha-yadav** [comment]
> Can you please tell me the last date to make the final PRs? @nimisha-yadav

30 November but try to wrap up things by 20 Nov so we can get time for review. @mandeep168

**Comment by nimisha-yadav** [comment]
> Can you please tell me the last date to make the final PRs? @nimisha-yadav

30 November but this issue has been assigned to you since 2 weeks so try to wrap it up within one week or sooner. @Elisha-s
