### ISSUE TITLE
2.1 Strings - Manacher's Algorithm - Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3271]
## Description
Discuss Manacher's Algorithm and its significance. Mention about its implementation, complexity, and examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by shahhilag** [comment]
I would like to work on this issue.
Name- Hilag Shah 
Batch-DSA Batch 1

**Comment by shahhilag** [comment]
Thankyou very much @nimisha-yadav mam

**Comment by shahhilag** [comment]
Sorry @nimisha-yadav mam due to some issues I would not be able to complete the task.I hope you would understand.
