### ISSUE TITLE
2.1 Strings - Manacher's Algorithm - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#3273]
## Description
Discuss Manacher's Algorithm and its significance. Mention about its implementation, complexity, and examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by shahhilag** [comment]
@nimisha-yadav I would like to work on this issue.
Name-Hilag Shah
Batch - DSA Batch 1

**Comment by Sumit3301** [comment]
@nimisha-yadav  I would like to take up this issue
Kindly assign this issue to me
