### ISSUE TITLE
DSA 2.2.7 Searching & Sorting Algorithms : Insertion Sort - Video

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3299]
### Description
Implement and explain Insertion sort Algorithm

## Task
- [ ] Audio
- [ ] Video
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Apoorv-17** [comment]
I would like to work on this issue.
Name: Apoorv Yadav
Batch: 7
Type: Documentation
Approach: Introduction, Algorithm, Working of the algo, Time and Space complexity and at last implementation of insertion sort.

**Comment by goelesha** [comment]
@Apoorv-17 This issue is for video.

**Comment by Apoorv-17** [comment]
I thought that because documentation was also listed in the task list. Anyways, I would like to work on this issue with task type as Video.
Name: Apoorv Yadav
Batch: 7
Type: Video
Approach: Introduction, Algorithm, Working of the algo, Time and Space complexity and at last implementation of insertion sort.

**Comment by goelesha** [comment]
@Apoorv-17 Assigning the issue to you for video.
Make sure to submit a PR within 7 days

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by Apoorv-17** [comment]
@goelesha my PR has been accepted for this issue but still the issue is opened and it also doesn't shows PR request merged in this thread. Could you please check.

**Comment by goelesha** [comment]
@Apoorv-17 No problem in that. Your PRs will be counted at the end.
