### ISSUE TITLE
DSA 2.2.8 Searching & Sorting Algorithms : Bubble Sort - Video

### ISSUE THREAD

**Issue by goelesha** [girlscript/winter-of-contributing#3301]
### Description
Implement and explain Bubble sort Algorithm

## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sirilalithaadapa** [comment]
Siri Lalitha
Batch -07
Type : Documentation

**Comment by Eswari-Priya** [comment]
/assign 
i am eswari priya from dsa batch2. i'd like to contribute to this issue via documentation. pls assign me this issue. @pjdurden

**Comment by goelesha** [comment]
@Eswari-Priya Pls read the title of the issue carefully. This issue if for video, not for documentation.
You can go ahead and work on the video.

**Comment by rohit-goyal** [comment]
Hello My name is Rohit Goyal 
I would like to work on Documentation Part of this issue
I am from DSA Batch-2

**Comment by triptic1412** [comment]
Hello, I'm Tripti
DSA Batch 1
I would like to work on the video

**Comment by goelesha** [comment]
@rohit-goyal The issue is for the video.
@triptic1412 Assigning the issue to you for the video. Make sure to submit a PR within 7 days.

**Comment by triptic1412** [comment]
> @rohit-goyal The issue is for the video. @triptic1412 Assigning the issue to you for the video. Make sure to submit a PR within 7 days.

Yeah sure, thank you

**Comment by triptic1412** [comment]
@goelesha ma'am kindly review my PR. Since I'm a beginner, so if anything wasn't done right, you can let me know, I'll make the required changes.
