### ISSUE TITLE
Frontend With Angular: What is Angular and Why Angular?

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#331]
- What is Angular?
- Why Angular?
- Features?
- Its Advantages?
- Disadvantages?

 Note:-

1.  Don't even think about copy pasting we after reviewing would be merging the PR.
2.  Changes should be made inside "**Frontend_Web_Development_React_Angular_Vue/Angular**" directory
3.  Tasks would be assigned on First Come First Serve Basis.

**Comment by RIYANSHGARG** [comment]
I would Like to solve this issue. Please assign it to me

**Comment by mukeshmjn** [comment]
@RIYANSHGARG sure mate! Go for it :)

**Comment by RIYANSHGARG** [comment]
I have to create a folder named Frontend_Web_Development_React_Angular_Vue/Angular and then create a readme file in it to start writing content ?

**Comment by mukeshmjn** [comment]
> I have to create a folder named Frontend_Web_Development_React_Angular_Vue/Angular and then create a readme file in it to start writing content ?

No, it's the directory you need not to create a folder. If you are posting written content the just create a .md file and start working! File would be added into Frontend_Web_Development_React_Angular_Vue/Angular directory!

**Comment by RIYANSHGARG** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/74728397/133723295-f847b0e8-c5a9-4b53-bf7c-ce36b1045319.png)
Can you please help me out what is wrong here and how to correct it ?

**Comment by RIYANSHGARG** [comment]
I have add a Pull request, Please Consider it.

**Comment by RIYANSHGARG** [comment]
I have re-added the pull request, Please considered it.

**Comment by anandhu720** [comment]
@RIYANSHGARG bro your pr is closed,before making pr please read the instructions we given,please make sure you obyed all of our instruction and make a new pr.

**Comment by RIYANSHGARG** [comment]
I have added the pull request, Please consider it.
