### ISSUE TITLE
JS: Async/Await

### ISSUE THREAD

**Issue by Moeen-Ul-Islam** [girlscript/winter-of-contributing#3310]
> **Outdated!** Move to #721 .

## Description

> Please describe here.

## Directory
```
Topics/Async_Await
```

### Domain

JavaScript

### Type of Contribution

- [ ] Documentation
- [ ] Video
- [ ] Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by cenacrharsh** [comment]
Just to be sure, I am a part of Frontend with html/css/js domain, I can work on this one right ??

**Comment by daminimehra** [comment]
@paramsiddharth pls assign this issue. I would like to work on this issue.

**Comment by Moeen-Ul-Islam** [comment]
> Just to be sure, I am a part of Frontend with html/css/js domain, I can work on this one right ??  @Moeen-Ul-Islam

Yes you can do that!

**Comment by paramsiddharth** [comment]
@cenacrharsh Hey! Pardon for the delay in reply. I think you might not be eligible to work for this issue unless you are a registered contributor for the JavaScript domain. FEWD contributors can only work on JavaScript issues pertaining to the FEWD branch.

**Comment by cenacrharsh** [comment]
> @cenacrharsh Hey! Pardon for the delay in reply. I think you might not be eligible to work for this issue unless you are a registered contributor for the JavaScript domain. FEWD contributors can only work on JavaScript issues pertaining to the FEWD branch.

Ok then unassign me as I am not a part of Js domain, I belong to FEWD domain.

**Comment by paramsiddharth** [comment]
@Moeen-Ul-Islam @daminimehra Please tag #721 in your PRs, not this issue. It is duplicate, to be closed.
