### ISSUE TITLE
Cybersecurity 4.1 Symmetric Cryptography

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#3319]
### Description

Description

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
> Hey, assign this to me pls, Name: Mohd Uvaish Siddiqui Batch: 1 Type: Documentation

Assigned!

**Comment by Anant1711** [comment]
@0xUvaish When you are going to submit your work?

**Comment by 0xUvaish** [comment]
Sorry for the delay. Within 2 days I'll complete it

**Comment by 0xUvaish** [comment]
@Anant1711 I made a PR. Is there anything else to do?

**Comment by Anant1711** [comment]
> @Anant1711 I made a PR. Is there anything else to do?
