### ISSUE TITLE
Cybersecurity 4.2 Asymmetric cryptography

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#3321]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by 0xUvaish** [comment]
Hey, assign this to me pls,
Name: Mohd Uvaish Siddiqui
Batch: 1
Type: Documentation

**Comment by Anant1711** [comment]
> Hey, assign this to me pls, Name: Mohd Uvaish Siddiqui Batch: 1 Type: Documentation

One task at a time

**Comment by 0xUvaish** [comment]
ok, but I haven't been assigned any task yet

**Comment by Anant1711** [comment]
> ok, but I haven't been assigned any task yet

Check symmetric one

**Comment by 0xUvaish** [comment]
OK

**Comment by pragmatic-philosopher09** [comment]
Hi, can I take this up under documentation? I've unassigned myself from the previous task of creating a virus...

**Comment by Anant1711** [comment]
> Hi, can I take this up under documentation? I've unassigned myself from the previous task of creating a virus...

Okay
