### ISSUE TITLE
Cybersecurity 4.4 RSA

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#3323]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by medhatiwari** [comment]
Hey, I would like to work on this. Please assign this to me.

**Comment by Anant1711** [comment]
> Hey, I would like to work on this. Please assign this to me.
> `Documentation`

assigned!

**Comment by Anant1711** [comment]
@medhatiwari When are you going to submit your work?

**Comment by medhatiwari** [comment]
> @medhatiwari When are you going to submit your work?

Today Only. I am really for the delay

**Comment by Anant1711** [comment]
> > @medhatiwari When are you going to submit your work?
> 
> Today Only. I am really for the delay

Okkayyy!

**Comment by SwarnaliBhunia** [comment]
sir I would submit by today itself.
