### ISSUE TITLE
Open Source: 4.20 explain everything related to SWOC(Script Winter Of Code)

### ISSUE THREAD

**Issue by iamsunil25** [girlscript/winter-of-contributing#3325]
### Description

in this issue you have to Explain everything related to SWOC(Script Winter Of Code) 

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ELLIPSIS009** [comment]
@iamsunil25 @Aryamanz29 can you assign me this manually, the bot cant because i am currently dont have any issue but the previous issue are not yet closed by the respective mentors/supervisors

**Comment by iamsunil25** [comment]
@ELLIPSIS009 i am just contributor i can't assign

**Comment by iamsunil25** [comment]
@ELLIPSIS009 i am just contributor i can't assign

**Comment by ShivaniAgarwal2001** [comment]
@Aryamanz29 review and merge the PR #5001
