### ISSUE TITLE
C_CPP : Shallow copy and Deep copy in C++

### ISSUE THREAD

**Issue by vartikavr** [girlscript/winter-of-contributing#3347]
### Description

Documentation on <b>Shallow copy and Deep copy</b> in C++.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR is merged !
