### ISSUE TITLE
bitwise operators

### ISSUE THREAD

**Issue by Akshat-2002-coder** [girlscript/winter-of-contributing#3359]
### Description

Give a brief description of different bitwise operators.
also explain some bitwise techniques 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as #3969 got merged !
