### ISSUE TITLE
Open Source: Explain Everything Related To Script Winter of Code 

### ISSUE THREAD

**Issue by Varun270** [girlscript/winter-of-contributing#3366]
### Description

Description

Prepare documentation related to Script Winter of Code

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Varun270** [comment]
@Aryamanz29 I would like to work on this issue and can you please tell me what serial number should I put over the doc and issue name?

**Comment by ShivaniAgarwal2001** [comment]
This issue was already been created. Kindly check it @Aryamanz29 and @Kajol-Kumari . I requested to close it.
Check #3325

**Comment by Varun270** [comment]
@ShivaniAgarwal2001  I had opened this issue first, I assume the guy who opened this issue was not aware of the fact.

**Comment by Varun270** [comment]
@ShivaniAgarwal2001 Sorry, I just noticed the serial number mine was created later, it was a coincidence. I am closing this issue you can work on the issue it's all yours now. Happy Contributing and again sorry for the inconvenience caused.

**Comment by ShivaniAgarwal2001** [comment]
> @ShivaniAgarwal2001 Sorry, I just noticed the serial number mine was created later, it was a coincidence. I am closing this issue you can work on the issue it's all yours now. Happy Contributing and again sorry for the inconvenience caused.

No worries, you can create another issue and work on it, or wait for the Mentor to create one!
