### ISSUE TITLE
[ JAVA ]: final keyword in java 

### ISSUE THREAD

**Issue by vishnu95075** [girlscript/winter-of-contributing#3368]
### Description

# Final keyword in java 
- Java final Variable
- Java final Method
- Java final Class

### Domain

Backend Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by tamalbag117** [comment]
\assign Audio
