### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(2.5) -> What is Event Binding?

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#3392]
### Description

- What is Event Binding?
- How it works?
- How it is different from Property Binding?
- How to customise event binding?
- Explain with code snippets
- Reference :- https://angular.io/guide/event-binding
(Week 2 Issue)

Note:-

1. Don't copy paste, we would be merging  after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week2" directory
3. Tasks would be assigned on First Come First Serve Basis.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by LegendSumeet** [comment]
Assign me /assign

**Comment by LegendSumeet** [comment]
@koshimagoyal assign meee

**Comment by mukeshmjn** [comment]
Done @LegendSumeet go for it!

**Comment by mukeshmjn** [comment]
@LegendSumeet any updates over this?

**Comment by LegendSumeet** [comment]
Yes it's will done till tomorrow with PR @mukeshmjn

**Comment by uniquenikki** [comment]
assign me/assign

**Comment by mukeshmjn** [comment]
@LegendSumeet status?..its been two more days now

**Comment by LegendSumeet** [comment]
Yeah today It's done just Add images today I will raise the PR @mukeshmjn

**Comment by mukeshmjn** [comment]
@LegendSumeet u have time till today ..otherwise i will reassign

**Comment by LegendSumeet** [comment]
ohk @mukeshmjn

**Comment by LegendSumeet** [comment]
https://github.com/girlscript/winter-of-contributing/pull/4172
review it
