### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(2.6) -> What is Two Way Data Binding? 

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#3398]
### Description

- What is Two Way Data Binding?
- How it is different from One Way Data Binding?
- How it works?
- How it is implemented in forms?
- Explain with code snippets/syntax.
- Reference :- https://angular.io/guide/two-way-binding
(Week 2 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week2" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by LegendSumeet** [comment]
assign me
@koshimagoyal

**Comment by LegendSumeet** [comment]
@koshimagoyal assign me my fav topic mam plz .......

**Comment by RIYANSHGARG** [comment]
I would like to work on this issue kindly assign it to me.
/assign

**Comment by RIYANSHGARG** [comment]
I have created a pull request @koshimagoyal  kindly review it .
