### ISSUE TITLE
Frontend: Collecting HTML form response in Google Sheets

### ISSUE THREAD

**Issue by arpanaditya** [girlscript/winter-of-contributing#341]
I'd like to explain here how we can collect HTML form responses in Google Sheets and managing them.
Please assign it to me @praveenscience

**Comment by WhiteBear1611** [comment]
I would also like to work on this issue via documentation

**Comment by AnuragSomani1611** [comment]
I would also like to work on this issue via documentation

**Comment by rohangilbile123** [comment]
I would like to work on this issue

**Comment by FirdausJawed** [comment]
I want to contribute with documentation. Please assign it to me !!

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.Please consider me for this..
Riya Pandey
Batch-2

**Comment by Drontitan** [comment]
@praveenscience pls check my issue

**Comment by Drontitan** [comment]
close this issue its already merge
