### ISSUE TITLE
C_CPP: Access Specifiers in Classes

### ISSUE THREAD

**Issue by Pranshu321** [girlscript/winter-of-contributing#3414]
### Description

In this topic i give detail explanation of access specifiers used in the classes in this i talk about the public,private and protected specifiers how,when,why they are used in classes.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged
