### ISSUE TITLE
Python: 2.1 Basic Datatypes of Python

### ISSUE THREAD

**Issue by nakshatra-garg** [girlscript/winter-of-contributing#342]
Description :
Briefly explain Basic Datatypes of Python with some examples.
Note :
Changes should be made inside the Python/ directory & Python branch.
Issue only for GWOC'21 contributors.
The issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.
In the PR, keep this issue's title as your PR's title.
Must-Follow: Contributing Guidelines & Code of Conduct before start Contributing.
@adityabisoi

**Comment by GopinathBalaji** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by lohith1392** [comment]
Can I work on this issue

**Comment by lohith1392** [comment]
Documentation

**Comment by WhiteBear1611** [comment]
I would like to make a documentation/video over this issue

**Comment by Yukti-20** [comment]
I can make well-formatted and well-designed documentation and video on this issue @nakshatra-garg . May I do this?

**Comment by nakshatra-garg** [comment]
I already opened a pull request I've worked on documentation for this issue

**Comment by AnuragSomani1611** [comment]
I would like like work on this issue via Video

**Comment by nayakaj** [comment]
i want to work on this

**Comment by harshithapasupuleti** [comment]
I would like to work on this (Documentation)

**Comment by adityabisoi** [comment]
This issue has already been covered in https://github.com/girlscript/winter-of-contributing/issues/245
