### ISSUE TITLE
MERN_Express: 2.1 Send HTML & JSON Data as a Response

### ISSUE THREAD

**Issue by hardikk2002** [girlscript/winter-of-contributing#3422]
### :pushpin:  Minimum points to be covered.

- How to send Data as response on `.get("/", call_back)`.
- Send HTML  Tag & JSON Data as a Response.
       - Difference between `res.write() and res.send() and res.json()`.
- What is `Status Code`, how to set it.
- What is `content-type`, and what client expect, in different content type, header. 
       - Example, for `res.json() -> application/JSON`
- Small example
       - "/" send HTML tags
       - "/about" send your info in JSON format

### :file_folder:  Project Directory
Branch MERN>MERN/Topic/Backend/Express/

### :paintbrush: Filename
2.1_Send_HTML_&_JSON_Data_as_a_Response(D).md

## Happy Contributing :partying_face::raised_hands:

---
Doubt? Reach me on Discord.

### Domain

MERN

### Type of Contribution

Documentation

EDIT: MERN , Documentation for Labels.
### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aishapervin** [comment]
@hardikk2002 plz assign me this issue

**Comment by hardikk2002** [comment]
> @hardikk2002 plz assign me this issue

@aishapervin You can't work on more than 3 issues at the same time. So please complete them first.
