### ISSUE TITLE
FRONTEND WITH FRAMEWORK: REACT-1.4 JSX Attributes and Styling react elements

### ISSUE THREAD

**Issue by riasenpai** [girlscript/winter-of-contributing#343]
Contributors are required to include information about the JSX Attributes , different ways to style a react element, syntax, examples and anything relevant to the framework.

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)
and [Code Of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by iamsuyashpatel07** [comment]
@the-pro can I work on this.

**Comment by lohith1392** [comment]
Can I work on this issue documentation

**Comment by the-pro** [comment]
@iamsuyashpatel07 Go ahead!

**Comment by tusharjha44** [comment]
Commented

**Comment by tusharjha44** [comment]
Ready to work on this

**Comment by helper-uttam** [comment]
Can I go with `styling` part? using `JSX.module.css`.

**Comment by the-pro** [comment]
@tusharjha44 @helper-uttam We try to assign one issue to one contributor. You can wait for other issues to be created. Check "Frontend with frameworks" milestone for new issues

**Comment by ShobhanSrivastava** [comment]
Can I work on the video part of it?

**Comment by PAARTH2608** [comment]
Can I work on this??

**Comment by the-pro** [comment]
@iamsuyashpatel07 any updates?

**Comment by iamsuyashpatel07** [comment]
@the-pro 
- project setup done
- work started on the issue
- structuring of the article done.(what topic and subtopic should be included).
- started writing the content

**Comment by heet-kumar** [comment]
> Can I work on the video part of it?

On these issue video is not required, only documentation is required with code.

**Comment by anandhu720** [comment]
@iamsuyashpatel07 any updates on your work.

**Comment by iamsuyashpatel07** [comment]
@the-pro @anandhu720  
completed
