### ISSUE TITLE
CSS Transition and Tranformation

### ISSUE THREAD

**Issue by PrachiDoshi2170** [girlscript/winter-of-contributing#3435]
### Description.

I will describe about the CSS transition and transform properties in detail with live coded examples for the same.

@moulikagrawal please assign this work to me

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by moulikagrawal** [comment]
This issue is already opened qnd being worked upon. Kindly check with the existing issues list before opening an issue.
