### ISSUE TITLE
FRONTEND WITH FRAMEWORK: REACT-1.5 What is NPM? 

### ISSUE THREAD

**Issue by riasenpai** [girlscript/winter-of-contributing#344]
Contributors are required to include information about NPM, about React Package (a good starting point https://www.npmjs.com/package/react) , packages and modules, an example and syntax. Anything relevant to the framework and the topic should be included.

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)
and [Code Of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by lohith1392** [comment]
Can I work on this issue documentation

**Comment by Saurabh-crypto16** [comment]
I have used Node Package manager(npm), I have an idea about it. I want to work on this. 
FRONTEND WITH FRAMEWORK BATCH 2

**Comment by the-pro** [comment]
@lohith1392 Sure!

**Comment by Sarfraz-droid** [comment]
Can I work on a Video?

**Comment by the-pro** [comment]
Video is not required here

**Comment by paras-saxena11** [comment]
can i work in this?

**Comment by riyapandey730** [comment]
can i work on this

**Comment by the-pro** [comment]
Someone is already working on it. We will be creating more issues. Keep checking the "Frontend with frameworks" milestone

**Comment by riyapandey730** [comment]
thanks

**Comment by the-pro** [comment]
@lohith1392 Any progress on this or is this up for grabs

**Comment by lohith1392** [comment]
@the-pro ya almost done I will submit it by tonight

**Comment by lohith1392** [comment]
I was not able to present the information accurately sorry!!!

**Comment by anandhu720** [comment]
@lohith1392 no problem

**Comment by Aryan-Mohanty** [comment]
Can I work on this issue?

**Comment by anandhu720** [comment]
@Aryan-Mohanty yes

**Comment by Aryan-Mohanty** [comment]
Hey,@anandhu720, I only have to write about npm and the react package, right?

**Comment by anandhu720** [comment]
> Hey,@anandhu720, I only have to write about npm and the react package, right?

what is npm,installation of npm(in all os) all that things need to be included
