### ISSUE TITLE
FRONTEND WITH FRAMEWORK: REACT-1.6 Create and initialize a React App

### ISSUE THREAD

**Issue by riasenpai** [girlscript/winter-of-contributing#345]
Contributors are required to include information about any prerequisite for installing React, its syntax , an example , an explanation (a good starting point https://reactjs.org/docs/create-a-new-react-app.html) about what each statement : For eg, What is npx, what does "cd" do , what does "npm start" do etc.

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)
and [Code Of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Adarshswain** [comment]
can i work on this

**Comment by Sarfraz-droid** [comment]
Can I work on a Video tutorial for this?

**Comment by Adarshswain** [comment]
i will make video with documentation

**Comment by Saurabh-crypto16** [comment]
I want to make the documentation to create and initialize a create app using npx command and show how to use this command to initialize an app with a template(including a custom template).

**Comment by Adarshswain** [comment]
ok done I will do this

**Comment by amankumar11** [comment]
Can i do this

**Comment by GyaniRoman23** [comment]
@riasenpai I would like to work on this issue. If it is reassigned , please do consider me for it.

**Comment by paras-saxena11** [comment]
can i do ?
please assign me

**Comment by anandhu720** [comment]
@paras-saxena11 bro it is already given to someone.Please wait for new issues

**Comment by paras-saxena11** [comment]
okay @anandhu720.
till when new issues will come?

**Comment by riyapandey730** [comment]
can i do this

**Comment by Adarshswain** [comment]
Till which date I have to submit

**Comment by anandhu720** [comment]
@Adarshswain max one week.Try to finish before that

**Comment by Adarshswain** [comment]
Ok sure I will do it within 2 days

**Comment by ishangupta6412** [comment]
@riasenpai ma'am can you please assign this one to me?

**Comment by heet-kumar** [comment]
> @riasenpai ma'am can you please assign this one to me?

@ishangupta6412 bro this issue is assigned already to someone. Till then wait for new issues and stay active on discord.

**Comment by Drontitan** [comment]
pls assign me this issue i have to work on this

**Comment by anandhu720** [comment]
@Adarshswain any updates on your work

**Comment by Adarshswain** [comment]
sir i have almost completed sir within 2 day i will submit

**Comment by anandhu720** [comment]
Try to make it fast.5 days already finished bro

**Comment by Adarshswain** [comment]
Yes bro tommorow I will submit forsure

**Comment by Adarshswain** [comment]
Sir I have submitted the PR. please Check

**Comment by RIYANSHGARG** [comment]
What is status, If not resolved can I work on this ?

**Comment by Adarshswain** [comment]
alerady done
