### ISSUE TITLE
Android-Kotlin : 03.1 Installing Android Studio 

### ISSUE THREAD

**Issue by sitamadex11** [girlscript/winter-of-contributing#346]
## Description :
* Give a stepwise description of how to install the latest version of android studio. (For Windows, Mac, Linux)
*  Required documentation or video.

## References :
> https://developer.android.com/studio/install?authuser=2
> https://www.geeksforgeeks.org/guide-to-install-and-set-up-android-studio/

* Changes should be made in **Android_Development/Kotlin/** directory under **Android_Development_With_Kotlin** branch.
* You have to push your PR to the **Android_Development_With_Kotlin** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to **squash** your commits into one commit.
> Supervisor @rahulsain

**Comment by tanishqchugh2002** [comment]
I would like to contribute on this Sr no. 6938

**Comment by sitamadex11** [comment]
@tanishqchugh2002 ya sure. You can start working.

**Comment by tanishqchugh2002** [comment]
I have created a PR please review it
