### ISSUE TITLE
Data Science with Python : Feature Selection Techniques

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#347]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about feature selection techniques. Tutorial to feature selection techniques and how it's applied using sample code. Be as elaborative as possible. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Peehu Saxena](https://github.com/PeehuSaxena) / [Arya Patel](https://www.github.com/AryaPatel1111)

Points to Note : 

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172. I would like to do documentation on this issue.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy with serial number:174. I would like to do documentation on this issue.

**Comment by prathimacode-hub** [comment]
Kindly provide all the details asked to assign it on FCFS. Approach is missing here. Whoever states it on first, would get this issue assigned. @ashish-reddy-20-08 @deepthi1107

**Comment by deepthi1107** [comment]
I will write the different steps and approaches of feature selection techniques. I will also add the code to the documentation. 
I am Deepthi M with serial number:172.

**Comment by ashish-reddy-20-08** [comment]
Yes @prathimacode-hub, I am willing to do a presentation video as @deepthi1107 is going for documentation.
My approach would be, I would be going through the importance of feature selection in machine learning and then the various ways or approaches of feature selection and then heading towards some real-life examples in PPT format and would present it.

**Comment by prathimacode-hub** [comment]
Awesome folks, @ashish-reddy-20-08 and @deepthi1107, issue is assigned to you both. You can proceed.

**Comment by ashish-reddy-20-08** [comment]
Thank you @prathimacode-hub.

**Comment by deepthi1107** [comment]
thanks for the opportunity @prathimacode-hub

**Comment by BhaswatiRoy** [comment]
I am bhaswati roy from dswp batch 19
I would like to contribute for this.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M, my serial number:172. I have started writing the document, I am presently working on a dataset with the implementation of feature selection.

**Comment by prathimacode-hub** [comment]
> Hello, I am Deepthi M, my serial number:172. I have started writing the document, I am presently working on a dataset with the implementation of feature selection.

Great going. Keep it up. @deepthi1107

**Comment by deepthi1107** [comment]
hello @prathimacode-hub i have written document and code, I am stuck where to do PR and how to do. Can you guide me?

**Comment by m0hit-kumar** [comment]
I would like to work on this.
Mohit Kumar
Type: Documentation
Issue: 347
Approach:
what is feature selection,
how to analyze datasets for various features,
how features impact the overall performance,
useful features and not important.
how to remove features that are of no use,
how to create useful features from given features

**Comment by deepthi1107** [comment]
Hello mam, I have don PR. Please do evaluate @prathimacode-hub

**Comment by ashish-reddy-20-08** [comment]
Hello @prathimacode-hub . I have created a pull request. Can you please look into that.

Link for the pull request: https://github.com/girlscript/winter-of-contributing/pull/1568

**Comment by ashish-reddy-20-08** [comment]
Hello @prathimacode-hub. I have created a pull request. Can you please look.
I have closed the previous pull request due to an issue.
so can you please look into this 
Link: https://github.com/girlscript/winter-of-contributing/pull/2136

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Can you please assign audio to me for this issue.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for audio contribution
