### ISSUE TITLE
DSA:2.2.10 Searching & Sorting Algorithms : Quick Sort - Audio

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#3479]
### Description
Implement and explain Quick sort Algorithm

## Task
- [ ] Audio
- [ ] Video
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Eswari-Priya** [comment]
/assign
i am eswari priya . i belong to dsa batch2 . pls assign me this issue @Muskan-creator @pjdurden

**Comment by sonali-t** [comment]
Name: Sonali Tomar
Batch: DSA Batch 4
@Muskan-creator @pjdurden please assign me this issue I would like to contribute via documentation

**Comment by rohit-goyal** [comment]
Hello My name is Rohit Goyal 
Pls assign the documentation part of this issue to me 
I am from DSA Batch-2
