### ISSUE TITLE
DSA 2.2.10 Searching & Sorting Algorithms : Quick  Sort - Documentation

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#3480]
### Description

Implement and explain Quick sortAlgorithm

## Task
- [ ] Audio
- [ ] Video
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ShikhaSwati60** [comment]
Name-Swati Shikha
Batch 7
Documentation

**Comment by VikasYadav-1** [comment]
Documentation

**Comment by tanvideshmukh29** [comment]
Can I work on it?
Name-Tanvi Deshmukh
batch-5
Contribution type: documentation

**Comment by cookieg13** [comment]
Hi! I would love to work on this issue? can you please assign it to me?
Name: Debarati Ghatak
Batch: 3
Contribution type: Documentation

**Comment by ShikhaSwati60** [comment]
@Muskan-creator please inform us, to whom is this issue assigned?

**Comment by Muskan-creator** [comment]
This issue has been assigned to @raghav01ib on first come first basis.
Happy contributing 🙂

**Comment by ShikhaSwati60** [comment]
@Muskan-creator Then there is no meaning of this line "While requesting the issue to be assigned, please mention your NAME & BATCH NUMBER" and also you have highlighted the line "Do not use the assign command for this issue". Please be specific about what is written  in the NOTE.

**Comment by raghav01ib** [comment]
@Muskan-creator Chill, please don't make this a zero-sum competition. I am unassigning myself from this issue, you can carry on. All the best

**Comment by ShikhaSwati60** [comment]
@raghav01ib I don't have a problem with u being assigned. Point is that in other domains they follow what is written in the templates because they are the ones who make the rule.

**Comment by Muskan-creator** [comment]
@ShikhaSwati60 This issue is assigned to you .Sorry for inconvienence caused.

**Comment by rohit-goyal** [comment]
Hello My name is Rohit Goyal 
I would like to work on this issue via documentation
I am DSA Batch-2

**Comment by jaigora24** [comment]
@Muskan-creator mam assign this documentation to me.. I think the assignee is inactive
Name - Jai Gora
Batch - 7
Type - Documentation
