### ISSUE TITLE
C_CPP : Level order Traversal in Binary Tree

### ISSUE THREAD

**Issue by Pranshu321** [girlscript/winter-of-contributing#3490]
### Description

In this i give full explain about the approach of the level order traversal in binary tree in document form and with good code snippet and also with understandable comments . 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged !
