### ISSUE TITLE
Objects and Arrays in Javascript

### ISSUE THREAD

**Issue by subhradwip01** [girlscript/winter-of-contributing#3497]
### Description

I will make documentation about arrays and objects in javascript.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : Objects and Arrays in Javascript
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-3497
Contribution Approaches-What is an object, why do we need objects, what is an array, why do we need arrays, examples
Type-Audio
