### ISSUE TITLE
Queue in C++ Standard Template Library

### ISSUE THREAD

**Issue by rishigupta1109** [girlscript/winter-of-contributing#3501]
### Description

This documentation will explain queue of STL in c++ 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged !
