### ISSUE TITLE
Queue Implementation in C

### ISSUE THREAD

**Issue by motasimmakki** [girlscript/winter-of-contributing#3504]
### Description

Description
In this documentation, I will explain the implementation of Queue Data Structure in the C programming language.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by motasimmakki** [comment]
Kindly review PR #3522

**Comment by Saviour1001** [comment]
Closing as the PR is now merged
