### ISSUE TITLE
Flutter: Dealing with assets -Video

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#3506]
### Description

Add video explaining (with a demo) about assets, covering:
- Specifying assets
- Asset bundling
- Asset variants
- Loading assets(text, images, with package dependencies)
- Bundling of package assets
Sharing assets with the underlying platform(ios, Linux, Windows)

### Domain

Android Dev (Flutter)

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by akshat-crypto** [comment]
hey @pratishthaa i would like to work on this issue 
can you please assign this to me if possible

**Comment by akshat-crypto** [comment]
@pratishthaa i have created one pull request regarding this issue. Can you please check this and merge it
