### ISSUE TITLE
Flutter : Navigation - Documentation

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#3507]
### Description

Add documentation on Navigation in Flutter, covering:
- the Navigation model
-  its approach 
- Navigator API

Cover examples too!

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by adityaraj079** [comment]
can i work on this issue

**Comment by ViAsmit** [comment]
@adityaraj079 no need to ask.. if you think you will be able to complete this issue... just type /assign. it will get automatically assigned to you. check for other unassigned issues.
