### ISSUE TITLE
Flutter : Deep Linking -Video

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#3510]
### Description

Add video explanation on Deep Linking in Flutter, covering:

- Enabling deep linking on different OS
- Testing deep linking on different OS
- Migrating from plugin-based deep linking
- Behavior of Linking(routing on different OS)

Give examples for syntax.

### Domain

Android Dev (Flutter)

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by bakisama** [comment]
Hi @pratishthaa 
Could you explain what topics should I wlaborate on
