### ISSUE TITLE
Flutter : Animation - Documentation

### ISSUE THREAD

**Issue by pratishthaa** [girlscript/winter-of-contributing#3511]
### Description

Add documentation on Animations in Flutter, covering:

- Animation
- types of animation
- description of all types(with code examples)
- approach

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by eshan1925** [comment]
Hey, @pratishthaa May I please know the location where the file has to be stored and also The name of the file.

**Comment by eshan1925** [comment]
Hey, @pratishthaa and @ViAsmit I have created the PR for the issue please review it and If everything is good to go you can merge it.
Thankyou

**Comment by ViAsmit** [comment]
Hi @eshan1925... Thanks for the PR.....can you contact your batch mentor to verify your PR. 
If you don't know your batch...post your PR in general channel of discord. Some one will verify , and give you suggestions if required.. and then we will merge it

**Comment by eshan1925** [comment]
Ok Thankyou @ViAsmit

**Comment by eshan1925** [comment]
@ViAsmit please merge the PR if there is no issues...
