### ISSUE TITLE
Frontend with FrameWork - All about npm

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#352]
### **NEED TO CONTAIN**

* What is npm
* Why npm
* Where we use npm
* Installing npm in local machine(all os)
* npm cli
* Advantages of npm

Apart from this any thing relavant about npm can be added.If you guys are making documentation try to include pictures of installation steps.It will be great if you can

You can take refer from [https://docs.npmjs.com/about-npm](url)

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ React inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by Ananyagupta43** [comment]
i want to work on this

**Comment by CSAURABH** [comment]
Can I work on this issue documentation

**Comment by anandhu720** [comment]
@Ananyagupta43 I am assigning you the work

**Comment by anandhu720** [comment]
@CSAURABH we follow first come first serve method.Please wait for other issues bro

**Comment by GyaniRoman23** [comment]
In case if this issue is reassigned to someone, do consider me @anandhu720. I would like to work on this.

**Comment by anandhu720** [comment]
@GyaniRoman23 sure

**Comment by ShobhanSrivastava** [comment]
I have used npm and have quite a good knowledge about it. Can I work on the video part of it?

**Comment by suvangi2205** [comment]
Can I work on documentation part?
