### ISSUE TITLE
Data Science with Python : PDFs and CDFs in ML

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#3520]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in gaining all the guidance that one needs to know about PDFs and CDFs in ML. Tutorial to Temporal PDFs and CDFs in ML and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Peehu Saxena / Jivitesh Jain

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by surjyaneeh** [comment]
Name: Surjyanee Halder 
Sl. No. :966
Type: Documentation 
Approach : introduction, uses, python code samples, conclusion

**Comment by prathimacode-hub** [comment]
Issue assigned to @surjyaneeh for documentation

**Comment by rachita11** [comment]
Name : C. Rachita
type : Video
Approach: explanation of the mathemathics behind, application and visualization

**Comment by ron352** [comment]
Sarmistha Sarna
Serial no: 614
type : Audio

@prathimacode-hub  can I work on it mam?

**Comment by prathimacode-hub** [comment]
Issue assigned to @rachita11 for video and @ron352 for audio contribution. @

**Comment by surjyaneeh** [comment]
I have unassigned myself, can you please assign me again ?
Thank you.
