### ISSUE TITLE
Frontend Dev (HTML, CSS, JS): CSS Combinators

### ISSUE THREAD

**Issue by braveheartdata** [girlscript/winter-of-contributing#3527]
### Description

# Description
I would like to make documentation on CSS Combinators
I would provide theory related to it along with some examples

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Subhrato20** [comment]
@ayushjain27 this issue was created by me so please try to understand and create your own issue.
