### ISSUE TITLE
C_CPP: Text Files and Binary Files

### ISSUE THREAD

**Issue by 124015001** [girlscript/winter-of-contributing#3578]
### Description

Description

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged
