### ISSUE TITLE
[Create New Issue]: Stacks in c++

### ISSUE THREAD

**Issue by jyotibajaj729** [girlscript/winter-of-contributing#3588]
### Description

First of all  i will explain what basically stack is then its syntax , its member types and all the functions that can be performed in it.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by jyotibajaj729** [comment]
\assign

**Comment by priyankapiba** [comment]
@Saviour1001 please assign me this issue.

**Comment by ayushjain27** [comment]
\assign

**Comment by jyotibajaj729** [comment]
> /assign

I have made a pr on this issue can u plzz take some another issue

**Comment by ayushjain27** [comment]
Okay no problem
