### ISSUE TITLE
Algorithms: Kadane's Algorithm(CPP)

### ISSUE THREAD

**Issue by amankumar11** [girlscript/winter-of-contributing#3592]
### Description

Covering the code and use of kadane's algo.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged
