### ISSUE TITLE
Android-Java: 1.3 Installing Android Studio

### ISSUE THREAD

**Issue by Rohit-2602** [girlscript/winter-of-contributing#36]
## Description ->
- Give a brief on how to download and install Android Studio on a device (Mac, Windows, Linux).

## Source ->
- https://developer.android.com/studio/install

## Note ->
- Changes should be made inside the Android_Development/Java directory & Android_Development_with_java branch.
- Issue only for GWOC'21 contributors.
- Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.

Must-Follow: Contributing Guidelines & Code of Conduct before start Contributing.

**Comment by pranjalkalal** [comment]
I want work on this issue

**Comment by Rohit-2602** [comment]
Yes sure go on mate. Good luck!!

**Comment by anmol20112000** [comment]
I want to work on this

**Comment by Rohit-2602** [comment]
@anmol20112000 this issue is already assigned, I will make a new one tomorrow then you can take that issues

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 1.3 for instance `1.3 Installing Android Studio`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `1.3.1`, `1.3.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by anmol20112000** [comment]
Sir u assigned this work to me..?

**Comment by VikasPandey121** [comment]
Hi @anmol20112000! Sorry for the misunderstanding. This issue has been assigned to @pranjalkalal only, you can work upon any other issue which is still not assigned.
Thanks for understanding.

**Comment by pranjalkalal** [comment]
https://github.com/girlscript/winter-of-contributing/pull/2083 @Rohit-2602

**Comment by Rohit-2602** [comment]
@pranjalkalal are still facing problems with Git or it is OK

**Comment by pranjalkalal** [comment]
Yes please arrange one talk with any mentor who explain me this process .
suppose it's easy from your side but I have some time to understand  so
direct talk is better option more than documents .
