### ISSUE TITLE
DSA 2.1.11.2 longest increasing subsequence

### ISSUE THREAD

**Issue by vikhyatsingh123** [girlscript/winter-of-contributing#3606]
## Description

Explain and implement Length of longest increasing subsequence in a string.

## Task
- [ ] Audio
- [ ] Video
- [x] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Harshil-Jani** [comment]
With the continuation of Topic from #3605  Can I also try documenting this  as well @vikhyatsingh123 ?
**Harshil Jani
DSA-Batch2**

**Comment by mehabhalodiya** [comment]
@goelesha Please assign this issue to @Harshil-Jani

**Comment by vikhyatsingh123** [comment]
@jaigora24 Don't use assign command for issues created by supervisors

**Comment by vikhyatsingh123** [comment]
> With the continuation of Topic from #3605 Can I also try documenting this as well @vikhyatsingh123 ? **Harshil Jani DSA-Batch2**

Delete issue number that you have written here.

**Comment by pranshukas** [comment]
@vikhyatsingh123 I am willing to work on this issue if it's still open. 
Name: Pranshu Kashyap
Batch: DSA Batch-5
Language of Contribution: C++ (Documentation + Code) 

Please assign me this issue.

**Comment by vikhyatsingh123** [comment]
@Shruti-Subu ok
