### ISSUE TITLE
Opensource : Explaining about opensource ```Licenses``` in detail.

### ISSUE THREAD

**Issue by Harshil-Jani** [girlscript/winter-of-contributing#3619]
### Description

- Explain importance of Licenses.
- Difference between available Licenses on Github.
- Describe License used by GWOC repository as an Example.

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Harshil-Jani** [comment]
@Aryamanz29 Can I work on this ?

**Comment by Gur-jot** [comment]
How can I make my contribution in Opensource

**Comment by Harshil-Jani** [comment]
> How can I make my contribution in Opensource

Hey I would suggest you to go to OpenSource Folder from main code file and go through topics and read them. Multiple contributors have created nice content for open source and everything is well documented :100: !
All the Best :crossed_fingers:

**Comment by Harshil-Jani** [comment]
@Aryamanz29 Can you plz look up at this Issue and Assign it to me ?

**Comment by Harshil-Jani** [comment]
@Aryamanz29 Any Updates on this issue? Can I work for it?
