### ISSUE TITLE
Shortest path from 1 to n #3626

### ISSUE THREAD

**Issue by vishal1patidar** [girlscript/winter-of-contributing#3626]
### Description

#Aim
Consider a directed graph whose vertices are numbered from 1 to n. There is an edge from a vertex i to a vertex j if either j = i + 1 or j = 3 * i. The task is to find the minimum number of edges in a path in G from vertex 1 to vertex n.

Please Assign me under GWOC21 .I will be solving in C++.

Programming language

 C++

### Domain

C/CPP

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vishal1patidar** [comment]
**/assign**

**Comment by shikhar13012001** [comment]
Can @vishal1patidar tell me where should I put the solution to this above problem, please?

**Comment by vishal1patidar** [comment]
@shikhar13012001 
Here and create pull request

Or add a folder in c/cpp and create pull request
