### ISSUE TITLE
[Create New Issue]: Javascript Popup boxes : Prompt, Alert and confirm 

### ISSUE THREAD

**Issue by ayushjain27** [girlscript/winter-of-contributing#3631]
### Description

Explain Javascript Popup boxes with Examples

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ayushjain27** [comment]
\assign

**Comment by ayushjain27** [comment]
\assign

**Comment by ayushjain27** [comment]
I created this issue for myself. Can you take please another one @sharvariiii

**Comment by ayushjain27** [comment]
\assign

**Comment by sharvariiii** [comment]
okay, no problem😊
Ayushi, use **forward-slash character ( / )** to get it assigned, you are using backslash ( \ ).



> I created this issue for myself. Can you take please another one @sharvariiii

**Comment by ayushjain27** [comment]
Thanks to you. It's not ayushi and It's ayush @sharvariiii

**Comment by Arya-Gupta** [comment]
I want to contribute to this issue : [Create New Issue]: Javascript Popup boxes : Prompt, Alert and confirm
Name-Arya Gupta
Domain-Frontend with HTML CSS
Batch-16
Serial No-3172
Issue Number-3631
Contribution Approaches-What are popup boxes, why are they necessary, types of popup boxes, when to use which popup box
Type-Audio

**Comment by ShraddhaMeshram27** [comment]
/assign
Please guide me on how to get the issue?
Do we have to create the issue ourselves and assign it ourselves?
What do we need to do sir @github-actions
