### ISSUE TITLE
Open Source:explain everything related to LGMSoC(LetsGrowMore)  

### ISSUE THREAD

**Issue by iamsunil25** [girlscript/winter-of-contributing#3640]
### Description

explain everything related to LGMSoC Open Program 

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by iamsunil25** [comment]
@paul-111 as you can see above, this issue is already assigned to @pspiagicw then you shouldn't have to comment "/assign".

**Comment by Aryamanz29** [comment]
Not need this issue
