### ISSUE TITLE
Cybersecurity 4.6 Vigenère Cipher

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#3646]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AtharvaaPatil** [comment]
Hey I want to do the documentation part

**Comment by RK1905101** [comment]
/assign

for documentation

**Comment by Anant1711** [comment]
> Hey I want to do the documentation part

Assigned!

**Comment by Anant1711** [comment]
@AtharvaaPatil When you are going to submit your work?

**Comment by iamKushGupta** [comment]
Is this not merged yet?
Did I make a mistake???
