### ISSUE TITLE
Cybersecurity 4.7 Substitution  Cipher 

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#3647]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HumblePlebeian** [comment]
I would like to work on this topic. Can you please assign this issue to me?

**Comment by Anant1711** [comment]
> I would like to work on this topic. Can you please assign this issue to me?

can you work on video?

**Comment by HumblePlebeian** [comment]
I wanted to contribute in doc format this time

**Comment by Anant1711** [comment]
> I wanted to contribute in doc format this time

I think @nikki-priyaHIT is doing doc!!!

@nikki-priyaHIT are you doing in doc or in the video!

**Comment by nikki-priyaHIT** [comment]
> > I wanted to contribute in doc format this time
> 
> I think @nikki-priyaHIT is doing doc!!!
> 
> @nikki-priyaHIT are you doing in doc or in the video!

I am extremly sorry for my mistake please assign this issue to @HumblePlebeian , haven't seen that it was of cyber security and it's not my topic

**Comment by Anant1711** [comment]
@HumblePlebeian 
assigned for doc!

**Comment by HumblePlebeian** [comment]
> @HumblePlebeian assigned for doc!

Thank you!
