### ISSUE TITLE
Cybersecurity 4.8 Affine  Cipher

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#3648]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by artishukla1** [comment]
Can you assign me this @Anant1711 ?

**Comment by Anant1711** [comment]
> Can you assign me this @Anant1711 ?

Assigned!

**Comment by artishukla1** [comment]
Thankyou !

**Comment by Anant1711** [comment]
@artishukla1 When you are going to submit your work?

**Comment by artishukla1** [comment]
@Anant1711, Submitted. Kindly check!

**Comment by artishukla1** [comment]
> @artishukla1 When you are going to submit your work?

@Anant1711 , Submitted. Kindly check!
