### ISSUE TITLE
Technical Questions -Bit Manipulation

### ISSUE THREAD

**Issue by rhythmjayee** [girlscript/winter-of-contributing#3660]
### Description

Description
This issue should contain top frequently asked Interview questions and all-important bit manipulation tricks. Video Solution will be good if made !! Search for the quality questions on the web and explain the approach in your words for each problem you solve (either you can add comments in the code or subtitles in your video).

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nikki-priyaHIT** [comment]
may i work on this issue?
Nikki Priya
DSA Batch-2
Documentation

**Comment by nikki-priyaHIT** [comment]
I want to work on this issue @rhythmjayee, please assign this to me.

**Comment by rhythmjayee** [comment]
@nikki-priyaHIT  at most only 3 issues can be assigned to single contributor

**Comment by nikki-priyaHIT** [comment]
i have unassigned myself from one of my assigned issue it was of audio,video part so i want this issue to be assign for me @rhythmjayee

**Comment by nikki-priyaHIT** [comment]
@rhythmjayee please preview my PR, if any changes you want then let me know and if everything is okay then kindly please merge it :-), Thank You!
