### ISSUE TITLE
Data Science with Python : Bagging and Boosting

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#367]
Welcome to 'DSWP' Team, good to see you here

With this issue, you can provide guidance on bagging and boosting techniques. Explain elaborately and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Nithin](https://github.com/Nithin-Reddy-02) / Gauri Bharadwaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Adi7171** [comment]
@prathimacode-hub  I would like to be assigned this . i will write some ifo regarding it and then provide some code as well.
sno: 92
type: documentation

**Comment by prathimacode-hub** [comment]
Issue assigned to @Adi7171 for documentation

**Comment by shubhdholakiya** [comment]
Can I work on this Issue?

**Comment by shubhdholakiya** [comment]
The previously assigned participant has unassigned himself.

**Comment by ishreyakumari** [comment]
I want to be assigned.
SHREYA KUMARI - 457
(Documentation)
Approach - introduction, steps and approaches, examples ,difference between Bagging and Boosting, applications.

**Comment by prathimacode-hub** [comment]
> Can I work on this Issue? Kindly assign me this!
> Shubh Dholakiya
> Documentation.
> DSWP Batch - 10, SR. 362

Kindly provide the approach, so that I could assign it up. Approach in the session, what you would like to bring up to the table. @shubhdholakiya

**Comment by prathimacode-hub** [comment]
> > Can I work on this Issue? Kindly assign me this!
> > Shubh Dholakiya
> > Documentation.
> > DSWP Batch - 10, SR. 362
> 
> Kindly provide the approach, so that I could assign it up. Approach in the session, what you would like to bring up to the table. Do this next time, while expressing interest along with serial number and choice. @shubhdholakiya

For now it has to be assigned to @ishreyakumari, as she has provided all the details in first commit.

**Comment by prathimacode-hub** [comment]
Issue is assigned to you @ishreyakumari

**Comment by prathimacode-hub** [comment]
If you are up for Audio / Video let me know but lots arriving up. @shubhdholakiya

**Comment by ishreyakumari** [comment]
@prathimacode-hub Thank you :). Can you please assign this issue to me since it is not reflecting in "Assignees".

**Comment by ishreyakumari** [comment]
> Issue is assigned to you @ishreyakumari for documentation

@prathimacode-hub Thank you :). Can you please assign this issue to me since it is not reflecting in "Assignees".

**Comment by shubhdholakiya** [comment]
> If you are up for Audio / Video let me know but lots arriving up. @shubhdholakiya

Sure.

**Comment by ishreyakumari** [comment]
@Nithin-Reddy-02 this task is assigned to me. I have a doubt. In data science with python branch, I have to go to machine learning folder and put coding notebook plus readme file there and then create pull request. Is it? Can you please guide me. Thank you.

**Comment by prathimacode-hub** [comment]
Yes exactly. There are subfolders inside machine learning, choose the sub repo according to your issue title in it and follow the remaining process. @ishreyakumari

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution
