### ISSUE TITLE
Heap Sort in C++

### ISSUE THREAD

**Issue by arjyo851** [girlscript/winter-of-contributing#3673]
### Description

This issue will cover the heap sort topic.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged
