### ISSUE TITLE
CSS: Text_Manipulation 

### ISSUE THREAD

**Issue by AS8420** [girlscript/winter-of-contributing#3674]
### Description

This documentation will contain information regards Text Manipulation in CSS.

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by negiaditi** [comment]
I can do this, if you can assign me the same

**Comment by Divyanshigarg** [comment]
can i also get to work on this?

**Comment by AS8420** [comment]
Please everyone choose different topic.
It's already assigned to me. If you want to do this topic then issue this
one in different format to yourself.
