### ISSUE TITLE
Frontend With Framework - Javascript Expressions in JSX & ES6 Template Literals

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#369]
### **NEED TO CONTAIN**

* How javascript expression are done using Jsx in React
* ES6 Template Literals
* Advantage of ES6 template literals

Apart from this any thing relavant about npm can be added.If you guys are making documentation try to include pictures of topic.It will be great if you can

You can take refer from
* [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals](url)
* [https://reactjs.org/docs/introducing-jsx.html#:~:text=Embedding%20Expressions%20in%20JSX&text=You%20can%20put%20any%20valid,into%20an%20element.](url)

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ React inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by CSAURABH** [comment]
Can I work on this issue documentation

**Comment by tanishqchugh2002** [comment]
I would like to work on this

**Comment by amankumar11** [comment]
i would like to work on this

**Comment by anandhu720** [comment]
@CSAURABH I am assigning this work to you

**Comment by anandhu720** [comment]
@CSAURABH are you going to do documentation or video.

**Comment by CSAURABH** [comment]
@anandhu720 Documentation.

**Comment by anandhu720** [comment]
@tanishqchugh2002 @amankumar11 guys if you guys are intrested in making video about it.I can assign you that work

**Comment by ShobhanSrivastava** [comment]
Can I work on the video part of it?

**Comment by anandhu720** [comment]
@ShobhanSrivastava Sure,I will assign you this work
