### ISSUE TITLE
Heap Sort 

### ISSUE THREAD

**Issue by rajraii** [girlscript/winter-of-contributing#3690]
### Description

Ill take up the topic of heap sort in which where ill cover all the aspect of heap sort and some tips to how you can use them in your various programs to smooth things out. It will be in a documented way.

### Domain

C/CPP

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Iamtripathisatyam** [comment]
hello @ rajraii
I wanted to contribute to it using documentation, Please assign it to me!

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by Suvraneel** [comment]
@rajraii  duplicate  of #3673
