### ISSUE TITLE
Data Science with Python : Edges & Contours using OpenCV

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#370]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Edges & Contours using OpenCV. Tutorial to Edges & Contours elaborately and how it's applied visually.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Computer Vision

Mentors Assigned : [Jivitesh Jain](https://github.com/jiviteshjain) / [Dhruv Bajaj](https://github.com/DhruvBajaj01)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Adi7171** [comment]
@prathimacode-hub I would like to be assigned this. I will write some info regarding it such as its workings etc and then explain code regarding it using open cv.
sno: 92
type: documentation

**Comment by prathimacode-hub** [comment]
@Adi7171 Already an issue is assigned to you. This would go for someone who aren't assigned yet.

**Comment by Adi7171** [comment]
@prathimacode-hub  I would like to recieve this one instead of bagging because I think I can write this better

**Comment by shubhdholakiya** [comment]
I am Interested in this can you please assign this to me, mam?

**Comment by surjyaneeh** [comment]
I want to be assigned.
Surjyanee Halder - 966
(Documentation)
Approach - introduction, steps and approaches, examples/ code

**Comment by prathimacode-hub** [comment]
Ok @Adi7171, issue is assigned to you. 

@shubhdholakiya @surjyaneeh, you can express interest on other open and upcoming issues. Just missed it out.

**Comment by Adi7171** [comment]
thanks @prathimacode-hub

**Comment by shubhdholakiya** [comment]
> Ok @Adi7171, issue is assigned to you.
> 
> @shubhdholakiya @surjyaneeh, you can express interest on other open and upcoming issues. Just missed it out.

Okay

**Comment by Adi7171** [comment]
@prathimacode-hub I did a PR can u check once

**Comment by DhruvBajaj01** [comment]
The file will be reviewed and mentored by me . @prathimacode-hub

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
