### ISSUE TITLE
Python: Dictionaries in Python 

### ISSUE THREAD

**Issue by Varun270** [girlscript/winter-of-contributing#3700]
### Description

Description

Breif description of dictionaries in Python

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by adityabisoi** [comment]
Topic already covered. Closing this issue.
