### ISSUE TITLE
C_CPP : Encryption and Decryption in C++

### ISSUE THREAD

**Issue by ankushsingh24** [girlscript/winter-of-contributing#3706]
### Description

This documentation will explain Encryption and Decryption of messages in C++

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purohitmansi** [comment]
Please do assign this to me.
