### ISSUE TITLE
Data Science with Python : Hyperparameter Tuning

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#372]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in know all the information before working on Hyperparameter Tuning. Brief elaboration along with sample code of Hyperparameter Tuning is needed. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Dhruv Bajaj](https://github.com/DhruvBajaj01) / [Peehu Saxena](https://github.com/PeehuSaxena)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by imedusa** [comment]
I would like to work on this issue. I will add the code explaining the topic along with comments. The .ipynb notebook will have codes explaining the stuff from scratch.

I am Medini N B. Serial Number : 585, DSWP batch - 16

**Comment by GopinathBalaji** [comment]
Hello, I am Gopinath Balaji with serial number: 315. I would like to do documentation on this issue.
I would like the explain the basics of hyperparameter selection and tuning

**Comment by prathimacode-hub** [comment]
@imedusa, issue assigned on FCFS for documentation. 

@GopinathBalaji, many more issues arriving up.

**Comment by imedusa** [comment]
Thank you @prathimacode-hub

**Comment by m0hit-kumar** [comment]
I would like to work on this.
Mohit kumar
Type: Doccumentation
Issue: 386
Approach: what is  Hyperparameter Tuning, how to do Hyperparameter Tuning and find the best parameter for the model

**Comment by DhruvBajaj01** [comment]
This file/issue will be mentored by me. @prathimacode-hub

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
