### ISSUE TITLE
Python: Basic of Tkinter

### ISSUE THREAD

**Issue by priyanshuc4423** [girlscript/winter-of-contributing#3775]
### Description

Description:
Gives all the basic info to get you started with Tkinter

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshuc4423** [comment]
/assign
@adityabisoi

**Comment by adityabisoi** [comment]
Go ahead

**Comment by adityabisoi** [comment]
@nirvikagarwal Is the mentor of this issue

**Comment by achsahxavier** [comment]
@adityabisoi 
If this issue is open for audio contribution, please assign it to me.
Thank you.
