### ISSUE TITLE
C/CPP  Merge Sort 

### ISSUE THREAD

**Issue by rravi1401** [girlscript/winter-of-contributing#3787]
### Description

<hr>

## Description

I will write and explain the code of merge sort ###documentation

<hr>

## Domain of contribution

-[x] C/CPP

<hr>

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
@rravi1401  Like stated before, closing & reopening the issue won't work...
Its already past deadline... Kindly find a new issue to work on
