### ISSUE TITLE
Cybersecurity: 1.2 Importance of Information Security? 

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#38]
## Description
Information security is designed to protect the `electronic` and other `private`, `sensitive`, and `personal` data from Hackers. 
**Explain what is the importance of Information Security in the cyber world?**
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on **first come first serve**
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by anjanaaaaaaaa** [comment]
I would like to take this

**Comment by Anant1711** [comment]
> I would like to take this

@anjanaaaaaaaa I'm assigning you this task! 👍🏻
