### ISSUE TITLE
Data Science with Python: Support Vector Machines

### ISSUE THREAD

**Issue by shreyarai05** [girlscript/winter-of-contributing#3800]
### Description

Providing brief description to explain the topic with help of code snippets and example.

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment]
It's already done I guess. @shreyarai05

**Comment by prathimacode-hub** [comment]
> It's already done I guess and also inform when issue is created from your end. @shreyarai05

**Comment by shreyarai05** [comment]
mam how would i inform you?

**Comment by prathimacode-hub** [comment]
Thanks for informing in thread. Issue assigned to @shreyarai05 for documentation

**Comment by shreyarai05** [comment]
Mam can i prepare simple doc file for the resolving issue?

**Comment by shreyarai05** [comment]
@prathimacode-hub 
mam would u tell me what kind of file i need to prepare for contributing

**Comment by prathimacode-hub** [comment]
No, it's an algorithm. It needs .ipynb file with sample code and implementation along with README.md file with good elaboration. @shreyarai05

**Comment by prathimacode-hub** [comment]
Sorry to say, but this issue is already done. It can't be worked on. If you would like to work on this issue, there is already an open issue with same title, you can check over there if audio / video contribution available. @shreyarai05
