### ISSUE TITLE
Frontend with Framework : Creating an Angular Project, angular-cli

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#385]
Contributors are required to explain what things to setup for creating an angular project , angular-cli setup. They can refer to https://angular.io/guide/setup-local for the same .

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by Saurabh-crypto16** [comment]
I want to work on this.

**Comment by Saurabh-crypto16** [comment]
Do I have to make it in a .md file?

**Comment by the-pro** [comment]
You can create content in whatever form you like

**Comment by Saurabh-crypto16** [comment]
ok, thank you.
