### ISSUE TITLE
MERN_Express: 2.3 Dynamic Content in Express & Intro to Template Engines

### ISSUE THREAD

**Issue by hardikk2002** [girlscript/winter-of-contributing#3851]
### :pushpin: Minimum points to be covered.
- What's Dynamic Website.
- What is `Template Engine` and why we need them.
- Briefly tell about these template Engines
      1. `Pug`
      2. `HandleBars(hbs), Mustache`
      3. `EJS`
- How to set view engine in Express, `app.set("view ...", " ")`
- Use of `views` folder
- `res.render()` vs `res.send()`

### :file_folder: Project Directory

Branch MERN>MERN/Topic/Backend/Express/

### :paintbrush: Filename
2.3_Dynamic_Content_in_Express_and_Intro_to_Template_Engines(D).md

## Happy Contributing :partying_face::raised_hands:

---
Doubt? Reach me on Discord.

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by soma2000-lang** [comment]
@hardikk2002 I am an participant of GWOC and would like to work on this issue.Please assign me this

**Comment by hardikk2002** [comment]
> @hardikk2002 I am an participant of GWOC and would like to work on this issue.Please assign me this

Comment `/a s s i g n`  in continuation,
