### ISSUE TITLE
Frontend Dev (HTML, CSS, JS): CSS background-repeat( CSS property to set how background images are repeated)

### ISSUE THREAD

**Issue by braveheartdata** [girlscript/winter-of-contributing#3854]
### Description

# Description
I would like to make documentation on CSS background-repeat ( CSS property to set how background images are repeated)
I would provide theory related to it along with some examples

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Diksha02** [comment]
I would like to work on this, I'm from batch 13 of FEWD using HTML, CSS and js.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> /assign

@Diksha02  That's not the spirit of open-source. @Subhrato20  Opened & got assigned this issue, so you can't work on this one.

**Comment by Diksha02** [comment]
Okay.. I thought they got unassigned. My bad.
