### ISSUE TITLE
Data Science with Python : Introduction to Linear Algebra

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#389]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in knowing about Introduction to Linear Algebra. Tutorial to Linear Algebra and how it's applied effectively

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Linear Algebra

Mentors Assigned : [Aishani Singh](https://github.com/aishanii) / [Shivang Dubey](https://github.com/shivangdubey)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by khush2706** [comment]
I would like to work on this...
Khushboo Chaturvedi Batch-13

**Comment by prathimacode-hub** [comment]
To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Kindly provide all these details. And approach here is how would you like to work on it and what all would you cover up with respect to this issue. @khush2706

**Comment by khush2706** [comment]
> To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.
> 
> Kindly provide all these details. And approach here is how would you like to work on it and what all would you cover up with respect to this issue. @khush2706 

- S.No. is 388
I would make the documentation for it covering the basic definations, after that the code demonstrations using numpy.

**Comment by prathimacode-hub** [comment]
Ok, issue is assigned to @khush2706 for documentation.

**Comment by shivangdubey** [comment]
@khush2706 any updates?

**Comment by khush2706** [comment]
Hi,
Sorry for the late reply. Actually there was a death at my home and I was
occupied by that. Apparently I am running a bit late on my issue, therefore
I wanted to know if it would be alright if I submitted it a bit
late...maybe by 25th..?
I apologize for this hindrance.

**Comment by aishanii** [comment]
@khush2706 ig the issue gets automatically unassigned after 5 days

**Comment by aishanii** [comment]
@prathimacode-hub add me as assignee please

**Comment by harichandana1406** [comment]
/assign
Name - Srikurmum HariChandana
Serial Number - 929
Batch :21
Type - Documentation
Approach: I will explain Introduction to Linear Algebra for data science with python.

**Comment by harichandana1406** [comment]
@prathimacode-hub Can you review and merge pull request?

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub ,
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution
