### ISSUE TITLE
Cybersecurity: 1.3 Challenges in Information Security?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#39]
## Description
**Discuss challenges face in information security.**
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by medhatiwari** [comment]
I would like to work on this

**Comment by Anant1711** [comment]
> I would like to work on this

@medhatiwari I'm assigning this task to you!👍🏻

**Comment by medhatiwari** [comment]
@Anant1711 Sir I have made the pr, check once and suggest changes (if any)
