### ISSUE TITLE
Python strings , Lists , Tuples and Dictionaries  

### ISSUE THREAD

**Issue by roopali-1** [girlscript/winter-of-contributing#3902]
### Description

in this issue we have to discuss about strings , tuples , lists and dictionaries of python that how they are written , what is the syntax and how they work .

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by roopali-1** [comment]
@prathimacode-hub mam i created this issue and i want to work on this one . so kindly assign this issue to me so that i can work on this accordingly .
thank you !!

**Comment by prathimacode-hub** [comment]
Do you want to work on this? I guess already an issue is assigned to you. @roopali-1

**Comment by SoubhPrat17** [comment]
Please let me work on this. I haven't worked on a single issue

**Comment by roopali-1** [comment]
Now 1 issue got assigned to me .. if someone is not worked in this then i
will ..
As of now i am already working on 1 issue..

**Comment by Varun270** [comment]
@prathimacode-hub I am already working on creating documentation for dictionaries in python. Here is the issue that I created 2 days ago-  #3700. I created this after getting a go-ahead from Randrita and then assigned it to myself. I assume that the issue creator somehow didn't check whether an issue like this already exists or not. Kindly close this issue.
