### ISSUE TITLE
DSA 2.1.12 longest palindromic substring

### ISSUE THREAD

**Issue by vikhyatsingh123** [girlscript/winter-of-contributing#3915]
## Description

Explain and implement Longest Palindromic Substring.

## Task
- [ ] Audio
- [ ] Video
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- **Mention the type of contribution you want to make**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- **Do not use the assign command for this issue. Follow the above procedure.**
- In case you see that the issue has already been assigned, try to request a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be the same as the issue.
- This issue is only for 'GWOC' contributors of the 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

DSA

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Eswari-Priya** [comment]
I am Eswari Priya Repaka and i belong to dsa batch2. I'm interested in working on this issue. Kindly assign it to me @vikhyatsingh123

**Comment by tanvideshmukh29** [comment]
I would love to work on this issue .
Can u please assign to me
Name-Tanvi Deshmukh
Batch-6

**Comment by tanvideshmukh29** [comment]
I would love to work on this issue .
Can u please assign to me
Name-Tanvi Deshmukh
Batch-6
Type Documentation

**Comment by Parth-001-git** [comment]
I am Parth Sharma and I belong to dsa batch 5. I'm interested in working on this issue via audio. Kindly assign it to me @vikhyatsingh123

**Comment by Eswari-Priya** [comment]
@vikhyatsingh123 sir ,I had seen that @goelesha mam had already created this issue #3080 . Should I continue to work on it? Pls let me know
