### ISSUE TITLE
Data Science with Python : Text Preprocessing in NLP

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#392]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers understand with the concepts of Text preprocessing or cleaning scripts in NLP like Eg. Lowercasing, Punctuation Removal, Removing stopwords, text standardization, Spelling correction, Tokenization, etc. along with sample code. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : [Arya Patel](https://www.github.com/AryaPatel1111) / Gauri Bharadwaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepeshaburse** [comment]
I would like to contribute to this 
I'm from DSWP batch 4

**Comment by prathimacode-hub** [comment]
More details needed. 

Refer this :

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

@deepeshaburse

**Comment by deepeshaburse** [comment]
I would like to work on the documentation, I am unable to find the spreadsheet as of now, could you give me a few minutes to check that out?

**Comment by prathimacode-hub** [comment]
> I would like to work on the documentation, I am unable to find the spreadsheet as of now, could you give me a few minutes to check that out?

Sure, you can come and edit the comment here with details and also let me know of your approach on what all you be dealing with and how you would apply. @deepeshaburse

**Comment by deepeshaburse** [comment]
S. No. 136
I would like to work on the documentation.
I will explain all the concepts that come under NLP and libraries available and put a code excerpt to preprocess data through the library nltk.

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepeshaburse for documentation. @deepeshaburse

**Comment by Deepika-Pavundoss** [comment]
Sr no: 161
Deepika Pavundoss
Batch 5
I would like to work on this
Video
Approach: How text preprocessing is done, different libraries used and how NLP uses the preprocessed text in determining and analyzing the text

**Comment by Subhrato20** [comment]
I would like to be assigned to work on it.
Name:- Subhrato Som
Batch:- 9
Serial Number:- 322
Contribution Type:- Documentation
Approach:- Introduction to NLP and the application of text processing in it, How it works, Usage and Example of analyzing text.

**Comment by prathimacode-hub** [comment]
Issue assigned to @Deepika-Pavundoss for video contribution. 

@Subhrato20, documentation and video is already taken.

**Comment by avinash-218** [comment]
@prathimacode-hub 
I would like to work on this.
Name : Avinash R
Type: Documentation
Batch: 19
Issue: 796
Approach:
1) Expand Contractions (Eg: Don't -> Do not)
2) Convert to Lower Case
3) Remove Punctuations
4) Remove words containing digits
5) Stop-words Removal
6) Stemming
7) Lemmatization
8) Remove extra space
9) Tokenization - Word, Sentence etc...
10) Spelling Correction
11) POS tagging
12) Frequency Distribution
