### ISSUE TITLE
MERN_React: 1.1 What is React?

### ISSUE THREAD

**Issue by manjeetdhayal** [girlscript/winter-of-contributing#394]
# Instructions 

## Project directory
    Branch MERN>Web_Development/MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## What is React?
Write a brief summary on what is React? Please refrain from coping from internet. You can use any source as inspiration. 

# Task 
- [ ] Audio
- [ ] Documentation
- [ ] Video

### Send a PR in the following branch only and make documentation in form of markdown file with (.md) extension and in the respective folder

**Comment by Saurabh-crypto16** [comment]
I want to make the documentation part.

**Comment by siddhi-244** [comment]
I haven't selected this domain. But still can I contribute?

**Comment by Sarfraz-droid** [comment]
Can I work on the Video part?

**Comment by amankumar11** [comment]
I can work on the documentation part

**Comment by GyaniRoman23** [comment]
Hey!! @manjeetdhayal . Can I please work on the Documentation part?

**Comment by miraj0507** [comment]
I wish to contribute in this documentation

**Comment by manjeetdhayal** [comment]
@Saurabh-crypto16 You can work on documentation part I have assigned you

**Comment by manjeetdhayal** [comment]
@Sarfraz-droid I have assigned you, you can work on video part

**Comment by manjeetdhayal** [comment]
@miraj0507 you can work on audio part. I have assigned it to you

**Comment by Jaya3112** [comment]
I wish to contribute in the form of documentation. Assign me this work.

**Comment by ayushjha952** [comment]
Can I work on the documentation part?
Ayush Jha 
MERN batch-1

**Comment by manjeetdhayal** [comment]
hey @ayushjha952 this is already assigned. You can work on another issues

**Comment by ayushjha952** [comment]
okay
