### ISSUE TITLE
Data Science With python:Introduction to plotly and cufflinks 

### ISSUE THREAD

**Issue by shreyarai05** [girlscript/winter-of-contributing#3947]
### Description

Briefly explaining the topic using example and code snippet.

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreyarai05** [comment]
@prathimacode-hub
mam please assign me this issue

**Comment by sanjana-iyengar** [comment]
I would like to contribute.

Full name: Sanjana Alaham
Batch Number: 19
GitHub Profile Link: https://github.com/sanjana-iyengar
Contribution: Documentation

**Comment by shreyarai05** [comment]
I would want to contribute.
Name: Shreya Rai
Serial no:155 
Batch:5
Approach : Theory explaining the topic along with examples.
type:Documentation
