### ISSUE TITLE
visualization of data

### ISSUE THREAD

**Issue by ashutoshlovpry** [girlscript/winter-of-contributing#3978]
### Description

visualization of data from csv file as a graph format

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashutoshlovpry** [comment]
serial no.-116
batch-4
name-ashutosh singh

**Comment by prathimacode-hub** [comment]
Don't create issues without informing. @ashutoshlovpry
