### ISSUE TITLE
Cybersecurity: 1.4 Information security controls?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#40]
## Description
**Discuss Information security controls!**

## Sources
[Wiki](https://en.wikipedia.org/wiki/Security_controls)
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by akshara-narayanan** [comment]
I would like to take this

**Comment by Anant1711** [comment]
> I would like to take this

@akshara-narayanan I'm assigning this task to you!👍🏻

**Comment by b33pl0g1c** [comment]
Hi @Anant1711 nobody is assigned to this task, Can I work on the documentation of this?

**Comment by ilakkiya-v** [comment]
@Anant1711  hello! I've been assigned this task. I would like to take up the documentation for this!

**Comment by Anant1711** [comment]
> @Anant1711 hello! I've been assigned this task. I would like to take up the documentation for this!

Okay go for it!

**Comment by Anant1711** [comment]
@ilakkiya-v when do you submit your work?

**Comment by ilakkiya-v** [comment]
> @ilakkiya-v when do you submit your work?

Hello! I'm so sorry for the delay! I'll submit it in two days! Other works had come up.

**Comment by Anant1711** [comment]
Okay please submit in only two days!
