### ISSUE TITLE
OpenSource: 5.8 Youtube Video links for Beginners to get started with Open Source

### ISSUE THREAD

**Issue by Varun270** [girlscript/winter-of-contributing#400]
A Collection of all resources - Videos, Blogs link for a beginner to get started with Open Source. From generating their first PR to best practices to follow in Open Source.
## NOTE :
- Changes should be made inside the `Open_Source/Respective_Section` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

**Comment by Varun270** [comment]
@Aryamanz29 Please assign me this issue , I would like to work on this.

**Comment by Aryamanz29** [comment]
@Varun270  Assigning this to you, Happy Doc 🎉🎉

**Comment by Varun270** [comment]
@Aryamanz29 I have checked out to Open Source branch and there are different sections from 1-5 with documents in it. In which section should I made my document. Is there any rule for sections or I can create  my doc file in any of them?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I have checked out to Open Source branch and there are different sections from 1-5 with documents in it. In which section should I make my document. Is there any rule for sections or I can create my doc file in any of them?

Put your doc in `section-5` @Varun270

**Comment by Varun270** [comment]
@Aryamanz29 I have Opened the PR, Kindly review it once you get time.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I have Opened the PR, Kindly review it once you get time.

I Dont see any PR??

**Comment by Varun270** [comment]
Here it is showing this -
<img width="649" alt="commit" src="https://user-images.githubusercontent.com/75975268/133886923-8d2793fb-7046-446a-a751-846283b6dbb6.png">

**Comment by Varun270** [comment]
When I tried  Creating a PR, I didn't get the Compare and Pull request option, and when I navigated back here I saw the above commit So I thought my PR has been generated. What should I do now to regenerate the same PR?

**Comment by Varun270** [comment]
I think If I have to create a new PR, I will have to do some minor changes in the doc file so that I could commit them.

**Comment by Varun270** [comment]
> > I think If I have to create a new PR, I will have to do some minor changes in the doc file so that I could commit them.
> 
> Close that PR and create a new one and make sure to put your doc in their corresponding section with proper naming convention

Alright, I will do it right now

**Comment by Varun270** [comment]
@Aryamanz29 I really don't understand what the problem is here, I have done numerous contributions created several PR's but this time I am not able to create a PR. I am able to commit the changes whenever I push those changed git shows that it has been pushed successfully but when I Open the forked repo I am not getting the Compare and Pull request option. I tried what you suggested using the contribute button to open PR
<img width="380" alt="faded" src="https://user-images.githubusercontent.com/75975268/133918256-f5bc61a4-e464-4181-acbd-c835c39620a5.png">
<img width="806" alt="git log" src="https://user-images.githubusercontent.com/75975268/133918266-2321cc68-f087-48b1-abbf-d4031314314c.png">
. I am not getting that option either I have synced my local repo with remote repo twice. I am confused.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I really don't understand what the problem is here, I have done numerous contributions created several PR's but this time I am not able to create a PR. I am able to commit the changes whenever I push those changed git shows that it has been pushed successfully but when I Open the forked repo I am not getting the Compare and Pull request option. I tried what you suggested using the contribute button to open PR
> <img alt="faded" width="380" src="https://user-images.githubusercontent.com/75975268/133918256-f5bc61a4-e464-4181-acbd-c835c39620a5.png">
> <img alt="git log" width="806" src="https://user-images.githubusercontent.com/75975268/133918266-2321cc68-f087-48b1-abbf-d4031314314c.png">
> . I am not getting that option either I have synced my local repo with remote repo twice. I am confused.

Join discord voice channel

**Comment by Varun270** [comment]
Sorry, I wasn't online at that time, Tell me whenever you are free I will join it at that time.

**Comment by Aryamanz29** [comment]
Join me @discord voice channel today after 11 PM

**Comment by Varun270** [comment]
> Join me @discord voice channel today after 11 PM

Yeah sure, Thank you for your time
