### ISSUE TITLE
OpenSource: 5.7 Create your own open source project

### ISSUE THREAD

**Issue by Kajol-Kumari** [girlscript/winter-of-contributing#401]
## **Deliverables -** 👇

- [ ] Create **a new repo under your own GitHub account.**
- [ ]  `Make 3 sample pages` **[eg - About open source, Version control system, about git/GitHub, etc] with whatever language you are comfortable with [may it be HTML, CSS, react, angular, etc.]**
- [ ] Host `the same repo/website` using `GitHub pages, Heroku or netlify` **[Whichever platform you are comfortable with]**
- [ ] `Create a new file` named projects made under this  repo **[if the file is already present no need to create again]**
- [ ] ` Paste you're hosted and GitHub URLs` in it and `create a PR`

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  `Multiple Contributors` can work on this
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Asmit2952** [comment]
I want to work on this!!

**Comment by RK1905101** [comment]
can I also work in this issue?

**Comment by Aryamanz29** [comment]
I have assigned @RK1905101 @Asmit2952

**Comment by Asmit2952** [comment]
I had one doubt, instead of creating 3 pages, can we create a simple app (todo app in javascript)?

**Comment by Aryamanz29** [comment]
> I had one doubt, instead of creating 3 pages, can we create a simple app (todo app in javascript)?

@Kajol-Kumari

**Comment by baazis** [comment]
Hey Can I also work on this??

**Comment by Kajol-Kumari** [comment]
> I had one doubt, instead of creating 3 pages, can we create a simple app (for eg: todo app in javascript)?

Yes @Asmit2952 you can create a simple app to host but it would be better if you could include some ages about open source as well

**Comment by mayankkuthar** [comment]
@Aryamanz29 @Kajol-Kumari I would also like to work on this one, Please Assign me too.

**Comment by Soumili1818** [comment]
May I have the honour of working on this issue?

**Comment by paras-saxena11** [comment]
I want to contribute in this please assign me

**Comment by Kajol-Kumari** [comment]
@mayankkuthar @Soumili1818 @paras-saxena11 please go ahead with this issue.
Happy learning :)

**Comment by priyaa-rawat** [comment]
May I work on this too
Priya Rawat 
batch-4
@Aryamanz29 @Kajol-Kumari

**Comment by Aryamanz29** [comment]
@priyaa-rawat  Assigning this to you, Happy Documenting 🎉

**Comment by AkshataABhat** [comment]
Hey, can I work on this issue? @Aryamanz29 @Kajol-Kumari

**Comment by ELLIPSIS009** [comment]
Hey can i contribute to this issue? @Aryamanz29 @Kajol-Kumari

**Comment by Tiwarisonal19** [comment]
Hey, I too want to work on this issue, can you assign this to me? @Aryamanz29

**Comment by akashshukla7458** [comment]
Hey , i would like to contribute in this @Aryamanz29

**Comment by suvangi2205** [comment]
Can I contribute on this issue, Ma'am? @Kajol-Kumari @Aryamanz29

**Comment by Aryamanz29** [comment]
Assigning this to you both @suvangi2205  @akashshukla7458

**Comment by Aryamanz29** [comment]
REFERENCE PR  ✅ :- https://github.com/girlscript/winter-of-contributing/pull/530

**Comment by amanraj-iit** [comment]
I want to contribute in this please assign me

**Comment by Aryamanz29** [comment]
@Gur-jot  @amanraj-iit  Sure , Happy Learning 🎉🎉

**Comment by Asmit2952** [comment]
Hey, @Aryamanz29  I want to contribute to this, can you assign this to me?

**Comment by Asmit2952** [comment]
> @Gur-jot @amanraj-iit Sure, Happy Learning 🎉🎉 I think I can't assign more than 10 contributors to a particular issue so you can start working on it.

Ohh, Ohkk, so I can send a PR right? @Aryamanz29

**Comment by Harshit-Poddar90** [comment]
pls assign it to me

**Comment by A-GHOSH-dev** [comment]
I would like to contribute in this please.

**Comment by Aryamanz29** [comment]
@Harshit-Poddar90  @A-GHOSH-dev  Sure , Go ahead

**Comment by afreenabegum** [comment]
I would like to work on this. Can you assign it to me!!
@Aryamanz29 

Afreena begum
open source batch-1.

**Comment by Aryamanz29** [comment]
@aaryan078  Go ahead 🎉🎉

**Comment by Aryamanz29** [comment]
Closing this issue now, Thanks everyone for contributing  🎉🎉
