### ISSUE TITLE
DSA 1.1.3.1 Arrays: Range Queries (Sum/Product)

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#403]
## Description
Explain Range Sum and Range Product Queries.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by siddhi-244** [comment]
Can I try it

**Comment by siddhi-244** [comment]
Documentation

**Comment by kamleshjoshi8102** [comment]
Hi I am Interested for Documentation 
DSA-batch-5
Kamlesh Joshi

**Comment by siddhi-244** [comment]
DSA BATCH 1

**Comment by Ayushi2811** [comment]
I would like to contribute for this in documentation
Ayushi Chauhan
Batch-1
Kindly assign it to me.

**Comment by GenMech** [comment]
@nimisha-yadav Hey i have a very good hold on Arrays and i would like to contribute and prepare a well documented sheet on this topic and as is see there is no assignees yet , it would be great if you assign it to me.

**Comment by motasimmakki** [comment]
For the documentation section kindly assign this issue to me @nimisha-yadav.
I will work on this with my full interest give you a satisfactory result.

**Motasim (DSA Batch-01)**

**Comment by nimisha-yadav** [comment]
> Hi I am Interested for Documentation
> DSA-batch-5
> Kamlesh Joshi

Assigning this issue to you @kamleshjoshi8102, all the best!

**Comment by siddhi-244** [comment]
> > Hi I am Interested for Documentation
> > DSA-batch-5
> > Kamlesh Joshi
> 
> Assigning this issue to you @kamleshjoshi8102, all the best!

But I was the first one to ask !

**Comment by kamleshjoshi8102** [comment]
> > Hi I am Interested for Documentation
> > DSA-batch-5
> > Kamlesh Joshi
> 
> Assigning this issue to you @kamleshjoshi8102, all the best!

Thanks a Lot! 😄

**Comment by nimisha-yadav** [comment]
> 
> But I was the first one to ask !

As it was mentioned, you need to put the name and batch so the first person who followed the guide got the issue. Don't worry, there will be a lot of issues to contribute :D

**Comment by nimisha-yadav** [comment]
@kamleshjoshi8102, any updates?

**Comment by kamleshjoshi8102** [comment]
> @kamleshjoshi8102, any updates?

Please review I have added 2 functions for PrefixSum and Range-product
