### ISSUE TITLE
CPP: Ternary search in c++

### ISSUE THREAD

**Issue by Rohit-dubey45** [girlscript/winter-of-contributing#4033]
### Description

Here , i will provide detail documentation of ternary search in c++.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged !
