### ISSUE TITLE
DSA 1.1.3.2 Arrays: Range Queries (LCM/GCD)

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#404]
## Description
Explain LCM/GCD Queries.

## Task
- [x] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by siddhi-244** [comment]
DSA Batch 1
I want to contribute in documentation

**Comment by kamleshjoshi8102** [comment]
Hi I am Interested for Documentation
DSA-batch-05
Kamlesh Joshi

**Comment by Ayushi2811** [comment]
I would like to contribute for this in documentation
Ayushi Chauhan
Batch-1
Kindly assign it to me.

**Comment by GenMech** [comment]
@nimisha-yadav  Hey i have a very good hold on Arrays and i would like to contribute and prepare a well documented sheet on this topic and as is see there is no assignees yet , it would be great if you assign it to me.
Gitesh Pareek
Batch-1

**Comment by Harsh-Chaudhary7** [comment]
I have been eagerly waiting to contribute and would love to work on arrays related issues as i got pretty good hold on the topic.
**Harsh Chaudhary
DSA Batch 3**

**Comment by motasimmakki** [comment]
For the documentation section kindly assign this issue to me @nimisha-yadav.
I will work on this with my full interest give you a satisfactory result.

**Motasim (DSA Batch-01)**

**Comment by nimisha-yadav** [comment]
> DSA Batch 1
> I want to contribute in documentation

Assigning this to you @siddhi-244 but don't forget to put your full name in future issues. All the best!

**Comment by siddhi-244** [comment]
> > DSA Batch 1
> > I want to contribute in documentation
> 
> Assigning this to you @siddhi-244 but don't forget to put your full name in future issues. All the best!

Ok maam

**Comment by mansisingh2803** [comment]
I would like to work on this issue pls assign this issue to me
Mansi Singh
DSA batch - 4

**Comment by mansisingh2803** [comment]
For type video and audio

**Comment by siddhi-244** [comment]
Please check my pr!

**Comment by siddhi-244** [comment]
Please review my pr !

**Comment by nimisha-yadav** [comment]
> 
> 
> I would like to work on this issue pls assign this issue to me
> Mansi Singh
> DSA batch - 4

Assigning you @mansisingh2803 for audio and video, all the best!

**Comment by purohitmansi** [comment]
Name: Mansi
Batch: 4
Please do assign this to me.

**Comment by nimisha-yadav** [comment]
> 
> 
> Name: Mansi Batch: 4 Please do assign this to me.

Assigning this to you for audio and video @purohitmansi, all the best!

**Comment by purohitmansi** [comment]
> > Name: Mansi Batch: 4 Please do assign this to me.
> 
> Assigning this to you for audio and video @purohitmansi, all the best!

Thank you Nimisha

**Comment by rohit-goyal** [comment]
I would like to work on documentation part of these issue
Name : Rohit Goyal 
Batch : DSA Batch 2

**Comment by nimisha-yadav** [comment]
@purohitmansi final call. Submit the PR within 2 days else the issue will be closed.
