### ISSUE TITLE
Frontend : CSS general rule in document form

### ISSUE THREAD

**Issue by Pranshu321** [girlscript/winter-of-contributing#4046]
### CSS general rule
In this i deeply explain about that should be followed while writing the css , which benefit's reader and developer for understanding of code of css. 

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by brassgolem-25** [comment]
@Pranshu321 same issue is opened way before. Check it here #2313

**Comment by Pranshu321** [comment]
> @Pranshu321 same issue is opened way before. Check it here #2313 and a PR too #3355

Sorry ..... I will be closing this
