### ISSUE TITLE
Frontend With Framework - Introduction to Vue

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#405]
### **NEED TO CONTAIN**

*  What is Vue.js
*  Why Vue.js
*  Advantage of Vue.js
*  Dis Advantages of Vue.js

can take referance form [https://vuejs.org/v2/guide/](url)

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ Vue inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by YASHMAROO** [comment]
Sir I would like to work on this documentation.

**Comment by anandhu720** [comment]
@YASHMAROO sure.I will assgin you

**Comment by YASHMAROO** [comment]
Sir, I would have to make my PR for this documentation in the Vue folder of the Frontend with the framework branch?

**Comment by anandhu720** [comment]
@YASHMAROO Yes there is a Week1 folder in it,Do it there

**Comment by YASHMAROO** [comment]
Ok, sir.

**Comment by baazis** [comment]
Can more that 1 members work on a issue?

**Comment by anandhu720** [comment]
@baazis he is doing documentation,So if you are intrested in creating Video in same,I can assign you.As per now we are assigning only one for one issue

**Comment by baazis** [comment]
@anandhu720  I would Love to do it.

**Comment by anandhu720** [comment]
@baazis So you just make a video about this topic.I am assigning you that task
