### ISSUE TITLE
Detect Loop in Singly Linked List

### ISSUE THREAD

**Issue by VARUN-K-BANSAL** [girlscript/winter-of-contributing#4093]
### Description

documentation for detecting whether a loop is present or not in the Singly Linked List.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged
