### ISSUE TITLE
ML 3.1 What is Clustering? Validate its necessity using real-world applications. (A)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#4098]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_What is Clustering? Validate its necessity using real-world applications._**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). **Please note this issue is for audio contribution only**

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Unsupervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ron352** [comment]
Sarmistha Sarna
Batch :01
https://github.com/ron352
type : audio

**Comment by Mohdtalibakhtar** [comment]
Mohd Talib Akhtar 
Batch : 03
Github : https://github.com/Mohdtalibakhtar
Type : Documentation

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Machine Learning
Type-Audio
Batch-6
Issue Number-                                                                                                                                                      
Contribution Approaches-what is clustering, different algorithms of clustering, main principle behind clustering, sample usecases in real life

**Comment by abhisheks008** [comment]
@ron352 Issue assigned!
