### ISSUE TITLE
ML 3.1 What is Clustering? Validate its necessity using real-world applications. (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#4099]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_What is Clustering? Validate its necessity using real-world applications._**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). **Please note this issue is for video contribution only**

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Unsupervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
Hello, I am M. Ashish Reddy, I would like to work on this issue. 
Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
contribution you want to make : video

**Comment by ashish-reddy-20-08** [comment]
@geeythree @abhisheks008 , Can you please assign me this issue, I am ready with the PR.

**Comment by geeythree** [comment]
@ashish-reddy-20-08 You've been assigned, buddy. 😄

**Comment by ashish-reddy-20-08** [comment]
@geeythree @Isha307 @abhisheks008 , Can you please evaluate the PR.
PR link: https://github.com/girlscript/winter-of-contributing/pull/4133
