### ISSUE TITLE
Cybersecurity: 1.5 What is Physical Security?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#41]
## Description
Physical security is very important to any organization/company, including fences, laser alarms, etc.
Explain more about What is Physical Security?
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by astelrastogi** [comment]
I want to work on this issue

**Comment by Anant1711** [comment]
> I want to work on this issue

Okay
I'm assigning this to you👍

**Comment by Anant1711** [comment]
@astelrastogi 
Please submit your work by Today itself, your deadline was of 4 days!
Otherwise, I have to transfer this task to someone else!

**Comment by astelrastogi** [comment]
Created a PR: https://github.com/girlscript/winter-of-contributing/pull/617

**Comment by Nupurksk** [comment]
@astelrastogi There is a plag of 92%!! 
kindly check this again....Plag should not be there but we can have max of 25% not more than this any how.

**Comment by Nupurksk** [comment]
> Created a PR: #617

@astelrastogi There is a plag of 92%!! 
kindly check this again....Plag should not be there but we can have max of 25% not more than this any how.

**Comment by astelrastogi** [comment]
I've made the changes, pls check https://github.com/girlscript/winter-of-contributing/pull/617

**Comment by Nupurksk** [comment]
> I've made the changes, pls check https://github.com/girlscript/winter-of-contributing/pull/617

_Now it's Perfectly Fine_
