### ISSUE TITLE
ML 3.5: Hierarchical Clustering (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#4101]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

▶️ This issue will helps readers in acquiring all the knowledge that one needs to know about ---- Hierarchical Clustering
### Implement Support Vector Machine without using any standard ML library like scikit-learn or more.

🔴 To get assigned to this issue, add your Batch Numbers mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : Machine Learning

🔴🟡 Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the Machine Learning/Machine_Learning/Unsupervised_Machine_Learning Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**

✅ To be Mentioned while taking the issue :
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by parvatijay2901** [comment]
Name: Parvati Jayakumar
Batch: 3
GitHub profile: https://github.com/parvatijay2901
Contribution type: Audio

Please check the PR I've created (https://github.com/girlscript/winter-of-contributing/pull/4157). If that is fine, please assign this to me. Thank you.

**Comment by Isha307** [comment]
@parvatijay2901 you can work on this.
