### ISSUE TITLE
ML 3.9 : Outlier Detection using Random Forest - Isolation Forest (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#4104]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Outlier Detection using Random Forest - Isolation Forest_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Unsupervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hrugved06** [comment]
/assign
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation
I would like to work on it

**Comment by abhisheks008** [comment]
Sorry @hrugved06 you've been unassigned due to violating the rules of not to use `/assign`

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation

**Comment by abhisheks008** [comment]
This issue will not be assigned to you. Go with another one and maintain proper guidelines. @hrugved06

**Comment by Yugal41735** [comment]
Yugal Agarwal
Github => https://github.com/Yugal41735
Batch - 1
Contribution => documentation

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
iwould like to contribute to this issue.. plz assign it to me.

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
type-documentation
iwould like to contribute to this issue.. plz assign it to me.

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
I would like to contribute to this issue.. plz assign it to me.

**Comment by rahulsinghal1904** [comment]
I would like to work on this issue.
Name : Rahul Singhal
Batch : 1
Github Profile link: https://github.com/rahulsinghal1904
Approach : Implementation of outlier detection using Random Forest.
Type : Documentation

**Comment by Subhrato20** [comment]
I would like to work on this issue.
Name : Subhrato Som
Batch : 2
Type : Documentation

**Comment by abhisheks008** [comment]
issue assigned to @Yugal41735

**Comment by Yugal41735** [comment]
@abhisheks008  sorry due to my mid sem i was not able to give u any update, and yup i am working on it, if it possible could u give me time till tomorrow.

**Comment by abhisheks008** [comment]
@Yugal41735 No worries complete this by tomorrow positively!

**Comment by Yugal41735** [comment]
@abhisheks008  I am unable to checkout to Machine Learning  branch after cloning the repo
