### ISSUE TITLE
ML 3.5: Hierarchical Clustering (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#4105]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

▶️ This issue will helps readers in acquiring all the knowledge that one needs to know about ---- Hierarchical Clustering 
### Implement Support Vector Machine without using any standard ML library like scikit-learn or more.

🔴 To get assigned to this issue, add your Batch Numbers mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : Machine Learning

🔴🟡 Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the Machine Learning/Machine_Learning/Unsupervised_Machine_Learning Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**

✅ To be Mentioned while taking the issue :
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video
**
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
@Isha307 , Can you please assign me this issue.
Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08

**Comment by abhisheks008** [comment]
one issue at a time @ashish-reddy-20-08

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , I have completed the PR for the first issue 
PR LINK: https://github.com/girlscript/winter-of-contributing/pull/4133

**Comment by ashish-reddy-20-08** [comment]
@abhisheks008 , Can you please assign sir , As i have done PR also sir.

**Comment by Isha307** [comment]
okay

**Comment by geeythree** [comment]
@ashish-reddy-20-08 Please wait until we review the PR.

**Comment by ashish-reddy-20-08** [comment]
@geeythree @Isha307 @abhisheks008 , Mam and sir others will take up the good issues if we dont comment soon  , right mam and sir, that is the reason i have made the PR soon by completing the first issue and now asking for the second one .
Can you please make it soon mam and sor , as i want to work more and learn new things , if the team helps me by making the merging soon then it would be help me mam and sir.

**Comment by geeythree** [comment]
@ashish-reddy-20-08 issue has already been assigned to you. Also, you need not address us as Sir or Ma'am 😄

**Comment by ashish-reddy-20-08** [comment]
@Isha307 , Mam can you please evaluate my PR soon. So that I can work on other issues. 
Name: M. Ashish Reddy
Batch - 2
PR LINK : https://github.com/girlscript/winter-of-contributing/pull/4151
