### ISSUE TITLE
ML 3:2: k-means Clustering (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#4111]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_k-means Clustering_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). **Please note this issue is for VIDEO contribution only**

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Unsupervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ShubhamPatel01** [comment]
Hello, I would like to work on this issue
Name: Shubham Patel
Batch: 1
GitHub id: https://github.com/ShubhamPatel01
Approach: What is k means clustering, how to implement it, and applications of k means clustering algorithm.

**Comment by abhisheks008** [comment]
Sorry @m0hit-kumar  you've been unassigned due to violating the rules of not to use /assign

**Comment by abhisheks008** [comment]
@ShubhamPatel01 This is a video contribution, would you like contribute in this?

**Comment by ShubhamPatel01** [comment]
> @ShubhamPatel01 This is a video contribution, would you like contribute in this?

Yes, I would like to contribute

**Comment by geeythree** [comment]
@ShubhamPatel01 Amazing! This issue has been assigned to you. Please make sure that you complete the work and make a PR within 3 days.

**Comment by m0hit-kumar** [comment]
@geeythree can you elaborate what I did wrong or what violation."To get assigned to this particular issue please use /assign ". I just follow this

**Comment by geeythree** [comment]
@mohit355 Hey, we had asked all the contributors in ML domain to comment on the issues to get them assigned. The thing is, in some cases somebody might have already commented on the issue and a new person might just come in and self assign the issue, then the first person to have commented would not get a fair chance. We just want to make it fair for everyone. There are plenty more issues that you could contribute to. Please check them out. 😄

**Comment by m0hit-kumar** [comment]
> @mohit355 Hey, we had asked all the contributors in ML domain to comment on the issues to get them assigned. The thing is, in some cases somebody might have already commented on the issue and a new person might just come in and self assign the issue, then the first person to have commented would not get a fair chance. We just want to make it fair for everyone. There are plenty more issues that you could contribute to. Please check them out. 😄

but here I was the one to comment first.

**Comment by ShubhamPatel01** [comment]
> > @mohit355 Hey, we had asked all the contributors in ML domain to comment on the issues to get them assigned. The thing is, in some cases somebody might have already commented on the issue and a new person might just come in and self assign the issue, then the first person to have commented would not get a fair chance. We just want to make it fair for everyone. There are plenty more issues that you could contribute to. Please check them out. 😄
> 
> but here I was the one to comment first.

Please check the discord pinned messages, you will understand why you were not given the issue.
