### ISSUE TITLE
ML 3.11 : Implement K-Means without using any ML Library like scikit-learn or more (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#4119]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Implement K-means without using any ML Library like scikit learn or, more_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Unsupervised_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Coding with proper visualization)
******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Ruchika-20** [comment]
I would like to work on this issue

**Comment by abhisheks008** [comment]
Sorry @Ruchika-20  you've been unassigned due to violating the rules of not to use /assign

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation
I would like to work on this issue

**Comment by AdityaStark7** [comment]
Aditya Kumar
batch: 04
Documentation

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
I would like to contribute to this issue.. plz assign it to me.

**Comment by rahulsinghal1904** [comment]
I would like to work on this issue.
Name : Rahul Singhal
Batch : 1
Github Profile link: https://github.com/rahulsinghal1904
Approach : Intro about K-means and its required implementation without scikit-learn
Type : Documentation

**Comment by abhisheks008** [comment]
@hrugved06 Issue assigned to you.

**Comment by Ruchika-20** [comment]
> Sorry @Ruchika-20 you've been unassigned due to violating the rules of not to use /assign

I've used the label /assign sir....kindly have a look

**Comment by abuzarbagewadi** [comment]
Abuzar Bagewadi
Batch: 2
Github Profile: https://github.com/abuzarbagewadi
Documentation
I would like to work on this issue

**Comment by hrugved06** [comment]
@abhisheks008,  I have created a PR, please do check it :-D
