### ISSUE TITLE
3.8 : What is Outlier Detection. How is it important in ML? (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#4129]
### 📌  Issues for Week 3
Welcome to 'ML' Team, good to see you here

▶️ This issue will helps readers in acquiring all the knowledge that one needs to know about ---- Outlier Detection
### Implement Support Vector Machine without using any standard ML library like scikit-learn or more.

🔴 To get assigned to this issue, add your Batch Numbers mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : Machine Learning

🔴🟡 Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the Machine Learning/Machine_Learning/Unsupervised_Machine_Learning Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

✅ To be Mentioned while taking the issue :
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AdityaNikhil** [comment]
**Full name** : Aditya Nikhil
**Batch Number** : 2
**GitHub Profile Link** : github.com/adityanikhil
**Which type of Contribution you want to make** :
Audio

**Comment by PurviBhoyar21** [comment]
Hello Supervisors and mentors
I am Purvi Bhoyar from ML batch 1
Please assign me this issue
I would love to work 
Thank you

**Comment by abhisheks008** [comment]
Hey @AdityaNikhil One issue at a time. Please complete your previous issue first!

**Comment by abhisheks008** [comment]
@PurviBhoyar21 This is an audio contribution, would you like to work in this?

**Comment by PurviBhoyar21** [comment]
Yes
PLEASE  @abhisheks008 
assign me

**Comment by abhisheks008** [comment]
Ok then Issue assigned to @PurviBhoyar21
