### ISSUE TITLE
Data Science with Python : Introduction to Keras 

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#416]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Introduction to Keras. Tutorial to Keras and how it's Implied using sample code

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Deep Learning

Mentors Assigned : [Kareem Negm](https://github.com/Kareem-negm) / [Arya Patel](https://www.github.com/AryaPatel1111)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by freny24** [comment]
Name: Freny
serial no: 707
Type: Documentation
Approach: Explaining Keras using sample codes in python

**Comment by prathimacode-hub** [comment]
Issue is assigned to @freny24 for documentation

**Comment by Kareem-negm** [comment]
Hello @prathimacode-hub  , Please put me up as an Assignees

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
