### ISSUE TITLE
Data Science with Python : DBSCAN Algorithm

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#4160]
Welcome to 'DSWP' Team, good to see you here

With this issue, readers will get introduced with core information to DBSCAN Algorithm along with sample code completely in a effective way.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Kareem Negm / Aishani Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by uttarabahad** [comment]
Name-Uttara Bahad
Serial No-328
Type: Documentation
Approach-Introduction, Sample example code with explanation, Advantages/ Disadvantages, Use.

**Comment by prathimacode-hub** [comment]
Issue assigned to @uttarabahad

**Comment by ron352** [comment]
Mam is it up for audio?.

**Comment by Kareem-negm** [comment]
Hello @prathimacode-hub , please assigned me the issue

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution
