### ISSUE TITLE
[C_CPP]: Nested Function

### ISSUE THREAD

**Issue by vishnu95075** [girlscript/winter-of-contributing#4166]
## Function 
- Nested Function and its examples .
-  Nested Function using auto keyword

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by LegendSumeet** [comment]
assign me @vishnu95075

**Comment by LegendSumeet** [comment]
@mukeshmjn assign me

**Comment by Saviour1001** [comment]
Closing this issue as this is not the behaviour I was expecting from all you guys. Please understand the workflow and then start working, just commenting /assign haphazardly on all issues is not how it's supposed to be. Go through the resources provided in the #announcements channel of Discord. 
If still in doubt ping any mentor on Discord but don't act without thinking. 
@SudhansuuRanjan @mukeshmjn @LegendSumeet
