### ISSUE TITLE
Data Science with Python : K Medoid Algorithm

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#4169]
Welcome to 'DSWP' Team, good to see you here

With this issue, readers will get introduced with core information to K Medoid Algorithm along with sample code completely in a effective way.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Jivitesh Jain / Kareem Negm

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by photon149** [comment]
Name: Shiwansh Raj
- Batch: 10
- Sr. No: 368
- [GitHub Profile](https://github.com/photon149)
-  [x]  Documentation
- Approach: Introduction, properly commented code, images wherever required, proved conclusion
@prathimacode-hub , can you assign this to me manually , I have asked for the same on discord
 :)

**Comment by prathimacode-hub** [comment]
Issue assigned to @photon149 for documentation

**Comment by ShubhamPatel01** [comment]
Hello, could you assign this to me.
Name: Shubham Patel
Serial No. 104
Type: Video
Approach: Introduction to K medoid Algorithm, Working of K medoid algorithm and implementing it, And Application of K medoid  algorithm

**Comment by prathimacode-hub** [comment]
Issue assigned to @ShubhamPatel01 for video contribution
