### ISSUE TITLE
Data Science with Python : Elbow Method In KMeans Clustering

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#4171]
Welcome to 'DSWP' Team, good to see you here

With this issue, readers will get introduced with core information to Elbow Method In KMeans Clustering along with sample code completely in a effective way.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Dhruv Bajaj / Yash Goel

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ayushijindal** [comment]
Approach: Taking Exemplary dataset to make understand the concept
Format: documentation
Serial no:253

**Comment by prathimacode-hub** [comment]
Issue assigned to @ayushijindal for documentation

**Comment by ShubhamPatel01** [comment]
Hello, could you assign this to me.
Name: Shubham Patel
Serial No. 104
Approach: What is elbow method and why it is used.
Type: Video

**Comment by prathimacode-hub** [comment]
Issue assigned to @ShubhamPatel01 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
