### ISSUE TITLE
[Create New Issue]: Html_tables

### ISSUE THREAD

**Issue by VaishnaviPhadtare** [girlscript/winter-of-contributing#4179]
### Description

HTML_Tables 

what is html tables :-
Table - rows ,cells ,headers
basic styling for html tables

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by SudhansuuRanjan** [comment]
Do you really wanna work on it??

**Comment by VaishnaviPhadtare** [comment]
yes
