### ISSUE TITLE
Android - Java : 2.2 Button in Android

### ISSUE THREAD

**Issue by Kajal13081** [girlscript/winter-of-contributing#418]
1. What are buttons and types of buttons in android.
2. How to make android button more attractive?
3. XML Attributes of buttons in android
4. How to code and create buttons? 
5. Button examples.

**Comment by Kajal13081** [comment]
@VikasPandey121 Sir, I have created this issue. Can you please assign me this?

**Comment by Rohit-2602** [comment]
yes @Kajal13081 you can work on it

**Comment by Kajal13081** [comment]
> yes @Kajal13081 you can work on it

Can you assign me this and also mention the tags? @Rohit-2602

**Comment by Rohit-2602** [comment]
Mentor can't assign or add labels,
start working on it don't worry about labels and all

**Comment by Kajal13081** [comment]
> Mentor can't assign or add labels,
> start working on it don't worry about labels and all

Okay

**Comment by SouravKr2001** [comment]
I am interested in (documen...)

**Comment by Kajal13081** [comment]
> I am interested in (documen...)

Hey, This is already assigned to me. And only one person can work on one issue.

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development_With_Java/Android_UI_Widgets/` with the file name starting from 2.2 for instance `2.2 Button in Android`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.2.1`, `2.2.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by Kajal13081** [comment]
> Please keep these steps in mind while creating a pull request:
> 
> * use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
> * Your Contributing file should be in this directory `Android_Development_With_Java/Android_UI_Widgets/` with the file name starting from 2.2 for instance `2.2 Button in Android`
>   Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.2.1`, `2.2.2` etc
> * Create a new branch and push your PR on `Android_Development_With_Java` branch.
> * Pull request should contain only one commit
>   Note: If you have multiple commits then `squash` your commit.

**Comment by Rohit-2602** [comment]
@Kajal13081  can you please give a progress update about the issue and if you are facing any problem feel free to ask.

**Comment by Kajal13081** [comment]
> @Kajal13081 can you please give a progress update about the issue and if you are facing any problem feel free to ask.

I am done 80%. Work will be finished in 2-3 days more. Will definitely ask if facing any issue.

**Comment by Kajal13081** [comment]
@Rohit-2602 I have completed the doc. Just have to convert it in md. Will make pull request by tonight or tomorrow.

**Comment by Kajal13081** [comment]
@Rohit-2602 
made pull request #3849
