### ISSUE TITLE
Data Science with Python : Sentiment Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#419]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Sentiment Analysis. Tutorial to Sentiment Analysis and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Natural Language Processing

Mentors Assigned : [Nithin](https://github.com/Nithin-Reddy-02) / Gauri Bharadwaj

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by prathimacode-hub** [comment]
Issue assigned to @divya-chhoriya for documentation.

**Comment by farhan-naqvi** [comment]
Syed Farhan Naqvi
Serial Number: 454
Documentation

Approach: Sentiment analysis using NLTK

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub, Can you please assign me a video contribution for this mam. 
M. Ashish Reddy 
Batch -5 
Approach - A detailed explanation with examples

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution
