### ISSUE TITLE
Cybersecurity: 1.6 Importance of Physical Security?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#42]
## Description
Physical security is very important to any organization/company, including fences, laser alarms, etc.
Discuss the importance of physical security in the Cyberworld.
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by RK1905101** [comment]
I would like to take up this topic.

**Comment by Anant1711** [comment]
> I would like to take up this topic.

Okay! I'm assigning this to you!

**Comment by Anant1711** [comment]
@RK1905101 
please submit your work today itself, the deadline for any topic is 4 days!
Otherwise, I have to transfer this task to someone else.

**Comment by RK1905101** [comment]
Sir, actually I was having exams, and so that's why i was unable to do it...
Today is the last, which is at evening and so i'll complete it by tonight itself..
sorry for being delayed sir.

**Comment by Anant1711** [comment]
> Sir, actually I was having exams, and so that's why i was unable to do it...
> Today is the last, which is at evening and so i'll complete it by tonight itself..
> sorry for being delayed sir.

Okay!
Great ....
