### ISSUE TITLE
Map in  Python

### ISSUE THREAD

**Issue by Kalpana-Kathait11** [girlscript/winter-of-contributing#4202]
### Description

This issue is for use of map() in python.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Kalpana-Kathait11** [comment]
[README.md](https://github.com/girlscript/winter-of-contributing/files/7274125/README.md)

**Comment by Kalpana-Kathait11** [comment]
# Map() and filter() in Python




## Map() :
Map() is built-in function in python.The map function takes two input a function and iterable object.

**Syntax:** **map(function,iterator)** 

**Function:** It is  mandatory function to be given to map, which will be applied to all the elements available in the iterator.

**Iterator:** An iterable is compulsory object. It can be a list, a tuple, etc. We can pass multiple iterator objects to map() function.

**Return Value:** The map() function returns an object of map class. The returned value can be passed to functions like list,tuple,etc.

## 1. Example of Map() function :

```Python
def square(n):
    return n*n

num=[2,3,2,4,5,2,5]
result= map(square,num)
print(result) 
print(list(result))
```
**Output:** 

<map object at 0x7fb16f2e7cd0>

[4, 9, 4, 16, 25, 4, 25]

## 2. Passing multiple iterator to map :
```Python
def multi(n,n1):
    return n*n1

num=[2,3,2,4,5,2,5]
num1=[3,4,3,2,4,5,2]
result= map(multi,num,num1)
print(result) 
print(list(result))
```
**Output:**

<map object at 0x7f775d01a340>

[6, 12, 6, 8, 20, 10, 10]

## Filter():
filter is built-in function in python.It is used to filtered the data. It takes two argunment first is function and next is iterable. The first could be none if any function is not available.

**Syntax:** filter(function,iterable)

## 1. Example :

```Python
def div(n):
    return n%2==0
    
num=[4,3,3,34,34,45,23,345,34,45,56]
result=filter(div,num)

print(result)

print(list(result))
```
**Output:**
<filter object at 0x7f003cab9cd0>

[4, 34, 34, 34, 56]

**Return Value:** The filter function returns a sequence from those elements of iterable for which is True. 
  
## Contribution:
Kalpana-Kathait11

**Comment by adityabisoi** [comment]
Topic already covered. Closing this issue.
