### ISSUE TITLE
Recursion in Python

### ISSUE THREAD

**Issue by priyankapiba** [girlscript/winter-of-contributing#4206]
### Description

Recursion is essential in coding which reduces the time complexity as well as space complexity.
Add python code to demonstrate recursion.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyankapiba** [comment]
@adityabisoi please assign me this issue.

**Comment by adityabisoi** [comment]
Go ahead

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Python 
Batch-3  
Type-Audio
Issue Number-about recursion, ways to implement, importance, similarity with loops & iterations

**Comment by priyankapiba** [comment]
> Go ahead

Which mentor is assigned to me @adityabisoi ?

**Comment by adityabisoi** [comment]
@hritikksingh Is the mentor of this issue

**Comment by BhaswatiRoy** [comment]
> @hritikksingh Is the mentor of this issue

okay sir thank you
