### ISSUE TITLE
Python : 3.2 Operators: Comparison operators and Logical operators

### ISSUE THREAD

**Issue by tejas342** [girlscript/winter-of-contributing#421]

**Comment by tejas342** [comment]
@adityabisoi i want to contribute in this by documentation.
Tejas Prajapati (Python batch-6)

**Comment by Yukti-20** [comment]
I can contribute for Documentation and Video 
Batch - 4
Documentation and Video
@adityabisoi

**Comment by vkaash-sharma** [comment]
I want to contribute to this issue for documentation.
i can share all detailed information of the topic via documents

**Comment by adityabisoi** [comment]
Already cvered in https://github.com/girlscript/winter-of-contributing/issues/412
