### ISSUE TITLE
Android Java : Add Firebase to Android project

### ISSUE THREAD

**Issue by saloni33** [girlscript/winter-of-contributing#4218]
### Description

Documentation on how to integrate firebase with the android project

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saloni33** [comment]
can i work on this issue

**Comment by LegendSumeet** [comment]
@saloni33 assign me
