### ISSUE TITLE
Queue Data Structure

### ISSUE THREAD

**Issue by tandrimasingha** [girlscript/winter-of-contributing#4224]
### Description

Write a program of implementation of Queue Data Structure with proper commenting the program

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on this in C++.
