### ISSUE TITLE
[Create New Issue]: Infix to Postfix Conversion

### ISSUE THREAD

**Issue by shrutigrover25** [girlscript/winter-of-contributing#4227]
### Description

Given an infix expression, you have to convert it into postfix.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purohitmansi** [comment]
Please do assign this to me. I would like to work on this.
