### ISSUE TITLE
Data Science with Python : Data Visualizations with Seaborn

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#423]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Data Visualizations with Seaborn. Tutorial to Data Visualizations with Seaborn and how it's applied visually.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualizations

Mentors Assigned : [Kareem Negm](https://github.com/Kareem-negm) / [Shivang Dubey](https://github.com/shivangdubey)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Shashankkrj** [comment]
@prathimacode-hub I would like to work on this issue. Please assign me this issue.

Type : Documentation
Sr. No: 968

**Comment by prathimacode-hub** [comment]
Ok, but do let me know of your approach as well of how you're going to proceed. @Shashankkrj

**Comment by KhushiKV** [comment]
@prathimacode-hub I would like to bring to your notice that in cab=se this issue is not yet assigned to anyone, I would be happy to work on it.
Sr. No. - 568
Type Preference 1: Documentation
Type Preference 2: Video
I propose to write down short notes along with code examples in a googleColab notebook, to demonstrate various funcgtionalisties available in Seaborn, the different kinds of plots etc. This would be for Documentation, and in case I get the video option, I will use the same Notebook and demonstrate it live in a video with some explanantions.
Thankyou.

**Comment by prathimacode-hub** [comment]
Ok, issue is assigned to @KhushiKV for documentation.

@Shashankkrj As you haven't provided the approach, issue is been assigned to next person in queue. Next time along with the details also add up your approach you would be proceeding with. There are many more issue to come.

**Comment by prathimacode-hub** [comment]
> Ok, issue is assigned to @KhushiKV for documentation. Should I add you up for Video as well?
> 
> @Shashankkrj As you haven't provided the approach, issue is been assigned to next person in queue. Next time along with the details also add up your approach you would be proceeding with. There are many more issue to come.

**Comment by KhushiKV** [comment]
Thank you for considering my request. Since you asked for video as well, I would like to ask you that if I contribute to both documentation and video, will they be considered as two separate contributions?

**Comment by prathimacode-hub** [comment]
@KhushiKV Sorry for the inconvenience, issues had set up double.  Can you mind changing up to an another issue as [this issue](https://github.com/girlscript/winter-of-contributing/issues/382) is already created earlier and assigned.

**Comment by KhushiKV** [comment]
Oh, no problem..thanks

**Comment by prathimacode-hub** [comment]
@KhushiKV If you like to work on any particular topic, you can let me know so that I create an issue of the topic and assign it to you directly.

**Comment by KhushiKV** [comment]
> @KhushiKV If you like to work on any particular topic, you can let me know so that I create an issue of the topic and assign it to you directly.

Ohkay, thankyou very much...If possible I would like to work on 'Data Visualisations using Matplotlib'.

**Comment by prathimacode-hub** [comment]
Sure, issue would be created and assigned to you directly. @KhushiKV

**Comment by KhushiKV** [comment]
Thank you very much once again...I would love to work on it. 
Will it be one contribution as Documentation, or 2 contributions separately as Documentation and Video?

**Comment by prathimacode-hub** [comment]
> Thank you very much once again...I would love to work on it.
> Will it be one contribution as Documentation, or 2 contributions separately as Documentation and Video?

It will be as 1 contribution, since this as a whole is 1 issue. But PR's and issues would be tagged up with Doc and Video label, so team would be knowing that you had done both. @KhushiKV

**Comment by KhushiKV** [comment]
Okay got it,..please assign me for Documentation.

**Comment by prathimacode-hub** [comment]
Ok, comment on the issue $445 created just. So that i can assign you as a assignee. @KhushiKV

**Comment by BhaswatiRoy** [comment]
I am bhaswati roy from dswp batch 19
I would like to contribute for this.

**Comment by ProMinato500** [comment]
I would like to work on this issue which is issue no. #423
Name - Pradipta Nandi
Sno - 250
Documentation

**Comment by nakshatra-garg** [comment]
S.no 609
I would like to work on the documentation part of this issue.
Approach:
Explain basic code to get started with seaborn
Show various seaborn visualization tools
Show different types of charts and plots

**Comment by Khushi-Shah-1** [comment]
If this issue is not yet assigned to anyone, I would be love to work on it.
Sr. No. - 630
Preference 1: Documentation
Preference 2: Video
I will show various functionalities available and plots we can make in seaborn. Along with the code, I will write comments on what each line is doing. 
Thank you.

**Comment by Khushi-Shah-1** [comment]
@prathimacode-hub If this issue is already assigned, I would like to work on the topic "LightGBM algorithm". Can the issue be created?

**Comment by tewarigargi** [comment]
Sr. No. - 752
Name: Gargi Tewari
Preference 1: Documentation
I will show various functions available and plots that are inbuilt and also when which plot is more appropriate. I will show these via code and comments. 
Thank you.

**Comment by Kareem-negm** [comment]
why this issue has been closed @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Its because, issue was duplicated. @Kareem-negm
