### ISSUE TITLE
Hand Made Graphs Visualization using Cutecharts Library

### ISSUE THREAD

**Issue by SaloniThete** [girlscript/winter-of-contributing#4241]
### Description

A detailed explanation of Hand Made Graphs Visualization using Cutecharts Library with examples.
Fixes #4162

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by m0hit-kumar** [comment]
i will love to contribute pls assign it to me
