### ISSUE TITLE
Data Science with Python : GeoSpatial Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#426]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in get familiarity with GeoSpatial Analysis. Tutorial to GeoSpatial Analysis and how it's applied using visual analysis.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualization

Mentors Assigned : [Shivang Dubey](https://github.com/shivangdubey) / [Yash Goel](https://github.com/Yash621)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by JRManasa** [comment]
J R Manasa 
Serial No. 
Documentation 
Batch 521

**Comment by prathimacode-hub** [comment]
Kindly let me know of your approach. @JRManasa

**Comment by JRManasa** [comment]
Introduction to GeoPandas, different data structures ,reading and writing files

**Comment by JRManasa** [comment]
Basic Intro to GeoPandas, diff data structures, reading and writing files and  mapping tools

**Comment by prathimacode-hub** [comment]
Ok, issue assigned to @JRManasa for documentation.

**Comment by shivangdubey** [comment]
@JRManasa any updates on the documentation?

**Comment by JRManasa** [comment]
Hello sir,
kindly guide on how to send m updates please?
Should I send my .ipynb file or just explain what I have done till now ?
Also should I send my updates on discord or here sir ?

**Comment by shivangdubey** [comment]
> Hello sir,
> kindly guide on how to send my updates please?
> Should I send my .ipynb file or just explain what I have done till now ?
> Also should I send my updates on discord or here sir ?

Just let us know about what progress you made on this issue and is there problem you are facing. Choose any platform.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
