### ISSUE TITLE
Python : Dictionary Comprehension

### ISSUE THREAD

**Issue by rex2828** [girlscript/winter-of-contributing#4286]
## Description

Create a video on Python Dictionary Comprehension
- What is Dictionary Comprehension in Python?
- Using Dictionary Comprehension
- Conditionals in Dictionary Comprehension
- Nested Dictionary Comprehension

## Domain

- [x] Python_Domain

## Type of Contribution

- [x]  Video

### Domain

Python_Domain

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by m0hit-kumar** [comment]
I will love to contribute pls assign it to me

**Comment by rex2828** [comment]
@adityabisoi can you assign this to me and give appropriate tags to this issue.

**Comment by adityabisoi** [comment]
This topic is already covered. Closing this issue
