### ISSUE TITLE
Frontend with Framework: React 3.2 Composition vs Inheritance

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#4296]
## Description
Contributors are required to create documentation and explain about Composition and Inheritance which should cover questions like :- 
- What is Composition in React ?
- When do we use Composition ?
- What is Inheritance in React ?
- When do we use Inheritance ?
- How to implement Composition and Inheritance with code (also give theory explanation of the code) ?
- You can take 2-3 examples with codes of different types to explain this etc.... 
and also add some more points related to this topic from your side.

#### Note : 

- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the Week3 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Narcos101** [comment]
@heet-kumar I'll do it today itself!

**Comment by heet-kumar** [comment]
@Narcos101 how many days more you want create pull request last day for you or else we will re-assign it to some other contributor we can give at most 1 week to each contributor .

**Comment by anandhu720** [comment]
@Narcos101 I can give you one more day for creating pr or need to give a valid reason.Otherwise we will go for @nikki-priyaHIT
