### ISSUE TITLE
Cybersecurity: 1.7 Challenges in Physical Security?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#43]
## Description
**Mention challenges faced by organizations/companies in physical security?**
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by PrachiDoshi2170** [comment]
I would like to be assigned this issue

**Comment by Anant1711** [comment]
> I would like to be assigned this issue

Okay!
Go for it!👍
