### ISSUE TITLE
DSA 2.1.15 String Matching Algorithms

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#4309]
## Description
Give an introduction and explain the working of various String Matching Algorithms.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
I would like to work on this issue. (documentation)
Batch -2 
Dhruti Gandhi

**Comment by dhruti29** [comment]
/assign 
documentation

**Comment by ayushjha952** [comment]
I would like to work on the documentation part can you please assign it to me.
Ayush Jha
Batch - 3.

**Comment by Subhradeep10** [comment]
@dhruti29 Don't do self assign..
@ayushjha952 @dhruti29 Assigned to both of you

**Comment by ayushjha952** [comment]
@pjdurden @Subhradeep10  can you please check the above PR once?
