### ISSUE TITLE
Data Science with Python : Bayesian Regression

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#431]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Bayesian Regression. Tutorial to Bayesian Regression and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Aishani Singh](https://github.com/aishanii) / [Yash Goel](https://github.com/Yash621)
Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by uttarabahad** [comment]
Hello. Could I get assigned to this issue?
Name-Uttara Bahad
Serial No-328
Type: Documentation
Approach-Introduction, Sample example code with explanation, Advantages of Bayesian Regression.

**Comment by prathimacode-hub** [comment]
Issue assigned to @uttarabahad for documentation

**Comment by uttarabahad** [comment]
@aishanii @Yash621 Hello mentors, I am Uttara Bahad. I have started working on the issue and would like to update about my progress- I have completed with the main definition of Bayesian Regression and the main mathematical formula involved. Started with a sample code application as well! I also plan to cover the advantages of Bayesian Regression.
Please suggest if you would like me to add anything else. Thank You!

**Comment by aishanii** [comment]
Sure I'll go over it and get back to you!

**Comment by aishanii** [comment]
Hey Uttara, I checked the contributors list and found that you're in Batch
10. I suggest you to reach out to the Mentor alloted to your batch (Ishika
Kesarwani) for reviews.

**Comment by uttarabahad** [comment]
@aishanii Ok, thank you.

**Comment by aishanii** [comment]
Hey sorry, your issue number has been allotted to me only. I will review it
and get back to you.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
