### ISSUE TITLE
DSA 2.1.13.1  1's and 2's Compliment of Binary String

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#4310]
## Description
Give an introduction and explain the algorithm for finding 1's and 2's complement of Binary String.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ayushjha952** [comment]
I would like to work on the documentation part can you assign it to me.
Ayush Jha
Batch 3.

**Comment by Elisha-s** [comment]
I would like to work on the documentation for this issue. Kindly assign it to me. 
Elisha Singh
DSA-Batch 9

/assign
