### ISSUE TITLE
DSA 2.1.13.2 n-bit Gray Codes

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#4311]
## Description
Give an introduction and explain the working of algorithms for generating n-bit gray codes.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by HassanRahim26** [comment]
Can you please assign me this issue.

**Comment by HassanRahim26** [comment]
Hey @Subhradeep10, I would like to work on this issue. Can you please assign me this issue.
Name:- Hassan Rahim
Batch: DSA Batch-2
Type: Documentation

I commented first in this issue. Also, we're not allowed to use the /assign command on those issue which are created by the supervisor. So, @Subhradeep10 I request you to please assign me this.

**Comment by Subhradeep10** [comment]
@HassanRahim26 Assigned to you

**Comment by itsbittoosharma** [comment]
@Subhradeep10 It's been 4 days there is no update from the person you assigned according to your last comment. You forgot to unassign me, and that person still gave no progress.
So now can I make a PR by tonight if you allow?
