### ISSUE TITLE
DSA 2.1.13.3 Alternate Binary String problem

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#4312]
## Description
Give an introduction and explain the working of algorithms for the following problem-
"Minimum number of characters to be removed to make a binary string alternate".

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ayushjha952** [comment]
I want to work on the **documentation** part can you please assign it to me .
Ayush Jha
Batch -3 .
