### ISSUE TITLE
DSA 2.1.13.5 Lexicographical String pattern problem

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#4315]
## Description
Give an introduction and explain the working of an algorithm for finding Lexicographically largest subsequence such that every character occurs at least k times.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by utkarshpathak2504** [comment]
I would like to work on this issue(documentation part). Please assign it to me.
Utkarsh Pathak
DSA Batch-4

**Comment by itsbittoosharma** [comment]
/assign Documentation 
Utkarsh Upadhyay
DSA Batch-3
