### ISSUE TITLE
DSA 2.2.6.4 Interpolation Search(Searching and Sorting)

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#4319]
## Description
Give an introduction and explain the working of an algorithm for Interpolation Search.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
I would like to work on this issue. (documentation)
Batch -2 
Dhruti Gandhi

**Comment by sonali-t** [comment]
@pjdurden I would like to work on this issue(documentation part). Please assign it to me.
Sonali Tomar
DSA Batch-4

**Comment by aisharay** [comment]
/assign
Documentation
Aisha ray
DSA batch 7
