### ISSUE TITLE
[Create New Issue]: Recursion

### ISSUE THREAD

**Issue by purohitmansi** [girlscript/winter-of-contributing#4327]
### Description

Description

### Domain

DSA

### Type of Contribution

Documentation, Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by purohitmansi** [comment]
I have opened the issue to work on it. Please do assign this to me.
/assign

**Comment by purohitmansi** [comment]
> /assign

Please do checkout for other issue. I have made to contribute in this.

**Comment by jaigora24** [comment]
I want to work on this issue.
