### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(3.1) -> Built-in Directives 

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#4328]
### Description

- What are directives?
- What are different types of directives?
- What are built-in structural directives?
- What are built-in attribute directives?
- How to host a directive without a DOM element?
- Explain with code snippets/syntax.
- Reference :- https://angular.io/guide/built-in-directives
(Week 3 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week3" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RIYANSHGARG** [comment]
I would like to work on this. Kindly, assign it to me

**Comment by RIYANSHGARG** [comment]
I have created a pull req kindly review it .
