### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(3.3) -> Attribute Directives 

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#4330]
### Description

- What is attribute directive?
- How to build attribute directive?
- How to handle user events?
- How to pass value into an attribute directive?
- How to bind it with second property?
- How to deactivate attribute directive processing?
- Reference :- https://angular.io/guide/attribute-directives
(Week 3 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week3" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by CSAURABH** [comment]
@mukeshmjn can i work on this issue.

**Comment by Hritik157** [comment]
/ assign

**Comment by mukeshmjn** [comment]
Assigned to u @CSAURABH
