### ISSUE TITLE
Data Science with Python : Getting Started With Seaborn

### ISSUE THREAD

**Issue by SARANYA233** [girlscript/winter-of-contributing#4331]
### Description

Need to create a Documentation

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment]
Don't create issues without informing. @SARANYA233
