### ISSUE TITLE
Code of Conduct & Contribution Guidelines should be in front.

### ISSUE THREAD

**Issue by Sin-Sumit** [girlscript/winter-of-contributing#4348]
### Description

Code of Conduct & Contribution Guidelines files are placed inside the .github directory, both files should be in front with others like License, README, not inside any directory.

Because beginners most of the time not able to find these important files.

Please put them in front.

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nishant-giri** [comment]
@Sin-Sumit, could you kindly review the changes in #4488?

**Comment by Sin-Sumit** [comment]
@nishant-giri I'm not a maintainer.
