### ISSUE TITLE
Problems which uses Dynamic Programming Algorithm || 0/1 Knapsack

### ISSUE THREAD

**Issue by DwipshikhaLodh** [girlscript/winter-of-contributing#4354]
### Description

Description: Here I'll be describing how dp algorithm can be used to solve few standard problems.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by DwipshikhaLodh** [comment]
@vasu-1 is it compulsory that after the pr for the raised issue gets merged the issue needs to get closed? I'm a little confused because my other issued got closed but not this one

**Comment by vasu-1** [comment]
After pr Gets merged  you can close it and also you can close respective issue !

**Comment by vasu-1** [comment]
If a supervisor forgets to close then you can close it by yourself
