### ISSUE TITLE
DSA 2.1 Strings: Substrings - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4358]
## Description
What are substrings? Give examples. How do you implement them? Mention atleast three approaches.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by vanshikapandey** [comment]
Hey I wanted to take up this issue and work upon it. I will complete the issue in the format stated by you Kindly assign this issue to me.
Name : Vanshika Pandey
Batch no: 10

**Comment by nimisha-yadav** [comment]
> 
> 
> Hey I wanted to take up this issue and work upon it. I will complete the issue in the format stated by you Kindly assign this issue to me. Name : Vanshika Pandey Batch no: 10

Assigning this issue to you @vanshikapandey, all the best!

**Comment by vanshikapandey** [comment]
Thank you so much:)
