### ISSUE TITLE
DSA 1.1.4.1 Arrays: Order Statistics

### ISSUE THREAD

**Issue by Sarthak-Agg** [girlscript/winter-of-contributing#436]
> ## Description
> Explain how to find the Kth smallest/Largest element in Sorted/Unsorted arrays
> 
> ## Task
Contribution can be in the forms of

> * [ ]  Editorial/Documentaion
> * [ ]  Audio
> * [ ]  Video
> 
> ## Note
> * While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
> * Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
> * In case you see that the issue has already been assigned, try to request for a different task within the same issue.
> * Changes should be made inside the `DSA/directory` & `DSA` branch.
> * Name of the file should be same as the issue.
> * This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by rkadam61001** [comment]
Name:Rajnandini Kadam
Batch-1
Pls assign me this issue

**Comment by RBiswa787** [comment]
I would like to work on this issue.
Name: Biswadeep
Batch: 5
Serial No.: 958
Type: Video(Presentation)
I would like to explain the topic visually through a presentation along with code.

**Comment by msbuddhu** [comment]
Hey @ViAsmit,
Shabi Kaushal this side. I am good at Data Structures and Algorithms. I can implement them in practice lucidly as well as document them. May you assign me this task?

Shabi Kaushal (DSA Batch 05)

**Comment by dhruti29** [comment]
Name: Dhruti Gandhi
Batch-2
Pls, assign me this issue (Editorial/Documentation).

**Comment by Sarthak-Agg** [comment]
task assigned to @RBiswa787 for video representation and @rkadam61001 @msbuddhu @dhruti29 for (Editorial/Documentation)

**Comment by Sarthak-Agg** [comment]
> > ## Description
> > Explain how to find the Kth smallest/Largest element in Sorted/Unsorted arrays
> > ## Task
> 
> Contribution can be in the forms of
> 
> > * [ ]   Editorial/Documentaion
> > * [ ]   Audio
> > * [ ]   Video
> > 
> > ## Note
> > 
> > * While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
> > * Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
> > * In case you see that the issue has already been assigned, try to request for a different task within the same issue.
> > * Changes should be made inside the `DSA/directory` & `DSA` branch.
> > * Name of the file should be same as the issue.
> > * This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Aniketsinghcoder** [comment]
Aniket Singh & DSA-batch-3
Sir, I want to contribute to this issue in the Editorial/Documentation part. 
In case if the array is sorted it is easy to find the kth smallest/largest.
but in the case of the unsorted array, we can use heap data structure or quick select algorithm.

**Comment by mansisingh2803** [comment]
Hii Sarthak!!!
Mansi Singh & DSA batch 4
Please assign this issue to me.

**Comment by Sarthak-Agg** [comment]
issue assigned, let the the contributions begin

**Comment by HardikJain-Harry** [comment]
Hii Sarthak!!!
Hardik Jain & DSA batch 3
Please assign this issue to me.

**Comment by msbuddhu** [comment]
@vikhyatsingh123 Please have a look at the PR

**Comment by msbuddhu** [comment]
@Sarthak-Agg I have created a PR. Please have a look.

**Comment by A-nn-e** [comment]
Heyy, I am Anmol, from DSA: Batch 5. I would like to work on this issue.
