### ISSUE TITLE
DSA 2.1 Strings: Binary Strings - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4361]
## Description
What are Binary Strings? Give examples.
Given a binary string, count number of substrings that start and end with 1.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by vanshikapandey** [comment]
Please assign this issue to me
Name Vanshika Pandey
Batch no: 10

**Comment by Koustav-1250** [comment]
Can you assign me documentation part of It please
