### ISSUE TITLE
DSA 2.1 Strings Anagram: Introduction - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4367]
## Description
What is an anagram of a string? Give examples. Write a function to check whether two given strings are anagram of each other or not.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by jarul-jangid** [comment]
Jarul Jangid Batch 1
