### ISSUE TITLE
DSA 2.1 Strings Anagram: Introduction - Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4368]
## Description
What is an anagram of a string? Give examples. Write a function to check whether two given strings are anagram of each other or not.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by rajmadhu0406** [comment]
Can you assign this issue to me?
Raj Madhu
batch - 6

**Comment by motasimmakki** [comment]
@nimisha-yadav 
Kindly assign this to me.

Motasim (DSA Batch-01)

**Comment by sahildhiman-nsutian** [comment]
Hey @nimisha-yadav  I would like to work to this issue.  My video would demonstrate anagrams with example. Further ,I will explain my code to check whether two strings are anagram of not . Please assign me.
Thank you !

**Comment by sahildhiman-nsutian** [comment]
I forget to tell my name is Sahil .

**Comment by nimisha-yadav** [comment]
> 
> 
> I forget to tell my name is Sahil . It would be also awesome if you can label it for Hacktoberfest 21 .

Alright, please mention your DSA Batch Number as well @sahildhiman-nsutian

**Comment by sahildhiman-nsutian** [comment]
@nimisha-yadav Hey actually I am new to this organization . How to see Batch number ?

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav Hey actually I am new to this organization . How to see Batch number ?

Hey @sahildhiman-nsutian, this issue is only for GWOC Contributors of DSA domain, are you a part of this program?

**Comment by shahhilag** [comment]
@nimisha-yadav Mam if this task has not been alloted to anyone I would like to work on this.
Name-Hilag Shah
Batch-DSA batch 1

**Comment by nimisha-yadav** [comment]
> It actually contains ":" due to which windows is unable to clone the repo

Fixed it

**Comment by shahhilag** [comment]
Really sorry
