### ISSUE TITLE
Data Science with Python : Regularization in Regression

### ISSUE THREAD

**Issue by DhruvBajaj01** [girlscript/winter-of-contributing#4376]
### Description

Welcome to 'DSWP' Team, good to see you here

With this issue, readers will get introduced to core information to Regularization in Regression along with sample code completely in an effective way.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning 

Mentors Assigned: Dhruv Bajaj / Aishani Singh 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include the issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of the 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Video, Documentation

### Code of Conduct

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by PurviBhoyar21** [comment]
Hello supervisors and mentors 
I want to work on it

Thank you

**Comment by prathimacode-hub** [comment]
> Hello supervisors and mentors I want to work on it
> 
> Thank you

Details please. @PurviBhoyar21

**Comment by PurviBhoyar21** [comment]
I am from ML batch 1
Python batch 5
and I want to contribute to DSA domain for this issue

**Comment by prathimacode-hub** [comment]
Are you from DSWP? If so what's your serial number, type of contribution and your approach? This issue is only for DSWP domain contributors.  @PurviBhoyar21

**Comment by PurviBhoyar21** [comment]
#5262 is my serial number
No I am not from DSWP 
Documentation will be the type of contribution
but want to contribute to this issue

**Comment by ayushi424** [comment]
Name: Ayushi Shrivastava
S No: 811
Batch No. 19
Contribution type: 
-  Documentation 

Approach to be followed:  
 -  Explanation  about Regularization in regression along with sample code implementation for better understanding.

@prathimacode-hub

**Comment by prathimacode-hub** [comment]
> #5262 is my serial number No I am not from DSWP Documentation will be the type of contribution but want to contribute to this issue

Sorry but these issues are only for contributors from DSWP domain. @PurviBhoyar21

**Comment by prathimacode-hub** [comment]
Issue assigned to @ayushi424 for documentation

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do **video** on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
