### ISSUE TITLE
Factorial program in c++ using recursion

### ISSUE THREAD

**Issue by shubh045** [girlscript/winter-of-contributing#4391]
### Description

program to find factorial of a number using recursion

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by PurviBhoyar21** [comment]
Hello Supervisors and mentors
Please assign me this issue
I would love to contribute to this
and please include a label of hactoberfest - It would be great
THANK YOU

**Comment by shubh045** [comment]
Hello supervisers and mentors 
please include the label of hactoberfest to this issue
