### ISSUE TITLE
Cybersecurity: 1.8 Security, Functionality, and usability triangle

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#44]
## Description
Discuss the strength of this triangle and discuss what makes it so stable?
 
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by HumblePlebeian** [comment]
I am interested to explore and contribute to this topic.
Please assign this issue to me. 
Thanks!

**Comment by Anant1711** [comment]
> I am interested to explore and contribute to this topic.
> Please assign this issue to me.
> Thanks!

Okay!
I'm assigning it to you 👍
