### ISSUE TITLE
JS: Loops in Javascript

### ISSUE THREAD

**Issue by gurpreet-legend** [girlscript/winter-of-contributing#440]
## Introduction to loops in Javascript:
This will describe the usage of different loops in Javascript

## Directory:
```
Topics/4.Syntax/5.Loops
```
## Description:

- What are loops?
- Different types of loops in Javascript 
  - for
  - for/in
  - for/of
  - while
  - do/while
 
## Formats:
- [x] Document
- [ ] Video
- [ ] Audio

**Comment by Asmit2952** [comment]
I want to work on this!! Please assign it to me

**Comment by SudhansuuRanjan** [comment]
I want to contribute with documentation. Please assign it to me !!

**Comment by Soumili1818** [comment]
May I have the honour of contributing to this issue, please?

**Comment by FirdausJawed** [comment]
I want to contribute with documentation. Please assign it to me !!

**Comment by preeti-14-7** [comment]
I would like to contribute to the documentation part of this task. 
js batch 1 
preeti kumari yadav
