### ISSUE TITLE
Cybersecurity 5.1 Server and Client Socket

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#4407]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
> /assign

One task at a time !

**Comment by Kalpana-Kathait11** [comment]
OK

**Comment by iamKushGupta** [comment]
Can the documentation for this issue be assigned to me ?

**Comment by lala-lala-lori** [comment]
I would like to work on this issue in documentation format.

**Comment by Anant1711** [comment]
> Can the documentation for this issue be assigned to me ?

Assigned for Documentation!

**Comment by Anant1711** [comment]
> I would like to work on this issue in documentation format.

Documentation is taken!
Do you want to do it in Video format?

**Comment by lala-lala-lori** [comment]
> 
> 
> > I would like to work on this issue in documentation format.
> 
> Documentation is taken! Do you want to do it in Video format?

No sir, video format seems difficult for me.

**Comment by Anant1711** [comment]
@iamKushGupta When you are going to submit your work!

**Comment by iamKushGupta** [comment]
I thought I had submitted my work... Guess I was wrong.
Nevertheless, will submit it within today.
