### ISSUE TITLE
1.1 Array - Misc: Array Rotation: Algorithms

### ISSUE THREAD

**Issue by GenMech** [girlscript/winter-of-contributing#441]
<h2>Reversal algorithm for array rotation</h2>

- <h3>Subarrays are created and reversed to perform the rotation of the array.</h3>

<h2>Block swap algorithm for array rotation</h2>

- <h3>It is an efficient algorithm that is used for array rotation. It can do your work in O(n) time complexity.</h3>

**Comment by AJgthb2002** [comment]
Please assign this to me. I'd like to create documentation on this topic.
Ananya Joshi
DSA batch2

**Comment by Ayushi2811** [comment]
I hold a good experience in DSA since past year and can present a welll structured documentation on the same.
Could u please assign it to me. @GenMech 
AYUSHI CHAUHAN
DSA Batch-01

**Comment by FirdausJawed** [comment]
I want to contribute with documentation. Please assign it to me !!

**Comment by GenMech** [comment]
@nimisha-yadav I have created this issue and i would like to work on it pls add labels and assign it to me! Thanks
Gitesh Pareek
Batch-1

**Comment by preeti-14-7** [comment]
I want to contribute with documentation. Please assign it to me !!
DSA batch 3 
preeti kumari yadav

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav I have created this issue and i would like to work on it pls add labels and assign it to me! Thanks
> Gitesh Pareek
> Batch-1

Go ahead with your issue @GenMech, all the best!

**Comment by Aryan-Mohanty** [comment]
Can I work on this issue ?

**Comment by khushipunia21** [comment]
@nimisha-yadav I am interested to work on this issue.
Name: Khushi Punia
Type: Documentation
