### ISSUE TITLE
New issue: C_Cpp templates and libraries

### ISSUE THREAD

**Issue by udayan-banik** [girlscript/winter-of-contributing#4443]
### Description

I would like to contribute to the documentation for C++ Templates and libraries.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Vaibhavwani11** [comment]
I can add some more useful information about c++ templates. Pls assign this issue to me.
