### ISSUE TITLE
Data Science with Python : Data Visualizations using Matplotlib

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#445]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in getting all the guidance that one needs to learn about Data Visualizations with Matplotlib. Tutorial to Data Visualizations with Matplotlib and how it's applied visually.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualizations

Mentors Assigned : [Shivang Dubey](https://github.com/shivangdubey) / [Nithin](https://github.com/Nithin-Reddy-02)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by Malvikakaushal2001** [comment]
I want to contribute in this issue.
I am from ds python batch 20

**Comment by ShubhamPatel01** [comment]
I would like to work on this issue, which is issue no. 445
Name: Shubham Patel
Serial No. 104.
Type: Documentation
Approach:

- Introduction to Matplotlib library
- Several types of Visualization techniques using Matplotlib
- Alternatives of Matplotlib for visualization in Python

**Comment by dakshitathakkar** [comment]
Hey @prathimacode-hub, I would like to work on this
Name - Dakshita Thakkar
Sno - 392
Type : Documentation, Audio

**Comment by prathimacode-hub** [comment]
@KhushiKV this issue is allotted to you for documentation and video. 

@ShubhamPatel01 @Malvikakaushal2001 @dakshitathakkar, any of you can choose audio if you are interested. This issue is assigned to Khushi as she was assigned to wrong issue earlier.

There are many more issues coming. Stay tuned to grab.

**Comment by KhushiKV** [comment]
@prathimacode-hub Thank you very much...I will prepare the Documentation.

**Comment by BhaswatiRoy** [comment]
I am bhaswati roy from dswp batch 19
I would like to contribute for this.

**Comment by ShubhamPatel01** [comment]
> @KhushiKV this issue is allotted to you for documentation.
> 
> @ShubhamPatel01 @Malvikakaushal2001 @dakshitathakkar, any of you can choose video / audio if you are interested. This issue is assigned to Khushi as she was assigned to wrong issue earlier.
> 
> There are many more issues coming. Stay tuned to grab.

I would like to work on this issue, which is issue no. 445
Name: Shubham Patel
Serial No. 104.
Type: Video
Approach:

- Introduction to Matplotlib library

-Several types of Visualization techniques using Matplotlib
-Alternatives of Matplotlib for visualization in Python

**Comment by dakshitathakkar** [comment]
> @KhushiKV this issue is allotted to you for documentation.
> 
> @ShubhamPatel01 @Malvikakaushal2001 @dakshitathakkar, any of you can choose video / audio if you are interested. This issue is assigned to Khushi as she was assigned to wrong issue earlier.
> 
> There are many more issues coming. Stay tuned to grab.

I would like to work on this issue, which is issue no. #445
Name - Dakshita Thakkar
Sno - 392
Type : Audio

**Comment by ProMinato500** [comment]
I would like to work on this issue which is issue no. #445
Name - Pradipta Nandi
Sno - 250

**Comment by KhushiKV** [comment]
@Nithin-Reddy-02 @shivangdubey mentors, Hi I am Khushi, since I have been assigned this issue for Documentation, I thought about updating you with the status, as we were asked to. Should I messages you here only for further communication? So far, I have decided what all resources I would be using to make my contribution and collected most of the data, I will start the Coding part shortly afterwards. 
Thank you

**Comment by Nithin-Reddy-02** [comment]
Hello @KhushiKV, you can communicate here or even in the discord as per your comfort. Its a good thing you have started working and completed collecting the data, take your own time and start the coding part and make sure the resources you use are well recognised/cited. You can keep updating about your work whenever possible and finally ping me if you have any doubt or if you need anything, I'd be happy to help you.

**Comment by shivangdubey** [comment]
> @Nithin-Reddy-02 @shivangdubey mentors, Hi I am Khushi, since I have been assigned this issue for Documentation, I thought about updating you with the status, as we were asked to. Should I messages you here only for further communication? So far, I have decided what all resources I would be using to make my contribution and collected most of the data, I will start the Coding part shortly afterwards.
> Thank you

For this issue, you may use GitHub only. And for any other doubt ping at Discord. All the best!

**Comment by prathimacode-hub** [comment]
Issue is assigned to @ShubhamPatel01 for Video.

@dakshitathakkar, have you been alloted to any other issue? If not also add up your approach in your comment.

**Comment by dakshitathakkar** [comment]
> Issue is assigned to @ShubhamPatel01 for Video.
> 
> @dakshitathakkar, have you been alloted to any other issue? If not also add up your approach in your comment.

I am assigned an issue but it is under another domain and not under Data Science with Python. It's all right if I can't contribute to different domains at the same time, and if  I can, I've added an approach in my previous comment.

**Comment by prathimacode-hub** [comment]
That's ok if it's for other domain, as long as no multiple issues are assigned in same domain. 

Issue allotted to @dakshitathakkar for audio contribution

**Comment by ShubhamPatel01** [comment]
Hello, this message is regarding timely update of issue assigned. I have completed making graphs to show in my video presentation and will be recording the video by end of the week.

**Comment by dakshitathakkar** [comment]
Hi, This is regarding an update of my work on this issue. I've recorded the audio and made a presentation for the same. Will shortly upload the files on google drive and complete the work.

**Comment by KhushiKV** [comment]
Hi, I would like to provide an update about my work for this issue, I have written and prepared the Colab notebook halfway so far. I would be completing it soon. Thanks.

**Comment by KhushiKV** [comment]
@Nithin-Reddy-02 @shivangdubey mentors, hello...I have completed my documentation for this issue and have opened a pull request for the same. Please let me know if you are able to see and merge it with the repository. 
Is there anything else that needs to be done from my end for this? 
Thank you very much.
