### ISSUE TITLE
Opensource: 4.22 Explain everything about `bitcoin summer of code`

### ISSUE THREAD

**Issue by priyanshiparolia** [girlscript/winter-of-contributing#4456]
### Description

 4.22 Explain everything about `bitcoin summer of code`

### Domain

Open Source

### Note 👇

- Doc should be submitted inside `4.Open_Source_Programs/` with name `4.22_Bitcoin_Summer_Of_Code.md`

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@priyanshiparolia  Do we need to add into ` Open source` programs? Since this program, I guess not active right now (last update : 2020) https://railsgirlssummerofcode.org/

**Comment by priyanshiparolia** [comment]
I think you are right this program didnt took place in 2021 so maybe its not active

**Comment by priyanshiparolia** [comment]
should I close this issue or replace its description with another one

**Comment by Aryamanz29** [comment]
> should I close this issue or replace its description with another one

It would be better if you edit this any other program or if don't found any then you may close this

**Comment by Aryamanz29** [comment]
@priyanshiparolia Go with `Bitcoin summer of code`, This year bitcoin org started this program

**Comment by Aryamanz29** [comment]
@priyanshiparolia  Issue description updated

**Comment by paul-111** [comment]
@Aryamanz29  how to add this hacktoberfest tag in an issue while creating?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 how to add this hacktoberfest tag in an issue while creating?

You can't add by yourself, You can tag `Supervisors` or `Mentor` for that
