### ISSUE TITLE
DSA 1.1.2.2 Array Rearrangement STL 

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#446]
## Description
Minimum swaps required to bring elements less than equal to k together, STL implementations of rearrangement(sort comparator etc).

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Ayushi2811** [comment]
I hold a good experience in DSA since past year and can present a well structured documentation on the same.
Could u please assign it to me. @pjdurden
AYUSHI CHAUHAN
Barch-01

**Comment by nik09877** [comment]
I would like to work on this issue ( Documentation part ). I have done similar problem on codeforces.
Nikhil Kumar Mishra.
DSA Batch-3

**Comment by Subhradeep10** [comment]
@nik09877 Assigned to you

**Comment by geeky01adarsh** [comment]
Name: Adarsh  Navneet Sinha
Batch: DSA batch 2
Type: Documentation
I want to work on the documentation of this issue. Please assign the documentation part to me.

**Comment by jaya6400** [comment]
Name - Jaya Dubey
Batch - DSA 3 
Type - Documentation 
Want to work on this problem and create a Documentaion for clear understanding.
Please assign me this issue:)

**Comment by Subhradeep10** [comment]
@jaya6400 @geeky01adarsh Go ahead, Assigned to you

**Comment by dhruti29** [comment]
Name: Dhruti Gandhi
Batch: DSA batch 2
Type: Documentation
I want to work on the documentation of this issue. Please assign me.

**Comment by uditkatyal** [comment]
@pjdurden  pls assign this issue to me 
type : documentation
name : udit 
DSA batch 3

**Comment by Ayushi2811** [comment]
> @jaya6400 @geeky01adarsh Go ahead, Assigned to you

I was the one to ask first but its not assigned to me can I know why??
