### ISSUE TITLE
DSA 1.1.2.3 Array Rearrangement Circular arrays

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#447]
## Description
Circular array problem(Maximize sum, maximize difference), left and right shift on the circular array.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Ayushi2811** [comment]
I hold a good experience in DSA since past year and can present a welll structured documentation on the same.
Could u please assign it to me. @pjdurden
AYUSHI CHAUHAN
Barch-01

**Comment by vkaash-sharma** [comment]
I have good knowledge of dsa i can contribute to the documentation please assign this to me!

**Comment by preeti-14-7** [comment]
I would like to work on this issue via the Documentation part . 
dsa batch 3
preeti yadav

**Comment by Subhradeep10** [comment]
@preeti-14-7 Go for it, Assigned to you
