### ISSUE TITLE
DSA 1.1.2.4 Array Rotations (Using reversal)

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#448]
## Description
Rotation of array using reversal, blockswap methods, cyclic rotation.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Ayushi2811** [comment]
I hold a good experience in DSA since past year and can present a welll structured documentation on the same.
Could u please assign it to me. @pjdurden 
AYUSHI CHAUHAN
Barch-01

**Comment by AJgthb2002** [comment]
Please assign this to me. I'd like to contribute in the form of documentation.
Ananya Joshi
DSA batch2

**Comment by ayushjha952** [comment]
Can you please assign this issue to me. I'd like to contribute in the form of documentation.
Ayush Jha
DSA batch3

**Comment by ayushjha952** [comment]
Please assign this issue to me. I'd like to contribute in the form of documentation.
Ayush Jha
DSA batch3

**Comment by msbuddhu** [comment]
Hey @pjdurden,
Shabi Kaushal this side. I am good with Data Structures and Algorithms. I can implement them in C/C++/Python lucidly as well as document it. 

Shabi Kaushal (DSA Batch 05)
issue #448

**Comment by Subhradeep10** [comment]
@ayushjha952 Assigned to you. Go ahead

**Comment by ayushjha952** [comment]
@Subhradeep10 this issue was assigned to me, right?
