### ISSUE TITLE
Opensource : 7.0 `Licenses` In Open Source 

### ISSUE THREAD

**Issue by VandanaKumari18** [girlscript/winter-of-contributing#4492]
### Description

Detailed information `about licenses` and `different types of licenses in open source` and `their importance`.

### NOTE 👇
Please put your doc `7.License/` with the name `7._About_License.md`

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@VandanaKumari18  Issue description updated so please look that before raising any PR
Thanks
