### ISSUE TITLE
Questions to master binary search

### ISSUE THREAD

**Issue by geetika005** [girlscript/winter-of-contributing#4493]
### Description

This documentation will include list of some questions of leetcode which will help you to understand the concept of binary search

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as #4501 got merged
