### ISSUE TITLE
DSA 1.1.2.5 Array Rotation non query problems

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#450]
## Description
Maximize i*arr[i] in all rotations, rotation count in rotated sorted array.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by nik09877** [comment]
I would like to work on this issue .
Nikhil Kumar Mishra.
DSA Batch 3

**Comment by cookieg13** [comment]
Hi ! I would love to work on this issue. Can you please assign it to me? Debarati Ghatak DSA Batch3

**Comment by geeky01adarsh** [comment]
Name: Adarsh  Navneet Sinha
Batch: DSA batch 2
Type: Documentation
I want to work on the documentation of this issue. Please assign the documentation part to me.

**Comment by rajveer43** [comment]
Name: Rajveer Rathod
Batch: DSA batch 3
Type: Documentation
I want to work on the documentation of this issue. Assign the documentation part to me.

**Comment by Subhradeep10** [comment]
@rajveer43 Go for it, Assigned to you
