### ISSUE TITLE
SQL Queries and Sub Queries

### ISSUE THREAD

**Issue by ayushmaan02** [girlscript/winter-of-contributing#4507]
### Description

Description
1. About Queries, syntax, example
2. About Sub Queries, syntax, example

### Domain

Database

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Rohit484** [comment]
First thing query means what have your doubts or we can say  A request for data or information from a database table combination of tables here many features are involved like CREATE, UPDATE,INSERT,DELETE ALTER ete

**Comment by Rohit484** [comment]
documentation/
