### ISSUE TITLE
Flutter : Introduction to Interaction models and widgets

### ISSUE THREAD

**Issue by iamayushkr** [girlscript/winter-of-contributing#4517]
### Description

Make a README file on the interaction model and widgets.
Your documentation should covers topics like:
1. Gesture Detectors
2. Draggable
3.  Scrollable
4. Dismissible
5. etc...

You can take reference from the link: https://flutter.dev/docs/development/ui/widgets/interaction

### Domain

Android Dev (Flutter)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ViAsmit** [comment]
@iamayushkr have you completed the issue?
