### ISSUE TITLE
DSA 1.1.2.6 Array Rotation some O(N) problems

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#452]
## Description
Left rotation, rotations required to sort array, elements at index I after k rotations.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by AJgthb2002** [comment]
Please assign this to me. I'd like to contribute in the form of documentation.
Ananya Joshi
DSA batch 2

**Comment by yatharthrajput** [comment]
#include <bits/stdc++.h>
using namespace std;
 

void leftRotatebyOne(int arr[], int n)
{
    int temp = arr[0], i;
    for (i = 0; i < n - 1; i++)
        arr[i] = arr[i + 1];
 
    arr[n-1] = temp;
}
 
/*Function to left rotate */
void leftRotate(int arr[], int d, int n)
{
    for (int i = 0; i < d; i++)
        leftRotatebyOne(arr, n);
}
 

void printArray(int arr[], int n)
{
    for (int i = 0; i < n; i++)
        cout << arr[i] << " ";
}
 
/* Driver */
int main()
{
    int arr[] = { 1, 2, 3, 4, 5, 6, 7 };
    int n = sizeof(arr) / sizeof(arr[0]);
 
    // Function calling
    leftRotate(arr, 2, n);
    printArray(arr, n);
 
    return 0;
}

**Comment by yatharthrajput** [comment]
Please assign this to me. I'd like to contribute in the form of documentation.
Yatharth Rajput
DSA batch 4

**Comment by nik09877** [comment]
I'd like to contribute in the form of documentation.
Nikhil Kumar Mishra
DSA batch 3

**Comment by HassanRahim26** [comment]
Hey @pjdurden , I would like to work on this issue. Can you please assign me this issue?
Name :- Hassan Rahim
Batch:-  2
Type:- Documentation
I've previously solved problems related to Array Rotation. That's why I would like to work on this issue, and I'm sure I would explain it in a better and easy way.

**Comment by preeti-14-7** [comment]
I would like to work on this issue. 
Name :-Preeti Kumari Yadav 
DSA Batch:- 3
Type:- Documentation

**Comment by cookieg13** [comment]
Hi ! I would love to work on this issue. Can you please assign it to me? Debarati Ghatak DSA Batch3

**Comment by Subhradeep10** [comment]
@cookieg13 Go for it, assigned to you

**Comment by AJgthb2002** [comment]
@Subhradeep10 Arent the issues assigned on a first come basis?

**Comment by Subhradeep10** [comment]
@AJgthb2002 We have to do the batch preference also, Cause the superviser is for  DSA-Batch 3 , So we have to give the preference to DSA -Batch 3 Contruibuter first

**Comment by AJgthb2002** [comment]
oh okay!

**Comment by arjyo851** [comment]
I would like to work on this issue.Can you please assign this to me?
Name: Arjyo Chakraborty 
Batch :- DSA - Batch 3

**Comment by Subhradeep10** [comment]
@mansisingh2803 @arjyo851 @AJgthb2002 Go ahead, Assigned to you.

**Comment by AJgthb2002** [comment]
Thank you @Subhradeep10 
But in the assignees section, it is still showing 'no one assigned'. I am a beginner, I did not understand why the assignees are not shown?
