### ISSUE TITLE
Android-Kotlin : 01.1 Requirement of Version Control System

### ISSUE THREAD

**Issue by anantcodes** [girlscript/winter-of-contributing#453]
## Description :
*  Give a brief description stating the need of Version Control System.
* Also describe about Git and GitHub.
*  Required documentation, audio, or video.

## References :
https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control
https://guides.github.com/activities/hello-world/

* Changes should be made in Android_Development/Kotlin/ directory under Android_Development_With_Kotlin branch.
* You have to push your PR to the Android_Development_With_Kotlin branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.

> Supervisor @rahulsain

**Comment by Asmit2952** [comment]
Can I take this?

**Comment by anantcodes** [comment]
> Can I take this?

Yeah sure.
