### ISSUE TITLE
Opensource : M.14 Explain what is Web Hosting ? and How it is done ?

### ISSUE THREAD

**Issue by paul-111** [girlscript/winter-of-contributing#4536]
## Description 📜

Explain **what is Web Hosting ?** and **How it is done ?**

### NOTE 👇
Please put your doc `Miscellaneous/` with the name `M.14_Web_Hosting.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
Can I work on this issue??

**Comment by paul-111** [comment]
yea sure go on :)

**Comment by PranshuSrivastava** [comment]
Can I work on this issue as well?

**Comment by Aryamanz29** [comment]
@PranshuSrivastava  Happy Learning 🎉🎉  Issue description updated so look that as well before working on this issue

**Comment by PranshuSrivastava** [comment]
> @PranshuSrivastava Happy Learning tadatada Issue description updated so look that as well before working on this issue

@Aryamanz29 Sure
