### ISSUE TITLE
DSA: Queue implementation using Array in C Programming

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#4541]
### Description

Explain the Basic method of Queue and queue Implementation in C Programming using an array.
Methods to explain:-

   1)Enqueue
   2)Dequeue
   3)Show
   4)IsEmpty

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by motasimmakki** [comment]
Kindly assign this to me.

Motasim (DSA Batch-01)

**Comment by motasimmakki** [comment]
@nimisha-yadav
As this issue is not assigned to anyone by the maintainer, kindly assign this to me ✨

**Comment by nimisha-yadav** [comment]
> 
> 
> @nimisha-yadav As this issue is not assigned to anyone by the maintainer, kindly assign this to me ✨

Hey, queue is not part of our week 3, 2 or 1 agenda so such Issues/PRs are discarded. I'll be creating 9-10 issues by evening, stay active, you can work on them.
