### ISSUE TITLE
Beans and Bean annotations

### ISSUE THREAD

**Issue by Satyam175** [girlscript/winter-of-contributing#4555]
### Description

<h2>Beans</h2>
<ul>
<li>Defining beans</li>
<li>Annotations</li>
<li>Configuration</li>
</ul>

### Domain

Backend Dev (Java)

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by YASHMAROO** [comment]
@Satyam175 please close this issue also.
