### ISSUE TITLE
PHP Error Handling

### ISSUE THREAD

**Issue by vasu-1** [girlscript/winter-of-contributing#4637]
### Description

In this issue i am working with error handling in php.(Documentation)

### Domain

Backend Dev (PHP)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by mmeghana2405** [comment]
hello iam meghana batch -6 can please assign me video
