### ISSUE TITLE
Data Science with Python : Dimensionality Reduction

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#464]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in providing all the guidance that one needs to learn about Dimensionality Reduction. Tutorial to Dimensionality Reduction and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : Gauri Bharadwaj / [Peehu Saxena](https://github.com/PeehuSaxena)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by prathimacode-hub** [comment]
Kindly provide all the details. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

@BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> Kindly provide all the details.
> 
> To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.
> 
> @BhaswatiRoy

Sure wait

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Data Science with Python 
Batch-19  
Serial No-787 
Issue Number-464
Contribution Ideas- Explanation of why we need dimensionality reduction concepts like pca on big and complex datasets and ways to apply, other approaches rather than pca

**Comment by prathimacode-hub** [comment]
What's the choice? Documentation, Audio, Video @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> What's the choice? Documentation, Audio, Video @BhaswatiRoy

I would like to go for documentation

**Comment by prathimacode-hub** [comment]
Ok, issue assigned to @BhaswatiRoy for documentation.

**Comment by BhaswatiRoy** [comment]
> Ok, issue assigned to @BhaswatiRoy for documentation.

Thank You!

**Comment by BhaswatiRoy** [comment]
I have completed the documentation part so how should I submit now?

**Comment by prathimacode-hub** [comment]
Ok, you had done with documentation? I shall add a project structure of how it should be in discord general channel of our domain. once you check on it and create a PR. @BhaswatiRoy

**Comment by BhaswatiRoy** [comment]
> Ok, you had done with documentation? I shall add a project structure of how it should be in discord general channel of our domain. once you check on it and create a PR. @BhaswatiRoy

Yes, I am done you may!........we only need to do on google colab right and nowhere else?

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do video on this issue.
my approach: A detail explanation.

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for audio and @deepthi1107 for video contribution
