### ISSUE TITLE
Open Source : 6.18 Explain everything related to `fastAPI`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#4648]
<hr>

## Description 📜

Open Source : 6.18 explain everything related to `fastAPI`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.18_fastAPI.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HassanRahim26** [comment]
Hey @Aryamanz29, I would like to work on this issue. Can you please assign me this issue?
Name:- Hassan Rahim
Batch:- Open-Source Batch-1
Type:- Documentation

**Comment by Aryamanz29** [comment]
@HassanRahim26 Sure, Happy Learning 🎉🎉
