### ISSUE TITLE
Python : Logical Operators

### ISSUE THREAD

**Issue by ParagD25** [girlscript/winter-of-contributing#4666]
### Description

Documentation of Logical Operations in Python.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ParagD25** [comment]
@adityabisoi can you assign me this issue?

**Comment by sid-khuntwal** [comment]
I would like to work on this one please assign me

**Comment by sid-khuntwal** [comment]
Ok sure!

**Comment by ParagD25** [comment]
@sid-khuntwal you cannot self assign a issue.

**Comment by sid-khuntwal** [comment]
Oh sorry I just saw other issues where it was done like this so I too did

**Comment by sid-khuntwal** [comment]
Am I still assigned to this?

**Comment by ParagD25** [comment]
> Oh sorry I just saw other issues where it was done like this so I too did

No problem 😊

**Comment by ParagD25** [comment]
> Am I still assigned to this?

Tag python mentors or supervisors and let them decide whom to assign this issue.

**Comment by adityabisoi** [comment]
Related issue  was already created. Closing this
