### ISSUE TITLE
Open Source : 6.23 Explain everything related to `Django`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#4669]
<hr>

## Description 📜

Open Source : 6.23 Explain everything related to `Django`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.23_Django.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by geeythree** [comment]
I'd like to work on this /assign

**Comment by riyapandey730** [comment]
I want to work on this

**Comment by Aryamanz29** [comment]
@palakshivlani-11 Assigned, Happy learning 🎉🎉

**Comment by palakshivlani-11** [comment]
Thank u😊 @Aryamanz29

**Comment by Aryamanz29** [comment]
@palakshivlani-11  Any updates on this?
