### ISSUE TITLE
Open Source : 6.24 Explain everything related to `Apache HTTP Server`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#4670]
<hr>

## Description 📜

Open Source : 6.24 Explain everything related to `Apache HTTP Server`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.24_Apache_HTTP_Server.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by riyapandey730** [comment]
I want to work on this

**Comment by Aryamanz29** [comment]
@geeythree  Assigned, Happy learning 🎉🎉
