### ISSUE TITLE
Open Source : 6.28 Explain everything related to `Vue`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#4675]
<hr>

## Description 📜

Open Source : 6.27 Explain everything related to `Vue`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.28_Vue.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyall** [comment]
@Aryamanz29 I would like to work on this issue

**Comment by Aryamanz29** [comment]
@priyall  Assigned, Happy learning 🎉🎉

**Comment by sid-khuntwal** [comment]
I would like to work on this issue @Aryamanz29

**Comment by priyall** [comment]
> @priyall Any updates on this?

Yes I'll create PR by today

**Comment by Aryamanz29** [comment]
@priyall  Any updates?
