### ISSUE TITLE
Data Science with Python : Generative Adversarial Networks 

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#469]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about gettng started with Generative Adversarial Networks . Tutorial to Generative Adversarial Networks and how it's used effectively with sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Artificial Intelligence

Mentors Assigned : [Yash Goel](https://github.com/Yash621) / [Dhruv Bajaj](https://github.com/DhruvBajaj01) 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by ron352** [comment]
Sarmistha Sarna
Issue no: 469

Documentation
Approach: Introduction to GAN, Structure, Variations etc

**Comment by prathimacode-hub** [comment]
Issue assigned to @ron352 for documentation.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
