### ISSUE TITLE
Open Source : 7.7 Explain everything related to `MIT license`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#4693]
<hr>

## Description 📜

Open Source : 7.7 Explain everything related to `MIT license`

### NOTE 👇
Please put your doc `7.License/` with the name `7.7_MIT_License.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@Bhuvnesh875  Assigned, Happy Learning 🎉🎉

**Comment by Bhuvnesh875** [comment]
@Aryamanz29 thannkyouu
