### ISSUE TITLE
Open Source : 7.9 Explain everything related to `Common Development and Distribution License`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#4695]
<hr>

## Description 📜

Open Source : 7.9 Explain everything related to `Common Development and Distribution License`

### NOTE 👇
Please put your doc `7.License/` with the name `7.9_Common_Development_Distribution_.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Hritik157** [comment]
/ assign

**Comment by Aryamanz29** [comment]
@Hritik157  Assigned, Happy Learning 🎉🎉

**Comment by Hritik157** [comment]
Thank you :)
