### ISSUE TITLE
Recursive Implementation of Tower of Hanoi Problem

### ISSUE THREAD

**Issue by roopali-1** [girlscript/winter-of-contributing#4725]
### Description

Explain about Tower of Hanoi problem and it's recursive implementation in CPP. 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by roopali-1** [comment]
@Suvraneel sir here it is mentioning that supervisor/mentor has to assign this issue to me manually. I am not working on any other issue at present time . so can I start working on this one ??

**Comment by roopali-1** [comment]
> Close your old issues (that are assigned to you)

done only this issue is there in the assigned section

**Comment by Suvraneel** [comment]
But okay... I'm doing manually so no one else takes this up before you do

**Comment by roopali-1** [comment]
yes, thank you sir ..for assigning :)
