### ISSUE TITLE
Competitive_Programming: Arrays 

### ISSUE THREAD

**Issue by supriya-045** [girlscript/winter-of-contributing#476]
I would like to write documentation on array in competitive programming from its theory to all practice questions.

Topics will be covered:
1. Introduction to Arrays 
2. Multidimensional arrays
3. declaration and examples
4. Rotation of arrays
5. Product array puzzle

Please assign this issue to me.

**Comment by uditkatyal** [comment]
Hey pls assign this issue to me!

**Comment by geeky01adarsh** [comment]
Name: Adarsh  Navneet Sinha
Batch: CP batch 1
Type: Documentation
I want to work on the documentation of this issue. Please assign the documentation part to me.

**Comment by shubhamjain2001** [comment]
Hello I am Shubham Jain from CP batch 4 . Please assign this task to me

**Comment by asppanda12** [comment]
Hello I am Sameer I would like do all documentation part on this
