### ISSUE TITLE
2.1.18.1_Lyndon_Factorization - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4779]
## Description
What is Lyndon factorization? Discuss Duval algorithm, give its implementation and complexity.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by thatSophisticatedMess18** [comment]
okay, sorry mam.

**Comment by nimisha-yadav** [comment]
> Hello mam , I have a doubt that in which folder do I have to include this document? And document has to be made in google collab only? Can you please guide me through this. @nimisha-yadav

Hey, there's a folder named Lyndon Factorisation in 2.1 Strings. You need to add your file there and name it 2.1.18.1_Lyndon_Factorisation.md 
And you need to add your documentation via md files, that's it. For reference, you can glance through the already merged files there. @thatSophisticatedMess18

**Comment by nimisha-yadav** [comment]
@motasimmakki you may take up this issue.

**Comment by motasimmakki** [comment]
> @motasimmakki you may take up this issue.

sure, thanks! ✨
