### ISSUE TITLE
2.1.18.2_Suffix_Automaton - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4782]
## Description
What is suffix automaton for a string? Discuss its properties and give examples.

**Important: Do not use assign command for this issue.**
## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Hritik157** [comment]
@nimisha-yadav mam I'm not the part DSA contribution domain, still can I contribute in this issue? Though I'm part of GWOC

**Comment by Hritik157** [comment]
If possible could you assign this issue to me

**Comment by sonali-t** [comment]
@nimisha-yadav  I would like to work on this issue(documentation part). Please assign it to me.
Sonali Tomar
DSA Batch-4
