### ISSUE TITLE
DSA 2.1.19_Expression_Parsing - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4785]
## Description
What is Expression Parsing? Discuss the notations and properties.
**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ayushjha952** [comment]
I want to work on the documentation part @nimisha-yadav can you please assign it to me ?
Ayush Jha
DSA Batch - 3.

**Comment by mehabhalodiya** [comment]
@nimisha-yadav Please assign this to @ayushjha952

**Comment by Parth-001-git** [comment]
@nimisha-yadav Please review (The previous one was not correct)
