### ISSUE TITLE
DSA 2.2 Stability in Sorting Algorithms - Audio

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#4790]
## Description
What do you mean by stability in sorting algorithms? Which sorting algorithms are unstable? Give examples. How can you make them stable?
**Important: Do not use assign command for this issue.**
## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ujju20** [comment]
Can I take this issue?

**Comment by ujju20** [comment]
My Full name is Ujjawal Sharma and batch number is 1.

**Comment by nimisha-yadav** [comment]
> My Full name is Ujjawal Sharma and batch number is 1.

@ujju20 it's been many days, kindly submit PR within 2 days else the issue will be closed.

**Comment by jaigora24** [comment]
@nimisha-yadav mam assign this issue to me, if it is pending.
Name - Jai Gora
Batch - 7
