### ISSUE TITLE
DSA 1.2.2.1 Algorithms: Recurrence Relations (Introduction)

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#482]
## Description
Explain recurrence relations and their properties.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to the [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by siddhi-244** [comment]
Siddhi Bhanushali 
Dsa batch 1
I would like to try this

**Comment by Harshil-Jani** [comment]
Harshil Jani
DSA Batch 2
Can I try with Documentation?

**Comment by geeky01adarsh** [comment]
Name: Adarsh  Navneet Sinha
Batch: DSA batch 2
Type: Documentation
I want to work on the documentation of this issue. Please assign the documentation part to me.

**Comment by nimisha-yadav** [comment]
> 
> 
> Harshil Jani
> DSA Batch 2
> Can I try with Documentation?

Assigning this issue to you @Harshil-Jani, all the best!

hey @siddhi-244 and @geeky01adarsh, since you're already working on an issue so newer people are given the chance. Let me know if y'all are interested in audio/video format of this issue, I'll assign them to you.

**Comment by mansisingh2803** [comment]
@nimisha-yadav pls assign this issue to me for video and audio type
Mansi Singh
Batch -4

**Comment by siddhi-244** [comment]
Plzz assign this issue to me.

**Comment by jaisinha** [comment]
Can you assign this issue to me?

**Comment by nimisha-yadav** [comment]
@siddhi-244 and @jaisinha, can you elaborate in which format(Audio/Video/Improvement to Doc) and in what way would you be contributing?

**Comment by siddhi-244** [comment]
> @siddhi-244 and @jaisinha, can you elaborate in which format(Audio/Video/Improvement to Doc) and in what way would you be contributing?

Improvement to doc.
