### ISSUE TITLE
string pool in java

### ISSUE THREAD

**Issue by Danish-Belal** [girlscript/winter-of-contributing#4857]
### Description

Explain String pool in java

### Domain

Java_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shahishree03** [comment]
can I be part of this issue

**Comment by SAYAK-CHAKRABORTY** [comment]
I would like to contribute to this
SAYAK CHAKRABORTY
java(batch1)

**Comment by SAYAK-CHAKRABORTY** [comment]
@Danish-Belal i am still working on this issue

**Comment by SAYAK-CHAKRABORTY** [comment]
@Danish-Belal  kindly review my issue

**Comment by SAYAK-CHAKRABORTY** [comment]
@Danish-Belal kindly review my pull Request
