### ISSUE TITLE
2D Array Question

### ISSUE THREAD

**Issue by Danish-Belal** [girlscript/winter-of-contributing#4864]
### Description

2D Array Questions.

### Domain

C_CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Danish-Belal** [comment]
assign/

**Comment by Danish-Belal** [comment]
assign/

**Comment by Danish-Belal** [comment]
assign/

**Comment by poorvi-vaish** [comment]
If it is not assigned yet, I think you're using the wrong method, use /assign
