### ISSUE TITLE
FRONTEND WITH FRAMEWORK: VueJS-1.1 => VueJS Intro (uses, benefits, scalability)

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [girlscript/winter-of-contributing#489]
Contributors are required to include an Introduction of VueJS which covers basic questions for a newcomer. like:-
What is VueJs?
Why do we use it?
What are its benefits?
etc ...

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by Techno-Simpola** [comment]
@SourabhSaraswat-191939  may I contribute and may you 
assign this issue to me

**Comment by SourabhSaraswat-191939** [comment]
Hey @Techno-Simpola ,
Sorry for the inconvenience as this issue is closed because a similar kind of similar issue is already there.
I will suggest you to work on other issue.
I made one new issue. The task will be assigned on first come first serve.
[https://github.com/girlscript/winter-of-contributing/issues/523](https://github.com/girlscript/winter-of-contributing/issues/523)
