### ISSUE TITLE
Most popular Algorithms asked in Interviews.

### ISSUE THREAD

**Issue by singhnikhiljsr** [girlscript/winter-of-contributing#4891]
### Description

Here, I will be listing most popular Algorithms Definitions, where to use it along with its psuedo code where applicable.

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by rhythmjayee** [comment]
@syedareehaquasar can you close this issue and other merged/done issues

**Comment by syedareehaquasar** [comment]
sure

**Comment by rhythmjayee** [comment]
@syedareehaquasar I can close only issues that were opened by me.
