### ISSUE TITLE
Android-Java: 1.4 Creating First Project

### ISSUE THREAD

**Issue by Rohit-2602** [girlscript/winter-of-contributing#49]
## Description ->
- Explain how to create the first project
- Explain About selecting different base Activity and API level

## Source ->
- https://developer.android.com/studio/projects/create-project

## Note ->
- Changes should be made inside the Android_Development/Java directory & Android_Development_with_java branch.
- Issue only for GWOC'21 contributors.
- Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.

Must-Follow: Contributing Guidelines & Code of Conduct before start Contributing.

**Comment by saigoud25** [comment]
can I work on this??

**Comment by Rohit-2602** [comment]
Yes sure mate

**Comment by kritika2311** [comment]
can I work on this.

**Comment by Arjun2905** [comment]
I would like to work on this issue.

**Comment by Arjun2905** [comment]
@Rohit-2602 please assign this issue to me

**Comment by Rohit-2602** [comment]
This issue is already assigned to @saigoud25

**Comment by priyanshu688** [comment]
I would like to work on this..

**Comment by LegendSumeet** [comment]
can you assign this work to me? @Rohit-2602

**Comment by Rohit-2602** [comment]
@saigoud25 can you please give a progress update about the issue and if you are facing any problem feel free to ask.

**Comment by saigoud25** [comment]
I'm working on it. Is there any deadlines to complete?

**Comment by Rohit-2602** [comment]
there is no deadline, but will be better if you complete it as soon as possible

**Comment by saigoud25** [comment]
can you check the PR
