### ISSUE TITLE
Android-Kotlin: 02.3 Loops in Kotlin

### ISSUE THREAD

**Issue by Sakalya100** [girlscript/winter-of-contributing#491]
I want to create and make the documentation for this topic. Kindly assign me this issue @rahulsain 
Myself Sakalya Mitra(Batch 3 Android Dev with Kotlin)

**Comment by sitamadex11** [comment]
@Sakalya100 please change the number from 04.1 to 02.3

**Comment by Sakalya100** [comment]
Done @sitamadex11

**Comment by ayush-sleeping** [comment]
Hey @rahulsain , I would like fix the Audio part of this issue . <br>
Assign me this issue
