### ISSUE TITLE
DSA 1.1 Readme.md

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#493]
## Description
Contribute to the readme file of week 1 topic Arrays.

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by geeky01adarsh** [comment]
Name: Adarsh  Navneet Sinha
Batch: DSA batch 2
Type: Documentation
I want to work on the documentation of this issue. Please assign the documentation part to me.

**Comment by HassanRahim26** [comment]
Hey @pjdurden, I would like to work on this issue. Can you please assign me this issue?
Name:- Hassan Rahim
Batch: DSA batch 2
Type: Documentation

**Comment by Raghavshalu** [comment]
I can do this work so...can u please assign me this issue... thank you! 
Type:-documentation
Batch:-5

**Comment by uditkatyal** [comment]
@pjdurden   assign this issue to me 
Name : Udit katyal
Batch Number :- 3
Type : Documentation

**Comment by Subhradeep10** [comment]
@uditkatyal @Raghavshalu @HassanRahim26 Go for it
