### ISSUE TITLE
DSA 1.2 Readme.md Analysis of Algorithms

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#494]
## Description
Contribute to the readme file of week 1 topic Analysis of Algorithms.

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by lohith1392** [comment]
I am not belonging to death but I am interested can I do

**Comment by lohith1392** [comment]
Dsa*

**Comment by geeky01adarsh** [comment]
Name: Adarsh  Navneet Sinha
Batch: DSA batch 2
Type: Documentation
I want to work on the documentation of this issue. Please assign the documentation part to me.

**Comment by HassanRahim26** [comment]
Hey @pjdurden, I would like to work on this issue. Can you please assign me this issue?
Name:- Hassan Rahim
Batch: DSA batch 2
Type: Documentation

**Comment by uditkatyal** [comment]
Name : Udit katyal
Batch : DSA batch 3
Type: documentation
Pls assign this issue to me!

**Comment by Subhradeep10** [comment]
@pjdurden @HassanRahim26 @geeky01adarsh Assigned to you
