### ISSUE TITLE
Android-Development-Java 4.4: Android-Context-Menu

### ISSUE THREAD

**Issue by Rohit-2602** [girlscript/winter-of-contributing#4958]
### Description

Give a brief about
- Context Menu
- Usage
- How to use it in Activities and Fragments.

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Pradumnasaraf** [comment]
/assign 

This issue is now open for almost a month, now I will be working on this issue

**Comment by Pradumnasaraf** [comment]
This issue is now open for almost a month, now I will be working on this issue.

@VikasPandey121 @Rohit-2602
