### ISSUE TITLE
Cybersecurity: 1.2 What is the importance and need for information security?

### ISSUE THREAD

**Issue by Nikita512** [girlscript/winter-of-contributing#498]
Please assign me this issue, I want to make documentation/audio content for the issue.
Nikita Agrawal (Batch-1, Cyber Security)

**Comment by imcoza** [comment]
Assign this issue to me. I want to write documentation on this issue.
Imama Shehzad

**Comment by Anant1711** [comment]
@Nikita512 Please Do not make issues from your side, and this issue has already been done in the documentation format.
But if you want to make `audio` then I'll assign you this task!
But please don't make issues from your side, ask me on discord (DM or on batch-1-cybersecurity channel by mentioning me). I will surely help you!

**Comment by Anant1711** [comment]
> Assign this issue to me. I want to write documentation on this issue.
> Imama Shehzad

@imcoza Sorry, this task is already Done!
You can check other active issues!

**Comment by Anant1711** [comment]
@Nikita512 What is your working status on this topic?
When you will go to submit your work?

**Comment by Nikita512** [comment]
@Anant1711 I was not able to complete due to health issues, Can I submit by tomorrow?

**Comment by Anant1711** [comment]
Yes please submit it by tomorrow!

**Comment by Nikita512** [comment]
@Anant1711 Please let me know how to upload audio file and submit and pull request

**Comment by Anant1711** [comment]
> @Anant1711 Please let me know how to upload audio file and submit and pull request

Upload your audio on your google drive, then copy the link of your audio!
Then make a `<Your_topic_name>.md` file in respective Week folder and embed your audio like this!
![](your_audio_link)

**Comment by Nikita512** [comment]
@Anant1711 I created .md file and embed the audio file, how to add in week folder it's showing to pull request

**Comment by Nikita512** [comment]
@Anant1711 I'm new to Git, can you guide me through all the steps?

**Comment by Anant1711** [comment]
@Nikita512 
Go to the week 1 folder, where you have to create .md file and embed your audio link!
then commit!

**Comment by Nikita512** [comment]
Do I have to fork the file? @Anant1711

**Comment by Anant1711** [comment]
> Do I have to fork the file? @Anant1711

Yes you have to fork the girlscript repo

**Comment by Nikita512** [comment]
I have forked but I cannot clone the repo in to local machine
![image](https://user-images.githubusercontent.com/54329368/135301879-a9f6ac26-f610-4655-b14e-1ea738e2509c.png)

**Comment by Nikita512** [comment]
![image](https://user-images.githubusercontent.com/54329368/135312509-e9964045-4e20-41f2-a39a-9988657ee6e1.png)

**Comment by Anant1711** [comment]
Try again!

**Comment by Nikita512** [comment]
@Anant1711 still same issue is there with checkout failed
