### ISSUE TITLE
Frontend with HTML and CSS: HTML Form and Form Validation. (Documentation)

### ISSUE THREAD

**Issue by Ananya-Patra9437** [girlscript/winter-of-contributing#499]
**Documentation**
BATCH - 17

**Comment by Adarshswain** [comment]
can i go for it

**Comment by CrypticMuze** [comment]
Id like to get assigned this issue

**Comment by guptapriya-83900** [comment]
Can I make a contribution in this issue in the form of documentation?

**Comment by FirdausJawed** [comment]
I wanna work on this issue

**Comment by Rishika-Gaur** [comment]
I am interested in doing this topic too.

**Comment by Ayushi2811** [comment]
Can i make a well descriptive vedio on this
Ayushi Chauhan
batch-1

**Comment by Adarshswain** [comment]
I am from batch-17

**Comment by DeepCoomer** [comment]
I would like to contribute in this issue
Deep Coomer
Batch - 5

**Comment by krupesh87** [comment]
I would like to contribute in this issue.
krupesh patel,
Batch-5.

**Comment by bumblebee28** [comment]
Hey @Ananya-Patra9437 , I am familiar with the concept of Form and Form validation and have been learning HTML and CSS. Can I contribute to this issue?

**Comment by prathamjagga** [comment]
I want to do it!

**Comment by ghulamyazdani** [comment]
@Ananya-Patra9437 and @Adarshswain Assigned this issue to you both! 
Please reply if you are taking this.

**Comment by Drontitan** [comment]
hey@Ananya-Patra9437 pls give me this isuue thank you

**Comment by Adarshswain** [comment]
till which date i have to submit

**Comment by Adarshswain** [comment]
yes I am ready to assign

**Comment by Himanshu664** [comment]
"/assign"

**Comment by rishabh2030** [comment]
please assign me this issue i will work on it and Definitely make it amazing

**Comment by Ananya-Patra9437** [comment]
> @Ananya-Patra9437 and @Adarshswain Assigned this issue to you both!
> Please reply if you are taking this.

yes,its my pleasure to contribute to this issue.

**Comment by chakitg** [comment]
Hey creator, I would like to work on this issue. Can you please assign me this?
Name: Chakit Gupta
Batch: Frontend with HTML CSS Js Batch-4
Type: Documentation

**Comment by joshi-kaushal** [comment]
Is this issue still on? I'd love to work on this!
