### ISSUE TITLE
Android-Development-Java 2.1.4 ViewPager in Android

### ISSUE THREAD

**Issue by Rohit-2602** [girlscript/winter-of-contributing#5006]
### Description

Explain -

- What is EditText
- Attributes
- Use cases with some code example

Also, include TabLayout for the same

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Rohit-2602** [comment]
@ShivaniAgarwal2001 do "/assign"

**Comment by eshan1925** [comment]
@VikasPandey121 This is the issue and i have generated the pr.
Please review it.
Thanks

**Comment by eshan1925** [comment]
@VikasPandey121 I have updated the image now.
Please have a look
