### ISSUE TITLE
Android-Development-Java 2.1.7 CardVew in Android

### ISSUE THREAD

**Issue by Rohit-2602** [girlscript/winter-of-contributing#5009]
### Description

A brief about CardView and its attributes.

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ShivaniAgarwal2001** [comment]
@Rohit-2602 assign documentation

**Comment by VikasPandey121** [comment]
> > @ShivaniAgarwal2001 complete those issues first
> > if you facing some problem regarding anything ask us in chat
> 
> The issues are from different domains, and I have already created the PR but the mentors are taking time to merge. And now I am sitting empty-handed.

Please tag your PR with the issue and tag any of the mentors for review.
