### ISSUE TITLE
[DSA 1.1] Scanline Algorithm

### ISSUE THREAD

**Issue by abhinavdixit2306** [girlscript/winter-of-contributing#5036]
### Description

<h1> Scanline ALgorithm </h1>
<p> This algorithm is used very much in competitive programming and has various use cases. </p>

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
All the valid merged PRs will automatically count for hacktober fest, all the best.

**Comment by abhinavdixit2306** [comment]
@nimisha-yadav Please review my PR and let me know if any changes are required.
https://github.com/girlscript/winter-of-contributing/pull/5194
