### ISSUE TITLE
[DSA]:Arrays: Valid Sudoku: C++

### ISSUE THREAD

**Issue by ishrutik** [girlscript/winter-of-contributing#5043]
### Description

Determine if a 9 x 9 Sudoku board is valid. Return true if sudoku is valid otherwise false. Implemented in C++

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh 
Batch -6
Plz assign to me.
