### ISSUE TITLE
Python: Linked List

### ISSUE THREAD

**Issue by Vibhu562** [girlscript/winter-of-contributing#5111]
### Description

# Description

What is Linked List in Python?
Why we need Linked List in Python?
Some advantages of Linked List

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by naveeramesh** [comment]
/assign
Can I work on this issue for documentation part.?
