### ISSUE TITLE
 Types of Hackers documentation

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#512]
@Anant1711 CAN YOU ASSIGN ME TO THESE?

**Comment by FirdausJawed** [comment]
i want to work on this issue

please assign this to me

**Comment by 0shivamh** [comment]
@LegendSumeet do not make an issue by yourself, the mentor will do. and types of hacker issue is already created and assigned.

**Comment by Anant1711** [comment]
ya! Guyz please do not make issues by yourself, Please be active on the discord channel! I'll post there all updated/new issues
@LegendSumeet @FirdausJawed
