### ISSUE TITLE
Python: String Method

### ISSUE THREAD

**Issue by Vibhu562** [girlscript/winter-of-contributing#5126]
### Description

# Description
What are methods in String.
Explain all method by giving suitable example.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by guptapriya-83900** [comment]
@adityabisoi 
I would like to do the documentation part of this issue. Please assign me this issue.

**Comment by Vibhu562** [comment]
@adityabisoi Please assign me my task.

**Comment by harmankaler2000** [comment]
Hey can I work on this issue through video contribution
Harmandeep Kaur Kaler
python batch - 4
