### ISSUE TITLE
Puzzles for Inteviews

### ISSUE THREAD

**Issue by akriti-upadhyay** [girlscript/winter-of-contributing#5168]
### Description

This will include the resources for the Puzzles that are asked in interview rounds

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by akriti-upadhyay** [comment]
@princemsd007 @syedareehaquasar Hey, I created this issue, can I start working on it? Also, can you please tell me how can I add the label "hacktoberfest" in this issue?

**Comment by syedareehaquasar** [comment]
I am adding the label You can also edit I guess in the right pannel!
You can go ahead with this issue!

**Comment by akriti-upadhyay** [comment]
@syedareehaquasar Hey, I am really sorry, I think I merged my pull request and closed it by mistake. How can I undo this now? My PR was not yet reviewed.

**Comment by syedareehaquasar** [comment]
it's merged in ur repo if u want I can unmerge the changes but it's not pushed into GWoc repo yet. it's merged from ur branch to main.
