### ISSUE TITLE
C CPP : Documentation on Palindrome using Stack

### ISSUE THREAD

**Issue by itsgourav62** [girlscript/winter-of-contributing#5175]
### Description

This code will be using stack to determine the string is a palindrome or not..

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing as the PR got merged
