### ISSUE TITLE
OpenSource : 6.39 Explain everything related to `gun.js`

### ISSUE THREAD

**Issue by ashish-patwal** [girlscript/winter-of-contributing#5240]
### Description

[![GUN](https://i.ytimg.com/vi/oTQXzhm8w_8/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAk_A97ffzKYXm5Hcw4FXy-z7SLYQ)](https://www.youtube.com/watch?v=oTQXzhm8w_8)

## Description
GUN is an opensource project and an ecosystem of tools that allows you to create encrypted applications that run thanks to a community . Gun is based on Decentralized web or "Dweb" and aims to make the internet freer and less greedy by leveraging p2p encrypted connections , decentralized database and inbuilt user authentication . 

## Points to cover 
- What is gun.js
- Idea behind gun.js
- Advantages of gun.js ( eg. p2p encrypted connections , Decentralized network etc )
- Examples of gun.js 

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Meghna2080** [comment]
@ashish-patwal

**Comment by Meghna2080** [comment]
Yes, I created some issues of other domains and self assigned yesterday only

**Comment by HassanRahim26** [comment]
@ashish-patwal, can you please assign me this issue

**Comment by HassanRahim26** [comment]
> > @ashish-patwal, can you please assign me this issue
> 
> You are already assigned to it

So, can I work on this issue?

**Comment by ashish-patwal** [comment]
> Okay @ashish-patwal sir, apologies for the inconvenience caused

@Meghna2080 , Hey no worries . And please no salutation . I'm not that old .

**Comment by ashish-patwal** [comment]
> @ashish-patwal am i also eligible to contribute in this

@Adi9235 Sorry , the issue has already been claimed .
