### ISSUE TITLE
Android-Development-Java 4.5: BroadCast Receivers in Android

### ISSUE THREAD

**Issue by Rohit-2602** [girlscript/winter-of-contributing#5285]
### Description

Give a brief about BroadCast Receivers with a simple example (can be: Data Change, Connectivity Change)

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by SB2318** [comment]
I want to work on this issue. Please assign it to me @Rohit-2602

**Comment by Rohit-2602** [comment]
@SB2318 type "/assign"
