### ISSUE TITLE
Front_End: HTML Forms

### ISSUE THREAD

**Issue by GenMech** [girlscript/winter-of-contributing#529]
<h1>HTML Forms</h1>

- Creating HTML forms with HTML/CSS

<h3>Description</h3> 

- Forms Attributes
- Forms Elements
- Input Types
- Input Attributes
- Input Forms Attributes

**Comment by uditkatyal** [comment]
Assugn this issue to me 
I have worked on numerous projects that used forms in it!

**Comment by GenMech** [comment]
@ghulamyazdani @praveenscience I have good hold on HTML and i have created this issue , i would like to contribute in this in a well documented form Kindly assign it to me.

**Comment by anushka-mishra-code** [comment]
I would be glad to work on this issue.
Name : Anushka Mishra
Batch : 1
Serial No.: 175
Type : Documentation
Approach:

Brief Introduction to HTML ,CSS
Explaination of all the elements , attributes, etc to be used in form
Explaination of how to create  a form with example

**Comment by Ayushi2811** [comment]
Can i create a vedio on this
Ayushi Chauhan
barch-1
do assign vedio task to me @GenMech

**Comment by monotion25** [comment]
please assign it to me

**Comment by SakshiSharma2002** [comment]
I have created numerous html forms. I have a good command over HTML5 and CSS3. I would be glad to work on this issue, Please assign this issue to me!!
Name : Sakshi Sharma
Batch : 10
Type : Documentation
Approach : 
1) Brief Introduction to HTML ,CSS and the form 
     tag.
2) Explaination of all the GUI elements/Input 
     controls , attributes, etc to be used in form with 
     examples.
3) Explanation of new form attributes given by 
     HTML5 with examples.
4) Explaination of how to create a form with 
     Examples.

**Comment by Kalyani02072003** [comment]
can I be assigned to this documentation?
I am a beginner but I will try my best to provide the best
batch - 18 frontend
discord - STRAWHAT_LUFFY#8651

**Comment by rishabh2030** [comment]
please assign me this issue i will work on it and Definitely make it amazing

**Comment by Binita-tech** [comment]
\assign

**Comment by HarshS1611** [comment]
\assign 
Harsh Singh 
Batch 12

**Comment by abhi-2024** [comment]
I have learnt HTML thoroughly and I believe I can give a good insight on this topic.
    
/assign

Documentation
Batch -18

**Comment by manishkumar-hub** [comment]
\assign document

**Comment by HarshS1611** [comment]
Please assign me for this issue
