### ISSUE TITLE
Explain the Sliding Window Technique 

### ISSUE THREAD

**Issue by paul-111** [girlscript/winter-of-contributing#5291]
### Description

Description

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by tanvideshmukh29** [comment]
Can I work on it ?
Tanvi Deshmukh
Batch -7

**Comment by Aishwarya713** [comment]
/assign 
Aishwarya Rai
Batch 2
