### ISSUE TITLE
Cybersecurity 6 Vulnerability identification

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#5307]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
@dummy-co-der

**Comment by dummy-co-der** [comment]
Yes Sir @Anant1711 ?

**Comment by Anant1711** [comment]
> Yes Sir @Anant1711 ?

You didn't submit your work !!!!

**Comment by dummy-co-der** [comment]
Sit it's already done !! Here is the link of the md file you can check https://github.com/girlscript/winter-of-contributing/pull/5823/commits

**Comment by Anant1711** [comment]
> Sit it's already done !! Here is the link of the md file you can check https://github.com/girlscript/winter-of-contributing/pull/5823/commits

Ok ok....lemme merge it!
Thanks

**Comment by dummy-co-der** [comment]
Yes sir !!
