### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular -> How to Create a Component using Angular CLI?

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#531]
- How to create a component using cli?
- What files are created when you create a component?

Things to be included:-

1.  cli command ?
2. Files created and their use?

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "**Frontend_Web_Development_React_Angular_Vue/Angular/Week1**" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by RIYANSHGARG** [comment]
I would Like to work on this issue. kindly assign it to me

**Comment by mukeshmjn** [comment]
> I would Like to work on this issue. kindly assign it to me

Go on!

**Comment by RIYANSHGARG** [comment]
I have added a pull request please consider it.
