### ISSUE TITLE
Cybersecurity 6.3 Remediation

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#5310]
### Description

Discuss about Remediation in Vulnerability assesment!

## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
> Assign this to me pls. Name - Mohd Uvaish Siddiqui Batch - 1 Cyber Security Type - Documentation

One Task at a time!

**Comment by Anant1711** [comment]
> Assign this to me Name - Atharva Patil Batch 1 - Cyber Security Type - Documentation

Assigned!

**Comment by Anant1711** [comment]
@AtharvaaPatil 
Submit your work!

**Comment by RK1905101** [comment]
can i take up this issue, if he's not working on it!?
@Anant1711

**Comment by Anant1711** [comment]
> can i take up this issue, if he's not working on it!? @Anant1711

yes,  please!

**Comment by RK1905101** [comment]
@Anant1711 , i guess this issue has been completed, as the documentation part is been shown in the week 6 folder.

![image](https://user-images.githubusercontent.com/64470404/143678638-c321daeb-16a6-455d-9d55-aa815fa95740.png)
