### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular -> How to create an Angular Component manually without CLI?

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#532]
- Briefly explain how to create an Angular Component without Angular CLI?
- What files need to be created? 
- What import need to be done?
- Reference:- https://angular.io/guide/component-overview

Note:- 

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "**Frontend_Web_Development_React_Angular_Vue/Angular/Week1**" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by CSAURABH** [comment]
@mukeshmjn can i work on this issue (Documentation).

**Comment by anandhu720** [comment]
@CSAURABH yes

**Comment by mukeshmjn** [comment]
@CSAURABH any updates on this?
