### ISSUE TITLE
ML 4.8: Implement DQNs (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#5320]
### 📌  Issues for Week 4
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Implement DQNs_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). **Please note this issue is for VIDEO contribution only**

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Reinforcement_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by abhisheks008** [comment]
@karma659 It's been 6 days still you have not come up with the PR. Why?

**Comment by karma659** [comment]
I will do the PR today . My laptop had issues it is now resolved.

**Comment by karma659** [comment]
Can i do it by 20th , I have an emergency .

**Comment by ShraddhaMeshram27** [comment]
Full name - Shraddha Meshram
Batch Number - ML batch 3
GitHub Profile Link - https://github.com/ShraddhaMeshram27
Contribution type: video

Would like to take up this issue and complete my work within 2 days positively.
Can you assign this issue to me?

**Comment by raina-akshay** [comment]
go for it @ShraddhaMeshram27

**Comment by abhisheks008** [comment]
@ShraddhaMeshram27 complete the PR ASAP.

**Comment by ShraddhaMeshram27** [comment]
Yes, I will do it today itself.

**Comment by abhisheks008** [comment]
@ShraddhaMeshram27 How much time do you need now?

**Comment by abhisheks008** [comment]
@ShraddhaMeshram27 ❓

**Comment by ShraddhaMeshram27** [comment]
I have made the PR.
Sir, do we need to do 5 PR to avail the certificate?

**Comment by abhisheks008** [comment]
> I have made the PR. Sir, do we need to do 5 PR to avail the certificate?

@ShraddhaMeshram27 yeah you need to complete 5 PRs irrespective of the domain.
