### ISSUE TITLE
ML 4.9: Practical Applications of Reinforcement Learning (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#5329]
### 📌  Issues for Week 4
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Practical Applications of Reinforcement Learning_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). **Please note this issue is for VIDEO contribution only**

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Reinforcement_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

******************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by usgn94** [comment]
I would like to work on documentation
Pla assign me

**Comment by srini047** [comment]
Hi, I would like to work on this issue.
Name: Sriniketh J
Batch No: 1
Profile: https://github.com/srini047/
Type: Video

**Comment by abhisheks008** [comment]
Update on this issue @srini047

**Comment by srini047** [comment]
> Update on this issue @srini047

I have **done** the PPT and just need to record the *video*.
I will **update** within *tomorrow* @abhisheks008.

**Comment by abhisheks008** [comment]
@srini047 Whats the update on this issue?
