### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular -> Angular Component LifeCycle

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#534]
- Briefly Explain Angular Component LifeCycle Hooks.
- What functions/methods are their in lifecyle hooks? like ngoninit, ngOnChanges
- Also, explain these functions use sequentially.

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week1" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by CSAURABH** [comment]
can i work on this issue

**Comment by monotion25** [comment]
can i work on this issue?

**Comment by Techno-Simpola** [comment]
I also want to work on this, I may work on Documentation part of this issue

**Comment by mukeshmjn** [comment]
@CSAURABH I think you are already working on other issues as well..Let others get a chance too :)/// @monotion25 assigning u this!

**Comment by mukeshmjn** [comment]
@monotion25 what you are going to do documentation, audio or video?

**Comment by debidattasuryaprakash** [comment]
Can I work on this issue?

**Comment by mukeshmjn** [comment]
@monotion25 any updates on this?

**Comment by mukeshmjn** [comment]
As @monotion25 has not been responding since 2 days after been asked too .. @Techno-Simpola u would like to work on this?

**Comment by Techno-Simpola** [comment]
ya sure

**Comment by Techno-Simpola** [comment]
It would be great to work on this topic

**Comment by mukeshmjn** [comment]
Go for it @Techno-Simpola

**Comment by mukeshmjn** [comment]
@Techno-Simpola any updates over this? It's already been 3days.

**Comment by pankaj-Makhijani** [comment]
Hello @mukeshmjn I would like to work on the documentation part of this issue.

**Comment by debidattasuryaprakash** [comment]
May I work on this issue?

**Comment by RIYANSHGARG** [comment]
I want to work on this issue, kindly assign it to me.

**Comment by mukeshmjn** [comment]
@pankaj-Makhijani any updates over this?

**Comment by pankaj-Makhijani** [comment]
Working on it, will create PR by tomorrow.

**Comment by RIYANSHGARG** [comment]
Is this issue open ? as already 15 days are passed if there is no pull request for it or no one is working on it then I would like to work on it .

**Comment by mukeshmjn** [comment]
@pankaj-Makhijani any updates?
If you dont make a pr I will assign to @RIYANSHGARG tomorrow .. @RIYANSHGARG just wait till tomorrow..

**Comment by RIYANSHGARG** [comment]
ok sir .

**Comment by pankaj-Makhijani** [comment]
@mukeshmjn Please check my PR and let me know if any changes are required.
