### ISSUE TITLE
DSA:2.2.12 Explain everything related to shell sort

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5343]
## Description
Give an introduction and explain the working of shell sort

## Task

- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AJgthb2002** [comment]
Hi, please assign it to me. I'd like to contribute in the form of documentation

**Comment by Muskan-creator** [comment]
This issue is for audio addition .You can work on audio part

**Comment by AJgthb2002** [comment]
@Muskan-creator I want to work on documentation only.. saw the documentation tag so I thought this issue is open for documentation. 
If not, kindly unassign me. I'll choose another issue
