### ISSUE TITLE
DSA:2.2.13 Everything about shell sort 

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5344]
## Description
Give an introduction and explain the working of shell sort in video format

## Task

- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by VandanaKumari18** [comment]
Pls assign this to me..
Dsa batch 8

**Comment by taranjotsingh23** [comment]
I am Taranjot Singh from DSA Batch-7. Could you please assign me this issue?

**Comment by atharva20-coder** [comment]
@Muskan-creator Is this repository is out of hacktoberfest because I have submitted 1 PR which is accepted but it shows me *Excluded Project*�
![Screenshot 2021-10-19 121524](https://user-images.githubusercontent.com/69634375/137858153-e796e34d-a534-4629-9b69-7a178565d9b6.png)
�
