### ISSUE TITLE
DSA:Quick_Sort

### ISSUE THREAD

**Issue by dikshamalik2552** [girlscript/winter-of-contributing#5345]
### Description

Adding all about the searching and sorting algorithm Quick sort and its implementation in java

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Muskan-creator** [comment]
Please don not create duplicated issue
