### ISSUE TITLE
DSA:2.2.1.1 Difference between searching and sorting algorithms

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5346]
## Description
Give an introduction and explain difference between searching and sorting algorithms

## Task
- [ ] Documentation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by 0xUvaish** [comment]
Assign this to me pls.
Mohd Uvaish Siddiqui
Batch - 7 DSA
Type - Documentation

**Comment by tanvideshmukh29** [comment]
Plz assign to me
Tanvi Deshmukh
Batch 7

**Comment by dhruti29** [comment]
@Muskan-creator I would like to work on this issue. (documentation)
Batch -2
Dhruti Gandhi

**Comment by Muskan-creator** [comment]
@dhruti29 assigning to you
