### ISSUE TITLE
[DSA]: 2.2.1.2 Differnece between searching and sorting algorithms.

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5348]
## Description
Give an introduction and write about differences between searching and sorting alogorithms

## Task

- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by mrkc2303** [comment]
@Muskan-creator Should I unassign this issue to me as there is a limit of 3 so that I can work on more issues?
