### ISSUE TITLE
JUCE Framework with C++

### ISSUE THREAD

**Issue by 1PRatgit** [girlscript/winter-of-contributing#5349]
### Description

Explain about JUCE framework with respect to C++ in documentation.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as PR #5449 got merged
