### ISSUE TITLE
DSA:2.1.14.1 explain Knuth–Morris–Pratt algorithm(Strings)-Documentation

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5356]
### Description

Discuss the Knuth–Morris–Pratt . Mention about its implementation, complexity, examples.

## Task
- [ ] Documantation

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by thatSophisticatedMess18** [comment]
Diksha Gupta
Batch -2

**Comment by jaigora24** [comment]
Jai Gora 
Batch 7

**Comment by Muskan-creator** [comment]
@Sakshi-1101 Assigning to you

**Comment by Muskan-creator** [comment]
Hey @Sakshi-1101 , No need to make directory folder push your changes in strings folder
