### ISSUE TITLE
[DSA]: 2.2.14.2 Explain Knuth–Morris–Pratt algorithm(Strings)-Audio

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5357]
### Description

Discuss the Knuth Moris Pratt Algorithm. Mention about its implementation, complexity, examples.

## Task
- [ ] Audio

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Muskan-creator** [comment]
Do you want to work on this issue @Palak-Srivastava ?

**Comment by Palak-Srivastava** [comment]
Yes @Muskan-creator Maam, Can I?
