### ISSUE TITLE
DSA:2.2.14.3 Explain Knuth–Morris–Pratt algorithm(Strings)-Video

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#5358]
### Description

Discuss theKnuth–Morris–Pratt  Algorithm. Mention about its implementation, complexity, examples.

## Task
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by diya-dhan** [comment]
Diya Dhandapani
Batch 11
I would like to work on this please @Muskan-creator
