### ISSUE TITLE
FRONTEND WITH FRAMEWORK: VueJS-1.4 => Intro to Lifecycle Diagram and Lifecycle Hooks (Theory explanation)

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#540]
Contributors are required to include an Intro to Lifecycle Diagram, which should cover questions like :-
Vue instance
What is LifeCycle Hooks and Diagrams
Explain every 8 life cycle hook
etc....

Also, make sure -
Iclude Diagrams and code snippets for better understanding
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by Saurabh-crypto16** [comment]
I want to do it

**Comment by a12baghel2** [comment]
I want to do it.

**Comment by anandhu720** [comment]
@a12baghel2 sure

**Comment by a12baghel2** [comment]
Thanks for assigning it to me.

**Comment by SourabhSaraswat-191939** [comment]
Hey @a12baghel2, are there any updates regarding this issue?
If you are facing any problem while working then you can discuss it here or on Discord.

**Comment by a12baghel2** [comment]
No  No, I will send PR by today.

**Comment by SourabhSaraswat-191939** [comment]
Great 👍🏻

**Comment by a12baghel2** [comment]
@anandhu720  I have completed the task. Kindly review my PR.

**Comment by anandhu720** [comment]
@SourabhSaraswat-191939 please suggest any changes if required
