### ISSUE TITLE
Flutter: Create a Flutter Bulb App

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#5435]
### Description

# A simple Flutter Bulb App

## Description
A simple app with bulb images (one on, and one off ) and a switch button, to make the bulb on or off.

<img src="https://user-images.githubusercontent.com/55342789/136703071-f04909c9-8d76-47b3-bf27-a5f2f0d57719.png" height="500px" />

Features Required:

- [x] Add Assets
- [x] Create Static Main Page ( No Logic, only UI)
- [ ] Add Logic and complete working of the app
- [ ] Proper README file for explaining the project
- [ ] A Video explaining the project

Additional Features:

- [ ] New Designs and Additional Features 

### Domain

Android Dev (Flutter)

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RK1905101** [comment]
Can I contribute in this for documentation part?

**Comment by ViAsmit** [comment]
@RK1905101 we got our whole app... now you can work for the documentation part, according to the code, inside the project DiceApp.
I am creating an issue, for documentation, assign it to yourself.
