### ISSUE TITLE
JAVA :  Polymorphism in Java

### ISSUE THREAD

**Issue by iamtanya-22** [girlscript/winter-of-contributing#5450]
### Description

Description

### Domain

Java_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nandini7637** [comment]
@iamtanya-22 you cannot create issues yourself, your PR won't be considered!
