### ISSUE TITLE
Python: Loops- for loop

### ISSUE THREAD

**Issue by adityabisoi** [girlscript/winter-of-contributing#556]
### Description :
What is for loop in python?

### Note : 

- Changes should be made inside the `Python/` directory & `Python` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR.**  
-  In the PR, keep this issue's title as your PR's title.

#### Must Follow : [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing.

**Comment by lohith1392** [comment]
I would like to work on this please documentation

Peddi sai lohith
Python batch 4

**Comment by Mitali-13** [comment]
I would like to work on this . pls assign
open source 
batch 3

**Comment by itsKiranay** [comment]
I would like to work on this issue. Thank you!!

**Comment by nayakaj** [comment]
i would like to work on this issue

**Comment by harmankaler2000** [comment]
Hi I'd like to contribute through documentation on this topic
Harmandeep - python - batch 4

**Comment by SaijyotiTripathy** [comment]
Hi I would like to contribute through documentation
Saijyoti - python batch 5

**Comment by Sreemoyee26** [comment]
Hi, I am from batch 4, I would like to contribute on this topic

**Comment by manthan89-py** [comment]
### Interested in working on this issue via documentation

**Comment by Vibhu562** [comment]
I would like to work on this issue through documentation.
Vibhu - Python Batch 5

**Comment by Dracarys0511** [comment]
I would like to contribute here. I can contribute in any of the three ways audio/video/documentation.

**Comment by priyanshinaredi** [comment]
@adityabisoi 
Sir, I would like to contribute to this issue.
Name: Priyanshi Naredi
Type: Documentation
Batch: 18

**Comment by ekesel** [comment]
I would like to work on this issue via documentation.

**Comment by prettylittleminds** [comment]
@adityabisoi 
Sir, I would like to contribute to this issue.
Name: Arushi Rautela
Type: Video
Batch: 6

**Comment by adityabisoi** [comment]
> Hi I'd like to contribute through documentation on this topic
> Harmandeep - python - batch 4

Can you go ahead with Video?

**Comment by harmankaler2000** [comment]
@adityabisoi Absolutely, I can contribute through video as well.

**Comment by adityabisoi** [comment]
@ankurg132 Is the mentor of this issue. Please reach out to him in case of queries.
