### ISSUE TITLE
Open Source : 6.43 Explain everything related to `redis`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#5616]
<hr>

## Description 📜

Open Source : 6.43 Explain everything related to `redis`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.43_redis.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by abhinavdixit2306** [comment]
@Aryamanz29 I want to work on this issue

**Comment by 4neesc0des** [comment]
almost completed, I will make a PR by tomorrow.
