### ISSUE TITLE
Open Source : 6.44 Explain everything related to `celery`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#5617]
<hr>

## Description 📜

Open Source : 6.44 Explain everything related to `celery`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.44_celery.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@Hritik157  Any updates?

**Comment by Hritik157** [comment]
Today I will make the PR sir
