### ISSUE TITLE
Open Source : 6.49 Explain everything related to `RxJS`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#5625]
<hr>

## Description 📜

Open Source : 6.49 Explain everything related to `RxJS`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.49_RxJS.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Muskan-sam** [comment]
@Aryamanz29  I have completed my work but I need help in converting the google colab file to .md file and make the pull request. Can you please help me?
