### ISSUE TITLE
What is DynamoDb?

### ISSUE THREAD

**Issue by aaryan078** [girlscript/winter-of-contributing#5636]
### Description

Explain about DynamoDb

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ELLIPSIS009** [comment]
@Aryamanz29 @aaryan078 can i work on this ?
