### ISSUE TITLE
Maximum Histogram

### ISSUE THREAD

**Issue by Danish-Belal** [girlscript/winter-of-contributing#5649]
### Description

You are given an array, element of the array represent a bar of histogram,  return value should me the maximum area coverd in histogram.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by thatSophisticatedMess18** [comment]
Diksha Gupta
Batch-2 
I would like to work on this issue
