### ISSUE TITLE
Data Science with Python : Types of Chatbots

### ISSUE THREAD

**Issue by ShraddhaP123** [girlscript/winter-of-contributing#5657]
### Description

Description
It is a word document that consists of detailed information about chatbots and their types.
Name - Shraddha Pattanshetti
Batch - 17
Batch name - Data Science with Python
Sr no - 649

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment]
Don't create issues by own and without the approval. @ShraddhaP123

**Comment by ShraddhaP123** [comment]
> Don't create issues by own and without the approval. @ShraddhaP123

@prathimacode-hub, okay ma'am

**Comment by RicaGhosh** [comment]
I would like to contribute an AUDIO on this issue. Please assign it to me.
Name - Rica Ghosh
Serial no - 229
Batch - 7
Issue no - #5657
Type - AUDIO
Approach - Chatbots Intro, Types & Applications

**Comment by prathimacode-hub** [comment]
Issue assigned to @RicaGhosh for audio contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do video on this issue.
My approach: a detailed explanation

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do Documentation  on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for video contribution
