### ISSUE TITLE
Data Science with Python : Machine Learning and Types

### ISSUE THREAD

**Issue by Kareem-negm** [girlscript/winter-of-contributing#5660]
### Description

Welcome to 'DSWP' Team, good to see you here

you will give an overview of Machine learning and its types and applications

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : @Kareem-negm / @DhruvBajaj01

Start from: you can use this [notebook ](https://www.kaggle.com/kareem3egm/learn-machine-learning-faster-1)to give you a sample overview 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Hritik157** [comment]
Name: Hritik Sharma
Serial no.: 276
Discord: Hritik | Contributor
Type: Documentation
Approach: Explaining about Machine Learning , its implementation, its examples ,and providing code of some/all of the examples.

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
