### ISSUE TITLE
Simpson's Rule in DSA

### ISSUE THREAD

**Issue by VandanaKumari18** [girlscript/winter-of-contributing#5670]
### Description

Everything about Simpson's rule and it's implementation 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by VandanaKumari18** [comment]
Vandana kumari 
Dsa batch - 8 
Pls assign this to me @nimisha-yadav 
Thanks.

**Comment by nimisha-yadav** [comment]
> Vandana kumari Dsa batch - 8 Pls assign this to me @nimisha-yadav Thanks.

Hey it's already assigned to you, all the best.
