### ISSUE TITLE
Type conversion in C++

### ISSUE THREAD

**Issue by shreyarai05** [girlscript/winter-of-contributing#5672]
### Description

Giving explanation of topic using examples and code for better understanding.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreyarai05** [comment]
I have only 3 open issue including this one. can i work?

**Comment by ishangupta6412** [comment]
@Harsh-Chaudhary7 can u pls add hactober label on this one
