### ISSUE TITLE
Loop in a Linked List

### ISSUE THREAD

**Issue by onlykingKD** [girlscript/winter-of-contributing#5674]
### Description

Documentation about detecting loop in a linked list

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aishwarya713** [comment]
/assign
Aishwarya Rai
Batch 2
