### ISSUE TITLE
Open Source : 6.51 Explain everything related to ```Node.js```

### ISSUE THREAD

**Issue by mayankkuthar** [girlscript/winter-of-contributing#5677]
### Description

Description 📜
Open Source: 6.51 Explain everything related to ```Node.js```

NOTE 👇
Please put your doc ```6.Popular_Projects``` with the name ```6.51_Node.js.md```

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@mayankkuthar Issue description updated, Have a look before raising any PR
Thanks
