### ISSUE TITLE
Frontend_with_Framework: React 4.1 Conditional rendering

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#5684]
### Description

Contributors are required to create documentation and explain about the Conditional Rendering which should cover the questions like : 

- What is Conditional Rendering in React ?
- Benefits of Conditional Rendering
- Where we use conditional Rendering ?
- Give some example of the Conditional Rendering 
- also give some theory explanation with code.
- Ways to implement Conditional rendering in React

Note :
- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the Week 4 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreya024** [comment]
Okay.Can I add a subtopic of 'Ways to implement Conditional Rendering in React'?
