### ISSUE TITLE
Flutter:  Flutter Dice App - Video

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#5691]
### Description

Create a video, explaining the working of the project - Dice App( present inside our Flutter Folder)
Reference: #5417 

### Domain

Android Dev (Flutter)

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Rosy-Chadha** [comment]
@ViAsmit I have created a video and let me know the required changes. I just got unassigned from this.
