### ISSUE TITLE
Bootstrap Grids

### ISSUE THREAD

**Issue by khush2706** [girlscript/winter-of-contributing#5725]
### Description

What are grids? What is their purpose? How to use them? How to style grids using CSS?

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AkMo3** [comment]
> 
> 
> @AkMo3 can you assign me audio part of this issue?

No, it is not part of the Java domain.
