### ISSUE TITLE
[Frontend with HTML,CSS,JS]: Class and Id

### ISSUE THREAD

**Issue by samipak458** [girlscript/winter-of-contributing#5830]
### Description

1) What is class and how it works?
2) What is id and how it works?

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by code-reaper08** [comment]
This topic is already discussed. If you are contributing in form of audio or video, let me know. Else, I'll close this issue.
