### ISSUE TITLE
Python: List Method

### ISSUE THREAD

**Issue by Vibhu562** [girlscript/winter-of-contributing#5832]
### Description

What are methods in List.
Explain all method by giving suitable example.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Vibhu562** [comment]
@adityabisoi  Please assign me my issue

**Comment by adityabisoi** [comment]
@Vibhu562 Why not self-assign as soon as you create one?

**Comment by Vibhu562** [comment]
I forgot

**Comment by Vibhu562** [comment]
thanks
