### ISSUE TITLE
Repeating and the missing numbers

### ISSUE THREAD

**Issue by vineetsingh0809** [girlscript/winter-of-contributing#5838]
### Description

This code will be solving an array problem where an array is given and we have to find the missing and repeating number.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR got merged !!
