### ISSUE TITLE
Documentation on multilevel inheritance

### ISSUE THREAD

**Issue by prak895** [girlscript/winter-of-contributing#5857]
### Description

Add some info about multilevel inheritance

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prak895** [comment]
@ishita3513 I already make this documentation and in 1-2 days I do pull request for it.

**Comment by ishita3513** [comment]
@prak895  How can I contribute then? 
Should I have to do /assign others repo or have to create own? 
How do reviewers check my work?

**Comment by prak895** [comment]
@ishita3513 Go and see roadmap of particular domain after that choose topic of your choice and see that if anyone not working on that issue then self assign to U that's all . If any doubts then ping me in discord
