### ISSUE TITLE
ML 1.1 : Variables, Range, Population Distribution, Sample Distribution (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#586]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Variables, Range, Population Distribution, Sample Distribution in ML**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Using Google Colab/Jupyter Notebook) [Upload the documented .ipynb file while making the PR]

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sumit3301** [comment]
Hi sir
I would like to contribute to this
Full name:Sumit Gaur
Batch Number: 3
github profile: https://github.com/Sumit3301
Type: Documentation

**Comment by abhisheks008** [comment]
Issue assigned @Sumit3301 
Happy Contributing!

**Comment by Anindyadeep** [comment]
Name: Anindyadeep Sannigrahi
Batch: 1
Github Profile : https://github.com/Anindyadeep
Contribution type : Documentation

**Comment by Praannjaal** [comment]
Name :Pranjal Mittal
Batch: 6
Github Profile: [https://github.com/Praannjaal](url)
Contribution Type: Documentation

**Comment by abhisheks008** [comment]
@Sumit3301 Please create the PR ASAP!

**Comment by Sumit3301** [comment]
okay sir
