### ISSUE TITLE
ML 1.4 : Variance, Standard Deviation, Expectation (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#589]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Variance, Standard Deviation, Expectation in ML**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Using Google Colab/Jupyter Notebook) [Upload the documented .ipynb file while making the PR]

All the best. Enjoy your open source journey ahead. 😎

**Comment by priyanshinaredi** [comment]
@abhisheks008 
Sir, I would like to contribute to this issue.
Name: Priyanshi Naredi
Type: Documentation
Batch: 4
Github : https://github.com/priyanshinaredi

**Comment by abhisheks008** [comment]
Issue assigned to you @priyanshinaredi 
Happy contributing!

**Comment by Sakshi1700** [comment]
@abhisheks008 
Sir, I would like to contribute to this issue.
Name: Sakshi Verma
Type: Documentation
Batch: 4 
Serial Number: 628
Github: https://github.com/Sakshi1700

**Comment by abhisheks008** [comment]
What is the update @priyanshinaredi? It's been 7 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by priyanshinaredi** [comment]
Ya please give me today I ll be done with it

**Comment by abhisheks008** [comment]
Complete it by this evening @priyanshinaredi
