### ISSUE TITLE
DSA 2.1 Strings - Readme

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#5898]
## Description
Contribute to the readme file of 2.1 Strings
**Important: Do not use assign command for this issue.**

## Task
- [ ] Documentation

## Note

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by trip0le** [comment]
Hello @nimisha-yadav Ma'am! This is Titas Nath from DSA batch 6. Could you please assign me this issue?

**Comment by priyanshu688** [comment]
@nimisha-yadav Please assign this issue to me ..
Name - Priyanshu Vaishnavi
 Batch - DSA Batch -3

**Comment by jaigora24** [comment]
@nimisha-yadav mam please assign this to me
Name :- Jai Gora
Batch :- 7

**Comment by nimisha-yadav** [comment]
@trip0le final call. Kindly submit PR with 2 days else issue will be assigned to other contributors.

**Comment by trip0le** [comment]
> @trip0le final call. Kindly submit PR within 2 days else the issue will be assigned to other contributors.

yes ma'am you can assign it to someone else. sorry for the inconvenience.

**Comment by Aniketsinghcoder** [comment]
Hey @nimisha-yadav,
I would like to work on the documentation task of this issue.
Aniket Singh
DSA Batch-3

**Comment by Aniketsinghcoder** [comment]
Hey, @nimisha-yadav Can you please, unassign this issue?  My College Exams have started.

**Comment by nimisha-yadav** [comment]
@jaigora24 @taranjotsingh23 @priyanshu688 Is anyone of you interested in taking up this issue now?

**Comment by priyanshu688** [comment]
@nimisha-yadav yes I m interested

**Comment by priyanshu688** [comment]
@nimisha-yadav Can you please brief me what change I exactly need to do in README.md file of  DSA 2.1 Strings???

**Comment by nimisha-yadav** [comment]
@priyanshu688 take reference from 2.2 Searching Sorting folder readme. We are mentioning the major topics of the specific folder in the readme and describing it in 2-3 lines. So you'd need to mention the content of 2.1 String folder. These are the [topics](https://docs.google.com/document/d/1N4Htf4LI6YJfHZnHSD8CQIj1fhjNqZu0sbLjQJG6A30/edit?usp=drivesdk).

**Comment by priyanshu688** [comment]
@nimisha-yadav In 2.2 Searching sorting folder readme ...there is no such content found there.

**Comment by nimisha-yadav** [comment]
I meant how 2.2 Searching and sorting readme has summarised the content of 2.2 Searching and sorting folder, similarly you need to summarise the content of 2.1 Strings folder. I have already shared the topics in 2.1 Strings.

**Comment by priyanshu688** [comment]
@nimisha-yadav Got it

**Comment by priyanshu688** [comment]
@nimisha-yadav Please review this PR.. I have all the changes as you have instructed - https://github.com/girlscript/winter-of-contributing/pull/8114
