### ISSUE TITLE
DSA 2.2 Searching and Sorting Algorithms - Readme

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#5899]
## Description
Contribute to the readme file of 2.2 Searching and Sorting Algorithms.
**Important: Do not use assign command for this issue.**

## Task
- [ ] Documentation

## Note

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Varun270** [comment]
@nimisha-yadav I would like to work on this issue, Please assign this to me
Name - Varun Shrivastava
Batch - 02/DSA

**Comment by Varun270** [comment]
@nimisha-yadav Hey, Can you please elaborate on the issue? Like what will be your expectation for the README file so that I could really work through it.

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav Hey, Can you please elaborate on the issue? Like what will be your expectation for the README file so that I could really work through it.

Hey, just a basic readme containing all the contents of the folder. Starting with introduction of searching algorithms, sorting algo, their applications and importance in DSA. Then you can mention in bullets all the files present in the folder and describing them briefly in 2-3 lines.

**Comment by nimisha-yadav** [comment]
@Varun270 Did your issue get resolved? For more convenience, I've deleted the original readme file, now update your fork and add it again.

**Comment by Varun270** [comment]
@nimisha-yadav Hey, I have reached out to the supervisor with this problem and she is trying to help me with this problem. I know this issue has taken a lot of time and I apologize for the inconveniences caused. I have asked about this issue in multiple discord server and still no one knows why its happening. I will try to give you updates regarding this issue till this evening.

**Comment by Varun270** [comment]
Till then you can review my changes here - https://github.com/girlscript/winter-of-contributing/compare/DSA...Varun270:DSA?expand=1

**Comment by nimisha-yadav** [comment]
Hey no worries, the readme is nice. LGTM.
I went through the link and this issue is due to the merge conflicts like I said above. You're not editing the file but trying to add the same file with same name which is creating conflicts. 
Now just follow these steps as it is: Save your doc somewhere, delete your fork and your cloned folder on the local computer. Fork and clone again. Add the files again in their respective folder, send one PR with 2 changed files. I'll merge both these file via single PR.

Though it's not the preferred way, one should work on different issues in different branches so that separate PRs get linked to separate issues.

**Comment by Varun270** [comment]
> Hey no worries, the readme is nice. LGTM. I went through the link and this issue is due to the merge conflicts like I said above. You're not editing the file but trying to add the same file with same name which is creating conflicts. Now just follow these steps as it is: Save your doc somewhere, delete your fork and your cloned folder on the local computer. Fork and clone again. Add the files again in their respective folder, send one PR with 2 changed files. I'll merge both these file via single PR.
> 
> Though it's not the preferred way, one should work on different issues in different branches so that separate PRs get linked to separate issues. But for your problem, let's keep it like the way mentioned above.

Okk will do it.

**Comment by Varun270** [comment]
# Update
I had contacted Esha Goel for the same problem and she suggested the same thing as you did. So I followed your instructions and did exactly what you asked and this time I did get the option to create a PR. But here's a new problem - 
https://github.com/girlscript/winter-of-contributing/compare/DSA...Varun270:DSA?expand=1

**Comment by Varun270** [comment]
I only pushed a single README.md file but it showed 717 files changed, and around 1000 commits. I pushed the changes from DSA[Forked Repo] ---> DSA[GWOC].

**Comment by Varun270** [comment]
<img width="774" alt="are yaarrrrrrr" src="https://user-images.githubusercontent.com/75975268/140754202-55bd9062-b5c9-4418-ba40-4a6e5236fd8f.png">

**Comment by nimisha-yadav** [comment]
Okay so we can conduct a GMeet to look at the problem. It's not possible to see through the whole process via Git terminal so I'd help you to create the PR and make commits via GitHub UI itself. I'm free after 12 midnight today or post 10 pm tomorrow, let me know what's feasible for you. @Varun270

**Comment by Varun270** [comment]
@nimisha-yadav We can do GMeet tomorrow after 10 pm.
