### ISSUE TITLE
Android-Java: 1.5 Run your app using virtual device and real device.

### ISSUE THREAD

**Issue by sitamadex11** [girlscript/winter-of-contributing#59]
## Description :
* Describe how to set up your real device using USB debugging to run your app in android studio.
* Describe how to create an android-virtual-device using AVD manager to run your app in android studio.

## References :
> https://developer.android.com/training/basics/firstapp/running-app
> https://developer.android.com/studio/run/emulator?authuser=2

* Changes should be made in **Android_Development/Java** directory under **Android_Development_With_Java** branch.
* You have to give your PR to the **Android_Development_With_Java** branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for **GWOC'21** contributors only.

**Comment by prince02765** [comment]
I would like to work on this issue.

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 1.5 for instance `1.5 Running your app using virtual device`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `1.5.1`, `1.5.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.
