### ISSUE TITLE
ML 1.5 : Probability Distributions (Gaussian, Standard, Poisson) (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#590]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Probability Distributions (Gaussian, Standard, Poisson)**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Using Google Colab/Jupyter Notebook) [Upload the documented .ipynb file while making the PR]

All the best. Enjoy your open source journey ahead. 😎

**Comment by guptapriya-83900** [comment]
I would like to the documentation of this issue. In the documentation, I will be providing the description of everything long with examples and their uses. Please assign m this issue. 
ML Batch 1

**Comment by geeythree** [comment]
Issue has been assigned to you @guptapriya-83900 
Happy Contributing! 😄

**Comment by guptapriya-83900** [comment]
I have a doubt, If we have been assigned 1 issue can we take another issue during this time?

**Comment by geeythree** [comment]
@guptapriya-83900 No, you have to complete an issue first. If any changes were suggested, you need to look into that too. Once your PR has been approved, you can move onto next issue. You may get in touch with your assigned mentors for clarifying any doubt you may have regarding the topic you are working on.

**Comment by IshaDagar** [comment]
I would like to work on this.
Approach : Definition , Algo , How does it work, examples and applications
Name: Isha Dagar
ML Batch 6
Github profile link: https://github.com/IshaDagar
Contribution: Documentation

**Comment by guptapriya-83900** [comment]
@geeythree, @abhisheks008
Status: I have completed  Gaussian and Standard . I will be  starting Poisson today.

**Comment by geeythree** [comment]
> 
> 
> I would like to work on this.
> Approach : Definition , Algo , How does it work, examples and applications
> Name: Isha Dagar
> ML Batch 6
> Github profile link: https://github.com/IshaDagar
> Contribution: Documentation

@Isha307 This issue has already been assigned to another contributor. Kindly look for other issues with the labels **ML** and **Up For Grabs**.

**Comment by geeythree** [comment]
@guptapriya-83900 Sure, no problem. Take care

**Comment by guptapriya-83900** [comment]
Thank you!

**Comment by guptapriya-83900** [comment]
@geeythree, @abhisheks008 
I have created PR.
