### ISSUE TITLE
DSA 3.2 Greedy Algorithms - Readme

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#5900]
## Description
Contribute to the readme file of 3.2 Greedy Algorithms
**Important: Do not use assign command for this issue.**

## Task
- [ ] Documentation

## Note

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by nisha855** [comment]
Hey @nimisha-yadav, please review my PR and suggest changes if any...
