### ISSUE TITLE
DSA 3.1 Linked Lists - Readme

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#5901]
## Description
Contribute to the readme file of 3.1 Linked Lists
**Important: Do not use assign command for this issue.**

## Task
- [ ] Documentation

## Note

- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Varun270** [comment]
@nimisha-yadav I would like to work on this issue.
Name - Varun Shrivastava
Batch no. - 02/ DSA

**Comment by preestine** [comment]
Hello, @nimisha-yadav I would like to work on this issue.
Name: Preeti Chaudhari
Batch: 06/DSA
Sr. No. : 1165
Approach: Creating a detailed readme file for linked lists, which consists of a basic Introduction of Linked Lists and review of pointers, structure of nodes, tutorial on how to create a linked lists with n nodes and other tutorials including insertion and deletion of nodes along with proper algorithm explanation.(This is just one of the approaches which I might follow, actual file may differ a bit according to guidelines given by mentor/supervisor.)
