### ISSUE TITLE
ML 1.7 : Parzen Windows (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#592]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Parzen Windows**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation (Using Google Colab/Jupyter Notebook) [Upload the documented .ipynb file while making the PR]

All the best. Enjoy your open source journey ahead. 😎

**Comment by ELLIPSIS009** [comment]
hey, can i contribute to this ? @abhisheks008

**Comment by ELLIPSIS009** [comment]
Abhinav Mathur 
ML Batch - 1
GitHub link: https://github.com/ELLIPSIS009
Type of contribution : Documentation (ipynb)

**Comment by abhisheks008** [comment]
Issue assigned @ELLIPSIS009 
Happy contributing!

**Comment by uttarabahad** [comment]
Hello, Is this issue open? If yes can I get assigned to it? 
Name- Uttara Bahad
Batch Number- 3
GitHub Link- https://github.com/uttarabahad
Type of contribution- Documentation

**Comment by ELLIPSIS009** [comment]
i am working on this issue i will submit my pr by tomorrow

**Comment by ELLIPSIS009** [comment]
i am working on this issue i will submit my pr by tomorrow
