### ISSUE TITLE
Intersection of two array

### ISSUE THREAD

**Issue by Anuj2403** [girlscript/winter-of-contributing#5969]
### Description

we will solve the problem of the intersection of two arrays where the resultant array contains unique elements in it.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@Anuj2403 Please assign this issue to me ?? 
Name - Priyanshu Vaishnavi
Batch - DSA Batch -3
