### ISSUE TITLE
Python : Curated List of all Online Python resources

### ISSUE THREAD

**Issue by Varun270** [girlscript/winter-of-contributing#598]
A list of all the Python resources for a beginner which will include Video links, Blog links.

**Comment by Varun270** [comment]
@adityabisoi Please assign me this issue, I would like to work on it.

**Comment by Pranav120602** [comment]
Hello @adityabisoi, Kindly assign it to me. I am ready to contribute as a doc, video. 
Thanks and Regards, 
Pranav Shankar - Batch 6

**Comment by prettylittleminds** [comment]
@adityabisoi 
Sir, I would like to contribute to this issue.
Name: Arushi Rautela
Type: Video / Documentation
Batch: 6

**Comment by jhanvee-khola** [comment]
@adityabisoi
I would like to contribute to this issue.
Name: Jhanvee Khola
Any type audio/video/documentation
Batch: 4

**Comment by adityabisoi** [comment]
@Randrita Is the mentor for this issue. Please reach out to her in case of queries.

**Comment by Varun270** [comment]
@Randrita Please review my PR.

**Comment by Varun270** [comment]
@Randrita I am closing this issue
