### ISSUE TITLE
ML 1.1 : Variables, Range, Population Distribution, Sample Distribution (A)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#599]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Variables, Range, Population Distribution, Sample Distribution in ML**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by Khushi-Agrawal-1** [comment]
I would like to contribute to this
Full name: Khushi Agrawal
Batch Number: 6
GitHub profile: https://github.com/Khushi-Agrawal-1
Type: Audio

**Comment by abhisheks008** [comment]
Issue assigned @Khushi-Agrawal-1 
Happy contributing!

**Comment by Khushi-Agrawal-1** [comment]
I'm very sorry but I don't I'll be able to do this issue. I request you to un-assign me.

**Comment by abhisheks008** [comment]
**No problem, hope you'll be back with a bang!**

**Comment by SathiyaEthi** [comment]
Hi abhisheks008 ,
I would like to contribute to this
Full name: Sathiya Govindaraj
Batch Number: 1
GitHub profile: https://github.com/Khushi-Agrawal-1
Type: Audio

**Comment by abhisheks008** [comment]
Great @SathiyaEthi issue assigned. Try to complete this issue within this friday.  Happy contributions!

**Comment by Ruchika-20** [comment]
I would like to contribute to this
Full name: Ruchika singh
Batch Number: 3
Type: Documentation

**Comment by abhisheks008** [comment]
What is the update @SathiyaEthi ? It's been 4 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by SathiyaEthi** [comment]
> What is the update @SathiyaEthi ? It's been 4 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

Hi Abhishek, Today, i will complete this issue and upload the audio . Thanks!
