### ISSUE TITLE
ML 1.1 : Variables, Range, Population Distribution, Sample Distribution (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#600]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Variables, Range, Population Distribution, Sample Distribution in ML**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M . I would like to do documentation on this issue.

**Comment by abhisheks008** [comment]
Issue assigned @deepthi1107 
Happy contributing!

**Comment by deepthi1107** [comment]
thanks!
