### ISSUE TITLE
ML 1.2 : PDFs and CDFs (A)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#601]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **PDFs and CDFs**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by Nafizza** [comment]
I would like to work on this issue.
Name: Nazhath Nafizza N
Batch : 1
GitHub profile: https://github.com/Nafizza
Type of contribution: Documentation

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by Isha307** [comment]
@mohitmishra786 At one time, you can work on only one issue.

**Comment by TishaJhabak1014** [comment]
Name: Tisha Jhabak
ML-batch-6
Profile link -https://github.com/TishaJhabak1014
Assign me for this. Via Audio. Thank you.

**Comment by geeythree** [comment]
@TishaJhabak1014 You've been assigned this issue. Kindly note that you need to complete the work and make a PR within 3 days. Happy Contributing! 😄
