### ISSUE TITLE
Android Java: 02.18 Nested ScrollView in Android

### ISSUE THREAD

**Issue by sitamadex11** [girlscript/winter-of-contributing#6010]
<hr>

## Description :scroll:

* Give a step-by-step tutorial of Nested ScrollView in Android (Java).
*  Required Documentation or Video or Audio.

<hr>

## Domain of Contribution :bar_chart:

- [x] Android Dev (java)

<hr>

<hr>

## References :
https://www.geeksforgeeks.org/nestedscrollview-in-android-with-example/

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in Android_Development_With_Java/ directory under Android_Development_With_Java branch.
* Inside Android_Development_With_Java directory/ creates a directory and names it according to the topic
* Inside Topic Name directory/ add your task with subtopic number and name and make changes accordingly.
* You have to push your PR to the Android_Development_With_Java branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.
* Will assign you on a first come first serve basis.
* Please try to complete your assigned task within 7 days. If you need some more time then, please inform mentors and supervisors.
* If you have two previously assigned issues on Android-Java pending then please first complete them.
> Supervisor @VikasPandey121

**Comment by Yugal41735** [comment]
@sitamadex11  @VikasPandey121  could u plz review my pr and tell me if any further changes are required

**Comment by Yugal41735** [comment]
@sitamadex11 @VikasPandey121 could u plz review my pr, is it fine?

**Comment by Yugal41735** [comment]
@VikasPandey121  @sitamadex11 could u plz review it
