### ISSUE TITLE
Android Java: 02.20 TimePicker in android

### ISSUE THREAD

**Issue by HeySitam** [girlscript/winter-of-contributing#6012]
<hr>

## Description :scroll:

* Give a step-by-step tutorial of TimePicker in Android (Java).
*  Required Documentation or Video or Audio.

<hr>

## Domain of Contribution :bar_chart:

- [x] Android Dev (java)

<hr>

<hr>

## References :
https://www.tutorialspoint.com/android/android_timepicker_control.htm

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in Android_Development_With_Java/ directory under Android_Development_With_Java branch.
* Inside Android_Development_With_Java directory/ creates a directory and names it according to the topic
* Inside Topic Name directory/ add your task with subtopic number and name and make changes accordingly.
* You have to push your PR to the Android_Development_With_Java branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.
* Will assign you on a first come first serve basis.
* Please try to complete your assigned task within 7 days. If you need some more time then, please inform mentors and supervisors.
* If you have two previously assigned issues on Android-Java pending then please first complete them.
> Supervisor @VikasPandey121

**Comment by Kajal13081** [comment]
I would like to work on this @sitamadex11 @VikasPandey121 Sir.
