### ISSUE TITLE
ML 1.2 : PDFs and CDFs (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#602]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **PDFs and CDFs**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by abhisheks008** [comment]
@mohitmishra786 It is clearly written in the guideline of this issue that it is a video contribution. You can contribute in this issue by making a video over the topic. The documentation of this was already assigned.

**Comment by mohitmishra786** [comment]
@abhisheks008  can you tell me what should be the length of video and audio

**Comment by riyasai22** [comment]
I would like to take up this issue in video format.
Name: Riya Srisailam Sailesh
ML Batch-11
Github Profile: https://github.com/riyasai22

**Comment by abhisheks008** [comment]
> @abhisheks008 can you tell me what should be the length of video and audio

@mohitmishra786 length of the content completely depends on you. Whenever you search for some content in YouTube you get different types of length of the videos but they demonstrate the same things. So it's up to you how precisely and easily you can create a video or an audio file which will cover the topic.

**Comment by abhisheks008** [comment]
What is the update @riyasai22 ? It's been 7 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by riyasai22** [comment]
@abhisheks008 
I have made a video contribution.
Please do look into it.
