### ISSUE TITLE
ML 1.3 : Central Limit Theorem (A)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#604]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Central Limit Theorem**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by Isha307** [comment]
Issue has been assigned to you @mohitmishra786 
Happy Contributing!!

**Comment by abhisheks008** [comment]
@mohitmishra786 you are taking an issue of Audio content and you want to contribute through documentation. Atleast read the guidelines first and also the labels assigned to it. This is an Audio contribution not a documentation.

**Comment by Khushi-Shah-1** [comment]
Khushi Shah
ML-Batch-2
Profile_Link:- https://github.com/Khushi-Shah-1
I want to contribute through Audio content

**Comment by abhisheks008** [comment]
Issue assigned @Khushi-Shah-1 
happy contributing!
