### ISSUE TITLE
Introduction to Figma Part 11 - Left Panel tools

### ISSUE THREAD

**Issue by ShudhanshuSingh** [girlscript/winter-of-contributing#6045]
### Description

Description

You need to show either what are the tools available on the left side panel of figma and what are the different things which we can do with it. 

### Domain

UI/UX

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreya024** [comment]
I would like to work on this issue.Kindly assign this to me .

**Comment by shreya024** [comment]
@garvitraj Thank you for merging.Kindly close this issue.
