### ISSUE TITLE
ML 1.3 : Central Limit Theorem (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#605]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Central Limit Theorem**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video
All the best. Enjoy your open source journey ahead. 😎

**Comment by UditJain77** [comment]
Hi sir
I would like to contribute to this
Full name: Udit Kumar Jain
Batch Number: 1
github profile: https://github.com/UditJain77
Type: Video

**Comment by abhisheks008** [comment]
Issue assigned @UditJain77 
Happy contributing!

**Comment by UditJain77** [comment]
Today's Update
Creating a PPT for CRT!

**Comment by UditJain77** [comment]
Today's Update
Creating a PPT for this CLT issue.

**Comment by abhisheks008** [comment]
What is the update @UditJain77 ? It's been 7 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do video on this issue.

**Comment by UditJain77** [comment]
@abhisheks008 I am extremely sorry for not updating, i had some issues. By tomorrow i will try to commit it fully.

**Comment by Isha307** [comment]
@UditJain77 update?

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do a video on this issue.
@abhisheks008 @Isha307 as the deadline has arrived can u please look into the deadline and process after that?

**Comment by Isha307** [comment]
@UditJain77 Please give us update.

**Comment by UditJain77** [comment]
@Isha307 I am extremely sorry for the delay. I wont be able to work on this issue for the being due to some problems. I request you to grant this issue to @deepthi1107

**Comment by abhisheks008** [comment]
No problem @UditJain77. Well wishes.

**Comment by deepthi1107** [comment]
please do assign me @Isha307 @abhisheks008
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do a video on this issue

**Comment by Isha307** [comment]
No problem @UditJain77, @deepthi1107 you can work on this.
