### ISSUE TITLE
ML 1.4 : Variance, Standard Deviation, Expectation (A)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#606]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Variance, Standard Deviation, Expectation in ML**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by Khushi-Agrawal-1** [comment]
I would like to contribute to this
Full name: Khushi Agrawal
Batch Number: 6
GitHub profile: https://github.com/Khushi-Agrawal-1
Type: Audio

**Comment by abhisheks008** [comment]
@mohitmishra786 would you want to contribute in this issue with audio contribution?

**Comment by abhisheks008** [comment]
> I would like to contribute to this
> Full name: Khushi Agrawal
> Batch Number: 6
> GitHub profile: https://github.com/Khushi-Agrawal-1
> Type: Audio

@Khushi-Agrawal-1  1 issue at a time. Once you successfully merge the PR of your previous issue then only you can get opportunity to contribute in others.

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Machine Learning
Batch-6
Issue Number-606
Contribution Approaches-statistical concepts, formulas, explanations, functions to do execute the concepts

**Comment by jainbhupesh533** [comment]
I want to contribute to this issue :
Name-Bhupesh Parakh
Domain-Machine Learning
Batch-3
Issue Number-606
github_id:  https://github.com/jainbhupesh533
Type- Audio

**Comment by mohitmishra786** [comment]
> @mohitmishra786 would you want to contribute in this issue with audio contribution?

Yes I will

**Comment by geeythree** [comment]
@mohitmishra786 you have been assigned one issue already. Please complete it before proceeding onto the next.

**Comment by mohitmishra786** [comment]
> @mohitmishra786 you have been assigned one issue already. Please complete it before proceeding onto the next.

No I am not been assigned with any ML issue

**Comment by mohitmishra786** [comment]
Sorry I didn't check

**Comment by geeythree** [comment]
> 
> 
> I want to contribute to this issue :
> Name-Bhaswati Roy
> Domain-Machine Learning
> Batch-6
> Issue Number-606
> Contribution Approaches-statistical concepts, formulas, explanations, functions to do execute the concepts

@BhaswatiRoy Kindly note that you need to mention the contribution type(documentation/video/audio). Also, this issue is for **Audio** content only.

**Comment by geeythree** [comment]
@jainbhupesh533 you've been assigned this issue! Note that you need to complete it and make a PR within 3 days. Happy contributing! 😄

**Comment by tavneetgill** [comment]
I want to contribute this issue.
Full name-Tavneet Kaur Gill
Batch Number-2
GitHub Profile Link-https://github.com/tavneetgill
Contribution Type-Audio
Issue number-606
Contribution approaches-detailed explanation with examples and sample codes, formulas, statistical data required etc.

**Comment by abhisheks008** [comment]
@tavneetgill this issue is already assigned :(

**Comment by tavneetgill** [comment]
@abhisheks008 is there any available issue at this time on which I can work on of ML?

**Comment by abhisheks008** [comment]
Issues still not being assigned :

1. https://github.com/girlscript/winter-of-contributing/issues/612
2. https://github.com/girlscript/winter-of-contributing/issues/613
3. https://github.com/girlscript/winter-of-contributing/issues/1115
4. https://github.com/girlscript/winter-of-contributing/issues/1555
5. https://github.com/girlscript/winter-of-contributing/issues/1556
6. https://github.com/girlscript/winter-of-contributing/issues/1558

**Comment by jainbhupesh533** [comment]
> @abhisheks008 is there any available issue at this time on which I can work on of ML?

@tavneetgill  Hey i am working and will merge this issue today
