### ISSUE TITLE
ML 1.4 : Variance, Standard Deviation, Expectation (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#607]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Variance, Standard Deviation, Expectation in ML**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by ashish-reddy-20-08** [comment]
Hey, I am M. Ashish Reddy I would like to work on this. 
my serial number: 260 
Batch: 2

**Comment by geeythree** [comment]
@ashish-reddy-20-08 Please mention the contribution type too.

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by Vibhu562** [comment]
My name is Vibhu . I would like to work on this issue.
My batch No:- 4
Github Profile - https://github.com/Vibhu562
Contribution type: Documentation

**Comment by Vibhu562** [comment]
My name is Vibhu . I would like to work on this issue.
My batch No:- 4
Github Profile - https://github.com/Vibhu562
Contribution type: Documentation

**Comment by purvanshgarg** [comment]
Hello, I am Purvansh Garg I would like to work on this issue
Batch : 2
Profile: https://github.com/purvanshgarg
I would like to make a video contribution

**Comment by Mohdtalibakhtar** [comment]
Hello , I would like to work on this 
Github : https://github.com/Mohdtalibakhtar
I would like to contribute through documentation

**Comment by parvatijay2901** [comment]
Name: Parvati Jayakumar
Batch: 3
GitHub profile: https://github.com/parvatijay2901
Contribution type: Video.

**Comment by geeythree** [comment]
@purvanshgarg You've been assigned this issue. Kindly note that you need to complete the work and make a PR within 3 days. Happy Contributing! 😄

**Comment by purvanshgarg** [comment]
I want to change my contribution to audio can i do that?
sorry for the discrepancy
