### ISSUE TITLE
ML 1.5 : Probability Distributions (Gaussian, Standard, Poisson) (A)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#608]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Probability Distributions (Gaussian, Standard, Poisson)**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by abhisheks008** [comment]
This is an Audio contribution, you can contribute by the audio contribution with this issue. @mohitmishra786

**Comment by mohitmishra786** [comment]
Ok i will can you please tell me how can I do contribution in audio and video way, am I going to upload my audio of explaining the topic here or what

**Comment by abhisheks008** [comment]
Yeah you will be explaining the topic via an audio file.

**Comment by mohitmishra786** [comment]
Ok i will do that please assign me this

**Comment by theshredbox** [comment]
Hey. I'd like to take take this issue for contribution.
Name- Aryan Ahuja
Serial no. 691
Type- Video/Audio and Documentation
Approach- Use python tools to visualize and analyze randomly generated data.
1. Statistics Basics
2. Working with probability distributions in SciPy

**Comment by Aaksha-sharma** [comment]
Aaksha Sharma
ML-Batch-3
Profile_Link:- https://github.com/Aaksha-sharma
I want to contribute through documentation

**Comment by geeythree** [comment]
@theshredbox This issue is for **audio** contribution only.

**Comment by Pratyaksha-047** [comment]
Hey I'd like to take this issue for contribution.
Name- Pratyaksha Gupta
Type- Audio
Github-https://github.com/Pratyaksha-047

**Comment by abhisheks008** [comment]
@Pratyaksha-047 issue assigned.

**Comment by abhisheks008** [comment]
What is the update @Pratyaksha-047 ? It's been 5 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by Pratyaksha-047** [comment]
I am so sorry , I fell sick after getting my vaccine and due to which I am
late in contributing, but I have made a pull request now.
My apologies, and thank you for understanding.
