### ISSUE TITLE
Android Java: 02.36 Rating Bar in Android

### ISSUE THREAD

**Issue by PranavPrakasan07** [girlscript/winter-of-contributing#6086]
### Description

The description on how to use Rating Bar view in android, java.

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sitamadex11** [comment]
Thanks buddy🤩
