### ISSUE TITLE
ML 1.5 : Probability Distributions (Gaussian, Standard, Poisson) (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#609]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Probability Distributions (Gaussian, Standard, Poisson)**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M . I would like to work on this issue.
batch : 2
github link: https://github.com/deepthi1107
type:video

**Comment by abhisheks008** [comment]
@deepthi1107 1 issue at a time. Complete your previous issue first and make the PR, then only you can work on the other issues.

**Comment by Vibhu562** [comment]
My name is Vibhu . I would like to work on this issue.
My batch No:- 4
Github Profile - https://github.com/Vibhu562
Contribution type: Documentation

**Comment by abhisheks008** [comment]
@Vibhu562 This is a video contribution.

**Comment by parvatijay2901** [comment]
Name: Parvati Jayakumar
Batch: 3
GitHub profile: https://github.com/parvatijay2901
Contribution type: Video

**Comment by Anindyadeep** [comment]
Name: Anindyadeep Sannigrahi
Batch: 1
Github Profile : https://github.com/Anindyadeep
Contribution type : Documentation

**Comment by abhisheks008** [comment]
@Anindyadeep Come on man, it's clearly written that its a Video content, also it is assigned! Don't spam like this :(

**Comment by Anindyadeep** [comment]
> @Anindyadeep Come on man, it's clearly written that its a Video content, also it is assigned! Don't spam like this :(

Yeahhh i was actually going through all the issues and wriiten the requests.... so it was a silly mistake which i came to know late... sorry

**Comment by abhisheks008** [comment]
What is the update @parvatijay2901 ? It's been 7 days and you were although you've assigned an issue. Create the PR ASAP, otherwise we can't make further issues!

**Comment by parvatijay2901** [comment]
I'll upload it soon.

**Comment by Isha307** [comment]
@parvatijay2901 It's been 13 days, Any Update?

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-2. I would like to do a video on this issue. Its been 13 days since, the issue has opened, I request @abhisheks008 @Isha307 to look into it. If there is a chance of assigning, please assign me to work on this issue.

**Comment by parvatijay2901** [comment]
@Isha307 I'm sorry, I was in hospital since some days and couldn't let you know too earlier. I will make the PR by today night. Thanks

**Comment by parvatijay2901** [comment]
@Isha307 https://github.com/girlscript/winter-of-contributing/pull/4157
