### ISSUE TITLE
1.6 Setting up git and connecting Github account to Android Studio.

### ISSUE THREAD

**Issue by NamanManjkhola** [girlscript/winter-of-contributing#61]
### Description

1. how set up git in android studio.
2. how to connect your GitHub account to android studio.

**Comment by NamanManjkhola** [comment]
[@Rohit-2602](https://github.com/Rohit-2602) Can I work on this issue I created?

**Comment by Rohit-2602** [comment]
yes sure 😀

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 1.5 for instance `1.5 Setting up git and connecting Github account to Android Studio`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `1.5.1`, `1.5.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by SouravKr2001** [comment]
I am interested in the issue (doc...)
