### ISSUE TITLE
ML 1.7 : Parzen Windows (A)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#612]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Parzen Windows**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

All the best. Enjoy your open source journey ahead. 😎

**Comment by AdityaStark7** [comment]
Hey,
I want to work on this issue
Aditya Kumar
Batch: 03
Serial No. 374

**Comment by AdityaStark7** [comment]
Hey,
I want to work on this issue
Aditya Kumar
Batch: 03
Serial No. 374
Type: Documentation

**Comment by geeythree** [comment]
@AdityaStark7 Kindly note that this issue is for **Audio** content only.

**Comment by tavneetgill** [comment]
I want to contribute this issue.
Full name-Tavneet Kaur Gill
Batch Number-2
GitHub Profile Link-https://github.com/tavneetgill
Contribution Type-Audio
Issue number-612
Contribution approaches-basic definition, detailed explanation with examples and sample codes, formulas, where it is used

**Comment by abhisheks008** [comment]
Issue assigned @tavneetgill. Finish this issue by this Friday.

**Comment by tavneetgill** [comment]
@abhisheks008  By Friday means tomorrow or next?

**Comment by abhisheks008** [comment]
Try to make it by today midnight, we don't wanna overlap week 1 contents with week 2 contents. @tavneetgill

**Comment by abhisheks008** [comment]
@tavneetgill Please make the PR ASAP!

**Comment by tavneetgill** [comment]
@abhisheks008 Created the PR please review the content and let me know if it needs any changes or alterations!!
