### ISSUE TITLE
DSA 3.1.3 Length of Linked List

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#6124]
## Description
Give an introduction and explain the working of both iterative and recursive algorithms to find length of a linked list.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by divya1467** [comment]
Can you please assign me the documentation part
Divya(Batch 5)

**Comment by SUKHJIT-CYBER** [comment]
SUKHJIT SINGH
Batch 8
