### ISSUE TITLE
DSA 3.1.4 nth node from end of a Linked List

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#6125]
## Description
Give an introduction and explain the working of an algorithm for finding the nth node from end of a linked list.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by jaigora24** [comment]
Assign this issue to me (Documentation)
Jai Gora
Batch 7

**Comment by aisharay** [comment]
/assign 
Documentation 
Aisha ray 
Batch 7
