### ISSUE TITLE
DSA 3.1.5 Pairwise swap Linked List

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#6126]
## Description
Give an introduction and explain the working of an algorithm for pairwise swapping of elements of a linked list.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
I would like to work on this issue. (Documentation)
DSA batch - 2
Dhruti Gandhi

**Comment by aisharay** [comment]
/assign 
documentation
Aisha ray 
Batch 8
