### ISSUE TITLE
DSA 3.2.18 Max Flow Algorithms

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#6128]
## Description
Give an introduction and explain the working of an algorithm for finding the maximum flow in a flow network. Also discuss the Integral Flow Theorem.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
I would like to work on this issue. (Documentation)
DSA batch - 2
Dhruti Gandhi

**Comment by SUKHJIT-CYBER** [comment]
Doing this as a Documentation Part
SUKHJIT-SINGH
/assign

**Comment by nikki-priyaHIT** [comment]
Nikki Priya
DSA Batch-2
Documentation
I want to work on this issue may i be assign for this issue?
