### ISSUE TITLE
ML 1.7 : Parzen Windows (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#613]
Welcome to 'ML' Team, good to see you here

This issue will helps readers in acquiring all the knowledge that one needs to know about **Parzen Windows**.

To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

Domain : Machine Learning

Points to Note :

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Statistics_for_Machine_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

**To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

All the best. Enjoy your open source journey ahead. 😎

**Comment by mohitmishra786** [comment]
Mohit Mishra
ML-Batch-1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by abhisheks008** [comment]
@mohitmishra786 This is an video contribution, and remember you can take up one issue at a time. Please don't ask for different issues at a time, this will bring wrong impression on you by the team and also read the issue checkbox, title and labels first.

**Comment by mohitmishra786** [comment]
ok sure i was not aware of this

**Comment by abhisheks008** [comment]
@mohitmishra786 Wherever you want to contribute make sure you check all the details first and try to check the labels there, this will help you in future contributions too. If you want to make contribution using a Video then you can take up this issue.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do a video on this issue.

**Comment by abhisheks008** [comment]
Issue assigned @deepthi1107
