### ISSUE TITLE
Frontend With Framework - Virtual DOM and Internals

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#615]
Need to include
1 What is the Virtual DOM
2  Advantages of Virtual DOM
3 Is the Shadow DOM the same as the Virtual DOM
4 What is React fibre

Please try to add pictures related to the topic.

Also make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by GyaniRoman23** [comment]
Hey @anandhu720 I would like to work with this issue.

**Comment by RIYANSHGARG** [comment]
I would Like to work on this issue, Kindly assign it to me.

**Comment by vatsal1704** [comment]
Hii @anandhu720 can I work on this issue?

**Comment by kajaljha09** [comment]
I would like to work on this issue

**Comment by Anisha135** [comment]
I would like to work on this issue

**Comment by Jaya3112** [comment]
I would like to work on this issue. please assign me this issue

**Comment by anandhu720** [comment]
@GyaniRoman23 sure

**Comment by anandhu720** [comment]
guys we follow first come first serve method

**Comment by anandhu720** [comment]
@GyaniRoman23 we have suggested changes in your pr,please make the changes.
