### ISSUE TITLE
FRONTEND WITH FRAMEWORK: VueJS-1.5 => Installing Vue-DevTools

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [girlscript/winter-of-contributing#618]
Contributors are required to include a procedure to Install Vue-DevTools, which should cover questions like:-
What is Vue-DevTools?
Why it is needed?
How to install it?
How to open Vue-DevTools in the browser? (you can make GIF, which shows how to open this)
etc....

**And also mention that we will learn, how to use it further in the upcoming topics.**

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by SourabhSaraswat-191939** [comment]
If you don't know this framework. Don't worry still, you can contribute.
Here I am attaching some references for you.

https://vuejs.org/v2/guide/
https://www.tutorialspoint.com/vuejs/vuejs_overview.htm
https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started

You can also study from any other source to learn.

Note -> These references contents are not to copy/paste. Avoid copy/paste, We will be checking.

**Comment by GyaniRoman23** [comment]
Hey @SourabhSaraswat-191939 I would suggest you to add the required labels to this issue as it would help make a better clarity for individuals looking for a particular issue inside of a particular domain.

**Comment by SourabhSaraswat-191939** [comment]
Hey @GyaniRoman23, 
Actually, mentors do not have the right to add labels, milestones, and merging the PR. This thing will be done by supervisors.
When the supervisor sees issues. They add related labels and milestones.
Hope you understand.

**Comment by GyaniRoman23** [comment]
> Hey @GyaniRoman23,
> Actually, mentors do not have the right to add labels, milestones, and merging the PR. This thing will be done by supervisors.
> When the supervisor sees issues. They add related labels and milestones.
> Hope you understand.

Oh!! I get it. Thank you for the information.

**Comment by Saurabh-crypto16** [comment]
I want to work on it

**Comment by SourabhSaraswat-191939** [comment]
> > Hey @GyaniRoman23,
> > Actually, mentors do not have the right to add labels, milestones, and merging the PR. This thing will be done by supervisors.
> > When the supervisor sees issues. They add related labels and milestones.
> > Hope you understand.
> 
> Oh!! I get it. Thank you for the information.

👍🏻

**Comment by SourabhSaraswat-191939** [comment]
> I want to work on it

@Saurabh-crypto16, Go for it.

**Comment by Saurabh-crypto16** [comment]
> > I want to work on it
> 
> @Saurabh-crypto16, Go for it.
> 
> 

Assign me @SourabhSaraswat-191939

**Comment by anandhu720** [comment]
content added
