### ISSUE TITLE
ML 5.14 : Cross Validation (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#6182]
### 📌  Issues for Week 5
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Cross Validation_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Feature_Engineering_and_Performance_Metrices` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
Type- Documentation
Plz assign to me

**Comment by guptapriya-83900** [comment]
Name: Priya Gupta
Batch: Batch 1
GitHub: https://github.com/guptapriya-83900
Type: Documentation

**Comment by Yugal41735** [comment]
Yugal Agarwak
Batch -1
Github- https://github.com/Yugal41735
Documentation

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
[Profile link](https://github.com/priyall)
Contribution type: Documentation
I would like to contribute to this issue.

**Comment by pranav7kaushik** [comment]
Pranav Kaushik
Batch - 4
Github: https://github.com/pranav7kaushik
Type: Documentation
