### ISSUE TITLE
Two Stack in an Array

### ISSUE THREAD

**Issue by Danish-Belal** [girlscript/winter-of-contributing#6207]
### Description

Implement two Stack in a single Array , and the size of  Stack should not be fixed, which means you can not fix Stack1 size from  0 to arr.length/2 . 

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@Danish-Belal Can I work on this issue??
 Priyanshu Vaishnavi
DSA Batch 3
