### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular -> How to install Angular Material in Angular?

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#622]
- CLI command
- Its use?
- Reference:- https://material.angular.io/guide/getting-started

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week1" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by RIYANSHGARG** [comment]
I would like to solve this. Kindly assign it to me

**Comment by mukeshmjn** [comment]
Sure @RIYANSHGARG go for it!

**Comment by RIYANSHGARG** [comment]
I have generated a pull request, please consider it.
