### ISSUE TITLE
OpenSource : Difference between Linux and Unix

### ISSUE THREAD

**Issue by Harshil-Jani** [girlscript/winter-of-contributing#625]
This is Self Issue.
I want to do documentation on **Difference between Linux and Unix**
Points I plan to cover : 
- History of Unix and Linux
- Growth in OpenSource
- Competition and Comparison between them 

- [x] Documentation
- [ ] Audio
- [ ] Video

**Comment by Aryamanz29** [comment]
We don't need, refrain from creating the same issues 
Thanks
