### ISSUE TITLE
OpenSource : 5.9 Explain everything related to `Kubernetes`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#630]
### Description :

- **Explain everything related to `Kubernetes`**
-  How to configure our projects with it
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by siddhi-244** [comment]
Can I try it?

**Comment by Asmit2952** [comment]
Can I work on this?

**Comment by Harshkumar62367** [comment]
can i work on this @Aryamanz29 ?

**Comment by Aryamanz29** [comment]
@Harshkumar62367  Assigning this to you, Happy Learning 🎉🎉
