### ISSUE TITLE
Frontend With Framework : Introduction to useRef

### ISSUE THREAD

**Issue by anandhu720** [girlscript/winter-of-contributing#6306]
### Description

Description
Contributors are required to create documentation and explain:-

- [ ]  What is useRef
- [ ] Why use useRef
- [ ] Advantages of useRef

Note :
Plagiarism is strictly prohibited.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Files need to be added into the Week5 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreya024** [comment]
@anandhu720 Kindly close this issue.
