### ISSUE TITLE
OpenSource : 5.10 Explain everything related to `Docker`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#632]
### Description :

- **Explain everything related to `Docker`**
-  How to `configure our projects` with it.
-  `Use docker with your project` and document the whole process in steps
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by siddhi-244** [comment]
Can I try it

**Comment by Aryamanz29** [comment]
> Can I try it

@siddhi-244  Assigning this to you, Happy learning 🎉🎉

**Comment by siddhi-244** [comment]
I am srry was busy bciz of my exams will make a pr tomorrow.  Really srry.

**Comment by divyanshuss** [comment]
Can I try to put in something?

**Comment by siddhi-244** [comment]
> Can I try to put in something?

I am doing it

**Comment by divyanshuss** [comment]
Okay sure. Good luck

**Comment by siddhi-244** [comment]
@Aryamanz29 plz see to it. I have completed all my issues.

**Comment by Aryamanz29** [comment]
@siddhi-244  Happy Learning  🎉🎉

**Comment by Aryamanz29** [comment]
@siddhi-244  Any updates on this ?

**Comment by siddhi-244** [comment]
> @siddhi-244 Any updates on this ?

Actually sir I am unable to run docker on my pc. Rest all is done. So should I add only the explanation with examples?

**Comment by Aryamanz29** [comment]
> > @siddhi-244 Any updates on this ?
> 
> Actually sir I am unable to run docker on my pc. Rest all is done. So should I add only the explanation with examples?

Hmm ok, Go ahead with examples and explanations 👍

**Comment by Harshil-Jani** [comment]
@Aryamanz29 I was able to run the docker on my PC while learning and I am ready with the Project and Documentation ! So, Once you pull Explaination  from Siddhi then can I add Project Config and Demo Project to it ?

**Comment by siddhi-244** [comment]
> @Aryamanz29 I was able to run the docker on my PC while learning and I am ready with the Project and Documentation ! So, Once you pull Explaination from Siddhi then can I add Project Config and Demo Project to it ?

Let's do it then. I will add my documentation as soon as my exam finishes . Then uh can add the screenshots

**Comment by Harshil-Jani** [comment]
> > @Aryamanz29 I was able to run the docker on my PC while learning and I am ready with the Project and Documentation ! So, Once you pull Explaination from Siddhi then can I add Project Config and Demo Project to it ?
> 
> Let's do it then. I will add my documentation as soon as my exam finishes . Then uh can add the screenshots

Okay ! Thankss . Shall we do like you make doc in your fork Let me know, I will merge there and combined doc you can later merge to this GWOC repo ?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I was able to run the docker on my PC while learning and I am ready with the Project and Documentation ! So, Once you pull Explaination from @siddhi-244 then can I add Project Config and Demo Project to it ?

Create a new issue for that and tag me. I'll assign you
