### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(5.2) -> Defining a route

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#6321]
### Description

- What is route?
- How to add route to application?
- What is route order?
- Explain with syntax/example
- Reference :- https://angular.io/guide/router

(Week 5 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week5" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RIYANSHGARG** [comment]
I will create a pr for other issue till tomorrow so, If You would like to assign it to me Then please assign it to me.
