### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(5.5) -> Setting up redirects

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#6324]
### Description

- How to set up redirects?
- Why redirect is required?
- Explain with syntax/example
- Reference :- https://angular.io/guide/router

(Week 5 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week5" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RIYANSHGARG** [comment]
https://github.com/girlscript/winter-of-contributing/pull/7951 
@mukeshmjn  I have created a pr Kindly review it.
