### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(5.6) -> Nesting routes

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#6325]
### Description

- What is nesting routing?
- How it can be achieved?
- Why nesting routing is needed?
- Explain with syntax/example
- Reference :- https://angular.io/guide/router

(Week 5 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week5" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by A-GHOSH-dev** [comment]
@koshimagoyal Can I work on this issue?
I am a GWoC'21 Participant. 
While getting selected, I chose ML, OpenSource and Backend with Python as my 3 Domains. I have already contributed to those domains.
But am equally interested to work in Frontend Domain. Can I contribute here?

**Comment by RIYANSHGARG** [comment]
@mukeshmjn I have created the pull request kindly review it .
https://github.com/girlscript/winter-of-contributing/pull/8812
