### ISSUE TITLE
OpenSource : 5.11 Explain everything related to `terraform`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#633]
### Description :

- **Explain everything related to `terraform`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Asmit2952** [comment]
Can I work on this?

**Comment by Aryamanz29** [comment]
@Asmit2952  Assigned, Happy learning 🎉🎉
