### ISSUE TITLE
Merge Sort using C++ Language

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#6335]
### Description

What is Merge Sort? Briefly Explain this and also Its Algorithm. Also Write one program which implement Merge Sort.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
duplicate of #4054 by @rajraii
