### ISSUE TITLE
OpenSource : 5.12 Explain everything related to `Prometheus`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#634]
### Description :

- **Explain everything related to `Prometheus`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Abhay3008** [comment]
I need to work on this!

**Comment by lohith1392** [comment]
I would like to work on this please documentation

Peddi sai lohith

**Comment by Aryamanz29** [comment]
> I need to work on this!

@Abhay3008  Assigning this to you, Happy Learning 🎉🎉

**Comment by mayankkuthar** [comment]
@Aryamanz29  If Anyone is not working on this Issue Kindly Assign this to me, I would love to work o this one. :octocat:

**Comment by Abhay3008** [comment]
I'll be making PR tonight, @mayankkuthar you can improve it afterwards.

**Comment by mayankkuthar** [comment]
@Abhay3008 Ok Great 👍

**Comment by Aryamanz29** [comment]
@Abhay3008  Any updates on this ?
