### ISSUE TITLE
DSA : Greedy Algorithm - Fractional Knapsack

### ISSUE THREAD

**Issue by ShikhaSwati60** [girlscript/winter-of-contributing#6370]
### Description

I will provide detailed documentation on fractional knapsack.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by pushpit-J19** [comment]
@nimisha-yadav @pjdurden can i work on this issue if that is fine ?

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav @pjdurden can i work on this issue if that is fine ?

Since this issue has been stale for more than 12 days, @pushpit-J19 you may work on this.
