### ISSUE TITLE
OpenSource : 5.13 Explain everything related to `Vitess`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#638]
### Description :

- **Explain everything related to `Vitess`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by itsbittoosharma** [comment]
Please assign this to me
I could work on it

**Comment by Aryamanz29** [comment]
@itsbittoosharma Assigned, Happy learning 🎉🎉

**Comment by itsbittoosharma** [comment]
@Aryamanz29 Please close this issue, as my PR is already merged, so that I could take another issue :)
