### ISSUE TITLE
[Create New Issue]: Dijkstra's algorithm

### ISSUE THREAD

**Issue by ShrutiPandey27** [girlscript/winter-of-contributing#6384]
### Description

Description

I will provide detailed documentation on Dijkstra's algorithm in which we majorly make use of greedy approach.with code for it.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by goelesha** [comment]
@ShrutiPandey27 Dijkstra is already created I think
