### ISSUE TITLE
Python Iterators

### ISSUE THREAD

**Issue by TammanaNiharika** [girlscript/winter-of-contributing#6399]
### Description

To describe iterators and related concepts in python.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nayakaj** [comment]
@adityabisoi  plz assign me for documentation

**Comment by TammanaNiharika** [comment]
Successfully merged.
