### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular ->Component Interaction(1.4)

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#641]
- How to do component interaction in Angular?
- How to share data between components?
- Explain Different ways to do it.

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week1" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by CSAURABH** [comment]
@anandhu720 can i work on this issue(Documentation).

**Comment by anandhu720** [comment]
@CSAURABH sure

**Comment by mukeshmjn** [comment]
@CSAURABH any updates on this?

**Comment by CSAURABH** [comment]
@mukeshmjn  I will send you pr today.
