### ISSUE TITLE
Cybersecurity 7.4 Burp-suite

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#6411]
### Description

# Description
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

### Domain

Cyber Security

### Type of Contribution

Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anant1711** [comment]
Guys?
@IshikaMeghaSaha @AtharvaaPatil

**Comment by AtharvaaPatil** [comment]
@Anant1711 working on it can I get a few more days I was busy travelling

**Comment by Anant1711** [comment]
> @Anant1711 working on it can I get a few more days I was busy travelling

Have you done?

**Comment by artishukla1** [comment]
Hi @Anant1711, can i work on this for documentation?

**Comment by AtharvaaPatil** [comment]
> > @Anant1711 working on it can I get a few more days I was busy travelling
> 
> Have you done?

Working almost done

**Comment by Anant1711** [comment]
> > > @Anant1711 working on it can I get a few more days I was busy travelling
> > 
> > 
> > Have you done?
> 
> Working almost done

when you will submit?

**Comment by AtharvaaPatil** [comment]
> > > > @Anant1711 working on it can I get a few more days I was busy travelling
> > > 
> > > 
> > > Have you done?
> > 
> > 
> > Working almost done
> 
> when you will submit?

Till Saturday? sorry I have exams going on

**Comment by Anant1711** [comment]
> > > > > @Anant1711 working on it can I get a few more days I was busy travelling
> > > > 
> > > > 
> > > > Have you done?
> > > 
> > > 
> > > Working almost done
> > 
> > 
> > when you will submit?
> 
> Till Saturday? sorry I have exams going on

ok
