### ISSUE TITLE
MERN_NodeJS:  Installing NPM packages

### ISSUE THREAD

**Issue by joshi-kaushal** [girlscript/winter-of-contributing#6417]
### Description

I want to add a brief explanation about NPM Packages in documentation format.
The related information will be added in MERN/Topic/Backend/Node/ directory.

please guide me about the naming convention.

### Domain

MERN

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by kanthalaHarivardhanReddy** [comment]
\assign

**Comment by joshi-kaushal** [comment]
I have made a PR regarding this.
