### ISSUE TITLE
Some Famous Open-Source Software 

### ISSUE THREAD

**Issue by 1PRatgit** [girlscript/winter-of-contributing#643]
**Description** : There are various Open-Source Software Apps. This documentation gives brief notes on some of Open-Source software Apps such as Django, visual studio, Angular, React Native, VLC and many more. 
@Aryamanz29 I will able to share my knowledge on these topics if you assign this issue to me.

**Comment by Aryamanz29** [comment]
Thanks for suggesting, I'll creating issues try to complete that first
