### ISSUE TITLE
[Create New Issue]: Z's Algorithm

### ISSUE THREAD

**Issue by muskan26062000** [girlscript/winter-of-contributing#6439]
### Description

I would provide detailed explaination and code for the implementation of Z's Algorithm which is an algorithm for sorting and searching.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
Closing the issue since deadline to open new PRs is over. Thanks for all your contributions.
