### ISSUE TITLE
OpenSource : 5.14 Explain everything related to `Rook`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#646]
### Description :

- **Explain everything related to `Rook`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by HassanRahim26** [comment]
Hey @Aryamanz29, I would like to work on this issue. Can you please assign me this issue?
Name:- Hassan Rahim
Batch:- Open-Source Batch-6
Type:- Documentation

**Comment by FirdausJawed** [comment]
wanna contribute here

**Comment by mohitmishra786** [comment]
Mohit Mishra
Open Source Batch 1 
Link:-https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by Aryamanz29** [comment]
@FirdausJawed   Assigned, Happy Learning 🎉🎉

**Comment by mayankkuthar** [comment]
@Aryamanz29 If Anyone is not working on this issue, I would love to work on this one, Kindly Assign it to me, 😄

**Comment by Aryamanz29** [comment]
@FirdausJawed  Try to raise PR by today

**Comment by Harshkumar62367** [comment]
can i work on this @Aryamanz29 . I am currently out of issues.

**Comment by mayankkuthar** [comment]
@Aryamanz29 Please Assign me this issue I would like to work on this one, I showed my interest fo this one earlier too. :octocat:

**Comment by Aryamanz29** [comment]
@mayankkuthar  Assigning this to you
