### ISSUE TITLE
 Open Source : 6.61 Explain everything related to `youtube-dl`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6462]
<hr>

## Description 📜

 Open Source : 6.61 Explain everything related to `youtube-dl`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.61_youtube-dl.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@Binita-tech  Sure, Go ahead

**Comment by Aryamanz29** [comment]
Any updates on this ?  @Binita-tech

**Comment by Binita-tech** [comment]
Will make PR today
