### ISSUE TITLE
 Open Source : 6.62 Explain everything related to `httpie`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6463]
<hr>

## Description 📜

 Open Source : 6.62 Explain everything related to `httpie`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.62_httpie.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RK1905101** [comment]
/assign
for documentation
