### ISSUE TITLE
OpenSource : 5.15 Explain everything related to `Helm`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#647]
### Description :

- **Explain everything related to `Helm`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by HassanRahim26** [comment]
Hey @Aryamanz29, I would like to work on this issue. Can you please assign me this issue?
Name:- Hassan Rahim
Batch:- Open-Source Batch-6
Type:- Documentation

**Comment by mohitmishra786** [comment]
Mohit Mishra
Open Source Batch 1 
Link:-https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by FirdausJawed** [comment]
I want to contribute here in documentation form

**Comment by Aryamanz29** [comment]
You both have already assigned issue , try to complete that first @mohitmishra786  @FirdausJawed

**Comment by mohitmishra786** [comment]
@Aryamanz29 I had already created a PR for my last issue, until when it will be closed or I will git any review for changes so that I can choose another issue

**Comment by Aryamanz29** [comment]
@mohitmishra786  Assigning this to you , Happy Learning 🎉🎉

**Comment by aaditya2801** [comment]
Hey, I am Aaditya Tiwari GWOC Contributor, my domain is open source, and I would like to add content related to Helm. please /assign me.

**Comment by mayankkuthar** [comment]
@Aryamanz29 If no one is working on this issue, I would like to contribute, Please Assign me the issue.

**Comment by Aryamanz29** [comment]
@aaditya2801  Assigning this you , Happy Learning 🎉🎉

**Comment by aaditya2801** [comment]
@Aryamanz29 Thank you, I am working on it 👍
