### ISSUE TITLE
OpenSource : 5.16 Explain everything related to `Jaeger`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#648]
### Description :

- **Explain everything related to `Jaeger`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by HassanRahim26** [comment]
Hey @Aryamanz29, I would like to work on this issue. Can you please assign me this issue?
Name:-  Hassan Rahim
Batch:- Open-Source Batch-6
Type:- Documentation

**Comment by Sakshi-1101** [comment]
Sir may I contribute to this?

**Comment by Aryamanz29** [comment]
@Sakshi-1101 Assigning this to you, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@Sakshi-1101  Any updates ?? Already 3 days passed?

**Comment by Sakshi-1101** [comment]
Sorry for the delay sir...
I'll make the PR by tomorrow.

**Comment by Sakshi-1101** [comment]
Sir I am new to open source. 
I am not able to see the pull request option? 
Please help..

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Sir I am new to open source.
> I have a doubt. Do I have to make a new branch and make changes in that or I have to change my branch from main to Opensource because when I am changing the branch to opensource it is showing an error??
> Please help..

You have to checkout `Opensource branch` and make changes then create PR to `girlscript : Opensource`
