### ISSUE TITLE
OpenSource : 5.18 Explain everything related to `envoy`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#649]
### Description :

- **Explain everything related to `envoy`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by HassanRahim26** [comment]
Hey @Aryamanz29, I would like to work on this issue. Can you please assign me this issue?
Name:- Hassan Rahim
Batch:- Open-Source Batch-1
Type:- Documentation

**Comment by Aryamanz29** [comment]
@HassanRahim26  Assigning this to you, Happy Learning 🎉🎉
