### ISSUE TITLE
OpenSource : 5.19 Explain everything related to `containerd`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#650]
### Description :

- **Explain everything related to `containerd`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by mohitmishra786** [comment]
Mohit Mishra
OpenSource Batch 1
Profile_Link:- https://github.com/mohitmishra786
I want to contribute through documentation

**Comment by Aryamanz29** [comment]
@mohitmishra786   Assigning this to you, Happy Learning 🎉🎉
