### ISSUE TITLE
[Python] : Image Processing using Python

### ISSUE THREAD

**Issue by burpcat** [girlscript/winter-of-contributing#6500]
### Description

- What is Image Processing?
- How Python can be used for image processing?
- Examples

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vandana3869** [comment]
@adityabisoi  please assign this issue for the video contribution

**Comment by adityabisoi** [comment]
@iamtanya-22 Audio??

**Comment by vandana3869** [comment]
@adityabisoi  please review this pr
