### ISSUE TITLE
Dictionary Method

### ISSUE THREAD

**Issue by Vibhu562** [girlscript/winter-of-contributing#6548]
### Description

What are methods in dictionary.
Explain all methods by giving suitable example.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by TakshakRamteke** [comment]
@adityabisoi is the issue still open to contribution, would like to contribute via Audio/Video

**Comment by shaurya24sri** [comment]
@adityabisoi please assign me for audio
