### ISSUE TITLE
OpenSource : 5.22 Explain everything related `CoreDNS`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#656]
### Description :

- **Explain everything related to `CoreDNS`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by harshi606** [comment]
Hi! I would love to contribute. Can you assign me to this topic ?

**Comment by Aryamanz29** [comment]
@harshi606  Assigned, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@harshi606  Any updates on this ?? Already 3 days passed

**Comment by ELLIPSIS009** [comment]
@Aryamanz29 can i contribute to this ?

**Comment by Aryamanz29** [comment]
@ELLIPSIS009  Assigning this to you , Happy learning 🎉🎉

**Comment by Aryamanz29** [comment]
@ELLIPSIS009  Any updates?

**Comment by mayankkuthar** [comment]
@Aryamanz29 If no one is working on this issue, I would like to contribute, Please Assign me the issue.

**Comment by ELLIPSIS009** [comment]
@Aryamanz29 i am almost done with the documentation
