### ISSUE TITLE
Documentation about AVL tree 

### ISSUE THREAD

**Issue by prak895** [girlscript/winter-of-contributing#6569]
### Description

In this I clearly defined about AVL tree with examples.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
You can work on it @prak895
