### ISSUE TITLE
OpenSource : 5.23 Explain everything related to `etcd`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#657]
### Description :

- **Explain everything related to `etcd`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Khushi-Agrawal-1** [comment]
I would like to contribute to this
Full name: Khushi Agrawal
Batch Number: 2
GitHub profile: https://github.com/Khushi-Agrawal-1
Type: Documentation

**Comment by Aryamanz29** [comment]
@Khushi-Agrawal-1  Assigned to you, Complete that first 
Thanks

**Comment by AdityaStark7** [comment]
Hey! 
I would like to contribute on this issue 
Batch: 03

**Comment by mayankkuthar** [comment]
I would love to work on this, Please Assign me this Issue. :octocat:

**Comment by Aryamanz29** [comment]
@mayankkuthar  Go ahead, Happy Learning 🎉🎉
