### ISSUE TITLE
Flutter: CALLS SCREEN for Whatsapp clone

### ISSUE THREAD

**Issue by ViAsmit** [girlscript/winter-of-contributing#6579]
### Description

Create a chat screen for WhatsApp clone
The screen where we have all the calls from all people.

Reference: #6573

NOTE: USE models for data, don't add hardcoded data, by yourself. Hardcoded data will be present in the models folder, inside classes, and list, Use that only

### Domain

Android Dev (Flutter)

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ViAsmit** [comment]
@Gagarod Please pull the latest changes, as some images were not correct in models.

**Comment by Gagarod** [comment]
@ViAsmit Can I make a few changes in the Call Model?

**Comment by ViAsmit** [comment]
Yep... you can

**Comment by Gagarod** [comment]
@ViAsmit  I have made the PR. Please check if everything is good to go.
