### ISSUE TITLE
OpenSource : 5.24 Explain everything related to `Open Policy Agent`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#658]
### Description :

- **Explain everything related to `Open Policy Agent`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by KhafiaAyyub** [comment]
Can I work on this issue?

**Comment by Aryamanz29** [comment]
@KhafiaAyyub  Assigning this to you, Happy learning 🎉🎉

**Comment by Aryamanz29** [comment]
@KhafiaAyyub  Any updates on this ?? Already 3 days passed

**Comment by KhafiaAyyub** [comment]
@Aryamanz29 Yes, I am working will submit it today .
