### ISSUE TITLE
Different types of Loops

### ISSUE THREAD

**Issue by priyankapiba** [girlscript/winter-of-contributing#6582]
### Description

What are loops?
What are different kinds of loops in python with example?

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by adityabisoi** [comment]
Topic already covered. Closing this issue.
