### ISSUE TITLE
ML 6.8 : Stochastic and Minibatch Gradient Descent (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#6597]
### 📌  Issues for Week 6
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Stochastic and Minibatch Gradient Descent_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Dimensionality_Reduction_&_Neural_Networks` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by abhisheks008** [comment]
@tanvideshmukh29 ?

**Comment by abhisheks008** [comment]
Hey @tanvideshmukh29 what's the update?

**Comment by tanvideshmukh29** [comment]
Sry for the delay (due to some reason)will do it tomorrow.

**Comment by abhisheks008** [comment]
@tanvideshmukh29 ?

**Comment by abhisheks008** [comment]
@tanvideshmukh29 ❔

**Comment by riyasai22** [comment]
If this issue is still open, I would like to contribute to this issue. @abhisheks008
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22
Contribution type: documentation

**Comment by ShraddhaMeshram27** [comment]
Full name : Shraddha Meshram
Batch Number : 3
GitHub Profile Link : https://github.com/ShraddhaMeshram27
Which type of Contribution you want to make :
Documentation

Assign me this issue if @tanvideshmukh29 is busy.
I'll do it in a day positively.

**Comment by tanvideshmukh29** [comment]
I m doing it.

**Comment by abhisheks008** [comment]
@tanvideshmukh29 when will you be able to create the PR for your assigned issue?

**Comment by tanvideshmukh29** [comment]
before 1 am today
