### ISSUE TITLE
How to Install and Setup Flutter for App Development 

### ISSUE THREAD

**Issue by aaryan078** [girlscript/winter-of-contributing#66]
Description
Give a brief on how to download and install Flutter on a device (Mac, Windows, Linux).

**Comment by aaryan078** [comment]
can I take this

**Comment by anmol20112000** [comment]
Can i work on this??

**Comment by jaissumi1402** [comment]
can you assign this work to me?

**Comment by AdityaChaudhary18** [comment]
Can I work on this?

**Comment by LegendSumeet** [comment]
can you assign this work to me? @aaryan078

**Comment by ViAsmit** [comment]
@aaryan078  have you completed this issue?

**Comment by msbuddhu** [comment]
Hey @ViAsmit,
Shabi Kaushal this side. I am good at Cross-platform development using Dart and Flutter. I can implement them in practice lucidly as well as document them. May you assign me this task?

Shabi Kaushal (Android Development with Flutter Batch 10)

**Comment by aaryan078** [comment]
@ViAsmit  No, i will complete in 2 days

**Comment by ViAsmit** [comment]
@msbuddhu sorry for the convenience.. someone already started the work for this topic... I will be adding new topics by tomorrow. You can contribute in those.. thank you

**Comment by Harshit9557** [comment]
I am interested in this issue
Can you assign this to me?
