### ISSUE TITLE
OpenSource : 5.26 Explain everything related to `Linkerd`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#660]
### Description :

- **Explain everything related to `Linkerd`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Khushi-Agrawal-1** [comment]
I would like to contribute to this
Full name: Khushi Agrawal
Batch Number: 2
GitHub profile: https://github.com/Khushi-Agrawal-1
Type: Documentation

**Comment by Aryamanz29** [comment]
@Khushi-Agrawal-1  Assigning this to you, Happy learning 🎉🎉
