### ISSUE TITLE
ML 6.10 : Back-propagation (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#6612]
### 📌  Issues for Week 6
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Back-propagation_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Dimensionality_Reduction_&_Neural_Networks` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by raina-akshay** [comment]
@kokila-Manogar ?

**Comment by abhisheks008** [comment]
Hey @kokila-Manogar  what's the update?

**Comment by Isha307** [comment]
@kokila-Manogar Give us the update by today, if you fail to do so then this issue will be unassigned to you.

**Comment by kokila-Manogar** [comment]
@abhisheks008  sorry sir , I don't know how to create Pull request and add my readme file. 
Extremely, Sorry for replying late. 
If you help me on that surly I will submit it by today itself sir. 
And I have another doubt I want to upload my video on YouTube or drive, Sir

@Isha307 help me mam.

**Comment by abhisheks008** [comment]
@kokila-Manogar ❓

**Comment by mimansa-sardhalia** [comment]
please assign me this issue
name- Mimansa Sardhalia
Batch-5

**Comment by abhisheks008** [comment]
@mimansa-sardhalia what's the update here?

**Comment by samridhikapoor** [comment]
I would like to contribute for this issue. I request you to assign me the same.
Thanks

Name: Samridhi Kapoor
Batch No.: 3
Github Profile link: https://github.com/samridhikapoor
Type of contribution I want to make: Video (as specified)

**Comment by abhisheks008** [comment]
issue assigned to @samridhikapoor

**Comment by abhisheks008** [comment]
What's the progress in this issue @samridhikapoor ?

**Comment by samridhikapoor** [comment]
The PPT is almost ready. Just a few slides are left. Will record the same and submit it ASAP.
@abhisheks008

**Comment by abhisheks008** [comment]
What's your progress here @samridhikapoor

**Comment by samridhikapoor** [comment]
The PPT is complete. Will record the video and submit it by Saturday for sure.

**Comment by abhisheks008** [comment]
Make sure you submit your PR by Saturday @samridhikapoor

**Comment by samridhikapoor** [comment]
Yeah I will for sure. @abhisheks008

**Comment by abhisheks008** [comment]
@samridhikapoor Today is Sunday. Haven't got your PR.

**Comment by samridhikapoor** [comment]
> @samridhikapoor Today is Sunday. Haven't got your PR.

I have created the PR for this issue. Kindly review the same

Link to the PR: https://github.com/girlscript/winter-of-contributing/pull/7883

Thanks
