### ISSUE TITLE
OpenSource : 5.28 Explain everything related to `BuildPacks`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#663]
### Description :

- **Explain everything related to `BuildPacks`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Asmit2952** [comment]
I already have info present with me, because I was researching about BuildPacks for Mentorship.  Can I work on this?

**Comment by Aryamanz29** [comment]
@Asmit2952  Suree, Happy Learning 🎉🎉
