### ISSUE TITLE
Adding full structure of Recursion and Backtracking

### ISSUE THREAD

**Issue by Bikramjit21** [girlscript/winter-of-contributing#6635]
### Description

Recursion and Backtracking

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
@Bikramjit21 you've created the same issue twice so closing one of them. Also, please see the discord for the response on your PR problem and submit the work asap. Thanks.
