### ISSUE TITLE
OpenSource : 5.29 Explain everything related to `CloudEvents`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#664]
### Description :

- **Explain everything related to `CloudEvents`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by priyanshuc4423** [comment]
please assign me

**Comment by Aryamanz29** [comment]
@priyanshuc4423  Assigned, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@priyanshuc4423  Any updates on this ?? Already 3 days passed

**Comment by priyanshuc4423** [comment]
> @priyanshuc4423 Any updates on this ?? Already 3 days passed

added please have a look
