### ISSUE TITLE
OpenSource : 5.30 Explain everything related to `Cloud Native :- Container Networking Interface (CNI)`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#665]
### Description :

- **Explain everything related to `Cloud Native Network (CNI)`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by yashikabhargava** [comment]
@Aryamanz29 can I work on this

**Comment by Aryamanz29** [comment]
@yashikabhargava  Container Networking Interface

**Comment by yashikabhargava** [comment]
@Aryamanz29 Thank you!

**Comment by yashikabhargava** [comment]
@Aryamanz29 can you please review my PR.
