### ISSUE TITLE
Python Keywords

### ISSUE THREAD

**Issue by TammanaNiharika** [girlscript/winter-of-contributing#6653]
### Description

To describe what is a **keyword** and available keywords in python.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal
I would like to work on documentation part of this issue
pls assign it to me

**Comment by TammanaNiharika** [comment]
Documentation completed!

**Comment by TammanaNiharika** [comment]
Successfully merged to python branch
