### ISSUE TITLE
OpenSource : 5.31 Explain everything related to `Contour`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#666]
### Description :

- **Explain everything related to `Contour`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by xxEasterGrymm** [comment]
I would like to contribute to this @Aryamanz29

**Comment by Aryamanz29** [comment]
@xxEasterGrymm  Sure, Happy Learning 🎉🎉

**Comment by LegendSumeet** [comment]
assign me to these @Aryamanz29

**Comment by priyall** [comment]
assign me to this @Aryamanz29

**Comment by Aryamanz29** [comment]
> assign me to this @Aryamanz29

Assigned , Happy docs 🎉

**Comment by Aryamanz29** [comment]
@priyall  Any updates on this ?

**Comment by xxEasterGrymm** [comment]
@Aryamanz29 why was I unassigned from this?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 why was I unassigned from this?

Due to inactivity, Raise PR by today to get it merged

**Comment by Aryamanz29** [comment]
@xxEasterGrymm  Create PR from `your_fork : Opensource` branch to `girlscript : Opensource` branch

**Comment by priyall** [comment]
@Aryamanz29  Apologies for late reply, I was actually understanding the process so couldn't complete it in the given time.

**Comment by mayankkuthar** [comment]
@Aryamanz29 If no one is working on this issue, I would like to contribute, Please Assign me the issue.

**Comment by xxEasterGrymm** [comment]
> 
> 
> > @Aryamanz29 why was I unassigned from this?
> 
> Due to inactivity, Raise PR by today to get it merged

@Aryamanz29 but I was active, I had raised two PRs, yes both of them were invalidated, but I wasn't inactive
