### ISSUE TITLE
OpenSource : 5.32 Explain everything related to `Cortex`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#667]
### Description :

- **Explain everything related to `Cortex`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by LegendSumeet** [comment]
assign me to these @Aryamanz29

**Comment by AdityaStark7** [comment]
Hello,
I would like to contribute to this issue
Batch: 03
Aditya Kumar
@Aryamanz29 
Thanks !

**Comment by Aryamanz29** [comment]
@LegendSumeet  Sure, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@LegendSumeet  Any updates on this ?

**Comment by LegendSumeet** [comment]
Yes just finalized things are Remaining Like Conclusion etc

**Comment by Aryamanz29** [comment]
@LegendSumeet  Any updates ??

**Comment by LegendSumeet** [comment]
Yes today last day @Aryamanz29

**Comment by Aryamanz29** [comment]
@LegendSumeet last day?

**Comment by LegendSumeet** [comment]
Yess sorry I am facing plag issue so just tomorrow is will be ready@Aryamanz29
