### ISSUE TITLE
OpenSource : 5.33 Explain everything related to `CRI-O`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#668]
### Description :

- **Explain everything related to `CRI-O`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Dracarys0511** [comment]
Can I contribute here in form of documentation?

**Comment by Aryamanz29** [comment]
@Dracarys0511  Assigning this to you, Happy Learning 🎉🎉

**Comment by Dracarys0511** [comment]
> 
> 
> @Dracarys0511 Assigning this to you, Happy Learning 🎉🎉

Thank you

**Comment by Dracarys0511** [comment]
@Aryamanz29 sir is it fine for merging?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 sir is it fine for merging?

Merged  🎉🎉
