### ISSUE TITLE
OpenSource : 5.34 Explain everything related to `CrossPlane`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#669]
### Description :

- **Explain everything related to `CrossPlane`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by PrachiDoshi2170** [comment]
Hello @Aryamanz29 I would like this issue to be assigned to me
This will be my first contribution to the open source branch
Type: Documentation

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170  Sure, Happy Learning 🎉🎉

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170  Any updates On this ??

**Comment by PrachiDoshi2170** [comment]
Yes yes I am done almost I will upload by tonight

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170  Cool

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170  Any updates on this ?

**Comment by mayankkuthar** [comment]
@Aryamanz29 If no one is working on this issue, I would like to contribute, Please Assign me the issue.

**Comment by Aryamanz29** [comment]
@mayankkuthar  Assigning this you @mayankkuthar , Happy Learning 🎉🎉
