### ISSUE TITLE
OpenSource : 5.35 Explain everything related to `DragonFly`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#670]
### Description :

- **Explain everything related to `DragonFly`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by developer-metalhead** [comment]
I would like to work on this issue.

**Comment by AdityaStark7** [comment]
I want to work on this issue.
Name: Aditya Kumar
Batch: 03
Serial No. 374

**Comment by AdityaStark7** [comment]
Hey,
I would like to work on this issue
Batch: 03
Aditya Kumar
Type: Documentation

**Comment by Aryamanz29** [comment]
@AdityaStark7  Assigning this to you , Happy learning 🎉

**Comment by Aryamanz29** [comment]
@AdityaStark7  Any updates on this ?? Already 3 days passed
