### ISSUE TITLE
OpenSource : 5.36 Explain everything related to `Falco`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#671]
### Description :

- **Explain everything related to `Falco`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by LegendSumeet** [comment]
assign me to these @Aryamanz29

**Comment by AdityaStark7** [comment]
Hey! 
I would like to contribute on this issue 
Batch: 03

**Comment by 4khadija** [comment]
Hey, I  would like to contribute on this.
Name- Khadija Korasawala
Batch-4 
Type: Documentation

**Comment by Aryamanz29** [comment]
@4khadija  Sure,Happy Learning 🎉🎉

**Comment by 4khadija** [comment]
I'm sorry I just need a little more time, I am working on it.
