### ISSUE TITLE
STOCK MARKET PREDICTION AND FORECASTING USING LSTM

### ISSUE THREAD

**Issue by ShraddhaP123** [girlscript/winter-of-contributing#6710]
### Description

Description
Description
Shraddha Pattanshetti -649
Batch - 17
Type: documentation
Approach: What is LSTM, Purpose of LSTM and code of Stock market prediction using LSTM

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by rahilmehta-24** [comment]
./assign documentation
