### ISSUE TITLE
OpenSource : 5.37 Explain everything related to `Flagger`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#672]
### Description :

- **Explain everything related to `Flagger`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by LegendSumeet** [comment]
assign me to these @Aryamanz29

**Comment by Kalyani02072003** [comment]
can i be assigned to work on its documentation ?

**Comment by 4khadija** [comment]
Hey, I would like to contribute on this.
Name- Khadija Korasawala
Batch-4
Type: Documentation

**Comment by Aryamanz29** [comment]
@Kalyani02072003 Assigned, Happy Learning 🎉🎉

**Comment by Kalyani02072003** [comment]
@Aryamanz29 thank you for assigning me, if I run into problems how can I contact you? 
my discord username is - STRAWHAT_LUFFY#8651

**Comment by Aryamanz29** [comment]
> @Aryamanz29 thank you for assigning me, if I run into problems how can I contact you?
> my discord username is - STRAWHAT_LUFFY#8651

Sure

**Comment by Aryamanz29** [comment]
@Kalyani02072003  Any updates on this ?

**Comment by Kalyani02072003** [comment]
> @Kalyani02072003 Any updates on this ?

yes sir, sir i am currently learning about flagger first. i put my name here because I have not been assigned to anything that time. give me like a week or so, once I understand flagger then I write on it so that even a complete beginner like me can also understand

**Comment by Kalyani02072003** [comment]
> @Kalyani02072003 Any updates on this ?

sir can you please assign it to someone else, because I can barely understand what is flagger. it is better if someone who is familiar with this open source write about it. thank you again

**Comment by Aryamanz29** [comment]
> > @Kalyani02072003 Any updates on this ?
> 
> sir can you please assign it to someone else, because I can barely understand what is flagger. it is better if someone who is familiar with this open source write about it. thank you again

Sure

**Comment by Harshkumar62367** [comment]
Can i work on this @Aryamanz29

**Comment by Aryamanz29** [comment]
@Harshkumar62367  Sure, Happy learning 🎉🎉
