### ISSUE TITLE
Android Kotlin: Marvel vs DC Quiz App

### ISSUE THREAD

**Issue by shubhmittal07** [girlscript/winter-of-contributing#6746]
@rahulsain 
This is a quiz app related to superhero franchise DC and Marvel.

<p align = "left">
<img src="https://user-images.githubusercontent.com/59731205/138231597-cefc4a27-3d9f-4dec-80ab-f43a344b95ae.png" width ="200">
<img src="https://user-images.githubusercontent.com/59731205/138231899-214c5c29-2136-4826-a974-3be096ff750c.png" width ="200">
<img src="https://user-images.githubusercontent.com/59731205/138232001-eade077b-84a2-498b-a7fa-2f9e5ae52476.png" width ="200">
</p>

**Comment by sitamadex11** [comment]
@rahulsain I think we should close this issue.

**Comment by shubhmittal07** [comment]
Should I close it then? @sitamadex11 @rahulsain
