### ISSUE TITLE
OpenSource : 5.39 Explain everything related to `gRPC`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#675]
### Description :

- **Explain everything related to `gRPC`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by riyapandey730** [comment]
I would like to contribute to this via documentation.Please consider me for this..
Riya Pandey
Batch-2

**Comment by Aryamanz29** [comment]
@riyapandey730  Assigning this to you, Happy Learning 🎉🎉🎉

**Comment by riyapandey730** [comment]
Thankyou...

**Comment by Aryamanz29** [comment]
Any updates on this @riyapandey730

**Comment by riyapandey730** [comment]
by tomorrow
