### ISSUE TITLE
OpenSource : 5.40 Explain everything related to `KEDA`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#676]
### Description :

- **Explain everything related to `KEDA`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by lohith1392** [comment]
I would like to work on this please documentation

Peddi sai lohith

**Comment by LegendSumeet** [comment]
assign me to these @Aryamanz29

**Comment by PrachiDoshi2170** [comment]
Hello @Aryamanz29 I would like this issue to be assigned to me I have not yet got the opportunity to contribute to the domain of open source.

Type: Documentation

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170   Assigning this to you , Happy docs 🎉🎉

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170 Any updates on this ?? Already 2 days passed

**Comment by PrachiDoshi2170** [comment]
Hey I have almost completed both the works I will upload for PR by tomorrow
evening.

**Comment by Aryamanz29** [comment]
@PrachiDoshi2170  Any updates??

**Comment by PrachiDoshi2170** [comment]
I have added the pull request
