### ISSUE TITLE
Add number system in Python

### ISSUE THREAD

**Issue by priyankapiba** [girlscript/winter-of-contributing#6765]
### Description

What is a number system?
What are the types of number systems in Python with examples?

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by adityabisoi** [comment]
Can you give a better description on your topic?

**Comment by priyankapiba** [comment]
Number system, I mean, binary number system, decimal number system and many more, explanation with examples as well as python program for converting from one form to another.

**Comment by adityabisoi** [comment]
Go ahead

**Comment by priyankapiba** [comment]
Which mentor is assigned for this issue?


> Go ahead

Which mentor is assigned for this issue?

**Comment by adityabisoi** [comment]
You can ask any of the mentors
