### ISSUE TITLE
OpenSource : 5.41 Explain everything related to `KubeEdge`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#677]
### Description :

- **Explain everything related to `KubeEdge`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Harshkumar62367** [comment]
can i work on this @Aryamanz29 ? I can do this alongside with kubernates.

**Comment by Aryamanz29** [comment]
@Harshkumar62367  Assigning this to you, Happy docs 🎉

**Comment by Aryamanz29** [comment]
@Harshkumar62367  Any updates on this ?? Already 3 days passed
