### ISSUE TITLE
return keyword in Python

### ISSUE THREAD

**Issue by I-ArchanaDash** [girlscript/winter-of-contributing#6777]
### Description

Description:
This Documentation will explain the use of **return** keyword in Python

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by adityabisoi** [comment]
The topic doesn't exist, but will be too short. You can also include return vs break & return vs continue in your content.

**Comment by adityabisoi** [comment]
Go ahead with it

**Comment by I-ArchanaDash** [comment]
> The topic doesn't exist, but will be too short. You can also include return vs break & return vs continue in your content.

Okay I will add these too

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal
I would like to work on documentation part of this issue
pls assign it to me

**Comment by I-ArchanaDash** [comment]
> Hello My name is Rohit Goyal I would like to work on documentation part of this issue pls assign it to me

@rohit-goyal I have already made a PR on this issue and working on the same also. You can continue with audio/video

**Comment by vandana3869** [comment]
@adityabisoi I would like to contribute to this issue in video format. Please assign :)
