### ISSUE TITLE
C/C++: Competitive Programming Problem(Card Shuffle)

### ISSUE THREAD

**Issue by Rijudas149** [girlscript/winter-of-contributing#6797]
### Description

In this Document, I want to make a document on a problem named "Card Shuffle"

Problem Link:- https://www.codechef.com/problems/CARDSHUF

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by jr-boney** [comment]
I would like to learn programming what should i do to learn it
