### ISSUE TITLE
OpenSource : 5.43 Explain everything related to `Notary`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#680]
### Description :

- **Explain everything related to `Notary`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by mohitmishra786** [comment]
@Aryamanz29  can you please assign me this issue as I had already opened the PR for my last issue.

**Comment by divyanshuss** [comment]
@Aryamanz29 Can I contribute?

**Comment by iamsunil25** [comment]
@Aryamanz29 can you please assign me this issue?
