### ISSUE TITLE
  Open Source : 6.70 Explain everything related to `FileZilla`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6809]
<hr>

## Description 📜

  Open Source : 6.70 Explain everything related to `FileZilla`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.70_filezilla.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by RaghavvGupta** [comment]
@Aryamanz29 can I work on this?

**Comment by Aryamanz29** [comment]
@RaghavvGupta  Go ahead
