### ISSUE TITLE
FRONTEND WITH FRAMEWORK: React -> Getting Started with React 

### ISSUE THREAD

**Issue by Subhampreet** [girlscript/winter-of-contributing#681]
### NEED TO CONTAIN

- What is React JS?
- Installation and Setup
- Hello World with Stateless Functions
- Absolute Basics of Creating Reusable Components
- Create React App
- Hello World Component

#### You can take refer from [React Official Documentation](https://reactjs.org/)

Also, make sure -
Avoid copy/paste, We will be checking.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ React inside Frontend_Web_Development_React_Angular_Vue branch.
The task will be assigned on first come first serve
Check out Contribution Guidelines
and Code Of Conduct

**Comment by shreya024** [comment]
Can I do this?

**Comment by Anshii12** [comment]
I would like to contribute to this. 
Name- Anshita Sharma
Batch- 3

**Comment by Subhampreet** [comment]
Hey @shreya024, I am assigning you the issue to work on!

**Comment by Babithakumari** [comment]
I want to work on this. If there is any reassigning, do consider me !

**Comment by Subhampreet** [comment]
Sure @Babithakumari  and @Anshii12, I would consider you if there's any kind of reassigning done!

**Comment by Tanisha-creator** [comment]
I want to work on this issue.
Type: Documentation
Batch 1

**Comment by prathamjagga** [comment]
I also want to contribute!
Name: Pratham
Batch: 3

**Comment by AnantDuhan** [comment]
I would love to work on this issue

**Comment by Harshita-Kohli** [comment]
I would like to work on this
Name: Harshita Kohli
Batch: 3
