### ISSUE TITLE
  Open Source : 6.75 Explain everything related to `Blender`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6814]
<hr>

## Description 📜

 Open Source : 6.75 Explain everything related to `blender`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.75_blender.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Adi9235** [comment]
@Aryamanz29 can i work on this issue

**Comment by Aryamanz29** [comment]
@Adi9235  Go ahead
