### ISSUE TITLE
  Open Source : 6.80 Explain everything related to `opencart`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6818]
<hr>

## Description 📜
  Open Source : 6.80 Explain everything related to `opencart`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.80_opencart.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
Any updates on this ?  @eshan1925

**Comment by eshan1925** [comment]
Will make a PR within 2 days was unwell sorry!!!
