### ISSUE TITLE
  Open Source : 6.79 Explain everything related to `7Zip`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6827]
<hr>

## Description 📜

  Open Source : 6.79 Explain everything related to `7Zip`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.79_7Zip.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by aaryan078** [comment]
I would like to work on this, please assign this to me
