### ISSUE TITLE
  Open Source : 6.89 Explain everything related to `Red Hat OpenShift`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6830]
<hr>

## Description 📜

  Open Source : 6.89 Explain everything related to `Red Hat OpenShift`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.89_RedHatOpenShift.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
@nishtha2405  Go ahead :fireworks:

**Comment by Aryamanz29** [comment]
@nishtha2405  Any updates?

**Comment by nishtha2405** [comment]
yes sir I'm working on it.

**Comment by riyapandey730** [comment]
can i work on this?
