### ISSUE TITLE
  Open Source : 6.92 Explain everything related to `Servo`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6833]
<hr>

## Description 📜

    Open Source : 6.92 Explain everything related to `Servo`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.92_Servo.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by 1PRatgit** [comment]
@Aryamanz29 I will be creating PR by evening.
