### ISSUE TITLE
  Open Source : 6.94 Explain everything related to `PyTorch`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6835]
<hr>

## Description 📜

  Open Source : 6.94 Explain everything related to `PyTorch`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.94_PyTorch.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Harshkumar62367** [comment]
Pls review my pr @Aryamanz29

**Comment by Harshkumar62367** [comment]
Can you close this one @Aryamanz29 . I have already submitted my pr
