### ISSUE TITLE
  Open Source : 6.95 Explain everything related to `Ant Design`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6836]
<hr>

## Description 📜

  Open Source : 6.95 Explain everything related to `Ant Design`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.95_AntDesign.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by A-GHOSH-dev** [comment]
I have only one open issue. Rest all I have created PR. (1 PR merged, 2 are still open)

**Comment by A-GHOSH-dev** [comment]
If it's not a problem, then can this issue be assigned to me?
