### ISSUE TITLE
  Open Source : 6.96 Explain everything related to `Fastlane`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6837]
<hr>

## Description 📜

   Open Source : 6.96 Explain everything related to `Fastlane`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.96_Fastlane.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
Any updates on this ? @astelrastogi

**Comment by RaghavvGupta** [comment]
@Aryamanz29 can I take this up?
