### ISSUE TITLE
  Open Source : 6.97 Explain everything related to `Nextcloud`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6838]
<hr>

## Description 📜

  Open Source : 6.97 Explain everything related to `Nextcloud`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.97_Nextcloud.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aryamanz29** [comment]
Any updates on this ? @astelrastogi

**Comment by Aryamanz29** [comment]
@Binita-tech  Sure, Go ahead

**Comment by riyapandey730** [comment]
can i work on this
