### ISSUE TITLE
OpenSource : 5.45 Explain everything related to `OperatorFramework`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#684]
### Description :

- **Explain everything related to `OperatorFramework`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by LegendSumeet** [comment]
assign me to these? @Aryamanz29

**Comment by Aryamanz29** [comment]
@LegendSumeet  Assigning this to you, Happy Learning 🎉🎉

**Comment by rajatsinghchauhan** [comment]
working on this

**Comment by Aryamanz29** [comment]
@rajatsinghchauhan  Cool

**Comment by Aryamanz29** [comment]
@rajatsinghchauhan  Any updates ??

**Comment by mayankkuthar** [comment]
@Aryamanz29 Please Assign me I would like to work on this issue
