### ISSUE TITLE
  Open Source : 6.99 Explain everything related to `TypeScript`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6840]
<hr>

## Description 📜

  Open Source : 6.99 Explain everything related to `TypeScript`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.99_TypeScript.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by riyapandey730** [comment]
@Aryamanz29 can you assign me this? I want to work on this....

**Comment by Harshkumar62367** [comment]
Hey @riyapandey730 , i am already assigned to this issue, and will be submitting my pr tonight, if you want to further contribute in this issue, you can reassign this issue after I submit my pr.
