### ISSUE TITLE
  Open Source : 6.100 Explain everything related to `Marlin`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#6841]
<hr>

## Description 📜

  Open Source : 6.100 Explain everything related to `Marlin`

### NOTE 👇
Please put your doc `6.Popular_Projects` with the name `6.100_Marlin.md`

<hr>

### Domain

Open Source

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by PurviBhoyar21** [comment]
@Aryamanz29 
 Can you please explain "Marlin" in 1 sentence just for more clarity.

**Comment by A-GHOSH-dev** [comment]
Marlin is open source firmware primarily designed for RepRap project based FDM (fused deposition modelling) 3D-printers using the Arduino platform. 

I was just searching through issues, and found your question. So answered it. I hope this will help.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Can you please explain "Marlin" in 1 sentence just for more clarity.

https://github.com/MarlinFirmware/Marlin

**Comment by Aryamanz29** [comment]
Any updates on this ? @PurviBhoyar21

**Comment by PurviBhoyar21** [comment]
I will make PR by this weekend because I am out of station.
@Aryamanz29 lemme know if this is possible to you

**Comment by Aryamanz29** [comment]
> I will make PR by this weekend because I am out of station. @Aryamanz29 lemme know if this is possible to you

Ok no problem :)
