### ISSUE TITLE
OpenSource : 5.46 Explain everything related to `Spiffe`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#685]
### Description :

- **Explain everything related to `Spiffe`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by eshan1925** [comment]
May i Work on this issue?

**Comment by Aryamanz29** [comment]
@eshan1925 Assigning this to you, Happy Learning 🎉🎉

**Comment by eshan1925** [comment]
ThankYou

**Comment by eshan1925** [comment]
So we need to submit everything related to spiffe in word form or pdf or readme.md?

**Comment by eshan1925** [comment]
@Aryamanz29 Please reply so that I can create PR by today. And also the PR which I will create will be for my own branch right?

**Comment by eshan1925** [comment]
Hey @Aryamanz29 please merge the PR if there is no issue.
Completed two of the assigned tasks.
