### ISSUE TITLE
Static scoping & Dynamic Scoping

### ISSUE THREAD

**Issue by vishnu95075** [girlscript/winter-of-contributing#6854]
### Description

# Static scoping & Dynamic Scoping with example

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as the PR is  merged !!
