### ISSUE TITLE
OpenSource : 5.48 Explain everything related to `THANOS`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#686]
### Description :

- **Explain everything related to `THANOS`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by sandeepkumar00110** [comment]
sir, i want to work on this. GSOC , OpenSource Batch-04

**Comment by Aryamanz29** [comment]
@sandeepkumar00110  Assigning this to you, Happy Learning 🎉🎉
