### ISSUE TITLE
OpenSource : 5.47 Explain everything related to `SPIRE`

### ISSUE THREAD

**Issue by Aryamanz29** [girlscript/winter-of-contributing#687]
### Description :

- **Explain everything related to `SPIRE`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-5`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by samik-rathore** [comment]
I would like to work on this issue

**Comment by Aryamanz29** [comment]
@samik-rathore  Suree, Happy Learning 🎉🎉

**Comment by samik-rathore** [comment]
Please assign this issue to me
Samiksha Rathore

**Comment by Aryamanz29** [comment]
@samik-rathore  Any updates on this ?? Already 3 days passed

**Comment by samik-rathore** [comment]
I have raised a PR please review it for any changes to be made

**Comment by samik-rathore** [comment]
@Aryamanz29

**Comment by Aryamanz29** [comment]
@samik-rathore  Why don't your PR to this issue?
