### ISSUE TITLE
C/CPP: XOR Linked List Documentation

### ISSUE THREAD

**Issue by OptimalLearner** [girlscript/winter-of-contributing#6874]
## XOR Linked List
A documentation describing XOR Linked List and all its operation in C++

## Directory
Data Structures/Linked List/XOR Linked List

## Description
- What is XOR Linked List?
- Insertion, Deletion, Traversal and Reversal in XOR Linked List
- Advantages and Disadvantages of XOR Linked List

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by rohit-goyal** [comment]
Hello 
My name is Rohit Goyal 
I would like to work on documentation part of this issue 
pls assign it to me
