### ISSUE TITLE
FRONTEND WITH FRAMEWORK: VueJS-6.5 => Dynamic Components

### ISSUE THREAD

**Issue by SourabhSaraswat-191939** [girlscript/winter-of-contributing#6905]
### Description

Contributors are required to explain about Dynamic Components in VueJs, which should cover questions like:-
What are Dynamic Components in Vue.js?
How does this work?
Why there is a need for this?
What are the advantages to use it and when to use it?
How to implement this with code (also give theory explanation of code)?
You can take 2-3 examples with codes of different types to explain this.
etc....

Note:

Plagiarism is strictly prohibited.
Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.
Files need to be added into the Week6 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by satyam-mahajan** [comment]
please assign me this issue, I can do it.

**Comment by SourabhSaraswat-191939** [comment]
> please assign me this issue, I can do it.

Hi @satyam-mahajan, sorry but Kriti used "/assign" before you that's why that is assigned to her. You can go for other issues.
#6903
#6902
#6900
#6355
#6353
#6000
#5997

It would be great to see you working on any of this issues.

**Comment by KritiG7** [comment]
Please do not unassign me . I have done the work but having issues making a PR  through git. I'll resolve and make a new PR asap for the following issue.

**Comment by SourabhSaraswat-191939** [comment]
@KritiG7 
Actually, this was unassigned automatically by github-bot because you used /assign more than 3 times. Or you can say you assigned yourself more active issues than the amount mentioned in the rules of bot.

No worry we will reassign this to you. Keep on working.

@anandhu720, please reassign it to her.

**Comment by KritiG7** [comment]
Sir kindly review my PR  and merge it. I have made a new one.

**Comment by SourabhSaraswat-191939** [comment]
I did that, you can check.

**Comment by KritiG7** [comment]
When you merge a PR it will automatically gets closed or will I have to close it from my end?

**Comment by SourabhSaraswat-191939** [comment]
No, you don't have to do anything. It will be merged and closed by Supervisor.

**Comment by KritiG7** [comment]
Alright ! Thanks
