### ISSUE TITLE
Android-Kotlin: 05.3 Android Broadcasts and Broadcast Receivers

### ISSUE THREAD

**Issue by ydasc815** [girlscript/winter-of-contributing#691]
### Description
- Create a documentation about Broadcasts and Broadcast Receivers in Android.
- You can develop small sample apps and use code screenshots to make the doc more illustrative.

### Resources

> [An overview of Broadcasts in Android - Official Docs](https://developer.android.com/guide/components/broadcasts)

- Changes should be made in **Android_Development/Kotlin/** directory under **Android_Development_With_Kotlin** branch.
- You have to push your PR to the **Android_Development_With_Kotlin** branch only.
- You can take help from the references provided here but do not simply try to copy it. Try to explain in your own words. **PRs with Plagiarised content will be rejected**.
- This issue is for **GWOC'21** contributors only.
- You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.

> Supervisor @rahulsain

**Comment by LegendSumeet** [comment]
yes i can do that can @ydasc815 assign me to these?

**Comment by Pooja-Goyal-1** [comment]
I would like to work on this issue. Please assign me

**Comment by rahulsain** [comment]
@LegendSumeet  already working on documentation part @Pooja-Goyal-1

**Comment by Pooja-Goyal-1** [comment]
Can we collab if @LegendSumeet agrees? Or what else has to be done?

**Comment by LegendSumeet** [comment]
Ohk @Pooja-Goyal-1

**Comment by LegendSumeet** [comment]
Ohk @Pooja-Goyal-1

**Comment by rahulsain** [comment]
@Pooja-Goyal-1 you can also work on audio or video part

**Comment by Sonali-Sharma-1** [comment]
@rahulsain  Could you assign me this task ?

**Comment by LegendSumeet** [comment]
yes lets collab

**Comment by Sonali-Sharma-1** [comment]
> yes lets collab

Where can i connect with you ? 
Slack / skype ?

**Comment by LegendSumeet** [comment]
You can develop small sample apps and use code screenshots to make the doc more illustrative.
@Sonali-Sharma-1 you just work on these and get ready by tomorrow or a day after

**Comment by LegendSumeet** [comment]
Yess @rahulsain assign to @Sonali-Sharma-1 she did the best  Documentation on these issue

**Comment by LegendSumeet** [comment]
@rahulsain no folder for activities
After 4  direct 7 
@ydasc815 
Where to commit 06 issues

**Comment by rahulsain** [comment]
> @rahulsain no folder for activities After 4 direct 7 @ydasc815 Where to commit 06 issues

you can make one for folder 05. , I have updated the issue name

**Comment by rahulsain** [comment]
> > @rahulsain no folder for activities After 4 direct 7 @ydasc815 Where to commit 06 issues
> 
> you can make one for folder 05. , I have updated the issue name

**Comment by Sonali-Sharma-1** [comment]
@rahulsain  I will make changes accordingly then.

**Comment by sitamadex11** [comment]
@rahulsain

**Comment by ayush-sleeping** [comment]
Hey @rahulsain , Assign me this issue for  ` "  Audio  " ` section . <br>
Thanks
