### ISSUE TITLE
Timing Events in JavaScript

### ISSUE THREAD

**Issue by I-ArchanaDash** [girlscript/winter-of-contributing#6924]
### Description

Description
This Documentation explains JS Timing Events

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@I-ArchanaDash Can you please assign this issue to me ?

**Comment by I-ArchanaDash** [comment]
> @I-ArchanaDash Can you please assign this issue to me ?

Hey @priyanshu688 , I'm also one of the contributors just like you and have opened this issue for myself.
