### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(6.5) -> FormControl,FormBuilder

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#6931]
### Description

- What is formcontrol?
- Define some methods of formcontrol?
- What is formbuilder?
- Define some methods of formbuilder?
- How to initialise formcontrol?
- Explain with syntax/example
- Reference :- https://angular.io/guide/forms-overview
https://angular.io/api/forms/FormBuilder
https://angular.io/api/forms/FormControl

(Week 6 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week6" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by satyam-mahajan** [comment]
please assign me this issue ,I can do it.

**Comment by koshimagoyal** [comment]
@satyam-mahajan please use /assign to assign it for yourself

**Comment by satyam-mahajan** [comment]
Closes #6931

**Comment by satyam-mahajan** [comment]
Fixes #6931

**Comment by satyam-mahajan** [comment]
please unassign this issue to me so that I can take another.

**Comment by koshimagoyal** [comment]
@satyam-mahajan you haven't created any PR to this yet

**Comment by satyam-mahajan** [comment]
I created but not much knowledge of framework.

**Comment by koshimagoyal** [comment]
@satyam-mahajan no problem just answer questions with what you have learnt and we will review it. We will also tell if any enhancement need to be done. This is how you will also learn.

**Comment by satyam-mahajan** [comment]
Ohk mam, I will do it

**Comment by satyam-mahajan** [comment]
There is no week 6 in angular section. then where should I documented.

**Comment by satyam-mahajan** [comment]
mam when I fork the repositery it shows 3 week only in angular section Not available week 6 section in fork. how to do the changes.
