### ISSUE TITLE
Infix to Postfix using stack in C++

### ISSUE THREAD

**Issue by Narotam-singh** [girlscript/winter-of-contributing#6945]
### Description

Hey, I want to create documentation on converting infix expression to postfix using stack in c++

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this as PR got merged
