### ISSUE TITLE
Implementation of linked list 

### ISSUE THREAD

**Issue by akratikushwah** [girlscript/winter-of-contributing#6950]
### Description

Implementation of linked list 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this issue as #7455 got merged !
