### ISSUE TITLE
DSA 4.1.1 Introduction to stacks-documentation

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#6964]
## Description
Give an introduction and explain the working of stacks

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Kavindra-Mohan-Dwivedi** [comment]
Please Assign this to me if not self assigned.

**Comment by uzma024** [comment]
I would like to work on this issue.
Uzma Firoz Khan
DSA
Batch 10
Documentation.

**Comment by dhruti29** [comment]
@Muskan-creator I would like to work on this issue.
BATCH - 2 
Dhruti Gandhi

**Comment by Muskan-creator** [comment]
@Kavindra-Mohan-Dwivedi go ahead

**Comment by siddhi-244** [comment]
Can I try this?
Documentation 
DSA Batch 1

**Comment by jaigora24** [comment]
@Muskan-creator  mam if this issue is pending plz assign to me
Name - Jai Gora
Batch - 7
Type - Documentation
