### ISSUE TITLE
Front-end: Syntactically Awesome StyleSheets (SASS)

### ISSUE THREAD

**Issue by Yashesvinee** [girlscript/winter-of-contributing#6976]
### Description

Sass, or "Syntactically Awesome StyleSheets", is a language extension of CSS

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Yashesvinee** [comment]
@2024-SANDHYA  all topics from the roadmap has been covered

**Comment by Yashesvinee** [comment]
Aren't we allowed to make our own issues related to the domain?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Aren't we allowed to make our own issues related to the domain? SASS is a language extension of CSS

Sass is a different topic in itself.  Create issues within HTML JS & CSS that's it !!
