### ISSUE TITLE
CN [Cheat Sheet]

### ISSUE THREAD

**Issue by rhythmjayee** [girlscript/winter-of-contributing#6983]
### Description

CN (Computer Networks) mostly asked Questions and Answers.

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saketsagarsingh** [comment]
Saket Sagar
Interview Preparation Batch-2
Documentation
I want to work on this issue may I be assigned for this issue.

**Comment by saketsagarsingh** [comment]
Saket Sagar
Interview Preparation Batch-2
Documentation
I want to work on this issue may I be assigned for this issue.
