### ISSUE TITLE
ML 7.5: Catboost (V)

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#7002]
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Catboost_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Bayesian_ML_&_Ensemble_based_Learning` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make :
    - [ ] Video

*************************************************************
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by kishlayaug15** [comment]
Name - Kishlay Kumar
Batch - 4
Serial No - 673
GithubLink :- https://github.com/kishlayaug15
Approach: A detailed explanation with examples

**Comment by raina-akshay** [comment]
@kishlayaug15 not more than 1 issue at a time

**Comment by NikitaEmberi** [comment]
Nikita Bhrugumaharshi Emberi 
Domain-Machine Learning 
Batch-6 
Serial No-992
type - video

**Comment by raina-akshay** [comment]
to you @NikitaEmberi
