### ISSUE TITLE
ML 7.2: Adaboost (V)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#7005]
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Adaboost_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Ensemble_based_Learning_&_Probabilistic_ML` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
I am M. Ashish Reddy, I would like to work on this issue. 

Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
Approach: A detailed explanation with examples.

**Comment by kishlayaug15** [comment]
Name - Kishlay Kumar
Batch - 4
Serial No - 673
GithubLink :- https://github.com/kishlayaug15
Approach: A detailed explanation with Audio

**Comment by raina-akshay** [comment]
@ashish-reddy-20-08 @kishlayaug15 
already assigned issues.

**Comment by AdityaNikhil** [comment]
**Full name** : Aditya Nikhil
**Batch Number** : 2
**GitHub Profile Link** : github.com/adityanikhil
**Which type of Contribution you want to make** :
Video

**Comment by raina-akshay** [comment]
assigned to @AdityaNikhil

**Comment by abhisheks008** [comment]
@AdityaNikhil  What's the update on this issue ❓

**Comment by ShraddhaMeshram27** [comment]
Full name: Shraddha Meshram
Batch Number : 3
GitHub Profile Link: https://github.com/ShraddhaMeshram27
Which type of Contribution you want to make :
Video

Assign me this issue if Aditya is busy.

**Comment by AdityaNikhil** [comment]
@abhisheks008 
As I am currently busy with some other work, I request you please assign this to @ShraddhaMeshram27.

**Comment by raina-akshay** [comment]
@ShraddhaMeshram27 go for it 🎉
