### ISSUE TITLE
ML 7.3: LGBM (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#7008]
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_ LGBM_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Ensemble_based_Learning_&_Probabilistic_ML` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by khushali452** [comment]
Name- Khushali Vasani
Batch Number- 3
GitHub Link- https://github.com/khushali452
Type of contribution- Documentation

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
Profile link: https://github.com/priyall
Contribution type: Documentation
I would like to contribute to this issue.

**Comment by Isha307** [comment]
@khushali452 You cannot use this "assign" tag.

**Comment by khushali452** [comment]
@Isha307 Please Assign me this Documentation... I am having only 2 open issues and i assure you to submit it within 2-3 days

**Comment by khushali452** [comment]
> @khushali452 You cannot use this "assign" tag.

@Isha307 Okay ..my bad!

**Comment by raina-akshay** [comment]
happy contributing @khushali452
