### ISSUE TITLE
Can you please assign this task to me?

### ISSUE THREAD

**Issue by akratikushwah** [girlscript/winter-of-contributing#701]

**Comment by GyaniRoman23** [comment]
@akratikushwah Why are you spamming with ghost issues? Kindly refrain from this and I would request you to kindly remove these.

**Comment by GyaniRoman23** [comment]
@gauravdas014 Kindly look into this matter as it is providing a lot of unnecessary chaos.

**Comment by gauravdas014** [comment]
@GyaniRoman23 Thank you for letting me know about it. I will take necessary measures

**Comment by akratikushwah** [comment]
> would

I am really sorry I am not able to understand how to raise issue to let the task assigned to me
