### ISSUE TITLE
ML 7.4: XGBoost (A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#7013]
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_XGBoost_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Ensemble_based_Learning_&_Probabilistic_ML` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Shivangik01** [comment]
Name: Shivangi Kochrekar
Batch: 3
Github Link: https://github.com/Shivangik01
Type: Audio
I would like to contribute to this issue.

**Comment by Isha307** [comment]
@Shivangik01 Issue assigned to you 🚀

**Comment by abhisheks008** [comment]
@Shivangik01  What's the update on this issue ❓

**Comment by ShraddhaMeshram27** [comment]
Name: Shraddha Meshram
Batch: 3
Github Link: https://github.com/ShraddhaMeshram27
Type: Audio
I would like to contribute to this issue if Shivangi is busy

**Comment by Shivangik01** [comment]
I'm sorry for the delay. I'll raise a pr today.

**Comment by abhisheks008** [comment]
@Shivangik01 do it by EOD, otherwise this will be assigned to @ShraddhaMeshram27
