### ISSUE TITLE
ML 7.8 : Gaussian Mixture Models (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#7051]
### 📌  Issues for Week 7
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Gaussian Mixture Models_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/Ensemble_based_Learning_&_Probabilistic_ML` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by riyasai22** [comment]
I would like to contribute to this issue. @abhisheks008
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22
Contribution type: documentation

**Comment by riyasai22** [comment]
I would like to contribute to this issue. @abhisheks008
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22
Contribution type: documentation

**Comment by shrestharushika** [comment]
Name- Rushika Shrestha
Batch:1
Contribution type: documentation
Profile link: https://github.com/shrestharushika

**Comment by Isha307** [comment]
Issue assigned to you @riyasai22
