### ISSUE TITLE
[DSA]: Dynamic Programming - 0/1 Knapsack Problem in Java

### ISSUE THREAD

**Issue by singhmansi25** [girlscript/winter-of-contributing#7053]
### Description

**Description:** The issue deals with explanation of Dynamic Programming Problem- 0/1 Knapsack problem.
The documentation will contain- Problem statement, Approach to problem, Solution of Problem in Java, Backtracking.
Name - Mansi Singh
Batch - 3
Type - documentation

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by singhmansi25** [comment]
@ASLManasa 
U can't self assign yourself until supervisor assigns you

**Comment by ASLManasa** [comment]
okay

**Comment by ASLManasa** [comment]
@singhmansi25 can I get this issue assigned?

**Comment by singhmansi25** [comment]
I'm not supervisor. But I've asked them to assign me.
You can contribute as well
