### ISSUE TITLE
Introduction To CSS

### ISSUE THREAD

**Issue by samipak458** [girlscript/winter-of-contributing#7056]
### Description

- All about **CSS**
- Why **CSS** is so important?

### Domain

Frontend Dev HTML/CSS/JS

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by iam-sakshi** [comment]
can I work on this issue?
