### ISSUE TITLE
[Create New Issue]: Build Heap from Array

### ISSUE THREAD

**Issue by Pawanupadhyay10** [girlscript/winter-of-contributing#7081]
### Description

Description
Given an array of N elements. The task is to build a Binary Heap from the given array. The heap can be either Max Heap or Min Heap.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
Stale issue, so closing it.
