### ISSUE TITLE
DSA: Implement stack using queue.

### ISSUE THREAD

**Issue by jaissumi1402** [girlscript/winter-of-contributing#7085]
### Description

I will be creating a document on how to implement stack using queue.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by goelesha** [comment]
@jaissumi1402 Go ahead

**Comment by nimisha-yadav** [comment]
Stale issue, so closing it.
