### ISSUE TITLE
Python : Recursion in Python

### ISSUE THREAD

**Issue by dhruti29** [girlscript/winter-of-contributing#7120]
### Description

Explain about Recursion in Python.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by dhruti29** [comment]
@adityabisoi Can I work on this issue?

Please Assign me..!!!

**Comment by pragatikesarwani38** [comment]
I would like to contribute to this topic via documentation

**Comment by shaurya24sri** [comment]
@adityabisoi Can I work on this issue  ?
Contribution type-audio

**Comment by adityabisoi** [comment]
The topic is already covered in #4206
