### ISSUE TITLE
Python:What are errors and its types?

### ISSUE THREAD

**Issue by shaurya24sri** [girlscript/winter-of-contributing#713]
**Description:**
Explain What are Errors in Python and its types ?
@
**Note :**
Changes should be made inside the Python/ directory & Python branch.
Issue only for GWOC'21 contributors.
Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.
In the PR, keep this issue's title as your PR's title.

Must follow: Contributing  Guidelines  and Code of Conduct

**Comment by shaurya24sri** [comment]
I am Shaurya I want to work on the documentation part can you assign to me this issue@adityabisoi

**Comment by Pranav120602** [comment]
@adityabisoi , I am interested to contribute via doc or video. 
kindly assign it to me. 
Thanks and Regards, 
Pranav Shankar 
Python - Batch 6.

**Comment by adityabisoi** [comment]
> @adityabisoi , I am interested to contribute via doc or video.
> kindly assign it to me.
> Thanks and Regards,
> Pranav Shankar
> Python - Batch 6.

One issue at a time.

**Comment by shaurya24sri** [comment]
Thank you @adityabisoi for assigning me this .

**Comment by TakshakRamteke** [comment]
Hello @adityabisoi would love to work on this via **Documentation**, Would be great if you may assign this to me

**Comment by pragatikesarwani38** [comment]
@adityabisoi I would like to contribute to this via documentation or audio.

**Comment by adityabisoi** [comment]
> @adityabisoi I would like to contribute to this via documentation or audio.

Assigned for Audio

**Comment by Kalyani02072003** [comment]
@adityabisoi 
kindly assign it to me, i would like to work on its documentation part
I am a beginner to contribution but have intermediate python knowledge 
batch- 5 python 
discord - STRAWHAT_LUFFY#8651

**Comment by jhanvee-khola** [comment]
@adityabisoi , I am interested to contribute via audio or video.
kindly assign it to me.
Thanks
Jhanvee Khola
Python - Batch 4

**Comment by khushipunia21** [comment]
@adityabisoi I am interested to work on this issue.
Name: Khushi Punia
batch: python 6
Type: Audio/Video

**Comment by Praannjaal** [comment]
@adityabisoi I would like to work on this issue
Name: Pranjal mittal
Batch:3
github: [https://github.com/Praannjaal](url)
Type: Documentation

**Comment by adityabisoi** [comment]
@Randrita Is the mentor for this issue. Please reach out to her in case of queries.

**Comment by priyanshinaredi** [comment]
@adityabisoi 
Sir I would like to contribute to this issue
Name: Priyanshi Naredi
batch: 2
Type: Documentation

**Comment by shaurya24sri** [comment]
@Randrita .Please Review my PR https://github.com/girlscript/winter-of-contributing/pull/3992

**Comment by khushipunia21** [comment]
@Randrita Please Review my PR#4323
