### ISSUE TITLE
DSA 4.1.2 Implementation of Stacks - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7136]
## Description
Discuss in detail the implementation of Stacks in Java, Python, and C++

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [ ] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ShraddhaMeshram27** [comment]
I'm Shraddha Meshram
Not from  any DSA branch 
Can i get this issue?

**Comment by Bhavika2210** [comment]
@nimisha-yadav 
Hello there, Im Bhavika Sachdeva, from DSA batch-6
Issue #7136
Can i Please work on the audio for Stack Operations in C++
I really wish to contribute

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav Hello there, Im Bhavika Sachdeva, from DSA batch-6 Issue #7136 Can i Please work on the audio for Stack Operations in C++ I really wish to contribute

Go ahead @Bhavika2210

**Comment by Bhavika2210** [comment]
> > @nimisha-yadav Hello there, Im Bhavika Sachdeva, from DSA batch-6 Issue #7136 Can i Please work on the audio for Stack Operations in C++ I really wish to contribute
> 
> Go ahead @Bhavika2210

Thanks Nimisha for the opportunity 
Here is the drive link for the audio of implementing stack operations: #7136 
https://drive.google.com/file/d/13yzAlbHWTFA1XCOyox62Xyh9duimNXhC/view?usp=sharing

**Comment by Bhavika2210** [comment]
kindly review the audio 
thanks
