### ISSUE TITLE
DSA 4.1.7 Implement Stack using Priority Queue or Heap - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7137]
## Description
Discuss in detail the implementation of Stacks using Priority Queue or Heap.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by maneet057** [comment]
Please assign me this one
Maneet kaur 
DSA batch 1

**Comment by jaigora24** [comment]
@nimisha-yadav mam plz assign this issue to me
Jai Gora
Batch - 7

**Comment by jaigora24** [comment]
@nimisha-yadav mam plz review
