### ISSUE TITLE
DSA 4.1.7 Implement Stack using Priority Queue or Heap - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7138]
## Description
Discuss in detail the implementation of Stacks using Priority Queue or Heap.

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [ ] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by jaigora24** [comment]
@nimisha-yadav mam assign audio part to me
Name - Jai Gora
Batch - 7
