### ISSUE TITLE
DSA 4.1.11.1 Stacks: Infix to Prefix - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7139]
## Description
How to convert infix expressions to prefix? Show examples and implementation.

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [ ] Audio
- [x] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by harshithatnbr** [comment]
@nimisha-yadav
  I would like to work on this issue in **video format**. Please assign me this issue.
 Thankyou!
Name : Harshitha
Batch: DSA batch-3

**Comment by priyashajain** [comment]
Name- Priyasha Jain
Batch - DSA-7
I would like to work on this issue in audio format. Please assign this issue to me. 
Thank you!

**Comment by priyashajain** [comment]
Hi! Can u please open this issue again? I had prepared material but I contributed in the wrong method before.

**Comment by priyashajain** [comment]
Thank you so much!!
