### ISSUE TITLE
DSA 4.1.11.1 Stacks: Infix to Prefix - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7140]
## Description
How to convert infix expressions to prefix? Show examples and implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by SUKHJIT-CYBER** [comment]
Hey Please assign this to me 
SUKHJIT SINGH
Batch 8

**Comment by nimisha-yadav** [comment]
@SUKHJIT-CYBER PR updates?

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav mam if this issue is pending plz assign to me Name - Jai Gora Batch - 7

Go ahead @jaigora24
