### ISSUE TITLE
DSA 4.1.11.2 Stacks: Infix to Postfix - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7141]
## Description
How to convert infix expressions to postfix? Show examples and implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by motasimmakki** [comment]
I'm Interested in this also.
Motasim (DSA Batch - 01)

**Comment by maneet057** [comment]
Please assign me this one, I was looking for such topics i can explain well. 
Maneet kaur 
DSA batch 1

**Comment by maneet057** [comment]
I am done with this one please review it
