### ISSUE TITLE
DSA 4.1.11.2 Stacks: Infix to Postfix - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7142]
## Description
How to convert infix expressions to postfix? Show examples and implementation.

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [x] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by afreenabegum** [comment]
@nimisha-yadav mam
please assign me this issue. I would like to contribute through Audio.

Afreena begum
DSA Batch1.
