### ISSUE TITLE
DSA 4.1.16 Stacks: Iterative Tower of Hanoi - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7143]
## Description
How do you implement the Tower of Hanoi problem using Stacks?

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by nisha855** [comment]
Nisha Tirkey
Batch No.-6
Hey @nimisha-yadav , I would like to work on this issue.

**Comment by PVenkatArvind** [comment]
pls assign

**Comment by kalyanirb12** [comment]
can I work on this issue? please assign it to me.
batch=6
kalyani rajebhosale

**Comment by maneet057** [comment]
Can I please work on this topic ?
Maneet kaur 
DSA batch 1
