### ISSUE TITLE
DSA 4.1.16 Stacks: Iterative Tower of Hanoi - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7144]
## Description
How do you implement the Tower of Hanoi problem using Stacks?

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [ ] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by PVenkatArvind** [comment]
please assign
