### ISSUE TITLE
DSA 4.2.5.1 Priority Queue - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7151]
## Description
What is Priority Queue? Discuss in detail its implementation.

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [x] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by jaigora24** [comment]
@nimisha-yadav mam assign audio to me
Name :- Jai Gora
Batch - 7
