### ISSUE TITLE
DSA 4.2.5.1 Priority Queue - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7152]
## Description
What is Priority Queue? Discuss in detail its implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
I would like to work on this issue (documentation).
batch - 2
Dhruti Gandhi
