### ISSUE TITLE
DSA 4.2.5.2 Deque - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7153]
## Description
What is Deque? Discuss in detail its implementation.

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [x] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by afreenabegum** [comment]
Hi mam @nimisha-yadav 
Please assign me this issue. I would like to contribute through Audio.

Afreena begum
DSA Batch-1.

**Comment by afreenabegum** [comment]
Hi Mam @nimisha-yadav 
I can submit this PR by wednesday. May I know if you can re-open this issue? 

It would be helpful if you can re-open this issue. So that I will be completing 5 PR's in this program. 

Thank u. 
Afreena begum

**Comment by nimisha-yadav** [comment]
> Hi Mam @nimisha-yadav I can submit this PR by wednesday. May I know if you can re-open this issue?
> 
> It would be helpful if you can re-open this issue. So that I will be completing 5 PR's in this program.
> 
> Thank u. Afreena begum

Sure @afreenabegum, I am reopening but please try to submit the PR by the deadline which is today midnight. All the best.

**Comment by afreenabegum** [comment]
> > Hi Mam @nimisha-yadav I can submit this PR by wednesday. May I know if you can re-open this issue?
> > 
> > It would be helpful if you can re-open this issue. So that I will be completing 5 PR's in this program.
> > 
> > Thank u. Afreena begum
> 
> Sure @afreenabegum, I am reopening but please try to submit the PR by the deadline which is today midnight. All the best.

Ok mam. 
Thank you
