### ISSUE TITLE
DSA 4.2.5.2 Deque - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7154]
## Description
What is Deque? Discuss in detail its implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
I would like to work on this issue (documentation).
batch - 2
Dhruti Gandhi

**Comment by dhruti29** [comment]
I would like to work on this issue (documentation).
batch - 2
Dhruti Gandhi

**Comment by Pawanupadhyay10** [comment]
I would like to work on this issue (documentation).
batch - 4
Pawan upadhyay

**Comment by divya1467** [comment]
Can I work on the documentation part?
Divya(batch-5)

**Comment by kalyanirb12** [comment]
kalyani rajebhosale
batch=6
can I work on this documentation part?

**Comment by jaigora24** [comment]
@nimisha-yadav mam please assign this to me
Name :- Jai Gora
Batch :- 7
