### ISSUE TITLE
DSA 4.2.5.3 Circular Queue - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7157]
## Description
What is Circular Queue? Discuss in detail its implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by motasimmakki** [comment]
Kindly Assign it to me!
Motasim (DSA Batch -01)

**Comment by Pawanupadhyay10** [comment]
Kindly Assign it to me!
Pawan upadhyay  (DSA Batch -04)
