### ISSUE TITLE
DSA 4.2.6 LIFO vs FIFO Approach - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7158]
## Description
Discuss in detail the LIFO vs FIFO approach - their pros/cons, examples, and implementation.

Two contributors may take up this issue depending on Audio or Video format.

## Task
- [x] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by jaigora24** [comment]
@nimisha-yadav plz assign this to me for audio part
Jai Gora
Batch - 7
