### ISSUE TITLE
DSA 4.2.6 LIFO vs FIFO Approach - Documentation

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7159]
## Description
Discuss in detail the LIFO vs FIFO approach - their pros/cons, examples, and implementation.

## Task
- [ ] Documentation

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by dhruti29** [comment]
@nimisha-yadav  I would like to work on this issue (documentation).
batch - 2
Dhruti Gandhi

**Comment by Pawanupadhyay10** [comment]
I would like to work on this issue (documentation).
batch - 4
Pawan upadhyay

**Comment by nimisha-yadav** [comment]
@Pawanupadhyay10 It's fine for this time but please read the instructions and don't use command for such issues.

Also @dhruti29, we're assigning only one doc issue at a time to give chance to new people so if you'd like to contribute to more issues, feel free to take up the audio/video ones or create your own based on standard problems.

**Comment by kalyanirb12** [comment]
kalyani rajebhosale
batch=6
can I work on the documentation part?
