### ISSUE TITLE
DSA 4.3.4 Boyer Moore Algorithm - Audio/Video

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7161]
## Description
Discuss in detail the Boyer Moore Algorithm.

Two contributors may take up this issue depending on Audio or Video format.
## Task
- [ ] Video
- [ ] Audio

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by Elisha-s** [comment]
Please assign the audio part of this issue to me 
Elisha Singh
DSA- Batch 9

**Comment by nimisha-yadav** [comment]
@Elisha-s you may try for some of these documentation topics as well by creating issue on your own.
1. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/08.%20Fitting%20Shelves%20Problem
2. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/07.%20Minimum%20Swaps%20for%20Bracket%20Balancing
3. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/11.%20Boruvka's%20Minimum%20Spanning%20Tree
4. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/19.%20Standard%20Array%20Greedy%20Algorithms
