### ISSUE TITLE
4.1.9.1-Stack: Sort a stack -documentation

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#7164]
## Description
write an algorithm to sort a stack

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

 Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by uzma024** [comment]
I would like to work on this issue.
Uzma Firoz Khan
batch 10 
DSA
Documentation

**Comment by priyanka001tech** [comment]
I want to do it in documentation.

**Comment by uzma024** [comment]
> /assign

@priyanka001tech self assign is not allowed.
@Muskan-creator Please look into the matter.

**Comment by priyanka001tech** [comment]
> > /assign
> 
> @priyanka001tech self assign is not allowed. @Muskan-creator Please look into the matter.

But there is written that "To get assigned to this particular issue please use /assign"

**Comment by uzma024** [comment]
> > > /assign
> > 
> > 
> > @priyanka001tech self assign is not allowed. @Muskan-creator Please look into the matter.
> 
> But there is written that "To get assigned to this particular issue please use /assign"

You must be new. It's not allowed to self assign (unless you opened the issue ofc). Kindly remove your assignment. Mentor assign people manually.

**Comment by Muskan-creator** [comment]
@priyanka001tech Self assigning on issues are not allowed.Please look for some other open issue

**Comment by uzma024** [comment]
@Muskan-creator Kindly review and merge my pr :)

**Comment by uzma024** [comment]
@Muskan-creator Kindly review this issue.

https://github.com/girlscript/winter-of-contributing/pull/7959#issue-1054875856
