### ISSUE TITLE
4.1.8.3 -Reverse a stack using recursion -Audio

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#7166]
## Description
Give an algorithm to reverse a stack using recursion in audio format.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

### Domain

DSA

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by kanthalaHarivardhanReddy** [comment]
@Muskan-creator 
Assign me the documentation part of this issue
Name Harivardhan 
Batch 1

**Comment by A-nn-e** [comment]
Anmol Jha, DSA: Batch 5

/assign

**Comment by A-nn-e** [comment]
> Anmol Jha, DSA: Batch 5

/assign
