### ISSUE TITLE
Binary Search in Python 

### ISSUE THREAD

**Issue by Vishaka830** [girlscript/winter-of-contributing#7182]
### Description

I want to contribute a video tutorial on binary search in the Python language. I'll discuss the binary search algorithm and how it can be implemented recursively and iteratively in Python.

### Domain

Python_Domain

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Vishaka830** [comment]
@adityabisoi sir can I work on this topic? I've completed all my previous issues.

**Comment by shaurya24sri** [comment]
@adityabisoi Can I work on this issue -
contribution type :-documentation

**Comment by adityabisoi** [comment]
This issue is a ds-algo based one. Closing this issue.
