### ISSUE TITLE
Python: Bubble sort

### ISSUE THREAD

**Issue by Vibhu562** [girlscript/winter-of-contributing#7204]
### Description

What is bubble sort in Python.
Explain it by giving suitable example.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Vibhu562** [comment]
@adityabisoi can i work on my issue

**Comment by rachita11** [comment]
Name: C.Rachita
Contribution type: Video
@adityabisoi

**Comment by shaurya24sri** [comment]
@adityabisoi Can I contribute in Audio format

**Comment by adityabisoi** [comment]
Topic is a part of ds-algo domain.
