### ISSUE TITLE
 Decorators

### ISSUE THREAD

**Issue by shaurya24sri** [girlscript/winter-of-contributing#7233]
### Description

Decorators

### Domain

Python_Domain

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shaurya24sri** [comment]
@adityabisoi Can you assign me this issue 
Contribution type-audio

**Comment by shaurya24sri** [comment]
@adityabisoi Can you assign me this issue 
Contribution type-audio

**Comment by adityabisoi** [comment]
Already covered in #576
