### ISSUE TITLE
Advanced_function_lambda()

### ISSUE THREAD

**Issue by shaurya24sri** [girlscript/winter-of-contributing#7235]
### Description

What is Lambda Function in python?

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shaurya24sri** [comment]
@adityabisoi Please assign me this issue.
Contribution type-Documentation

**Comment by shaurya24sri** [comment]
@adityabisoi I have completed all other issues and my pr is also merged.
Please assign me this issue

**Comment by kalyanirb12** [comment]
can I contribute to this issue.

**Comment by shaurya24sri** [comment]
@adityabisoi Can I start working on this issue?

**Comment by adityabisoi** [comment]
Issue already covered
