### ISSUE TITLE
Cybersecurity: 2.2 Mac address

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#724]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by I-Infinatoo** [comment]
Can I do the documentation part ?

**Comment by Anant1711** [comment]
> Can I do the documentation part ?

Go with it! `Documentation`
