### ISSUE TITLE
Perfect Guess Game

### ISSUE THREAD

**Issue by yashh18** [girlscript/winter-of-contributing#7243]
### Description

This is a game that generates a random number and asks us to guess it. It takes input from the user and tells that the generated number is smaller or larger than the input number and records the number of guesses and stores it in a "highscore.txt" file till we get the correct answer.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by yashh18** [comment]
@adityabisoi please assign me this issue 
content type - documentation

**Comment by adityabisoi** [comment]
Make an `Examples` folder and place your contributions in it.
