### ISSUE TITLE
13.03 Use of Shimmer Library in Android

### ISSUE THREAD

**Issue by anisha-01-phoenix** [girlscript/winter-of-contributing#7248]
### Description

Implementation and Use of Android Content Placeholder Animation like Facebook using Shimmer

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sitamadex11** [comment]
@anisha-01-phoenix please change the issue title from `Use of Shimmer Library in Android` to `13.03 Use of Shimmer Library in Android`
