### ISSUE TITLE
Cybersecurity: 2.3 IP address v/s MAC address

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#725]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by 0shivamh** [comment]
I would like to work on this

**Comment by 0shivamh** [comment]
> I would like to work on this

for doc

**Comment by Anant1711** [comment]
> > I would like to work on this
> 
> for doc

Okay!
Go with it!
