### ISSUE TITLE
Android Java: 13.04 TextView fading animation Android Studio

### ISSUE THREAD

**Issue by prince02765** [girlscript/winter-of-contributing#7255]
### Description

How to Create Fading TextView Animation Android Studio (Java)

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by sitamadex11** [comment]
@prince02765 please change the issue title from `Android Java: 13.02 TextView fading animation Android Studio` to `Android Java: 13.04 TextView fading animation Android Studio`
