### ISSUE TITLE
Cybersecurity: 2.4 TCP

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#726]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by iamKushGupta** [comment]
Can this issue be assigned to me ?

**Comment by Anant1711** [comment]
> Can this issue be assigned to me ?

Wait until your previous work is merged!

**Comment by artishukla1** [comment]
Can I work on this topic?

**Comment by Anant1711** [comment]
> Can I work on this topic for documentation?

Go with it!

**Comment by artishukla1** [comment]
Thanks @Anant1711

**Comment by artishukla1** [comment]
Yes, it is completed. I will submit it tomorrow.
