### ISSUE TITLE
Frontend with frameworks: Angular:Sharing data between parent and child components in Angular

### ISSUE THREAD

**Issue by the-pro** [girlscript/winter-of-contributing#729]
### Required Content

- Sending data to a child component
- Sending data to a parent component
- Using @Input() and @Output() together

Link to get started: https://angular.io/guide/inputs-outputs

### Rules to follow
- Do NOT copy/paste
- Do not push to the main branch
- Specify the issue you are working on the PR
- Do not remove previous content

**Comment by RIYANSHGARG** [comment]
I would like to work on this issue kindly assign it to me.

**Comment by the-pro** [comment]
Sure @RIYANSHGARG Go ahead!

**Comment by RIYANSHGARG** [comment]
I have added the pull request please consider it.

**Comment by RIYANSHGARG** [comment]
I have added the pull request please consider it
