### ISSUE TITLE
DSA 4.1.10.1 Postfix to Infix

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#7299]
## Description
Give an introduction and explain the working of an algorithm for converting postfix expression to infix.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by thatSophisticatedMess18** [comment]
/assign documentation
Diksha Gupta
Batch - 2

**Comment by afreenabegum** [comment]
Hi sir @pjdurden 
Please assign me this issue. I would like to contribute through Audio.

Afreena begum
DSA Batch-1.

**Comment by thatSophisticatedMess18** [comment]
@pjdurden please assign the documentation part of this issue to me
