### ISSUE TITLE
Data Science with Python : Introduction to Pytorch

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#730]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Pytorch. Tutorial to Pytorch and how it's applied using sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Arya Patel](https://www.github.com/AryaPatel1111) / [Aishani Singh](https://github.com/aishanii)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by KTK-5901** [comment]
I would like to work on this issue
Name: Kartikey Gupta
Serial No. 552
Type: Documentation
Approach:
Introduction to PyTorch
Explanation with examples of some functions present in PyTorch

**Comment by prathimacode-hub** [comment]
Issue is assigned to @KTK-5901 for documentation.

**Comment by mahmoudmohamed22** [comment]
I would be glad to work on this issue.
Name : mahmoud mohamed abdelwahab
Batch : 3
serial number:91
Type : video
Approach:
Introduction to PyTorch
Explanation with examples of some functions present in PyTorch

**Comment by prathimacode-hub** [comment]
Issue assigned to @mahmoudmohamed22 for documentation

**Comment by aishanii** [comment]
I'm the mentor for this issue, please add me as assignee

**Comment by aishanii** [comment]
@prathimacode-hub please add me as assignee

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do AUDIO on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for audio contribution
