### ISSUE TITLE
DSA 4.1.13 The Celebrity Problem

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#7302]
## Description
Give an introduction and explain the working of an algorithm to solve the celebrity problem.
The statement for the problem can be summed up by this statement - "We can describe the problem input as an array of numbers/characters representing persons in the party. We also have a hypothetical function HaveAcquaintance(A, B) which returns true if A knows B, false otherwise."
You can consult this link for more information - "https://www.geeksforgeeks.org/the-celebrity-problem/"

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ayushjha952** [comment]
Hi @pjdurden can you assign me this issue I would like to work on the documentation part .
Ayush Jha
DSA Batch 3
