### ISSUE TITLE
DSA 4.3.7 Z Algorithm

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#7307]
## Description
Give an introduction and explain the working of Z Algorithm. 
Further information about this algorithm can be found in the link given below.
https://www.hackerearth.com/practice/algorithms/string-algorithm/z-algorithm/tutorial/

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ParagD25** [comment]
@goelesha can you assign me this issue?

**Comment by goelesha** [comment]
@ParagD25 The issue is created by @pjdurden . He will guide you further
