### ISSUE TITLE
DSA 4.3.8 Suffix Tree (Ukkonen’s algorithm )

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#7308]
## Description
Give an introduction and explain the working of Suffix Tree and also explain the Ukkonen's Algorithms for suffix tree construction.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by ParagD25** [comment]
@goelesha can you assign me this issue?

**Comment by dhruti29** [comment]
@pjdurden can I work on this issue...?
DSA-2
