### ISSUE TITLE
Python : Numpy

### ISSUE THREAD

**Issue by yashh18** [girlscript/winter-of-contributing#7313]
### Description

Covering the necessary information about the use of numpy in python 
Type : Documentation

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by yashh18** [comment]
@adityabisoi please assign me this issue

**Comment by roopali-1** [comment]
@adityabisoi is this issue open for audio ??? if yes then do assign it to me.
I would like to work on this issue as audio contri

**Comment by Ajinkyap331** [comment]
@adityabisoi am I good to continue with his

**Comment by adityabisoi** [comment]
Topic is already covered
