### ISSUE TITLE
Advanced_function_filter()

### ISSUE THREAD

**Issue by shaurya24sri** [girlscript/winter-of-contributing#7329]
### Description

What is Advanced_function_filter()?

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shaurya24sri** [comment]
@adityabisoi Can i start working on this issue

**Comment by adityabisoi** [comment]
Please check for existing issues before making them. This topic is already covered.

**Comment by shaurya24sri** [comment]
this issue is not covered as documentation .Please assign me this issue..This issue has covered only in video  @adityabisoi

**Comment by adityabisoi** [comment]
If it is, you have to comment there, instead of creating a new one.
