### ISSUE TITLE
Data Science with Python : Titanic Survival Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#7337]
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know to use machine learning to create a model that predicts which passengers survived the Titanic shipwreck

Here is the dataset to follow :  https://www.kaggle.com/c/titanic/data

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Kaggle Competitions

Mentors Assigned : Dhruv Bajaj | Kareem Negm

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by theshredbox** [comment]
I would like to take this issue.
Name- Aryan Ahuja
Serial No. 117
Type- Documentation
Approach- creating a machine learning model that provides information on the fate of passengers on the Titanic, summarized according to economic status (class), sex, age and survival.

**Comment by prathimacode-hub** [comment]
Issue assigned to @theshredbox for documentation

**Comment by SaloniThete** [comment]
Name: saloni Thete
Sr. No: 821
Type : video
Approach : Detailed explanation of Titanic survival including jupyter notebook using a machine learning model.
@prathimacode-hub, kindly assign
/assign

**Comment by pankaj-sawnani** [comment]
I would like to work on this topic.
Pankaj Sawnani - 936
Batch - 21
Issue No - #7337
Type: Video

**Comment by pankaj-sawnani** [comment]
@prathimacode-hub 👆👆

**Comment by prathimacode-hub** [comment]
Are you sure, you can complete it. Already issues are assigned to you? @pankaj-sawnani

**Comment by prathimacode-hub** [comment]
Ok sure, Issue assigned to @pankaj-sawnani for video contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution

**Comment by pankaj-sawnani** [comment]
Hello, @prathimacode-hub Kindly review my pr.
