### ISSUE TITLE
Data Science with Python : Complete Overview of Regression

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#735]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Regression. Tutorial to Regression and how it's applied using visual representations and sample code, techniques you can follow up with regression and it's usage.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Machine Learning

Mentors Assigned : [Yash Goel](https://github.com/Yash621) / [Kareem Negm](https://github.com/Kareem-negm)

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by yashh18** [comment]
Yash Kataria (Serial no - 861)
Approach : What is Regression, evaluating regression, linear regression(in detail), polynomial regression
Type : Documentation

**Comment by prathimacode-hub** [comment]
Issue assigned to @yashh18 for documentation

**Comment by ProMinato500** [comment]
I want to apply for video.
Name - Pradipta Nandi

**Comment by ProMinato500** [comment]
I want to contribute in issue #735
Name - Pradipta Nandi
S.No. - 250
Type - Video
Approach - Introduction to Regression, Linear Regression, Polynomial Regression, Classification Regression

**Comment by prathimacode-hub** [comment]
Issue assigned to @ProMinato500 for video contribution

**Comment by m0hit-kumar** [comment]
name : Mohit Kumar
Approach: What is Regression, evaluating regression, linear regression(in detail), polynomial regression
Type : Documentation

**Comment by prathimacode-hub** [comment]
@m0hit-kumar, issue is assigned to documentation, video. If you are ok, you can take audio.

**Comment by m0hit-kumar** [comment]
i want to contribute only for documentation, if its already assigned why there is a label of documentation.

**Comment by Kareem-negm** [comment]
Hello, the mentor here for any help

**Comment by BhaswatiRoy** [comment]
I want to contribute to this issue :                 
Name-Bhaswati Roy   
Domain-Data Science with Python 
Batch-19  
Serial No-787 
Issue Number-735
Type-Audio
Contribution Approaches-what is regression, types of regression like linear, multiple, polynomial, lasso ridge, why logistic regression is called regression

**Comment by Rishika-12** [comment]
I want to contribute in this issue under documentation.

**Comment by prathimacode-hub** [comment]
> i want to contribute only for documentation, if its already assigned why there is a label of documentation.

Labels are tagged for issues that are been assigned to. @m0hit-kumar

**Comment by prathimacode-hub** [comment]
@BhaswatiRoy, you want to work for audio contribution?

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy, you want to work for audio contribution?

Sorry maam but I am already working on multiple issues rn....

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
