### ISSUE TITLE
Cybersecurity: 2.5 UDP

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#736]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by prithwishpramanik** [comment]
sir i want to do the documentation part

**Comment by Anant1711** [comment]
> sir i want to do the documentation part

Okay!
Assigned

**Comment by SwarnaliBhunia** [comment]
I want to take up the vedio contribution part

**Comment by Anant1711** [comment]
> I want to take up the vedio contribution part

Okay, 
I'm assigning this task to you!

**Comment by SwarnaliBhunia** [comment]
thank you
