### ISSUE TITLE
Cybersecurity: 2.6 3-Way handshake

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#737]
## Note:
- This task is only for `Video` submission.
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security` branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by Anant1711** [comment]
Mr. @Ayush7614 this is my last and humble request to you!
Do not create mess everywhere, I saw you reviewing my domain PRs also.
and now You are adding your domain tags to other domains!
So please, If you have any doubt about tags and all you can contact me, but without knowing anything don't do this!
PLEASE!

**Comment by Ayush7614** [comment]
Okk sorry from side

**Comment by iamKushGupta** [comment]
Can I be assigned this ??

**Comment by Anant1711** [comment]
> Can I be assigned this ??



> Can I be assigned this ??



> Can I be assigned this ??

You have to submit your previous work first!

**Comment by RK1905101** [comment]
Can I contribute in this, for documentation part!?

**Comment by Sukriti-sood** [comment]
can i take up the issue

**Comment by Anant1711** [comment]
> can i take up the issue

Great!
I'm assigning this to you!

**Comment by HumblePlebeian** [comment]
Could you please assign this issue to me?

**Comment by IshikaMeghaSaha** [comment]
Can I be assigned this?

**Comment by Anant1711** [comment]
> Can I be assigned this?

Okay!
I'm assigning this task to you for `Video` submission!

**Comment by Anant1711** [comment]
@IshikaMeghaSaha 
Any update?
Please submit your Work!
you took 5 days.

**Comment by IshikaMeghaSaha** [comment]
Yes I'm working on it. Will submit it by tuesday.

**Comment by Anant1711** [comment]
> Yes I'm working on it. Will submit it by tuesday.

Okay submit it by Tuesday please!
