### ISSUE TITLE
BAR CHART USING ARRAY IN C

### ISSUE THREAD

**Issue by ANUSHKA-AARYA** [girlscript/winter-of-contributing#7374]
### Description

In this documentation ,I will explain about making a bar chart  for comparing populations in different countries using arrays and '*' operator in c language.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Saviour1001** [comment]
Closing this issue as #7384 got merged !!
