### ISSUE TITLE
Cybersecurity: 2.7 Common ports and protocols

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#739]
## Note:
- If interested, Mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security`/ directory & `Cyber_Security` branch.
- Task will be assigned on **first come first serve**
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by kar-cloud** [comment]
I would like to do this in documentation form

**Comment by Anant1711** [comment]
> I would like to do this in documentation form

GO with it!
