### ISSUE TITLE
Floyd's Algorithm

### ISSUE THREAD

**Issue by shaurya24sri** [girlscript/winter-of-contributing#7422]
### Description

Floyd's Algorithm

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shaurya24sri** [comment]
@adityabisoi please assign me this issue

**Comment by adityabisoi** [comment]
This is a algo-based topic, closing the issue
