### ISSUE TITLE
Python:List Method

### ISSUE THREAD

**Issue by shaurya24sri** [girlscript/winter-of-contributing#7423]
### Description

List Method

### Domain

Python_Domain

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shaurya24sri** [comment]
@adityabisoi Please assign me this issue

**Comment by adityabisoi** [comment]
This topic is already covered. Closing this issue
