### ISSUE TITLE
Data Science with Python : Data Visualization with Seaborn

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#744]
Welcome to 'DSWP' Team, good to see you here

This issue will helps readers in acquiring all the knowledge to learn about getting involved with Data Visualization with Seaborn. Tutorial to Data Visualization with Seaborn and how it's applied using visual representations and sample code.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

This issue is created for beginners and who aren't assigned to any issues yet.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain : Data Analysis and Visualization

Mentors Assigned : Gauri Bharadwaj / Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your open source journey ahead. 😎

**Comment by prishita-s** [comment]
I would like to work on this issue
Serial number in excel sheet: 721
Mode: Documention 
Approach: Intro to seaborn. Different plots for visualization of data in the seaborn library.

**Comment by vanshika230** [comment]
I would like to work on this.
Vanshika Mishra
Batch - 5
Type: Documentation
Approach:
1 Working with tips data set
2 Barplot, countplot, boxplot,violin plot
3 distplot , kdeplot, joinplot, pairplot
4 Correlation and heatmaps

**Comment by prathimacode-hub** [comment]
@vanshika230 @prishita-s these issues are created from request of contributors. If you have not been assigned to any issue, and want to work on issues you're interested. You can check out with the thread created in discord channel to know the process and also watch out with pinned messages.

**Comment by Vidit-Ostwal** [comment]
@prathimacode-hub Kindly assign to that particular contributors,
 having an issue not assigned to someone seems somewhat illogical

**Comment by ProMinato500** [comment]
I want to contribute to documentation to issue #744.
Name - Pradipta Nandi

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Kindly assign to that particular contributors,
> having an issue not assigned to someone seems somewhat illogical

Yes true. I agree. I will make sure to assign it soon. @Vidit-Ostwal

**Comment by prathimacode-hub** [comment]
> I want to contribute to documentation to issue #744.
> Name - Pradipta Nandi

If you're in for Audio/Video let me know. Documentation is already assigned.

**Comment by mahmoudmohamed22** [comment]
I would like to work on this.
name :mahmoud mohamed abdelwahab
number in sheet :91
Batch :3
Issue Number - #744
Type: Documentation
Approach:
1-Seaborn Versus Matplotlib
2-Exploring Seaborn Plots

**Comment by prathimacode-hub** [comment]
@mahmoudmohamed22, issue is assigned to you for documentation.

**Comment by prathimacode-hub** [comment]
Since this is a repetitive issue, it's closed.
