### ISSUE TITLE
ML 8.2 : LSTM(A)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#7476]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_LSTM_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Seqential_Data_&_Visual_Data` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Audio

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Audio

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by jahnvishah** [comment]
Name: Jahnvi Shah
Batch: 5
Github Link: https://github.com/jahnvishah
Type: Documentation
I would like to contribute to this issue.

**Comment by hrugved06** [comment]
- Name: Hrugved Kolhe
- Batch: 3
- [GitHub Profile](https://github.com/hrugved06)
-  [x]  Documentation
Interested

**Comment by abhisheks008** [comment]
What's your progress here @jahnvishah

**Comment by abhisheks008** [comment]
What's your Progress here @jahnvishah

**Comment by Shivangik01** [comment]
Name: Shivangi Kochrekar
Batch: 3
Github Link: https://github.com/Shivangik01
Type: Audio
I would like to contribute to this issue if Jahnvi is busy.

**Comment by Isha307** [comment]
@Shivangik01 This issue is already assigned to @jahnvishah

**Comment by abhisheks008** [comment]
What's the progress here @jahnvishah

**Comment by jahnvishah** [comment]
Due some unforseen circumstances I won't be able to generate the PR.

**Comment by abhisheks008** [comment]
@Shivangik01 would you like to take up this issue?

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do audio on this issue.my approach: a detailed explanation

**Comment by Shivangik01** [comment]
> @Shivangik01 would you like to take up this issue?

Yes

**Comment by abhisheks008** [comment]
@Shivangik01 issue assigned to you, complete this within 3 days.
