### ISSUE TITLE
ML 8.12 : What is Object Detection and RCNN (D)

### ISSUE THREAD

**Issue by raina-akshay** [girlscript/winter-of-contributing#7480]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_What is Object Detection and RCNN_**

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Sequential_Data_&_Visual Data' Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Yugal41735** [comment]
Yugal Agarwal
Batch - 1
https://github.com/Yugal41735
Documentation

**Comment by purvanshgarg** [comment]
Name:Purvansh Garg
Batch 2
https://github.com/purvanshgarg
Documentation

**Comment by VidhiBhatt01** [comment]
Please assign this issue to me.
Name: Vidhi Bhatt
Domain: ML Batch 3
Serial no: 490
Github link: https://github.com/VidhiBhatt01
Documentation

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
plz assign to me.

**Comment by Mann-tech13** [comment]
Please assign this issue to me.
Name: Mann Shah
Domain: ML Batch 3
Github link: https://github.com/Mann-tech13
Documentation

**Comment by raina-akshay** [comment]
to @Yugal41735

**Comment by abhisheks008** [comment]
What's your progress here @Yugal41735

**Comment by Yugal41735** [comment]
Working on it

**Comment by abhisheks008** [comment]
What's your progress here @Yugal41735

**Comment by Yugal41735** [comment]
till sunday I would be able to make pr.

**Comment by abhisheks008** [comment]
Today is the last date of pushing your PR, do it by EOD @Yugal41735

**Comment by VidhiBhatt01** [comment]
I would like to work on this, please assign if possible @abhisheks008

**Comment by Yugal41735** [comment]
Just some editing is left I will make pr by today for sure.

**Comment by Yugal41735** [comment]
Hello, I am trying to implement RCNN in my documentation to kind of giving an example of how RCNN works, so actually training is taking a little bit time and as sson as the training finishes i will make the pr 
<img width="370" alt="Screenshot 2021-11-15 231010" src="https://user-images.githubusercontent.com/74638775/141828893-58ad5c91-fbea-422c-a266-cfbb11f363cf.png">

**Comment by Yugal41735** [comment]
@raina-akshay @abhisheks008  could u plz review the pr. Thanks. Again sorry for the late pr.
