### ISSUE TITLE
ML 8.13 : YOLO (D)

### ISSUE THREAD

**Issue by raina-akshay** [girlscript/winter-of-contributing#7490]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_You Only Look Once_**

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Sequential_Data_&_Visual Data' Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Yugal41735** [comment]
Yugal Agarwal
Batch - 1
https://github.com/Yugal41735
Documentation

**Comment by vanshhhhh** [comment]
Please assign this issue to me.
Name: Vansh Sharma
Domain: ML Batch 3
Github link: https://github.com/vanshhhhh

**Comment by Mann-tech13** [comment]
Name: Mann Shah
Batch: ML Batch 3
GitHub: https://github.com/Mann-tech13
Documentation

**Comment by VidhiBhatt01** [comment]
Please assign this issue to me.
Name: Vidhi Bhatt
Domain: ML Batch 3
Serial no: 490
Github link: https://github.com/VidhiBhatt01
Documentation

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
Profile link: https://github.com/priyall
Contribution type: Documentation
I would like to contribute to this issue.

**Comment by Ruchika-20** [comment]
Please assign this issue to me.
Name: Ruchika
Domain: ML Batch 3
Documentation

**Comment by raina-akshay** [comment]
> Yugal Agarwal Batch - 1 https://github.com/Yugal41735 Documentation

Already assigned

**Comment by raina-akshay** [comment]
@vanshhhhh @Mann-tech13 @VidhiBhatt01 you already been assigned issues?

**Comment by vanshhhhh** [comment]
> @vanshhhhh @Mann-tech13 @VidhiBhatt01 you already been assigned issues?

No issues have been assigned from this week.

**Comment by vanshhhhh** [comment]
Sorry @raina-akshay I am unassigning this issue. I checked and got another issue. You can give this issue to some other contributor.

**Comment by VidhiBhatt01** [comment]
@raina-akshay please assign me this. I haven't contributed much

**Comment by Isha307** [comment]
@VidhiBhatt01 one issue at a time, please make the PR for previous assigned issue first.

**Comment by Isha307** [comment]
I m sorry @VidhiBhatt01 but Rule is Rule.
Why didn't you give the time to it previously.
I would like to suggest you to create the PR for assigned issue ASAP, then grab the other issue.

**Comment by VidhiBhatt01** [comment]
@Isha307 Please check your LinkedIn DM.

**Comment by VidhiBhatt01** [comment]
I have completed previously assigned issue. Please assign me this. @abhisheks008 @Isha307

**Comment by abhisheks008** [comment]
issue assigned to you @VidhiBhatt01
