### ISSUE TITLE
Android-Java: 1.8 Introduction to android manifest file or manifest style structure in android studio

### ISSUE THREAD

**Issue by SB2318** [girlscript/winter-of-contributing#75]
1. Here I will describe first, how one can find the manifest file in android studio.
2. Role of the manifest file in our development.
3. Give a brief description of some important attributes present in the manifest file, which will help us further in our project.

**Comment by SB2318** [comment]
@VikasPandey121  can I work on this issue?

**Comment by anmol20112000** [comment]
Can i work on this..?

**Comment by VikasPandey121** [comment]
I have assigned this issue to @SB2318 as she asked for it first. @anmol20112000, please look up any other issue that is not assigned to anyone yet or you can create your own issue depending upon the need of the repository.

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- Your Contributing file should be in this directory `Android_Development/Java/` with the file name starting from 1.8 for instance `1.8 Introduction to android manifest file`.
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `1.8.1`, `1.8.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by SouravKr2001** [comment]
I am from Android Development with Java Batch-6
I want to contribute/work in this issue via documentation

**Comment by SB2318** [comment]
@VikasPandey121 Please check this.

**Comment by VikasPandey121** [comment]
> @VikasPandey121 Please check this.

Thank you for the contribution @SB2318 🎉🎉
