### ISSUE TITLE
FRONTEND WITH FRAMEWORK: Angular -> Dynamic Components in Angular

### ISSUE THREAD

**Issue by mukeshmjn** [girlscript/winter-of-contributing#750]
- What are Dynamic Components?
- When we use them?
- How to create ?

Note:-

1. Don't even think about copy pasting we after reviewing would be merging the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week1" directory
3. Tasks would be assigned on First Come First Serve Basis.

**Comment by RIYANSHGARG** [comment]
I would like to work on this issue, Kindly assign it to me.

**Comment by mukeshmjn** [comment]
go for it!

**Comment by mukeshmjn** [comment]
go for it!

**Comment by VAISHNAVI0715** [comment]
hi, I am interested in this issue, will do contribute via docs.
-Vaishnavi
-Batch-4

**Comment by mukeshmjn** [comment]
@RIYANSHGARG any updates on this?

**Comment by RIYANSHGARG** [comment]
I am working on this and till morning I will create a pull request
