### ISSUE TITLE
ML 8.14 : Single Shot Detector (D)

### ISSUE THREAD

**Issue by raina-akshay** [girlscript/winter-of-contributing#7504]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Single Shot Detector_**

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Sequential_Data_&_Visual Data' Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by VidhiBhatt01** [comment]
Please assign this issue to me.
Name: Vidhi Bhatt
Domain: ML Batch 3
Serial no: 490
Github link: https://github.com/VidhiBhatt01
Documentation

**Comment by Yugal41735** [comment]
Yugal Agarwal
Batch - 1
https://github.com/Yugal41735
Documentation

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
plz assign to me.

**Comment by Ruchika-20** [comment]
https://github.com/Ruchika-20
Please assign this issue to me.
Name: Ruchika
Domain: ML Batch 3
Documentation

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
Profile link: https://github.com/priyall
Contribution type: Documentation
I would like to contribute to this issue.

**Comment by raina-akshay** [comment]
assigned to @tanvideshmukh29

**Comment by abhisheks008** [comment]
What's the progress here @tanvideshmukh29

**Comment by abhisheks008** [comment]
What's the progress here @tanvideshmukh29

**Comment by tanvideshmukh29** [comment]
@abhisheks008  plz check the PR.

**Comment by abhisheks008** [comment]
@tanvideshmukh29 changes requested in your PR. You haven't follow the template for documentation.
