### ISSUE TITLE
ML 8.16 : Fourier and Discrete Cosine Transformations of Images (D)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#7507]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Fourier and Discrete Cosine Transformations of Images_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Seqential_Data_&_Visual_Data` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by VidhiBhatt01** [comment]
Please assign this issue to me.
Name: Vidhi Bhatt
Domain: ML Batch 3
Serial no: 490
Github link: https://github.com/VidhiBhatt01
Documentation

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
Profile link: https://github.com/priyall
Contribution type: Documentation
I would like to contribute to this issue.

**Comment by Ruchika-20** [comment]
https://github.com/Ruchika-20
Please assign this issue to me.
Name: Ruchika
Domain: ML Batch 3
Documentation

**Comment by Yugal41735** [comment]
Yugal Agarwal
Batch - 1
https://github.com/Yugal41735
Documentation

**Comment by tanvideshmukh29** [comment]
Tanvi Deshmukh
batch-5
plz assign to me.

**Comment by Isha307** [comment]
@VidhiBhatt01 one issue at a time, please make the PR for previous assigned issue first.

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 one issue at a time, please make the PR for the previous assigned issue first.

@Isha307 This is the last set of issues and I have 0 contributions in the ML domain. I am sure I will complete them within the deadline. Please keep the issues assigned to me

**Comment by Isha307** [comment]
I m sorry @VidhiBhatt01 but Rule is Rule.
Why didn't you give the time to it previously.
I would like to suggest you to create the PR for assigned issue ASAP, then grab the other issue.

**Comment by VidhiBhatt01** [comment]
@Isha307 Please check your LinkedIn DM.

**Comment by abhisheks008** [comment]
@Isha307 I would like to assign this issue to @Ruchika-20 as per the FCFS basis. Have you sort out the problem with @VidhiBhatt01 ? If yes then please let me know, I'll assign this to Ruchika.

**Comment by abhisheks008** [comment]
@VidhiBhatt01 would you like to work in this issue?

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 would you like to work in this issue?

@abhisheks008 Given a choice, I would prefer working on 8.13 .

**Comment by VidhiBhatt01** [comment]
@abhisheks008 I have created PR for 8.13. You can assign me this now.

**Comment by abhisheks008** [comment]
Issue assigned to you @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
> Issue assigned to you @VidhiBhatt01

Thank you @abhisheks008
