### ISSUE TITLE
ML 8.16 : Fourier and Discrete Cosine Transformations of Images (V)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#7508]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Fourier and Discrete Cosine Transformations of Images_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Seqential_Data_&_Visual_Data` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Video
*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by ashish-reddy-20-08** [comment]
I am M. Ashish Reddy, I would like to work on this issue. 

Batch Number: 2
Serial Number: 260
GitHub Profile Link: https://github.com/ashish-reddy-20-08
Approach: A detailed explanation with examples.

**Comment by Preet1406** [comment]
Name: Ravanpreet Kaur Bagga
Batch Number: 2
Which type of Contribution you want to make : Documentation

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do Video on this issue.my approach: a detailed explanation

**Comment by Isha307** [comment]
@Preet1406 Issue assigned to you.

**Comment by abhisheks008** [comment]
@Preet1406 This is a Video contribution, not a documentation. Are you okay with that?

**Comment by deepthi1107** [comment]
@abhisheks008 sir, can you please assign to me, sir
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to do Video on this issue.my approach: a detailed explanation

**Comment by Preet1406** [comment]
@abhisheks008 Yes I'm okay with it

**Comment by abhisheks008** [comment]
Great @Preet1406. Complete this within 3 days.

**Comment by Preet1406** [comment]
@abhisheks008 alright!

**Comment by abhisheks008** [comment]
What's the update here @Preet1406

**Comment by Preet1406** [comment]
@abhisheks008 I'll be done by evening
I'm sorry for the delay, my exams were going on

**Comment by abhisheks008** [comment]
@Preet1406 ❓
