### ISSUE TITLE
ML 8.18 : Image Denoising (D)

### ISSUE THREAD

**Issue by Isha307** [girlscript/winter-of-contributing#7511]
### 📌  Issues for Week 8
Welcome to 'ML' Team, good to see you here

:arrow_forward: This issue will helps readers in acquiring all the knowledge that one needs to know about ----
### **_Image Denoising_**.

:red_circle: To get assigned to this issue, add your **Batch Numbers** mentioned in the spreadsheet of "Machine Learning", the approach one would follow and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

✔️ Domain : **Machine Learning**

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

- "Issue Title" and "PR Title should be the same. Include issue number along with it.

- Changes should be made inside the `Machine Learning/Machine_Learning/ML_for_Seqential_Data_&_Visual_Data` Branch.

- Follow Contributing Guidelines & Code of Conduct before start Contributing.

- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

************************************************************

:white_check_mark: **To be Mentioned while taking the issue :**
- Full name
- Batch Number
- GitHub Profile Link
- Which type of Contribution you want to make : 
    - [ ] Documentation

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by khushali452** [comment]
Please assign this issue to me.
Name: Khushali Vasani
Domain: ML Batch 3
Github link: https://github.com/khushali452

**Comment by khushali452** [comment]
Please assign this issue to me.
Name: Khushali Vasani
Domain: ML Batch 3
Github link: https://github.com/khushali452

**Comment by Ruchika-20** [comment]
https://github.com/Ruchika-20
Please assign this issue to me.
Name: Ruchika
Domain: ML Batch 3
Documentation

**Comment by Yugal41735** [comment]
Yugal Agarwal
Batch - 1
https://github.com/Yugal41735
Documentation

**Comment by Isha307** [comment]
@Ruchika-20 complete your previous issue first, 
@khushali452 Create PR within 3 days.

**Comment by abhisheks008** [comment]
Whats the progress here @khushali452

**Comment by khushali452** [comment]
@abhisheks008 I have made a PR .pls review it !

**Comment by abhisheks008** [comment]
You have made the PR for ResNet (D), and that issue is closed. Where is your PR for Image Denoising (D) @khushali452 ?

**Comment by khushali452** [comment]
I had two commits in that PR....1 for ResNet and other for image denoising....shall i make it separately?

**Comment by khushali452** [comment]
and it has been merged also

**Comment by abhisheks008** [comment]
My bad @khushali452
