### ISSUE TITLE
Frontend_with_Framework: React 7.1 -> State Management in React

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#7590]
### Description

Contributors are required to create Documentation and explain about the **State Management in React** which should cover the questions like : 
- What is State Management in React ?
- Where we use this concept in React ?
- Benefits of using this concept ?
- also give some theory explanation with code.
- also any add-ons from your side (in-depth of the topic).

Note :

- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the **Week 7** folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreya024** [comment]
I would like to work on this issue.Kindly assign

**Comment by nisha855** [comment]
@heet-kumar
Nisha Tirkey
Batch-5

**Comment by heet-kumar** [comment]
> @heet-kumar
> Nisha Tirkey
> Batch-5

ok go for it

**Comment by heet-kumar** [comment]
> @heet-kumar I would like to work on this issue.Kindly assign it to me.

hey you already know that you need to write just /assign

**Comment by shreya024** [comment]
/assign is not working for me.I have more than 3 open  issues from other domain which I have already made PR but still under review.
It would be great if you could assign this to me.I commented on it first.@heet-kumar

**Comment by heet-kumar** [comment]
#7904 PR merged for issue #7590 and closed.
