### ISSUE TITLE
Binary Tree Traversals

### ISSUE THREAD

**Issue by saloni33** [girlscript/winter-of-contributing#7591]
### Description

Documentation on tree traversals in Binary Tree namely -
1. Preorder traversal
2. Postorder traversal
3. Inorder traversal
with their codes.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by saloni33** [comment]
@VikasPandey121 sir kindly review my pr #7681

**Comment by VikasPandey121** [comment]
> @VikasPandey121 sir kindly review my pr #7681

Please ping DSA Supervisor here.
