### ISSUE TITLE
Frontend_with_Framework: React 7.3 -> Redux in React

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#7593]
### Description

Contributors are required to create Documentation and explain about the **Redux in React** which should cover the question like :
- What is Redux in React ?
- Where we use Redux in React ?
- Benefits of using Redux.
- also give some theory explanation with code samples.
- also any add-ons from your side (in-depth of the topic).

Note : 
- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the Week 7 folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by heet-kumar** [comment]
@HarjasSodhi make good PR on this topic because Redux is vast topic and also try to cover the all aspects .

**Comment by HarjasSodhi** [comment]
@heet-kumar tried my best . please review it and let me know if you want me to make any changes.
https://github.com/girlscript/winter-of-contributing/pull/7846

**Comment by heet-kumar** [comment]
@HarjasSodhi its amazing PR Its quite good and it is already merged. 👍
