### ISSUE TITLE
Quick Sort Algorithm (DSA>>Searching and Sorting)

### ISSUE THREAD

**Issue by Ishaarora1234** [girlscript/winter-of-contributing#7599]
### Description

Quick Sort Algorithm with elaborative description for DSA folder, Searching and Sorting  sub-folder

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
Stale issue, so closing it.
