### ISSUE TITLE
Frontend_with_Framework: React 7.2 -> Importance of State Management in React

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#7622]
### Description

Contributors are required to create **Video** and explain about the **Importance State Management in React** which should cover the question like :
- What is state management in React ?
- Where we use this concept in React ?
- Importance of using the State Management in React .
- also give some explanation with code samples.
- also any add-ons in depth about these topic from your side.

Note : 
- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the **Week 7** folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Anshii12** [comment]
Updates- Half of the video is done.

**Comment by heet-kumar** [comment]
@Anshii12 ok continue try to complete it fast because we will release new issues very soon so that you can grab that issues also.

**Comment by heet-kumar** [comment]
@Anshii12  any updates ?

**Comment by Anshii12** [comment]
Yes sir, actully my college has shifted to offline mode so I was a bit busy. I'll create a pr by tomorrow.

**Comment by heet-kumar** [comment]
@Anshii12 but do as soon as possible.

**Comment by Anshii12** [comment]
Yes! Extremely sorry for this. I'll complete it by tomorrow.

**Comment by heet-kumar** [comment]
@Anshii12 any updates ?

**Comment by heet-kumar** [comment]
@Anshii12 try to create PR in Frontend_Web_Development_React_Angular_Vue branch
