### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(7.4) -> Requesting Data from Server

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#7699]
### Description

- How to request data from server?
- How to read full response?
- How to request non-json data?
- Explain with syntax/example
- Reference :- https://angular.io/guide/http
(Week 7 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week7" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HastiSutaria** [comment]
/assign 
Name - Hasti Sutaria
I wish to work on it 
@anandhu720 please assign it to me.

**Comment by anandhu720** [comment]
Sure

**Comment by HastiSutaria** [comment]
@mukeshmjn @anandhu720 PR created. Please review.
