### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(7.5) -> Error Handling

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#7700]
### Description

- How to get error details?
- how to retry a failed request?
- Explain with syntax/example
- Reference :- https://angular.io/guide/http
(Week 7 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week7" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HastiSutaria** [comment]
Name : Hasti Sutaria 
Please assign I would like to work on it.

**Comment by HastiSutaria** [comment]
@anandhu720  please assign this issue. I wish to work on it.

**Comment by anandhu720** [comment]
Sure,if you have issue with working on both issue,please tell

**Comment by HastiSutaria** [comment]
> Sure,if you have issue with working on both issue,please tell

no it's fine. I will complete both the issue by tomorrow.

**Comment by HastiSutaria** [comment]
@anandhu720 Please review my PR.

**Comment by anandhu720** [comment]
@HastiSutaria  I  appreciate your work please coutinue your contributon.Great job

**Comment by HastiSutaria** [comment]
Thank you @anandhu720
