### ISSUE TITLE
[C/CPP]: Pointer vs References in C++

### ISSUE THREAD

**Issue by areenoverclouds** [girlscript/winter-of-contributing#7714]
### Description

I would like to provide documentation on pointers vs references in c++.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Prateek-8168** [comment]
I want to work on this issue.
Kindly assign me this issue.
