### ISSUE TITLE
What is OS Module in Python?

### ISSUE THREAD

**Issue by anjalikumawat2002** [girlscript/winter-of-contributing#7715]
### Description

What is OS Module in python and what functionalities are provided by the os module.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by adityabisoi** [comment]
Topic already covered in #4011
