### ISSUE TITLE
DSA: Stacks 4.1.12.1 Prefix to Postfix Conversion 

### ISSUE THREAD

**Issue by nimisha-yadav** [girlscript/winter-of-contributing#7718]
## Description
How to convert prefix expressions to postfix? Show examples and implementation.

Three contributors may take up this issue depending on the format.

## Task
- [x] Documentation 
- [ ] Audio
- [ ] Video

## Note
- Do not use assign command for this issue.
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**. 
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.

**Comment by nimisha-yadav** [comment]
@uzma024 you may take up this.

**Comment by jaigora24** [comment]
@nimisha-yadav mam plz assign this to me
Type :- Documentation
Name :- Jai Gora
DSA Batch No. :- 7
