### ISSUE TITLE
[Interview Preparation]: Add OOPs cheat sheet

### ISSUE THREAD

**Issue by Ayonijakaushik19** [girlscript/winter-of-contributing#7763]
### Description

Hi admin, i want to add OOPs cheat sheet under Interview preparation repository. Please assign it to me.

### Domain

Interview Prep

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Pragati1419** [comment]
"\assign
