### ISSUE TITLE
DSA 6.2.1 Tower of Hanoi

### ISSUE THREAD

**Issue by Perpetual-Incantation** [girlscript/winter-of-contributing#778]
# Description

Write the **algorithm** of Hanoi tower?
Describe the approach also?

**Comment by Perpetual-Incantation** [comment]
@nimisha-yadav I have created this issue and I would like to work on it. Please add labels and assign it to me ! Thanks.

**Comment by itsbittoosharma** [comment]
Please assign this to me. I could also work on it

**Comment by vkaash-sharma** [comment]
please assign this issue to me i like to work on the documentation of this issue

**Comment by Kashika02** [comment]
I hold a good command on dsa , I would like to contribute to this issue 
Kashika Parmar
Batch 1 dsa

**Comment by nimisha-yadav** [comment]
Hey @Perpetual-Incantation, this topic is not there in the week 1 agenda so I'm closing this issue, please [refer here](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/README.md) for more info.
