### ISSUE TITLE
Data Science with Python : Glass Classification and Analysis

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#7797]
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know on how to work on classification problem especially with Glass Classification and it's analysis.

Dataset : https://www.kaggle.com/uciml/glass

This issue is created on contributors request. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : Yash Goel | Nithin 

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Deepika-Pavundoss** [comment]
Deepika-Pavundoss commented 2 days ago
Sr no: 161
Batch: 5
Name: Deepika Pavundoss
Type : Video
I would like to explain about the different algorithms, the libraries used here, process and the code in detail
@prathimacode-hub

**Comment by Deepika-Pavundoss** [comment]
Sr no: 161
Batch: 5
Name: Deepika Pavundoss
Type : Video
I would like to explain about the different algorithms, the libraries used here, process and the code in detail
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @Deepika-Pavundoss for documentation

**Comment by pankaj-sawnani** [comment]
I would like to work on this topic
Pankaj Sawnani - 936
Batch - 21
Issue No - #7797
Type: Video
Approach: I will clearly explain about the model i am using and how i have selected the model for classification and analysis.
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Issue assigned to @pankaj-sawnani for video contribution

**Comment by kishlayaug15** [comment]
Name - Kishlay Kumar
Batch - 4
Serial No - 673
GithubLink :- https://github.com/kishlayaug15
Approach: A detailed explanation with Audio

**Comment by kishlayaug15** [comment]
@prathimacode-hub can I start working on this issue??

**Comment by pankaj-sawnani** [comment]
@prathimacode-hub please review my PR.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution
