### ISSUE TITLE
Data Science with Python : Credit Card Fraud Detection

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#7798]
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will know on how to work on detecting the credit card frauds.

Dataset : https://www.kaggle.com/mlg-ulb/creditcardfraud

This issue is created on contributors request. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : Aarya Patel | Shivang Dubey

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by divya-chhoriya** [comment]
/assign
Divya Chhoriya
Sr no. 444
Batch 12
Type: documentation
Approach: credit card fraud detection using three different methods

**Comment by prathimacode-hub** [comment]
Issue assigned to @divya-chhoriya for documentation

**Comment by pankaj-sawnani** [comment]
I would like to work on this.
Pankaj Sawnani - 936
Batch - 21
Issue No - #7798
Type: Video
/assign

**Comment by yashh18** [comment]
Name - Yash Kataria
Serial No - 861
Batch No - 20
Type - Audio
Approach - I would explain the topic with the help of various code examples and check the accuracy of model using different machine learning models.
@prathimacode-hub Please assign this to me

**Comment by prathimacode-hub** [comment]
Issue assigned to @pankaj-sawnani for video and @yashh18 for audio contribution
