### ISSUE TITLE
[FRONTEND WITH FRAMEWORK]: Angular(7.7) -> Interceptors

### ISSUE THREAD

**Issue by koshimagoyal** [girlscript/winter-of-contributing#7801]
### Description

- What is interceptor?
- How to write an interceptor?
- How to handle interceptor events?
- Explain with syntax/example
- Reference :- https://angular.io/guide/http
(Week 7 Issue)

Note:-

1. Don't copy paste, we would be merging after reviewing the PR.
2. Changes should be made inside "Frontend_Web_Development_React_Angular_Vue/Angular/Week7" directory
3. Tasks would be assigned on First Come First Serve Basis

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HastiSutaria** [comment]
Name : Hasti Sutaria 
I would like to work on it

**Comment by HastiSutaria** [comment]
I have completed my issues but they aren’t closed by mentors.

**Comment by HastiSutaria** [comment]
@anandhu720 please assign this issue. I wish to work on it.

**Comment by anandhu720** [comment]
sure

**Comment by HastiSutaria** [comment]
I am currently working on it since it was assigned. @anandhu720 please reassign.

**Comment by HastiSutaria** [comment]
@anandhu720 @mukeshmjn Please review my PR.
