### ISSUE TITLE
Everything about Command line

### ISSUE THREAD

**Issue by amanraj-iit** [girlscript/winter-of-contributing#7804]
### Description

The command line is an essential tool for software development.
By using commands, we can execute a wide variety of programs on your computer.
In this we will learn the fundamental UNIX commands necessary for development in this course!

### Domain

C_CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by amanraj-iit** [comment]
https://github.com/girlscript/winter-of-contributing/pull/8210/files#
@Saviour1001

**Comment by amanraj-iit** [comment]
please review

**Comment by Saviour1001** [comment]
I am a supervisor of CPP Domain, and your PR is of multiple domains. Thus I can't review and merge it. Kindly ping the Supervisor/Mentor of the respective domains.
