### ISSUE TITLE
Frontend: HTML Forms

### ISSUE THREAD

**Issue by SaniyaBhargav** [girlscript/winter-of-contributing#782]
I would like to contribute to the mentioned domain.

**Comment by cenacrharsh** [comment]
I would like to contribute to this issue.
Batch- 5 Frontend with HTML, CSS
Discord - cenacr007#9148

**Comment by vkaash-sharma** [comment]
I can contribute to this issue.
u can check my portfolio where I use my knowledge of HTML forms.

https://vkaash-sharma.github.io/vikas-portfolio/

**Comment by VAISHNAVI0715** [comment]
I would like to contribute to this domain via docs.
Batch- 4 Frontend with HTML, CSS.

**Comment by AnantDuhan** [comment]
I would love to contribute on this

**Comment by 7sakshi7** [comment]
I would like to contribute to this issue.
Batch- 18 Frontend with HTML, CSS
Discord - agarwalSakshi | Contributor#9567

**Comment by Kalyani02072003** [comment]
i would like to contribute in it
batch - 18 frontend 
discord - STRAWHAT_LUFFY#8651
