### ISSUE TITLE
Cybersecurity: 2.8 OSI model

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#785]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by RK1905101** [comment]
can i take up this issue to contribute in documentation?

**Comment by Anant1711** [comment]
> can i take up this issue to contribute in documentation?

OK!
I'm assigning this task to you!

**Comment by Anant1711** [comment]
`Documentation is Done!`
Does anyone want to `contribute` a video on this topic?

**Comment by Nikita512** [comment]
Please assign me this issue, I want to make video for the issue.
Nikita Agrawal (Batch-1, Cybersecurity)

**Comment by Anant1711** [comment]
> Please assign me this issue, I want to make video for the issue.
> Nikita Agrawal (Batch-1, Cybersecurity)

@Nikita512 Sorry Your previous work is pending! First, submit that one, then I can assign you other!

**Comment by monika1024** [comment]
can i contribute in audio

**Comment by Anant1711** [comment]
> can i contribute in audio

Okay!
But it will be better if you contribute in `video` it will be great for users who will see/listen to your work!
or if you want to contribute in `Audio` then I'll assign you for audio?

**Comment by monika1024** [comment]
ok. assign then'

**Comment by Anant1711** [comment]
> ok. assign then'

Okay!
I'm assigning you this task for the video!

**Comment by Anant1711** [comment]
@monika1024 I didn't get any update from your side!
You took 5 days!
please submit your work!
