### ISSUE TITLE
ML : Breast Cancer Classification (ML-Projects)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#7853]
### 📌 Issues for Week 9 - Basic Projects of Machine Learning

🔴 **Project Title** : **Breast Cancer Classification**
🔴 **Aim of the Project** : Creating a machine learning model, which will classify breast cancer and then predict accordingly.
🔴 **Dataset** : https://www.kaggle.com/merishnasuwal/breast-cancer-prediction-dataset
🔴 **Domain** : Machine Learning
🔴 **Special Credit** : **Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked through the accuracy scores to determine the best fitted model**

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain. 

**************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

**Take the Reference from these two projects attached here,** 
1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Changes should be made inside the `Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning` Branch.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- Batch Number : 
- GitHub Profile Link : 
- Approach for this Project :
- Are you a participant of GWoC21?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Basic Projects of Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:198, Batch-2. I would like to work on this issue.my approach: a detailed explanation

**Comment by abhisheks008** [comment]
Follow the guidelines and provide the approach of your project, like which algorithms you gonna use, how you'll check the accuracy of them @deepthi1107

**Comment by deepthi1107** [comment]
Full name : Deepthi M
Batch Number : 02
GitHub Profile Link :  https://github.com/deepthi1107
Approach for this Project : a detailed EDA and I would like to use supervised machine learning models.
Are you a participant of GWoC21?
 YES

**Comment by abhisheks008** [comment]
Issue assigned @deepthi1107 , complete this within 3 days.

**Comment by kishlayaug15** [comment]
Full name : Kishlay Kumar
Batch Number : 04
serial no = 673
GitHub Profile Link : https://github.com/kishlayaug15
Approach for this Project : a detailed EDA and I would like to use supervised machine learning models like svm, decision tree, random forest and many more
Are you a participant of GWoC21?
YES

**Comment by abhisheks008** [comment]
This issue is already assigned to @kishlayaug15

**Comment by kishlayaug15** [comment]
> This issue is already assigned to @kishlayaug15

Is it assigned to me??
So, I can start working on it.

**Comment by abhisheks008** [comment]
> > This issue is already assigned to @kishlayaug15
> 
> Is it assigned to me?? So, I can start working on it.

No sorry my bad. This is assigned to @deepthi1107. You can't work on it.

**Comment by kishlayaug15** [comment]
ok, when next set of issues will be uploaded? @abhisheks008

**Comment by abhisheks008** [comment]
What's the progress in this project work? @deepthi1107

**Comment by deepthi1107** [comment]
its in the final process sir

**Comment by abhisheks008** [comment]
@deepthi1107 How's all going?
