### ISSUE TITLE
ML : Sentiment Analysis on Twitter Data

### ISSUE THREAD

**Issue by geeythree** [girlscript/winter-of-contributing#7856]
### 📌 Issues for Week 9 - Basic Projects of Machine Learning

🔴 **Project Title** : Sentiment Analysis on Twitter Data
🔴 **Aim of the Project** : Analysing the sentiment of the users and creating a prediction model based on the data, which will predict the sentiment of the user.
🔴 **Dataset** : https://www.kaggle.com/arkhoshghalb/twitter-sentiment-analysis-hatred-speech
🔴 **Domain** : Machine Learning
🔴 **Special Credit** : **Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked through the accuracy scores to determine the best fitted model**

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain. 

**************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

**Take the Reference from these two projects attached here,** 
1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Changes should be made inside the `Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning` Branch.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- Batch Number : 
- GitHub Profile Link : 
- Approach for this Project :
- Are you a participant of GWoC21?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by riyasai22** [comment]
I would like to contribute to this issue.
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22
contribution type:documentation

**Comment by abhisheks008** [comment]
Follow the guidelines and provide the approach of your project, like which algorithms you gonna use, how you'll check the accuracy of them @riyasai22

**Comment by riyasai22** [comment]
I would like to contribute to this issue.
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22
Approach:Using modules Tweepy and TextBlob for sentiment analysis also will try EDA method and use f1 score to check the accuracy.
contribution type : documentation

**Comment by abhisheks008** [comment]
Contribution type is Projects. As this is a project contribution.

Go ahead, issue assigned to you @riyasai22 , complete this within 3 days.

**Comment by abhisheks008** [comment]
What's the progress in this project work? @riyasai22

**Comment by riyasai22** [comment]
I'll be making a pr soon. @abhisheks008 

> What's the progress in this project work? @riyasai22

**Comment by priyall** [comment]
Name: Priyal Palkhiwala
Batch: 5
Profile link: https://github.com/priyall
Contribution type: Project
I would like to contribute to this issue.

**Comment by abhisheks008** [comment]
@priyall what will be your approach?

**Comment by priyall** [comment]
> @priyall what will be your approach?

Approach will be: using libraries and classifiers like textblob, SVM, regression for sentiment analysis and check accuracy and model evaluation using f1 scores

**Comment by abhisheks008** [comment]
Go ahead and complete this within 3 days positively @priyall

**Comment by abhisheks008** [comment]
How's all going @priyall

**Comment by priyall** [comment]
> How's all going @priyall. I think you have got the announcement message from the GWoC Team about the completion of the assigned issues, hence I'd like to request you to make the PR as soon as possible, so that we can evaluate timely.

Yes, I'll complete it by tomorrow.

**Comment by abhisheks008** [comment]
@priyall waiting for your PR.
