### ISSUE TITLE
ML : Customer Segmentation (ML-Projects)

### ISSUE THREAD

**Issue by abhisheks008** [girlscript/winter-of-contributing#7858]
### 📌 Issues for Week 9 - Basic Projects of Machine Learning

🔴 **Project Title** : **Customer Segmentation**
🔴 **Aim of the Project** : Analysing different types of customers around the globe and build a classification model accordingly.
🔴 **Dataset** : https://www.kaggle.com/vetrirah/customer
🔴 **Domain** : Machine Learning
🔴 **Special Credit** : **Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked through the accuracy scores to determine the best fitted model**

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain. 

**************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

**Take the Reference from these two projects attached here,** 
1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Changes should be made inside the `Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning` Branch.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- Batch Number : 
- GitHub Profile Link : 
- Approach for this Project :
- Are you a participant of GWoC21?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Basic Projects of Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by NikitaEmberi** [comment]
Name-Nikita Bhrugumaharshi Emberi
Domain-Machine Learning
Batch-6
Serial No-992
Type : Documentation

**Comment by abhisheks008** [comment]
Follow the guidelines and provide the approach of your project, like which algorithms you gonna use, how you'll check the accuracy of them @NikitaEmberi

**Comment by NikitaEmberi** [comment]
Please can I let you know the procedure after some time...? @abhisheks008

**Comment by abhisheks008** [comment]
Ok. No problem, once you tell me your approach I'll assign you for sure.

**Comment by NikitaEmberi** [comment]
@abhisheks008 , I'm thinking of using KNN, Linear SVC, Random Forest and XGBoost Classifier to classify the customers and compare the accuracy of the models.

**Comment by abhisheks008** [comment]
And then you'll find the best fitted model. But before that add some visualizations of the dataset (EDA things). Got it @NikitaEmberi ?

**Comment by NikitaEmberi** [comment]
@abhisheks008 yes

**Comment by abhisheks008** [comment]
Great then issue assigned to you @NikitaEmberi , complete  this within 3 days.

**Comment by NikitaEmberi** [comment]
One more doubt, Can I change the algorithms later, if there is a need to change...?

**Comment by abhisheks008** [comment]
Yeah you can, but try to use more than 3-4 algorithms, which  will help you to make a good comparison @NikitaEmberi

**Comment by NikitaEmberi** [comment]
@abhisheks008 sir yes got it. thank you.
