### ISSUE TITLE
ML : Wine Quality Prediction Project

### ISSUE THREAD

**Issue by kshitijshrivastava1903** [girlscript/winter-of-contributing#7863]
### Description

🔴 Project Title : Wine Quality Prediction
🔴 Aim of the Project : The objectives of this project are as follows
1. To experiment with different classification methods to see which yields the highest accuracy
2. To determine which features are the most indicative of a good quality wine
🔴 Dataset : https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009
🔴 Domain : Machine Learning
🔴 Special Credit : Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked through the accuracy scores to determine the best fitted model. Try judging the algorithms on different parameters, not just accuracy and come up with a graphical representation of how the algorithms are performing in various parameters, to choose the best. 

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain.

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Changes should be made inside the Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning Branch.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
✅ To be Mentioned while taking the issue :

Full name :
Batch Number :
GitHub Profile Link :
Approach for this Project :
Are you a participant of GWoC21?
 YES
 No
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

Domain
Machine Learning

Type of Contribution
Basic Projects of Machine Learning

### Domain

Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by divya-chhoriya** [comment]
please assign me this issue
Divya Chhoriya
batch 2
documentation
https://github.com/divya-chhoriya

**Comment by kshitijshrivastava1903** [comment]
This is audio contribution type issue.

**Comment by kshitijshrivastava1903** [comment]
You can start working on it.

**Comment by divya-chhoriya** [comment]
> You can start working on it.

for documentation?

**Comment by kshitijshrivastava1903** [comment]
Yes, its documentation only

**Comment by divya-chhoriya** [comment]
please assign me this issue
Divya Chhoriya
batch 2
documentation
https://github.com/divya-chhoriya

**Comment by riyasai22** [comment]
I would like to contribute to this issue. 
Name: Riya Srisailam Sailesh
Batch: 4
Profile link: https://github.com/riyasai22

**Comment by abhisheks008** [comment]
Follow the guidelines and provide the approach of your project, like which algorithms you gonna use, how you'll check the accuracy of them @divya-chhoriya

**Comment by divya-chhoriya** [comment]
> Follow the guidelines and provide the approach of your project, like which algorithms you gonna use, how you'll check the accuracy of them @divya-chhoriya
> 
> This is a project work, not a documentation.

Okay
I will be using different ML algorithms such as Random forest, decision tree, adaboost, and gradient boosting.  I will calculate the accuracy score, precision, recall, f1score and display confusion matrix for all the algorithms

**Comment by abhisheks008** [comment]
@divya-chhoriya Before creating the models, visualize the data (EDA things) will be great.

**Comment by divya-chhoriya** [comment]
> @divya-chhoriya Before creating the models, visualize the data (EDA things) will be great.

Yeah I will do that also

**Comment by abhisheks008** [comment]
Great! All the best @divya-chhoriya
