### ISSUE TITLE
ML Projects : Heart Disease Prediction

### ISSUE THREAD

**Issue by kshitijshrivastava1903** [girlscript/winter-of-contributing#7864]
### Description

📌 Issues for Week 9 - Basic Projects of Machine Learning
🔴 Project Title : Heart Disease Prediction
🔴 Aim of the Project : Use this dataset to predict which patients are most likely to suffer from a heart disease in the near future using the features given.
🔴 Dataset : https://www.kaggle.com/rishidamarla/heart-disease-prediction
🔴 Domain : Machine Learning
🔴 Special Credit : Try to implement more than three machine learning algorithms and make a comparison between them, then conclude about the best fit algorithm to create the model. All the algorithms must be checked with various methods of evaluating ML algorithms like F1-score, accuracy, precision, recall.  Make a graph of the performance of the model in different area, to depict clearly, which model is performing best, in differenent parameters.

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain.

📍 Follow the Guidelines to Contribute in the Project :
You need to create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project
Take the Reference from these two projects attached here,

https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis
🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Changes should be made inside the Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning Branch.
Follow Contributing Guidelines & Code of Conduct before start Contributing.
This issue is only for 'GWOC' contributors of 'Machine Learning' domain.
✅ To be Mentioned while taking the issue :

Full name :
Batch Number :
GitHub Profile Link :
Approach for this Project :
Are you a participant of GWoC21?
 YES
 No
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

Domain
Machine Learning

Type of Contribution
Basic Projects of Machine Learning

Code of Conduct

### Domain

Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by hrugved06** [comment]
Hrugved kolhe
Batch: 3
GitHub: https://github.com/hrugved06
Type:- Documentation
Interested

**Comment by kshitijshrivastava1903** [comment]
Please tell me your approach of this project.

**Comment by hrugved06** [comment]
Detailed explanation of the steps with preprocessing of data followed by proper EDA (heatmaps, histograms, subplots), then I will perform feature selection and then best algorithm selection.

**Comment by kshitijshrivastava1903** [comment]
You can start working on the project.

**Comment by kshitijshrivastava1903** [comment]
If possible, try to implement one algorithm from scratch, without using sklearn or any other library, so that reader is also clear about the mathematics behind the algorithm.

**Comment by abhisheks008** [comment]
What's the progress in this project work? @hrugved06

**Comment by hrugved06** [comment]
@abhisheks008, i am done with the project just some theory content is pending. I'll definitely add it and create a PR by tonight or tomorrow evening.

Thanks a lot for the patience, as I also have to cope up with the ongoing exams at my institute which is causing bit of delay, thanks
