### ISSUE TITLE
[C_CPP]: NP Completeness 

### ISSUE THREAD

**Issue by vishnu95075** [girlscript/winter-of-contributing#7874]
### Description

# NP Completeness Algorithm 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by dummy-co-der** [comment]
#7890 Done!

**Comment by vasu-1** [comment]
@Suvraneel  Please check this issue and do needful !!

**Comment by Suvraneel** [comment]
Reason : Author Prioritised

> Self-assigns by the original author will be prioritised by mentors manually
