### ISSUE TITLE
Cybersecurity: 2.9.1 Router

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#788]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by LegendSumeet** [comment]
assign me to these @Anant1711

**Comment by anjanaaaaaaaa** [comment]
can i take this in documentation

**Comment by Anant1711** [comment]
> can i take this in documentation

Assigned for `Documentation`.

**Comment by Anant1711** [comment]
`Documentation` is Done!
Is anyone willing to contribute Video?

**Comment by LegendSumeet** [comment]
OHK I CAN ?

**Comment by Anant1711** [comment]
> OHK I CAN ?

I guess you didn't submit your previous task work also `Documentation` and `VIdeo` both!
first, submit this, only then I can assign you a new task!
