### ISSUE TITLE
Cybersecurity: 2.9.2 HUBs

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#789]
## Note:
- If interested, mention in which format you want to contribute: `Documentation` or `Video`
- Please avoid copy/paste, `BE YOURSELF`
- Try to explain with *Diagrams*
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security `branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by LegendSumeet** [comment]
assign me to these @Anant1711

**Comment by Anant1711** [comment]
> assign me to these @Anant1711

One Task at a Time!

**Comment by LegendSumeet** [comment]
i can do it in documentation

**Comment by RK1905101** [comment]
Can I contribute in this, for documentation part!?

**Comment by Anant1711** [comment]
> Can I contribute in this, for documentation part!?

Okay! Go for `Documentation`

**Comment by Nikita512** [comment]
@Anant1711 Please assign me this issue, I want to make video for the issue.
Nikita Agrawal (Batch-1, Cybersecurity)
