### ISSUE TITLE
Data Structures Problems in C++

### ISSUE THREAD

**Issue by Pragati1419** [girlscript/winter-of-contributing#7937]
### Description

Topic-wise selected problems with easy medium and hard  level  from gfg.........

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Pragati1419** [comment]
"\assign"

**Comment by Bhavika2210** [comment]
Can I please be assigned with the documentation. I havent made any PR yet, i wish to contribute.
Kindly assign
