### ISSUE TITLE
Semantic HTML 

### ISSUE THREAD

**Issue by VanshSh** [girlscript/winter-of-contributing#794]
Name: Vansh Sharma
Batch number:  4 
Domain: Frontend development with HTML/CSS/JS/Bootstrap
Discord user name:  Vansh Sharma#0122
@praveenscience #794  #261

**Comment by praveenscience** [comment]
Yep go for it.

**Comment by dikshatakyar** [comment]
Hi, Can you please assign me this ?
I will do contribution via video.
Name : Diksha Takyar
Batch no. 12
Domain: Frontend development with HTML/CSS/JS/Bootstrap
discord username : dikshaaaa#1262
@praveenscience

**Comment by VanshSh** [comment]
Heyy @dikshatakyar 
After completing the video part please do share your link so that I can add that link in my doc
 for the people if they want to refer to the video learning.

**Comment by dikshatakyar** [comment]
@VanshSh , I haven't been assigned the video part yet , If I am assigned then I will create a different branch here and it will be merged

**Comment by VanshSh** [comment]
You can ask supervisors of your domain and send the link of your issue they will give permission to you because I did the same.
