### ISSUE TITLE
Top 10 Open Source Software

### ISSUE THREAD

**Issue by LegendSumeet** [girlscript/winter-of-contributing#796]
@Aryamanz29 assign me to these i will making a good and short document on it

**Comment by Kalyani02072003** [comment]
please assign it to me
i am a beginner but I will try my best to provide the best document

**Comment by Aryamanz29** [comment]
We already covering every program, Don't need this
Thanks

**Comment by Kalyani02072003** [comment]
@Aryamanz29 Sir i am a beginner, may i know if anyone is assigned to it or you will be assigning it in a while?

**Comment by LegendSumeet** [comment]
@Kalyani02072003 it had been closed
