### ISSUE TITLE
[Create New Issue]: circular linked list

### ISSUE THREAD

**Issue by Sharayu1071** [girlscript/winter-of-contributing#7960]
### Description

What is a circular linked list and all operations on a circular linked list.

### Domain

DSA

### Type of Contribution

Video

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Sharayu1071** [comment]
I am working on this issue.

**Comment by goelesha** [comment]
It has already been done. Pls create some other issue

**Comment by Sharayu1071** [comment]
Okay
