### ISSUE TITLE
Explain everything Related to `Julia Summer of Code`

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#797]
### Description :

- **Explain everything related to `Julia Summer of Code`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-4`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by eshan1925** [comment]
May I work on this issue?
And what is the format we need to submit our docs in . Like is it gonna be pdf,word or Readme.md file?
ANd what should be the approximate length of the explanation.

**Comment by Harshit-Poddar90** [comment]
May I work?

**Comment by Muskan-creator** [comment]
@eshan1925 Assigning issue to you .
@Harshil-Jani Issue assigning is based on first come first basis . I hope you don't mind.

**Comment by eshan1925** [comment]
Thankyou @Muskan-creator  just tell me an approximate length of explanantion.

**Comment by Harshil-Jani** [comment]
> @eshan1925 Assigning issue to you .
> @Harshil-Jani Issue assigning is based on first come first basis . I hope you don't mind.

Hey ! Ig you made a wrong tag😅 it was supposed to be for @Harshit-Poddar90 .

**Comment by Muskan-creator** [comment]
Sorry @Harshil-Jani

**Comment by Harshit-Poddar90** [comment]
Thank you for assigning me. 
I just want to know is there any time limit for this?

**Comment by Harshit-Poddar90** [comment]
@eshan1925 pls guide me as I am new to this field.

**Comment by eshan1925** [comment]
@Harshit-Poddar90 you are not assigned to this task. As all of this comes on first come first serve basis.

**Comment by Harshit-Poddar90** [comment]
Oh so why I was tagged? 
Anyways np

**Comment by eshan1925** [comment]
Hey @Muskan-creator have created PR for the task that youassigned me today, I have according to me provided all the things related to the Julia Summer of Code, so you can merge the PR.
Thank You
[https://github.com/girlscript/winter-of-contributing/pull/895](Pull Request)

**Comment by eshan1925** [comment]
Hey @Aryamanz29 and @Muskan-creator  I have created yhe pull request now in the OpenSource branch. Please merge if there is no problem in the documentation.
