### ISSUE TITLE
4.20 Explain everything related to `NJACK Winter Of Code`

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#798]
### Description :

- **Explain everything related to `NJACK Winter Of Code`**
### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Put  your `doc` inside `section-4`
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by Varun270** [comment]
@Aryamanz29 please assign this issue to me , I would like to work on it.

**Comment by Muskan-creator** [comment]
@Varun270 Assigning issue to you

**Comment by Varun270** [comment]
@Muskan-creator Can you tell me is there any kind of deadline to solve this issue

**Comment by Muskan-creator** [comment]
You have to solve it in max 1 week 😀

**Comment by Varun270** [comment]
@Muskan-creator Hey I have created the documentation for this issue can you please rename this issue with the suggested naming convention so that it would be easy for me to name the commit message and PR.

**Comment by Varun270** [comment]
<img width="389" alt="name_convention" src="https://user-images.githubusercontent.com/75975268/134189408-9b9b4551-151f-43a2-b843-db7efb952719.png">
As you can see all the doc files here follow the name convention and I don't know what should be the serial number of this issue.

**Comment by Varun270** [comment]
@Aryamanz29 Have a look at this issue, It doesn't have serial number.

**Comment by Varun270** [comment]
@Aryamanz29 Kindly review this PR, I am aware of the fact that I haven't mentioned the serial number. Today was the deadline so I had to Open a PR.

**Comment by Muskan-creator** [comment]
Added serial no Make a Pr into section 4 of `/Opensource` directory
