### ISSUE TITLE
Explain everything related to `Mozilla Winter of Security`

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#800]
### Description :

- **Explain everything related to `Mozilla Winter of Security`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by itsbittoosharma** [comment]
Please assign this issue to me
I want to work on this 
Batch - 2

**Comment by Muskan-creator** [comment]
@itsbittoosharma Assigning issue to you

**Comment by itsbittoosharma** [comment]
In which directory the file has to be created or in which Section folder in Open Source directory? And also what will be the serial number for .md file in that directory?

**Comment by itsbittoosharma** [comment]
@Muskan-creator ?? Please let me know so that I could make a PR

**Comment by Muskan-creator** [comment]
PR should in section -4 of open source directory and in .md file format

**Comment by itsbittoosharma** [comment]
Please check my pr
