### ISSUE TITLE
[Android Dev with Java]: Android - Loading Spinner 

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#8005]
### Description

Discuss the use of Loading Spinner.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@VikasPandey121 Please assign this issue to me

**Comment by priyanshu688** [comment]
@sitamadex11 Please assign this issue to me

**Comment by VikasPandey121** [comment]
I have assigned this issue to you @priyanshu688. You can start working on it now.

**Comment by priyanshu688** [comment]
@VikasPandey121 Please review this PR - https://github.com/priyanshu688/winter-of-contributing/pull/32
