### ISSUE TITLE
[DSA]: Tower of Hanoi  

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#8018]
### Description

Briefly discuss about Tower of Hanoi, Its Rules and Its Algorithm.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@nimisha-yadav @pjdurden @Muskan-creator Please assign this issue

**Comment by nimisha-yadav** [comment]
This issue already exists. @priyanshu688
