### ISSUE TITLE
OpenSource : 4.15 Explain everything related to `Kharagpur Winter Of Code`

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#802]
### Description :

- **Explain everything related to `Kharagpur Winter Of Code`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title  `

## Happy Contributing 🙌

**Comment by siddhi-244** [comment]
Can I try ?

**Comment by Muskan-creator** [comment]
@siddhi-244 Assigning this issue to you

**Comment by siddhi-244** [comment]
Please check my pr !
