### ISSUE TITLE
Data Science with Python : Multilayer Perceptron's

### ISSUE THREAD

**Issue by ShraddhaP123** [girlscript/winter-of-contributing#8020]
### Description

Name - Shraddha Pattanshetti
Batch - Data Science with Python
Sr no - 649
Batch - 17
Approach:
Introduction, What is Neuron, Hidden layers, Universal Approximators, Activation function, Conclusion 

### Domain

Datascience with Python

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment]
Issue is assigned to @ShraddhaP123 for documentation

**Comment by prathimacode-hub** [comment]
You don't have any mentor assigned to your issue. Your assigned mentor in Aishani Singh | Kareem Negm @ShraddhaP123

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for audio contribution

**Comment by ashish-reddy-20-08** [comment]
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment]
Issue assigned to @ashish-reddy-20-08 for video contribution
