### ISSUE TITLE
GitHub Terminologies

### ISSUE THREAD

**Issue by priyankapiba** [girlscript/winter-of-contributing#8022]
### Description

GitHub Terminologies with explanation.

### Domain

Python_Domain

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyankapiba** [comment]
@adityabisoi , allow me to work on this issue.

**Comment by adityabisoi** [comment]
Can you write what do u want to do in detail?

**Comment by priyankapiba** [comment]
> Can you write what do u want to do in detail?

https://docs.github.com/en/get-started/quickstart/github-glossary

**Comment by adityabisoi** [comment]
There's an issue already existing on this topic. Closing the issue
