### ISSUE TITLE
OpenSource:4.21 Explain everything related to `OpenCode IIITA`

### ISSUE THREAD

**Issue by Muskan-creator** [girlscript/winter-of-contributing#803]
### Description :

- **Explain everything related to `OpenCode IIITA`**

### Note : 

- Changes should be made inside the `Open_Source/` directory & `Opensource` branch.
-  Issue only for `GWOC'21` contributors.
-  Issue will be assigned on a **first come first serve basis**, **1 Issue  ==  1 PR == 1 Contributor**
-  For `Contributor` please don't create the same issue again, before creating any issue do visit [OpenSource Milestone](https://github.com/girlscript/winter-of-contributing/milestone/2)
- `Doc name` should same as the `issue title `

## Happy Contributing 🙌

**Comment by sanjana-coder** [comment]
Please assign this to me

**Comment by Muskan-creator** [comment]
@sanjana-coder Assigning this issue to you😊

**Comment by sanjana-coder** [comment]
Thanks!

**Comment by chakitg** [comment]
Hey @Muskan-creator, I would like to work on this issue, is it possible now? Can you please assign me this?
Name: Chakit Gupta
Batch: Open-Source Batch-1
Type: Documentation

**Comment by Muskan-creator** [comment]
@sanjana-coder how is the progress?

**Comment by sanjana-coder** [comment]
Sorry for the delay, I've been having my exams
If it's okay, I'll create a PR by tomorrow 
Else you can assign it to anyone else

**Comment by Muskan-creator** [comment]
Okay @sanjana-coder make a pr by tomorrow 🙂

**Comment by Muskan-creator** [comment]
@chakitg Try on some other issues I will assign you 🙂

**Comment by sanjana-coder** [comment]
Sure will do!
