### ISSUE TITLE
Central Limit Theorem

### ISSUE THREAD

**Issue by amanraj-iit** [girlscript/winter-of-contributing#8042]
### Description

Defining Central Limit Theorem 

### Domain

Machine Learning

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by amanraj-iit** [comment]
[](https://github.com/girlscript/winter-of-contributing/pull/8048)
please review

**Comment by amanraj-iit** [comment]
update

**Comment by abhisheks008** [comment]
@amanraj-iit Who told you to create an issue and assign it yourself by your own?

**Comment by amanraj-iit** [comment]
hi , I was searching for a contribution and found this on ML, so I thought to contribute

**Comment by amanraj-iit** [comment]
please review

**Comment by A-GHOSH-dev** [comment]
@abhisheks008 Can I contribute here?
