### ISSUE TITLE
Data Science with Python : Heart Disease Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [girlscript/winter-of-contributing#8046]
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, the readers will get detailed explanation of how to work on Heart Disease Prediction using dataset provided

Dataset : https://www.kaggle.com/rishidamarla/heart-disease-prediction

This issue is created on contributors request. 

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned : Yash Goel | Pushpit Singh

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Data Science with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by HastiSutaria** [comment]
I would like to work on this.
Hasti Sutaria - 426
Type: Documentation
Approach: Working with dataset performing EDA, training and testing the ML model and applying the algorithm that gives better accuracy.

**Comment by divya-chhoriya** [comment]
/assign
Divya Chhoriya
Sr no. 444
Batch 12
Type: documentation
Approach: EDA, prediction using different models, calculate the accuracy score

**Comment by prathimacode-hub** [comment]
Issue assigned to @divya-chhoriya for documentation. @HastiSutaria, you can choose another issue to work on or audio/video. This is created on contributors request.

**Comment by kishlayaug15** [comment]
@prathimacode-hub
Kishlay Kumar
Sr no. 501
Batch 15
Type: Audio
Approach: EDA, prediction using different models, calculate the accuracy score

**Comment by prathimacode-hub** [comment]
Issue assigned to @kishlayaug15 for audio contribution

**Comment by deepthi1107** [comment]
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do video on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment]
Issue assigned to @deepthi1107 for video contribution
