### ISSUE TITLE
[DSA]: Dynamic Programming and Its Significance 

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#8056]
### Description

Give a detailed introduction on Dynamic Programming.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@nimisha-yadav Please assign this issue to me

**Comment by priyanshu688** [comment]
@nimisha-yadav Can you please clarify me why this is showing that assigned contributor has more than 3 open issues

**Comment by nimisha-yadav** [comment]
Assigned it to you

**Comment by priyanshu688** [comment]
@nimisha-yadav Please review and merge this PR - https://github.com/priyanshu688/winter-of-contributing/pull/27
