### ISSUE TITLE
Android-Java: 2.5 CheckBox in Android

### ISSUE THREAD

**Issue by Janhvi-s** [girlscript/winter-of-contributing#807]
## Things I'll be working on this issue
- What is a checkbox?
- How to implement a checkbox in Java

**Comment by Janhvi-s** [comment]
@VikasPandey121 Can I work on this issue?

**Comment by VikasPandey121** [comment]
Please keep these steps in mind while creating a pull request:

- use `git fetch` and `git pull` commands before pushing commit it to the remote repository.
- Your Contributing file should be in this directory `Android_Development_With_Java/Android UI Widgets` with the file name starting from 2.3 for instance `2.3 CheckBox in Android`
Note:- If you have multiple files to commit then add a tag at the beginning of your file name like `2.3.1`, `2.3.2` etc
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by Rohit-2602** [comment]
@Janhvi-s can you please give a progress update about the issue and if you are facing any problem feel free to ask.

**Comment by Janhvi-s** [comment]
My content is ready, was just stuck in the git commands. Working on it!

**Comment by Rohit-2602** [comment]
Nice work @Janhvi-s  👍
