### ISSUE TITLE
Frontend_with_Framework: React 8.3 -> Axios in React

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#8076]
### Description

Contributors are required to create Documentation and explain about the **Axios in React** which should cover the question like :

- What is Axios in React ?
- Where we use Axios in React ?
- Benefits of the Axios.
- also give some theory explanation with code.
- also any add-ons in depth about these topic from your side. 

Note : 

- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the **Week 8** folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Ajinkyap331** [comment]
@heet-kumar @shreya024 is also having another issue of build in api so as per the rule can you please assign it to me
