### ISSUE TITLE
C_CPP : Moving from C to CPP

### ISSUE THREAD

**Issue by Kamya123** [girlscript/winter-of-contributing#8082]
### Description

- This will help to learn CPP very easily if anybody knows C already. 

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Kanishk0412** [comment]
Can I work on this issue @Suvraneel?

**Comment by Suvraneel** [comment]
@Kanishk0412  Its already been taken Kanishk..

**Comment by Kanishk0412** [comment]
I'm only Kanishk.

**Comment by Kanishk0412** [comment]
Okay no problem
