### ISSUE TITLE
Cybersecurity: 1.9 What is Virtualization ?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#81]
## Description
If we want to do penetration testing then kali Linux is recommended in your system, for running both machines host+virtual (Windows and kali on the same device, when your base operating system is Windows!) we need virtualization.
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on *first come first serve*
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by AtharvaaPatil** [comment]
Can I work on this

**Comment by iamKushGupta** [comment]
Can this issue be assigned to me along with 1.9.1, please ??

**Comment by Anant1711** [comment]
> Can I work on this

Yes @AtharvaaPatil you can go with this task!
I'm assigning it to you!

**Comment by Anant1711** [comment]
> Can this issue be assigned to me along with 1.9.1, please ??

Hi @iamKushGupta ,
Atharvaa comment first on this issue, so I assigned this task to Atharva, You can check other issues.
Thank you!
