### ISSUE TITLE
FRONTEND WITH FRAMEWORK: React 9.1: React icons

### ISSUE THREAD

**Issue by its-me-Harsh-Anand** [girlscript/winter-of-contributing#8124]
### Description

Description
Topics covered
- What is react icon
- Why to use it
- How to use it
- Different method of styling icons

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-Harsh-Anand** [comment]
/assign

@anandhu720 sir, please assign me this issue

**Comment by heet-kumar** [comment]
@its-me-Harsh-Anand don't create the issues by your own it causes partiality for others contributors.
