### ISSUE TITLE
Frontend_with_Framework: React 9.2 -> Testing in React

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#8142]
### Description

Contributors are required to create Documentation and explain about the **Testing in React** which should cover the question like :

- What is Testing ?
- What are the types ?
- Benefits of the Testing.
- also give some theory explanation.
- also any add-ons in depth about these topic from your side.

Note :

- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the **Week 9** folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by shreya024** [comment]
I would like to work on this issue.Kindly assign

**Comment by heet-kumar** [comment]
@shreya024 close any one issue out of 3. Then write '/assign' here so that it will get assign you. Because if we assign you then BOT will remove you again automatically so assign issue out of 3, one issue should be closed.

**Comment by heet-kumar** [comment]
@shreya024 issue assigned now go for it

**Comment by shreya024** [comment]
> @shreya024 issue assigned now go for it

Thank you :)
