### ISSUE TITLE
Frontend_with_Framework: React 9.4 -> React Testing Library

### ISSUE THREAD

**Issue by heet-kumar** [girlscript/winter-of-contributing#8144]
### Description

Contributors are required to create Documentation and explain about the **React Testing Library** which should cover the question like :

- What is React Testing Library ?
- Where we use ?
- What are the benefits of React Testing Library ?
- also give some theory explanation (with code samples) .
- also any add-ons in depth about these topic from your side.

Note :

- Plagiarism is strictly prohibited.
- **Changes should be made inside the Frontend_Web_Development_React_Angular_Vue/ dir inside Frontend_Web_Development_React_Angular_Vue branch.**
- Files need to be added into the **Week 9** folder only.

### Domain

Frontend Dev React/Angular/Vue

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by its-me-Harsh-Anand** [comment]
@heet-kumar @anandhu720 Please assign this to me sir

**Comment by anandhu720** [comment]
@its-me-Harsh-Anand You can work on it

**Comment by anandhu720** [comment]
@its-me-Harsh-Anand Please create pr by 2 day.Only 4 days remaining

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand Please create pr by 2 day.Only 4 days remaining

Okay sir, I'll do

**Comment by heet-kumar** [comment]
@its-me-Harsh-Anand create PR 3 days over buddy.

**Comment by its-me-Harsh-Anand** [comment]
> @its-me-Harsh-Anand create PR 3 days over buddy.

Today itself I'm creating PR

**Comment by heet-kumar** [comment]
@its-me-Harsh-Anand ok do it asap
