### ISSUE TITLE
depth first and bread first traversals

### ISSUE THREAD

**Issue by Eswari-Priya** [girlscript/winter-of-contributing#8153]
### Description

I'd like to describe about bfs and dfs traversals of graphs. I will also include some examples, algorithm and its implementation.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Eswari-Priya** [comment]
@goelesha @nimisha-yadav @pjdurden @Muskan-creator  could you pls look into this issue and pls let me know if i could work on it.
I am eswari priya repaka and i belong to dsa batch-2

**Comment by nimisha-yadav** [comment]
Go ahead @Eswari-Priya

**Comment by Eswari-Priya** [comment]
Thank you !
