### ISSUE TITLE
Android Java: 13.03 Create swipe views with tabs using ViewPager2

### ISSUE THREAD

**Issue by Kajal13081** [girlscript/winter-of-contributing#8173]
### Description

- Implement swipable views with ViewPager2
- Use TabLayout with ViewPager2 and swipe to change tabs

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Kajal13081** [comment]
@VikasPandey121 please assign this issue to me. I would like to work on this.

**Comment by VikasPandey121** [comment]
> 

Yes, sure @Kajal13081. 
Go ahead.

**Comment by Kajal13081** [comment]
PR #8775 
@VikasPandey121, @sitamadex11 Sir review this PR please.
