### ISSUE TITLE
Cybersecurity: 1.9.1 Types of Virtualization  - What is Network Virtualization ?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#82]
## Description
If we want to do penetration testing then kali Linux is recommended in your system, for running both machines host+virtual (Windows and kali on the same device, when your base operating system is Windows!) we need virtualization.
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by iamKushGupta** [comment]
Can this be assigned to me along with 1.9 ??

**Comment by Anant1711** [comment]
> Can this be assigned to me along with 1.9 ??

Yes, go with it!
