### ISSUE TITLE
Introduction to Backtracking

### ISSUE THREAD

**Issue by syedmdsaifihassan** [girlscript/winter-of-contributing#8282]
### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
Stale issue, so closing it.
