### ISSUE TITLE
Cybersecurity: 1.9.2 Types of Virtualization - What is Virtual Desktop Infrastructure (VDI) ?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#83]
## Description
If we want to do penetration testing then kali Linux is recommended in your system, for running both machines host+virtual (Windows and kali on the same device, when your base operating system is Windows!) we need virtualization.
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by IshikaMeghaSaha** [comment]
Hello Anant! I would like to work on this issue.

**Comment by Anant1711** [comment]
> Hello Anant! I would like to work on this issue.

Okay! I'm assigning you this task!

**Comment by Anant1711** [comment]
@IshikaMeghaSaha 
When are you going to submit your work?

**Comment by IshikaMeghaSaha** [comment]
By today. I am done with the writeup. It's taking a little time to document it using stackedit.

**Comment by Anant1711** [comment]
> By today. I am done with the writeup. It's taking a little time to document it using stackedit.

Okay!
