### ISSUE TITLE
C_CPP :- Looping Control structure/statements

### ISSUE THREAD

**Issue by Ravinayak07** [girlscript/winter-of-contributing#834]
<hr>

## Description 📜

I want to work on making documentation on Looping Control structure/statements

@Suvraneel  please /assign this to me 
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by vkaash-sharma** [comment]
assign this issue to me!

**Comment by Suvraneel** [comment]
@Ravinayak07  Please edit your comment & take only 1 topic...
And before that make sure it isn't a duplicate one

**Comment by Ravinayak07** [comment]
> @Ravinayak07 Please edit your comment & take only 1 topic...
> And before that make sure it isn't a duplicate one 👍🏻

Sir the duplicate issues of these topics has already been created by others. 
Also i have already completed making the documentation of the first 2 topics.
what should i do now sir?

**Comment by Suvraneel** [comment]
@Ravinayak07  We consider/prefer the 1st issue maker for every topic...
But yes, to resolve conflicts, I'll recommend taking up a non-conflicting issue
C++ has infinite algorithms & problems to contribute to

**Comment by Ravinayak07** [comment]
> @Ravinayak07 We consider/prefer the 1st issue maker for every topic...
> But yes, to resolve conflicts, I'll recommend taking up a non-conflicting issue
> C++ has infinite algorithms & problems to contribute to

okay sure
