### ISSUE TITLE
Prime Factor C_CPP

### ISSUE THREAD

**Issue by amanraj-iit** [girlscript/winter-of-contributing#8358]
### Description

C_CPP

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by amanraj-iit** [comment]
@Saviour1001 please assign this to me

**Comment by amanraj-iit** [comment]
I had closed all my issues then also the bot is not assigning me

**Comment by Saviour1001** [comment]
Closing this as #8359 got merged
