### ISSUE TITLE
bank management  project in cpp

### ISSUE THREAD

**Issue by Octocat-10** [girlscript/winter-of-contributing#8385]
### Description

how to do bank management project in cpp.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
Code present [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Projects%20in%20C_C%2B%2B/Simple_ATM_Bank_in_C.md)
