### ISSUE TITLE
Cybersecurity: 1.9.3 Types of Virtualization - What is application virtualization?

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#84]
## Description
If we want to do penetration testing then kali Linux is recommended in your system, for running both machines host+virtual (Windows and kali on the same device, when your base operating system is Windows!) we need virtualization.
## Note:
- Please avoid copy/paste, `BE YOURSELF`
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by Kavyaabhishek** [comment]
I'm Kavya, an enthusiastic student and I'm Intrested to work on this issue

**Comment by Anant1711** [comment]
> I'm Kavya, an enthusiastic student and I'm Intrested to work on this issue

okay! I'm assigning you this task!

**Comment by Kavyaabhishek** [comment]
Thank you for assigning this work to me.

**Comment by Anant1711** [comment]
@Kavyaabhishek 
Are working on this?

**Comment by Kavyaabhishek** [comment]
> @Kavyaabhishek 
> Are working on this?

I can't do this because I'm not able to do it in markdown language.

**Comment by Anant1711** [comment]
> > @Kavyaabhishek
> > Are working on this?
> 
> I can't do this because I'm not able to do it in markdown language.

What issue do you face? I can help you out!
Or you can submit `Video` also!

**Comment by RK1905101** [comment]
Can i take up this this issue?😅

**Comment by Anant1711** [comment]
> Can i take up this this issue?😅

Yes, You can!
I'm assigning this to you!

**Comment by RK1905101** [comment]
are both documentation and video available or just any one!?

**Comment by Anant1711** [comment]
> are both documentation and video available or just any one!?

Yeah, Both are available!
You can do both or one, it depends on you!

**Comment by RK1905101** [comment]
Oki
Both I'll do it..
just in case...
can I submit the video part by Tuesday!?

**Comment by Anant1711** [comment]
> can I submit the video part by Tuesda

yeah yeah sure!
