### ISSUE TITLE
Android Kotlin: Readme Update

### ISSUE THREAD

**Issue by ayush-sleeping** [girlscript/winter-of-contributing#8410]
## Description :scroll:

* All the Topics name in Roadmap make responsive  <br> (so that just touching the topics name we can reach to the documentation very easily )

*  Badge or Sheild  of Kotlin lang. and Android studio . 

## Domain of Contribution :bar_chart:

- [x] Android Dev (Kotlin)

<hr>

## Please Read it Carefully Before Contributing
* Changes should be made in Android_Development_With_Kotlin/ directory under Android_Development_With_Kotlin branch.
* Inside Android_Development_With_Kotlin/ directory creates a directory and names it according to the topic ( for this issue 09. Dynamic User Interface)
* Inside 09. Dynamic User Interface/ directory add your task with subtopic number and name and make changes accordingly.
* You have to push your PR to the Android_Development_With_Kotlin branch only.
* You can take help to the references but don't simply try to copy it. Just explain in your own word.
* This issue is for GWOC'21 contributors only.
* You need to push in a single commit. If there exists more than one commit then you need to squash your commits into one commit.
* Will assign you on a first come first serve basis.
* Please try to complete your assigned task within 7 days. If you need some more time then, please inform mentors and supervisors.
* If you have two previously assigned issues on Android-Kotlin pending then please first complete them.
> Supervisor @rahulsain

**Comment by ayush-sleeping** [comment]
Hey @rahulsain , I want to make all the topic and subtopic name in Roadmap of Android dev. kotlin " Responsive " <br> and want to add Badge or sheild of Android studio and Kotlin lang. <br>
* It will make out Readme of Android dev. kotlin more impressive and Responsive <br>
* What do you think @rahulsain let me know <br>

And if you agree ,  " Assign "  me this issue . ........................

**Comment by rahulsain** [comment]
You can work on this issue, however no need to add `Badge or sheild of Android studio and Kotlin lang etc`

**Comment by ayush-sleeping** [comment]
> You can work on this issue, however no need to add `Badge or sheild of Android studio and Kotlin lang etc`

Ok Rahul ,
