### ISSUE TITLE
Frontend : HTML Lists

### ISSUE THREAD

**Issue by Ravinayak07** [girlscript/winter-of-contributing#842]
<hr>

## Description 📜

I want to work on making documentation on  HTML Lists  with its example code and output .
Please /assign this to me.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by Kalyani02072003** [comment]
@Ravinayak07 sir i am new to this contribution can you help me with this as we are assigned to same issue

**Comment by Ravinayak07** [comment]
> @Ravinayak07 sir i am new to this contribution can you help me with this as we are assigned to same issue

you have to create documentation on HTML Lists

**Comment by Kalyani02072003** [comment]
@Ravinayak07 i get it i will create the documentation, should i do it in word and where should I submit it?

**Comment by Ravinayak07** [comment]
> @Ravinayak07 sir i am new to this contribution can you help me with this as we are assigned to same issue

you have to submit in the form of Markdown file (like README.md). Follow the contributing guidelines

**Comment by Kalyani02072003** [comment]
@Ravinayak07 okay, how can i contact you if i run into problem? i will not message unnecessarily

**Comment by joshi-kaushal** [comment]
Is this issue still on? I'd love to help
