### ISSUE TITLE
[DSA]: Introduction to Tries and Its Implementation in Cpp, Java or Python 

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#8432]
### Description

Introduction to Tries and Its Implementation in Cpp, Java or Python

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@nimisha-yadav Please assign this issue to me

**Comment by nimisha-yadav** [comment]
Go ahead @priyanshu688

**Comment by priyanshu688** [comment]
@nimisha-yadav Kindly review and merge this PR - https://github.com/priyanshu688/winter-of-contributing/pull/33

**Comment by nimisha-yadav** [comment]
The deadline to create new PRs has passed. Thank you for all your contributions.
