### ISSUE TITLE
[DSA]: Introduction to Disjoint Set Union

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#8433]
### Description

Discuss in detail about Disjoint Set Union.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by priyanshu688** [comment]
@nimisha-yadav Please assign this to me

**Comment by priyanshu688** [comment]
@nimisha-yadav Please review this PR - https://github.com/priyanshu688/winter-of-contributing/pull/34

**Comment by nimisha-yadav** [comment]
@priyanshu688 your method of creating PR is incorrect. Create PR towards GWOC repo

**Comment by nimisha-yadav** [comment]
The deadline to create new PRs has passed. Thank you for all your contributions.
