### ISSUE TITLE
Frontend : HTML Style Attribute

### ISSUE THREAD

**Issue by Ravinayak07** [girlscript/winter-of-contributing#844]
<hr>

## Description 📜

I want to work on making documentation on  HTML Style Attribute  with its example code and output .
Please /assign this to me.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by Anshii12** [comment]
May I work on this issue. 
Name- Anshita Sharma
Batch- 7

**Comment by hrshita-kshyp** [comment]
/ assign

**Comment by Ravinayak07** [comment]
FrontEnd

**Comment by Ravinayak07** [comment]
@sifa123 can you please add the frontend labels to this issue

**Comment by Ravinayak07** [comment]
@sifa123 i have submitted a PR. Please Kindly review it.
