### ISSUE TITLE
Creation of Binary Tree using Linked List

### ISSUE THREAD

**Issue by pinpan123** [girlscript/winter-of-contributing#8469]
### Description

Description

### Domain

C/C++

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment]
@pinpan123  Also, where is the description for the issue ?
From next time decide what issue youre going to fix, create it & then make a PR regarding it

> ### Description
> Description
> 
> ### Domain
> C/C++
> 
> ### Type of Contribution
> Documentation
> 
> ### Code of Conduct
> * [x]  I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by pinpan123** [comment]
Okay. I will keep this in mind.
