### ISSUE TITLE
[DSA]: 7.2.6 Topological Sort

### ISSUE THREAD

**Issue by 0xUvaish** [girlscript/winter-of-contributing#8472]
### Description

Explain Topological Sort algorithm with diagrams and codes.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Aishwarya713** [comment]
Please assign this issue to me @0xUvaish 
/assign

**Comment by 0xUvaish** [comment]
Hi @Aishwarya713 I have created this issue for myself. Pls create an issue on your own and assign yourself.

You can unassign it by /unassign command.

**Comment by nimisha-yadav** [comment]
Closing the issue since deadline to open new PRs is over. Thanks for all your contributions!
