### ISSUE TITLE
[Create New Issue]: Array Implementation of Stacks

### ISSUE THREAD

**Issue by VaibhavMalik4187** [girlscript/winter-of-contributing#8485]
### Description

I will be providing documentation for Array Implementation Of Stack

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav Is that good to go?

**Comment by nimisha-yadav** [comment]
> @nimisha-yadav Is that good to go?

Yes go ahead

**Comment by nimisha-yadav** [comment]
@VaibhavMalik4187 Please try to submit the PR by today or tomorrow maximum since we're starting to close the issues now. 

It would be great if you could cover up [this topic](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/11.%20Boruvka's%20Minimum%20Spanning%20Tree) as well, this folder is empty.

**Comment by VaibhavMalik4187** [comment]
> @VaibhavMalik4187 Please try to submit the PR by today or tomorrow maximum since we're starting to close the issues now.
> 
> It would be great if you could cover up [this topic](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/11.%20Boruvka's%20Minimum%20Spanning%20Tree) as well, this folder is empty.

Don't worry about these stack issues, I'll make a PR today itself, but I am really sorry, I won't he able to cover the minimum spanning tree topic, I have never studied that algorithm

**Comment by nimisha-yadav** [comment]
Alright, no worries @VaibhavMalik4187. Your contributions has been nice, I'd encourage you to contribute to [1-2 more issues](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/2.1%20Strings/4.%20Arithmetic%20Operations%20Using%20Numbers%20as%20Strings) :D

**Comment by VaibhavMalik4187** [comment]
@nimisha-yadav Thanks a lot, I'm really lucky to have awesome mentors like you, I am going to make the PR, if you're on, then let me know if changes are required
