### ISSUE TITLE
[Android Dev with Java]: Fragments

### ISSUE THREAD

**Issue by utkarshakakade** [girlscript/winter-of-contributing#8495]
### Description

What is Fragments?
Use of Fragment in Android
Lifecycle of fragment and it's example.

### Domain

Android Dev (Java)

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by utkarshakakade** [comment]
\assign documentation

**Comment by Rohit484** [comment]
\assign documentation
