### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by VikasPandey121** [girlscript/winter-of-contributing#85]
Your task is to :

- Go through the README.md  of [Android-Dev-Java directory](https://github.com/girlscript/winter-of-contributing/tree/main/Android_Development/Java) and add the [Roadmap of Android Development using Java](https://docs.google.com/document/d/137rcHXwjCMY8rSD06IwtJzAEMS1g4_G8VJEggRwhjGQ/edit?usp=sharing) in README.md file without adding timeline (Weeks that is mentioned in the doc file)
- Make it self explanatory 
- Create a new branch and push your PR on `Android_Development_With_Java` branch.
- Pull request should contain only one commit
Note: If you have multiple commits then `squash` your commit.

**Comment by anmol20112000** [comment]
I want to work on this..

**Comment by VikasPandey121** [comment]
@anmol20112000 great!
You are good to go. 😇

**Comment by anmol20112000** [comment]
> @anmol20112000 great!
> You are good to go. 😇

Ok thanks sir... Can u plzz tell me about deadline of this....?

**Comment by anmol20112000** [comment]
@VikasPandey121 in Your task section ... When i am clicking on android-dev-java-directory....it is showing error..."""404 this is not the webpage ur looking for"""
