### ISSUE TITLE
[DSA]: 7.2.8 Prim's Algorithm

### ISSUE THREAD

**Issue by 0xUvaish** [girlscript/winter-of-contributing#8506]
### Description

Explain Prim's algorithm with diagrams and codes

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
Repetitive issue so closing it. @0xUvaish try working on backtracking problems, hastables, bit manipulation. These folders are empty.

**Comment by nimisha-yadav** [comment]
Apart from these topics, check out these folders. You may work on them as well.
1. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/02.%20Activity%20Selection%20Problem
2. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/03.%20Job%20Sequencing%20Problem
3. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.2%20Greedy%20Algorithms/15.%20Dial's%20Algorithm
