### ISSUE TITLE
[DSA]: 7.2.9 Kruskal's Algorithm 

### ISSUE THREAD

**Issue by 0xUvaish** [girlscript/winter-of-contributing#8508]
### Description

Explain Kruskal's algorithm with diagrams and codes.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by rajmadhu0406** [comment]
> The assigned contributor has more than 3 open issues, kindly reassign manually (@Supervisors/Mentors)

All my open issues are merged, I request supervisor/mentors to recheck.

**Comment by 0xUvaish** [comment]
Hey @rajmadhu0406, I've opened this issue for myself. Better create a new one and assign yourself.

**Comment by rajmadhu0406** [comment]
Okay 👍🏻

**Comment by nimisha-yadav** [comment]
Repetitive issue so closing it.  It's better if you could get your issue reviewed once before starting working on it.

**Comment by nimisha-yadav** [comment]
@rajmadhu0406 If you want to contribute, try creating issues on these topics:
1. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/07.%20Floyd%20Cycle%20Detection
2. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/08.%20Josepheus%20Circle
3. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/11.%20Doubly%20Linked%20List%20from%20Ternary%20Tree
4. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/13.%20Length%20of%20Doubly%20Linked%20List
5. https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/3.1%20Linked%20List/14.%20Reverse%20Doubly%20Linked%20List
