### ISSUE TITLE
C_CPP : Two-pointer Algorithm popular questions

### ISSUE THREAD

**Issue by shreya0204** [girlscript/winter-of-contributing#864]
<hr>

## Description 📜

I'm going to add a list of two-pointer algorithm popular questions from easy to hard divided to practice in documentation.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by shreya0204** [comment]
@Suvraneel In which folder should I attach these practice questions of the two-pointer algorithm.

**Comment by Suvraneel** [comment]
@shreya0204 Pointer and its types

**Comment by shreya0204** [comment]
@Suvraneel It's been 7+ days please review this pr.

**Comment by Suvraneel** [comment]
@shreya0204  Which PR ?
This is an issue...
