### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Anushka2705** [girlscript/winter-of-contributing#866]
<hr>

This issue will explain the topic of inheritance with examples . 
Inheritance in cpp  
<hr>
[sample.txt](https://github.com/girlscript/winter-of-contributing/files/7192020/sample.txt)
[sample.txt](https://github.com/girlscript/winter-of-contributing/files/7192021/sample.txt)
 Domain of Contribution 📊
- [ x] C/CPP

<hr>

**Comment by Suvraneel** [comment]
Add proper heading to your issue & use PR-template
