### ISSUE TITLE
Height of a Binary Tree

### ISSUE THREAD

**Issue by juhik24** [girlscript/winter-of-contributing#8665]
### Description

Discuss the implementation to find height of a Binary Tree.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
@juhik24 you've been contributing well in DSA branch. It'd be great if you could cover [1. Introduction to Trees](https://github.com/girlscript/winter-of-contributing/tree/DSA/DSA/6.1%20Trees/1.%20Introduction%20to%20Trees) as well!
