### ISSUE TITLE
Constructor Types and Destructors(documentation)

### ISSUE THREAD

**Issue by Eswari-Priya** [girlscript/winter-of-contributing#868]
<hr>

## Description 📜

I'd like to explain the constructors and destructors ,their types, how to use them and how they work.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by kashyap1905** [comment]
Assign it to me

**Comment by Suvraneel** [comment]
@joshi-anita @kashyap1905 
The issue author gets preference here :)
Feel free to contribute something else here
