### ISSUE TITLE
Cocktail Sort

### ISSUE THREAD

**Issue by TechnoPhasePRO** [girlscript/winter-of-contributing#8707]
### Description

Documentation on Cocktail Sort

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by nimisha-yadav** [comment]
Closing the issue since deadline to open new PRs is over. Thanks for all your contributions.
