### ISSUE TITLE
ML : Describe everything related to Kernels?

### ISSUE THREAD

**Issue by mohitmishra786** [girlscript/winter-of-contributing#875]
<hr>

## Description 📜

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [x] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by pspiagicw** [comment]
Can somebody guide me , is this regarding the kernel in SVM or kernel as in Jupyter Notebook or Ipython kernel ?

**Comment by mohitmishra786** [comment]
> Can somebody guide me , is this regarding the kernel in SVM or kernel as in Jupyter Notebook or Ipython kernel ?

SVM

**Comment by abhisheks008** [comment]
@mohitmishra786 You have been assigned to an issue previously, complete that first and merge the PR. Why are you creating issues?
