### ISSUE TITLE
ML: Study and Implement Research Article (ML Projects)

### ISSUE THREAD

**Issue by raina-akshay** [girlscript/winter-of-contributing#8923]
### 📌 Issues for Week 9 - Basic Projects of Machine Learning

🔴 **Project Title** : **CoVID-19 Detection using Cough and other vocal audio samples**🌟 
🔴 **Aim of the Project** : Study and Implement a research article on the title, available [here](https://www.sciencedirect.com/science/article/pii/S0010482521003668?via%3Dihub).
🔴 **Dataset** : https://www.github.com/iiscleap/Coswara-Data
🔴 **Domain** : Machine Learning
🔴 **Aim** : **Try to implement the study and replicate the results obtained by the authors and make relevant visualizations.**

Welcome to 'ML' Team, good to see you here, in this week we'll be creating several basic projects of this Machine Learning Domain. 

**************************************************************

### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Implementation- To store the implementation you've developed using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project

**Take the Reference from these two projects attached here,** 
1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

***********************************************************************

:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Changes should be made inside the `Machine Learning/Machine_Learning/Basic_Projects_of_Machine_Learning` Branch.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'GWOC' contributors of 'Machine Learning' domain.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- Batch Number : 
- GitHub Profile Link : 
- Are you a participant of GWoC21?
    - [x] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

### Domain

Machine Learning

### Type of Contribution

Basic Projects of Machine Learning

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by AdityaNikhil** [comment]
I would like to contribute to this project along with my teammates,
@tavneetgill , @divya-chhoriya , @mimansa-sardhalia , @sannamir

**Batch Number** : 2, 5(@mimansa-sardhalia)
**Which type of Contribution you want to make** :
Code

**Comment by raina-akshay** [comment]
Assigned to all 👍🏻

**Comment by sannamir** [comment]
I would like to contribute to this project along with my teammates,
@AdityaNikhil @tavneetgill @divya-chhoriya @raina-akshay @mimansa-sardhalia

**Comment by tavneetgill** [comment]
I would  also like to contribute to this project along with my teammates,
@AdityaNikhil @sannamir @divya-chhoriya @raina-akshay @mimansa-sardhalia

**Comment by divya-chhoriya** [comment]
I would like to contribute to this project along with my teammates,
@AdityaNikhil @tavneetgill @sannamir  @raina-akshay @mimansa-sardhalia

**Comment by mimansa-sardhalia** [comment]
I would like to contribute to this project along with my teammates,
@AdityaNikhil @tavneetgill @sannamir @raina-akshay @divya-chhoriya
