### ISSUE TITLE
Introduction to Figma Part 3 - Vector Networks and Pen Tool

### ISSUE THREAD

**Issue by Debasmita-01** [girlscript/winter-of-contributing#91]
In this we need a documentation or a video tutorial showing how to work with vector networks and the Pen Tool. A vector network is a unique feature in Figma, and it takes it to the next level using pen tool . Check the below referrences to get an idea.
 
Referrences:
[link1](https://www.figma.com/blog/introducing-vector-networks/)
[link 2](https://medium.com/@alexharri/the-engineering-behind-figmas-vector-networks-688568e37110)

Note :
Folder Structure should be UI_UX/Introduction_to_Figma/Part_3  & changes should be made to  UI_UX branch.
Issue only for GWOC'21 contributors.
Issue will be assigned on a first come first serve basis, 1 Issue == 1 PR.
In the PR, keep this issue's title as your PR's title.
Must Follow : [Contributing Guidelines ](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)& [Code of Conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) before start Contributing

**Comment by Nafizza** [comment]
I would like to work on this

**Comment by Debasmita-01** [comment]
> I would like to work on this

Nice Go ahead. assigned.

**Comment by Puja-Saraf** [comment]
I would like to work on this issue

**Comment by Sarfraz-droid** [comment]
Can I work on video for this?

**Comment by Sarfraz-droid** [comment]
@Debasmita-01 please check out my PR

**Comment by Puja-Saraf** [comment]
@Debasmita-01 please review my PR

**Comment by Puja-Saraf** [comment]
@Debasmita-01 ma'am please review my PR
