### ISSUE TITLE
Programming Components, Structure & Keywords

### ISSUE THREAD

**Issue by Kanishk0412** [girlscript/winter-of-contributing#911]
<hr>

## Description 📜

I'll go with the Documentation of the Following Contents below:
1. I'll go over all of the C programming elements.
2. I'll go over every structure and keyword used in C programming.

<hr>

## Domain of Contribution 📊

- [ x] C/CPP

<hr>

**Comment by Kanishk0412** [comment]
Please assign me this task I have almost completed this due to some medical emergency I haven't pushed the code. 
@Suvraneel

**Comment by Suvraneel** [comment]
@Kanishk0412  Okay, sure

**Comment by Kanishk0412** [comment]
Thanks for reopening !!
