### ISSUE TITLE
C_CPP : Vectors in C++ (Documentation)

### ISSUE THREAD

**Issue by Sunainacode** [girlscript/winter-of-contributing#918]
<hr>

## Description 📜

This will explain the Vectors in STL.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>
Documentation

**Comment by ayushijindal** [comment]
Can two persons work on the same issue??

**Comment by ayushijindal** [comment]
can I work on more than two issues at the same time??

**Comment by ayushijindal** [comment]
I am from other domain I thought this is competitive programming issue
