### ISSUE TITLE
CPP: Linked List concepts with code (Video Explanation)

### ISSUE THREAD

**Issue by adityarajsahoo** [girlscript/winter-of-contributing#919]
<hr>

## Description 📜

Explanation of Linked List concepts with code through youtube uploaded videos.

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>
Video

**Comment by adityarajsahoo** [comment]
Do the issues after PR is merged, needs to be closed? @Suvraneel

**Comment by Suvraneel** [comment]
@adityarajsahoo  YES
otherwise you'd reach your limit of 3 assigned at once
