### ISSUE TITLE
Operators and Expressions in C

### ISSUE THREAD

**Issue by Kanishk0412** [girlscript/winter-of-contributing#926]
<hr>

## Description 📜

In the Documentation form, I'll go through all of the operators and expressions in detail and show you how to utilize them effectively in the C language.

<hr>

## Domain of Contribution 📊

- [ x] C/CPP

<hr>

**Comment by Kanishk0412** [comment]
This is my issue !!

**Comment by Saviour1001** [comment]
Closed as the PR #3386 got merged
