### ISSUE TITLE
C_CPP : Linked List

### ISSUE THREAD

**Issue by gauravchahar31** [girlscript/winter-of-contributing#927]
<hr>

## Description 📜

This will be a complete Linked List documentation.
Linked List (Singly, Circular, Doubly)
I will show Insertion, Deletion, Searching, Sorting, Reversing, Merging of Linked List.

<hr>

## Domain of Contribution 📊

- [ ] C/CPP
- [ ] DSA
- [ ] Interview Prep

<hr>

**Comment by gauravchahar31** [comment]
Gaurav Kumar
C/C++ Batch 11

**Comment by Aniketsinghcoder** [comment]
/assign
Aniket Singh
Interview Prep Batch 3

**Comment by rohit-goyal** [comment]
Hello
My name is Rohit Goyal 
I would like to contribution documentation part
i am from C/CPP Batch-2

**Comment by saketsagarsingh** [comment]
i want to work on this issue please assign it to me
Saket Sagar
Batch-2
Documentation

**Comment by saketsagarsingh** [comment]
If no one is working on this issue I want it to be assigned to me, please assign this issue to me manually
Saket Sagar
Batch-2
Documentation
