### ISSUE TITLE
Frontend :The Box Model in CSS

### ISSUE THREAD

**Issue by dikshatakyar** [girlscript/winter-of-contributing#930]
<hr>

## Description 📜
Every element is surrounded with a box. Here I will explain The Box Model in CSS via Video.

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev (HTML, CSS, JS)

<hr>

**Comment by nayyyhaa** [comment]
Hi @code-reaper08! I want to work on this issue in the form of a document. Kindly assign me!
Thank you :)

**Comment by nayyyhaa** [comment]
Hey @code-reaper08, I've created a PR for the assigned issue. Please review it :)

**Comment by dikshatakyar** [comment]
@code-reaper08 PLEASE OPEN THIS ISSUE. I HAVE ALREADY MADE A VIDEO BUT COULDN'T CONTRIBUTE AT THAT TIME DUE TO SOME FAMILY PROBLEMS. PLEASE LET ME CONTRIBUTE VIA VIDEO HERE. I DON'T WANT MY EFFORTS IN THE VIDEO TO GO WASTE. ALSO, THE ISSUE WAS OPENED JUST 4 DAYS AGO.PLEASE OPEN THIS ISSUE AGAIN !!

**Comment by code-reaper08** [comment]
@2024-SANDHYA Video contribution request, reopening the issue here.

**Comment by 2024-SANDHYA** [comment]
> 
> 
> @2024-SANDHYA Video contribution request, reopening the issue here.

Great !

**Comment by dikshatakyar** [comment]
@code-reaper08 Hi,Please review my PR. Thankyou !
