### ISSUE TITLE
C_CPP: Decision Making

### ISSUE THREAD

**Issue by AS8420** [girlscript/winter-of-contributing#934]
<hr>

## Description 📜

This will be documentation.
It will explain all the decision making statement used in the language so far. 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by ayushijindal** [comment]
is this issue for competitive programming domain?

**Comment by AS8420** [comment]
No, it's for C_CPP domain

**Comment by Shraddha-Jaggi** [comment]
I want to contribute to the following using video

**Comment by vasu-1** [comment]
> I want to contribute to the following using video


Hey you can do this but not on this issue. only one person can work on one issue !!!!!

Make another issue for this and select video format instead of documentation !!

I hope it will make sense !!!!!

**Comment by Saviour1001** [comment]
Closing this as the PR #2762 got merged

**Comment by AS8420** [comment]
Thanks Supervisor🙂
