### ISSUE TITLE
Cybersecurity: 1.9.4 Setup VirtualBox and Virtual Machine on Windows.

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#94]
## Description
Show **How to set VirtualBox and Virtual machine in windows** through `screen-recording` and explain every step!

 
## Note:
- Submission should be in screen-recording format with an explanation.
- Changes should be made inside the `Cyber_Security/` directory & `Cyber_Security` branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by sandeepkumar00110** [comment]
Can I work on this? I am a participant of GWOC21.

**Comment by SwarnaliBhunia** [comment]
I want to do this work

**Comment by Anant1711** [comment]
> I want to do this work

Go with it!

**Comment by SwarnaliBhunia** [comment]
Thank you

**Comment by prithwishpramanik** [comment]
sir I also want to do this work

**Comment by Anant1711** [comment]
> sir I also want to do this work

Sorry, @prithwishpramanik 
This is only for Video format and it is assigned to Swarnali already!
If she will not able to do this task only then I can pass this task to someone else.
You can check other issues also!

**Comment by prithwishpramanik** [comment]
> > sir I also want to do this work
> 
> Sorry, @prithwishpramanik
> This is only for Video format and it is assigned to Swarnali already!
> If she will not able to do this task only then I can pass this task to someone else.
> You can check other issues also!

ok sir, will we be able to contribute to the same issue if it is in documentation format only?

**Comment by Anant1711** [comment]
> > > sir I also want to do this work
> > 
> > 
> > Sorry, @prithwishpramanik
> > This is only for Video format and it is assigned to Swarnali already!
> > If she will not able to do this task only then I can pass this task to someone else.
> > You can check other issues also!
> 
> ok sir, will we be able to contribute to the same issue if it is in documentation format only?

Yeah, more than one contributors work on the same issue if the submission format is different! But in this case, it is only for Video.
