### ISSUE TITLE
JS: Conditional Statements in JavaScript

### ISSUE THREAD

**Issue by AbhinandanAdhikari** [girlscript/winter-of-contributing#942]
# Conditional Statements
Conditional Statements in JavaScript.

# Directory
```
Topics/5.Syntax/Conditionals
```
# Description
<li> What are Conditional Statements?
<li> Types of Conditional Statements in JavaScript.
<li> Give Example & Syntax of each conditional Statement in JavaScript.
<li> Tell about switch statement in JavaScript.
<li> Tell about ternary operator in JavaScript.

# Formats

- [x] Document
- [ ] Video
- [ ] Audio

**Comment by AbhinandanAdhikari** [comment]
> Hello @AbhinandanAdhikari,
> Thank you for opening an issue. :octocat:
> To get assigned to this particular issue please use /assign
> Check this [guide](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) before contributing.

/assign

**Comment by ayushijindal** [comment]
is this for HTML/CSS/JS

**Comment by AbhinandanAdhikari** [comment]
> is this for HTML/CSS/JS

No
Only for JavaScript Domain
