### ISSUE TITLE
Cybersecurity 1.9.5 Setup VirtualBox and Virtual Machine on Mac.

### ISSUE THREAD

**Issue by Anant1711** [girlscript/winter-of-contributing#95]
## Description
Show **How to set VirtualBox and Virtual machine in mac** through `screen-recording` and explain every step!
..

 
## Note:
- Submission should be in screen-recording format with an explanation.
- Changes should be made inside the `Cyber_Security/` directory & Cyber_Security branch.
- Task will be assigned on first come first serve
- Check it out [Contribution Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md)

**Comment by shubhdholakiya** [comment]
Can I work on this issue? Please assign this to me!

**Comment by Anant1711** [comment]
> Can I work on this issue? Please assign this to me!

Okay!
I'm assigning this task to you!

**Comment by shubhdholakiya** [comment]
Hello Sir,
I have reached pretty far and I think in a day or 2, I will make PR.

**Comment by Anant1711** [comment]
> Hello Sir,
> I have reached pretty far and I think in a day or 2, I will make PR.

Great!

**Comment by Anant1711** [comment]
@shubhdholakiya I didn't get any response from your side!
Are you ready with your `Video`?

**Comment by Anant1711** [comment]
@shubhdholakiya

**Comment by Nikita512** [comment]
@Anant1711 Can I make video for this issue?

**Comment by Anant1711** [comment]
> @Anant1711 Can I make video for this issue?

okay, Assigned!
You have to show How to do install virtual Box and any Virtual Machine on Mac!

**Comment by Anant1711** [comment]
> sir @Anant1711 can i work on that issue

Okay, I'm assigning this task to you!

**Comment by Anant1711** [comment]
> @Anant1711 sorry wasn't able to submit due to exams, can I submit now or should I look for other issue?

No issue, I assigned this task to someone else, You can choose other issue also!
