### ISSUE TITLE
Searching algorithms (Linear Search and Binary Search) - C_CPP 

### ISSUE THREAD

**Issue by pratyaksh1610** [girlscript/winter-of-contributing#975]
<hr>

## Description 📜

<p> Searching algorithms (Linear Search and Binary Search)</p>
<p> Documentation format</p>
<p>I will be working on this issue, explaining linear search and binary search in a detailed format with code samples and animations. </p>

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by pratyaksh1610** [comment]
Pratyaksh Khurana
C/C++ batch 9

**Comment by Saviour1001** [comment]
Closing this as the PR got merged !
