### ISSUE TITLE
Opensource: All about girlscript summer of code

### ISSUE THREAD

**Issue by siddhi-244** [girlscript/winter-of-contributing#982]
<hr>

## Description 📜

Opensource: All about girlscript summer of code
<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [x] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

**Comment by Aryamanz29** [comment]
Duplicate #293
