### ISSUE TITLE
A/B Testing_(D)

### ISSUE THREAD

**Issue by AdityaStark7** [girlscript/winter-of-contributing#984]
<hr>

## Description 📜

A/B Testing Statistics 

<hr>

## Domain of Contribution 📊

- [x] Machine Learning

<hr>

**Comment by Isha307** [comment]
> ## Description 📜
> A/B Testing Statistics
> 
> ## Domain of Contribution 📊
> * [ ]  Android Dev (Flutter, Java, Kotlin)
> * [ ]  Backend Dev (Java, .NET, Python)
> * [ ]  C/CPP
> * [ ]  Competitive Programming
> * [ ]  Cyber Security
> * [ ]  DSA
> * [ ]  Database
> * [ ]  Datascience with Python
> * [ ]  Datascience with R
> * [ ]  Frontend Dev (HTML, CSS, JS)
> * [ ]  Frontend Dev (React, Angular, Vue)
> * [ ]  Golang
> * [ ]  Interview Prep
> * [ ]  Java
> * [ ]  JavaScript
> * [ ]  MERN
> * [ ]  Machine Learning
> * [ ]  Open Source
> * [ ]  Python
> * [ ]  Rust
> * [ ]  Statistics
> * [ ]  UI/UX

Add your Batch Numbers, the approach one would follow and choice you prefer (Documentation, Audio, Video) or you can go with all three.
And also add your Name, github profile link.

**Comment by AdityaStark7** [comment]
Batch No. 03
Type: Documentation
Approach: Via Developing a Real Model for A/B Testing.

**Comment by Isha307** [comment]
Add your github profile link also, it would be better if you can edit your above comments :(

**Comment by AdityaStark7** [comment]
Name- Aditya Kumar
ML-Batch-3
Type: Documentation
github profile: https://github.com/AdityaStark7

**Comment by Aaksha-sharma** [comment]
Aaksha Sharma
Batch No. 03
Type: Documentation
Approach: Via Developing a Real Model for A/B Testing.
github link: https://github.com/Aaksha-sharma

**Comment by Isha307** [comment]
> Aaksha Sharma
> Batch No. 03
> Type: Documentation
> Approach: Via Developing a Real Model for A/B Testing.
> github link: https://github.com/Aaksha-sharma

@Aaksha-sharma This issue was already assigned to aditya, you can work on its video or audio part.

**Comment by Aaksha-sharma** [comment]
okay I would like to contribute in audio part how can I do it?

**Comment by Isha307** [comment]
Okay, let me create an issue for you.

**Comment by Isha307** [comment]
@Aaksha-sharma https://github.com/girlscript/winter-of-contributing/issues/1109
