### ISSUE TITLE
CPP: Introduction to OOPs - Classes & Objects

### ISSUE THREAD

**Issue by amankumar11** [girlscript/winter-of-contributing#987]
<hr>

## Description 📜

Covering classes and objects of programming in Introduction to OOPs. is there a requirement to cover all the 5 sub topics or can i do this single one only?

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

**Comment by SouravKr2001** [comment]
I am interested please assign it to me(documentation)

**Comment by amankumar11** [comment]
I have completed the documentation part and merged the pull request if any addition is asked to make we can by the mentor we can do it together @SouravKr2001

**Comment by Saviour1001** [comment]
Closing this issue as the PR got merged, you can open new issues !!

**Comment by SouravKr2001** [comment]
> I have completed the documentation part and merged the pull request if any addition is asked to make we can by the mentor we can do it together @SouravKr2001

Ok
