### ISSUE TITLE
MERN_React: 2.3 Basics of React.createElement() 

### ISSUE THREAD

**Issue by manjeetdhayal** [girlscript/winter-of-contributing#996]
<hr>

## Description 📜

# Instructions 

## Project directory
    Branch MERN>MERN/Topic/Frontend/React/ 

Please read the [contributing guidelines](https://github.com/girlscript/winter-of-contributing/blob/MERN/Web_Development/MERN/Contributing.md) to get started

## Why and What is React.createElement()?
Write a brief summary on what is React.createElement()? Why it is used and when to use it? Please refrain from coping from internet. You can use any source as inspiration. 

# Task 
- [ ] Audio
- [ ] Documentation
- [ ] Video

<hr>

## Domain of Contribution 📊

- [X] MERN

<hr>

**Comment by ayushjha952** [comment]
@manjeetdhayal can you assign this issue to me.
I would like to work on the documentation part.
Ayush Jha
Batch - 3

**Comment by VAISHNAVI0715** [comment]
@manjeetdhayal can you assign this issue to me.
I would like to work on the documentation part.
vaishnavi
Batch - 4

**Comment by SrijanShovit** [comment]
I would like to work on documentation part.
Batch - 3
Kindly assign this issue to me.
